Repository juju/juju, pull requests merged in 2020-06, with the labels that each got.

#11660 [2.7] A bunch of fixes to unblock CI
  .gitignore
  Gopkg.lock
  Gopkg.toml
  Makefile
  cmd/juju/commands/bootstrap_test.go
  cmd/jujud/agent/machine_test.go
  container/lxd/initialisation_test.go
  featuretests/remoterelations_test.go
  juju/testing/conn.go
  make_functions.sh
  state/upgrades_test.go
  tests/suites/static_analysis/lint_go.sh
  worker/certupdater/certupdater_test.go
Labels: 2.7

#11650 2.7 - Kill Test Workers with Thread-Safe gc.C
  container/lxd/initialisation_linux.go
  state/presence/pruner_test.go
Labels: 2.7

#11639 Unpin machine applications on destroy
  apiserver/facades/client/machinemanager/instance_information_test.go
  apiserver/facades/client/machinemanager/machinemanager.go
  apiserver/facades/client/machinemanager/machinemanager_test.go
  apiserver/facades/client/machinemanager/mocks/leadership_mock.go
  apiserver/facades/client/machinemanager/package_test.go
  mongo/mongo.go
  tests/suites/static_analysis/lint_go.sh
Labels: 2.7

#11638 2.7 - Hostname resolution in network-get omits loopback IPs
  worker/uniter/runner/jujuc/network-get.go
  worker/uniter/runner/jujuc/network-get_test.go
Labels: 2.7

#11657 2.7 Update Gorilla WebSocket Dependency
  Gopkg.lock
  Gopkg.toml
  Makefile
  api/apiclient.go
  cmd/jujud/agent/bootstrap_test.go
Labels: 2.7

#11684 Handle AWS bindings placements
  go.sum
  provider/ec2/context_mock_test.go
  provider/ec2/environ.go
  provider/ec2/environ_test.go
  provider/ec2/package_test.go
Labels: 2.8

#11681 fix typo in copyToPod debug logging
  caas/kubernetes/provider/exec/copy.go
Labels: 2.8

#11687 Show unit command
  api/application/client.go
  api/application/client_test.go
  api/facadeversions.go
  apiserver/allfacades.go
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/application_test.go
  apiserver/facades/client/application/application_unit_test.go
  apiserver/facades/client/application/backend.go
  apiserver/facades/client/application/export_test.go
  apiserver/facades/client/application/get_test.go
  apiserver/facades/client/application/mock_test.go
  apiserver/facades/schema.json
  apiserver/params/applications.go
  cmd/juju/application/export_test.go
  cmd/juju/application/show.go
  cmd/juju/application/showunit.go
  cmd/juju/application/showunit_test.go
  cmd/juju/commands/main.go
  cmd/juju/commands/main_test.go
  state/relation.go
  state/relationunit.go
  state/relationunit_test.go
Labels: 2.8

#11694 Fix/lp 1824465
  apiserver/facades/agent/uniter/uniter.go
  go.mod
  go.sum
  provider/azure/environ.go
  provider/azure/environ_test.go
  provider/azure/storage.go
Labels: 2.8, bug

#11695 Backport 11694
  Gopkg.lock
  apiserver/facades/agent/uniter/uniter.go
  provider/azure/environ.go
  provider/azure/environ_test.go
  provider/azure/storage.go
Labels: 2.7, bug

#11689 Generate schema docs
  .gitignore
  apiserver/facades/schema.json
  generate/schemagen/gen/describeapi_mock.go
  generate/schemagen/gen/generator.go
  generate/schemagen/gen/generator_test.go
  generate/schemagen/schemagen.go
  go.mod
  go.sum
  scripts/schemadocs/Makefile
  scripts/schemadocs/schemadocs.go
Labels: 2.8

#11696 Ensure dashboard is enabled on k8s bootstrap
  caas/jujud-operator-dockerfile
  caas/kubernetes/provider/bootstrap.go
  caas/kubernetes/provider/bootstrap_test.go
  cloudconfig/podcfg/podcfg.go
  cloudconfig/podcfg/podcfg_test.go
  environs/bootstrap/bootstrap.go
  environs/bootstrap/bootstrap_test.go
Labels: 2.8

#11703 The instance mutator worker ignores manually provisioned machines
  api/instancemutater/machine.go
  api/instancemutater/machine_test.go
  apiserver/facades/agent/instancemutater/instancemutater.go
  apiserver/facades/agent/instancemutater/instancemutater_test.go
  apiserver/facades/agent/instancemutater/interface.go
  apiserver/facades/agent/instancemutater/mocks/modelcache_mock.go
  core/cache/cachetest/state.go
  core/cache/changes.go
  core/cache/machine.go
  state/allwatcher.go
  state/machine.go
  state/multiwatcher/multiwatcher.go
  worker/instancemutater/mutater.go
  worker/instancemutater/worker_test.go
  worker/modelcache/worker.go
Labels: 2.7

#11705 Merge 2.7
  api/instancemutater/machine.go
  api/instancemutater/machine_test.go
  apiserver/facades/agent/instancemutater/instancemutater.go
  apiserver/facades/agent/instancemutater/instancemutater_test.go
  apiserver/facades/agent/instancemutater/interface.go
  apiserver/facades/agent/instancemutater/mocks/modelcache_mock.go
  apiserver/params/multiwatcher.go
  apiserver/watcher.go
  core/cache/cachetest/state.go
  core/cache/changes.go
  core/cache/machine.go
  core/multiwatcher/types.go
  state/allwatcher.go
  state/machine.go
  worker/instancemutater/mutater.go
  worker/instancemutater/worker_test.go
  worker/modelcache/worker.go
Labels: 2.8

#11700 Integration tests for lxd profiles
  tests/includes/wait-for.sh
  tests/suites/deploy/charms/lxd-profile-alt/README
  tests/suites/deploy/charms/lxd-profile-alt/config.yaml
  tests/suites/deploy/charms/lxd-profile-alt/hooks/install
  tests/suites/deploy/charms/lxd-profile-alt/hooks/start
  tests/suites/deploy/charms/lxd-profile-alt/hooks/update-status
  tests/suites/deploy/charms/lxd-profile-alt/hooks/upgrade-charm
  tests/suites/deploy/charms/lxd-profile-alt/icon.svg
  tests/suites/deploy/charms/lxd-profile-alt/lxd-profile.yaml
  tests/suites/deploy/charms/lxd-profile-alt/metadata.yaml
  tests/suites/deploy/deploy_bundles.sh
  tests/suites/deploy/deploy_charms.sh
Labels: 2.8

#11683 2.8 - Populate Link-Layer Device Origin from Instance Poller
  apiserver/facades/controller/instancepoller/export_test.go
  apiserver/facades/controller/instancepoller/instancepoller.go
  apiserver/facades/controller/instancepoller/instancepoller_test.go
  apiserver/facades/controller/instancepoller/merge.go
  apiserver/facades/controller/instancepoller/mock_test.go
  apiserver/facades/controller/instancepoller/package_mock_test.go
  apiserver/facades/controller/instancepoller/package_test.go
  apiserver/facades/controller/instancepoller/state.go
  apiserver/facades/schema.json
  state/application_test.go
  state/database.go
  state/export_test.go
  state/ipaddresses_test.go
  state/linklayerdevices.go
  state/linklayerdevices_ipaddresses.go
  state/linklayerdevices_test.go
  state/machine.go
  state/machine_linklayerdevices.go
  state/machine_test.go
  state/package_test.go
  state/state_test.go
Labels: 2.8

#11701 ensure lxd profiles applied before hooks run during install and upgrade
  api/facadeversions.go
  api/uniter/charm.go
  api/uniter/charm_test.go
  api/uniter/unit.go
  api/uniter/unit_test.go
  apiserver/allfacades.go
  apiserver/facades/agent/uniter/lxdprofile.go
  apiserver/facades/agent/uniter/mocks/newlxdprofile.go
  apiserver/facades/agent/uniter/newlxdprofile.go
  apiserver/facades/agent/uniter/newlxdprofile_test.go
  apiserver/facades/agent/uniter/package_test.go
  apiserver/facades/agent/uniter/uniter.go
  apiserver/facades/client/machinemanager/package_test.go
  apiserver/facades/schema.json
  caas/kubernetes/provider/specs/builder.go
  container/lxd/initialisation_linux.go
  state/machine_test.go
  state/state_test.go
  state/watcher.go
  worker/caasoperator/download.go
  worker/instancemutater/mutater.go
  worker/provisioner/provisioner_test.go
  worker/uniter/remotestate/mock_test.go
  worker/uniter/remotestate/snapshot.go
  worker/uniter/remotestate/state.go
  worker/uniter/remotestate/watcher.go
  worker/uniter/remotestate/watcher_test.go
  worker/uniter/resolver.go
  worker/uniter/resolver_test.go
  worker/uniter/uniter.go
  worker/uniter/uniter_test.go
  worker/uniter/util_test.go
  worker/uniter/verifycharmprofile/package_test.go
  worker/uniter/verifycharmprofile/verifycharmprofile.go
  worker/uniter/verifycharmprofile/verifycharmprofile_test.go
Labels: 2.8

#11715 Handle idle condition correctly
  tests/includes/juju.sh
  tests/includes/wait-for.sh
  tests/suites/agents/key_workers_run.sh
  tests/suites/agents/task.sh
  tests/suites/appdata/appdata.sh
  tests/suites/appdata/task.sh
  tests/suites/branches/active_branch.sh
  tests/suites/branches/branches.sh
  tests/suites/branches/task.sh
  tests/suites/cli/local_charms.sh
  tests/suites/cli/task.sh
  tests/suites/controller/mongo_memory_profile.sh
  tests/suites/controller/task.sh
  tests/suites/deploy/charms/lxd-profile-alt/lxd-profile.yaml
  tests/suites/deploy/deploy_bundles.sh
  tests/suites/deploy/deploy_charms.sh
  tests/suites/deploy/export_overlay.sh
  tests/suites/deploy/task.sh
  tests/suites/examples/example.sh
  tests/suites/examples/other.sh
  tests/suites/examples/task.sh
  tests/suites/hooks/dispatch.sh
  tests/suites/hooks/reboot.sh
  tests/suites/hooks/task.sh
  tests/suites/hooktools/state_tools.sh
  tests/suites/hooktools/task.sh
  tests/suites/machine/machine.sh
  tests/suites/machine/task.sh
  tests/suites/manual/deploy_manual.sh
  tests/suites/model/model_migration.sh
  tests/suites/model/task.sh
  tests/suites/relations/relation_data_exchange.sh
  tests/suites/relations/relation_departing_unit.sh
  tests/suites/relations/task.sh
  tests/suites/smoke/task.sh
  tests/suites/spaces_ec2/juju_bind.sh
  tests/suites/spaces_ec2/task.sh
  tests/suites/spaces_ec2/upgrade_charm_with_bind.sh
Labels: 2.8

#11706 Do not set controller link-layer data out-of-band
  api/facadeversions.go
  api/machiner/machine.go
  apiserver/allfacades.go
  apiserver/common/networkingcommon/networkconfigapi.go
  apiserver/common/networkingcommon/networkconfigapi_test.go
  apiserver/facades/agent/machine/machiner.go
  apiserver/facades/schema.json
  cmd/jujud/agent/machine.go
Labels: 2.8

#11726 Upgrade Step for Link-Layer Devices Named "unsupportedx"
  state/upgrades.go
  state/upgrades_test.go
  upgrades/backend.go
  upgrades/operations.go
  upgrades/sets_281_test.go
  upgrades/steps_28.go
  upgrades/steps_281.go
  upgrades/steps_28_test.go
  upgrades/upgrade_test.go
Labels: 2.8

#11671 Removes some static nature of model controller
  apiserver/facades/agent/logger/logger.go
  caas/kubernetes/provider/modeloperator.go
  cmd/jujud/agent/model.go
  cmd/jujud/agent/modeloperator/manifolds.go
  worker/caasadmission/controller.go
  worker/caasadmission/manifold.go
  worker/muxhttpserver/manifold.go
  worker/muxhttpserver/server.go
Labels: 2.8

#11744 Migrate Additional IP Address Fields
  go.mod
  go.sum
  state/migration_export.go
  state/migration_export_test.go
  state/migration_import.go
  state/migration_import_test.go
Labels: 2.8

#11745 Remove Method: SetDevicesAddressesIdempotently
  apiserver/common/networkingcommon/networkconfigapi.go
  state/ipaddresses_test.go
  state/machine.go
  state/machine_internal_test.go
  state/machine_linklayerdevices.go
Labels: 2.8

#11749 Network health integration test
  tests/includes/wait-for.sh
  tests/suites/network/network_health.sh
  tests/suites/network/task.sh
Labels: 2.8

#11753 Common Base for Link-Layer Update Model Operations
  apiserver/common/networkingcommon/linklayer.go
  apiserver/facades/controller/instancepoller/instancepoller_test.go
  apiserver/facades/controller/instancepoller/merge.go
  apiserver/facades/controller/instancepoller/mock_test.go
  apiserver/facades/controller/instancepoller/package_mock_test.go
  apiserver/facades/controller/instancepoller/package_test.go
  apiserver/facades/controller/instancepoller/state.go
Labels: 2.8

#11758 Fix test race in the instancemutater worker
  worker/instancemutater/worker_test.go
Labels: 2.8

#11763 [2.8] Display channel when upgrading charm
  cmd/juju/application/upgradecharm.go
Labels: 2.8

#11764 Handle series upgrade for machine upgraded out-of-band
  api/facadeversions.go
  api/upgradeseries/upgradeseries.go
  api/upgradeseries/upgradeseries_test.go
  apiserver/allfacades.go
  apiserver/facades/agent/upgradeseries/upgradeseries.go
  apiserver/facades/agent/upgradeseries/upgradeseries_test.go
  apiserver/facades/client/spaces/spaces.go
  apiserver/facades/schema.json
  service/agentconf.go
  service/agentconf_test.go
  worker/upgradeseries/manifold.go
  worker/upgradeseries/mocks/package_mock.go
  worker/upgradeseries/shim.go
  worker/upgradeseries/upgrader.go
  worker/upgradeseries/upgrader_test.go
  worker/upgradeseries/worker.go
  worker/upgradeseries/worker_test.go
Labels: 2.8

#11765 [2.8] Enable relation-list tool to list remote (or peer) application
  tests/main.sh
  tests/suites/relations/relation_list_app.sh
  tests/suites/relations/task.sh
  worker/uniter/runner/context/relation.go
  worker/uniter/runner/context/relation_test.go
  worker/uniter/runner/jujuc/context.go
  worker/uniter/runner/jujuc/context_mock_test.go
  worker/uniter/runner/jujuc/jujuctesting/relation.go
  worker/uniter/runner/jujuc/mocks/context_mock.go
  worker/uniter/runner/jujuc/relation-list.go
  worker/uniter/runner/jujuc/relation-list_test.go
  worker/uniter/runner/jujuc/relation_test.go
Labels: 2.8

#11778 Instance Poller - Remove Provider IDs for Unobserved Link-Layer Devices
  apiserver/facades/controller/instancepoller/instancepoller_test.go
  apiserver/facades/controller/instancepoller/merge.go
  state/linklayerdevices.go
  state/linklayerdevices_test.go
Labels: 2.8
