Repository juju/juju, pull requests merged in 2020-10, with the labels that each got.

#12083 Pin the transent dependency (2.8.4)
  caas/jujud-operator-requirements.txt
Labels: 2.8

#12089 Merge 2.8.4 into 2.8
  caas/jujud-operator-requirements.txt
  scripts/win-installer/setup.iss
  snap/snapcraft.yaml
  version/version.go
Labels: 2.8

#12093 Fix the validate model upgrade from a facade
  cmd/juju/commands/upgrademodel.go
  cmd/juju/commands/upgrademodel_test.go
Labels: 2.8, bug

#12067 Correct scoping in network-get to ensure public-first address sorting
  apiserver/facades/agent/uniter/networkinfo.go
  apiserver/facades/agent/uniter/networkinfo_test.go
Labels: 2.8

#12119 Annotate error return from AllLinkLayerDevices
  state/linklayerdevices.go
Labels: 2.8

#12132 Upgrade step to remove unused link-layer device provider IDs
  state/upgrades.go
  state/upgrades_test.go
  upgrades/backend.go
  upgrades/operations.go
  upgrades/steps_286.go
  upgrades/steps_286_test.go
  upgrades/upgrade_test.go
Labels: 2.8

#12133 Add an index to the linklayerdevices collection
  state/allcollections.go
  state/linklayerdevices_test.go
Labels: 2.8

#12094 Fix bug #1887549: Check args.AgentVersion in bootstrapCAAS
  environs/bootstrap/bootstrap.go
Labels: 2.8

#12098 [wait-for] Allow unit queries
  cmd/plugins/juju-wait-for/application.go
  cmd/plugins/juju-wait-for/application_test.go
  cmd/plugins/juju-wait-for/machine.go
  cmd/plugins/juju-wait-for/machine_test.go
  cmd/plugins/juju-wait-for/model.go
  cmd/plugins/juju-wait-for/model_test.go
  cmd/plugins/juju-wait-for/query/query.go
  cmd/plugins/juju-wait-for/strategy.go
  cmd/plugins/juju-wait-for/strategy_test.go
  cmd/plugins/juju-wait-for/unit.go
  cmd/plugins/juju-wait-for/unit_test.go
  cmd/plugins/juju-wait-for/waitfor.go
Labels: wait-for

#12128 [wait-for] Map queries
  cmd/plugins/juju-wait-for/application.go
  cmd/plugins/juju-wait-for/machine.go
  cmd/plugins/juju-wait-for/model.go
  cmd/plugins/juju-wait-for/query/ast.go
  cmd/plugins/juju-wait-for/query/errors.go
  cmd/plugins/juju-wait-for/query/lexer_test.go
  cmd/plugins/juju-wait-for/query/ord.go
  cmd/plugins/juju-wait-for/query/package_test.go
  cmd/plugins/juju-wait-for/query/parser.go
  cmd/plugins/juju-wait-for/query/query.go
  cmd/plugins/juju-wait-for/query/query_test.go
  cmd/plugins/juju-wait-for/query/scope.go
  cmd/plugins/juju-wait-for/query/scope_mock_test.go
  cmd/plugins/juju-wait-for/query/testfiles/failure
  cmd/plugins/juju-wait-for/query/testfiles/success
  cmd/plugins/juju-wait-for/query/token.go
  cmd/plugins/juju-wait-for/strategy.go
  cmd/plugins/juju-wait-for/unit.go
  cmd/plugins/juju-wait-for/waitforbase.go
Labels: wait-for

#12203 Fix add-machine error return
  api/machinemanager/machinemanager.go
  api/machinemanager/machinemanager_test.go
Labels: 2.8

#12214 Raft trace log detail
  cmd/jujud/agent/machine/manifolds.go
  core/raftlease/fsm.go
  core/raftlease/store.go
Labels: 2.8
