Repository juju/juju, pull requests merged in 2020-12, with the labels that each got.

#12383 LXD disk and architecture constraints
  container/lxd/container.go
  container/lxd/manager.go
  container/lxd/network.go
  container/lxd/network_test.go
  container/lxd/server.go
  container/lxd/testing/lxd_mock.go
  go.mod
  go.sum
  provider/lxd/environ_broker.go
  provider/lxd/environ_policy.go
  provider/lxd/environ_policy_test.go
  provider/lxd/server.go
  provider/lxd/server_mock_test.go
  provider/lxd/testing_test.go
Labels: 2.9

#12393 Fix time.After usage causing memory leaks.
  core/cache/controller.go
  state/watcher/hubwatcher.go
  worker/peergrouper/worker.go
  worker/state/manifold.go
Labels: 2.9

#12396 Not found charm error message
  cmd/juju/application/deploy.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/deployer.go
  cmd/juju/application/deployer/deployer_test.go
Labels: 2.9

#12395 Deploy charmhub bundle with charmhub charms
  apiserver/facades/client/charms/client.go
  apiserver/facades/client/charms/interfaces/state.go
  apiserver/facades/client/charms/mocks/state_mock.go
  apiserver/facades/client/charms/repositories.go
  apiserver/facades/client/charms/repositories_test.go
  cmd/juju/application/deployer/bundlehandler.go
  core/charm/channel.go
  testcharms/charm-hub/bundles/wordpress-simple/bundle.yaml
Labels: 2.9

#12419 Ensure NetworksForRelation never returns a CAAS container address
  apiserver/facades/agent/uniter/networkinfo.go
  apiserver/facades/agent/uniter/networkinfo_test.go
  apiserver/facades/agent/uniter/networkinfocaas.go
  apiserver/facades/agent/uniter/networkinfoiaas.go
Labels: 2.9

#12429 Remove dead test code and check errors
  api/upgrader/upgrader_test.go
  juju/testing/conn.go
Labels: 2.8

#12438 Do not resolve ingress address host-names for CAAS unit network-get calls
  apiserver/facades/agent/uniter/networkinfo.go
  apiserver/facades/agent/uniter/networkinfo_test.go
  apiserver/facades/agent/uniter/networkinfocaas.go
  apiserver/facades/agent/uniter/networkinfoiaas.go
Labels: 2.9

#12406 Feature/ecs provider
  agent/agentbootstrap/bootstrap.go
  caas/ecs/api.go
  caas/ecs/application.go
  caas/ecs/application_test.go
  caas/ecs/base_test.go
  caas/ecs/bootstrap.go
  caas/ecs/cloud.go
  caas/ecs/constants/constants.go
  caas/ecs/constraints.go
  caas/ecs/constraints_test.go
  caas/ecs/credentials.go
  caas/ecs/credentials_test.go
  caas/ecs/environ.go
  caas/ecs/environ_test.go
  caas/ecs/export_test.go
  caas/ecs/init.go
  caas/ecs/mocks/ecs_mock.go
  caas/ecs/package_test.go
  caas/ecs/provider.go
  caas/ecs/provider_test.go
  caas/ecs/storage.go
  caas/ecs/storage_test.go
  caas/ecs/watcher.go
  caas/ecs/watcher_test.go
  caas/kubernetes/provider/application/application.go
  caas/kubernetes/provider/builtin.go
  caas/kubernetes/provider/builtin_test.go
  caas/kubernetes/provider/cloud_test.go
  cloud/clouds.go
  cloud/clouds_test.go
  cloud/fallback-public-cloud.yaml
  cloud/fallback_public_cloud.go
  cmd/juju/commands/bootstrap_test.go
  cmd/juju/controller/destroy.go
  cmd/juju/controller/kill.go
  cmd/k8sagent/.gitignore
  go.mod
  go.sum
  provider/all/ecs.go
  state/model.go
  state/model_test.go
  worker/caasapplicationprovisioner/application.go
  worker/caasapplicationprovisioner/manifold.go
  worker/caasapplicationprovisioner/worker.go
Labels: 3.0, feature

#12446 Ensure origin with non-empty architecture for local charms
  apiserver/facades/client/application/deploy.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/charm.go
  cmd/juju/application/utils/origin.go
Labels: 2.9
