Repository juju/juju, pull requests merged in 2021-09, with the labels that each got.

#13286 Fix reportHookError blocking when relation hook fails due to missing relation
  worker/uniter/relation/statetracker.go
  worker/uniter/uniter.go
  worker/uniter/uniter_test.go
  worker/uniter/util_test.go
Labels: 2.9

#12569 Update contribution guide, with additional info on Go and Mongo versions
  CONTRIBUTING.md
Labels: 2.9

#13260 [dev] Implement async charm downloads
  api/charmdownloader/client.go
  api/facadeversions.go
  apiserver/allfacades.go
  apiserver/charms.go
  apiserver/charms_test.go
  apiserver/errors/errors.go
  apiserver/errors/errors_test.go
  apiserver/facades/client/charms/client.go
  apiserver/facades/client/charms/client_test.go
  apiserver/facades/client/charms/interfaces/state.go
  apiserver/facades/client/charms/mocks/repository.go
  apiserver/facades/client/charms/mocks/state_mock.go
  apiserver/facades/client/charms/package_test.go
  apiserver/facades/controller/charmdownloader/charmdownloader.go
  apiserver/facades/controller/charmdownloader/charmdownloader_test.go
  apiserver/facades/controller/charmdownloader/interfaces.go
  apiserver/facades/controller/charmdownloader/mock_watcher.go
  apiserver/facades/controller/charmdownloader/mocks.go
  apiserver/facades/controller/charmdownloader/package_test.go
  apiserver/facades/controller/charmdownloader/shims.go
  apiserver/facades/schema.json
  apiserver/params/apierror.go
  cmd/jujud/agent/engine_test.go
  cmd/jujud/agent/model/manifolds.go
  cmd/jujud/agent/model/manifolds_test.go
  downloader/downloader_test.go
  downloader/utils.go
  feature/flags.go
  go.mod
  go.sum
  state/application.go
  state/application_test.go
  state/charm.go
  state/charm_test.go
  state/watcher.go
  worker/charmdownloader/charmdownloader.go
  worker/charmdownloader/charmdownloader_test.go
  worker/charmdownloader/interfaces.go
  worker/charmdownloader/manifold.go
  worker/charmdownloader/manifold_test.go
  worker/charmdownloader/mock_watcher.go
  worker/charmdownloader/mocks.go
  worker/charmdownloader/package_test.go
  worker/uniter/charm/manifest_deployer.go
  worker/uniter/charm/manifest_deployer_test.go
  worker/uniter/charm/mocks/mocks.go
  worker/uniter/charm/package_test.go
Labels: 3.0

#13292 [2.9] Use CIDR-in-CIDR fallback when matching machine address CIDRs to subnet CIDRs
  core/network/subnet.go
  core/network/subnet_test.go
Labels: 2.9

#13295 Deploy by rev origin if already downloaded
  apiserver/facades/client/application/updateseries_test.go
  apiserver/facades/client/client/testing/suite.go
  apiserver/facades/client/machinemanager/upgradeseries_test.go
  apiserver/facades/client/resources/base_test.go
  apiserver/facades/client/resources/facade.go
  apiserver/facades/client/resources/mocks/logger.go
  apiserver/facades/client/resources/repository.go
  apiserver/facades/client/resources/repository_test.go
  apiserver/facades/client/resources/server_test.go
  apiserver/facades/controller/charmrevisionupdater/updater.go
  charmhub/refresh.go
  charmhub/refresh_test.go
  core/charm/downloader/downloader.go
  core/charm/downloader/downloader_mocks.go
  core/charm/downloader/downloader_test.go
  resource/resourceadapters/charmhub_test.go
Labels: 3.0

#13291 fix bundle loop caused by recent change sort algorithm updates.
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/bundlehandler_test.go
  core/bundle/changes/changes.go
  core/bundle/changes/changes_test.go
  core/bundle/changes/package_test.go
Labels: 3.0

#13293 Record secret rotation config and add watcher infrastructure
  api/facadeversions.go
  api/secrets/client.go
  api/secretsmanager/client.go
  api/secretsmanager/client_test.go
  api/watcher/watcher.go
  api/watcher/watcher_test.go
  apiserver/allfacades.go
  apiserver/facades/agent/secretsmanager/access.go
  apiserver/facades/agent/secretsmanager/mocks/secretsrotationwatcher.go
  apiserver/facades/agent/secretsmanager/mocks/secretswatcherservice.go
  apiserver/facades/agent/secretsmanager/package_test.go
  apiserver/facades/agent/secretsmanager/secrets.go
  apiserver/facades/agent/secretsmanager/secrets_test.go
  apiserver/facades/agent/secretsmanager/state.go
  apiserver/facades/schema.json
  apiserver/params/secrets.go
  apiserver/restrict_caasmodel.go
  apiserver/watcher.go
  cmd/containeragent/initialize/package_test.go
  cmd/containeragent/unit/package_test.go
  core/watcher/package_test.go
  core/watcher/secrets.go
  state/allcollections.go
  state/migration_internal_test.go
  state/secrets.go
  state/secrets_test.go
  state/testing/watcher.go
Labels: 2.9

#13312 Remove unnecessary txn watcher started channel/topic
  state/machine_ports_test.go
  state/pool.go
  state/watcher/hubwatcher.go
  state/watcher/txnwatcher.go
  state/watcher/txnwatcher_test.go
Labels: 2.9

#13221 Status watch flag
  cmd/juju/status/status.go
  cmd/juju/status/status_test.go
Labels: 2.9

#13315 Use a lxc client library helper to detect Not Found errors
  container/lxd/container_test.go
  container/lxd/image_test.go
  container/lxd/mocks/clock_mock.go
  container/lxd/mocks/snap_manager_mock.go
  container/lxd/network_test.go
  container/lxd/server.go
  container/lxd/testing/lxd_mock.go
  go.mod
  go.sum
  provider/lxd/credentials_test.go
Labels: 2.9

#13311 Be more lenient if the charm dir is deleted after a relation is joined
  worker/caasoperator/caasoperator.go
  worker/uniter/hook/hook.go
  worker/uniter/relation/relationer.go
  worker/uniter/relation/resolver.go
  worker/uniter/relation/state.go
  worker/uniter/relation/state_test.go
  worker/uniter/relation/statetracker.go
  worker/uniter/relation/statetracker_test.go
Labels: 2.9

#13316 Don't use GroupName when opening ports on AWS
  provider/ec2/environ.go
Labels: 2.9

#13301 deploy by revision integration tests
  tests/suites/deploy/deploy_bundles.sh
  tests/suites/deploy/deploy_revision.sh
  tests/suites/deploy/task.sh
Labels: 3.0

#13314 Securely handle /etc/snap.assertions
  cloudconfig/cloudinit/cloudinit_ubuntu.go
Labels: 2.9

#13318 Add test to ec2 + ensure ec2 SecurityGroup mutates use only group id
  provider/ec2/environ.go
  provider/ec2/internal/testing/securty_groups.go
  provider/ec2/local_test.go
Labels: 2.9

#13194 Replace missing links.
  README.md
Labels: 2.9

#13320 Revert LXD changes
  container/lxd/container_test.go
  container/lxd/image_test.go
  container/lxd/mocks/clock_mock.go
  container/lxd/mocks/snap_manager_mock.go
  container/lxd/network_test.go
  container/lxd/server.go
  container/lxd/testing/lxd_mock.go
  go.mod
  go.sum
  provider/lxd/credentials_test.go
Labels: 2.9

#13319 Apply Fan subnet fixes to Address collection in incoming network configuration
  apiserver/common/networkingcommon/networkconfigapi.go
  apiserver/common/networkingcommon/networkconfigapi_test.go
  network/containerizer/bridgepolicy.go
Labels: 2.9

#13274 Network devices from config host_name
  container/lxd/export_test.go
  container/lxd/manager.go
  container/lxd/manager_test.go
  container/lxd/network.go
  container/lxd/network_test.go
Labels: 2.9

#13325 Raft worker errors
  worker/raft/worker.go
Labels: 2.9

#13328 Fix assess_upgrade_series again
  acceptancetests/assess_upgrade_series.py
  tests/main.sh
Labels: 2.9

#13324 [2.9] Add OVS integration test
  tests/includes/juju.sh
  tests/main.sh
  tests/suites/ovs_maas/ovs_netplan_config.sh
  tests/suites/ovs_maas/task.sh
Labels: 2.9

#13330 Protect fakeStatusAPI.errors from concurrent access
  api/monitor_internal_test.go
  cmd/juju/status/status_test.go
Labels: 2.9

#13326 deploy by revision: deploy and export bundles with revision tag.
  apiserver/facades/client/bundle/bundle.go
  apiserver/facades/client/bundle/bundle_test.go
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/bundlehandler_test.go
  core/bundle/changes/changes.go
  core/bundle/changes/changes_test.go
  core/bundle/changes/handlers.go
  core/bundle/changes/handlers_test.go
  core/bundle/changes/model.go
  core/bundle/changes/model_test.go
  featuretests/cmd_juju_bundle_test.go
  go.mod
  go.sum
Labels: feature, 3.0

#13331 Add worker to watch for when to rotate secrets and notify unit agent
  worker/leadership/tracker.go
  worker/secretrotate/mocks/client_mock.go
  worker/secretrotate/mocks/watcher_mock.go
  worker/secretrotate/package_test.go
  worker/secretrotate/secretrotate.go
  worker/secretrotate/secretrotate_test.go
  worker/uniter/manifold.go
  worker/uniter/remotestate/mock_test.go
  worker/uniter/remotestate/watcher.go
  worker/uniter/remotestate/watcher_test.go
  worker/uniter/uniter.go
  worker/uniter/util_test.go
Labels: 2.9

#13333 Raft queue: Blocking queue
  worker/raft/queue/blockingqueue.go
  worker/raft/queue/blockingqueue_test.go
  worker/raft/queue/package_test.go
  worker/secretrotate/secretrotate_test.go
Labels: 2.9

#13335 Ensure secrets worker and facade are set up properly on k8s.
  apiserver/facades/agent/secretsmanager/access.go
  apiserver/facades/agent/secretsmanager/package_test.go
  apiserver/facades/agent/secretsmanager/secrets.go
  apiserver/facades/agent/secretsmanager/secrets_test.go
  apiserver/facades/schema.json
  worker/caasoperator/manifold.go
  worker/caasoperator/manifold_test.go
Labels: 2.9

#13337 Filter on offer uuid when processing offer relations on removal of an offer
  state/applicationoffers.go
  state/applicationoffers_test.go
Labels: 2.9

#13339 Implement secret-rotate hook
  api/secretsmanager/client.go
  api/secretsmanager/client_test.go
  apiserver/facades/agent/secretsmanager/mocks/secretsrotationservice.go
  apiserver/facades/agent/secretsmanager/mocks/secretswatcherservice.go
  apiserver/facades/agent/secretsmanager/package_test.go
  apiserver/facades/agent/secretsmanager/secrets.go
  apiserver/facades/agent/secretsmanager/secrets_test.go
  apiserver/facades/agent/secretsmanager/state.go
  apiserver/facades/schema.json
  apiserver/params/secrets.go
  caas/kubernetes/provider/application/application.go
  caas/kubernetes/provider/bootstrap.go
  caas/kubernetes/provider/bootstrap_test.go
  caas/kubernetes/provider/operator.go
  caas/kubernetes/provider/operator_test.go
  cmd/containeragent/main_nix.go
  cmd/juju/secrets/list_test.go
  core/secrets/secret.go
  core/secrets/secret_test.go
  go.mod
  go.sum
  state/export_test.go
  state/secrets.go
  state/secrets_test.go
  worker/uniter/hook/hook.go
  worker/uniter/hook/hook_test.go
  worker/uniter/op_callbacks.go
  worker/uniter/operation/interface.go
  worker/uniter/operation/mocks/interface_mock.go
  worker/uniter/operation/mocks/uniterstaterw_mock.go
  worker/uniter/operation/remoteinit_test.go
  worker/uniter/operation/runhook.go
  worker/uniter/operation/runhook_test.go
  worker/uniter/operation/util_test.go
  worker/uniter/remotestate/snapshot.go
  worker/uniter/remotestate/watcher.go
  worker/uniter/remotestate/watcher_test.go
  worker/uniter/resolver.go
  worker/uniter/resolver_test.go
  worker/uniter/runner/context/context.go
  worker/uniter/runner/context/context_test.go
  worker/uniter/runner/context/contextfactory.go
  worker/uniter/runner/context/contextfactory_test.go
  worker/uniter/runner/context/env_test.go
  worker/uniter/runner/context/export_test.go
  worker/uniter/runner/context/util_test.go
  worker/uniter/runner/jujuc/secret-get.go
  worker/uniter/secrets/package_test.go
  worker/uniter/secrets/rotatesecrets.go
  worker/uniter/secrets/rotatesecrets_test.go
  worker/uniter/uniter.go
  worker/uniter/uniter_test.go
  worker/uniter/util_test.go
Labels: 2.9

#13334 Raft apply operation
  agent/agentbootstrap/bootstrap.go
  cmd/jujud/agent/machine.go
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/agent/machine_test.go
  cmd/jujud/agent/util_test.go
  worker/raft/apply.go
  worker/raft/apply_test.go
  worker/raft/errors.go
  worker/raft/manifold.go
  worker/raft/manifold_test.go
  worker/raft/mock_test.go
  worker/raft/package_test.go
  worker/raft/queue/blockingqueue.go
  worker/raft/queue/blockingqueue_test.go
  worker/raft/raft_future_mock_test.go
  worker/raft/raft_mock_test.go
  worker/raft/raftlease_mock_test.go
  worker/raft/worker.go
  worker/raft/worker_test.go
Labels: 2.9

#13338 new charmhub metrics: replace current method with new and use for current metrics.
  apiserver/common/charmhub.go
  apiserver/facades/client/client/status_test.go
  apiserver/facades/controller/charmrevisionupdater/charmhub.go
  apiserver/facades/controller/charmrevisionupdater/interface.go
  apiserver/facades/controller/charmrevisionupdater/interface_test.go
  apiserver/facades/controller/charmrevisionupdater/mocks/mocks.go
  apiserver/facades/controller/charmrevisionupdater/updater.go
  apiserver/facades/controller/charmrevisionupdater/updater_test.go
  charmhub/client.go
  charmhub/refresh.go
  charmhub/refresh_test.go
  charmhub/refreshconfig.go
  charmhub/transport/refresh.go
  cmd/containeragent/initialize/package_test.go
  core/charm/metrics/metrics.go
  state/model.go
  state/model_test.go
Labels: feature, 3.0

#13302 Work on adding support for AWS instance profiles
  apiserver/facades/schema.json
  core/constraints/constraints.go
  core/constraints/constraints_test.go
  go.mod
  go.sum
  provider/ec2/client.go
  provider/ec2/config.go
  provider/ec2/environ.go
  provider/ec2/iam.go
  provider/ec2/iam_test.go
  provider/ec2/internal/testing/instances.go
Labels: 2.9

#13345 Restart cmr workers after offer has been removed
  apiserver/common/unitcommon/accessor.go
  apiserver/common/unitcommon/accessor_test.go
  apiserver/facades/agent/uniter/uniter.go
  apiserver/facades/agent/uniter/uniter_test.go
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/application_test.go
  apiserver/facades/client/application/application_unit_test.go
  apiserver/facades/client/application/backend.go
  apiserver/facades/client/application/mock_test.go
  apiserver/facades/client/applicationoffers/applicationoffers.go
  apiserver/facades/client/applicationoffers/applicationoffers_test.go
  apiserver/facades/controller/crossmodelrelations/mock_test.go
  apiserver/facades/controller/remoterelations/mock_test.go
  apiserver/rest_test.go
  cmd/juju/application/consume.go
  cmd/juju/application/deployer/bundlehandler.go
  featuretests/cmd_juju_crossmodel_test.go
  state/allwatcher.go
  state/applicationoffers.go
  state/applicationoffers_test.go
  state/export_test.go
  state/relation.go
  state/relationunit_test.go
  state/remoteapplication.go
  state/remoteapplication_test.go
  state/state.go
  state/state_test.go
  worker/remoterelations/mock_test.go
  worker/remoterelations/remoteapplicationworker.go
  worker/remoterelations/remoterelations.go
  worker/remoterelations/remoterelations_test.go
  worker/uniter/runner/context/context.go
  worker/uniter/runner/jujuc/jujuctesting/relationhook.go
Labels: 2.9

#13344 Fix assess_model_migration_versions
  acceptancetests/assess_model_migration.py
  acceptancetests/assess_model_migration_versions.py
  acceptancetests/deploy_stack.py
  acceptancetests/jujupy/client.py
  acceptancetests/jujupy/tests/test_client.py
Labels: 2.9

#13342 APIServer: Raft context
  agent/agentbootstrap/bootstrap.go
  api/facadeversions.go
  apiserver/allfacades.go
  apiserver/apiserver.go
  apiserver/apiserver_test.go
  apiserver/errors/errors.go
  apiserver/errors/errors_test.go
  apiserver/errors/types.go
  apiserver/facade/facadetest/context.go
  apiserver/facade/interface.go
  apiserver/facades/client/charms/client_test.go
  apiserver/facades/controller/caasmodelconfigmanager/mocks/context_mock.go
  apiserver/facades/controller/raftlease/facade.go
  apiserver/facades/controller/raftlease/facade_test.go
  apiserver/facades/controller/raftlease/package_test.go
  apiserver/facades/controller/raftlease/raft_mock_test.go
  apiserver/facades/schema.json
  apiserver/params/apierror.go
  apiserver/params/params.go
  apiserver/raft.go
  apiserver/raft_test.go
  apiserver/root.go
  apiserver/shared.go
  apiserver/shared_test.go
  apiserver/testserver/server.go
  cmd/jujud/agent/machine.go
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/agent/machine_test.go
  core/raft/queue/blockingqueue.go
  core/raft/queue/blockingqueue_test.go
  core/raft/queue/package_test.go
  provider/dummy/environs.go
  worker/apiserver/manifold.go
  worker/apiserver/manifold_test.go
  worker/apiserver/worker.go
  worker/apiserver/worker_state_test.go
  worker/apiserver/worker_test.go
  worker/raft/apply.go
  worker/raft/apply_test.go
  worker/raft/manifold_test.go
  worker/raft/worker.go
  worker/raft/worker_test.go
Labels: 2.9

#13119 Logs: Ensure we close goroutine on cancel
  api/client.go
  api/common/logs.go
  api/migrationmaster/client.go
  api/migrationmaster/client_test.go
  worker/migrationmaster/worker.go
  worker/migrationmaster/worker_test.go
Labels: 2.9

#13346 Raft API Client
  api/pubsub/package_test.go
  api/pubsub/pubsub_test.go
  api/raftlease/client.go
  api/raftlease/client_test.go
  api/raftlease/package_test.go
  api/raftlease/raftlease.go
  api/raftlease/raftlease_test.go
  api/raftlease/remote_mock.go
Labels: 2.9

#13353 Tweaks to make consuming cmr offers more robust
  apiserver/common/crossmodel/crossmodel.go
  apiserver/common/crossmodel/interface.go
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/application_unit_test.go
  apiserver/facades/client/application/backend.go
  apiserver/facades/client/application/mock_test.go
  state/applicationoffers.go
  state/relation.go
  state/remoteapplication.go
  state/remoteapplication_test.go
  state/remoteentities.go
  state/remoteentities_test.go
  worker/remoterelations/remoteapplicationworker.go
Labels: 2.9

#13354 When an offer is consumed a second time, delete the old proxy
  apiserver/common/crossmodel/interface.go
  apiserver/common/crossmodel/state.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations_test.go
  apiserver/facades/controller/crossmodelrelations/mock_test.go
  apiserver/facades/controller/remoterelations/mock_test.go
  apiserver/facades/controller/remoterelations/remoterelations.go
  apiserver/facades/controller/remoterelations/remoterelations_test.go
  apiserver/facades/schema.json
  apiserver/params/crossmodel.go
  state/remoteapplication.go
  state/remoteapplication_test.go
  worker/remoterelations/mock_test.go
  worker/remoterelations/remoteapplicationworker.go
  worker/remoterelations/remoterelations.go
  worker/remoterelations/remoterelations_test.go
Labels: 2.9

#13352 Adds controller tag support to instance profile.
  provider/ec2/environ.go
  provider/ec2/iam.go
  provider/ec2/iam_test.go
Labels: 2.9

#13355 opt out telemetry
  apiserver/facades/controller/charmrevisionupdater/interface_test.go
  apiserver/facades/controller/charmrevisionupdater/updater.go
  apiserver/facades/controller/charmrevisionupdater/updater_test.go
  environs/config/config.go
  environs/config/config_test.go
Labels: feature, 3.0

#13357 [dev] Rely on instancemutator to apply lxd profiles in async charm dl mode
  apiserver/facades/client/charms/client.go
  core/cache/charm.go
  core/cache/lxdprofilewatcher.go
  core/cache/lxdprofilewatcher_test.go
  core/cache/machine.go
  core/cache/model.go
  core/charm/repository.go
  core/charm/repository/charmhub.go
  core/charm/repository/charmhub_test.go
  core/charm/repository/charmstore.go
  core/charm/repository/charmstore_test.go
Labels: 3.0

#13360 Add tests to ensure simplestreams client does gzip compression
  environs/simplestreams/datasource_test.go
  environs/simplestreams/export_test.go
  environs/simplestreams/simplestreams.go
Labels: 2.9

#13363 Use a mock for upgradedatabase test clock
  worker/upgradedatabase/mocks/package.go
  worker/upgradedatabase/package_test.go
  worker/upgradedatabase/shim.go
  worker/upgradedatabase/worker_test.go
Labels: 2.9

#13364 Make upgrade smoke test workflow more robust
  .github/workflows/smoke.yml
Labels: 3.0

#13362 Fix OS detection for controller charm tests
  cmd/jujud/agent/bootstrap_test.go
Labels: 3.0

#13343 Bootstrap test refactor
  caas/kubernetes/provider/base_test.go
  caas/kubernetes/provider/bootstrap_test.go
  caas/kubernetes/provider/export_test.go
  caas/kubernetes/provider/watcher/k8swatcher.go
Labels: 2.9

#13367 charmhub application metrics
  apiserver/facades/controller/charmrevisionupdater/charmhub.go
  apiserver/facades/controller/charmrevisionupdater/interface.go
  apiserver/facades/controller/charmrevisionupdater/interface_test.go
  apiserver/facades/controller/charmrevisionupdater/mocks/mocks.go
  apiserver/facades/controller/charmrevisionupdater/updater.go
  apiserver/facades/controller/charmrevisionupdater/updater_test.go
  charmhub/refresh_test.go
  charmhub/refreshconfig.go
  core/charm/metrics/metrics.go
  state/state.go
  state/state_test.go
Labels: feature, 3.0
