Repository juju/juju, pull requests merged in 2021-04, with the labels that each got.

#12794 Add disk provisioning customization
  provider/vsphere/config.go
  provider/vsphere/config_test.go
  provider/vsphere/environ_broker.go
  provider/vsphere/environ_broker_test.go
  provider/vsphere/internal/vsphereclient/client.go
  provider/vsphere/internal/vsphereclient/createvm.go
  provider/vsphere/internal/vsphereclient/createvm_test.go
  provider/vsphere/provider_test.go
Labels: 2.9

#12842 Fix upgrade series agent version handling
  cmd/jujud/agent/agentconf/agentconf.go
  service/agentconf.go
  service/agentconf_test.go
  worker/upgrader/upgrader.go
  worker/upgrader/upgrader_test.go
  worker/upgradeseries/mocks/servicemanager_mock.go
  worker/upgradeseries/upgrader.go
  worker/upgradeseries/upgrader_test.go
Labels: 2.9

#12845 [2.9] Restore space support for manual machines
  api/common/network.go
  apiserver/params/network.go
  apiserver/params/network_test.go
  core/network/address.go
  core/network/address_test.go
  worker/machiner/machiner.go
Labels: 2.9

#12839 [2.8] Support merging of netplan configs
  network/netplan/netplan.go
  network/netplan/netplan_internal_test.go
  network/netplan/netplan_test.go
  network/netplan/testdata/TestReadDirectory/01.yaml
Labels: 2.8

#12852 [2.9] Forward-port netplan fixes
  network/netplan/netplan.go
  network/netplan/netplan_internal_test.go
  network/netplan/netplan_test.go
  network/netplan/testdata/TestReadDirectory/01.yaml
Labels: 2.9

#12853 Add display type for network-get results
  worker/uniter/runner/jujuc/network-get.go
  worker/uniter/runner/jujuc/network-get_test.go
Labels: 2.9

#12858 Ensure assess-upgrade-series does not report started prematuremly
  acceptancetests/assess_upgrade_series.py
  acceptancetests/jujupy/client.py
Labels: 2.8

#12863 Help when no controller is selected
  cmd/modelcmd/controller.go
  cmd/modelcmd/modelcommand.go
  cmd/plugins/juju-metadata/imagemetadata.go
Labels: 3.0

#12874 Use Patch instead of Update for ensuring ingress resources;
  caas/kubernetes/provider/ingress.go
  caas/kubernetes/provider/ingress_test.go
Labels: 2.9

#12876 Use Patch instead of Update for ensuring ingress resources;
  caas/kubernetes/provider/ingress.go
  caas/kubernetes/provider/ingress_test.go
Labels: 2.8

#12890 Fix passing empty string container name to unit params;
  cmd/containeragent/initialize/command.go
  cmd/containeragent/initialize/command_test.go
  cmd/containeragent/unit/agent.go
  cmd/containeragent/unit/agent_test.go
  cmd/containeragent/unit/export_test.go
  worker/uniter/pebblepoller.go
Labels: 2.9, bug

#12888 Ensure we validate the model target
  apiserver/common/charms/common_test.go
  charmhub/find.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/deployer.go
  cmd/juju/application/deployer/deployer_test.go
  core/model/model.go
  core/model/model_test.go
  juju/testing/conn.go
  state/application_test.go
  state/caasmodel_test.go
  state/charm.go
  state/charm_test.go
  state/export_test.go
  state/filesystem_test.go
  state/migration_import_test.go
  state/model_test.go
  state/state.go
  state/storage_test.go
  testcharms/charm-repo/focal/cockroach-container-less/config.yaml
  testcharms/charm-repo/focal/cockroach-container-less/hooks/db-relation-changed
  testcharms/charm-repo/focal/cockroach-container-less/hooks/hook.template
  testcharms/charm-repo/focal/cockroach-container-less/hooks/install
  testcharms/charm-repo/focal/cockroach-container-less/hooks/start
  testcharms/charm-repo/focal/cockroach-container-less/hooks/stop
  testcharms/charm-repo/focal/cockroach-container-less/manifest.yaml
  testcharms/charm-repo/focal/cockroach-container-less/metadata.yaml
  testcharms/charm-repo/focal/cockroach-container-less/revision
  testcharms/charm-repo/kubernetes/starsay/metadata.yaml
  testcharms/charm-repo/quantal/dummy-kubernetes/.dir/ignored
  testcharms/charm-repo/quantal/dummy-kubernetes/.ignored
  testcharms/charm-repo/quantal/dummy-kubernetes/actions.yaml
  testcharms/charm-repo/quantal/dummy-kubernetes/build/ignored
  testcharms/charm-repo/quantal/dummy-kubernetes/config.yaml
  testcharms/charm-repo/quantal/dummy-kubernetes/empty/.gitkeep
  testcharms/charm-repo/quantal/dummy-kubernetes/hooks/install
  testcharms/charm-repo/quantal/dummy-kubernetes/metadata.yaml
  testcharms/charm-repo/quantal/dummy-kubernetes/revision
  testcharms/charm-repo/quantal/dummy-kubernetes/src/hello.c
  testcharms/charm-repo/quantal/dummy-kubernetes/version
Labels: 2.9

#12897 [2.9] Use production charmhub endpoint
  charmhub/client.go
Labels: 2.9

#12898 Remove usage of systems package from CAAS application provisioner
  api/common/charms/common.go
  apiserver/facades/client/machinemanager/state.go
  apiserver/facades/controller/caasunitprovisioner/mock_test.go
  caas/kubernetes/provider/application/application_test.go
  caas/kubernetes/provider/application/trust_test.go
  cloudconfig/podcfg/image.go
  cloudconfig/podcfg/image_test.go
  go.mod
  go.sum
  pki/authority_test.go
  worker/caasapplicationprovisioner/application.go
Labels: 2.9

#12887 Resource validation error
  cmd/juju/application/deployer/deployer.go
  cmd/juju/application/deployer/deployer_test.go
Labels: 2.9

#12906 Register resource-get for containeragent binary;
  cmd/containeragent/main_nix.go
  component/all/all.go
  component/all/all_test.go
  component/all/component_mock.go
  component/all/payload.go
  component/all/resource.go
Labels: 2.9, bug

#12932 Remove "caas" from error messages
  api/caasoperatorprovisioner/client.go
  worker/caasoperator/caasoperator.go
  worker/caasoperatorprovisioner/worker.go
  worker/uniter/uniter.go
Labels: 2.9
