Repository juju/juju, pull requests merged in 2021-01, with the labels that each got.

#12477 [dev] Use juju ssh to reboot machines in acceptance tests
  acceptancetests/assess_container_networking.py
  acceptancetests/assess_network_health.py
Labels: 3.0

#12478 Deprecate services in bundles
  acceptancetests/jujupy/tests/test_client.py
  acceptancetests/repository/basic-openstack-lxd.yaml
  acceptancetests/repository/bundles-kubernetes-core-lxd.yaml
  acceptancetests/repository/bundles-trust-checker.yaml
  acceptancetests/repository/mediawiki-scalable.yaml
  acceptancetests/repository/network-health-2-machines-bind.yaml
  acceptancetests/repository/network-health-2-machines-vipl.yaml
  acceptancetests/repository/network-health-2-machines.yaml
  acceptancetests/repository/network-health-3-machines.yaml
  acceptancetests/repository/openstack-base-lxc.yaml
  acceptancetests/repository/openstack-base-lxd.yaml
  acceptancetests/repository/scale2-lxc.yaml
  acceptancetests/repository/scale2-lxd.yaml
  acceptancetests/repository/scale2lxd.yaml
  acceptancetests/repository/webscale-lxd.yaml
  apiserver/facades/client/charms/repositories_test.go
  cmd/juju/application/bundle_test.go
  cmd/juju/application/deployer/bundle.go
  testcharms/charm-hub/bundles/wordpress-simple/bundle.yaml
  testcharms/charm-repo/bundle/aws-integrator-trust-conf-param/bundle.yaml
  testcharms/charm-repo/bundle/aws-integrator-trust-multi/bundle.yaml
  testcharms/charm-repo/bundle/aws-integrator-trust-single/bundle.yaml
  testcharms/charm-repo/bundle/bad/bundle.yaml
  testcharms/charm-repo/bundle/basic/bundle.yaml
  testcharms/charm-repo/bundle/bitcoinminer-with-dashboard/bundle.yaml
  testcharms/charm-repo/bundle/gitlab/bundle.yaml
  testcharms/charm-repo/bundle/lxd-profile-fail-local/bundle.yaml
  testcharms/charm-repo/bundle/lxd-profile-fail/bundle.yaml
  testcharms/charm-repo/bundle/lxd-profile-local/bundle.yaml
  testcharms/charm-repo/bundle/lxd-profile-mixed-fail/bundle.yaml
  testcharms/charm-repo/bundle/lxd-profile/bundle.yaml
  testcharms/charm-repo/bundle/openstack/bundle.yaml
  testcharms/charm-repo/bundle/terms-simple/bundle.yaml
  testcharms/charm-repo/bundle/wordpress-simple/bundle.yaml
  testcharms/charm-repo/bundle/wordpress-with-endpoint-bindings/bundle.yaml
  testcharms/charm-repo/bundle/wordpress-with-logging/bundle.yaml
  testcharms/charm-repo/bundle/wordpress-with-mysql-storage/bundle.yaml
  testcharms/charm-repo/bundle/wordpress-with-plans/bundle.yaml
Labels: 2.9

#12479 [dev] Implement identity discovery for ECS tasks
  cmd/k8sagent/initialize/command.go
  cmd/k8sagent/initialize/config.go
  cmd/k8sagent/initialize/config_test.go
Labels: 3.0

#12495 Add indexes to instanceData collection
  state/allcollections.go
Labels: 2.8

#12503 Migration minion connection strategy to fix validation step
  migration/dialopts.go
  worker/migrationminion/worker.go
  worker/migrationminion/worker_test.go
Labels: 2.8

#12509 Merge 2.8 into 2.9
  cmd/juju/common/controller.go
  migration/dialopts.go
  state/allcollections.go
  worker/migrationminion/worker.go
  worker/migrationminion/worker_test.go
Labels: 2.9

#12514 Ensure azure bootstrap to byo vnet with existing subnets
  provider/azure/environ_network.go
  provider/azure/environ_test.go
Labels: 2.9

#12505 Update json for hash struct elements for resource downloads.
  apiserver/facades/client/resources/repository_test.go
  apiserver/facades/controller/charmrevisionupdater/updater_test.go
  charmhub/resources.go
  charmhub/transport/common.go
  charmhub/transport/resources.go
  resource/resourceadapters/charmhub_test.go
Labels: 2.9

#12488 Fallback architecture
  apiserver/facades/client/charms/charmhubrepo.go
  apiserver/facades/client/charms/charmhubrepo_test.go
  apiserver/facades/client/charms/charmstorerepo.go
  apiserver/facades/client/charms/client.go
  apiserver/facades/client/charms/client_test.go
  apiserver/facades/client/charms/clientnormalize_test.go
  apiserver/facades/client/charms/repositories.go
  apiserver/facades/client/charms/repositories_test.go
  cmd/juju/application/bundle_test.go
  cmd/juju/application/deploy.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/bundle.go
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/charm.go
  cmd/juju/application/deployer/deployer.go
  cmd/juju/application/deployer/interface.go
  cmd/juju/application/deployer/mocks/deploy_mock.go
  cmd/juju/application/diffbundle.go
  cmd/juju/application/diffbundle_test.go
  cmd/juju/application/export_test.go
  cmd/juju/application/utils/origin.go
  cmd/juju/application/utils/origin_test.go
  core/charm/origin.go
  core/charm/origin_test.go
  go.mod
  go.sum
Labels: 2.9

#12530 Merge 2.8 into 2.9
  worker/uniter/runner/jujuc/unit-get.go
  worker/uniter/runner/jujuc/unit-get_test.go
Labels: 2.9

#12522 Improve error message with controller older than 2.9.
  cmd/juju/charmhub/download.go
  cmd/juju/charmhub/download_test.go
  cmd/juju/charmhub/find.go
  cmd/juju/charmhub/find_test.go
  cmd/juju/charmhub/info.go
  cmd/juju/charmhub/info_test.go
Labels: 2.9

#12493 2.9 - Remove legacy check for ongoing space discovery at login
  cmd/juju/common/controller.go
  cmd/juju/common/controller_test.go
  featuretests/upgrade_test.go
Labels: 2.9

#12521 [CharmHub] - Resolve the series and arch when deploying a bundle.
  api/common/charm/charmorigin.go
  apiserver/common/charms/common_test.go
  apiserver/facades/client/bundle/bundle_test.go
  apiserver/facades/client/charms/charmhubrepo.go
  apiserver/facades/client/charms/charmhubrepo_test.go
  apiserver/facades/client/charms/repositories_test.go
  cmd/juju/application/bundle_test.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/bundlehandler_test.go
  cmd/juju/application/deployer/charm.go
  go.mod
  go.sum
  testcharms/charm-hub/bundles/amalgam/bundle.yaml
  testcharms/charm-hub/bundles/charm-reuse/bundle.yaml
Labels: 2.9

#12508 Remove unused CodeRetry
  api/apiclient.go
  api/apiclient_test.go
  apiserver/errors/errors.go
  apiserver/errors/errors_test.go
  apiserver/params/apierror.go
Labels: 2.9

#12517 Rename snapcraft to charmhub in CharmHub urls.
  apiserver/facades/controller/charmrevisionupdater/interface_test.go
  charmhub/client.go
  charmhub/info_integration_test.go
Labels: 2.9

#12539 Default source of LXD root disk to the default storage pool
  container/lxd/container.go
  container/lxd/manager.go
  provider/lxd/environ_broker.go
Labels: 2.9

#12541 [Charmhub] - Rename charmhub model config value.
  agent/agentbootstrap/bootstrap_test.go
  apiserver/facades/client/charmhub/charmhub_test.go
  apiserver/facades/client/modelconfig/modelconfig.go
  apiserver/facades/client/modelconfig/modelconfig_test.go
  apiserver/facades/controller/charmrevisionupdater/interface_test.go
  caas/kubernetes/provider/proxy/info_test.go
  caas/kubernetes/provider/proxy/setup_test.go
  cmd/juju/charmhub/download.go
  cmd/juju/charmhub/download_test.go
  cmd/juju/model/config.go
  cmd/juju/model/config_test.go
  environs/config/config.go
  environs/config/config_test.go
  state/upgrades.go
  state/upgrades_test.go
  testing/environ.go
  tests/includes/colors.sh
  upgrades/steps_29.go
  upgrades/steps_29_test.go
Labels: 2.9

#12542 [Charmhub] - No charmhub charm by revision
  apiserver/facades/client/charms/charmhubrepo.go
  apiserver/facades/client/charms/repositories_test.go
  cmd/juju/application/deployer/bundle.go
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/bundlehandler_test.go
  cmd/juju/application/deployer/charm.go
  cmd/juju/application/deployer/deployer.go
  cmd/juju/application/deployer/deployer_test.go
  cmd/juju/application/refresh.go
  cmd/juju/application/store/charmadapter_test.go
Labels: 2.9

#12527 [Charmhub] - Pass architecture for charmstore charms, allowing migration.
  cmd/juju/application/bundle_test.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/refresh_test.go
  cmd/juju/application/refresher/refresher_test.go
  cmd/juju/application/utils/origin.go
  state/migration_export.go
  state/migration_export_test.go
  state/migration_import.go
  state/migration_import_test.go
Labels: 2.9

#12532 [Charmhub] - Migrate download charm to refresh API
  charmhub/refresh.go
  cmd/juju/charmhub/download.go
  cmd/juju/charmhub/download_test.go
  cmd/juju/charmhub/interface.go
  cmd/juju/charmhub/mocks/api_mock.go
Labels: 2.9

#12557 Use a waitgroup, rather than a channel to manage metrics workers
  cmd/juju/metricsdebug/collectmetrics.go
Labels: 2.9

#12537 Slight change to k8s bootstrap wording in log
  cmd/juju/commands/bootstrap.go
Labels: 2.9

#12535 Add ingress v1 and v1beta1 support for podspec v3
  caas/kubernetes/provider/base_test.go
  caas/kubernetes/provider/ingress.go
  caas/kubernetes/provider/ingress_test.go
  caas/kubernetes/provider/k8s.go
  caas/kubernetes/provider/specs/customresourcedefinition.go
  caas/kubernetes/provider/specs/ingress.go
  caas/kubernetes/provider/specs/ingress_test.go
  caas/kubernetes/provider/specs/v2.go
  caas/kubernetes/provider/specs/v2_test.go
  caas/kubernetes/provider/specs/v3.go
  caas/kubernetes/provider/specs/v3_test.go
Labels: 2.9

#12556 [Charmhub] - Typed error codes
  charmhub/errors.go
  charmhub/errors_test.go
  charmhub/find.go
  charmhub/info.go
  charmhub/refresh.go
  charmhub/transport/error.go
  charmhub/transport/error_test.go
  cmd/juju/charmhub/download.go
  go.mod
Labels: 2.9

#12548 Wireup parallel actions
  api/machineactions/action.go
  api/machineactions/machineactions.go
  api/uniter/action.go
  api/uniter/action_test.go
  api/uniter/uniter.go
  cmd/juju/action/exec.go
  cmd/juju/action/exec_test.go
  cmd/jujud/agent/machine/manifolds.go
  core/machinelock/machinelock.go
  core/machinelock/machinelock_test.go
  worker/machineactions/fixture_test.go
  worker/machineactions/handleactions.go
  worker/machineactions/handleactions_test.go
  worker/machineactions/manifold.go
  worker/machineactions/manifold_test.go
  worker/machineactions/mocks/mock_facade.go
  worker/machineactions/mocks/mock_lock.go
  worker/machineactions/package_test.go
  worker/machineactions/worker.go
  worker/machineactions/worker_test.go
  worker/uniter/actions/resolver.go
  worker/uniter/actions/resolver_test.go
  worker/uniter/operation/executor.go
  worker/uniter/operation/executor_test.go
  worker/uniter/operation/factory.go
  worker/uniter/operation/factory_test.go
  worker/uniter/operation/interface.go
  worker/uniter/operation/lock.go
  worker/uniter/operation/mocks/interface_mock.go
  worker/uniter/operation/remoteinit.go
  worker/uniter/operation/runaction.go
  worker/uniter/operation/runaction_test.go
  worker/uniter/operation/util_test.go
  worker/uniter/relation/mock_test.go
  worker/uniter/runner/context/action.go
  worker/uniter/runner/context/mocks/hookunit_mock.go
  worker/uniter/runner/factory.go
  worker/uniter/runner/factory_test.go
  worker/uniter/runner/runner.go
  worker/uniter/runner/util_test.go
  worker/uniter/storage/mock_test.go
  worker/uniter/uniter.go
Labels: 3.0

#12568 Shut down agent when unit is not found
  api/uniter/unit.go
  worker/caasupgrader/upgrader.go
  worker/uniter/uniter.go
  worker/uniter/uniter_test.go
  worker/uniter/util_test.go
Labels: 2.8

#12552 Improve error reporting for invalid metrics arguments
  cmd/juju/metricsdebug/collectmetrics.go
Labels: 2.9

#12572 Run MacOS Tests
  .github/workflows/client-tests.yml
  Makefile
  cmd/juju/commands/plugin_test.go
Labels: 2.9
