Repository juju/juju, pull requests merged in 2021-03, with the labels that each got.

#12679 Add ConfigSourceNIC indirection and implementation
  api/common/network.go
  api/common/network_mock_test.go
  api/common/network_test.go
  api/common/package_test.go
  core/network/source.go
  core/network/source_other.go
  core/network/source_other_test.go
  core/network/source_test.go
  network/utils.go
  network/utils_test.go
Labels: 2.9

#12704 Re-write multi-model test in bash
  acceptancetests/assess_multimodel.py
  tests/includes/juju.sh
  tests/includes/random.sh
  tests/suites/model/migration.sh
  tests/suites/model/multi.sh
  tests/suites/model/task.sh
Labels: 2.9

#12708 update charm-resources help
  cmd/juju/resource/charmresources.go
  cmd/juju/resource/charmresources_test.go
  cmd/juju/resource/list_charm_resources_test.go
Labels: 2.9

#12707 Find with options
  api/charmhub/client.go
  api/charmhub/client_test.go
  apiserver/facades/client/charmhub/charmhub.go
  apiserver/facades/client/charmhub/charmhub_test.go
  apiserver/facades/client/charmhub/package_mock_test.go
  apiserver/facades/schema.json
  apiserver/params/charmhub.go
  charmhub/client.go
  charmhub/find.go
  charmhub/find_test.go
  charmhub/info.go
  charmhub/path/path_test.go
  cmd/juju/charmhub/find.go
  cmd/juju/charmhub/find_test.go
  cmd/juju/charmhub/info.go
  cmd/juju/charmhub/interface.go
  cmd/juju/charmhub/mocks/api_mock.go
Labels: 2.9

#12715 Ensure non nil context after refreshMany Build.
  charmhub/refresh.go
  charmhub/refresh_test.go
Labels: 2.9

#12600 Introduce auto bootstrap to kubeconfig contexts.
  caas/kubernetes/clientconfig/export_test.go
  caas/kubernetes/clientconfig/k8s.go
  caas/kubernetes/clientconfig/k8s_test.go
  caas/kubernetes/clientconfig/plugins.go
  caas/kubernetes/clientconfig/plugins_test.go
  caas/kubernetes/clientconfig/types.go
  caas/kubernetes/cloud/cloud.go
  caas/kubernetes/cloud/cloud_test.go
  caas/kubernetes/cloud/credential.go
  caas/kubernetes/cloud/credential_test.go
  caas/kubernetes/cloud/package_test.go
  caas/kubernetes/cloud/util.go
  caas/kubernetes/cloud/util_test.go
  caas/kubernetes/provider/builtin.go
  caas/kubernetes/provider/builtin_test.go
  caas/kubernetes/provider/cloud.go
  caas/kubernetes/provider/cloud_test.go
  caas/kubernetes/provider/credentials.go
  caas/kubernetes/provider/credentials_test.go
  caas/kubernetes/provider/detectcloud.go
  caas/kubernetes/provider/detectcloud_test.go
  caas/kubernetes/provider/export_test.go
  caas/kubernetes/provider/provider.go
  cloud/clouds.go
  cmd/juju/caas/add.go
  cmd/juju/caas/add_test.go
  cmd/juju/caas/credential.go
  cmd/juju/caas/export_test.go
  cmd/juju/cloud/list.go
  cmd/juju/commands/bootstrap.go
Labels: 2.9

#12716 Fix panic when using juju find --columns
  cmd/juju/charmhub/findwriter.go
Labels: 2.9

#12709 Remove deprecated juju charm command, including juju charm resources.
  cmd/juju/charmcmd/charm.go
  cmd/juju/commands/main.go
  cmd/juju/commands/main_test.go
  cmd/juju/resource/export_test.go
  cmd/juju/resource/list_charm_resources.go
  cmd/juju/resource/list_charm_resources_test.go
Labels: 2.9

#12720 Add IsSecondary to Address network params
  apiserver/facades/schema.json
  apiserver/params/network.go
  apiserver/params/network_test.go
Labels: 2.9

#12722 Prevent charm series and systems (bases)
  go.mod
  go.sum
  testcharms/charm-repo/focal/cockroach/manifest.yaml
Labels: 2.9

#12732 Ensure we use an os less than eoan for deployment
  tests/suites/deploy/deploy_charms.sh
Labels: 2.9

#12739 Scaffold upgrade series logic
  apiserver/facades/client/machinemanager/instance_information_test.go
  apiserver/facades/client/machinemanager/machinemanager.go
  apiserver/facades/client/machinemanager/machinemanager_test.go
  apiserver/facades/client/machinemanager/package_test.go
  apiserver/facades/client/machinemanager/state.go
  apiserver/facades/client/machinemanager/types_mock_test.go
  apiserver/facades/client/machinemanager/upgrade_series.go
  apiserver/facades/client/machinemanager/upgrade_series_mock_test.go
  apiserver/facades/client/machinemanager/upgrade_series_test.go
  apiserver/facades/schema.json
  state/application.go
Labels: 2.9

#12753 Disregard refcount for blobstore cleanup
  scripts/juju-blobstore-cleanup/main.go
Labels: 2.8

#12759 Fix errant relative timeout for migration minion reports
  worker/migrationmaster/worker.go
  worker/migrationmaster/worker_test.go
Labels: 2.8

#12760 [2.8] Include hostname in multi-watcher machine deltas
  apiserver/params/multiwatcher.go
  apiserver/watcher.go
  core/multiwatcher/types.go
  state/allwatcher.go
Labels: 2.8

#12761 New controller config for migration-agent-wait-time
  controller/config.go
  controller/config_test.go
  state/controller_test.go
Labels: 2.8

#12765 Add MinionReportTimeout to migration-master API
  api/facadeversions.go
  apiserver/allfacades.go
  apiserver/facades/controller/migrationmaster/backend.go
  apiserver/facades/controller/migrationmaster/facade.go
  apiserver/facades/controller/migrationmaster/facade_test.go
  apiserver/facades/controller/migrationmaster/mocks/backend.go
  apiserver/facades/controller/migrationmaster/mocks/precheckbackend.go
  apiserver/facades/controller/migrationmaster/mocks/state.go
  apiserver/facades/controller/migrationmaster/package_test.go
  apiserver/facades/schema.json
Labels: 2.8

#12767 Migration-master worker uses configured minion report timeout
  api/migrationmaster/client.go
  api/migrationmaster/client_test.go
  worker/migrationmaster/worker.go
  worker/migrationmaster/worker_test.go
Labels: 2.8

#12766 Enable ha integration test
  tests/suites/controller/enable_ha.sh
  tests/suites/controller/task.sh
Labels: 2.8

#12772 [2.8] Add link-local field to netplan.Interface
  network/netplan/netplan.go
  network/netplan/netplan_test.go
Labels: 2.8

#12763 Verify charmhub requests
  apiserver/facades/client/machinemanager/instance_information_test.go
  apiserver/facades/client/machinemanager/machinemanager.go
  apiserver/facades/client/machinemanager/machinemanager_test.go
  apiserver/facades/client/machinemanager/package_test.go
  apiserver/facades/client/machinemanager/state.go
  apiserver/facades/client/machinemanager/types_mock_test.go
  apiserver/facades/client/machinemanager/upgrade_series.go
  apiserver/facades/client/machinemanager/upgrade_series_test.go
Labels: 2.9

#12738 [2.8] Support dynamic instance type discovery on GCE
  provider/gce/environ.go
  provider/gce/environ_broker.go
  provider/gce/environ_broker_test.go
  provider/gce/environ_instance.go
  provider/gce/environ_instance_test.go
  provider/gce/environ_policy.go
  provider/gce/environ_policy_test.go
  provider/gce/export_test.go
  provider/gce/instance_information.go
  provider/gce/instance_information_test.go
  provider/gce/instancetypes.go
  provider/gce/testing_test.go
Labels: 2.8

#12771 Upgrade series graph/FSM
  apiserver/common/upgradeseries.go
  apiserver/common/upgradeseries_test.go
  apiserver/facades/client/machinemanager/machinemanager.go
  apiserver/facades/client/machinemanager/machinemanager_test.go
  apiserver/facades/client/machinemanager/upgrade_series.go
  core/model/upgradeseries.go
  core/model/upgradeseries_test.go
  state/machine_upgradeseries.go
  worker/uniter/remotestate/watcher.go
Labels: 2.9

#12777 Fixes facade method used for migration-minion report timeout
  api/migrationmaster/client.go
  api/migrationmaster/client_test.go
Labels: 2.8

#12749 Adds support for legacy kubernetes schemas.
  caas/kubernetes/clientconfig/k8s_test.go
  caas/kubernetes/cloud/credential.go
  caas/kubernetes/cloud/credential_test.go
  caas/kubernetes/provider/builtin_test.go
  caas/kubernetes/provider/cloud.go
  caas/kubernetes/provider/cloud_test.go
  caas/kubernetes/provider/credentials.go
  caas/kubernetes/provider/credentials_test.go
  cloud/clouds.go
  cmd/juju/caas/add_test.go
  state/cloudcredentials.go
  state/upgrades.go
  state/upgrades_test.go
  upgrades/backend.go
  upgrades/steps_29.go
  upgrades/steps_29_test.go
Labels: 2.9

#12776 Introduction of validation step into FSM
  apiserver/facades/client/machinemanager/machinemanager_test.go
  apiserver/facades/client/machinemanager/state.go
  apiserver/facades/client/machinemanager/types_mock_test.go
  apiserver/facades/client/machinemanager/upgrade_series.go
  apiserver/facades/client/machinemanager/upgrade_series_mock_test.go
  apiserver/facades/client/machinemanager/upgrade_series_test.go
  caas/kubernetes/cloud/cloud.go
  cloud/clouds.go
  cmd/juju/machine/export_test.go
  cmd/juju/machine/mocks/status_api_mock.go
  cmd/juju/machine/mocks/upgrademachineseries_api_mock.go
  cmd/juju/machine/package_test.go
  cmd/juju/machine/upgradeseries.go
  cmd/juju/machine/upgradeseries_test.go
  core/model/upgradeseries.go
  core/model/upgradeseries_test.go
  go.sum
  resource/resourceadapters/opener.go
  state/machine_upgradeseries.go
  worker/uniter/upgradeseries/resolver.go
  worker/uniter/upgradeseries/resolver_test.go
  worker/upgradeseries/worker.go
  worker/upgradeseries/worker_test.go
Labels: 2.9

#12787 Make errors from API2Resource users friendly by include relevent
  charmstore/client.go
  charmstore/client_test.go
Labels: 2.8

#12786 Verify charmhub subordinates
  apiserver/facades/client/machinemanager/machinemanager.go
  apiserver/facades/client/machinemanager/state.go
  apiserver/facades/client/machinemanager/types_mock_test.go
  apiserver/facades/client/machinemanager/upgrade_series.go
  apiserver/facades/client/machinemanager/upgrade_series_mock_test.go
  apiserver/facades/client/machinemanager/upgrade_series_test.go
  cmd/juju/machine/upgradeseries.go
Labels: 2.9

#12785 Change 'dialled' to 'dialed'.
  api/apiclient.go
  mongo/open.go
Labels: 2.8

#12792 Remove the force when destroying models
  tests/includes/juju.sh
Labels: 2.8

#12801 Move fan logic to core/network
  api/fanconfigurer/facade.go
  apiserver/common/networkingcommon/types.go
  core/network/fan.go
  core/network/fan_test.go
  environs/config/config.go
  state/spaces.go
  state/spaces_test.go
  worker/fanconfigurer/fanconfigurer.go
Labels: 2.9

#12791 Verify charmhub finish series
  apiserver/common/mocks/upgradeseries.go
  apiserver/common/upgradeseries.go
  apiserver/common/upgradeseries_test.go
  apiserver/errors/errors.go
  apiserver/facades/agent/upgradeseries/upgradeseries.go
  apiserver/facades/agent/upgradeseries/upgradeseries_test.go
  apiserver/facades/client/application/application_unit_test.go
  apiserver/facades/client/machinemanager/machinemanager_test.go
  apiserver/facades/client/machinemanager/upgrade_series.go
  state/machine.go
  state/machine_test.go
Labels: 2.9

#12768 Use system instead of core for writing proxy settings.
  go.mod
  go.sum
  mongo/mongo.go
  packaging/dependency/mongo.go
  service/snap/app.go
  service/snap/app_test.go
  service/snap/clock_mock_test.go
  service/snap/export_test.go
  service/snap/package_test.go
  service/snap/runnable_mock_test.go
  service/snap/snap.go
  service/snap/snap_test.go
  worker/proxyupdater/proxyupdater.go
  worker/proxyupdater/proxyupdater_test.go
Labels: 2.8

#12805 Support older agent upgrades
  acceptancetests/assess_upgrade.py
  acceptancetests/jujupy/stream_server.py
  api/client.go
  api/client_test.go
  apiserver/common/tools.go
  apiserver/facades/client/client/instanceconfig.go
  cmd/juju/commands/synctools.go
  cmd/juju/commands/synctools_test.go
  cmd/juju/commands/upgrademodel.go
  cmd/juju/commands/upgrademodel_test.go
  core/series/supportedseries.go
  core/series/supportedseries_test.go
  core/series/testing.go
  tests/includes/server.sh
  tests/suites/bootstrap/streams.sh
  tests/suites/upgrade/streams.sh
  worker/uniter/runner/context/env_test.go
Labels: 2.9

#12555 Standardize a number of error messages and help text
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/application_unit_test.go
  apiserver/restrict_caasmodel.go
  apiserver/restrict_caasmodel_test.go
  cmd/juju/common/controller.go
  cmd/modelcmd/modelcommand.go
  cmd/modelcmd/modelcommand_test.go
  state/state.go
  state/storage_test.go
Labels: 2.9

#12809 Validate units and applications
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/application_test.go
  apiserver/facades/client/application/application_unit_test.go
  apiserver/facades/client/application/backend.go
  apiserver/facades/client/application/deploy_test.go
  apiserver/facades/client/application/get_test.go
  apiserver/facades/client/application/mock_test.go
  apiserver/facades/client/application/package_test.go
  apiserver/facades/client/application/update_series.go
  apiserver/facades/client/application/update_series_mocks_test.go
  apiserver/facades/client/application/update_series_test.go
  apiserver/facades/client/machinemanager/machinemanager.go
  apiserver/facades/client/machinemanager/upgrade_series.go
  apiserver/facades/client/machinemanager/upgrade_series_mock_test.go
  apiserver/facades/client/machinemanager/upgrade_series_test.go
  apiserver/facades/schema.json
Labels: 2.9

#12821 [2.9] Ensure openstack unit tests pass on non amd64 hosts
  provider/openstack/local_test.go
Labels: 2.9

#12826 Add support for mem, cpu and arch to k8s.
  caas/kubernetes/provider/application/application.go
  caas/kubernetes/provider/application/application_test.go
  caas/kubernetes/provider/constraints.go
  caas/kubernetes/provider/constraints_test.go
  caas/kubernetes/provider/k8s.go
  caas/kubernetes/provider/k8s_test.go
Labels: 2.9

#12795 Charmhub bundle upload and test
  testcharms/charm-hub/bundles/juju-qa-bundle-test/.jujuignore
  testcharms/charm-hub/bundles/juju-qa-bundle-test/README.md
  testcharms/charm-hub/bundles/juju-qa-bundle-test/bundle.yaml
  testcharms/charm-hub/bundles/juju-qa-bundle-test/charmcraft.yaml
  tests/suites/deploy/deploy_bundles.sh
Labels: 2.9

#12513 Minor improvements to scripts/generate-password
  scripts/generate-password/main.go
Labels: 3.0

#12828 Remove InterfaceInfo.CIDR; use Address.CIDR instead
  api/instancepoller/machine_test.go
  api/provisioner/provisioner.go
  api/provisioner/provisioner_test.go
  apiserver/common/networkingcommon/networkconfigapi.go
  apiserver/common/networkingcommon/networkconfigapi_test.go
  apiserver/common/networkingcommon/types.go
  apiserver/facades/schema.json
  apiserver/params/network.go
  apiserver/params/network_test.go
  cloudconfig/cloudinit/network_ubuntu.go
  cloudconfig/cloudinit/network_ubuntu_test.go
  container/broker/broker_test.go
  container/lxd/manager_test.go
  container/lxd/network.go
  core/network/address.go
  core/network/address_options.go
  core/network/address_test.go
  core/network/nic.go
  core/network/nic_test.go
  provider/dummy/environs.go
  provider/dummy/environs_test.go
  provider/ec2/environ.go
  provider/ec2/local_test.go
  provider/gce/environ_network.go
  provider/gce/environ_network_test.go
  provider/lxd/environ_network.go
  provider/lxd/environ_network_test.go
  provider/maas/devices.go
  provider/maas/environ.go
  provider/maas/instance_test.go
  provider/maas/interfaces.go
  provider/maas/interfaces_test.go
  provider/maas/maas2_environ_whitebox_test.go
  provider/maas/maas2instance_test.go
  provider/oci/networking.go
  provider/oci/networking_test.go
  state/linklayerdevices.go
  state/linklayerdevices_test.go
  worker/containerbroker/broker_test.go
  worker/instancepoller/worker.go
  worker/instancepoller/worker_test.go
Labels: 2.9

#12835 Use charm url name when migrating charms.
  api/migrationtarget/client.go
  api/migrationtarget/client_test.go
  apiserver/charms.go
  apiserver/charms_test.go
Labels: 2.9

#12815 Allow setting of VM hardware version
  provider/vsphere/config.go
  provider/vsphere/config_test.go
  provider/vsphere/environ_broker.go
  provider/vsphere/internal/vsphereclient/client.go
  provider/vsphere/internal/vsphereclient/client_test.go
  provider/vsphere/internal/vsphereclient/createvm.go
  provider/vsphere/internal/vsphereclient/createvm_test.go
  provider/vsphere/internal/vsphereclient/mock_test.go
Labels: 2.9
