Repository juju/juju, pull requests merged in 2021-07, with the labels that each got.

#13127 Log discovered spaces
  environs/context/context_mock_test.go
  environs/mocks/package_mock.go
  environs/networking.go
  environs/space/context_mock_test.go
  environs/space/environs_mock_test.go
  environs/space/spaces.go
  environs/space/spaces_mock_test.go
  environs/sync/simplestreams_mock_test.go
  environs/testing/package_mock.go
  provider/azure/environ.go
  provider/azure/environ_network.go
  provider/dummy/environs.go
  provider/ec2/environ.go
  provider/ec2/environ_test.go
  provider/gce/environ.go
  provider/gce/environ_network.go
  provider/lxd/environ.go
  provider/lxd/environ_network.go
  provider/maas/environ.go
  provider/maas/environ_whitebox_test.go
  provider/manual/environ.go
  provider/manual/environ_network.go
  provider/oci/environ.go
  provider/oci/networking.go
  provider/openstack/provider.go
Labels: 2.9

#13121 Add test by cloud to bash integration tests
  tests/includes/juju.sh
  tests/main.sh
  tests/suites/caasadmission/admission.sh
  tests/suites/caasadmission/task.sh
  tests/suites/model/migration.sh
Labels: 2.9

#13130 Facades: Allow empty charm config values
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/application_unit_test.go
Labels: 2.9

#13134 [2.9] Backport equinix provider support
  cloud/clouds_test.go
  cloud/fallback-public-cloud.yaml
  cloud/fallback_public_cloud.go
  cmd/juju/commands/bootstrap_test.go
  go.mod
  go.sum
  provider/all/equinix.go
  provider/equinix/config.go
  provider/equinix/credentials.go
  provider/equinix/credentials_test.go
  provider/equinix/environ.go
  provider/equinix/environ_network.go
  provider/equinix/environ_network_test.go
  provider/equinix/environ_test.go
  provider/equinix/init.go
  provider/equinix/instance.go
  provider/equinix/mocks/packngo.go
  provider/equinix/package_test.go
  provider/equinix/provider.go
  provider/equinix/provider_test.go
  provider/equinix/testing_test.go
  provider/equinix/userdata.go
Labels: 2.9

#13137 Cache: Coherence
  core/cache/lxdprofilewatcher.go
  core/cache/model_test.go
  core/cache/watcher.go
Labels: 2.8

#13140 Create pull secrets for sidecar containers.
  caas/kubernetes/provider/application/application.go
  caas/kubernetes/provider/application/application_test.go
  caas/kubernetes/provider/export_test.go
  caas/kubernetes/provider/k8s_test.go
  caas/kubernetes/provider/resources/applier.go
  caas/kubernetes/provider/resources/applier_test.go
  caas/kubernetes/provider/resources/clusterrole.go
  caas/kubernetes/provider/resources/clusterrolebinding.go
  caas/kubernetes/provider/resources/daemonset.go
  caas/kubernetes/provider/resources/deployment.go
  caas/kubernetes/provider/resources/events.go
  caas/kubernetes/provider/resources/interface.go
  caas/kubernetes/provider/resources/mocks/resources_mock.go
  caas/kubernetes/provider/resources/persistentvolume.go
  caas/kubernetes/provider/resources/persistentvolumeclaim.go
  caas/kubernetes/provider/resources/pod.go
  caas/kubernetes/provider/resources/role.go
  caas/kubernetes/provider/resources/rolebinding.go
  caas/kubernetes/provider/resources/secret.go
  caas/kubernetes/provider/resources/service.go
  caas/kubernetes/provider/resources/serviceaccount.go
  caas/kubernetes/provider/resources/statefulset.go
  caas/kubernetes/provider/resources/storageclass.go
  caas/kubernetes/provider/secrets.go
  caas/kubernetes/provider/utils/dockerconfig.go
  caas/kubernetes/provider/utils/dockerconfig_test.go
Labels: 2.9

#13138 Implement AllDeviceSpaceAddresses as domain concern and remove from state package
  apiserver/facades/agent/uniter/networkinfoiaas.go
  apiserver/facades/client/sshclient/facade.go
  apiserver/facades/client/sshclient/shim.go
  apiserver/facades/schema.json
  core/network/address.go
  core/network/address_test.go
  core/network/subnet.go
  core/network/subnet_test.go
  state/ipaddresses_test.go
  state/machine_linklayerdevices.go
  state/subnets.go
  state/subnets_test.go
Labels: 2.9

#13141 Fix/windows bootstrap2microk8s
  caas/kubernetes/provider/bootstrap.go
  caas/kubernetes/provider/builtin.go
  caas/kubernetes/provider/builtin_test.go
  caas/kubernetes/provider/cloud.go
  caas/kubernetes/provider/cloud_test.go
  caas/kubernetes/provider/detectcloud_test.go
  caas/kubernetes/provider/provider.go
Labels: 2.9

#13150 [dev] Define request/response payload for the new deploy API
  apiserver/params/deploy.go
Labels: 3.0

#13147 Set target series in pre-upgrade-series hook environment
  acceptancetests/repository/charms/dummy-sink/hooks/pre-series-upgrade
  api/common/upgradeseries.go
  api/common/upgradeseries_test.go
  api/uniter/unit.go
  api/uniter/unit_test.go
  apiserver/common/mocks/upgradeseries.go
  apiserver/common/upgradeseries.go
  apiserver/common/upgradeseries_test.go
  apiserver/facades/schema.json
  apiserver/params/params.go
  state/machine_upgradeseries.go
  state/unit.go
  worker/uniter/hook/hook.go
  worker/uniter/hook/hook_test.go
  worker/uniter/operation/runhook_test.go
  worker/uniter/remotestate/mock_test.go
  worker/uniter/remotestate/snapshot.go
  worker/uniter/remotestate/state.go
  worker/uniter/remotestate/watcher.go
  worker/uniter/remotestate/watcher_test.go
  worker/uniter/resolver_test.go
  worker/uniter/runner/context/context.go
  worker/uniter/runner/context/contextfactory.go
  worker/uniter/runner/context/export_test.go
  worker/uniter/runner/jujuc/context.go
  worker/uniter/upgradeseries/resolver.go
Labels: 2.9

#13139 Improve transactions in action removeAndLogBuildTxn.
  apiserver/facades/agent/uniter/uniter_test.go
  apiserver/facades/client/action/action_test.go
  apiserver/facades/client/action/legacy_test.go
  apiserver/facades/client/action/operation.go
  go.mod
  go.sum
  state/action.go
  state/action_test.go
  state/allwatcher_internal_test.go
  state/cleanup_test.go
  state/machine_test.go
  state/migration_export.go
  state/migration_export_test.go
  state/migration_import.go
  state/migration_import_test.go
  state/migration_internal_test.go
  state/operation.go
  state/operation_test.go
  state/state_test.go
  state/unit_test.go
  state/upgrades.go
  state/upgrades_test.go
  state/watcher_test.go
  upgrades/backend.go
  upgrades/operations.go
  upgrades/steps_296_test.go
  upgrades/steps_299.go
  upgrades/steps_299_test.go
  upgrades/upgrade_test.go
  worker/uniter/runner/context/context_test.go
  worker/uniter/runner/context/contextfactory_test.go
  worker/uniter/runner/factory_test.go
  worker/uniter/util_test.go
Labels: 2.9, do not merge

#13146 address Merge comments
  tests/includes/juju.sh
  tests/main.sh
  tests/suites/caasadmission/admission.sh
  tests/suites/caasadmission/task.sh
Labels: 2.9

#13149 Loggo wire up labels.
  api/client_test.go
  api/common/logs.go
  api/migrationmaster/client_test.go
  apiserver/debuglog.go
  apiserver/debuglog_db.go
  apiserver/debuglog_db_internal_test.go
  apiserver/facades/client/charmhub/charmhub.go
  apiserver/facades/client/charmhub/convert.go
  apiserver/facades/client/modelconfig/modelconfig.go
  apiserver/logsink.go
  apiserver/logsink_test.go
  apiserver/logstream.go
  apiserver/logtransfer.go
  apiserver/params/internal.go
  apiserver/params/logstream.go
  apiserver/params/params.go
  charmhub/client.go
  charmhub/fake_test.go
  charmhub/http.go
  cmd/containeragent/initialize/package_test.go
  cmd/juju/charmhub/download.go
  cmd/juju/commands/debuglog.go
  cmd/juju/commands/debuglog_test.go
  cmd/jujud/dumplogs/dumplogs.go
  core/logger/labels.go
  featuretests/cmd_juju_dumplogs_test.go
  go.mod
  go.sum
  state/export_test.go
  state/logs.go
  state/logs_test.go
  state/modelconfig.go
  worker/logsender/bufferedlogwriter.go
  worker/logsender/worker.go
  worker/migrationmaster/worker.go
  worker/modelworkermanager/dblogger.go
Labels: 2.9

#13152 Merge 2.9 into develop
  acceptancetests/repository/charms/dummy-sink/hooks/pre-series-upgrade
  api/common/upgradeseries.go
  api/common/upgradeseries_test.go
  api/uniter/unit.go
  api/uniter/unit_test.go
  apiserver/common/mocks/upgradeseries.go
  apiserver/common/upgradeseries.go
  apiserver/common/upgradeseries_test.go
  apiserver/facades/agent/uniter/networkinfoiaas.go
  apiserver/facades/client/sshclient/facade.go
  apiserver/facades/client/sshclient/shim.go
  apiserver/facades/schema.json
  apiserver/params/params.go
  caas/kubernetes/provider/bootstrap.go
  caas/kubernetes/provider/builtin.go
  caas/kubernetes/provider/builtin_test.go
  caas/kubernetes/provider/cloud.go
  caas/kubernetes/provider/cloud_test.go
  caas/kubernetes/provider/detectcloud_test.go
  caas/kubernetes/provider/provider.go
  core/network/address.go
  core/network/address_test.go
  core/network/subnet.go
  core/network/subnet_test.go
  state/ipaddresses_test.go
  state/machine_linklayerdevices.go
  state/machine_upgradeseries.go
  state/subnets.go
  state/subnets_test.go
  state/unit.go
  worker/provisioner/export_test.go
  worker/provisioner/provisioner_task.go
  worker/provisioner/provisioner_task_test.go
  worker/provisioner/provisioner_test.go
  worker/uniter/hook/hook.go
  worker/uniter/hook/hook_test.go
  worker/uniter/operation/runhook_test.go
  worker/uniter/remotestate/mock_test.go
  worker/uniter/remotestate/snapshot.go
  worker/uniter/remotestate/state.go
  worker/uniter/remotestate/watcher.go
  worker/uniter/remotestate/watcher_test.go
  worker/uniter/resolver_test.go
  worker/uniter/runner/context/context.go
  worker/uniter/runner/context/contextfactory.go
  worker/uniter/runner/context/export_test.go
  worker/uniter/runner/jujuc/context.go
  worker/uniter/upgradeseries/resolver.go
Labels: 2.9

#13166 Add support for bespoke service principals in Azure credentials
  provider/azure/config_test.go
  provider/azure/credentials.go
  provider/azure/credentials_test.go
  provider/azure/disk.go
  provider/azure/environ.go
  provider/azure/environprovider.go
  provider/azure/internal/azureauth/serviceprincipal.go
  provider/azure/internal/azureauth/serviceprincipal_test.go
Labels: 2.9

#13162 enhance test-network-health
  tests/suites/network/network_health.sh
Labels: 2.9

#13169 SpaceAddress conversion from single candidates instead of a slice
  apiserver/facades/agent/uniter/networkinfoiaas.go
  apiserver/facades/client/sshclient/shim.go
  core/network/address.go
  core/network/address_test.go
Labels: 2.9

#13175 NetworkInfo - Use a single sortable address type
  apiserver/facades/agent/uniter/networkinfoiaas.go
Labels: 2.9

#13178 Do not pass bootstrap-series to k8s integration suites
  tests/includes/juju.sh
  tests/main.sh
Labels: 2.9

#13165 deploy by revision: update charmhub client to use new related api functionality
  apiserver/facades/client/charms/charmhubrepo.go
  apiserver/facades/client/charms/charmhubrepo_test.go
  charmhub/find_integration_test.go
  charmhub/info_integration_test.go
  charmhub/refresh.go
  charmhub/refresh_integration_test.go
  charmhub/refresh_test.go
  charmhub/refreshconfig.go
  charmhub/transport/error.go
  charmhub/transport/refresh.go
  charmhub/transport/resources.go
Labels: 3.0, feature

#13181 DebugLog: Space labels correctly.
  cmd/juju/commands/debuglog.go
  cmd/juju/commands/debuglog_test.go
Labels: 2.9

#13176 Scripts: Juju inspect
  scripts/juju-inspect/Makefile
  scripts/juju-inspect/README.md
  scripts/juju-inspect/main.go
  scripts/juju-inspect/rules/entities.go
  scripts/juju-inspect/rules/manifolds.go
  scripts/juju-inspect/rules/mongo.go
  scripts/juju-inspect/rules/pubsub.go
  scripts/juju-inspect/rules/raft.go
  scripts/juju-inspect/rules/startcount.go
Labels: 2.9

#13184 NetworkInfoIAAS - sort ingress addresses with same rules as bind addresses
  apiserver/facades/agent/uniter/export_test.go
  apiserver/facades/agent/uniter/networkinfo_test.go
  apiserver/facades/agent/uniter/networkinfoiaas.go
Labels: 2.9

#13180 update test-network
  tests/suites/network/network_health.sh
Labels: 2.9

#13188 [2.9] Fix filter by tag bug in equinix provider
  provider/equinix/environ.go
  provider/equinix/environ_test.go
Labels: 2.9

#13177 Fix/lp 1934614
  api/caasapplicationprovisioner/client.go
  api/caasapplicationprovisioner/client_test.go
  apiserver/facades/controller/caasapplicationprovisioner/mock_test.go
  apiserver/facades/controller/caasapplicationprovisioner/provisioner.go
  apiserver/facades/controller/caasapplicationprovisioner/provisioner_test.go
  apiserver/facades/controller/caasapplicationprovisioner/state.go
  apiserver/facades/schema.json
  apiserver/params/caas.go
  go.mod
  go.sum
  worker/caasapplicationprovisioner/application.go
  worker/caasapplicationprovisioner/application_test.go
  worker/caasapplicationprovisioner/manifold.go
  worker/caasapplicationprovisioner/mocks/broker_mock.go
  worker/caasapplicationprovisioner/mocks/facade_mock.go
  worker/caasapplicationprovisioner/mocks/unitfacade_mock.go
  worker/caasapplicationprovisioner/worker.go
Labels: 2.9

#13191 [dev] Refactor charm downloader
  apiserver/charms.go
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/application_test.go
  apiserver/facades/client/application/charmstore.go
  apiserver/facades/client/application/charmstore_test.go
  apiserver/facades/client/application/export_test.go
  apiserver/facades/client/application/mock_test.go
  apiserver/facades/client/application/mocks/charmstore_mock.go
  apiserver/facades/client/charms/charmstorerepo.go
  apiserver/facades/client/charms/client.go
  apiserver/facades/client/charms/client_test.go
  apiserver/facades/client/charms/interface.go
  apiserver/facades/client/charms/interfaces/downloader.go
  apiserver/facades/client/charms/interfaces/state.go
  apiserver/facades/client/charms/mocks/corecharm_mock.go
  apiserver/facades/client/charms/mocks/repositories_mock.go
  apiserver/facades/client/charms/mocks/repository.go
  apiserver/facades/client/charms/mocks/state_mock.go
  apiserver/facades/client/charms/mocks/storage_mock.go
  apiserver/facades/client/charms/package_test.go
  apiserver/facades/client/charms/services/downloader.go
  apiserver/facades/client/charms/services/interface_mocks.go
  apiserver/facades/client/charms/services/interfaces.go
  apiserver/facades/client/charms/services/package_test.go
  apiserver/facades/client/charms/services/repofactory.go
  apiserver/facades/client/charms/services/repofactory_test.go
  apiserver/facades/client/charms/services/storage.go
  apiserver/facades/client/charms/services/storage_test.go
  apiserver/facades/client/client/client.go
  apiserver/facades/client/client/client_test.go
  apiserver/facades/client/client/statushistory_test.go
  apiserver/facades/schema.json
  cmd/containeragent/initialize/package_test.go
  core/cache/package_test.go
  core/charm/downloader/downloader.go
  core/charm/downloader/downloader_mocks.go
  core/charm/downloader/downloader_test.go
  core/charm/downloader/error.go
  core/charm/downloader/package_test.go
  core/charm/repository.go
  core/charm/repository/charmhub.go
  core/charm/repository/charmhub_test.go
  core/charm/repository/charmstore.go
  core/charm/repository/charmstore_test.go
  core/charm/repository/logger.go
  core/charm/repository/mocks/charmhub_client_mock.go
  core/charm/repository/mocks/charmstore_client_mock.go
  core/charm/repository/mocks/logger_mock.go
  core/charm/repository/package_test.go
  core/charm/repository/sanitizer.go
  core/charm/repository/sanitizer_test.go
  core/charm/strategies.go
  core/charm/strategies_mock_test.go
  core/charm/strategies_test.go
  core/multiwatcher/package_test.go
  state/application.go
  state/application_test.go
  state/charm.go
Labels: 3.0

#13183 deploy by revision: add --revision to deploy cli and implement.
  charmhub/refresh_test.go
  charmhub/refreshconfig.go
  charmhub/transport/refresh.go
  cmd/juju/application/deploy.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/bundle.go
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/charm.go
  cmd/juju/application/deployer/deployer.go
  cmd/juju/application/deployer/deployer_test.go
  cmd/juju/application/refresh.go
  cmd/juju/application/refresher/refresher_test.go
  cmd/juju/application/store/charmadapter_test.go
  cmd/juju/application/utils/origin.go
  core/charm/repository/charmhub.go
  core/charm/repository/charmhub_test.go
Labels: 3.0, feature

#13200 Deploy by revision resources prep
  apiserver/facades/client/application/package_test.go
  apiserver/facades/client/application/updateseries.go
  apiserver/facades/client/application/updateseries_mocks_test.go
  apiserver/facades/client/application/updateseries_test.go
  apiserver/facades/client/charms/services/repofactory.go
  apiserver/facades/client/machinemanager/package_test.go
  apiserver/facades/client/machinemanager/upgradeseries.go
  apiserver/facades/client/machinemanager/upgradeseries_mock_test.go
  apiserver/facades/client/machinemanager/upgradeseries_test.go
  apiserver/facades/client/resources/repository.go
  charmhub/refresh.go
  charmhub/refresh_test.go
  charmhub/refreshconfig.go
Labels: 3.0, feature
