Repository juju/juju, pull requests merged in 2021-12, with the labels that each got.

#13538 [JUJU-277] Add storage env vars to storage hooks.
  worker/uniter/runner/context/context.go
  worker/uniter/runner/context/context_test.go
  worker/uniter/runner/context/env_test.go
  worker/uniter/runner/context/export_test.go
  worker/uniter/runner/context/flush_test.go
  worker/uniter/runner/context/unitStorage_test.go
  worker/uniter/runner/context/util_test.go
Labels: 2.9

#13535 [JUJU-278] Only the peer grouper on the primary machine should change the replicaset
  state/enableha.go
  worker/peergrouper/desired.go
  worker/peergrouper/desired_test.go
  worker/peergrouper/manifold.go
  worker/peergrouper/manifold_test.go
  worker/peergrouper/mock_test.go
  worker/peergrouper/worker.go
  worker/peergrouper/worker_test.go
Labels: 2.9

#13475 [JUJU-131] Ensure machine removal deletes link-layer device provider IDs
  state/cleanup.go
  state/cleanup_test.go
  state/linklayerdevices_test.go
  state/machine_linklayerdevices.go
  state/upgrades.go
  state/upgrades_test.go
  upgrades/backend.go
  upgrades/operations.go
  upgrades/steps_2922.go
  upgrades/steps_2922_test.go
  upgrades/upgrade_test.go
Labels: 2.9

#13543 [JUJU-298] Add 2 new azure regions
  cloud/fallback-public-cloud.yaml
  cloud/fallback_public_cloud.go
Labels: 2.9

#13537 [JUJU-270] Fix enable ha integration test
  tests/includes/juju.sh
  tests/suites/controller/enable_ha.sh
Labels: 2.9

#13549 [JUJU-301] Ensure state pool release upon worker start errors
  worker/apiserver/manifold.go
  worker/certupdater/manifold.go
  worker/certupdater/manifold_test.go
  worker/peergrouper/manifold.go
  worker/peergrouper/manifold_test.go
Labels: 2.9

#13499 [JUJU-154] [2.9] Refactor provisioning task to improve parallelism
  api/controller/legacy_test.go
  core/workerpool/package_test.go
  core/workerpool/workerpool.go
  core/workerpool/workerpool_test.go
  environs/config/config.go
  environs/config/config_test.go
  worker/provisioner/mocks/lxdprofileinstancebroker_mock.go
  worker/provisioner/provisioner.go
  worker/provisioner/provisioner_task.go
  worker/provisioner/provisioner_task_test.go
  worker/provisioner/provisioner_test.go
Labels: 2.9

#13545 [JUJU-227] Cancel the scheduled(1min delayed) forceDestroyUnit cleanups
  state/application.go
  state/cleanup.go
  state/cleanup_test.go
  state/export_test.go
Labels: bug, 2.9

#13551 [JUJU-269] fix nw-deploy-bionic-gke
  acceptancetests/jujupy/k8s_provider/gke.py
Labels: 2.9, python

#13547 [JUJU-290] Engine metrics
  agent/addons/addons.go
  agent/addons/addons_test.go
  agent/addons/engine_mock_test.go
  agent/addons/package_test.go
  agent/addons/prometheus_mock_test.go
  cmd/containeragent/unit/agent.go
  cmd/jujud/agent/caasoperator.go
  cmd/jujud/agent/caasoperator_test.go
  cmd/jujud/agent/caasunitinit_test.go
  cmd/jujud/agent/engine/config.go
  cmd/jujud/agent/machine.go
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/agent/model.go
  cmd/jujud/agent/package_test.go
  go.mod
  go.sum
  worker/deployer/nested_test.go
  worker/deployer/unit_agent_test.go
  worker/modelworkermanager/manifold.go
  worker/modelworkermanager/manifold_test.go
  worker/modelworkermanager/modelworkermanager.go
  worker/modelworkermanager/modelworkermanager_test.go
Labels: 2.9

#13497 [JUJU-189] Raft lease extension timeout
  api/facadeversions.go
  api/raftlease/client.go
  api/raftlease/client_test.go
  api/raftlease/raftlease.go
  api/raftlease/raftlease_test.go
  api/raftlease/remote_mock.go
  apiserver/allfacades.go
  apiserver/facade/interface.go
  apiserver/facades/controller/raftlease/facade.go
  apiserver/facades/controller/raftlease/facade_test.go
  apiserver/facades/controller/raftlease/package_test.go
  apiserver/facades/controller/raftlease/raft_mock_test.go
  apiserver/facades/schema.json
  apiserver/params/params.go
  apiserver/raft.go
  apiserver/raft_test.go
  core/raft/queue/opqueue.go
  core/raft/queue/opqueue_test.go
  core/raft/queue/package_test.go
  core/raftlease/store.go
  worker/apiserver/worker.go
  worker/raft/apply.go
  worker/raft/apply_test.go
  worker/raft/worker.go
  worker/raft/worker_test.go
Labels: 2.9

#13481 [JUJU-137] Batch expire the expired leases
  core/raftlease/fsm.go
  core/raftlease/fsm_test.go
  core/raftlease/store.go
  provider/dummy/leasestore.go
  state/raftlease/target.go
  state/raftlease/target_test.go
  worker/globalclockupdater/manifold_test.go
  worker/globalclockupdater/raftlease_test.go
  worker/raft/raftforwarder/worker.go
  worker/raft/raftlease_mock_test.go
  worker/raft/worker.go
Labels: 2.9

#13557 [JUJU-314] Fix maas bond interface bug
  apiserver/facades/controller/instancepoller/instancepoller.go
  provider/maas/interfaces.go
  provider/maas/interfaces_test.go
Labels: 2.9

#13541 [JUJU-268] Add support for tear down of instance roles.
  cmd/juju/controller/destroy.go
  cmd/juju/controller/kill.go
  provider/ec2/environ.go
  provider/ec2/iam.go
  provider/ec2/iam_docs.go
  provider/ec2/iam_test.go
  provider/ec2/internal/testing/instanceprofile.go
  provider/ec2/internal/testing/roles.go
  provider/ec2/internal/testing/server.go
  provider/ec2/local_test.go
Labels: 2.9

#13559 [JUJU-326] Stop saas relation worker when relation is removed
  apiserver/facades/agent/instancemutater/instancemutater.go
  apiserver/facades/client/cloud/cloud_test.go
  apiserver/facades/client/machinemanager/machinemanager_test.go
  worker/remoterelations/remoteapplicationworker.go
  worker/remoterelations/remoterelations.go
  worker/remoterelations/remoterelations_test.go
Labels: 2.9

#13556 [JUJU-169] fix bundle deployment with 2.9 client and older controllers
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/bundlehandler_test.go
  cmd/juju/application/deployer/interface.go
  cmd/juju/application/deployer/mocks/deploy_mock.go
  core/bundle/changes/changes.go
  core/bundle/changes/changes_test.go
  core/bundle/changes/handlers.go
  core/bundle/changes/handlers_test.go
  core/bundle/changes/model.go
  core/bundle/changes/model_test.go
Labels: 2.9

#13546 [JUJU-299] Store unit CharmURL as a string reference
  api/uniter/unit.go
  apiserver/facades/agent/uniter/mocks/lxdprofile.go
  apiserver/facades/agent/uniter/mocks/newlxdprofile.go
  apiserver/facades/agent/uniter/newlxdprofile.go
  apiserver/facades/agent/uniter/uniter.go
  apiserver/facades/agent/uniter/uniter_test.go
  apiserver/facades/client/metricsdebug/metricsdebug.go
  core/cache/cachetest/state.go
  migration/precheck.go
  migration/precheck_test.go
  resource/resourceadapters/mocks/opener_mock.go
  resource/resourceadapters/opener_test.go
  resource/unit.go
  scripts/juju-list-blobstore/main.go
  state/allwatcher.go
  state/application.go
  state/application_test.go
  state/metrics_test.go
  state/migration_import.go
  state/state.go
  state/unit.go
  state/unit_test.go
  state/upgrade/types.go
  state/upgrades.go
  state/watcher.go
  testing/factory/factory.go
  worker/uniter/util_test.go
Labels: 2.9

#13569 [JUJU-342] Use kubectl auth can-i to check RBAC;
  acceptancetests/jujupy/k8s_provider/base.py
Labels: 2.9, python

#13572 [JUJU-342] Ignore exit code for kubectl auth check;
  acceptancetests/jujupy/k8s_provider/base.py
Labels: 2.9, python

#13507 [JUJU-194] [2.9] Remove `charm-assumes` feature flag
  apiserver/facades/client/application/application_unit_test.go
  apiserver/facades/client/application/deploy.go
  apiserver/facades/client/application/deploy_test.go
  apiserver/facades/client/modelmanager/modelinfo_test.go
  apiserver/facades/client/modelmanager/modelmanager.go
  apiserver/facades/client/modelmanager/modelmanager_test.go
  core/assumes/feature_descriptions.go
  core/assumes/sat_checker.go
  feature/flags.go
  featuretests/cmd_juju_controller_test.go
Labels: 2.9

#13576 [JUJU-362] Do not force channel for local charms
  core/bundle/changes/changes_test.go
  core/bundle/changes/handlers.go
Labels: bug, 2.9

#13565 Merge 2.9 into develop
  api/uniter/unit.go
  apiserver/facades/agent/uniter/mocks/newlxdprofile.go
  apiserver/facades/agent/uniter/newlxdprofile.go
  apiserver/facades/agent/uniter/uniter.go
  apiserver/facades/agent/uniter/uniter_test.go
  apiserver/facades/client/metricsdebug/metricsdebug.go
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/bundlehandler_test.go
  cmd/juju/application/deployer/interface.go
  cmd/juju/application/deployer/mocks/deploy_mock.go
  core/bundle/changes/changes.go
  core/bundle/changes/changes_test.go
  core/bundle/changes/handlers.go
  core/bundle/changes/handlers_test.go
  core/bundle/changes/model.go
  core/bundle/changes/model_test.go
  core/cache/cachetest/state.go
  migration/precheck.go
  migration/precheck_test.go
  resource/resourceadapters/mocks/opener_mock.go
  resource/resourceadapters/opener_test.go
  resource/unit.go
  scripts/juju-list-blobstore/main.go
  state/allwatcher.go
  state/application.go
  state/application_test.go
  state/metrics_test.go
  state/migration_import.go
  state/state.go
  state/unit.go
  state/unit_test.go
  state/upgrade/types.go
  state/upgrades.go
  state/watcher.go
  testing/factory/factory.go
  worker/uniter/util_test.go
Labels: 3.0
