Repository juju/juju, pull requests merged in 2021-02, with the labels that each got.

#12561 [Charmhub] Use refresh for resolving charm channels
  api/common/charm/charmorigin.go
  apiserver/facades/client/charms/charmhubrepo.go
  apiserver/facades/client/charms/charmhubrepo_test.go
  apiserver/facades/client/charms/mocks/repositories_mock.go
  apiserver/facades/client/charms/repositories_test.go
  charmhub/selector/package_test.go
  charmhub/selector/selector.go
  charmhub/selector/selector_test.go
  charmhub/transport/error.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/charm.go
  core/charm/channel.go
  core/charm/origin.go
  go.mod
Labels: 2.9

#12577 Merge 2.9 -> develop
  api/common/charm/charmorigin.go
  apiserver/facades/client/charms/charmhubrepo.go
  apiserver/facades/client/charms/charmhubrepo_test.go
  apiserver/facades/client/charms/mocks/repositories_mock.go
  apiserver/facades/client/charms/repositories_test.go
  charmhub/selector/package_test.go
  charmhub/selector/selector.go
  charmhub/selector/selector_test.go
  charmhub/transport/error.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/charm.go
  core/charm/channel.go
  core/charm/origin.go
Labels: 3.0

#12574 [Charmhub] - Allow resolution for bundles.
  apiserver/facades/client/charmhub/convert.go
  apiserver/facades/client/charms/charmhubrepo.go
  apiserver/facades/client/charms/charmhubrepo_test.go
  charmhub/refresh.go
  charmhub/refresh_test.go
  charmhub/transport/common.go
  charmhub/transport/find.go
  charmhub/transport/info.go
  charmhub/transport/refresh.go
  cmd/juju/charmhub/download.go
  cmd/juju/charmhub/download_test.go
  cmd/juju/charmhub/mocks/api_mock.go
Labels: 2.9

#12559 Send errors related to metrics gathering to STDERR instead of STDOUT
  cmd/juju/metricsdebug/collectmetrics.go
  cmd/juju/metricsdebug/collectmetrics_test.go
Labels: 2.9

#12578 [Charmhub] - Ensure refresh install actions
  apiserver/facades/client/charms/charmhubrepo.go
  apiserver/facades/client/charms/charmhubrepo_test.go
  core/charm/strategies.go
Labels: 2.9

#12585 [Charmhub] - Normalize channel
  apiserver/facades/client/charms/charmhubrepo.go
  apiserver/facades/client/charms/charmhubrepo_test.go
Labels: 2.9

#12593 Small error message change in deploy, reference CharmHub, not the store
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/deployer.go
Labels: 2.9

#12588 Remove arch/os from deploy suggestions on Refresh failure.
  apiserver/facades/client/charms/charmhubrepo.go
  apiserver/facades/client/charms/charmhubrepo_test.go
  cmd/juju/charmhub/infowriter.go
  core/charm/channel.go
Labels: 2.9

#12599 [Charmhub] - Handle the error when calculating a sha
  cmd/juju/charmhub/download.go
  cmd/juju/charmhub/download_test.go
  cmd/juju/charmhub/mocks/fsys_mock.go
  cmd/juju/charmhub/package_test.go
Labels: 2.9

#12566 Make `coreos/go-systemd' buildable on windows
  service/systemd/service.go
  service/systemd/service_unix.go
  service/systemd/service_windows.go
Labels: 2.9

#12594 [Charmhub] - `Juju info` updates based on upcoming api changes.
  api/charmhub/data.go
  apiserver/facades/client/charmhub/convert.go
  apiserver/facades/client/charms/charmhubrepo.go
  apiserver/facades/client/charms/charmhubrepo_test.go
  apiserver/facades/client/charms/repositories_test.go
  apiserver/facades/schema.json
  apiserver/params/charmhub.go
  charmhub/filter.go
  charmhub/info.go
  charmhub/transport/common.go
  charmhub/transport/info.go
  cmd/juju/application/store/charmadapter.go
  cmd/juju/charmhub/download_test.go
Labels: 2.9

#12607 Clean up model migration code
  acceptancetests/assess_model_migration.py
Labels: 2.9

#12609 EC2 fix panic
  provider/common/availabilityzones.go
  provider/common/availabilityzones_test.go
  provider/common/mock_test.go
  provider/common/mocks/zoned_environ.go
  provider/dummy/environs.go
  provider/ec2/environ.go
  provider/ec2/environ_test.go
  provider/ec2/instance.go
  provider/gce/environ_availzones.go
  provider/gce/environ_availzones_test.go
  provider/lxd/environ.go
  provider/maas/environ.go
  provider/oci/environ.go
  provider/oci/environ_test.go
  provider/openstack/cinder.go
  provider/openstack/cinder_test.go
  provider/openstack/provider.go
  provider/vsphere/environ_availzones.go
  provider/vsphere/environ_availzones_test.go
  worker/provisioner/provisioner_task_test.go
  worker/provisioner/provisioner_test.go
Labels: 2.9

#12621 Relocates DNS and resolve.conf parsing from network to core/network
  container/broker/broker.go
  core/network/dns.go
  core/network/dns_test.go
  network/utils.go
  network/utils_test.go
Labels: 2.8

#12622 Move NetworkConfigSource from api/common to core/network
  api/common/network.go
  container/broker/instance_broker.go
  core/network/source.go
  core/network/source_other.go
  network/utils.go
  network/utils_test.go
  worker/machiner/machiner.go
  worker/machiner/machiner_test.go
  worker/provisioner/container_initialisation.go
  worker/provisioner/container_initialisation_test.go
  worker/provisioner/export_test.go
Labels: 2.8

#12619 Add set-series integration test
  tests/main.sh
  tests/suites/unit/task.sh
  tests/suites/unit/unit_series.sh
Labels: 2.9

#12617 Fixes permission for model operator.
  caas/kubernetes/provider/modeloperator.go
  caas/kubernetes/provider/modeloperator_test.go
  caas/kubernetes/provider/utils/cleanup.go
  caas/kubernetes/provider/utils/cleanup_test.go
Labels: 2.9

#12623 Indirection for network config sourced addresses
  api/common/network.go
  api/common/network_test.go
  core/network/network_test.go
  core/network/source.go
  core/network/source_other.go
  core/network/source_other_test.go
Labels: 2.8

#12630 Fix double upgrade edge case.
  worker/uniter/uniter.go
Labels: 2.8

#12629 Record why a cloud credential gets marked invalid and expose via show-model, status
  api/client.go
  api/facadeversions.go
  api/modelmanager/modelmanager.go
  api/state_test.go
  apiserver/allfacades.go
  apiserver/facades/client/client/backend.go
  apiserver/facades/client/client/client.go
  apiserver/facades/client/client/status.go
  apiserver/facades/client/client/statushistory_test.go
  apiserver/facades/schema.json
  cmd/juju/common/model.go
  cmd/juju/status/formatted.go
  cmd/juju/status/formatter.go
  cmd/juju/status/history.go
  cmd/juju/status/history_test.go
  cmd/juju/status/status_internal_test.go
  core/constraints/package_test.go
  core/status/package_test.go
  core/status/status_history.go
  provider/azure/internal/errorutils/errors.go
  provider/azure/internal/errorutils/errors_test.go
  provider/common/errors.go
  provider/common/errors_test.go
  provider/gce/google/errors.go
  provider/gce/google/errors_test.go
  provider/maas/errors_test.go
  provider/vsphere/environ_broker_test.go
  state/model.go
  state/modelcredential.go
  state/modelcredential_test.go
  state/modelsummaries.go
  state/modelsummaries_test.go
Labels: 2.8

#12633 Update how channel is created in ApplicationsInfo.
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/application_unit_test.go
  apiserver/facades/client/application/mock_test.go
  core/charm/channel.go
  core/charm/channel_test.go
Labels: 2.9

#12641 Bundle diff output with charm url names
  apiserver/facades/client/bundle/bundle.go
  apiserver/facades/client/client/status.go
  apiserver/facades/schema.json
  apiserver/params/status.go
  cmd/juju/application/bundle/bundle.go
  cmd/juju/application/bundle/bundle_test.go
  cmd/juju/application/deployer/deployer.go
  cmd/juju/application/diffbundle.go
  cmd/juju/application/diffbundle_test.go
  go.mod
  go.sum
  tests/suites/smoke/deploy.sh
Labels: 2.9

#12650 Ensure we normalize the charm url in bundle handler
  cmd/juju/application/deployer/bundlehandler.go
Labels: 2.9

#12653 Adds missing container status of creating.
  caas/kubernetes/provider/pod.go
  caas/kubernetes/provider/pod_test.go
Labels: 2.8

#12655 Merge 2.8
  caas/kubernetes/provider/pod.go
  caas/kubernetes/provider/pod_test.go
  upgrades/operations.go
  upgrades/steps_289.go
  upgrades/steps_289_test.go
  upgrades/upgrade_test.go
Labels: 2.9

#12656 Run Pebble as root inside container
  caas/kubernetes/provider/application/application.go
  caas/kubernetes/provider/application/application_test.go
Labels: 2.9

#12643 Expose charm channel in juju status
  apiserver/facades/schema.json
  apiserver/params/status.go
  apiserver/params/status_test.go
  cmd/juju/status/formatted.go
  cmd/juju/status/formatter.go
  cmd/juju/status/output_tabular.go
  cmd/juju/status/status_internal_test.go
  featuretests/cmd_juju_status_test.go
Labels: 2.9

#12636 Error if add-k8s is used with an existing cloud name
  caas/kubernetes/provider/cloud.go
  cmd/juju/caas/add.go
  cmd/juju/caas/add_test.go
Labels: 2.9

#12597 Add microk8s-tests
  .github/workflows/build.yml
  .github/workflows/client-tests.yml
  .github/workflows/microk8s-tests.yml
Labels: 2.8

#12626 Feature/kubeflow ci
  acceptancetests/assess_caas_deploy_charms.py
  acceptancetests/assess_caas_deploy_kubeflow.py
  acceptancetests/jujupy/client.py
  acceptancetests/jujupy/k8s_provider/aks.py
  acceptancetests/jujupy/k8s_provider/base.py
  acceptancetests/jujupy/k8s_provider/eks.py
  acceptancetests/jujupy/k8s_provider/gke.py
  acceptancetests/jujupy/k8s_provider/kubernetes_core.py
  acceptancetests/jujupy/k8s_provider/microk8s.py
  acceptancetests/requirements.txt
Labels: 2.8, python

#12661 Add IsSecondary to IP Addresses document
  go.mod
  go.sum
  state/ipaddresses_internal_test.go
  state/linklayerdevices_ipaddresses.go
  state/migration_import.go
  state/migration_internal_test.go
Labels: 2.9

#12663 Functional options for address constructors
  api/highavailability/client_test.go
  api/state_test.go
  api/testing/apiaddresser.go
  apiserver/admin_test.go
  apiserver/common/firewall/firewall_test.go
  apiserver/facades/agent/deployer/deployer_test.go
  apiserver/facades/agent/uniter/networkinfo_test.go
  apiserver/facades/agent/uniter/networkinfoiaas.go
  apiserver/facades/agent/uniter/uniter_test.go
  apiserver/facades/client/client/client_test.go
  apiserver/facades/client/highavailability/highavailability_test.go
  apiserver/facades/controller/instancepoller/instancepoller.go
  apiserver/facades/controller/instancepoller/instancepoller_test.go
  apiserver/params/network_test.go
  caas/kubernetes/provider/k8s.go
  caas/kubernetes/provider/k8s_test.go
  cmd/juju/commands/enableha_test.go
  cmd/juju/commands/ssh_machine_test.go
  cmd/juju/status/status_internal_test.go
  container/lxd/container_test.go
  core/network/address.go
  core/network/address_options.go
  core/network/address_test.go
  core/network/hostport_test.go
  environs/manual/addresses_test.go
  mongo/mongo_test.go
  provider/azure/instance.go
  provider/ec2/environ.go
  provider/ec2/local_test.go
  provider/gce/environ_network.go
  provider/gce/environ_network_test.go
  provider/gce/google/network_test.go
  provider/gce/google/testing_test.go
  provider/gce/testing_test.go
  provider/lxd/testing_test.go
  provider/oci/networking.go
  provider/oci/networking_test.go
  provider/openstack/local_test.go
  provider/openstack/provider.go
  state/address.go
  state/address_test.go
  state/allwatcher_internal_test.go
  state/application.go
  state/application_test.go
  state/machine_test.go
  state/migration_export_test.go
  state/migration_import_test.go
  state/relationunit_test.go
  state/state_test.go
  state/unit.go
  state/unit_test.go
  worker/certupdater/certupdater_test.go
  worker/instancepoller/worker_test.go
  worker/machiner/machiner_test.go
  worker/peergrouper/controllertracker_test.go
  worker/peergrouper/worker_test.go
  worker/uniter/runner/context/context_test.go
  worker/uniter/runner/context/util_test.go
  worker/uniter/runner/util_test.go
  worker/uniter/util_test.go
Labels: 2.9

#12669 Add IsSecondary to core/network addresses and factor into sort order
  core/network/address.go
  core/network/address_options.go
  core/network/address_test.go
  core/network/hostport.go
Labels: 2.9

#12659 add resource to ubuntu qa charm for test
  testcharms/charm-hub/charms/ubuntu-qa/.jujuignore
  testcharms/charm-hub/charms/ubuntu-qa/README.md
  testcharms/charm-hub/charms/ubuntu-qa/charmcraft.yaml
  testcharms/charm-hub/charms/ubuntu-qa/config.yaml
  testcharms/charm-hub/charms/ubuntu-qa/foo-file.txt
  testcharms/charm-hub/charms/ubuntu-qa/metadata.yaml
  testcharms/charm-hub/charms/ubuntu-qa/src/charm.py
  testcharms/charm-hub/charms/ubuntu-qa/version
Labels: 2.9

#12667 Merge 2.8
  .github/workflows/build.yml
  .github/workflows/client-tests.yml
  .github/workflows/microk8s-tests.yml
  acceptancetests/assess_caas_deploy_charms.py
  acceptancetests/assess_caas_deploy_kubeflow.py
  acceptancetests/jujupy/client.py
  acceptancetests/jujupy/k8s_provider/aks.py
  acceptancetests/jujupy/k8s_provider/base.py
  acceptancetests/jujupy/k8s_provider/eks.py
  acceptancetests/jujupy/k8s_provider/gke.py
  acceptancetests/jujupy/k8s_provider/kubernetes_core.py
  acceptancetests/jujupy/k8s_provider/microk8s.py
  acceptancetests/requirements.txt
  state/action_test.go
  state/backend.go
  state/watcher_test.go
Labels: 2.9

#12664 Lp1910989
  tests/suites/caasadmission/admission.sh
  tests/suites/caasadmission/task.sh
  worker/caasadmission/filter.go
  worker/caasadmission/handler.go
  worker/caasadmission/handler_test.go
Labels: 2.8

#12678 Merge pull request #12677 from wallyworld/delete-ec2-secgroups
  provider/ec2/environ.go
  provider/ec2/export_test.go
  provider/ec2/local_test.go
Labels: 2.9

#12676 Merge 2.8 to 2.9
  tests/suites/caasadmission/admission.sh
  worker/caasadmission/filter.go
  worker/caasadmission/handler.go
  worker/caasadmission/handler_test.go
Labels: 2.9

#12658 Charmhub bundle channel
  apiserver/facades/client/bundle/bundle_test.go
  apiserver/facades/client/client/bundles_test.go
  cmd/juju/application/bundle/bundle.go
  cmd/juju/application/bundle_test.go
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/bundlehandler_test.go
  core/charm/channel.go
  go.mod
  go.sum
Labels: 2.9

#12682 Ensure we use the same user-agent version
  apiserver/facades/client/application/charmstore.go
  apiserver/facades/client/charms/charmstorerepo.go
  charmhub/client.go
  charmstore/client.go
  cmd/juju/application/store/store.go
  go.mod
  go.sum
  version/version.go
Labels: 2.9

#12660 Remove obsolete application facade methods
  api/application/client.go
  api/application/client_test.go
  apiserver/allfacades.go
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/application_test.go
  apiserver/facades/client/application/application_unit_test.go
  apiserver/facades/client/application/get.go
  apiserver/facades/client/application/get_test.go
  apiserver/facades/client/client/perm_test.go
  apiserver/facades/schema.json
  apiserver/params/applications.go
  cmd/juju/application/addrelation.go
  cmd/juju/application/addrelation_test.go
  cmd/juju/application/addremoterelation_test.go
  cmd/juju/application/addunit.go
  cmd/juju/application/addunit_test.go
  cmd/juju/application/bind.go
  cmd/juju/application/bind_test.go
  cmd/juju/application/config.go
  cmd/juju/application/config_test.go
  cmd/juju/application/deploy.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/interface.go
  cmd/juju/application/deployer/mocks/deploy_mock.go
  cmd/juju/application/export_test.go
  cmd/juju/application/fakeapplication_test.go
  cmd/juju/application/refresh.go
  cmd/juju/application/refresh_test.go
  cmd/juju/application/refresher/refresher.go
  cmd/juju/application/refresher/refresher_test.go
  cmd/juju/application/remove_application_test.go
  cmd/juju/application/removeapplication.go
  cmd/juju/application/removerelation.go
  cmd/juju/application/removerelation_test.go
  cmd/juju/application/removesaas.go
  cmd/juju/application/removesaas_test.go
  cmd/juju/application/removeunit.go
  cmd/juju/application/removeunit_test.go
  cmd/juju/application/resolved.go
  cmd/juju/application/resolved_test.go
  cmd/juju/application/resumerelation.go
  cmd/juju/application/resumerelation_test.go
  cmd/juju/application/scaleapplication.go
  cmd/juju/application/scaleapplication_test.go
  cmd/juju/application/setseries.go
  cmd/juju/application/setseries_test.go
  cmd/juju/application/show.go
  cmd/juju/application/show_test.go
  cmd/juju/application/suspendrelation.go
  cmd/juju/application/suspendrelation_test.go
  cmd/juju/romulus/setplan/set_plan.go
  cmd/juju/romulus/setplan/set_plan_test.go
Labels: 3.0

#12683 Scaffolding for charmhub charm resources command
  cmd/juju/commands/main.go
  cmd/juju/resource/charmresources.go
  cmd/juju/resource/charmresources_test.go
  cmd/juju/resource/export_test.go
  cmd/juju/resource/list_charm_resources.go
  cmd/juju/resource/list_charm_resources_test.go
  cmd/juju/resource/stub_test.go
  featuretests/cmd_juju_resources_test.go
Labels: 2.9

#12691 Add coverage to make file
  .github/workflows/client-tests.yml
  Makefile
Labels: 2.9

#12695 List charm resources
  api/charms/client.go
  api/charms/client_test.go
  apiserver/facades/client/charms/charmhubrepo.go
  apiserver/facades/client/charms/charmhubrepo_test.go
  apiserver/facades/client/charms/charmstorerepo.go
  apiserver/facades/client/charms/client.go
  apiserver/facades/client/charms/repositories.go
  apiserver/facades/client/charms/repositories_test.go
  apiserver/facades/schema.json
  apiserver/params/resources.go
  cmd/juju/resource/charmresources.go
  core/charm/repository.go
Labels: 2.9
