Repository juju/juju, pull requests merged in 2021-11, with the labels that each got.

#13453 Raft queue changes
  apiserver/facade/interface.go
  apiserver/facades/controller/raftlease/facade.go
  apiserver/facades/controller/raftlease/facade_test.go
  apiserver/facades/controller/raftlease/raft_mock_test.go
  apiserver/raft.go
  apiserver/raft_test.go
  core/raft/queue/opqueue.go
  core/raft/queue/opqueue_test.go
  scripts/leadershipclaimer/run.sh
  worker/lease/manager.go
  worker/raft/apply.go
  worker/raft/apply_test.go
Labels: 2.9

#13412 Be smarter about container NIC MTUs when using the Fan
  container/lxd/manager.go
  network/containerizer/bridgepolicy.go
  state/linklayerdevices.go
  state/linklayerdevices_test.go
Labels: 2.9

#13464 Improve run hook error when charm is missing
  worker/uniter/runner/args.go
  worker/uniter/runner/runner.go
  worker/uniter/runner/runner_test.go
  worker/uniter/runner/util_test.go
Labels: 2.9

#13461 Enhanced logging detail when starting side-car agents
  caas/kubernetes/provider/application/application.go
  caas/kubernetes/provider/application/application_test.go
  cmd/containeragent/unit/agent.go
Labels: 2.9

#13468 Skip check for microk8s user group on macOS
  caas/kubernetes/provider/cloud.go
  caas/kubernetes/provider/cloud_test.go
Labels: 2.9

#13474 Backport lxd error handling
  container/lxd/server.go
Labels: 2.8

#13448 add multi-part yaml support to GetChanges for the bundle facade
  api/facadeversions.go
  apiserver/allfacades.go
  apiserver/facades/client/bundle/bundle.go
  apiserver/facades/client/bundle/bundle_test.go
  apiserver/facades/schema.json
Labels: 2.9

#13462 Context queue
  apiserver/raft.go
  apiserver/raft_test.go
  core/raft/queue/opqueue.go
  core/raft/queue/opqueue_test.go
Labels: 2.9

#13471 Merge 2.9 into develop
  apiserver/apiserver.go
  apiserver/common/crossmodel/crossmodel.go
  apiserver/facade/interface.go
  apiserver/facades/client/charms/client.go
  apiserver/facades/client/charms/client_test.go
  apiserver/facades/client/charms/interfaces/downloader.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations.go
  apiserver/facades/controller/raftlease/facade.go
  apiserver/facades/controller/raftlease/facade_test.go
  apiserver/facades/controller/raftlease/raft_mock_test.go
  apiserver/facades/controller/remoterelations/remoterelations_test.go
  apiserver/raft.go
  apiserver/raft_test.go
  cmd/juju/application/deployer/bundlehandler_test.go
  container/lxd/manager.go
  core/raft/queue/opqueue.go
  core/raft/queue/opqueue_test.go
  network/containerizer/bridgepolicy.go
  scripts/leadershipclaimer/run.sh
  state/linklayerdevices.go
  state/linklayerdevices_test.go
  tests/suites/deploy/bundles/telegraf_bundle.yaml
  tests/suites/model/metrics.sh
  tests/suites/model/task.sh
  tests/suites/ovs_maas/ovs_netplan_config.sh
  worker/caasrbacmapper/mapper_test.go
  worker/globalclockupdater/updater.go
  worker/globalclockupdater/updater_test.go
  worker/lease/manager.go
  worker/raft/apply.go
  worker/raft/apply_test.go
  worker/remoterelations/remoteapplicationworker.go
Labels: 3.0

#13465 Feature/manifests and blobs api for registries
  cmd/containeragent/initialize/package_test.go
  controller/config.go
  controller/config_test.go
  docker/auth.go
  docker/auth_test.go
  docker/registry/image/image.go
  docker/registry/image/image_test.go
  docker/registry/internal/acr.go
  docker/registry/internal/acr_test.go
  docker/registry/internal/base_client.go
  docker/registry/internal/base_client_test.go
  docker/registry/internal/base_manifests.go
  docker/registry/internal/base_manifests_test.go
  docker/registry/internal/base_tags.go
  docker/registry/internal/base_tags_test.go
  docker/registry/internal/base_test.go
  docker/registry/internal/dockerhub.go
  docker/registry/internal/dockerhub_test.go
  docker/registry/internal/ecr.go
  docker/registry/internal/ecr_test.go
  docker/registry/internal/gcr.go
  docker/registry/internal/gcr_test.go
  docker/registry/internal/github.go
  docker/registry/internal/github_test.go
  docker/registry/internal/gitlab.go
  docker/registry/internal/gitlab_test.go
  docker/registry/internal/interface.go
  docker/registry/internal/mocks/manifests_mock.go
  docker/registry/internal/package_test.go
  docker/registry/internal/quay.go
  docker/registry/internal/quay_test.go
  docker/registry/internal/transports.go
  docker/registry/internal/transports_test.go
  docker/registry/mocks/registry_mock.go
  docker/registry/registry.go
  docker/registry/utils/errors.go
  worker/caasmodelconfigmanager/worker.go
Labels: 2.9

#13460 Allow NotifyTarget to return an error
  cmd/jujud/agent/machine.go
  cmd/jujud/agent/machine/manifolds.go
  core/raftlease/fsm.go
  core/raftlease/fsm_test.go
  core/raftlease/logger.go
  core/raftlease/logger_mock_test.go
  core/raftlease/logger_test.go
  core/raftlease/store.go
  core/raftlease/writer_mock_test.go
  provider/dummy/leasestore.go
  state/raftlease/target.go
  state/raftlease/target_test.go
  upgrades/raft.go
  upgrades/raft_test.go
  worker/globalclockupdater/manifold.go
  worker/globalclockupdater/manifold_test.go
  worker/globalclockupdater/raft_test.go
  worker/globalclockupdater/raftlease_test.go
  worker/globalclockupdater/updater.go
  worker/globalclockupdater/worker.go
  worker/raft/apply.go
  worker/raft/apply_test.go
  worker/raft/manifold.go
  worker/raft/manifold_test.go
  worker/raft/raftforwarder/manifold.go
  worker/raft/raftforwarder/manifold_test.go
  worker/raft/raftforwarder/worker.go
  worker/raft/raftforwarder/worker_test.go
  worker/raft/raftlease_mock_test.go
  worker/raft/worker.go
Labels: 2.9

#13482 [JUJU-136] enable juju_machine_lock to display unit machine lock status.
  agent/addons/addons.go
  agent/addons/addons_test.go
  agent/addons/package_test.go
  cmd/containeragent/unit/agent.go
  cmd/jujud/agent/caasoperator.go
  cmd/jujud/agent/machine.go
  cmd/jujud/agent/util_test.go
  cmd/jujud/introspect/introspect.go
  cmd/jujud/main.go
  featuretests/dblog_test.go
  featuretests/upgrade_test.go
  worker/deployer/unit_agent.go
  worker/introspection/script.go
Labels: 2.9

#13478 [JUJU-163]create openstack FIPs on networks on AZ to match the server's addresses.
  go.mod
  go.sum
  provider/openstack/local_test.go
  provider/openstack/network_mock_test.go
  provider/openstack/networking.go
  provider/openstack/networking_interfaces.go
  provider/openstack/networking_test.go
  provider/openstack/package_test.go
Labels: bug, 2.9

#13493 [JUJU-185] Use the correct ingress resource version for the k8s cluster
  caas/kubernetes/provider/ingress.go
  caas/kubernetes/provider/ingress_test.go
  caas/kubernetes/provider/specs/ingress.go
  caas/kubernetes/provider/specs/ingress_test.go
  caas/kubernetes/provider/specs/v3_test.go
Labels: 2.9

#13496 [JUJU-187] Improve the help text for --keep-broken flag
  cmd/juju/commands/bootstrap.go
Labels: 2.9

#13492 [JUJU-180] Correct affected unit reporting in upgrade-series
  cmd/juju/machine/upgradeseries.go
  cmd/juju/machine/upgradeseries_test.go
Labels: 2.9

#13488 [JUJU-117] Don't bake defaults when updating config.
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/application_unit_test.go
Labels: 2.9

#13480 Added Jammy series as supported.
  core/series/supported.go
  core/series/supportedseries_linux_test.go
  core/series/supportedseries_test.go
  go.mod
  go.sum
Labels: 2.9

#13504 [JUJU-195] Format logs for mongo version more nicely
  mongo/mongo.go
  mongo/mongo_test.go
Labels: 2.9

#13506 [JUJU-207] Apply synchronously, respond asynchronously
  worker/raft/apply.go
  worker/raft/worker.go
Labels: 2.9

#13502 [JUJU-199] Remove an an old legacy cmr fallback and add upgrade step
  apiserver/common/crossmodel/crossmodel.go
  apiserver/common/crossmodel/state.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations.go
  apiserver/facades/controller/crossmodelrelations/mock_test.go
  state/applicationoffers.go
  state/applicationoffers_test.go
  state/upgrades.go
  state/upgrades_test.go
  upgrades/backend.go
  upgrades/operations.go
  upgrades/steps_2919.go
  upgrades/steps_2919_test.go
  upgrades/upgrade_test.go
Labels: 2.9

#13508 [JUJU-176] Fix mongo service enable by using start not restart.
  mongo/mongo.go
Labels: 2.9

#13498 [JUJU-113] Refactor upgrade controller command
  api/client.go
  api/facadeversions.go
  api/state_test.go
  apiserver/allfacades.go
  apiserver/common/tools.go
  apiserver/facades/agent/provisioner/provisioner.go
  apiserver/facades/client/client/client.go
  apiserver/facades/client/client/client_test.go
  apiserver/facades/client/client/mocks/client_mock.go
  apiserver/facades/client/client/mocks/common_mock.go
  apiserver/facades/client/client/mocks/facade_mock.go
  apiserver/facades/client/client/package_test.go
  apiserver/facades/client/client/statushistory_test.go
  apiserver/facades/client/modelmanager/modelmanager.go
  apiserver/facades/controller/caasapplicationprovisioner/provisioner.go
  apiserver/facades/controller/caasmodeloperator/operator.go
  apiserver/facades/controller/caasoperatorprovisioner/provisioner.go
  apiserver/facades/schema.json
  cmd/juju/commands/mocks/client_mock.go
  cmd/juju/commands/synctools.go
  cmd/juju/commands/synctools_test.go
  cmd/juju/commands/upgradecontroller.go
  cmd/juju/commands/upgradecontroller_test.go
  cmd/juju/commands/upgrademodel.go
  cmd/juju/commands/upgrademodel_test.go
Labels: 2.9

#13515 Remove unused ExportModel method
  migration/migration.go
  migration/migration_test.go
Labels: 2.9

#13501 [JUJU-197] Raft lease retries with exceeded dropped
  api/raftlease/client.go
  api/raftlease/client_test.go
  core/lease/errors.go
  worker/lease/manager.go
Labels: 2.9

#13523 Logging for link-layer device updates
  apiserver/common/networkingcommon/linklayer.go
  apiserver/common/networkingcommon/mocks/package_mock.go
  apiserver/common/networkingcommon/networkconfigapi.go
  apiserver/common/networkingcommon/networkconfigapi_test.go
  apiserver/common/networkingcommon/types.go
  apiserver/facades/agent/provisioner/provisioninginfo_test.go
  apiserver/facades/controller/instancepoller/instancepoller.go
  apiserver/facades/controller/instancepoller/merge.go
  apiserver/facades/controller/instancepoller/mock_test.go
  state/machine.go
Labels: 2.9

#13522 [JUJU-214] Fixes re-downloading of caas charm on restart.
  worker/caasoperator/caasoperator.go
  worker/caasoperator/caasoperator_test.go
  worker/uniter/remotestate/watcher.go
  worker/uniter/remotestate/watcher_test.go
  worker/uniter/uniter.go
Labels: 2.9

#13524 Update to latest Pebble (auto-restart and backoff)
  go.mod
  go.sum
Labels: 2.9

#13490 [JUJU-121] Adds support for auto create of instance profiles.
  environs/bootstrap/bootstrap.go
  environs/broker.go
  environs/instancerole.go
  provider/common/bootstrap.go
  provider/ec2/client.go
  provider/ec2/config.go
  provider/ec2/environ.go
  provider/ec2/iam.go
  provider/ec2/iam_docs.go
  provider/ec2/iam_test.go
  provider/ec2/internal/testing/iam_server.go
  provider/ec2/internal/testing/instanceprofile.go
  provider/ec2/internal/testing/roles.go
  provider/lxd/environ_broker.go
  state/constraints.go
  state/migration_internal_test.go
Labels: 2.9

#13525 [JUJU-250] Update juju/replicaset/v2 dependency
  cmd/jujud/agent/agenttest/agent.go
  cmd/jujud/agent/machine.go
  go.mod
  go.sum
  mongo/mongo.go
Labels: 2.9

#13526 Add logging to txnpruner worker
  worker/txnpruner/txnpruner.go
Labels: 2.9

#13529 [JUJU-261] Add index for model and name to units collection
  state/allcollections.go
Labels: 2.9

#13536 [JUJU-272] Add model UUID indexes
  state/allcollections.go
  state/constraints.go
  state/multienv.go
Labels: 2.9
