Repository juju/juju, pull requests merged in 2022-09, with the labels that each got.

#14506 [JUJU-1674]remove cloud display python test
  acceptancetests/assess_cloud_display.py
Labels: 2.9

#14237 Lock podspec to focal
  api/controller/caasoperatorprovisioner/client.go
  apiserver/facades/controller/caasoperatorprovisioner/provisioner.go
  apiserver/facades/controller/caasoperatorprovisioner/provisioner_test.go
  apiserver/facades/schema.json
  caas/Dockerfile
  caas/broker.go
  caas/kubernetes/provider/controller_upgrade.go
  caas/kubernetes/provider/k8s.go
  caas/kubernetes/provider/operator.go
  caas/kubernetes/provider/operator_test.go
  caas/kubernetes/provider/operator_upgrade.go
  caas/kubernetes/provider/operator_upgrade_test.go
  caas/kubernetes/provider/package_test.go
  caas/kubernetes/provider/statefulsets.go
  caas/kubernetes/provider/upgrade.go
  caas/kubernetes/provider/upgrade_test.go
  caas/scripts.go
  cloudconfig/podcfg/image.go
  cloudconfig/podcfg/image_test.go
  rpc/params/params.go
  worker/caasoperatorprovisioner/worker.go
Labels: 3.0

#14548 [JUJU-1667] Remove add-subnet command
  api/client/subnets/subnets.go
  api/client/subnets/subnets_test.go
  api/facadeversions.go
  apiserver/facades/client/subnets/register.go
  apiserver/facades/client/subnets/subnets.go
  apiserver/facades/client/subnets/subnets_test.go
  apiserver/facades/schema.json
  cmd/juju/commands/main.go
  cmd/juju/commands/main_test.go
  cmd/juju/subnet/add.go
  cmd/juju/subnet/add_test.go
  cmd/juju/subnet/subnet.go
  featuretests/cmd_juju_subnet_test.go
Labels: 2.9

#14596 [JUJU-1751] [caas/exec] filter namespaces by model UUID
  caas/kubernetes/provider/exec/exec.go
  caas/kubernetes/provider/exec/exec_test.go
  cmd/juju/commands/export_test.go
  cmd/juju/commands/ssh_container.go
Labels: bug, 2.9

#14561 [JUJU-1563] fix bug 1983581 inconsistent series selection
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/bundlehandler_test.go
Labels: bug, 2.9

#14617 [JUJU-1816] give the state converter worker it's own manifold
  cmd/jujud/agent/engine_test.go
  cmd/jujud/agent/machine.go
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/agent/machine/manifolds_test.go
  cmd/jujud/agent/machine/stateflag.go
  worker/conv2state/converter_test.go
  worker/conv2state/fakes_test.go
  worker/stateconverter/converter.go
  worker/stateconverter/converter_test.go
  worker/stateconverter/interfaces.go
  worker/stateconverter/manifold.go
  worker/stateconverter/manifold_test.go
  worker/stateconverter/mocks/agent_mock.go
  worker/stateconverter/mocks/dependency_mock.go
  worker/stateconverter/mocks/machiner_mock.go
  worker/stateconverter/package_test.go
Labels: 2.9

#14611 [JUJU-1777] Exclude Fan IPs from API Addresses
  agent/agentbootstrap/bootstrap_test.go
  network/network.go
  network/network_test.go
  worker/apiaddressupdater/apiaddressupdater_test.go
  worker/machiner/machiner_test.go
Labels: 2.9

#14627 [JUJU-1189] Remove nw assess persistent storage python tests
  acceptancetests/assess_persistent_storage.py
Labels: 2.9

#14608 [JUJU-1635, JUJU-1782] Rewrite api/client/firewallrules unit tests to use gomock
  api/client/firewallrules/client_test.go
  api/client/firewallrules/package_test.go
  rpc/params/firewall.go
Labels: failed to land

#14612 [JUJU-1779]handle invalid login username gracefully
  juju/api.go
Labels: 2.9

#14628 [JUJU-1823] Bug 1990182 refresh cs to ch
  cmd/juju/application/deploy_test.go
  cmd/juju/application/utils/origin.go
  cmd/juju/application/utils/origin_test.go
  cmd/juju/application/utils/package_test.go
  core/charm/repository/charmhub.go
  core/charm/repository/charmhub_test.go
  core/charm/repository/package_test.go
Labels: bug, 2.9

#14626 [JUJU-1761] Developed the bash-based change-user-password test using the expect tool
  .github/workflows/smoke.yml
  .github/workflows/static-analysis.yml
  tests/includes/expect-that.sh
  tests/main.sh
  tests/suites/user/login_password.sh
  tests/suites/user/task.sh
Labels: 2.9

#14528 [JUJU-1700] Added --watch flag to watch status changes via Viddy tool
  cmd/juju/status/status.go
  cmd/juju/status/status_test.go
  go.mod
  go.sum
Labels: 3.0

#14642 [JUJU-1874] Remove Legacy LXC Support
  agent/agentbootstrap/bootstrap_test.go
  container/lxd/cluster.go
  container/lxd/container.go
  container/lxd/container_test.go
  network/containerizer/bridgepolicy.go
  network/containerizer/bridgepolicy_integration_test.go
  network/network.go
  network/network_test.go
  state/linklayerdevices_test.go
  worker/apiaddressupdater/apiaddressupdater_test.go
  worker/machiner/machiner_test.go
Labels: 3.0

#14659 [JUJU-1548] Default series for charms
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/charm.go
  cmd/juju/application/deployer/charm_test.go
  cmd/juju/application/deployer/series_selector.go
  cmd/juju/application/deployer/series_selector_test.go
  core/charm/repository/charmhub.go
  environs/bootstrap/prepare_test.go
  environs/config/config.go
  environs/config/config_test.go
  juju/testing/repo.go
  provider/dummy/environs.go
  state/initialize_test.go
  state/migration_import.go
  state/migration_import_test.go
  state/modelsummaries_test.go
  state/upgrades.go
  state/upgrades_test.go
  testing/environ.go
  testing/factory/factory_test.go
  upgrades/backend.go
  upgrades/operations.go
  upgrades/steps_2935.go
  upgrades/steps_2935_test.go
  upgrades/upgrade_test.go
Labels: bug, 2.9

#14667 [JUJU-1876] do not present %%s or %s to lxd via cloudinit
  cloudconfig/cloudinit/cloudinit_test.go
  cloudconfig/cloudinit/cloudinit_ubuntu.go
  cloudconfig/cloudinit/network_ubuntu.go
  cloudconfig/cloudinit/network_ubuntu_test.go
  cloudconfig/cloudinit/utils.go
  cloudconfig/providerinit/providerinit_test.go
  cloudconfig/userdatacfg_test.go
  cloudconfig/userdatacfg_unix.go
  provider/ec2/local_test.go
Labels: bug, 2.9

#14663 [JUJU-1857] Discover manual cloud subnets on loopback device
  api/common/network.go
  api/common/network_test.go
  apiserver/common/networkingcommon/networkconfigapi.go
  apiserver/common/networkingcommon/networkconfigapi_test.go
Labels: 2.9

#14653 [JUJU-1859] Remove Lease Trapdoor
  api/watcher/watcher_test.go
  apiserver/common/crossmodel/state.go
  apiserver/common/getstatus_test.go
  apiserver/common/secrets/secrets.go
  apiserver/common/setstatus.go
  apiserver/facades/agent/secretsmanager/access.go
  apiserver/facades/agent/secretsmanager/mocks/leadershipchecker.go
  apiserver/facades/agent/secretsmanager/secrets_test.go
  apiserver/facades/agent/uniter/status.go
  apiserver/facades/agent/uniter/uniter.go
  apiserver/facades/agent/uniter/uniter_test.go
  apiserver/leadership.go
  core/leadership/interface.go
  core/lease/interface.go
  core/raftlease/store.go
  core/raftlease/store_test.go
  provider/dummy/environs.go
  provider/dummy/leasestore.go
  state/application_leader_test.go
  state/leadership.go
  state/migration_export_test.go
  state/raftlease/target.go
  state/raftlease/target_test.go
  state/relation_test.go
  state/state.go
  worker/lease/check.go
  worker/lease/manager.go
  worker/lease/manager_block_test.go
  worker/lease/manager_check_test.go
  worker/lease/manager_cross_test.go
  worker/lease/manager_validation_test.go
  worker/lease/manifold/manifold.go
  worker/lease/manifold/manifold_test.go
  worker/uniter/runner/context/flush_test.go
  worker/uniter/util_test.go
Labels: 3.0
