Repository juju/juju, pull requests merged in 2022-12, with the labels that each got.

#14953 [JUJU-2279] Added confirmation to destroy-model in 3.0
  cmd/juju/model/destroy.go
  cmd/juju/model/destroy_test.go
  tests/includes/juju.sh
  tests/suites/cli/block.sh
  tests/suites/secrets_k8s/k8s.sh
Labels: 3.0

#14962 [JUJU-2260] Revert "[JUJU-2251] Added skip-confirmation parameter to controller-config."
  controller/config.go
Labels: 3.0

#14969 [JUJU-2302] Adds support for ubuntu pro images with google cloud provider
  provider/gce/environ_broker.go
  provider/gce/environ_broker_test.go
  provider/gce/export_test.go
  provider/gce/gce.go
Labels: bug, 2.9

#14984 [JUJU-2312] Remove cs-channel from application doc.
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/application_unit_test.go
  apiserver/facades/client/application/backend.go
  apiserver/facades/client/application/deploy.go
  apiserver/facades/client/application/get.go
  apiserver/facades/client/application/mocks/application_mock.go
  apiserver/facades/client/application/updateseries_mocks_test.go
  apiserver/facades/client/client/status.go
  apiserver/facades/controller/charmrevisionupdater/interface.go
  apiserver/facades/controller/charmrevisionupdater/interface_test.go
  apiserver/facades/controller/charmrevisionupdater/mocks/mocks.go
  apiserver/facades/controller/charmrevisionupdater/updater.go
  state/application.go
  state/export_test.go
  state/migration_export.go
  state/migration_import.go
  state/migration_import_test.go
  state/migration_internal_test.go
  state/state.go
  testing/factory/factory.go
Labels: feature, 3.1

#14979 [JUJU-2240] disallow migration or upgrade of a model to 3.1 if charm store charms used in model
  apiserver/facades/client/modelupgrader/mocks/state_mock.go
  apiserver/facades/client/modelupgrader/shims.go
  apiserver/facades/client/modelupgrader/upgrader_test.go
  apiserver/facades/controller/migrationmaster/mocks/precheckbackend.go
  migration/precheck.go
  migration/precheck_test.go
  state/charm.go
  state/charm_test.go
  upgrades/upgradevalidation/interfaces.go
  upgrades/upgradevalidation/migrate.go
  upgrades/upgradevalidation/migrate_test.go
  upgrades/upgradevalidation/mocks/state_mock.go
  upgrades/upgradevalidation/package_test.go
  upgrades/upgradevalidation/upgrade.go
  upgrades/upgradevalidation/upgrade_test.go
  upgrades/upgradevalidation/validation.go
  upgrades/upgradevalidation/validation_test.go
Labels: feature, 3.0

#14974 [JUJU-2340] Fixes upgrade bugs for sidecar charms in 2.9
  api/controller/caasapplicationprovisioner/client.go
  apiserver/facades/controller/caasapplicationprovisioner/mock_test.go
  apiserver/facades/controller/caasapplicationprovisioner/provisioner.go
  apiserver/facades/controller/caasapplicationprovisioner/state.go
  apiserver/facades/schema.json
  caas/application.go
  caas/kubernetes/provider/application.go
  caas/kubernetes/provider/application/application.go
  caas/kubernetes/provider/application/application_test.go
  caas/kubernetes/provider/application/scale_test.go
  caas/kubernetes/provider/upgrade.go
  caas/mocks/application_mock.go
  worker/caasapplicationprovisioner/application.go
  worker/caasapplicationprovisioner/application_test.go
  worker/caasapplicationprovisioner/mocks/facade_mock.go
  worker/caasapplicationprovisioner/worker.go
Labels: failed to land, 2.9

#14994 [JUJU-2242] Remove support for charm store charms the resources package.
  resource/charmstore.go
  resource/charmstore_test.go
  resource/opener.go
  resource/retryclient.go
Labels: feature, 3.1

#14992 [JUJU-2241] Reword charm resource origin store in output
  cmd/juju/resource/formatter.go
  cmd/juju/resource/formatter_test.go
  cmd/juju/resource/list_test.go
  cmd/juju/resource/output_tabular_test.go
Labels: 3.1

#14993 [JUJU-2235] Remove support for charm store charms from resources command.
  cmd/juju/resource/charmresources.go
  cmd/juju/resource/charmresources_test.go
  cmd/juju/resource/deploy.go
  cmd/juju/resource/deploy_test.go
  cmd/juju/resource/list.go
  cmd/juju/resource/list_test.go
  featuretests/cmd_juju_resources_test.go
Labels: feature, 3.1

#14998 [JUJU-2116]: Store default-base in model-config
  apiserver/facades/client/modelconfig/modelconfig.go
  apiserver/facades/client/modelconfig/modelconfig_test.go
  apiserver/facades/client/modelmanager/modelinfo_test.go
  apiserver/facades/client/modelmanager/modelmanager.go
  apiserver/facades/schema.json
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/charm.go
  cmd/juju/application/deployer/charm_test.go
  cmd/juju/application/deployer/series_selector.go
  cmd/juju/application/deployer/series_selector_test.go
  cmd/juju/commands/bootstrap.go
  cmd/juju/commands/bootstrap_test.go
  cmd/juju/controller/addmodel.go
  cmd/juju/model/config.go
  cmd/juju/model/defaults.go
  cmd/plugins/juju-metadata/imagemetadata.go
  core/charm/repository/charmhub.go
  core/series/base.go
  core/series/supportedbases.go
  core/series/supportedbases_test.go
  core/series/validate.go
  core/series/validate_test.go
  environs/bootstrap/bootstrap.go
  environs/bootstrap/bootstrap_test.go
  environs/bootstrap/tools.go
  environs/bootstrap/tools_test.go
  environs/config/config.go
  environs/config/config_test.go
  environs/jujutest/livetests.go
  environs/jujutest/tests.go
  environs/open_test.go
  juju/testing/conn.go
  juju/testing/instance.go
  jujuclient/mem.go
  provider/azure/environ_test.go
  provider/common/bootstrap.go
  provider/common/bootstrap_test.go
  provider/dummy/environs_test.go
  provider/ec2/environ.go
  provider/ec2/local_test.go
  provider/maas/maas_environ_whitebox_test.go
  provider/openstack/local_test.go
  provider/openstack/provider.go
  rpc/params/model.go
  state/migration_import.go
  state/migration_import_test.go
  state/modelsummaries.go
  testing/environ.go
  testing/factory/factory_test.go
  tests/main.sh
Labels: 3.1
