Repository juju/juju, pull requests merged in 2022-11, with the labels that each got.

#14810 [JUJU-2024] avoid microk8s permission check when bootstrapping lxd
  caas/kubernetes/provider/detectcloud.go
Labels: 3.0

#14568 equinix: set default deny iptables policy
  go.mod
  go.sum
  provider/equinix/environ.go
  provider/equinix/environ_test.go
  provider/equinix/mocks/packngo.go
Labels: 2.9

#14861 [JUJU-2098] Fixed test-relation-data-exchange and test-relation-list-app in 3 0
  tests/suites/relations/relation_data_exchange.sh
  tests/suites/relations/relation_list_app.sh
Labels: 3.0

#14825 [JUJU-1929] Bash tests for secrets
  tests/main.sh
  tests/suites/secrets_iaas/juju.sh
  tests/suites/secrets_iaas/task.sh
  tests/suites/secrets_iaas/vault.sh
  tests/suites/secrets_k8s/k8s.sh
  tests/suites/secrets_k8s/task.sh
Labels: 3.0

#14880 [JUJU-2022] Fixed COSlite intergration test
  tests/includes/wait-for.sh
  tests/suites/coslite/cl.sh
  tests/suites/coslite/task.sh
Labels: 2.9

#14893 [JUJU-2170] Fixed juju run action command for coslite test in 3.0
  tests/suites/coslite/cl.sh
Labels: 3.0

#14892 K8s proxy support4register controller2.9
  api/apiclient.go
  apiserver/package_test.go
  apiserver/registration.go
  apiserver/registration_environs_mock_test.go
  apiserver/registration_proxy_mock_test.go
  apiserver/registration_test.go
  caas/kubernetes/provider/proxy/package_test.go
  caas/kubernetes/provider/proxy/proxier.go
  caas/kubernetes/provider/proxy/proxier_test.go
  cmd/juju/controller/register.go
  cmd/juju/controller/register_test.go
  cmd/juju/user/add.go
  cmd/juju/user/add_test.go
  cmd/juju/user/change_password.go
  cmd/juju/user/package_test.go
  cmd/juju/user/utils.go
  cmd/juju/user/utils_clientstore_mock_test.go
  cmd/juju/user/utils_controllercommand_mock_test.go
  cmd/juju/user/utils_test.go
  cmd/modelcmd/base.go
  go.mod
  go.sum
  jujuclient/package_test.go
  jujuclient/proxy.go
  jujuclient/proxy_mock_test.go
  jujuclient/proxy_test.go
  jujuclient/registration.go
  proxy/factory.go
  proxy/proxy.go
  proxy/testing/proxy.go
  rpc/params/proxy.go
  rpc/params/registration.go
Labels: bug, 2.9

#14899 [JUJU-2198] Juju status with selector matching on ports substring #2
  apiserver/facades/client/client/filtering.go
  apiserver/facades/client/client/filtering_test.go
Labels: bug, 2.9

#14924 [gh-actions] replace local setup-lxd action with canonical/setup-lxd
  .github/setup-lxd/action.yml
  .github/workflows/smoke.yml
  .github/workflows/snap.yml
  .github/workflows/upgrade.yml
Labels: dependencies, 2.9, github_actions

#14943 [JUJU-2277] Added --no-prompt flag to destroy-model
  cmd/juju/model/destroy.go
Labels: 2.9
