Repository juju/juju, pull requests merged in 2022-07, with the labels that each got.

#14219 [JUJU-1379] Preserve order of relations in bundles
  apiserver/facades/client/bundle/bundle_test.go
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/bundlehandler_test.go
  core/bundle/changes/changes.go
  core/bundle/changes/changes_test.go
  core/bundle/changes/changessort_test.go
Labels: 3.0

#14248 fixed charm channel issue in test-trusted-bundles-deploy-aws
  tests/suites/deploy/deploy_bundles.sh
Labels: bug, 2.9

#14247 Fix type in add-cloud help doc
  cmd/juju/cloud/add.go
Labels: 2.9

#14242 [JUJU-1386] Upgrade step to remove use-floating-ip=false from config.
  state/upgrades.go
  state/upgrades_test.go
  upgrades/backend.go
  upgrades/operations.go
  upgrades/steps_2933.go
  upgrades/steps_2933_test.go
  upgrades/upgrade_test.go
Labels: 2.9

#14175 [JUJU-1338] Uniter charmurl string
  api/agent/uniter/application.go
  api/agent/uniter/application_test.go
  api/agent/uniter/unit.go
  api/agent/uniter/unit_test.go
  worker/uniter/op_callbacks.go
  worker/uniter/operation/deploy.go
  worker/uniter/operation/deploy_test.go
  worker/uniter/operation/errors.go
  worker/uniter/operation/factory.go
  worker/uniter/operation/factory_test.go
  worker/uniter/operation/failaction_test.go
  worker/uniter/operation/interface.go
  worker/uniter/operation/mocks/interface_mock.go
  worker/uniter/operation/runaction_test.go
  worker/uniter/operation/state.go
  worker/uniter/operation/state_test.go
  worker/uniter/operation/util_test.go
  worker/uniter/remotestate/mock_test.go
  worker/uniter/remotestate/snapshot.go
  worker/uniter/remotestate/state.go
  worker/uniter/remotestate/watcher.go
  worker/uniter/remotestate/watcher_test.go
  worker/uniter/resolver.go
  worker/uniter/resolver/interface.go
  worker/uniter/resolver/loop.go
  worker/uniter/resolver/loop_test.go
  worker/uniter/resolver/mock_test.go
  worker/uniter/resolver/opfactory.go
  worker/uniter/resolver/opfactory_test.go
  worker/uniter/resolver_test.go
  worker/uniter/runcommands/runcommands_test.go
  worker/uniter/runner/context/util_test.go
  worker/uniter/uniter.go
  worker/uniter/verifycharmprofile/verifycharmprofile.go
  worker/uniter/verifycharmprofile/verifycharmprofile_test.go
Labels: 2.9

#14231 [JUJU-1385] Remove deprecated openstack config: use-floating-ip.
  cmd/juju/cloud/show_test.go
  provider/openstack/config.go
  provider/openstack/config_test.go
  provider/openstack/local_test.go
  provider/openstack/provider.go
  provider/openstack/provider_configurator.go
  tests/includes/juju.sh
Labels: 3.0

#14204 Destroy controller unit on controller machine destroy.
  state/cleanup.go
  state/cleanup_test.go
  state/conn_test.go
  state/export_test.go
  state/machine.go
  state/machine_test.go
  state/unit.go
Labels: 3.0

#14244 [JUJU-1400] Migrate allocate public ip constraint
  go.mod
  go.sum
  state/migration_export.go
  state/migration_import.go
Labels: bug, 2.9

#14102 [JUJU-1222] Update LXD dependency to the latest 5.3 release
  container/lxd/certificate.go
  container/lxd/container_test.go
  container/lxd/logger.go
  container/lxd/server.go
  container/lxd/testing/lxd_mock.go
  go.mod
  go.sum
  provider/lxd/credentials.go
  provider/lxd/credentials_test.go
  provider/maas/maas2storage.go
  service/discovery.go
  service/service_test.go
Labels: 2.9

#14123 [JUJU-1182] Remove k8s provider state storage
  caas/kubernetes/provider/storage.go
  caas/kubernetes/provider/storage_test.go
  provider/azure/storage.go
  provider/ec2/ebs.go
  provider/gce/disks.go
  provider/lxd/storage.go
  provider/maas/volumes.go
  provider/oci/storage.go
  provider/openstack/cinder.go
  state/storage.go
  storage/constants.go
  storage/interface.go
  storage/provider/dummy/provider.go
  storage/provider/k8s_validation.go
  storage/provider/loop.go
  storage/provider/rootfs.go
  storage/provider/tmpfs.go
Labels: 3.0

#14261 [JUJU-1107] new color scheme for juju run
  cmd/juju/action/common.go
  cmd/juju/action/run.go
  cmd/output/output.go
Labels: 3.0

#14209 [JUJU-1360] Rewrite machinemanager tests
  apiserver/facades/client/machinemanager/export_test.go
  apiserver/facades/client/machinemanager/instance_information_test.go
  apiserver/facades/client/machinemanager/machinemanager.go
  apiserver/facades/client/machinemanager/machinemanager_test.go
  apiserver/facades/client/machinemanager/mocks/environ_mock.go
  apiserver/facades/client/machinemanager/mocks/instance_config_mock.go
  apiserver/facades/client/machinemanager/mocks/state_mock.go
  apiserver/facades/client/machinemanager/mocks/state_storage_mock.go
  apiserver/facades/client/machinemanager/mocks/types_mock.go
  apiserver/facades/client/machinemanager/mocks/upgradeseries_mock.go
  apiserver/facades/client/machinemanager/mocks/volume_access_mock.go
  apiserver/facades/client/machinemanager/package_test.go
  apiserver/facades/client/machinemanager/state.go
  apiserver/facades/client/machinemanager/upgradeseries_test.go
Labels: 2.9

#14290 Block upgrading cloud-init deb during cloud-init.
  cloudconfig/cloudinit/cloudinit_ubuntu.go
Labels: 2.9

#14288 [JUJU-1430] CMR connection closure error logging and simplification
  worker/firewaller/manifold.go
  worker/firewaller/manifold_test.go
  worker/firewaller/shim.go
  worker/remoterelations/manifold.go
  worker/remoterelations/manifold_test.go
  worker/remoterelations/remoteapplicationworker.go
  worker/remoterelations/shim.go
Labels: 2.9

#14280 [JUJU-1334] Reduce http client instances
  apiserver/apiserver.go
  apiserver/facade/facadetest/context.go
  apiserver/facade/interface.go
  apiserver/facades/client/application/application.go
  apiserver/facades/client/charms/client.go
  apiserver/facades/client/charms/client_test.go
  apiserver/facades/client/charms/register.go
  apiserver/facades/client/charms/services/downloader.go
  apiserver/facades/client/machinemanager/machinemanager.go
  apiserver/facades/client/resources/facade.go
  apiserver/facades/controller/caasmodelconfigmanager/mocks/context_mock.go
  apiserver/facades/controller/charmdownloader/charmdownloader.go
  apiserver/facades/controller/charmdownloader/register.go
  apiserver/facades/controller/charmrevisionupdater/register.go
  apiserver/facades/controller/raftlease/raft_mock_test.go
  apiserver/root.go
  apiserver/shared.go
  apiserver/testserver/server.go
  cmd/jujud/agent/controllercharm.go
  cmd/jujud/agent/engine_test.go
  cmd/jujud/agent/machine.go
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/agent/machine/manifolds_test.go
  worker/apiserver/manifold.go
  worker/apiserver/manifold_test.go
  worker/apiserver/worker.go
  worker/apiserver/worker_state_test.go
  worker/apiserver/worker_test.go
  worker/proxyupdater/proxyupdater.go
Labels: do not merge

#14324 [JUJU-1460] Recreated ubuntu test charm.
  tests/suites/smoke/charms/ubuntu/.gitignore
  tests/suites/smoke/charms/ubuntu/.jujuignore
  tests/suites/smoke/charms/ubuntu/LICENSE
  tests/suites/smoke/charms/ubuntu/README.md
  tests/suites/smoke/charms/ubuntu/charmcraft.yaml
  tests/suites/smoke/charms/ubuntu/copyright
  tests/suites/smoke/charms/ubuntu/icon.svg
  tests/suites/smoke/charms/ubuntu/metadata.yaml
  tests/suites/smoke/charms/ubuntu/requirements.txt
  tests/suites/smoke/charms/ubuntu/revision
  tests/suites/smoke/charms/ubuntu/src/charm.py
Labels: 3.0

#14302 [JUJU-1441]Status_panic_when_status_color_is_unknown
  cmd/output/output.go
  cmd/output/output_test.go
  cmd/output/package_test.go
Labels: 3.0

#14319 [JUJU-1448] Fix charm download with forced series during deploy
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/application_test.go
  apiserver/facades/client/client/testing/suite.go
  apiserver/facades/controller/charmdownloader/charmdownloader.go
  apiserver/facades/controller/charmdownloader/charmdownloader_test.go
  apiserver/facades/controller/charmdownloader/interfaces.go
  apiserver/facades/controller/charmdownloader/mocks.go
  apiserver/facades/controller/charmdownloader/shims.go
  core/charm/origin.go
  core/charm/repository/charmhub.go
  core/charm/repository/charmhub_test.go
  state/application.go
  state/application_test.go
  state/charm.go
  state/state.go
  state/state_test.go
Labels: bug, 3.0

#14326 [JUJU-1451] exec: print output for multiple units
  cmd/juju/action/common.go
  cmd/juju/action/exec.go
  cmd/juju/action/exec_test.go
Labels: 3.0

#14334 Force focal for cli block integration tests
  tests/suites/cli/block.sh
Labels: 3.0

#14330 [Juju 1438] Merge develop and update semver
  apiserver/logsink/filewriter.go
  cmd/jujud/agent/caasoperator_test.go
  cmd/jujud/agent/machine.go
  cmd/jujud/agent/machine_test.go
  core/auditlog/auditlog.go
  core/charm/repository/charmhub_test.go
  core/machinelock/machinelock.go
  go.mod
  go.sum
  testcharms/charms/dummy-sink/README
  testcharms/charms/dummy-sink/actions.yaml
  testcharms/charms/dummy-sink/actions/echo
  testcharms/charms/dummy-sink/charmcraft.yaml
  testcharms/charms/dummy-sink/config.yaml
  testcharms/charms/dummy-sink/copyright
  testcharms/charms/dummy-sink/hooks/config-changed
  testcharms/charms/dummy-sink/hooks/install
  testcharms/charms/dummy-sink/hooks/post-series-upgrade
  testcharms/charms/dummy-sink/hooks/pre-series-upgrade
  testcharms/charms/dummy-sink/hooks/source-relation-changed
  testcharms/charms/dummy-sink/hooks/start
  testcharms/charms/dummy-sink/metadata.yaml
  testcharms/charms/dummy-source/README
  testcharms/charms/dummy-source/actions.yaml
  testcharms/charms/dummy-source/actions/echo
  testcharms/charms/dummy-source/charmcraft.yaml
  testcharms/charms/dummy-source/config.yaml
  testcharms/charms/dummy-source/copyright
  testcharms/charms/dummy-source/hooks/config-changed
  testcharms/charms/dummy-source/hooks/install
  testcharms/charms/dummy-source/hooks/sink-relation-joined
  testcharms/charms/dummy-source/hooks/start
  testcharms/charms/dummy-source/metadata.yaml
  testcharms/charms/network-health/README.ex
  testcharms/charms/network-health/actions.yaml
  testcharms/charms/network-health/actions/ping
  testcharms/charms/network-health/actions/ping.py
  testcharms/charms/network-health/actions/unit-info
  testcharms/charms/network-health/actions/unit-info.py
  testcharms/charms/network-health/charmcraft.yaml
  testcharms/charms/network-health/layer.yaml
  testcharms/charms/network-health/metadata.yaml
  testcharms/charms/network-health/reactive/network-health.py
  testcharms/charms/network-health/scripts/simple-server.py
  tests/suites/model/migration.sh
  worker/deployer/unit_agent.go
Labels: do not merge, 3.0

#14349 [JUJU-1476] Fix deploy resource by revision
  apiserver/facades/client/resources/repository.go
  cmd/juju/resource/deploy.go
Labels: bug, 3.0

#14353 [smoke test] use jammy
  .github/workflows/smoke.yml
  tests/suites/smoke/deploy.sh
Labels: 3.0

#14356 [juju-1483] Use requested resource revision
  resource/charmhub.go
  resource/charmhub_test.go
  tests/suites/deploy/deploy_revision.sh
Labels: bug, 2.9

#14348 [JUJU-1200] Complete coverage of nw model migration test in bash tests
  tests/includes/check.sh
  tests/main.sh
  tests/suites/constraints/constraints.sh
  tests/suites/constraints/constraints_lxd.sh
  tests/suites/constraints/constraints_vm.sh
  tests/suites/constraints/task.sh
  tests/suites/model/migration.sh
  tests/suites/network/network_health.sh
Labels: 2.9

#14309 [JUJU-1402] Search through existing relations when removing
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/application_unit_test.go
  apiserver/facades/client/application/backend.go
  apiserver/facades/client/application/mock_test.go
  featuretests/cmd_juju_relation_test.go
  state/application.go
  state/remoteapplication.go
  state/state.go
  state/state_test.go
  state/unit.go
  testcharms/charm-repo/quantal/mysql-alternative/metadata.yaml
Labels: 2.9

#14323 [JUJU-1372] Rewrite instanceconfig_test.go JujuConnSuite tests
  apiserver/facades/client/machinemanager/instanceconfig.go
  apiserver/facades/client/machinemanager/instanceconfig_test.go
  apiserver/facades/client/machinemanager/machinemanager_test.go
  apiserver/facades/client/machinemanager/mocks/instance_config_mock.go
  apiserver/facades/client/machinemanager/package_test.go
Labels: 2.9

#14351 [JUJU-1481] Check superuser for ssh access.
  apiserver/facades/client/sshclient/facade.go
  apiserver/facades/client/sshclient/facade_test.go
  apiserver/facades/client/sshclient/register.go
  apiserver/facades/client/sshclient/shim.go
Labels: 2.9

#14371 [JUJU-1499] State debug-log decoupling
  apiserver/debuglog_db.go
  apiserver/debuglog_db_internal_test.go
  apiserver/logstream.go
  apiserver/logstream_test.go
  cmd/jujud/dumplogs/dumplogs.go
  core/logger/tailer.go
  state/logs.go
  state/logs_test.go
Labels: 3.0

#14380 [JUJU-1518] Bump instance-poller intervals for instances not found
  worker/instancepoller/worker.go
  worker/instancepoller/worker_test.go
Labels: 2.9

#14381 [JUJU-1519] Lazy LXD activation
  container/factory/factory.go
  container/factory/factory_test.go
  container/interface.go
  container/lxd/export_test.go
  container/lxd/manager.go
  container/lxd/manager_test.go
  container/lxd/server.go
Labels: 2.9

#14344 [JUJU-1401] Move find tools logic from command side to controller;
  api/client/metricsdebug/client.go
  api/client/modelupgrader/mocks/apibase_mock.go
  api/client/modelupgrader/mocks/context_mock.go
  api/client/modelupgrader/mocks/httprequest_mock.go
  api/client/modelupgrader/package_test.go
  api/client/modelupgrader/upgrader.go
  api/client/modelupgrader/upgrader_test.go
  apiserver/facades/client/modelupgrader/findtools.go
  apiserver/facades/client/modelupgrader/mocks/common_mock.go
  apiserver/facades/client/modelupgrader/mocks/state_mock.go
  apiserver/facades/client/modelupgrader/package_test.go
  apiserver/facades/client/modelupgrader/register.go
  apiserver/facades/client/modelupgrader/shims.go
  apiserver/facades/client/modelupgrader/upgrader.go
  apiserver/facades/client/modelupgrader/upgrader_test.go
  apiserver/facades/schema.json
  cmd/juju/commands/bootstrap_test.go
  cmd/juju/commands/main.go
  cmd/juju/commands/main_test.go
  cmd/juju/commands/mocks/jujuclient_mock.go
  cmd/juju/commands/mocks/modelconfig_mock.go
  cmd/juju/commands/mocks/modelupgrader_mock.go
  cmd/juju/commands/mocks/synctool_mock.go
  cmd/juju/commands/package_test.go
  cmd/juju/commands/synctools.go
  cmd/juju/commands/synctools_test.go
  cmd/juju/commands/upgradecontroller.go
  cmd/juju/commands/upgradecontroller_test.go
  cmd/juju/commands/upgrademodel.go
  cmd/juju/commands/upgrademodel_test.go
  environs/bootstrap/bootstrap.go
  environs/bootstrap/bootstrap_test.go
  environs/jujutest/livetests.go
  environs/sync/sync.go
  environs/sync/sync_test.go
  environs/tools/build.go
  environs/tools/build_test.go
  environs/tools/testing/testing.go
  provider/azure/environ_test.go
  rpc/params/model.go
  worker/upgrader/upgrader.go
Labels: 2.9

#14386 Backport: Upgrade golint to 1.4.6
  .github/workflows/static-analysis.yml
  tests/suites/static_analysis/lint_go.sh
Labels: 2.9

#14392 [JUJU01492] Ensure AddCharm has a series
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/bundlehandler_test.go
  cmd/juju/application/deployer/charm.go
  cmd/juju/application/deployer/deployer.go
Labels: bug, 2.9

#14362 [JUJU-1513] migrate assess_upgrade_series.py to bash
  acceptancetests/assess
  acceptancetests/assess_upgrade_series.py
  testcharms/charms/dummy-sink/hooks/post-series-upgrade
  testcharms/charms/dummy-sink/hooks/pre-series-upgrade
  testcharms/charms/dummy-sink/hooks/source-relation-changed
  testcharms/charms/dummy-sink/hooks/start
  testcharms/charms/dummy-sink/scripts/check-token
  tests/suites/upgrade_series/series.sh
  tests/suites/upgrade_series/task.sh
Labels: do not merge, 2.9

#14298 Move to sstxns.log (non-capped collection) + improvements to sstxn retry/error handling.
  apiserver/errors/errors.go
  apiserver/errors/errors_test.go
  apiserver/facades/client/applicationoffers/applicationoffers.go
  apiserver/facades/client/cloud/cloud.go
  apiserver/facades/client/controller/controller.go
  apiserver/facades/client/modelmanager/modelmanager.go
  apiserver/facades/schema.json
  go.mod
  go.sum
  rpc/params/model.go
  scripts/juju-blobstore-cleanup/main.go
  scripts/mgo-run-txn/main.go
  state/action_test.go
  state/allcollections.go
  state/applicationoffers_test.go
  state/assign_test.go
  state/binarystorage/binarystorage_test.go
  state/cloudimagemetadata/image_test.go
  state/database.go
  state/export_test.go
  state/imagestorage/image.go
  state/imagestorage/image_test.go
  state/initialize.go
  state/leaseupgrades.go
  state/linklayerdevices_test.go
  state/machine_ports_test.go
  state/machine_test.go
  state/migration_internal_test.go
  state/model.go
  state/open.go
  state/pool.go
  state/raftlease/target_test.go
  state/state.go
  state/state_test.go
  state/unit_test.go
  state/watcher/logger.go
  state/watcher/txnwatcher.go
  state/watcher/txnwatcher_test.go
  upgrades/upgradevalidation/version.go
  upgrades/upgradevalidation/version_test.go
Labels: 3.0
