Repository juju/juju, pull requests merged in 2022-06, with the labels that each got.

#14090 [JUJU-1174] [config commands] Allow simultaneously setting, resetting, setting from file
  cmd/juju/application/config.go
  cmd/juju/application/config_test.go
  cmd/juju/config/config.go
  cmd/juju/config/config_test.go
  cmd/juju/controller/configcommand.go
  cmd/juju/controller/configcommand_test.go
  cmd/juju/model/config.go
  cmd/juju/model/config_test.go
  cmd/juju/model/defaults.go
  cmd/juju/model/defaults_test.go
  cmd/juju/model/fakeenv_test.go
Labels: 3.0

#14107 [JUJU-1220] Add tests to cover GetManifests not found case;
  apiserver/facades/client/client/client_test.go
  docker/registry/internal/base_manifests_test.go
Labels: 2.9

#14086 [JUJU-1187] Move consts in bootstrap to provider constants
  .github/workflows/smoke.yml
  agent/agentbootstrap/bootstrap.go
  caas/kubernetes/provider/bootstrap.go
  caas/kubernetes/provider/connection.go
  caas/kubernetes/provider/constants/constants.go
  caas/kubernetes/provider/controller_upgrade_test.go
  caas/kubernetes/provider/k8s.go
  cmd/juju/commands/bootstrap.go
  state/address.go
Labels: 3.0

#14052 [JUJU-1083] Make tests upgrade from 2.8
  .github/reg.yml
  .github/verify-elasticsearch-k8s.sh
  .github/workflows/smoke.yml
Labels: 2.9

#14122 [JUJU-1248] Fix race in state upgrade test TestFixCharmhubLastPollTime
  state/state.go
  state/upgrades_test.go
Labels: 2.9

#14120 [JUJU-1177] Drop JujuConnSuite from apiserver/common/tools_test.go
  apiserver/common/mocks/environs.go
  apiserver/common/mocks/storage.go
  apiserver/common/mocks/tools_mock.go
  apiserver/common/package_test.go
  apiserver/common/tools.go
  apiserver/common/tools_test.go
  apiserver/facades/agent/provisioner/provisioner.go
  apiserver/facades/agent/upgrader/upgrader.go
Labels: 2.9

#14134 Add a juju_apiserver_build_info metric
  apiserver/apiservermetrics.go
  apiserver/apiservermetrics_test.go
Labels: 2.9

#14130 [JUJU-1253] Restore stdin support for config commands
  cmd/juju/application/config.go
  cmd/juju/config/config.go
  cmd/juju/config/config_test.go
  cmd/juju/controller/config.go
  cmd/juju/controller/config_test.go
  cmd/juju/model/config.go
  cmd/juju/model/config_test.go
  cmd/juju/model/defaults.go
  cmd/juju/model/defaults_test.go
Labels: 3.0

#14133 [JUJU-1261] Bye bye rackspace
  apiserver/facades/client/cloud/cloud_test.go
  caas/kubernetes/metadata.go
  featuretests/cmd_juju_cloud_test.go
  featuretests/cmd_juju_credential_test.go
  provider/all/rackspace.go
  provider/openstack/networking_interfaces.go
  provider/openstack/provider.go
  provider/rackspace/config_test.go
  provider/rackspace/credentials.go
  provider/rackspace/credentials_test.go
  provider/rackspace/environ.go
  provider/rackspace/environ_test.go
  provider/rackspace/errors.go
  provider/rackspace/export_test.go
  provider/rackspace/firewaller.go
  provider/rackspace/flavors.go
  provider/rackspace/flavors_test.go
  provider/rackspace/init.go
  provider/rackspace/instance_information.go
  provider/rackspace/networking.go
  provider/rackspace/package_test.go
  provider/rackspace/provider.go
  provider/rackspace/provider_configurator.go
  provider/rackspace/provider_test.go
Labels: 3.0

#14101 [JUJU-1104]add_no_color_flag
  cmd/juju/status/output_tabular.go
  cmd/juju/status/status.go
  cmd/juju/status/status_internal_test.go
  cmd/juju/status/status_test.go
  featuretests/cmd_juju_status_test.go
Labels: 3.0

#14143 [JUJU-1281] Remove unused CharmMeta interface
  apiserver/facades/client/application/backend.go
  apiserver/facades/client/application/package_test.go
  apiserver/facades/client/application/updateseries_mocks_test.go
Labels: 2.9

#14118 [JUJU-1236] Get kubeconfig from content interface file
  caas/kubernetes/provider/builtin.go
  caas/kubernetes/provider/builtin_test.go
  caas/kubernetes/provider/cloud.go
  caas/kubernetes/provider/cloud_test.go
  caas/kubernetes/provider/detectcloud_test.go
  caas/kubernetes/provider/export_test.go
  caas/kubernetes/provider/k8s.go
  caas/kubernetes/provider/provider.go
  caas/kubernetes/provider/teardown.go
  caas/kubernetes/provider/volume.go
  snap/snapcraft.yaml
Labels: 2.9

#14152 [JUJU-1291] Upgrade golint to 1.4.6
  .github/workflows/static-analysis.yml
  tests/suites/static_analysis/lint_go.sh
Labels: 3.0

#14146 [JUJU-1285] Remove cloudsigma cloud registration
  cloud/clouds.go
  cloud/clouds_test.go
  cloud/fallback-public-cloud.yaml
  cloud/fallback_public_cloud.go
  cmd/juju/cloud/add.go
  cmd/juju/commands/bootstrap_test.go
Labels: 2.9

#14148 [JUJU-1284] remove cloudsigma provider
  go.mod
  go.sum
  provider/all/cloudsigma.go
  provider/cloudsigma/client.go
  provider/cloudsigma/client_test.go
  provider/cloudsigma/config.go
  provider/cloudsigma/config_test.go
  provider/cloudsigma/constraints.go
  provider/cloudsigma/constraints_test.go
  provider/cloudsigma/credentials.go
  provider/cloudsigma/credentials_test.go
  provider/cloudsigma/environ.go
  provider/cloudsigma/environ_test.go
  provider/cloudsigma/environcaps.go
  provider/cloudsigma/environinstance.go
  provider/cloudsigma/environinstance_test.go
  provider/cloudsigma/instance.go
  provider/cloudsigma/instance_information.go
  provider/cloudsigma/instance_test.go
  provider/cloudsigma/provider.go
  provider/cloudsigma/provider_test.go
  provider/cloudsigma/storage.go
  provider/cloudsigma/userdata.go
  provider/cloudsigma/userdata_test.go
Labels: 3.0

#14140 [JUJU-1275] Application charmurl string
  apiserver/common/crossmodel/interface.go
  apiserver/facades/agent/instancemutater/instancemutater.go
  apiserver/facades/agent/instancemutater/instancemutater_test.go
  apiserver/facades/agent/instancemutater/interface.go
  apiserver/facades/agent/instancemutater/lxdprofilewatcher.go
  apiserver/facades/agent/instancemutater/lxdprofilewatcher_test.go
  apiserver/facades/agent/instancemutater/mocks/instancemutater_mock.go
  apiserver/facades/agent/instancemutater/shim.go
  apiserver/facades/agent/uniter/uniter.go
  apiserver/facades/agent/uniter/uniter_test.go
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/backend.go
  apiserver/facades/client/application/deploy_test.go
  apiserver/facades/client/application/mock_test.go
  apiserver/facades/client/application/updateseries_mocks_test.go
  apiserver/facades/client/applicationoffers/applicationoffers_test.go
  apiserver/facades/client/applicationoffers/base.go
  apiserver/facades/client/applicationoffers/base_test.go
  apiserver/facades/client/applicationoffers/mock_test.go
  apiserver/facades/client/client/status.go
  apiserver/facades/client/client/status_test.go
  apiserver/facades/client/metricsdebug/metricsdebug.go
  apiserver/facades/controller/caasapplicationprovisioner/mock_test.go
  apiserver/facades/controller/caasapplicationprovisioner/provisioner.go
  apiserver/facades/controller/caasapplicationprovisioner/state.go
  apiserver/facades/controller/charmrevisionupdater/interface.go
  apiserver/facades/controller/charmrevisionupdater/interface_test.go
  apiserver/facades/controller/charmrevisionupdater/mocks/mocks.go
  apiserver/facades/controller/charmrevisionupdater/updater.go
  cmd/juju/application/deploy_test.go
  core/cache/cachetest/state.go
  migration/precheck.go
  migration/precheck_test.go
  resource/opener.go
  scripts/juju-list-blobstore/main.go
  state/action_test.go
  state/allwatcher.go
  state/allwatcher_internal_test.go
  state/application.go
  state/application_test.go
  state/bench_test.go
  state/charmref.go
  state/export_test.go
  state/migration_export.go
  state/migration_import.go
  state/state.go
  state/unit.go
  state/upgrades.go
  state/upgrades_test.go
  state/watcher.go
  state/watcher_profilecharm_test.go
  testing/factory/factory.go
  testing/factory/factory_test.go
  worker/uniter/resolver/loop.go
Labels: 2.9

#14161 [JUJU-1323] a bit of clean up while working on a large pr
  apiserver/common/charms/appcharminfo_test.go
  apiserver/common/charms/charminfo_test.go
  apiserver/common/charms/common.go
  apiserver/common/charms/mocks/mocks.go
  apiserver/facades/agent/caasoperator/mock_test.go
  apiserver/facades/agent/caasoperator/operator.go
  apiserver/facades/agent/caasoperator/state.go
  apiserver/facades/agent/metricsadder/metricsadder_test.go
  apiserver/facades/client/application/backend.go
  apiserver/facades/client/application/charmstore.go
  apiserver/facades/client/application/updateseries_mocks_test.go
  apiserver/facades/client/charms/client_test.go
  cmd/juju/application/refresh_test.go
  state/metrics_test.go
  state/migration_import_test.go
  worker/modelcache/worker_test.go
Labels: 2.9

#14142 [JUJU-1273] Check and branch on cloud type when remove-cloud
  cmd/juju/cloud/export_test.go
  cmd/juju/cloud/mocks/remove_mocks.go
  cmd/juju/cloud/package_test.go
  cmd/juju/cloud/remove.go
  cmd/juju/cloud/remove_test.go
Labels: 2.9

#14110 [JUJU-1231] Disallow do-release-upgrade for ubuntu controller;
  cloudconfig/instancecfg/instancecfg.go
  cloudconfig/machinecloudconfig_test.go
  cloudconfig/userdatacfg_win.go
  cmd/jujud/agent/machine.go
  cmd/jujud/agent/machine_test.go
  cmd/jujud/agent/mocks/machine_mock.go
  cmd/jujud/agent/package_test.go
  cmd/jujud/agent/util_test.go
Labels: 2.9

#14162 [JUJU-1325] Deprecate PodSpec charms;
  apiserver/facades/client/application/deploy.go
Labels: 3.0

#14132 [JUJU-1266] Rename column DNS --> Address in machines tabular output
  cmd/juju/machine/list_test.go
  cmd/juju/machine/show_test.go
  cmd/juju/status/output_tabular.go
  cmd/juju/status/status_internal_test.go
  featuretests/cmd_juju_status_test.go
Labels: bug, 2.9

#14121 [JUJU-1246] add deprecation notice to the 'juju sla' command
  cmd/juju/romulus/sla/sla.go
Labels: 2.9

#14199 [JUJU-1358]Fail more gracefully for negative watch values
  cmd/juju/status/status.go
Labels: 2.9

#14203 [JUJU-1368] Move more apis off the client facade
  api/agent/uniter/resource.go
  api/agent/upgradeseries/upgradeseries_test.go
  api/client/charms/client_test.go
  api/client/charms/downloader.go
  api/client/charms/downloader_test.go
  api/client/charms/package_test.go
  api/client/client/client.go
  api/client/client/client_macaroon_test.go
  api/client/client/client_test.go
  api/client/client/http.go
  api/client/resources/base_test.go
  api/client/resources/client.go
  api/client/resources/package_test.go
  api/client/usermanager/client.go
  api/client/usermanager/client_test.go
  api/facadeversions.go
  api/http/http.go
  api/http/http_test.go
  api/http/mocks/http_mock.go
  api/http/mocks/httpdoer_mock.go
  api/http/package_test.go
  api/httpclient.go
  api/httpclient_test.go
  apiserver/facades/client/client/client.go
  apiserver/facades/client/client/client_test.go
  apiserver/facades/client/usermanager/register.go
  apiserver/facades/client/usermanager/usermanager.go
  apiserver/facades/client/usermanager/usermanager_test.go
  apiserver/facades/schema.json
  cmd/juju/application/deploy.go
  cmd/juju/application/refresh.go
  cmd/juju/controller/listmodels_test.go
  cmd/juju/model/show_test.go
  cmd/juju/user/list.go
  cmd/juju/user/list_test.go
  cmd/juju/user/user_test.go
  cmd/jujud/agent/caasoperator/manifolds.go
  cmd/modelcmd/controller.go
  featuretests/api_model_test.go
  featuretests/package_test.go
  rpc/params/model.go
  worker/migrationmaster/manifold.go
  worker/uniter/charm/bundles_test.go
  worker/uniter/manifold.go
  worker/uniter/util_test.go
Labels: 2.9

#14206 [JUJU-1102]change_juju_status_color_help_string
  cmd/juju/status/status.go
Labels: 3.0

#14212 Fix `test-deploy-test-deploy-revision-lxd`
  tests/suites/deploy/deploy_revision.sh
Labels: do not merge, 2.9

#14215 [JUJU-1376] Close remote model connection when controller info update fails
  worker/remoterelations/mock_test.go
  worker/remoterelations/remoteapplicationworker.go
  worker/remoterelations/remoterelations_test.go
Labels: 2.9

#14174 [JUJU-1276] Charm's url saved as string
  apiserver/facades/client/application/application_test.go
  apiserver/facades/client/client/status.go
  state/allwatcher.go
  state/allwatcher_internal_test.go
  state/application_test.go
  state/charm.go
  state/charm_test.go
  state/charmref.go
  state/state.go
  state/state_test.go
  state/unit.go
  state/upgrades.go
  worker/caasoperator/download.go
  worker/metrics/collect/handler.go
  worker/metrics/collect/handler_test.go
  worker/metrics/collect/manifold.go
  worker/metrics/collect/manifold_test.go
  worker/uniter/charm/bundles.go
  worker/uniter/charm/bundles_test.go
  worker/uniter/charm/charm.go
  worker/uniter/charm/charm_test.go
  worker/uniter/charm/manifest_deployer.go
  worker/uniter/charm/manifest_deployer_test.go
  worker/uniter/charm/mocks/mocks.go
  worker/uniter/mockdeployer_test.go
  worker/uniter/util_test.go
Labels: 2.9

#14208 [JUJU-1371] Remove unnecessary function from state package
  rpc/params/params_test.go
Labels: 3.0
