Repository juju/juju, pull requests merged in 2022-10, with the labels that each got.

#14610 [JUJU-1803] Juju status with selector matching on ports substring edit
  apiserver/facades/client/client/filtering.go
  apiserver/facades/client/client/filtering_test.go
Labels: 2.9

#14682 [JUJU-1842] Added integration test for the magma project
  tests/main.sh
  tests/suites/magma/magma.sh
  tests/suites/magma/overlay/overlay.yaml
  tests/suites/magma/task.sh
Labels: 2.9

#14696 [JUJU-1877] Improve "juju info" channels output
  charmhub/find_test.go
  charmhub/info_test.go
  cmd/juju/charmhub/convert.go
  cmd/juju/charmhub/convert_test.go
  cmd/juju/charmhub/data.go
  cmd/juju/charmhub/find_test.go
  cmd/juju/charmhub/findwriter_test.go
  cmd/juju/charmhub/info.go
  cmd/juju/charmhub/info_test.go
  cmd/juju/charmhub/infowriter.go
  cmd/juju/charmhub/infowriter_test.go
  tests/suites/deploy/deploy_bundles.sh
Labels: 3.0

#14715 [JUJU-1926] Do no ops if nothing to remove;
  state/secrets.go
Labels: 3.0

#14698 Remove Mongo-based leases logic
  apiserver/common/modelmanagerinterface.go
  apiserver/facades/client/modelmanager/modelinfo_test.go
  apiserver/facades/controller/migrationmaster/facade.go
  apiserver/facades/controller/migrationmaster/facade_test.go
  apiserver/facades/controller/migrationmaster/mocks/backend.go
  apiserver/facades/controller/migrationmaster/register.go
  apiserver/facades/controller/migrationtarget/migrationtarget_test.go
  cmd/jujud/agent/machine/manifolds.go
  core/lease/store.go
  core/raftlease/fsm.go
  core/raftlease/fsm_test.go
  core/raftlease/store.go
  core/raftlease/store_test.go
  migration/migration.go
  migration/migration_test.go
  provider/dummy/environs.go
  provider/dummy/leasestore.go
  state/allcollections.go
  state/migration_export.go
  state/migration_export_test.go
  state/migration_import_test.go
  state/migration_internal_test.go
  state/raftlease/export_test.go
  state/raftlease/package_test.go
  state/raftlease/target.go
  state/raftlease/target_test.go
  state/state.go
  worker/globalclockupdater/manifold.go
  worker/globalclockupdater/manifold_test.go
  worker/globalclockupdater/package_test.go
  worker/globalclockupdater/raftlease_test.go
  worker/globalclockupdater/updater.go
  worker/globalclockupdater/updater_test.go
  worker/lease/manager_check_test.go
  worker/lease/manager_cross_test.go
  worker/lease/manager_leases_test.go
  worker/raft/apply.go
  worker/raft/apply_test.go
  worker/raft/manifold.go
  worker/raft/manifold_test.go
  worker/raft/package_test.go
  worker/raft/raftforwarder/manifold.go
  worker/raft/raftforwarder/manifold_test.go
  worker/raft/raftforwarder/worker.go
  worker/raft/raftforwarder/worker_test.go
  worker/raft/raftlease_mock_test.go
  worker/raft/worker.go
  worker/raft/worker_test.go
Labels: 3.0

#13876 [JUJU-796] Remove some alias commands
  apiserver/embeddedcli_whitelist.go
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/application_unit_test.go
  cmd/juju/action/list.go
  cmd/juju/action/run.go
  cmd/juju/action/show.go
  cmd/juju/action/showoperation.go
  cmd/juju/action/showtask.go
  cmd/juju/application/refresh.go
  cmd/juju/application/removesaas.go
  cmd/juju/cloud/defaultcredential.go
  cmd/juju/cloud/remove.go
  cmd/juju/cloud/updatecloud.go
  cmd/juju/commands/helptool.go
  cmd/juju/commands/helptool_test.go
  cmd/juju/commands/main_test.go
  cmd/juju/commands/synctools.go
  cmd/juju/commands/upgrademodel.go
  cmd/juju/controller/showcontroller.go
  cmd/juju/firewall/listrules.go
  cmd/juju/firewall/setrule.go
  cmd/juju/model/showcommit.go
  cmd/juju/resource/upload.go
  cmd/juju/resource/upload_test.go
  cmd/juju/secrets/package_test.go
  cmd/juju/space/move.go
  cmd/juju/space/remove.go
  cmd/juju/space/rename.go
  cmd/juju/space/show.go
  cmd/juju/ssh/debugcode.go
  cmd/juju/status/status.go
  cmd/juju/user/remove.go
  cmd/juju/user/whoami.go
  cmd/juju/user/whoami_test.go
  cmd/plugins/juju-metadata/generateagents.go
  cmd/plugins/juju-metadata/listimages.go
  cmd/plugins/juju-metadata/metadataplugin_test.go
  cmd/plugins/juju-metadata/validateagentsmetadata.go
  doc/simplestreams-metadata.txt
  etc/bash_completion.d/juju
  featuretests/cmd_juju_controller_test.go
  featuretests/cmd_juju_current_controller_test.go
  featuretests/cmd_juju_model_test.go
  featuretests/cmd_juju_space_test.go
  featuretests/cmd_juju_subnet_test.go
  featuretests/cmd_juju_user_test.go
  featuretests/storage_test.go
  jujuclient/interface.go
  state/modelsummaries.go
  tests/suites/bootstrap/streams.sh
  tests/suites/upgrade/streams.sh
Labels: 3.0

#14598 Update charm/v8 to remove series restrictions on kubernetes bundles.
  go.mod
  go.sum
Labels: 2.9

#14640 [JUJU-1824] run Pebble in api-server container
  caas/application.go
  caas/kubernetes/provider/application/application.go
  caas/kubernetes/provider/bootstrap.go
  caas/kubernetes/provider/bootstrap_test.go
  caas/kubernetes/provider/constants/constants.go
  caas/kubernetes/provider/pebble/doc.go
  caas/kubernetes/provider/pebble/pebble.go
  caas/scripts.go
  go.mod
  go.sum
  make_functions.sh
Labels: 3.0

#14726 Remove obsolete cached image metadata commands
  api/client/imagemanager/client.go
  api/client/imagemanager/client_test.go
  api/client/imagemanager/package_test.go
  api/facadeversions.go
  apiserver/allfacades.go
  apiserver/facades/client/imagemanager/export_test.go
  apiserver/facades/client/imagemanager/imagemanager.go
  apiserver/facades/client/imagemanager/imagemanager_test.go
  apiserver/facades/client/imagemanager/package_test.go
  apiserver/facades/client/imagemanager/register.go
  apiserver/facades/client/imagemanager/state.go
  apiserver/facades/client/imagemetadatamanager/register.go
  apiserver/facades/schema.json
  apiserver/observer/auditfilter.go
  cmd/juju/cachedimages/cachedimages.go
  cmd/juju/cachedimages/export_test.go
  cmd/juju/cachedimages/list.go
  cmd/juju/cachedimages/list_test.go
  cmd/juju/cachedimages/package_test.go
  cmd/juju/cachedimages/remove.go
  cmd/juju/cachedimages/remove_test.go
  cmd/juju/commands/main.go
  cmd/juju/commands/main_test.go
  rpc/params/params.go
  state/backups/db.go
  state/export_test.go
  state/images.go
  state/images_test.go
  state/imagestorage/export_test.go
  state/imagestorage/image.go
  state/imagestorage/image_test.go
  state/imagestorage/interface.go
Labels: 3.0

#14728 [JUJU-1957] Fixed test-unit in CI for 3.0.
  tests/suites/unit/unit_series.sh
Labels: 3.0

#14655 [JUJU-1837] openstack set root disk to use local storage
  provider/openstack/local_test.go
  provider/openstack/provider.go
Labels: 2.9

#14722 [JUJU-1940] Fixed test-cmr test
  tests/suites/cmr/offer_consume.sh
Labels: do not merge

#14731 [JUJU-1945] Remove API-based Raft Client
  api/controller/raftlease/client.go
  api/controller/raftlease/client_test.go
  api/controller/raftlease/mocks/remote_mock.go
  api/controller/raftlease/package_test.go
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/agent/machine/manifolds_test.go
  feature/flags.go
  worker/lease/manifold/manifold.go
  worker/lease/manifold/manifold_test.go
Labels: 3.0

#14714 Fix for url that when followed gives a 404 error.
  provider/lxd/environ.go
  provider/lxd/environ_test.go
Labels: 3.0

#14683 [JUJU-1538, JUJU-1860] Add cos lite integration test
  tests/includes/wait-for.sh
  tests/main.sh
  tests/suites/coslite/cl.sh
  tests/suites/coslite/overlay/offers-overlay.yaml
  tests/suites/coslite/overlay/storage-small-overlay.yaml
  tests/suites/coslite/task.sh
Labels: 2.9

#14721 [JUJU-1925] Secret get using label
  api/agent/secretsmanager/client.go
  api/agent/secretsmanager/client_test.go
  apiserver/facades/agent/secretsmanager/mocks/secretsconsumer.go
  apiserver/facades/agent/secretsmanager/secrets.go
  apiserver/facades/agent/secretsmanager/secrets_test.go
  apiserver/facades/agent/secretsmanager/state.go
  state/allcollections.go
  state/application.go
  state/secrets.go
  state/secrets_test.go
  upgrades/upgradevalidation/version.go
  worker/uniter/runner/context/context.go
  worker/uniter/runner/context/context_test.go
  worker/uniter/runner/context/export_test.go
  worker/uniter/runner/jujuc/secret-get.go
  worker/uniter/runner/jujuc/secret-get_test.go
Labels: 3.0

#14761 Fix kvm imagepath
  container/kvm/sync.go
  container/kvm/sync_internal_test.go
  container/kvm/wrappedcmds.go
  container/kvm/wrappedcmds_test.go
  scripts/win-installer/setup.iss
  snap/snapcraft.yaml
  version/version.go
Labels: 3.0

#14763 [JUJU-1977] Remove debugging left behind, tidy up k8s base handling
  api/common/charm/charmorigin.go
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/charm.go
  cmd/juju/application/refresher/refresher.go
  cmd/juju/application/utils/origin.go
  core/bundle/changes/handlers.go
  core/series/base.go
  juju/testing/conn.go
  state/application.go
  state/state.go
  testing/factory/factory.go
Labels: 3.0

#14768 [JUJU-1980] Do not filter out all API addresses when using Fan networking
  network/network.go
  network/network_test.go
Labels: 2.9

#14758 [JUJU-1848] Integration test for default-series and charm deployment
  tests/suites/deploy/deploy_default_series.sh
  tests/suites/deploy/task.sh
Labels: 2.9

#14744 [JUJU-1833]Integration refesh switch
  tests/main.sh
  tests/suites/deploy/deploy_revision.sh
  tests/suites/refresh/refresh.sh
  tests/suites/refresh/switch.sh
  tests/suites/refresh/task.sh
Labels: 2.9

#14765 [JUJU-1985] Support juju 3.0 controllers and centos series
  api/client/application/client.go
  api/client/charms/client.go
  api/client/client/client.go
  api/client/machinemanager/machinemanager.go
  api/client/resources/base_test.go
  api/client/resources/client.go
  api/facadeversions.go
  api/state_test.go
  apiserver/allfacades.go
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/application_test.go
  apiserver/facades/client/application/application_unit_test.go
  apiserver/facades/client/application/get_test.go
  apiserver/facades/client/application/register.go
  apiserver/facades/client/charms/client.go
  apiserver/facades/client/charms/client_test.go
  apiserver/facades/client/charms/conversions.go
  apiserver/facades/client/charms/export_test.go
  apiserver/facades/client/charms/register.go
  apiserver/facades/client/client/client.go
  apiserver/facades/client/client/register.go
  apiserver/facades/client/machinemanager/instanceconfig.go
  apiserver/facades/client/machinemanager/machinemanager.go
  apiserver/facades/client/machinemanager/machinemanager_test.go
  apiserver/facades/client/machinemanager/register.go
  apiserver/facades/client/resources/facade.go
  apiserver/facades/client/resources/register.go
  apiserver/facades/client/resources/server_addpending_test.go
  apiserver/facades/schema.json
  cloudconfig/cloudinit/renderscript_test.go
  cloudconfig/instancecfg/instancecfg.go
  cloudconfig/userdatacfg_test.go
  cmd/juju/backups/backups.go
  cmd/juju/machine/add.go
  cmd/juju/machine/list_test.go
  cmd/juju/machine/show_test.go
  cmd/juju/status/formatted.go
  cmd/juju/status/formatter.go
  cmd/juju/status/status_internal_test.go
  container/broker/broker_test.go
  container/kvm/live_test.go
  container/lxd/manager_test.go
  container/testing/common.go
  core/series/base.go
  environs/bootstrap/bootstrap.go
  environs/jujutest/livetests.go
  juju/testing/instance.go
  provider/azure/environ_test.go
  provider/common/bootstrap.go
  provider/common/bootstrap_test.go
  provider/ec2/local_test.go
  provider/equinix/environ_test.go
  provider/gce/testing_test.go
  provider/lxd/testing_test.go
  provider/vsphere/environ_broker_test.go
  worker/provisioner/provisioner_task.go
Labels: 2.9

#14747 [JUJU-1971] Fix namespace for k8s controller model
  caas/kubernetes/provider/exec/exec.go
  caas/kubernetes/provider/exec/exec_test.go
  caas/kubernetes/provider/exec/export_test.go
  caas/kubernetes/provider/operator.go
  caas/kubernetes/provider/utils/labels.go
  cmd/juju/commands/export_test.go
  cmd/juju/commands/mocks/ssh_container_mock.go
  cmd/juju/commands/package_test.go
  cmd/juju/commands/ssh.go
  cmd/juju/commands/ssh_container.go
  cmd/juju/commands/ssh_container_test.go
  cmd/modelcmd/modelcommand.go
Labels: 2.9

#14757 [JUJU-1538] Fix cos lite suite to use caas image repo
  tests/suites/coslite/task.sh
Labels: 2.9

#14778 [JUJU-1983] Do not allow upgrade from 2.9 to 3.0 for now.
  apiserver/facades/client/client/client_test.go
  cmd/juju/commands/upgrademodel_test.go
  upgrades/upgradevalidation/validation_test.go
  upgrades/upgradevalidation/version.go
  upgrades/upgradevalidation/version_test.go
Labels: 2.9

#14784 Consolidate min versions for upgrade and migrate
  apiserver/facades/client/modelupgrader/upgrader_test.go
  apiserver/restrict_newer_client.go
  apiserver/restrict_newer_client_test.go
  cmd/juju/commands/upgrademodel.go
  cmd/juju/commands/upgrademodel_test.go
  migration/precheck_test.go
  upgrades/upgradevalidation/migrate_test.go
  upgrades/upgradevalidation/upgrade_test.go
  upgrades/upgradevalidation/validation_test.go
  upgrades/upgradevalidation/version.go
  upgrades/upgradevalidation/version_test.go
Labels: 2.9

#14788 [JUJU-2000] Fix deploy revision refresh test regression
  core/charm/repository/charmhub_test.go
  go.mod
  go.sum
  tests/suites/deploy/deploy_bundles.sh
  tests/suites/deploy/deploy_revision.sh
Labels: 3.0

#14795 [JUJU-2010] Update series support tests to accomodate the Kinetic series
  core/series/supportedseries_linux_test.go
  core/series/supportedseries_test.go
Labels: 2.9

#14793 Bring in new description dep and update migration and tests
  apiserver/facades/client/bundle/bundle.go
  apiserver/facades/client/bundle/bundle_test.go
  apiserver/facades/client/client/client_test.go
  caas/kubernetes/provider/application/application_test.go
  cmd/juju/charmhub/convert.go
  cmd/juju/charmhub/convert_test.go
  cmd/juju/charmhub/info_test.go
  cmd/plugins/juju-wait-for/machine_test.go
  cmd/plugins/juju-wait-for/unit_test.go
  core/cache/machine_test.go
  core/cache/model_test.go
  core/cache/unit_test.go
  core/series/base.go
  core/series/base_test.go
  go.mod
  go.sum
  rpc/params/params_test.go
  state/allwatcher_internal_test.go
  state/application_test.go
  state/export_test.go
  state/migration_export.go
  state/migration_export_test.go
  state/migration_import.go
  state/migration_import_test.go
  state/mocks/description_mock.go
  testing/factory/factory.go
Labels: 2.9

#14770 [JUJU-1982] Metrics test appname
  tests/suites/model/metrics.sh
Labels: 2.9

#14800 [JUJU-2020] Reject if no data to set for secret-set;
  api/client/secrets/client.go
  cmd/juju/commands/upgrademodel_test.go
  cmd/juju/secrets/list.go
  worker/uniter/runner/context/context.go
  worker/uniter/runner/jujuc/secret-add.go
Labels: 3.0

#14741 [JUJU-1652, JUJU-1948] API client resources to gomock
  api/client/cloud/cloud_test.go
  api/client/resources/base_test.go
  api/client/resources/client_listresources_test.go
  api/client/resources/client_upload_test.go
  api/client/resources/package_test.go
Labels: failed to land

#14729 go.mod specifies go version 1.19. Set install-dependencies to check go.mod for version to use
  Makefile
Labels: 2.9

#14779 [JUJU-1935] Fixed test-relations-test-relation-data-exchange (proving-ground)
  tests/suites/relations/relation_data_exchange.sh
Labels: 2.9

#14830 [JUJU-1952] Fix manual deploy integration tests
  tests/suites/manual/deploy_manual.sh
  tests/suites/manual/deploy_manual_aws.sh
  tests/suites/manual/deploy_manual_lxd.sh
  tests/suites/manual/task.sh
  tests/suites/manual/util.sh
Labels: 2.9

#14767 [JUJU 1951] fix failing model metric tests in proving ground
  tests/suites/model/metrics.sh
  tests/suites/model/task.sh
Labels: 2.9
