Repository juju/juju, pull requests merged in 2022-05, with the labels that each got.

#14003 [JUJU-1058] Close buffered logger upon termination of converged unit agent
  worker/deployer/unit_agent.go
Labels: 2.9

#14011 [JUJU-1063] Update CK overlay because latest stable bundle renamed kubernetes-mas…
  tests/suites/ck/ck.sh
  tests/suites/ck/overlay/aws.yaml
  tests/suites/ck/overlay/azure.yaml
  tests/suites/ck/overlay/gce.yaml
Labels: 2.9

#13996 [JUJU-1019] Bug 1969929 bundle revision only
  api/client/charms/client.go
  apiserver/apiserver_test.go
  apiserver/errors/errors.go
  apiserver/facades/agent/secretsmanager/secrets_test.go
  apiserver/facades/agent/storageprovisioner/storageprovisioner_test.go
  apiserver/facades/agent/uniter/uniter_test.go
  apiserver/facades/client/cloud/instance_information_test.go
  apiserver/facades/client/metricsdebug/metricsdebug_test.go
  apiserver/facades/client/storage/storage_test.go
  apiserver/registration_test.go
  cmd/juju/application/deploy.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/deployer.go
  cmd/juju/application/deployer/deployer_test.go
  cmd/juju/application/deployer/series_selector_test.go
  cmd/juju/application/store/charmadapter.go
  core/charm/repository/charmhub_test.go
  go.mod
  go.sum
  rpc/params/apierror.go
  worker/uniter/runner/context/context_test.go
Labels: bug, 2.9

#13684 [JUJU-544] Remove redundant ifCredentialValid wrappers from model manifolds
  cmd/jujud/agent/model/manifolds.go
Labels: 2.9

#14002 [JUJU-1054] Ensure to convert pod status to juju status consistent across operato…
  caas/kubernetes/provider/application/application.go
  caas/kubernetes/provider/application/application_test.go
  caas/kubernetes/provider/events.go
  caas/kubernetes/provider/k8s.go
  caas/kubernetes/provider/operator.go
  caas/kubernetes/provider/pod.go
  caas/kubernetes/provider/pod_test.go
  caas/kubernetes/provider/resources/clusterrole_test.go
  caas/kubernetes/provider/resources/clusterrolebinding_test.go
  caas/kubernetes/provider/resources/events.go
  caas/kubernetes/provider/resources/pod.go
  caas/kubernetes/provider/resources/pod_test.go
  worker/caasapplicationprovisioner/application.go
Labels: 2.9

#14023 [JUJU-1070] Fix/lp 1971560
  apiserver/logsink.go
  worker/modelworkermanager/recordlogger.go
  worker/syslogger/worker.go
  worker/syslogger/worker_test.go
Labels: 2.9

#14027 Fix K8s application removal in pre-initialized error state
  state/application_test.go
  state/cleanup.go
  state/unit.go
  state/unit_test.go
  worker/caasapplicationprovisioner/application.go
Labels: 2.9

#14030 [JUJU-1099] Restore "Store unit CharmURL as a string reference"
  api/agent/uniter/unit.go
  apiserver/facades/agent/instancemutater/interface.go
  apiserver/facades/agent/instancemutater/lxdprofilewatcher.go
  apiserver/facades/agent/instancemutater/lxdprofilewatcher_test.go
  apiserver/facades/agent/instancemutater/mocks/instancemutater_mock.go
  apiserver/facades/agent/uniter/mocks/newlxdprofile.go
  apiserver/facades/agent/uniter/newlxdprofile.go
  apiserver/facades/agent/uniter/uniter.go
  apiserver/facades/agent/uniter/uniter_test.go
  apiserver/facades/client/metricsdebug/metricsdebug.go
  core/cache/cachetest/state.go
  migration/precheck.go
  migration/precheck_test.go
  resource/resourceadapters/mocks/opener_mock.go
  resource/resourceadapters/opener_test.go
  resource/unit.go
  scripts/juju-list-blobstore/main.go
  state/allwatcher.go
  state/application.go
  state/application_test.go
  state/metrics_test.go
  state/migration_import.go
  state/state.go
  state/unit.go
  state/unit_test.go
  state/upgrade/types.go
  state/upgrades.go
  state/watcher.go
  testing/factory/factory.go
  worker/uniter/util_test.go
Labels: 2.9

#14037 [JUJU-1109] Fix encoding for interfaceAddressDisplay, used by the network-get hook tool
  worker/uniter/runner/jujuc/network-get.go
  worker/uniter/runner/jujuc/network-get_test.go
Labels: 2.9

#14034 [JUJU-1077] Remove a pointless state shim
  apiserver/common/common_test.go
  apiserver/common/controllerconfig.go
  apiserver/common/controllerconfig_test.go
  apiserver/common/interfaces.go
  apiserver/common/mocks/controllerconfig_mock.go
  apiserver/common/package_test.go
  state/externalcontroller.go
  state/interface.go
Labels: 2.9

#14039 [JUJU-1118] Bug 1970608: should not have a local charm channel
  state/migration_import.go
  state/upgrades.go
  state/upgrades_test.go
  upgrades/backend.go
  upgrades/operations.go
  upgrades/steps_2930.go
  upgrades/steps_2930_test.go
  upgrades/upgrade_test.go
Labels: bug, 2.9

#14009 Update juju-db to 5.3 track
  Makefile
  acceptancetests/jujupy/controller.py
  agent/agent_test.go
  caas/kubernetes/provider/bootstrap_test.go
  controller/config.go
  snap/local/wrappers/fetch-oci
Labels: 3.0

#14029 [JUJU-1070] Use first 6 digits for short model UUID;
  cmd/jujud/agent/machine.go
  core/instance/namespace.go
  core/instance/namespace_test.go
  go.mod
  go.sum
  state/cleanup.go
  worker/apicaller/connect.go
  worker/migrationmaster/validate_test.go
  worker/migrationmaster/worker.go
Labels: 3.0

#14036 [JUJU-1039] Rewrite `controller-config` to use `ConfigCommandBase`
  cmd/juju/application/config.go
  cmd/juju/application/export_test.go
  cmd/juju/config/config.go
  cmd/juju/config/config_test.go
  cmd/juju/controller/configcommand.go
  cmd/juju/controller/configcommand_test.go
  cmd/juju/controller/export_test.go
  cmd/juju/model/config.go
Labels: 3.0

#14031 [JUJU-1095] Remove support for antiquated LXD versions
  container/lxd/export_test.go
  container/lxd/initialisation_linux.go
  container/lxd/initialisation_test.go
  container/lxd/network.go
  container/lxd/network_test.go
Labels: 3.0

#14057 [JUJU-1157] Check that an AgentStreamKey value exists.
  cmd/juju/commands/upgrademodel.go
Labels: bug, 2.9

#14064 [JUJU-1159] Improved help model-defaults message.
  cmd/juju/model/defaults.go
Labels: bug, 2.9

#14061 [JUJU-1122] Reject if --build-agent was provided for a snap juju;
  .github/workflows/smoke.yml
  environs/sync/sync_test.go
  environs/tools/build.go
  environs/tools/build_test.go
  environs/tools/export_test.go
Labels: 2.9

#14040 [JUJU-1080] Adds LXD server certificate credential validation.
  cloud/credentials.go
  cloud/credentials_test.go
  cmd/juju/cloud/addcredential.go
  pki/assertion/x509.go
  pki/assertion/x509_test.go
  provider/lxd/credentials.go
  provider/lxd/credentials_test.go
  provider/lxd/testing_test.go
Labels: 2.9

#14065 [JUJU-1161] Deploy cmd panic when invalid placements
  apiserver/facades/client/application/application.go
  cmd/juju/application/addunit.go
  cmd/juju/application/addunit_test.go
Labels: bug, 2.9

#14074 [JUJU-1129] Remove unnecessary abstractions from resources infrastructure
  apiserver/apiserver.go
  apiserver/facades/controller/caasapplicationprovisioner/provisioner.go
  core/resource/unit.go
  resource/charmhub.go
  resource/export_test.go
  resource/interfaces.go
  resource/mocks/cache_mock.go
  resource/mocks/opener_mock.go
  resource/mocks/repositories_mock.go
  resource/opener.go
  resource/opener_test.go
  resource/operations.go
  resource/operations_test.go
  resource/package_test.go
  resource/repository.go
  state/migration_export_test.go
  state/mocks/resources_mock.go
  state/resources.go
  state/resources_state_resource.go
Labels: 2.9

#14068 Allow conflicting constraints for arch+instance-type until arch issues can be resolved.
  core/constraints/validation.go
  core/constraints/validation_test.go
  provider/azure/environ.go
  provider/azure/environ_test.go
  provider/ec2/environ.go
  provider/ec2/instancetypes.go
  provider/ec2/local_test.go
  provider/gce/environ_policy.go
  provider/gce/instance_information.go
  provider/openstack/provider.go
Labels: 2.9

#14075 [JUJU-1122] Set FORCE-VERSION for uploaded tools;
  cmd/juju/commands/upgrademodel.go
  environs/tools/build.go
  environs/tools/build_test.go
Labels: 2.9, go

#14083 [JUJU-1081] Fixes expose ipv6 issue in Openstack.
  environs/jujutest/livetests.go
  provider/dummy/environs.go
  provider/openstack/firewaller.go
  provider/openstack/local_test.go
  provider/openstack/provider.go
  provider/openstack/provider_test.go
Labels: 2.9

#14092 [JUJU-1215] Fix timestamp when updating charmhub resources
  apiserver/facades/client/client/status_test.go
  apiserver/facades/controller/charmrevisionupdater/charmhub.go
  apiserver/facades/controller/charmrevisionupdater/register.go
  apiserver/facades/controller/charmrevisionupdater/updater.go
  apiserver/facades/controller/charmrevisionupdater/updater_test.go
  charmstore/latest.go
  charmstore/latest_test.go
  state/allcollections.go
  state/internal_test.go
  state/migration_import.go
  state/resources.go
  state/upgrades.go
  state/upgrades_test.go
  upgrades/backend.go
  upgrades/operations.go
  upgrades/steps_2932.go
  upgrades/steps_2932_test.go
  upgrades/upgrade_test.go
Labels: 2.9

#14096 Fix controller charm on caas/k8s
  caas/kubernetes/provider/bootstrap.go
  caas/kubernetes/provider/bootstrap_test.go
  cloudconfig/podcfg/podcfg.go
  cloudconfig/podcfg/podcfg_test.go
  cmd/containeragent/unit/agent.go
  cmd/containeragent/unit/manifolds.go
  cmd/containeragent/unit/manifolds_test.go
  cmd/jujud/agent/bootstrap_test.go
  cmd/jujud/agent/controllercharm.go
Labels: 3.0

#14095 [JUJU-1105] new_color_scheme_for_juju_status
  cmd/juju/status/output_tabular.go
  cmd/juju/status/utils.go
  cmd/juju/storage/listformatters.go
  cmd/output/output.go
Labels: 3.0
