Repository juju/juju, pull requests merged in 2022-03, with the labels that each got.

#13796 [JUJU-697] Verify pointers before using them in Report.
  state/pool.go
  state/state.go
  worker/deployer/nested.go
  worker/httpserver/worker.go
  worker/modelcache/worker.go
  worker/modelworkermanager/modelworkermanager.go
  worker/multiwatcher/worker.go
  worker/peergrouper/worker.go
  worker/pubsub/remoteserver.go
  worker/remoterelations/remoteapplicationworker.go
  worker/state/statetracker.go
  worker/uniter/relation/statetracker.go
Labels: 2.9

#13749 [JUJU-593] make verification of cloud connectivity at upgrade less intense.
  apiserver/facades/client/client/client.go
  apiserver/facades/client/client/client_test.go
  caas/kubernetes/provider/metadata.go
  environs/interface.go
  environs/utils.go
  go.mod
  go.sum
  provider/lxd/environ.go
  provider/maas/environ.go
  provider/openstack/provider.go
Labels: bug, 2.9

#13810 [JUJU-700] Setup CI test for deploying CK
  tests/includes/juju.sh
  tests/includes/wait-for.sh
  tests/main.sh
  tests/suites/ck/ck.sh
  tests/suites/ck/overlay/aws.yaml
  tests/suites/ck/overlay/azure.yaml
  tests/suites/ck/overlay/gce.yaml
  tests/suites/ck/storage/aws.yaml
  tests/suites/ck/storage/azure.yaml
  tests/suites/ck/storage/gce.yaml
  tests/suites/ck/task.sh
Labels: 2.9

#13836 [JUJU-700] Ci ck
  acceptancetests/assess_model_migration.py
  tests/suites/ck/ck.sh
  tests/suites/ck/task.sh
Labels: 2.9

#13838 [JUJU-751] Use the watchHashes helper for WatchConfigSettingsHash in the uniter API
  apiserver/facades/agent/uniter/uniter.go
Labels: 2.9

#13869 [JUJU-806] Remove Uniter() from api.Connection interface
  api/agent/uniter/uniter.go
  api/interface.go
  api/state.go
  apiserver/facades/agent/uniter/uniter_test.go
  cmd/containeragent/initialize/package_test.go
  featuretests/application_config_test.go
  worker/uniter/charm/bundles_test.go
  worker/uniter/runner/context/contextfactory_test.go
  worker/uniter/runner/context/relation_test.go
  worker/uniter/runner/context/unitStorage_test.go
  worker/uniter/runner/context/util_test.go
  worker/uniter/runner/factory_test.go
  worker/uniter/runner/util_test.go
  worker/uniter/util_test.go
Labels: trim-connection-interface

#13874 [JUJU-813] Remove unused InstancePoller()method from Connection interface
  api/interface.go
  api/state.go
  cmd/containeragent/initialize/package_test.go
Labels: trim-connection-interface

#13875 [JUJU-814] Remove UnitAssigner() method from Connection interface
  api/interface.go
  api/state.go
  apiserver/facades/client/application/application_test.go
  cmd/containeragent/initialize/package_test.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/refresh_resources_test.go
  cmd/juju/application/refresh_test.go
  juju/testing/repo.go
Labels: trim-connection-interface

#13878 [JUJU-819] Remove Client() method of api.Connection interface
  api/apiclient_test.go
  api/client.go
  api/client_macaroon_test.go
  api/client_test.go
  api/export_test.go
  api/interface.go
  api/state.go
  apiserver/admin_test.go
  apiserver/facades/client/application/application_test.go
  apiserver/facades/client/client/client_test.go
  apiserver/facades/client/client/instanceconfig_test.go
  apiserver/facades/client/client/perm_test.go
  apiserver/facades/client/client/status_test.go
  cmd/juju/application/deploy.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/refresh.go
  cmd/juju/commands/ssh_machine.go
  cmd/juju/machine/remove.go
  cmd/juju/user/list.go
  cmd/jujud/agent/machine_test.go
  cmd/modelcmd/modelcommand.go
  environs/jujutest/livetests.go
  environs/manual/sshprovisioner/provisioner_test.go
  featuretests/api_model_test.go
  featuretests/dblog_test.go
  worker/migrationmaster/manifold.go
Labels: trim-connection-interface

#13873 [JUJU-812] Remove Reboot method from api.Connection
  api/agent/reboot/reboot.go
  api/agent/reboot/reboot_test.go
  api/interface.go
  api/state.go
  cmd/containeragent/initialize/package_test.go
  worker/reboot/manifold.go
  worker/reboot/reboot_test.go
Labels: trim-connection-interface

#13903 Use version without build number for --agent-version;
  acceptancetests/jujupy/client.py
  version/version.go
Labels: 2.9, python

#13919 [JUJU-854] Removes UpdateNetworkInfo API client method
  api/agent/uniter/unit.go
  worker/uniter/runner/context/context.go
  worker/uniter/runner/context/mocks/hookunit_mock.go
Labels: 2.9
