Repository juju/juju, pull requests merged in 2022-02, with the labels that each got.

#13666 [JUJU-520] Remove redundant dependency from the presence manifold
  cmd/jujud/agent/machine/manifolds.go
  worker/presence/manifold.go
  worker/presence/manifold_test.go
  worker/stateconfigwatcher/manifold.go
Labels: 2.9

#13685 [JUJU-503] Reimplement essential metadata for charmhub using refresh API
  charmhub/refresh.go
  charmhub/refresh_test.go
  charmhub/refreshconfig.go
  charmhub/transport/refresh.go
  core/charm/repository/charmhub.go
  core/charm/repository/charmhub_test.go
Labels: 2.9

#13709 Use str option value for --trust and pass --trust to juju rather than…
  acceptancetests/assess_caas_deploy_kubeflow.py
Labels: 2.9, python

#13719 Fix/nw deploy kubeflow
  .github/workflows/microk8s-tests.yml
  acceptancetests/assess_caas_deploy_kubeflow.py
Labels: 2.9, python

#13724 [JUJU-575] Reset in kubeflow dir;
  acceptancetests/assess_caas_deploy_kubeflow.py
Labels: 2.9, python

#13716 [JUJU-586] Supply OpenStack FIPs to the instance-poller
  provider/openstack/networking.go
  provider/openstack/networking_test.go
Labels: 2.9

#13727 [JUJU-600] Add log diff debug message for assess_model_migration.py;
  acceptancetests/assess_model_migration.py
Labels: 2.9, python

#13745 [JUJU-627] Remove antiquated juju-bridge command
  cmd/juju-bridge/main.go
  network/bridge.go
  network/export_test.go
  network/scriptrunner.go
  network/scriptrunner_test.go
Labels: 2.9

#13758 Fix/crd upgrade
  .github/workflows/microk8s-tests.yml
  caas/kubernetes/provider/customresourcedefinitions.go
  caas/kubernetes/provider/customresourcedefinitions_test.go
  caas/kubernetes/provider/specs/customresourcedefinition.go
Labels: 2.9

#13759 [JUJU-647] improve messaging on deleted users
  cmd/juju/user/add.go
  cmd/juju/user/remove.go
  cmd/juju/user/remove_test.go
  featuretests/cmd_juju_user_test.go
  state/user.go
  state/user_test.go
Labels: bug, 2.9

#13769 Change wait check more robust for oidc-gatekeeper config-change hook;
  acceptancetests/assess_caas_deploy_kubeflow.py
Labels: 2.9, python

#13754 [JUJU-570] Allow forced-destruction of storage-linked file systems
  state/filesystem.go
  state/filesystem_test.go
Labels: 2.9

#13774 Disable Test Kubeflow gh action;
  .github/workflows/microk8s-tests.yml
Labels: 2.9, python

#13568 Integrate K8s probes to hit Pebble /v1/health endpoint
  caas/kubernetes/provider/application/application.go
  caas/kubernetes/provider/application/application_test.go
  go.mod
  go.sum
Labels: do not merge

#13775 [JUJU-600] Extend timeout for simple server deploy;
  acceptancetests/jujupy/workloads.py
Labels: 2.9, python

#13787 [JUJU-600] Fix nw-model-migration-amd64-gce
  acceptancetests/assess_model_migration.py
  acceptancetests/jujupy/workloads.py
Labels: 2.9, python

#13792 [JUJU-600] Bump GCE default constraints;
  provider/gce/environ_instance_test.go
  provider/gce/environ_policy_test.go
  provider/gce/instance_information.go
  provider/gce/instance_information_test.go
Labels: 2.9
