Repository juju/juju, pull requests merged in 2022-08, with the labels that each got.

#14372 Preserve mongod logs in juju k8s controller
  caas/kubernetes/provider/bootstrap_test.go
  caas/scripts.go
Labels: 2.9

#14385 [JUJU-1512] Update juju/cmd to v3.0.1
  cmd/juju/action/exec_test.go
  cmd/juju/action/listoperations_test.go
  cmd/juju/action/run_test.go
  cmd/juju/action/showtask_test.go
  cmd/juju/application/constraints.go
  cmd/juju/block/list_test.go
  cmd/juju/cloud/list_test.go
  cmd/juju/cloud/listcredentials_test.go
  cmd/juju/cloud/regions_test.go
  cmd/juju/commands/enableha_test.go
  cmd/juju/controller/listcontrollers_test.go
  cmd/juju/controller/listmodels_test.go
  cmd/juju/crossmodel/find_test.go
  cmd/juju/crossmodel/list_test.go
  cmd/juju/crossmodel/show_test.go
  cmd/juju/firewall/listrules_test.go
  cmd/juju/interact/query.go
  cmd/juju/machine/list_test.go
  cmd/juju/machine/show_test.go
  cmd/juju/metricsdebug/metrics.go
  cmd/juju/metricsdebug/metrics_test.go
  cmd/juju/model/config_test.go
  cmd/juju/model/constraints.go
  cmd/juju/model/listcommits.go
  cmd/juju/payload/list_test.go
  cmd/juju/resource/charmresources_test.go
  cmd/juju/resource/list_test.go
  cmd/juju/romulus/listagreements/listagreements.go
  cmd/juju/romulus/listplans/list_plans.go
  cmd/juju/romulus/listwallets/list-wallets.go
  cmd/juju/romulus/showwallet/show_wallet.go
  cmd/juju/romulus/sla/sla.go
  cmd/juju/secrets/list_test.go
  cmd/juju/space/list.go
  cmd/juju/space/list_test.go
  cmd/juju/space/move.go
  cmd/juju/status/history_test.go
  cmd/juju/status/output_oneline.go
  cmd/juju/status/status_internal_test.go
  cmd/juju/status/status_test.go
  cmd/juju/storage/filesystemlist_test.go
  cmd/juju/storage/list_test.go
  cmd/juju/storage/poollist_test.go
  cmd/juju/storage/volumelist_test.go
  cmd/juju/user/list_test.go
  cmd/juju/user/whoami.go
  cmd/plugins/juju-metadata/listimages_test.go
  featuretests/cmd_juju_controller_test.go
  featuretests/cmd_juju_current_controller_test.go
  featuretests/cmd_juju_model_test.go
  featuretests/cmd_juju_resources_test.go
  featuretests/cmd_juju_status_test.go
  featuretests/cmd_juju_user_test.go
  featuretests/storage_test.go
  go.mod
  go.sum
  worker/uniter/runner/jujuc/secret-get.go
  worker/uniter/runner/jujuc/secret-get_test.go
Labels: dependencies, do not merge, 3.0

#14410 [JUJU-1479] Check lxd version
  apiserver/facades/client/controller/controller.go
  apiserver/facades/client/modelupgrader/register.go
  apiserver/facades/client/modelupgrader/upgrader.go
  apiserver/facades/client/modelupgrader/upgrader_test.go
  apiserver/facades/controller/migrationmaster/facade.go
  apiserver/facades/controller/migrationmaster/facade_test.go
  apiserver/facades/controller/migrationmaster/register.go
  cmd/juju/commands/upgrademodel.go
  migration/precheck.go
  migration/precheck_test.go
  provider/lxd/server.go
  provider/lxd/server_integration_test.go
  provider/lxd/server_test.go
  upgrades/upgradevalidation/migrate.go
  upgrades/upgradevalidation/migrate_test.go
  upgrades/upgradevalidation/mocks/lxd_mock.go
  upgrades/upgradevalidation/package_test.go
  upgrades/upgradevalidation/upgrade.go
  upgrades/upgradevalidation/upgrade_test.go
  upgrades/upgradevalidation/validation.go
  upgrades/upgradevalidation/validation_test.go
Labels: 2.9

#14432 Update secret hook commands for new syntax
  api/agent/secretsmanager/client.go
  api/agent/secretsmanager/client_test.go
  apiserver/facades/agent/secretsmanager/secrets.go
  apiserver/facades/agent/secretsmanager/secrets_test.go
  apiserver/facades/schema.json
  core/secrets/createsecret.go
  core/secrets/createsecret_test.go
  core/secrets/rotate.go
  core/secrets/secret.go
  rpc/params/secrets.go
  worker/uniter/hook/hook.go
  worker/uniter/hook/hook_test.go
  worker/uniter/remotestate/snapshot.go
  worker/uniter/runner/context/context.go
  worker/uniter/runner/context/context_test.go
  worker/uniter/runner/jujuc/context.go
  worker/uniter/runner/jujuc/secret-add.go
  worker/uniter/runner/jujuc/secret-add_test.go
  worker/uniter/runner/jujuc/secret-get.go
  worker/uniter/runner/jujuc/secret-update.go
  worker/uniter/runner/jujuc/secret-update_test.go
  worker/uniter/util_test.go
Labels: 3.0

#14435 Wireup revised secrets model backend
  api/agent/secretsmanager/client.go
  api/agent/secretsmanager/client_test.go
  api/client/secrets/client.go
  api/client/secrets/client_test.go
  api/watcher/watcher_test.go
  apiserver/facades/agent/secretsmanager/mocks/secretservice.go
  apiserver/facades/agent/secretsmanager/package_test.go
  apiserver/facades/agent/secretsmanager/register.go
  apiserver/facades/agent/secretsmanager/secrets.go
  apiserver/facades/agent/secretsmanager/secrets_test.go
  apiserver/facades/client/secrets/secrets.go
  apiserver/facades/client/secrets/secrets_test.go
  apiserver/facades/schema.json
  cmd/juju/secrets/list.go
  cmd/juju/secrets/list_test.go
  core/secrets/rotate.go
  core/secrets/secret.go
  rpc/params/secrets.go
  secrets/interface.go
  secrets/provider/juju/secrets.go
  secrets/provider/juju/secrets_test.go
  state/allcollections.go
  state/export_test.go
  state/migration_internal_test.go
  state/secrets.go
  state/secrets_test.go
  worker/uniter/runner/context/context.go
  worker/uniter/runner/context/context_test.go
  worker/uniter/runner/jujuc/context.go
  worker/uniter/runner/jujuc/secret-add.go
  worker/uniter/runner/jujuc/secret-add_test.go
  worker/uniter/runner/jujuc/secret-update_test.go
  worker/uniter/util_test.go
Labels: 3.0

#14450 Add secrets watcher backend for notifying of secret revision changes
  api/agent/secretsmanager/client.go
  api/agent/secretsmanager/client_test.go
  apiserver/facades/agent/secretsmanager/mocks/secretsconsumer.go
  apiserver/facades/agent/secretsmanager/mocks/secretservice.go
  apiserver/facades/agent/secretsmanager/mocks/secretswatcher.go
  apiserver/facades/agent/secretsmanager/package_test.go
  apiserver/facades/agent/secretsmanager/register.go
  apiserver/facades/agent/secretsmanager/secrets.go
  apiserver/facades/agent/secretsmanager/secrets_test.go
  apiserver/facades/agent/secretsmanager/state.go
  apiserver/facades/schema.json
  core/secrets/secret.go
  go.mod
  go.sum
  rpc/params/secrets.go
  secrets/interface.go
  secrets/provider/juju/secrets.go
  secrets/provider/juju/secrets_test.go
  state/export_test.go
  state/secrets.go
  state/secrets_test.go
  worker/uniter/runner/context/context_test.go
Labels: 3.0

#14418 Remove stub firewallers
  provider/equinix/environ.go
  provider/equinix/firewaller.go
  provider/manual/environ.go
  provider/oci/environ.go
  provider/oci/firewall.go
Labels: 2.9

#14447 [JUJU-1392] Deprecation check for bootstrap/deploy/add-machine/add-model commands
  .github/workflows/smoke.yml
  .github/workflows/snap.yml
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/updateseries.go
  apiserver/facades/client/machinemanager/machinemanager.go
  apiserver/facades/client/machinemanager/machinemanager_test.go
  apiserver/facades/client/machinemanager/upgradeseries.go
  cloudconfig/cloudinit/renderscript_test.go
  cmd/juju/application/deploy.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/bundlehandler_test.go
  cmd/juju/application/deployer/charm.go
  cmd/juju/application/deployer/deployer.go
  cmd/juju/application/deployer/deployer_test.go
  cmd/juju/application/deployer/interface.go
  cmd/juju/application/deployer/series_selector.go
  cmd/juju/application/deployer/series_selector_test.go
  cmd/juju/application/export_test.go
  cmd/juju/application/refresh_resources_test.go
  cmd/juju/application/refresh_test.go
  cmd/juju/application/refresher/refresher.go
  cmd/juju/application/removeapplication_test.go
  cmd/juju/application/unexpose_test.go
  cmd/juju/commands/bootstrap.go
  cmd/juju/commands/bootstrap_test.go
  cmd/juju/machine/upgradeseries.go
  cmd/juju/machine/upgradeseries_test.go
  cmd/plugins/juju-metadata/imagemetadata_test.go
  cmd/plugins/juju-metadata/validateimagemetadata_test.go
  core/bundle/changes/handlers.go
  core/charm/charmpath.go
  core/charm/charmpath_test.go
  core/charm/computedseries.go
  core/charm/computedseries_test.go
  core/series/supported.go
  core/series/supported_test.go
  core/series/supportedseries.go
  core/series/supportedseries_linux_test.go
  core/series/supportedseries_test.go
  environs/bootstrap/bootstrap_test.go
  environs/config/config.go
  environs/config/config_test.go
  featuretests/cmd_juju_deploy_test.go
  provider/lxd/export_test.go
  provider/lxd/provider.go
  provider/lxd/server.go
  provider/lxd/server_integration_test.go
  provider/lxd/server_test.go
  state/application.go
  state/state_test.go
  testing/factory/factory_test.go
  tests/suites/smoke/deploy.sh
  upgrades/upgradevalidation/migrate.go
  upgrades/upgradevalidation/package_test.go
  upgrades/upgradevalidation/upgrade.go
  upgrades/upgradevalidation/validation.go
  upgrades/upgradevalidation/validation_test.go
Labels: 3.0

#14465 [JUJU-1612] KVM broker does not stop VMs
  container/kvm/container_internal_test.go
  container/kvm/containerfactory.go
  container/kvm/containerfactory_test.go
Labels: 2.9

#14470 [JUJU-1584] Fix LP1984061 fix latest vs default channels for charmhub charms
  cmd/juju/charmhub/find.go
  core/charm/channel.go
  core/charm/repository/charmhub_test.go
  go.mod
  go.sum
  state/migration_import.go
  state/migration_import_test.go
  state/upgrades.go
  state/upgrades_test.go
  upgrades/backend.go
  upgrades/operations.go
  upgrades/steps_2934.go
  upgrades/steps_2934_test.go
  upgrades/upgrade_test.go
Labels: bug, 2.9

#14484 [JUJU-1661] Better detection of LXD support
  container/lxd/connection.go
  container/lxd/connection_test.go
  container/lxd/manager.go
  container/lxd/manager_test.go
  container/lxd/package_test.go
  container/lxd/server.go
Labels: 2.9

#14493 [JUJU-1610] Replace kr/pretty with canonical/pretty
  go.mod
  go.sum
Labels: dependencies, 2.9

#14487 [JUJU-1665] Clean up generated files
  .github/workflows/gen.yml
  apiserver/facades/client/spaces/package_mock_test.go
  apiserver/facades/client/spaces/package_test.go
  cloud/fallback_public_cloud.go
  cloudconfig/winuserdata.go
  cloudconfig/winuserdatawrapper.go
  core/network/zone.go
  core/raftlease/package_test.go
  generate/filetoconst/filetoconst.go
  generate/winuserdata/winuserdata.go
  provider/common/mocks/availability_zone.go
  provider/openstack/goose_mock_test.go
  provider/openstack/package_test.go
  provider/vsphere/internal/vsphereclient/ovf_ubuntu.go
  resource/mocks/cache_mock.go
  state/database.go
  state/mocks/resources_mock.go
  state/mocks/txn_mock.go
  testing/certs.go
  worker/caasapplicationprovisioner/mocks/facade_mock.go
  worker/mocks/doc.go
  worker/mocks/worker_mock.go
  worker/uniter/runner/context/mocks/payload_mock.go
Labels: 2.9, github_actions, go

#14523 [JUJU-1697] Update test with new charm revisions which support focal and jammy.
  tests/suites/deploy/deploy_revision.sh
Labels: 3.0

#14474 [JUJU-1584] Display bundle unmarshall errors when deploying with --dry-run
  cmd/juju/application/bundle/bundle.go
  cmd/juju/application/bundle/bundle_test.go
  cmd/juju/application/deployer/bundle.go
  cmd/juju/application/diffbundle.go
  go.mod
  go.sum
Labels: bug, 2.9

#14469 [JUJU-1624] Do not terminate migrated CMR offers
  apiserver/common/crossmodel/crossmodel.go
  apiserver/common/crossmodel/crossmodel_test.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations_test.go
  apiserver/watcher.go
  core/migration/errors.go
Labels: 2.9
