Repository juju/juju, pull requests merged in 2023-02, with the labels that each got.

#15103 [JUJU-2552] Respect model constraints bundle
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/bundlehandler_test.go
Labels: bug, 2.9

#15134 [JUJU-2627] Ensure that we boostrap dqlite in agent tests
  cmd/jujud/agent/agenttest/agent.go
Labels: feature, 3.2

#15127 [JUJU-2642] - Fix/lp 2004220
  cmd/juju/application/refresh.go
  state/secrets.go
  state/secrets_test.go
  worker/uniter/runner/context/contextfactory.go
Labels: bug, 3.0

#15132 [JUJU-2582] Migrate settings/scopes for relations to remote applications
  apiserver/facades/controller/remoterelations/interface.go
  apiserver/facades/controller/remoterelations/remoterelations.go
  apiserver/watcher.go
  state/migration_export.go
  state/migration_export_test.go
  state/migration_import.go
  state/migration_import_test.go
Labels: 2.9

#15106 [JUJU-2251] Fixed test-upgrade-series-test-upgrade-series-relation
  tests/suites/upgrade_series/base.sh
Labels: 3.2

#15148 [JUJU-2627] Better dqlite build setup
  .github/golangci-lint.config.experimental.yaml
  .github/golangci-lint.config.yaml
  .github/workflows/static-analysis.yml
  Makefile
  scripts/dqlite/Makefile
  scripts/dqlite/build-script.sh
  scripts/dqlite/scripts/dqlite/build-lxd.sh
  scripts/dqlite/scripts/dqlite/build.sh
  scripts/dqlite/scripts/dqlite/dqlite-build.sh
  scripts/dqlite/scripts/dqlite/dqlite-install.sh
  scripts/dqlite/scripts/dqlite/install-if-missing.sh
  scripts/dqlite/scripts/dqlite/install.sh
  scripts/dqlite/scripts/env.sh
  scripts/dqlite/scripts/musl/install-if-missing.sh
  scripts/dqlite/scripts/musl/install.sh
  scripts/dqlite/scripts/musl/musl-install.sh
  tests/suites/static_analysis/copyright.sh
  tests/suites/static_analysis/doc_go.py
  tests/suites/static_analysis/doc_go.sh
Labels: feature, 3.2

#15117 Equinix Provider - Allow traffic from other juju machines
  provider/equinix/environ.go
Labels: 2.9

#15141 [JUJU-2586] Fix LP19988587 Can't switch from edge channel to stable channel
  cmd/juju/application/refresh.go
  cmd/juju/application/refresh_test.go
  state/application.go
  state/application_test.go
  tests/suites/refresh/refresh.sh
  tests/suites/refresh/switch.sh
Labels: do not merge, 2.9

#15140 [JUJU-2627] Allow testing on a mac
  .github/workflows/client-tests.yml
  Makefile
  database/app/dqlite_linux.go
  database/app/dqlite_other.go
  database/bootstrap.go
  database/bootstrap_test.go
  database/client/dqlite_linux.go
  database/client/dqlite_other.go
  database/driver/dqlite_linux.go
  database/driver/dqlite_other.go
  database/errors.go
  database/option.go
  database/option_test.go
  database/testing/fullsuite.go
  worker/dbaccessor/logger_mock_test.go
  worker/dbaccessor/manifold.go
  worker/dbaccessor/manifold_test.go
  worker/dbaccessor/package_mock_test.go
  worker/dbaccessor/package_test.go
  worker/dbaccessor/repl.go
  worker/dbaccessor/worker.go
  worker/dbaccessor/worker_test.go
Labels: feature, 3.2

#15163 [JUJU-2713] Fixed test-refresh suite in 3.0
  tests/suites/refresh/refresh.sh
Labels: 3.0

#15129 [JUJU-2615] Clean up entity parsing for debug-log
  api/common/logs.go
  cmd/juju/commands/debuglog.go
  state/logs.go
Labels: 3.0

#15156 [JUJU-2550] ChangeLog DDL
  .github/workflows/cla.yml
  .github/workflows/client-tests.yml
  .github/workflows/gen.yml
  .github/workflows/snap.yml
  .github/workflows/static-analysis.yml
  .github/workflows/update-brew-formulae.yml
  Makefile
  cmd/jujud/agent/mocks/machine_mock.go
  database/schema/controller.go
  environs/tools/build.go
  scripts/dqlite/scripts/dqlite/dqlite-install.sh
  scripts/dqlite/scripts/dqlite/install-if-missing.sh
Labels: feature, 3.2

#15159 [JUJU-2627] Install musl by default to the system
  scripts/dqlite/scripts/musl/musl-install.sh
Labels: feature, 3.2

#15081 [JUJU-2524] Avoid creating default lxd bridge when calling lxd init
  api/agent/provisioner/provisioner_test.go
  apiserver/facades/agent/provisioner/provisioner.go
  apiserver/facades/agent/provisioner/provisioner_test.go
  container/lxd/initialisation.go
  container/lxd/initialisation_linux.go
  container/lxd/initialisation_test.go
  worker/provisioner/container_initialisation.go
  worker/provisioner/container_initialisation_test.go
  worker/provisioner/containerworker_test.go
Labels: 3.2

#15179 Allow debug mode for dqlite
  scripts/dqlite/scripts/dqlite/dqlite-build.sh
  scripts/dqlite/scripts/env.sh
Labels: feature, 3.2

#15180 [JUJU-2770] Cross compile by default
  .github/workflows/build.yml
  .github/workflows/client-tests.yml
  Makefile
  scripts/dqlite/scripts/musl/musl-install.sh
Labels: feature, 3.2

#15169 Remove unexposed API methods
  apiserver/facades/client/application/application.go
  apiserver/facades/schema.json
  generate/schemagen/gen/generator.go
  go.mod
  go.sum
Labels: 3.1

#15186 [JUJU-2823] Copy required methods from lxc/lxd shared package
  container/lxd/certificate.go
  container/lxd/connection.go
  container/lxd/initialisation_linux.go
  container/lxd/manager.go
  container/lxd/manager_test.go
  container/lxd/server.go
  container/lxd/shared.go
  container/lxd/shared_test.go
  provider/lxd/credentials.go
Labels: feature, 3.2

#15191 [JUJU-2823] Fix generate
  .github/workflows/gen.yml
  .gitignore
  Makefile
  scripts/dqlite/scripts/musl/musl-install.sh
Labels: feature, 3.2

#15203 Merge 29 into 30
  tests/suites/refresh/switch.sh
Labels: 3.0

#15193 [JUJU-1844] Bash-based version of nw-deploy-bionic-aks-test
  tests/includes/controller.sh
  tests/suites/deploy_aks/deploy_aks.sh
  tests/suites/deploy_aks/task.sh
Labels: 2.9

#15208 [JUJU-2874] Dqlite dependency bump
  scripts/dqlite/scripts/env.sh
Labels: feature, 3.2

#15214 [JUJU-2874] Update dqlite build shas
  scripts/dqlite/scripts/dqlite/dqlite-install.sh
Labels: feature, 3.2

#15196 [JUJU-2749] upgrade a resource without a new charm revision available.
  apiserver/facades/client/application/application.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/interface.go
  cmd/juju/application/deployer/mocks/deploy_mock.go
  cmd/juju/application/deployer/resource.go
  cmd/juju/application/refresh.go
  cmd/juju/application/refresh_resources_test.go
  cmd/juju/application/refresh_test.go
  cmd/juju/application/refresher/refresher.go
  cmd/juju/application/utils/interface.go
  cmd/juju/application/utils/mocks/charmresource_mock.go
  cmd/juju/application/utils/utils.go
  cmd/juju/application/utils/utils_test.go
  state/application.go
  state/resources.go
  tests/suites/resources/attach.sh
  tests/suites/resources/refresh.sh
  tests/suites/resources/task.sh
Labels: bug, 2.9
