Repository juju/juju, pull requests merged in 2023-06, with the labels that each got.

#15673 Add GitHub action to check for merge conflicts
  .github/workflows/merge.yml
Labels: 2.9

#15489 Update links in README
  README.md
Labels: 3.3

#15664 [JUJU-3849] Introduce a new ApiServerSuite fixture to replace JujuConnSuite
  api/agent/agent/machine_test.go
  api/agent/agent/model_test.go
  api/agent/agent/unit_test.go
  api/apiclient_test.go
  api/controller/controller/legacy_test.go
  api/httpclient_test.go
  api/state_macaroon_test.go
  api/state_test.go
  api/testing/macaroonsuite.go
  apiserver/admin_test.go
  apiserver/apiserver_test.go
  apiserver/auditconfig_test.go
  apiserver/backup_test.go
  apiserver/basesuite_test.go
  apiserver/charms_test.go
  apiserver/common/controllerconfig_test.go
  apiserver/debuglog_db_internal_test.go
  apiserver/debuglog_db_test.go
  apiserver/embeddedcli_test.go
  apiserver/export_test.go
  apiserver/facades/client/annotations/client_test.go
  apiserver/facades/client/block/client_test.go
  apiserver/facades/client/charms/client_test.go
  apiserver/facades/client/client/api_test.go
  apiserver/facades/client/client/client_test.go
  apiserver/facades/client/client/perm_test.go
  apiserver/facades/client/client/status_test.go
  apiserver/facades/client/client/testing/suite.go
  apiserver/introspection_test.go
  apiserver/logsink_internal_test.go
  apiserver/logsink_test.go
  apiserver/logtransfer_test.go
  apiserver/objects_test.go
  apiserver/pinger_test.go
  apiserver/pubsub_test.go
  apiserver/ratelimit_test.go
  apiserver/registration_test.go
  apiserver/resources_mig_test.go
  apiserver/rest_test.go
  apiserver/server_test.go
  apiserver/testing/stub_network.go
  apiserver/testserver/server.go
  apiserver/tools_test.go
  cmd/modelcmd/modelcommand_test.go
  featuretests/api_controller_test.go
  featuretests/api_credentialmanager_test.go
  featuretests/api_logger_test.go
  featuretests/api_meterstatus_test.go
  featuretests/api_undertaker_test.go
  featuretests/client_macaroon_test.go
  featuretests/cmd_juju_dumplogs_test.go
  featuretests/cmd_juju_metrics.go
  featuretests/dblog_test.go
  featuretests/package_test.go
  featuretests/tools_test.go
  juju/testing/apiserver.go
  juju/testing/conn.go
  state/model.go
  worker/uniter/relation/resolver_test.go
Labels: 4.0

#15654 [JUJU-3738] - Fix/backend ref count
  apiserver/common/secrets/secrets.go
  cmd/juju/secretbackends/list.go
  core/secrets/secretbackend.go
  go.mod
  go.sum
  state/migration_export.go
  state/migration_export_test.go
  state/migration_import.go
  state/migration_import_tasks.go
  state/migration_import_test.go
  state/package_test.go
  state/secretbackends.go
  state/secrets.go
  state/secrets_test.go
  state/state.go
  state/upgrades.go
  state/upgrades_test.go
  upgrades/backend.go
  upgrades/operations.go
  upgrades/steps_313.go
  upgrades/steps_313_test.go
  upgrades/upgrade_test.go
  worker/secretdrainworker/worker.go
  worker/secretdrainworker/worker_test.go
Labels: 3.1

#15675 [JUJU-3867] Replace JujuConnSuite with base caller unit tests in more api test suites
  api/agent/keyupdater/authorisedkeys.go
  api/agent/keyupdater/authorisedkeys_test.go
  api/agent/keyupdater/package_test.go
  api/agent/machiner/machine.go
  api/agent/machiner/machiner.go
  api/agent/machiner/machiner_test.go
  api/agent/reboot/export_test.go
  api/agent/reboot/reboot.go
  api/agent/reboot/reboot_test.go
  api/controller/firewaller/application.go
  api/controller/firewaller/application_test.go
  api/controller/firewaller/firewaller.go
  api/controller/firewaller/firewaller_test.go
  api/controller/firewaller/machine.go
  api/controller/firewaller/machine_test.go
  api/controller/firewaller/package_test.go
  api/controller/firewaller/relation.go
  api/controller/firewaller/relation_test.go
  api/controller/firewaller/state_test.go
  api/controller/firewaller/unit.go
  api/controller/firewaller/unit_test.go
  api/state.go
  apiserver/admin_test.go
  apiserver/server_test.go
  cmd/jujud/agent/machine.go
  cmd/jujud/agent/machine_test.go
  worker/apiaddressupdater/apiaddressupdater_test.go
  worker/apiaddressupdater/manifold.go
  worker/authenticationworker/manifold.go
  worker/authenticationworker/worker.go
  worker/authenticationworker/worker_test.go
  worker/machiner/manifold.go
  worker/machiner/state.go
  worker/reboot/reboot.go
  worker/reboot/reboot_test.go
  worker/stateconverter/converter.go
  worker/stateconverter/manifold.go
Labels: 4.0

#15686 [JUJU-3884] Pass WatchableDBGetter through to the API server
  apiserver/apiserver.go
  apiserver/facade/facadetest/context.go
  apiserver/facade/interface.go
  apiserver/facades/client/charms/client_test.go
  apiserver/facades/client/modelmanager/register.go
  apiserver/facades/controller/caasmodelconfigmanager/mocks/context_mock.go
  apiserver/facades/controller/externalcontrollerupdater/register.go
  apiserver/package_test.go
  apiserver/root.go
  apiserver/shared.go
  apiserver/shared_test.go
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/agent/machine/manifolds_test.go
  core/changestream/eventsource.go
  core/database/dbmanager.go
  domain/modelmanager/service/deleter_mock_test.go
  domain/modelmanager/service/package_test.go
  domain/modelmanager/service/service.go
  domain/modelmanager/service/service_test.go
  domain/modelmanager/service/state_mock_test.go
  domain/state.go
  juju/testing/apiserver.go
  provider/dummy/environs.go
  worker/apiserver/manifold.go
  worker/apiserver/manifold_test.go
  worker/apiserver/worker.go
  worker/apiserver/worker_state_test.go
  worker/apiserver/worker_test.go
  worker/changestream/manifold.go
  worker/changestream/worker.go
  worker/changestream/worker_test.go
  worker/dbaccessor/manifold.go
  worker/dbaccessor/worker_integration_test.go
Labels: 4.0

#15692 [JUJU-3906] Fix cmr secrets watcher to lookup offer uuid
  api/controller/crossmodelrelations/crossmodelrelations.go
  api/controller/crossmodelrelations/crossmodelrelations_test.go
  api/watcher/watcher_test.go
  apiserver/common/crossmodel/auth.go
  apiserver/common/crossmodel/auth_test.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations_test.go
  apiserver/facades/controller/crossmodelrelations/mock_test.go
  apiserver/facades/controller/crossmodelrelations/state.go
  apiserver/facades/controller/crossmodelsecrets/crossmodelsecrets.go
  apiserver/facades/schema.json
  rpc/params/secrets.go
  worker/remoterelations/manifold.go
  worker/remoterelations/mock_test.go
  worker/remoterelations/remoteapplicationworker.go
  worker/remoterelations/remoterelations.go
  worker/remoterelations/remoterelations_test.go
Labels: 3.1

#15649 [JUJU-3786] Added controller config domain
  domain/controllerconfig/controllerconfig_test.go
  domain/controllerconfig/package_test.go
  domain/controllerconfig/service/package_mock_test.go
  domain/controllerconfig/service/package_test.go
  domain/controllerconfig/service/service.go
  domain/controllerconfig/service/service_test.go
  domain/controllerconfig/state/package_test.go
  domain/controllerconfig/state/state.go
  domain/controllerconfig/state/state_test.go
Labels: 4.0

#15690 [JUJU-3893] Use correct application name in client for upload pending resources for server side deploy
  cmd/juju/application/deployer/charm.go
Labels: feature, 3.3

#15684 [JUJU-3897] Implement initial cloud domain service and state
  domain/cloud/service/package_mock_test.go
  domain/cloud/service/package_test.go
  domain/cloud/service/service.go
  domain/cloud/service/service_test.go
  domain/cloud/state/package_test.go
  domain/cloud/state/state.go
  domain/cloud/state/state_test.go
  domain/cloud/state/types.go
Labels: 4.0

#15685 [JUJU-3782] Replace external controller retrieval in facades with new domain
  apiserver/facades/controller/externalcontrollerupdater/domain_mock_test.go
  apiserver/facades/controller/externalcontrollerupdater/externalcontrollerupdater.go
  apiserver/facades/controller/externalcontrollerupdater/externalcontrollerupdater_test.go
  domain/externalcontroller/service/package_mock_test.go
  domain/externalcontroller/service/service.go
  domain/externalcontroller/service/service_test.go
  domain/externalcontroller/state/state.go
  domain/externalcontroller/state/state_test.go
Labels: 4.0

#15704 [JUJU-2938] Add DDL for controller_node table
  domain/schema/controller.go
  domain/schema/controller_test.go
Labels: 4.0

#15669 Bump version to 4.0-beta1
  cmd/juju/commands/main_test.go
  scripts/win-installer/setup.iss
  snap/snapcraft.yaml
  version/version.go
Labels: 4.0

#15681 [JUJU-3882] Fixed test-deploy-test-deploy-bundle-aws in 3.1
  tests/suites/deploy/bundles/cmr_bundles_test_deploy.yaml
  tests/suites/deploy/deploy_bundles.sh
Labels: 3.1

#15573 [JUJU-3447] Enable ModelFirewaller for OpenStack
  environs/config/config.go
  environs/config/config_test.go
  environs/jujutest/livetests.go
  go.mod
  go.sum
  provider/dummy/environs.go
  provider/openstack/export_test.go
  provider/openstack/firewaller.go
  provider/openstack/live_test.go
  provider/openstack/local_test.go
  provider/openstack/provider.go
Labels: 3.2

#15695 [JUJU-3921] Prevent spin lock on zero subscription dispatches
  core/changestream/change.go
  core/charm/downloader/mocks/repo_mocks.go
  core/charm/downloader/mocks/storage_mocks.go
  core/charm/downloader/package_test.go
  worker/changestream/eventmultiplexer/benchmarks_test.go
  worker/changestream/eventmultiplexer/change_mock_test.go
  worker/changestream/eventmultiplexer/eventmultiplexer.go
  worker/changestream/eventmultiplexer/eventmultiplexer_test.go
  worker/changestream/eventmultiplexer/package_test.go
  worker/changestream/stream/package_test.go
  worker/changestream/stream/stream.go
  worker/changestream/stream/stream_test.go
Labels: feature, 4.0

#15712 [JUJU-3965] Attempt faster Dqlite shutdown
  worker/dbaccessor/package_test.go
  worker/dbaccessor/tracker_test.go
  worker/dbaccessor/worker.go
  worker/dbaccessor/worker_test.go
Labels: 4.0

#15707 [JUJU-2938] Database migrations use a Delta type instead of just a string
  core/database/delta.go
  database/migration.go
  database/migration_test.go
  database/testing/simplesuite.go
  domain/schema/controller.go
  domain/schema/controller_test.go
  provider/dummy/environs.go
Labels: 4.0

#15723 [JUJU-3935] Remove fullDocumentBeforeChange field on mongodb changestream
  state/watcher/txnwatcher.go
Labels: 4.0

#15621 [JUJU-3762] Changestream watermark
  cmd/jujud/agent/machine/manifolds.go
  core/charm/downloader/mocks/charm_archive_mocks.go
  core/charm/downloader/mocks/charm_mocks.go
  core/charm/downloader/package_test.go
  database/errors.go
  database/errors_test.go
  database/testing/fullsuite.go
  domain/schema/controller.go
  domain/schema/controller_test.go
  worker/changestream/eventmultiplexer/eventmultiplexer.go
  worker/changestream/eventmultiplexer/eventmultiplexer_test.go
  worker/changestream/manifold.go
  worker/changestream/manifold_test.go
  worker/changestream/stream/logger_mock_test.go
  worker/changestream/stream/package_test.go
  worker/changestream/stream/stream.go
  worker/changestream/stream/stream_test.go
  worker/changestream/worker.go
  worker/changestream/worker_test.go
  worker/querylogger/worker_test.go
Labels: feature, 4.0

#15728 [JUJU-3981] Fix the app name in the client side for the DeployFromRepository
  cmd/juju/application/deployer/charm.go
  cmd/juju/application/deployer/charm_test.go
Labels: feature, 3.3

#15740 Remove dead code that was spotted by TIOBE
  cmd/juju/waitfor/model.go
Labels: 3.1

#15726 [JUJU-3935] Remove fullDocumentBeforeChange field on mongodb changestream
  state/watcher/txnwatcher.go
Labels: 3.1

#15746 [JUJU-4002] Allow migration from >=2.9.42 to 3.1.x
  apiserver/restrict_newer_client.go
  apiserver/restrict_newer_client_test.go
Labels: bug, 3.1

#15750 [JUJU-4002] Merge 3.1 into 3.2
  apiserver/restrict_newer_client.go
  apiserver/restrict_newer_client_test.go
Labels: 3.2

#15764 Remove state.Addresses() method
  apiserver/common/addresses.go
  apiserver/common/addresses_test.go
  apiserver/facades/agent/caasoperator/register.go
  apiserver/facades/agent/caasoperator/state.go
  apiserver/facades/controller/caasapplicationprovisioner/provisioner.go
  apiserver/facades/controller/caasapplicationprovisioner/state.go
  state/address.go
  state/address_test.go
  state/state_test.go
  worker/uniter/uniter_test.go
  worker/uniter/util_test.go
Labels: 4.0

#15753 [JUJU-4012] Remove string resource type
  apiserver/apiserver.go
  apiserver/common/resource.go
  apiserver/common/resource_test.go
  apiserver/facade/facadetest/context.go
  apiserver/facade/interface.go
  apiserver/facades/client/application/application_test.go
  apiserver/facades/client/applicationoffers/access_test.go
  apiserver/facades/client/applicationoffers/applicationoffers.go
  apiserver/facades/client/applicationoffers/applicationoffers_test.go
  apiserver/facades/client/applicationoffers/base_test.go
  apiserver/facades/client/applicationoffers/register.go
  apiserver/facades/client/backups/backups.go
  apiserver/facades/client/backups/backups_test.go
  apiserver/facades/client/backups/register.go
  apiserver/facades/client/charms/client_test.go
  apiserver/facades/client/highavailability/highavailability.go
  apiserver/facades/client/highavailability/highavailability_test.go
  apiserver/facades/client/highavailability/register.go
  apiserver/facades/controller/caasmodelconfigmanager/mocks/context_mock.go
  apiserver/root.go
  apiserver/shared.go
  apiserver/shared_test.go
Labels: feature, 4.0

#15744 [JUJU-3946] Remove feature flag: server-side-charm-deploy
  api/facadeversions.go
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/application_test.go
  apiserver/facades/client/application/register.go
  apiserver/facades/schema.json
  cmd/juju/application/deployer/charm.go
  cmd/juju/application/deployer/charm_test.go
  feature/flags.go
Labels: feature, 3.3

#15765 [JUJU-4032] Fix potential LXD bootstrap panic
  provider/lxd/export_test.go
  provider/lxd/server.go
  provider/lxd/server_integration_test.go
Labels: 3.1

#15702 [JUJU-3919] Extended controller schema DDL for model migrations
  domain/schema/controller.go
  domain/schema/schema_test.go
Labels: 4.0

#15763 [JUJU-4004] Watcher registry
  apiserver/facades/controller/caasmodelconfigmanager/mocks/auth_mock.go
  apiserver/facades/controller/caasmodelconfigmanager/mocks/context_mock.go
  apiserver/facades/controller/caasmodelconfigmanager/mocks/resources_mock.go
  apiserver/facades/controller/caasmodelconfigmanager/package_test.go
  core/watcher/registry/clock_mock_test.go
  core/watcher/registry/package_test.go
  core/watcher/registry/registry.go
  core/watcher/registry/registry_test.go
  core/watcher/registry/worker_mock_test.go
Labels: feature, 4.0

#15772 Remove apiserver/common from api package
  .github/workflows/gen.yml
  api/client/cloud/cloud.go
  api/client/cloud/cloud_test.go
  api/client/cloud/export_test.go
  api/package_test.go
  api/state_test.go
  api/watcher/watcher.go
  apiserver/common/cloud.go
  apiserver/facades/client/cloud/cloud.go
  apiserver/facades/client/cloud/cloud_test.go
  apiserver/facades/client/cloud/export_test.go
  cmd/containeragent/initialize/package_test.go
Labels: bug, 3.1

#15328 [JUJU-3226] Fix destroy-model/destroy-controller to handle --force better.
  api/client/modelmanager/modelmanager.go
  api/client/modelmanager/modelmanager_test.go
  api/controller/undertaker/undertaker.go
  apiserver/facades/client/modelupgrader/mocks/state_mock.go
  apiserver/facades/client/modelupgrader/shims.go
  apiserver/facades/client/modelupgrader/upgrader.go
  apiserver/facades/client/modelupgrader/upgrader_test.go
  apiserver/facades/controller/undertaker/mock_test.go
  apiserver/facades/controller/undertaker/register.go
  apiserver/facades/controller/undertaker/state.go
  apiserver/facades/controller/undertaker/undertaker.go
  apiserver/facades/controller/undertaker/undertaker_test.go
  apiserver/facades/schema.json
  cmd/juju/controller/destroy.go
  cmd/juju/controller/destroy_test.go
  cmd/juju/model/destroy.go
  cmd/juju/model/destroy_test.go
  cmd/jujud/agent/engine_test.go
  cmd/jujud/agent/model/manifolds.go
  cmd/jujud/agent/model/manifolds_test.go
  core/life/life.go
  core/life/life_test.go
  state/model.go
  tests/includes/juju.sh
  worker/undertaker/manifold.go
  worker/undertaker/manifold_test.go
  worker/undertaker/mock_test.go
  worker/undertaker/undertaker.go
  worker/undertaker/undertaker_test.go
  worker/undertaker/validate_test.go
Labels: 2.9

#15769 Change usage of upsert statements.
  domain/cloud/state/state.go
  domain/externalcontroller/state/state.go
Labels: 4.0

#15762 'Correct' ipv6-icmp protocol type to icmp in O7k
  provider/openstack/firewaller.go
  provider/openstack/local_test.go
Labels: 2.9

#15775 [JUJU-4049] Fix data race in multiplexer
  worker/changestream/eventmultiplexer/benchmarks_test.go
  worker/changestream/eventmultiplexer/eventmultiplexer.go
  worker/changestream/eventmultiplexer/eventmultiplexer_test.go
  worker/changestream/eventmultiplexer/logger_mock_test.go
  worker/changestream/eventmultiplexer/package_test.go
  worker/changestream/eventmultiplexer/stream_mock_test.go
  worker/changestream/eventmultiplexer/subscription.go
  worker/changestream/stream/stream.go
Labels: 4.0

#15780 [JUJU-4056] Fix data race dbaccessor
  testing/logger.go
  worker/dbaccessor/package_test.go
  worker/dbaccessor/tracker_test.go
  worker/dbaccessor/worker.go
  worker/dbaccessor/worker_test.go
Labels: feature, 4.0

#15776 [JUJU-4050] Cache watchable DB
  cmd/jujud/agent/machine/manifolds.go
  worker/changestream/manifold.go
  worker/changestream/manifold_test.go
  worker/changestream/package_test.go
  worker/changestream/stream_mock_test.go
  worker/changestream/watchabledb.go
  worker/changestream/worker.go
  worker/changestream/worker_test.go
  worker/dbaccessor/worker.go
Labels: feature, 4.0

#15696 [JUJU-3782] Add watch capabilities on external controller domain
  apiserver/facades/controller/externalcontrollerupdater/domain_mock_test.go
  apiserver/facades/controller/externalcontrollerupdater/externalcontrollerupdater.go
  apiserver/facades/controller/externalcontrollerupdater/externalcontrollerupdater_test.go
  apiserver/facades/controller/externalcontrollerupdater/mock_test.go
  apiserver/facades/controller/externalcontrollerupdater/package_test.go
  apiserver/facades/controller/externalcontrollerupdater/register.go
  apiserver/facades/controller/externalcontrollerupdater/watcher_mock_test.go
  core/watcher/eventsource/base.go
  core/watcher/eventsource/changestream_mock_test.go
  core/watcher/eventsource/key.go
  core/watcher/eventsource/key_test.go
  core/watcher/eventsource/keys.go
  core/watcher/eventsource/keys_test.go
  core/watcher/eventsource/package_test.go
  domain/externalcontroller/service/service.go
  domain/externalcontroller/service/service_test.go
  domain/watcher.go
  domain/watcher_test.go
Labels: 4.0

#15773 [JUJU-3932] Create upgrades schema
  domain/schema/controller.go
  domain/schema/schema_test.go
Labels: 4.0

#15789 [JUJU-4082] Ensure ha setup complete before moving on with test.
  tests/suites/controller/enable_ha.sh
Labels: 3.1

#15680 [JUJU-3881] Any 3.x client can initiate migration from 2.9
  .github/workflows/migrate.yml
Labels: 3.1

#15782 [JUJU-4012] Wire up watcher registry
  apiserver/admin.go
  apiserver/apiserver.go
  apiserver/export_test.go
  apiserver/facade/facadetest/context.go
  apiserver/facade/interface.go
  apiserver/facade/mocks/facade_mock.go
  apiserver/facade/package_test.go
  apiserver/facade/resources.go
  apiserver/facade/watcherregistry.go
  apiserver/facades/client/pinger/register.go
  apiserver/facades/controller/caasmodelconfigmanager/mocks/context_mock.go
  apiserver/root.go
  worker/dbaccessor/package_test.go
  worker/dbaccessor/tracker_test.go
  worker/dbaccessor/worker_test.go
Labels: 4.0

#15729 [JUJU-3975] Adds support for model DDL databases.
  database/statement.go
  database/statement_test.go
  database/testing/simplesuite.go
  domain/schema/changelog.go
  domain/schema/controller.go
  domain/schema/model.go
  go.mod
  go.sum
Labels: 4.0

#15802 [JUJU-2024] Fix 2024783 - do not panic on invalid task|operation ID
  cmd/juju/action/cancel.go
  cmd/juju/action/cancel_test.go
  cmd/juju/action/showoperation.go
  cmd/juju/action/showoperation_test.go
  cmd/juju/action/showtask.go
  cmd/juju/action/showtask_test.go
Labels: bug, 3.1

#15804 [JUJU-4096] Convert firewaller worker tests to unit tests
  worker/firewaller/firewaller.go
  worker/firewaller/firewaller_test.go
  worker/firewaller/interface.go
  worker/firewaller/mocks/credential_mocks.go
  worker/firewaller/mocks/entity_mocks.go
  worker/firewaller/mocks/facade_mocks.go
  worker/firewaller/package_test.go
  worker/firewaller/ports_test.go
  worker/firewaller/shim.go
Labels: 4.0

#15815 [JUJU-4052] - Do markObsoleteRevisionOps only if consumer revision changed;
  state/package_test.go
  state/secrets.go
  state/secrets_test.go
Labels: bug, 3.1

#15738 [JUJU-3995] Introduction of CODEOWNERS
  .github/CODEOWNERS
Labels: 4.0

#15766 [JUJU-3928] Add image-id constraint on openstack
  provider/openstack/local_test.go
  provider/openstack/provider.go
Labels: 3.3

#15824 Lease expiry domain
  cmd/jujud/agent/machine/manifolds.go
  core/lease/store.go
  domain/lease/service/service.go
  domain/lease/service/service_test.go
  domain/lease/service/state_mock_test.go
  domain/lease/state/state.go
  domain/lease/state/state_test.go
  juju/testing/apiserver.go
  worker/lease/manifold.go
  worker/lease/manifold_test.go
  worker/leaseexpiry/manifold.go
  worker/leaseexpiry/manifold_test.go
  worker/leaseexpiry/package_test.go
  worker/leaseexpiry/store_mock_test.go
  worker/leaseexpiry/worker.go
  worker/leaseexpiry/worker_test.go
Labels: 4.0

#15821 [JUJU-4033] Subordinates are deployed with a num units of 0.
  apiserver/facades/client/application/deployrepository.go
  apiserver/facades/client/application/deployrepository_test.go
Labels: 3.3

#15820 [JUJU-4012] Fix apiserver watchers
  apiserver/allfacades.go
  apiserver/common/relationunitswatcher.go
  apiserver/common/resource.go
  apiserver/facades/client/applicationoffers/register.go
  apiserver/facades/client/pinger/register.go
  apiserver/facades/controller/crossmodelrelations/register.go
  apiserver/facades/controller/crossmodelsecrets/register.go
  apiserver/facades/controller/externalcontrollerupdater/externalcontrollerupdater.go
  apiserver/facades/schema.json
  apiserver/internal/package_test.go
  apiserver/internal/watcher.go
  apiserver/internal/watcher_mock_test.go
  apiserver/internal/watcher_test.go
  apiserver/root.go
  apiserver/watcher.go
  core/pinger/pinger.go
Labels: 4.0

#15823 Revert 15398
  api/client/application/client.go
  api/client/application/client_test.go
  api/client/applicationoffers/client.go
  api/client/applicationoffers/client_test.go
  apiserver/apiserver.go
  apiserver/common/crossmodel/auth.go
  apiserver/common/crossmodel/auth_test.go
  apiserver/export_test.go
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/application_unit_test.go
  apiserver/facades/client/applicationoffers/access_test.go
  apiserver/facades/client/applicationoffers/applicationoffers_test.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations_test.go
  apiserver/facades/controller/crossmodelsecrets/crossmodelsecrets_test.go
  apiserver/facades/schema.json
  apiserver/localofferauth.go
  apiserver/testing/fakeauthorizer.go
  cmd/juju/application/consume.go
  cmd/juju/application/consume_test.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/integrate.go
  cmd/juju/application/integrateremote_test.go
  core/crossmodel/interface.go
  rpc/params/crossmodel.go
  state/applicationoffers.go
  state/migration_export_test.go
  state/remoteapplication.go
  state/remoteapplication_test.go
Labels: do not merge, 3.2

#15818 [JUJU-3929] Add openstack image-id constraint integration test
  tests/suites/constraints/constraints.sh
  tests/suites/constraints/constraints_openstack.sh
Labels: 3.3

#15800 [JUJU-4097] Model database migration coordinator
  core/migration/package_test.go
  core/migration/targetinfo_test.go
  core/modelmigration/coordinator.go
  core/modelmigration/coordinator_test.go
  core/modelmigration/description_mock_test.go
  core/modelmigration/doc.go
  core/modelmigration/getter_mock_test.go
  core/modelmigration/op_mock_test.go
  core/modelmigration/pacage_test.go
Labels: 4.0
