Repository juju/juju, pull requests merged in 2023-11, with the labels that each got.

#16518 Use names when adding user secrets and include in tabular list
  api/client/secrets/client.go
  api/client/secrets/client_test.go
  apiserver/common/secrets/mocks/commonsecrets_mock.go
  apiserver/common/secrets/secrets.go
  apiserver/common/secrets/secrets_test.go
  apiserver/common/secrets/state.go
  apiserver/facades/agent/secretsmanager/secrets.go
  apiserver/facades/client/secrets/secrets.go
  apiserver/facades/client/secrets/secrets_test.go
  apiserver/facades/controller/usersecrets/mocks/state.go
  apiserver/facades/controller/usersecrets/secrets.go
  apiserver/facades/controller/usersecrets/state.go
  apiserver/facades/schema.json
  cmd/juju/secrets/add.go
  cmd/juju/secrets/add_test.go
  cmd/juju/secrets/common.go
  cmd/juju/secrets/grantrevoke.go
  cmd/juju/secrets/grantrevoke_test.go
  cmd/juju/secrets/list.go
  cmd/juju/secrets/list_test.go
  cmd/juju/secrets/mocks/secretsapi.go
  cmd/juju/secrets/remove.go
  cmd/juju/secrets/remove_test.go
  cmd/juju/secrets/show.go
  cmd/juju/secrets/show_test.go
  cmd/juju/secrets/update.go
  cmd/juju/secrets/update_test.go
  core/secrets/secret.go
  rpc/params/secrets.go
  state/secrets.go
  state/secrets_test.go
  tests/suites/secrets_iaas/juju.sh
  tests/suites/secrets_iaas/vault.sh
  tests/suites/secrets_k8s/k8s.sh
Labels: 3.3

#16527 Remove provider all in the wait-for
  cmd/juju/waitfor/waitfor.go
Labels: 3.1

#16484 Fix "detecing" ("detecting") typo in k8s provider
  caas/kubernetes/provider/detectcloud.go
Labels: 3.3

#16402 Wire up dqlite trace
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/agent/machine/manifolds_test.go
  domain/lease/state/state.go
  go.mod
  go.sum
  internal/database/txn/transaction.go
  juju/testing/apiserver.go
  worker/lease/config.go
  worker/lease/fixture_test.go
  worker/lease/manager.go
  worker/lease/manager_cross_test.go
  worker/lease/manager_validation_test.go
  worker/lease/manifold.go
  worker/lease/manifold_test.go
  worker/leaseexpiry/manifold.go
  worker/leaseexpiry/manifold_test.go
  worker/leaseexpiry/worker.go
  worker/leaseexpiry/worker_test.go
Labels: 4.0

#16534 Controller config string duration
  controller/config.go
  controller/configschema.go
  go.mod
  go.sum
Labels: 4.0

#16536 Remove tools version todo
  apiserver/tools.go
Labels: 4.0

#16127 juju-txn-helper: Allow querying of the full transaction collection
  scripts/juju-txn-helper/README.txt
  scripts/juju-txn-helper/test_txn_helper.py
  scripts/juju-txn-helper/txn_helper.py
Labels: 2.9

#16500 Remove upgrades from state
  apiserver/errors/errors.go
  apiserver/facades/agent/upgrader/upgrader_test.go
  apiserver/facades/client/client/backend.go
  apiserver/facades/client/client/mocks/client_mock.go
  apiserver/facades/client/controller/controller_test.go
  apiserver/facades/client/modelmanager/modelmanager_test.go
  apiserver/facades/client/modelupgrader/mocks/state_mock.go
  apiserver/facades/client/modelupgrader/package_test.go
  apiserver/facades/client/modelupgrader/register.go
  apiserver/facades/client/modelupgrader/shims.go
  apiserver/facades/client/modelupgrader/upgrader.go
  apiserver/facades/client/modelupgrader/upgrader_test.go
  apiserver/facades/schema.json
  cmd/containeragent/initialize/package_test.go
  cmd/juju/commands/mocks/modelupgrader_mock.go
  cmd/juju/commands/upgradecontroller.go
  cmd/juju/commands/upgrademodel.go
  cmd/juju/commands/upgrademodel_test.go
  cmd/jujud/agent/machine_test.go
  core/upgrade/errors.go
  scripts/juju-force-upgrade/main.go
  state/application.go
  state/binarystorage_test.go
  state/enableha.go
  state/errors/common.go
  state/export_test.go
  state/machine.go
  state/mocks/upgrader_mock.go
  state/package_test.go
  state/state.go
  state/state_test.go
  state/unit.go
  state/upgrade.go
  state/upgrade_test.go
  state/watcher.go
  worker/caasupgrader/upgrader.go
  worker/upgradedatabase/worker.go
  worker/upgrader/upgrader.go
  worker/upgradesteps/controllerworker.go
Labels: 4.0

#16519 Dqlite safe-mode
  cmd/jujud/agent/machine.go
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/agent/machine_test.go
  cmd/jujud/agent/safemode.go
  cmd/jujud/agent/safemode/manifolds.go
  cmd/jujud/agent/safemode/manifolds_test.go
  cmd/jujud/agent/safemode/package_test.go
  cmd/jujud/main.go
  cmd/jujud/util/stateflag.go
Labels: 4.0

#16520 [JUJU-4732] Use charm name string instead of charm URL
  apiserver/facades/client/application/repository_mocks_test.go
  apiserver/facades/client/charms/client.go
  apiserver/facades/client/charms/client_test.go
  apiserver/facades/client/charms/mocks/repository.go
  cmd/jujud/agent/bootstrap_test.go
  cmd/jujud/agent/controllercharm.go
  core/charm/downloader/downloader.go
  core/charm/downloader/downloader_test.go
  core/charm/downloader/export_test.go
  core/charm/downloader/mocks/charm_mocks.go
  core/charm/repository.go
  core/charm/repository/charmhub.go
  core/charm/repository/charmhub_test.go
Labels: 3.3

#16571 Object store metadata schema
  domain/schema/controller.go
  domain/schema/model.go
  domain/schema/objectstore.go
  domain/schema/schema_test.go
Labels: 4.0

#16555 Check error before checking image field
  container/lxd/image.go
Labels: 3.1

#16574 New password types and hasing for Juju and Dqlite.
  internal/auth/doc.go
  internal/auth/package_test.go
  internal/auth/password.go
  internal/auth/password_test.go
Labels: 4.0

#16550 Schema for Users
  domain/schema/controller.go
  domain/schema/schema_test.go
  domain/user/state/package_test.go
  domain/user/state/state_test.go
Labels: 4.0

#16543 Fuzz wait-for query and lexer
  Makefile
  cmd/juju/waitfor/query/parser_test.go
Labels: 4.0

#16565 Write caas application provisioner worker doc.go
  worker/caasapplicationprovisioner/doc.go
Labels: 3.3

#16573 Bump version to 3.4-beta1
  scripts/win-installer/setup.iss
  snap/snapcraft.yaml
  version/version.go
Labels: 3.4

#16561 Remove the places we compare charmurl series to bundle
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/store/charmadapter.go
  cmd/juju/application/store/charmadapter_test.go
  cmd/juju/application/store/resolve.go
  cmd/juju/resource/charmresources.go
Labels: 3.3

#16557 [JUJU-4638] Rename & refactor DeduceOrigin to MakeOrigin & remove charm url
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/bundlehandler_test.go
  cmd/juju/application/deployer/charm.go
  cmd/juju/application/deployer/deployer.go
  cmd/juju/application/diffbundle.go
  cmd/juju/application/refresh_test.go
  cmd/juju/application/refresher/refresher.go
  cmd/juju/application/store/store_test.go
  cmd/juju/application/utils/origin.go
  core/charm/channel.go
  core/charm/channel_test.go
Labels: 4.0

#16598 Treat owners of secrets the same as other consumers when reading secret content
  apiserver/common/secrets/access.go
  apiserver/common/secrets/access_test.go
  apiserver/facades/agent/secretsmanager/secrets.go
  apiserver/facades/agent/secretsmanager/secrets_test.go
  state/migration_import_tasks.go
  state/migration_import_test.go
  state/secrets.go
  state/upgrades.go
  state/upgrades_test.go
  upgrades/backend.go
  upgrades/steps_317.go
  upgrades/steps_317_test.go
Labels: 3.1

#16593 Drop unnecessary reference to curl Series
  upgrades/upgradevalidation/validation.go
Labels: 3.4

#16595 Drop curl.Series check
  cmd/juju/application/refresher/refresher.go
Labels: 3.4

#16556 Service layer for Users domain
  core/user/user.go
  domain/schema/controller.go
  domain/schema/schema_test.go
  domain/user/errors/errors.go
  domain/user/service/package_test.go
  domain/user/service/service.go
  domain/user/service/service_test.go
  domain/user/service/state_mock_test.go
  internal/auth/password.go
  internal/auth/password_test.go
Labels: 4.0

#16603 Inhook secret refresh
  api/agent/uniter/unit.go
  apiserver/facades/agent/secretsmanager/secrets.go
  apiserver/facades/agent/secretsmanager/secrets_test.go
  apiserver/facades/agent/uniter/uniter.go
  apiserver/facades/agent/uniter/uniter_test.go
  apiserver/facades/schema.json
  rpc/params/internal.go
  state/application.go
  state/secrets.go
  state/secrets_test.go
  worker/uniter/runner/context/context.go
  worker/uniter/runner/context/context_test.go
  worker/uniter/runner/context/export_test.go
  worker/uniter/runner/context/secrets.go
Labels: 3.1

#16583 Update merge bot
  .github/workflows/merge.yml
Labels: 2.9

#16537 Objectstore global tools
  apiserver/apiserver.go
  apiserver/common/mocks/domain_mock.go
  apiserver/common/mocks/objectstore.go
  apiserver/common/mocks/storage.go
  apiserver/common/mocks/tools_mock.go
  apiserver/common/package_test.go
  apiserver/common/tools.go
  apiserver/common/tools_test.go
  apiserver/common/unitstate.go
  apiserver/common/unitstate_test.go
  apiserver/export_test.go
  apiserver/facade/facadetest/context.go
  apiserver/facade/interface.go
  apiserver/facades/agent/provisioner/provisioner.go
  apiserver/facades/agent/secretsdrain/mocks/facade_mock.go
  apiserver/facades/agent/upgrader/register.go
  apiserver/facades/agent/upgrader/upgrader.go
  apiserver/facades/agent/upgrader/upgrader_test.go
  apiserver/facades/client/client/client.go
  apiserver/facades/client/machinemanager/instance_information_test.go
  apiserver/facades/client/machinemanager/instanceconfig.go
  apiserver/facades/client/machinemanager/instanceconfig_test.go
  apiserver/facades/client/machinemanager/machinemanager.go
  apiserver/facades/client/machinemanager/machinemanager_test.go
  apiserver/facades/client/machinemanager/mocks/instance_config_mock.go
  apiserver/facades/client/machinemanager/mocks/objectstore_mock.go
  apiserver/facades/client/machinemanager/mocks/state_storage_mock.go
  apiserver/facades/client/machinemanager/mocks/types_mock.go
  apiserver/facades/client/machinemanager/package_test.go
  apiserver/facades/client/machinemanager/state.go
  apiserver/facades/client/modelmanager/mocks/domain_mock.go
  apiserver/facades/client/modelmanager/modelmanager_test.go
  apiserver/facades/client/modelmanager/package_test.go
  apiserver/facades/client/modelmanager/register.go
  apiserver/facades/client/modelupgrader/register.go
  apiserver/facades/controller/caasmodelconfigmanager/facade.go
  apiserver/facades/controller/caasmodelconfigmanager/mocks/context_mock.go
  apiserver/httpcontext.go
  apiserver/root.go
  apiserver/tools.go
  apiserver/tools_test.go
  cmd/jujud/agent/bootstrap.go
  cmd/jujud/agent/bootstrap_test.go
  juju/testing/utils.go
  scripts/juju-list-blobstore/main.go
  state/binarystorage.go
  state/binarystorage/binarystorage.go
  state/binarystorage/binarystorage_test.go
  state/binarystorage/interface.go
  state/binarystorage/layered.go
  state/binarystorage/layered_test.go
  state/binarystorage_test.go
  state/state.go
  worker/objectstore/manifold.go
  worker/objectstore/objectstore_mock_test.go
  worker/objectstore/worker.go
Labels: 4.0

#16605 Remove unused charms endpoint
  apiserver/apiserver.go
  apiserver/charms_test.go
Labels: 4.0

#16599 Merge 2.9 into 3.1
  cloud/clouds.go
  cloud/clouds_test.go
Labels: 3.1

#16576 Precheck target controller migrations
  api/apiclient.go
  api/controller/migrationmaster/client_test.go
  api/controller/migrationtarget/client.go
  api/controller/migrationtarget/client_test.go
  api/export_test.go
  api/facadeversions.go
  api/facadeversions_test.go
  api/package_test.go
  apiserver/allfacades.go
  apiserver/allfacades_test.go
  apiserver/facades/controller/migrationtarget/migrationtarget.go
  apiserver/facades/controller/migrationtarget/migrationtarget_test.go
  apiserver/facades/controller/migrationtarget/register.go
  apiserver/facades/schema.json
  cmd/containeragent/initialize/package_test.go
  core/facades/facade.go
  core/facades/facade_test.go
  core/facades/package_test.go
  migration/precheck.go
  rpc/params/migration.go
  worker/migrationmaster/worker_test.go
Labels: 3.1

#16609 Prevent panic in wait-for command
  cmd/juju/waitfor/errors.go
Labels: 3.1

#16607 Better ModelDefaults values.
  domain/modelconfig/bootstrap/bootstrap.go
  domain/modelconfig/bootstrap/bootstrap_test.go
  domain/modelconfig/service/service.go
  domain/modelconfig/service/service_test.go
  domain/modelconfig/service/testing/service.go
  domain/modeldefaults/bootstrap/bootstrap.go
  domain/modeldefaults/bootstrap/bootstrap_test.go
  domain/modeldefaults/service/service.go
  domain/modeldefaults/service/service_test.go
  domain/modeldefaults/types.go
  domain/modeldefaults/types_test.go
Labels: 4.0

#16465 Fix WWW-Authenticate challenge handling with docker registries.
  docker/auth.go
  docker/auth_test.go
  docker/registry/internal/base_client.go
  docker/registry/internal/package_test.go
  docker/registry/internal/transports.go
  docker/registry/internal/transports_test.go
  make_functions.sh
Labels: 2.9

#16570 Objectstore global filestore
  cmd/containeragent/initialize/package_test.go
  cmd/jujud/agent/bootstrap.go
  cmd/jujud/agent/machine/manifolds.go
  controller/config.go
  controller/config_test.go
  controller/configschema.go
  core/objectstore/package_test.go
  core/objectstore/types.go
  core/objectstore/types_test.go
  internal/objectstore/factory.go
  internal/objectstore/factory_test.go
  internal/objectstore/objectstore_mock_test.go
  internal/objectstore/package_test.go
  internal/objectstore/stateobjectstore.go
  juju/testing/apiserver.go
  juju/testing/utils.go
  scripts/juju-list-blobstore/main.go
  state/controller_test.go
  testing/factory/factory.go
  worker/objectstore/manifold.go
  worker/objectstore/manifold_test.go
  worker/objectstore/worker.go
  worker/objectstore/worker_test.go
Labels: 4.0

#16512 Add subnet, fan and availability zone schemas
  domain/schema/model.go
  domain/schema/schema_test.go
Labels: 4.0

#16606 3.4 into main
  README.md
  cmd/juju/application/bundle_test.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/bundlehandler_test.go
  cmd/juju/application/deployer/charm.go
  cmd/juju/application/deployer/deployer.go
  cmd/juju/application/diffbundle.go
  cmd/juju/application/refresh_test.go
  cmd/juju/application/refresher/refresher.go
  cmd/juju/application/store/charmadapter.go
  cmd/juju/application/store/charmadapter_test.go
  cmd/juju/application/store/resolve.go
  cmd/juju/application/store/store_test.go
  cmd/juju/application/utils/origin.go
  cmd/juju/resource/charmresources.go
  core/charm/channel.go
  core/charm/channel_test.go
  worker/caasadmission/doc.go
Labels: 4.0

#16575 Trace flags: Sample ratio
  agent/agent.go
  agent/agent_test.go
  agent/format-2.0.go
  api/base/caller.go
  cloudconfig/instancecfg/instancecfg.go
  cloudconfig/podcfg/podcfg.go
  cmd/containeragent/initialize/config.go
  cmd/jujud/agent/agenttest/agent.go
  cmd/jujud/agent/bootstrap.go
  controller/config.go
  controller/config_test.go
  controller/configschema.go
  core/trace/context.go
  core/trace/tracer.go
  internal/upgrade/agent_mock_test.go
  internal/upgradesteps/agent_mock_test.go
  rpc/client.go
  rpc/context.go
  rpc/context_test.go
  rpc/dispatch_test.go
  rpc/jsoncodec/codec.go
  rpc/rpc_test.go
  rpc/server.go
  state/controller_test.go
  worker/agentconfigupdater/manifold.go
  worker/agentconfigupdater/manifold_test.go
  worker/agentconfigupdater/worker.go
  worker/agentconfigupdater/worker_test.go
  worker/containerbroker/mocks/agent_mock.go
  worker/instancemutater/mocks/agent_mock.go
  worker/objectstore/agent_mock_test.go
  worker/stateconverter/mocks/agent_mock.go
  worker/trace/agent_mock_test.go
  worker/trace/manifold.go
  worker/trace/manifold_test.go
  worker/trace/tracer.go
  worker/trace/tracer_test.go
  worker/trace/worker.go
  worker/trace/worker_test.go
  worker/upgradedatabase/agent_mock_test.go
  worker/upgradesteps/agent_mock_test.go
  worker/upgradestepsmachine/agent_mock_test.go
Labels: 4.0

#16615 Remove life from environ spaces
  environs/space/spaces.go
  environs/space/spaces_mock_test.go
  environs/space/spaces_test.go
  state/spaces.go
  state/spaces_test.go
Labels: 4.0

#16623 Merge 2.9 into 3.1
  testcharms/charms/lxd-profile-subordinate/charmcraft.yaml
  testcharms/charms/lxd-profile-subordinate/metadata.yaml
  testcharms/charms/lxd-profile-without-devices/charmcraft.yaml
  testcharms/charms/lxd-profile-without-devices/metadata.yaml
  testcharms/charms/lxd-profile/charmcraft.yaml
  testcharms/charms/lxd-profile/metadata.yaml
  tests/suites/deploy/charms/lxd-profile-alt/manifest.yaml
  tests/suites/deploy/charms/lxd-profile/manifest.yaml
  tests/suites/deploy/deploy_bundles.sh
  tests/suites/deploy/deploy_charms.sh
Labels: 3.1

#16626 Improve PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: 3.4

#16627 Backport change from 3.1 to fix model config test.
  tests/suites/model/config.sh
Labels: 2.9

#16622 Output controller and model logs to archive
  tests/includes/juju.sh
  tests/includes/pids.sh
  tests/main.sh
  tests/suites/ck/ck.sh
  tests/suites/secrets_iaas/cmr.sh
  tests/suites/secrets_iaas/juju.sh
  tests/suites/secrets_iaas/vault.sh
Labels: 3.1

#16629 Fixes deploy_aks CI test
  tests/suites/deploy_aks/deploy_aks.sh
Labels: 2.9

#16613 Objectstore state
  core/objectstore/metadata.go
  domain/errors.go
  domain/externalcontroller/state/state.go
  domain/externalcontroller/state/state_test.go
  domain/objectstore/errors.go
  domain/objectstore/package_test.go
  domain/objectstore/service/package_test.go
  domain/objectstore/service/service.go
  domain/objectstore/service/service_test.go
  domain/objectstore/service/state_mock_test.go
  domain/objectstore/state/package_test.go
  domain/objectstore/state/state.go
  domain/objectstore/state/state_test.go
  domain/objectstore/types.go
  domain/objectstore/watcher_test.go
  domain/schema/controller.go
  domain/schema/model.go
  domain/schema/objectstore.go
Labels: 4.0

#16594 Add support for downloading a specific revision with juju download
  cmd/juju/charmhub/download.go
  cmd/juju/charmhub/download_test.go
Labels: bug, 3.1

#16630 [JUJU-5059] - Simplify vault setup for secret Iaas tests;
  tests/suites/secrets_iaas/vault.sh
  tests/suites/secrets_k8s/k8s.sh
Labels: 3.1

#16632 Ensure iface matcher returns a valid value
  tests/suites/spaces_ec2/util.sh
Labels: 2.9

#16643 Rename uuid to id on subnet types tables
  domain/schema/model.go
Labels: 4.0

#16634 Validate api client imports
  .github/api-client-allowed-list.txt
  apiserver/facades/controller/usersecretsdrain/state.go
  tests/suites/static_analysis/lint_go.py
  tests/suites/static_analysis/lint_go.sh
Labels: 3.3

#16649 Merge 2.9 into 3.1
  state/allcollections.go
  tests/suites/spaces_ec2/util.sh
Labels: 3.1

#16651 Fix deploy charms to lxd container CI test
  tests/suites/deploy/deploy_charms.sh
Labels: 3.1

#16604 Secret grant info
  api/agent/secretsmanager/client.go
  api/agent/secretsmanager/client_test.go
  api/agent/uniter/unit.go
  api/client/secrets/client.go
  api/client/secrets/client_test.go
  apiserver/common/secrets/drain_test.go
  apiserver/common/secrets/mocks/commonsecrets_mock.go
  apiserver/common/secrets/mocks/state_mock.go
  apiserver/common/secrets/secrets.go
  apiserver/common/secrets/secrets_test.go
  apiserver/common/secrets/state.go
  apiserver/facades/agent/secretsmanager/mocks/secretsstate.go
  apiserver/facades/agent/secretsmanager/secrets_test.go
  apiserver/facades/agent/secretsmanager/state.go
  apiserver/facades/client/secrets/mocks/secretsstate.go
  apiserver/facades/client/secrets/secrets.go
  apiserver/facades/client/secrets/secrets_test.go
  apiserver/facades/client/secrets/state.go
  apiserver/facades/schema.json
  cmd/juju/secrets/list.go
  cmd/juju/secrets/show.go
  cmd/juju/secrets/show_test.go
  core/secrets/secret.go
  rpc/params/secrets.go
  state/secrets.go
  state/secrets_test.go
  worker/uniter/runner/context/context.go
  worker/uniter/runner/context/context_test.go
  worker/uniter/runner/context/contextfactory.go
  worker/uniter/runner/context/export_test.go
  worker/uniter/runner/context/secrets.go
  worker/uniter/runner/jujuc/context.go
  worker/uniter/runner/jujuc/jujuctesting/secrets.go
  worker/uniter/runner/jujuc/secret-grant.go
  worker/uniter/runner/jujuc/secret-info-get.go
  worker/uniter/runner/jujuc/secret-info-get_test.go
Labels: 3.3

#16513 Resolve old TODO for juju 3 RE charm origins.
  apiserver/facades/client/client/status_test.go
  cmd/juju/status/status_internal_test.go
  state/application.go
  state/application_test.go
  state/charm_test.go
  state/unit_test.go
  worker/uniter/util_test.go
Labels: 3.1
