Repository juju/juju, pull requests merged in 2023-08, with the labels that each got.

#16036 [JUJU-4257] - Grant secret
  .github/discourse-topic-ids.yaml
  api/client/secrets/client.go
  api/client/secrets/client_test.go
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/application_test.go
  apiserver/facades/client/application/export_test.go
  apiserver/facades/client/secrets/mocks/secretsstate.go
  apiserver/facades/client/secrets/package_test.go
  apiserver/facades/client/secrets/register.go
  apiserver/facades/client/secrets/secrets.go
  apiserver/facades/client/secrets/secrets_test.go
  apiserver/facades/client/secrets/state.go
  apiserver/facades/schema.json
  cmd/juju/commands/main.go
  cmd/juju/commands/main_test.go
  cmd/juju/secrets/grantrevoke.go
  cmd/juju/secrets/grantrevoke_test.go
  cmd/juju/secrets/mocks/secretsapi.go
  cmd/juju/secrets/package_test.go
  go.mod
  go.sum
  rpc/params/secrets.go
Labels: feature, go, 3.3

#16057 [JUJU-4403] Fix authentication worker test races
  worker/authenticationworker/worker_test.go
Labels: 4.0

#15999 [JUJU-4099] Add watcher to upgrade that notifies when upgrade can start
  domain/upgrade/service/package_mock_test.go
  domain/upgrade/service/package_test.go
  domain/upgrade/service/service.go
  domain/upgrade/service/service_test.go
  domain/upgrade/service/watcher.go
  domain/upgrade/service/watcher_test.go
Labels: 4.0

#16017 [JUJU-4319] Service factory worker
  apiserver/admin.go
  apiserver/apiserver.go
  apiserver/common/controllerconfig.go
  apiserver/common/controllerconfig_test.go
  apiserver/common/mocks/controllerconfig_mock.go
  apiserver/common/modelstatus_test.go
  apiserver/common/package_test.go
  apiserver/export_test.go
  apiserver/facade/facadetest/context.go
  apiserver/facade/interface.go
  apiserver/facades/client/controller/controller.go
  apiserver/facades/client/controller/controller_test.go
  apiserver/facades/client/controller/destroy_test.go
  apiserver/facades/client/controller/register.go
  apiserver/facades/client/highavailability/highavailability_test.go
  apiserver/facades/client/highavailability/register.go
  apiserver/facades/client/modelmanager/register.go
  apiserver/facades/controller/caasmodelconfigmanager/mocks/context_mock.go
  apiserver/facades/controller/externalcontrollerupdater/register.go
  apiserver/package_test.go
  apiserver/root.go
  apiserver/shared.go
  apiserver/shared_test.go
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/agent/machine/manifolds_test.go
  core/changestream/database_mock_test.go
  core/changestream/eventsource.go
  core/changestream/eventsource_test.go
  core/changestream/package_test.go
  database/testing/runner.go
  domain/servicefactory/controller.go
  domain/servicefactory/model.go
  domain/servicefactory/service.go
  domain/servicefactory/testing/logger.go
  domain/servicefactory/testing/service.go
  juju/testing/apiserver.go
  testing/logger.go
  worker/apiserver/manifold.go
  worker/apiserver/manifold_test.go
  worker/apiserver/worker.go
  worker/apiserver/worker_state_test.go
  worker/apiserver/worker_test.go
  worker/servicefactory/changestream_mock_test.go
  worker/servicefactory/database_mock_test.go
  worker/servicefactory/interface.go
  worker/servicefactory/manifold.go
  worker/servicefactory/manifold_test.go
  worker/servicefactory/package_test.go
  worker/servicefactory/servicefactory_mock_test.go
  worker/servicefactory/worker.go
  worker/servicefactory/worker_test.go
Labels: 4.0

#16065 [JUJU-4416] Remove external controller service apiserver
  apiserver/facade/interface.go
  apiserver/facades/agent/agent/agent_test.go
  apiserver/facades/agent/agent/model_test.go
  apiserver/facades/agent/agent/package_test.go
  apiserver/facades/agent/agent/register.go
  apiserver/facades/agent/caasadmission/register.go
  apiserver/facades/agent/caasagent/register.go
  apiserver/facades/agent/provisioner/container_test.go
  apiserver/facades/agent/provisioner/imagemetadata_test.go
  apiserver/facades/agent/provisioner/provisioner.go
  apiserver/facades/agent/provisioner/provisioner_test.go
  apiserver/facades/agent/provisioner/provisioninginfo_test.go
  apiserver/facades/agent/secretsmanager/register.go
  apiserver/facades/agent/uniter/uniter_test.go
  apiserver/facades/client/application/application.go
  apiserver/facades/controller/caasmodelconfigmanager/register.go
  apiserver/facades/controller/firewaller/firewaller_base_test.go
  apiserver/facades/controller/firewaller/register.go
  apiserver/facades/controller/migrationtarget/domain_mock_test.go
  apiserver/facades/controller/migrationtarget/migrationtarget.go
  apiserver/facades/controller/migrationtarget/migrationtarget_test.go
  apiserver/facades/controller/migrationtarget/package_test.go
  apiserver/facades/controller/migrationtarget/register.go
  apiserver/facades/controller/remoterelations/register.go
Labels: 4.0

#16059 Fix show cloud yaml support
  cmd/juju/cloud/show.go
  cmd/juju/cloud/show_test.go
Labels: 3.1

#16081 [JUJU-4166] wait-for documentation
  cmd/juju/waitfor/application.go
  cmd/juju/waitfor/machine.go
  cmd/juju/waitfor/model.go
  cmd/juju/waitfor/unit.go
  cmd/juju/waitfor/waitfor.go
  cmd/plugins/juju-metadata/metadataplugin_test.go
  go.mod
  go.sum
Labels: 3.1

#16097 [JUJU-4454] Add context.Context in agent/credentialvalidator facade
  apiserver/common/credentialcommon/cloudcredential.go
  apiserver/common/credentialcommon/cloudcredential_test.go
  apiserver/facades/agent/credentialvalidator/credentialvalidator.go
  apiserver/facades/agent/credentialvalidator/credentialvalidator_test.go
  apiserver/facades/client/credentialmanager/client.go
  apiserver/facades/client/credentialmanager/client_test.go
Labels: 4.0

#16099 [JUJU-4456] Add context.Context in agent/(d-l)* facades
  apiserver/facades/agent/deployer/deployer.go
  apiserver/facades/agent/deployer/deployer_test.go
  apiserver/facades/agent/diskmanager/diskmanager.go
  apiserver/facades/agent/diskmanager/diskmanager_test.go
  apiserver/facades/agent/fanconfigurer/fanconfigurer.go
  apiserver/facades/agent/fanconfigurer/fanconfigurer_test.go
  apiserver/facades/agent/hostkeyreporter/facade.go
  apiserver/facades/agent/hostkeyreporter/facade_test.go
  apiserver/facades/agent/instancemutater/instancemutater.go
  apiserver/facades/agent/instancemutater/instancemutater_test.go
  apiserver/facades/agent/keyupdater/authorisedkeys.go
  apiserver/facades/agent/keyupdater/authorisedkeys_test.go
  apiserver/facades/agent/leadership/interface.go
  apiserver/facades/agent/leadership/leadership.go
  apiserver/facades/agent/leadership/leadership_test.go
  apiserver/facades/agent/logger/logger.go
  apiserver/facades/agent/logger/logger_test.go
Labels: 4.0

#16086 [JUJU-4314] Inject ctrl config modelmanager
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/agent/machine/manifolds_test.go
  worker/modelworkermanager/manifold.go
  worker/modelworkermanager/manifold_test.go
  worker/modelworkermanager/modelworkermanager.go
  worker/modelworkermanager/modelworkermanager_test.go
  worker/modelworkermanager/shim.go
Labels: 4.0

#16092 [JUJU-4452] Add context.Context in agent/agent facade
  apiserver/facades/agent/agent/agent.go
  apiserver/facades/agent/agent/agent_test.go
Labels: 4.0

#15991 [JUJU-4321] Remove apiserver restart pubsub message
  apiserver/apiserver.go
  apiserver/apiserver_test.go
  pubsub/apiserver/messages.go
Labels: 4.0

#16103 [JUJU-4471] Add context.Context in agent/(r-u)* facades
  apiserver/common/tools.go
  apiserver/common/tools_test.go
  apiserver/facades/agent/reboot/reboot.go
  apiserver/facades/agent/reboot/reboot_test.go
  apiserver/facades/agent/resourceshookcontext/unitfacade.go
  apiserver/facades/agent/resourceshookcontext/unitfacade_test.go
  apiserver/facades/agent/retrystrategy/retrystrategy.go
  apiserver/facades/agent/retrystrategy/retrystrategy_test.go
  apiserver/facades/agent/secretsdrain/secrets.go
  apiserver/facades/agent/secretsdrain/secrets_test.go
  apiserver/facades/agent/secretsmanager/secrets.go
  apiserver/facades/agent/secretsmanager/secrets_test.go
  apiserver/facades/agent/storageprovisioner/storageprovisioner.go
  apiserver/facades/agent/storageprovisioner/storageprovisioner_test.go
  apiserver/facades/agent/unitassigner/unitassigner.go
  apiserver/facades/agent/unitassigner/unitassigner_test.go
  apiserver/facades/agent/uniter/goal-state_test.go
  apiserver/facades/agent/uniter/uniter.go
  apiserver/facades/agent/uniter/uniter_test.go
  apiserver/facades/agent/upgrader/unitupgrader.go
  apiserver/facades/agent/upgrader/unitupgrader_test.go
  apiserver/facades/agent/upgrader/upgrader.go
  apiserver/facades/agent/upgrader/upgrader_test.go
  apiserver/facades/agent/upgradeseries/upgradeseries.go
  apiserver/facades/agent/upgradeseries/upgradeseries_test.go
  apiserver/facades/agent/upgradesteps/upgradesteps.go
  apiserver/facades/agent/upgradesteps/upgradesteps_test.go
Labels: 4.0

#16102 [JUJU-4457] Add context.Context in agent/(m-p)* facades
  apiserver/facades/agent/machine/machiner.go
  apiserver/facades/agent/machine/machiner_test.go
  apiserver/facades/agent/machineactions/machineactions.go
  apiserver/facades/agent/machineactions/machineactions_test.go
  apiserver/facades/agent/meterstatus/meterstatus.go
  apiserver/facades/agent/meterstatus/meterstatus_test.go
  apiserver/facades/agent/meterstatus/testing/tests.go
  apiserver/facades/agent/metricsadder/metricsadder.go
  apiserver/facades/agent/metricsadder/metricsadder_test.go
  apiserver/facades/agent/metricsender/metricsender.go
  apiserver/facades/agent/metricsender/nopsender.go
  apiserver/facades/agent/metricsender/sender.go
  apiserver/facades/agent/metricsender/testing/mocksender.go
  apiserver/facades/agent/migrationflag/facade.go
  apiserver/facades/agent/migrationflag/facade_test.go
  apiserver/facades/agent/migrationminion/migrationminion.go
  apiserver/facades/agent/migrationminion/migrationminion_test.go
  apiserver/facades/agent/payloadshookcontext/unitfacade.go
  apiserver/facades/agent/payloadshookcontext/unitfacade_test.go
  apiserver/facades/agent/provisioner/container_test.go
  apiserver/facades/agent/provisioner/provisioner.go
  apiserver/facades/agent/provisioner/provisioner_test.go
  apiserver/facades/agent/proxyupdater/proxyupdater.go
  apiserver/facades/agent/proxyupdater/proxyupdater_test.go
  apiserver/facades/agent/uniter/uniter_test.go
Labels: 4.0

#16108 [JUJU-4480] Add context.Context in client/(r-u)* facades
  apiserver/facades/client/resources/facade.go
  apiserver/facades/client/resources/server_addpending_test.go
  apiserver/facades/client/resources/server_listresources_test.go
  apiserver/facades/client/secretbackends/secrets.go
  apiserver/facades/client/secretbackends/secrets_test.go
  apiserver/facades/client/secrets/secrets.go
  apiserver/facades/client/secrets/secrets_test.go
  apiserver/facades/client/spaces/spaces.go
  apiserver/facades/client/spaces/spaces_test.go
  apiserver/facades/client/sshclient/facade.go
  apiserver/facades/client/sshclient/facade_test.go
  apiserver/facades/client/storage/filesystemlist_test.go
  apiserver/facades/client/storage/poolcreate_test.go
  apiserver/facades/client/storage/poollist_test.go
  apiserver/facades/client/storage/poolremove_test.go
  apiserver/facades/client/storage/poolupdate_test.go
  apiserver/facades/client/storage/storage.go
  apiserver/facades/client/storage/storage_test.go
  apiserver/facades/client/storage/storageadd_test.go
  apiserver/facades/client/storage/volumelist_test.go
  apiserver/facades/client/subnets/subnets.go
  apiserver/facades/client/subnets/subnets_test.go
  apiserver/facades/client/usermanager/usermanager.go
  apiserver/facades/client/usermanager/usermanager_test.go
Labels: 4.0

#16107 [JUJU-4479] Add context.Context in client/(i-p)* facades
  apiserver/facades/client/imagemetadatamanager/metadata.go
  apiserver/facades/client/imagemetadatamanager/metadata_test.go
  apiserver/facades/client/keymanager/keymanager.go
  apiserver/facades/client/keymanager/keymanager_test.go
  apiserver/facades/client/machinemanager/machinemanager.go
  apiserver/facades/client/machinemanager/machinemanager_test.go
  apiserver/facades/client/metricsdebug/metricsdebug.go
  apiserver/facades/client/metricsdebug/metricsdebug_test.go
  apiserver/facades/client/modelconfig/modelconfig.go
  apiserver/facades/client/modelconfig/modelconfig_test.go
  apiserver/facades/client/modelgeneration/modelgeneration.go
  apiserver/facades/client/modelgeneration/modelgeneration_test.go
  apiserver/facades/client/modelmanager/listmodelsummaries_test.go
  apiserver/facades/client/modelmanager/modelinfo_test.go
  apiserver/facades/client/modelmanager/modelmanager.go
  apiserver/facades/client/modelmanager/modelmanager_test.go
  apiserver/facades/client/modelupgrader/upgrader.go
  apiserver/facades/client/modelupgrader/upgrader_test.go
  apiserver/facades/client/payloads/facade.go
  apiserver/facades/client/payloads/facade_test.go
  apiserver/facades/client/pinger/facade.go
Labels: 4.0

#16096 [JUJU-4455] Inject ctrl config certupdater
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/agent/machine/manifolds_test.go
  core/watcher/notify.go
  core/watcher/notify_test.go
  worker/apiaddressupdater/apiaddressupdater.go
  worker/authenticationworker/worker.go
  worker/certupdater/certupdater.go
  worker/certupdater/certupdater_test.go
  worker/certupdater/manifold.go
  worker/certupdater/manifold_test.go
  worker/logger/logger.go
  worker/machiner/machiner.go
  worker/machiner/machiner_test.go
  worker/machineundertaker/undertaker.go
  worker/meterstatus/connected.go
  worker/meterstatus/connected_test.go
  worker/proxyupdater/proxyupdater.go
  worker/reboot/reboot.go
  worker/reboot/reboot_test.go
  worker/retrystrategy/worker.go
  worker/stateconverter/converter.go
  worker/stateconverter/converter_test.go
Labels: 4.0

#16089 [JUJU-4313] Inject controller config to http server args
  apiserver/export_test.go
  apiserver/server_test.go
  apiserver/stateauthenticator/auth.go
  apiserver/stateauthenticator/authenticator_test.go
  apiserver/stateauthenticator/context.go
  apiserver/stateauthenticator/context_test.go
  apiserver/stateauthenticator/controller_config_mock_test.go
  apiserver/stateauthenticator/export_test.go
  apiserver/stateauthenticator/package_test.go
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/agent/machine/manifolds_test.go
  domain/controllerconfig/service/service.go
  domain/controllerconfig/service/service_test.go
  domain/controllerconfig/state/state.go
  juju/testing/apiserver.go
  worker/httpserverargs/authenticator.go
  worker/httpserverargs/controller_config_mock_test.go
  worker/httpserverargs/manifold.go
  worker/httpserverargs/manifold_test.go
  worker/httpserverargs/package_test.go
  worker/httpserverargs/worker.go
  worker/httpserverargs/worker_test.go
Labels: 4.0

#16117 [JUJU-4483] Add context.Context in controller/(a-c)* facades
  apiserver/facades/client/client/status_test.go
  apiserver/facades/controller/actionpruner/pruner.go
  apiserver/facades/controller/actionpruner/pruner_test.go
  apiserver/facades/controller/agenttools/agenttools.go
  apiserver/facades/controller/applicationscaler/facade.go
  apiserver/facades/controller/applicationscaler/facade_test.go
  apiserver/facades/controller/caasapplicationprovisioner/provisioner.go
  apiserver/facades/controller/caasapplicationprovisioner/provisioner_test.go
  apiserver/facades/controller/caasfirewaller/firewaller.go
  apiserver/facades/controller/caasfirewaller/firewaller_test.go
  apiserver/facades/controller/caasmodelconfigmanager/facade.go
  apiserver/facades/controller/caasmodeloperator/operator.go
  apiserver/facades/controller/caasmodeloperator/operator_test.go
  apiserver/facades/controller/caasoperatorupgrader/upgrader.go
  apiserver/facades/controller/caasoperatorupgrader/upgrader_test.go
  apiserver/facades/controller/caasunitprovisioner/provisioner.go
  apiserver/facades/controller/caasunitprovisioner/provisioner_test.go
  apiserver/facades/controller/charmdownloader/charmdownloader.go
  apiserver/facades/controller/charmdownloader/charmdownloader_test.go
  apiserver/facades/controller/charmrevisionupdater/updater.go
  apiserver/facades/controller/charmrevisionupdater/updater_test.go
  apiserver/facades/controller/cleaner/cleaner.go
  apiserver/facades/controller/cleaner/cleaner_test.go
  apiserver/facades/controller/crosscontroller/crosscontroller.go
  apiserver/facades/controller/crosscontroller/crosscontroller_test.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations_test.go
  apiserver/facades/controller/crossmodelsecrets/crossmodelsecrets.go
  apiserver/facades/controller/crossmodelsecrets/crossmodelsecrets_test.go
Labels: 4.0

#16119 [JUJU-4485] Add context.Context in controller/(r-u)* facades
  apiserver/facades/controller/remoterelations/remoterelations.go
  apiserver/facades/controller/remoterelations/remoterelations_test.go
  apiserver/facades/controller/secretbackendmanager/backends.go
  apiserver/facades/controller/secretbackendmanager/backends_test.go
  apiserver/facades/controller/singular/singular.go
  apiserver/facades/controller/singular/singular_test.go
  apiserver/facades/controller/statushistory/api.go
  apiserver/facades/controller/statushistory/pruner_test.go
  apiserver/facades/controller/undertaker/undertaker.go
  apiserver/facades/controller/undertaker/undertaker_test.go
Labels: 4.0

#16118 [JUJU-4484] Add context.Context in controller/(e-m)* facades
  apiserver/facades/controller/environupgrader/upgrader.go
  apiserver/facades/controller/environupgrader/upgrader_test.go
  apiserver/facades/controller/externalcontrollerupdater/externalcontrollerupdater.go
  apiserver/facades/controller/externalcontrollerupdater/externalcontrollerupdater_test.go
  apiserver/facades/controller/firewaller/firewaller.go
  apiserver/facades/controller/firewaller/firewaller_base_test.go
  apiserver/facades/controller/firewaller/firewaller_test.go
  apiserver/facades/controller/firewaller/firewaller_unit_test.go
  apiserver/facades/controller/imagemetadata/metadata.go
  apiserver/facades/controller/instancepoller/instancepoller.go
  apiserver/facades/controller/instancepoller/instancepoller_test.go
  apiserver/facades/controller/logfwd/lastsent.go
  apiserver/facades/controller/logfwd/lastsent_test.go
  apiserver/facades/controller/machineundertaker/undertaker.go
  apiserver/facades/controller/machineundertaker/undertaker_test.go
  apiserver/facades/controller/metricsmanager/metricsmanager.go
  apiserver/facades/controller/metricsmanager/metricsmanager_test.go
  apiserver/facades/controller/migrationmaster/facade.go
  apiserver/facades/controller/migrationmaster/facade_test.go
  apiserver/facades/controller/migrationtarget/migrationtarget.go
  apiserver/facades/controller/migrationtarget/migrationtarget_test.go
Labels: 4.0

#16120 Add open telemetry agent config
  agent/agent.go
  agent/agent_test.go
  agent/format-2.0.go
  agent/format-2.0_whitebox_test.go
  cloudconfig/instancecfg/instancecfg.go
  cloudconfig/podcfg/podcfg.go
  cmd/containeragent/initialize/config.go
  cmd/jujud/agent/agenttest/agent.go
  cmd/jujud/agent/bootstrap.go
  controller/config.go
  controller/config_test.go
  controller/configschema.go
  state/controller_test.go
  worker/agentconfigupdater/manifold.go
  worker/agentconfigupdater/manifold_test.go
  worker/agentconfigupdater/worker.go
  worker/agentconfigupdater/worker_test.go
  worker/containerbroker/mocks/agent_mock.go
  worker/instancemutater/mocks/agent_mock.go
  worker/stateconverter/mocks/agent_mock.go
Labels: 4.0

#16125 Make controller-config a dependency in state
  apiserver/facades/agent/deployer/deployer_test.go
  apiserver/facades/agent/machine/machiner.go
  apiserver/facades/agent/uniter/networkinfo_test.go
  apiserver/facades/agent/uniter/uniter_test.go
  apiserver/facades/client/highavailability/highavailability_test.go
  apiserver/facades/controller/instancepoller/instancepoller.go
  apiserver/facades/controller/instancepoller/instancepoller_test.go
  apiserver/facades/controller/instancepoller/mock_test.go
  apiserver/facades/controller/instancepoller/state.go
  cmd/jujud/agent/util_test.go
  juju/testing/utils.go
  state/allwatcher_internal_test.go
  state/controller_test.go
  state/machine.go
  state/machine_test.go
  state/relationunit_test.go
  state/state_test.go
  state/unit_test.go
  testing/factory/factory.go
Labels: 4.0

#16105 [JUJU-4334] Inject ctrl config upgrade steps
  apiserver/facades/agent/upgradesteps/facade_mock_test.go
  apiserver/facades/agent/upgradesteps/interface.go
  apiserver/facades/agent/upgradesteps/package_test.go
  apiserver/facades/agent/upgradesteps/register.go
  apiserver/facades/agent/upgradesteps/shim.go
  apiserver/facades/agent/upgradesteps/state_mock_test.go
  apiserver/facades/agent/upgradesteps/upgradesteps.go
  apiserver/facades/agent/upgradesteps/upgradesteps_mock_test.go
  apiserver/facades/agent/upgradesteps/upgradesteps_test.go
Labels: 4.0

#16137 [JUJU-4323] Inject controllerConfig service in agent/agent facade
  apiserver/facades/agent/agent/agent.go
  apiserver/facades/agent/agent/register.go
Labels: 4.0

#16139 [JUJU-4326] Inject controllerConfigService in agent/deployer facade
  apiserver/facades/agent/deployer/deployer.go
  apiserver/facades/agent/deployer/deployer_test.go
  apiserver/facades/agent/deployer/mocks/domain_mock.go
  apiserver/facades/agent/deployer/package_test.go
  apiserver/facades/agent/deployer/register.go
Labels: 4.0

#16121 [JUJU-3763] Add metrics to the changestream and dbaccessor packages
  cmd/jujud/agent/machine/manifolds.go
  worker/changestream/eventmultiplexer/benchmarks_test.go
  worker/changestream/eventmultiplexer/eventmultiplexer.go
  worker/changestream/eventmultiplexer/eventmultiplexer_test.go
  worker/changestream/eventmultiplexer/metrics_mock_test.go
  worker/changestream/eventmultiplexer/package_test.go
  worker/changestream/manifold.go
  worker/changestream/manifold_test.go
  worker/changestream/metrics.go
  worker/changestream/metrics_mock_test.go
  worker/changestream/metrics_test.go
  worker/changestream/package_test.go
  worker/changestream/stream/metrics_mock_test.go
  worker/changestream/stream/package_test.go
  worker/changestream/stream/stream.go
  worker/changestream/stream/stream_test.go
  worker/changestream/watchabledb.go
  worker/changestream/worker.go
  worker/changestream/worker_test.go
  worker/dbaccessor/metrics.go
  worker/dbaccessor/metrics_test.go
  worker/dbaccessor/tracker.go
Labels: 4.0

#16130 Pass in controller config for migration
  apiserver/facades/client/backups/backups.go
  apiserver/facades/client/backups/backups_test.go
  apiserver/facades/client/backups/create.go
  apiserver/facades/client/backups/create_test.go
  apiserver/facades/client/backups/domain_mock_test.go
  apiserver/facades/client/backups/package_test.go
  apiserver/facades/client/backups/register.go
  apiserver/facades/controller/migrationtarget/domain_mock_test.go
  apiserver/facades/controller/migrationtarget/migrationtarget.go
  apiserver/facades/controller/migrationtarget/migrationtarget_test.go
  apiserver/facades/controller/migrationtarget/package_test.go
  apiserver/facades/controller/migrationtarget/register.go
  migration/migration.go
  migration/migration_mock_test.go
  migration/migration_test.go
  migration/package_test.go
  state/backups/metadata.go
  state/initialize_test.go
  state/migration_import.go
  state/migration_import_test.go
  state/model.go
Labels: 4.0

#16157 [JUJU-4328] Inject controllerConfigGetter in agent/meterstatus facade
  apiserver/common/mocks/domain_mock.go
  apiserver/common/mocks/unitstate.go
  apiserver/common/package_test.go
  apiserver/common/tools.go
  apiserver/common/tools_test.go
  apiserver/common/unitstate.go
  apiserver/common/unitstate_test.go
  apiserver/facades/agent/meterstatus/domain_mock_test.go
  apiserver/facades/agent/meterstatus/meterstatus.go
  apiserver/facades/agent/meterstatus/meterstatus_mock_test.go
  apiserver/facades/agent/meterstatus/meterstatus_test.go
  apiserver/facades/agent/meterstatus/package_test.go
  apiserver/facades/agent/meterstatus/register.go
  apiserver/facades/agent/provisioner/provisioner.go
  apiserver/facades/agent/uniter/register.go
  apiserver/facades/agent/upgrader/domain_mock_test.go
  apiserver/facades/agent/upgrader/package_test.go
  apiserver/facades/agent/upgrader/register.go
  apiserver/facades/agent/upgrader/upgrader.go
  apiserver/facades/agent/upgrader/upgrader_test.go
  apiserver/facades/client/client/client.go
  apiserver/facades/client/machinemanager/instance_information_test.go
  apiserver/facades/client/machinemanager/instanceconfig.go
  apiserver/facades/client/machinemanager/instanceconfig_test.go
  apiserver/facades/client/machinemanager/machinemanager.go
  apiserver/facades/client/machinemanager/machinemanager_test.go
  apiserver/facades/client/machinemanager/mocks/domain_mock.go
  apiserver/facades/client/machinemanager/package_test.go
  apiserver/facades/client/modelmanager/mocks/domain_mock.go
  apiserver/facades/client/modelmanager/modelmanager_test.go
  apiserver/facades/client/modelmanager/package_test.go
  apiserver/facades/client/modelmanager/register.go
  apiserver/facades/client/modelupgrader/register.go
Labels: 4.0
