Repository juju/juju, pull requests merged in 2023-01, with the labels that each got.

#15009 [JUJU-2353] Allow repl access for all substrates
  scripts/dqlite/Makefile
Labels: 3.1

#15010 [JUJU-2355] CI: Speed up go generate
  .github/workflows/gen.yml
Labels: 3.1

#15014 Fix panic when trying to match storage class.
  caas/kubernetes/provider/metadata.go
  caas/kubernetes/provider/metadata_test.go
Labels: 2.9

#15016 Force controller config changes to be coerced to schema defined types.
  cmd/juju/controller/config.go
  cmd/juju/controller/config_test.go
  state/controller.go
Labels: 2.9

#15017 [JUJU-2377] Static analysis output is broken subtly.
  tests/includes/run.sh
Labels: 3.0

#15018 [JUJU-2390] Error message with no current model selected
  cmd/juju/commands/switch.go
  jujuclient/file.go
  worker/statushistorypruner/worker_test.go
Labels: 3.0

#14996 [JUJU-2339] Remove macaroons for no cs on juju
  api/client/charms/client.go
  api/client/charms/client_test.go
  api/client/resources/client.go
  api/facadeversions.go
  apiserver/facades/client/charms/client.go
  apiserver/facades/client/charms/client_test.go
  apiserver/facades/client/charms/export_test.go
  apiserver/facades/client/charms/interfaces/downloader.go
  apiserver/facades/client/charms/mocks/repository.go
  apiserver/facades/client/charms/mocks/state_mock.go
  apiserver/facades/client/charms/register.go
  apiserver/facades/client/charms/services/storage.go
  apiserver/facades/client/charms/services/storage_test.go
  apiserver/facades/controller/charmdownloader/charmdownloader.go
  apiserver/facades/controller/charmdownloader/charmdownloader_test.go
  apiserver/facades/controller/charmdownloader/interfaces.go
  apiserver/facades/controller/charmdownloader/mocks/mocks.go
  apiserver/facades/schema.json
  cmd/juju/application/deploy.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/bundle.go
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/bundlehandler_test.go
  cmd/juju/application/deployer/charm.go
  cmd/juju/application/deployer/charm_test.go
  cmd/juju/application/deployer/deployer_test.go
  cmd/juju/application/deployer/interface.go
  cmd/juju/application/deployer/mocks/deploy_mock.go
  cmd/juju/application/deployer/resource.go
  cmd/juju/application/mocks/deployer_mock.go
  cmd/juju/application/refresh.go
  cmd/juju/application/refresh_test.go
  cmd/juju/application/refresher/interface.go
  cmd/juju/application/refresher/refresher.go
  cmd/juju/application/refresher/refresher_test.go
  cmd/juju/application/refresher/store_mock_test.go
  cmd/juju/application/store/charmadapter.go
  cmd/juju/application/store/charmadapter_test.go
  cmd/juju/application/store/interface.go
  cmd/juju/application/store/mocks/store_mock.go
  cmd/juju/application/store/store.go
  cmd/juju/application/store/store_test.go
  cmd/juju/resource/deploy.go
  cmd/juju/resource/deploy_test.go
  cmd/jujud/agent/bootstrap_test.go
  cmd/jujud/agent/controllercharm.go
  core/charm/downloader/downloader.go
  core/charm/downloader/downloader_test.go
  core/charm/downloader/export_test.go
  core/charm/downloader/mocks/downloader_mocks.go
  core/charm/repository.go
  core/charm/repository/charmhub.go
  core/charm/repository/charmhub_test.go
Labels: feature, 3.1

#15022 [JUJU-2311] no charmstore in state
  apiserver/facades/controller/charmdownloader/interfaces.go
  apiserver/facades/controller/charmdownloader/mocks/mocks.go
  state/application.go
  state/application_test.go
  state/charm.go
  state/charm_test.go
  state/export_test.go
  state/metrics_test.go
  state/model_test.go
  state/unit_test.go
  state/upgrades_test.go
  state/watcher_profilecharm_test.go
Labels: feature, 3.1

#15023 [JUJU-2233] remove charmstore pkg
  api/apiclient.go
  api/controller/crossmodelrelations/macarooncache.go
  apiserver/authentication/user.go
  apiserver/common/crossmodel/auth.go
  apiserver/facades/controller/crossmodelrelations/mock_test.go
  apiserver/localofferauth.go
  apiserver/registration.go
  apiserver/stateauthenticator/context.go
  charmstore/charmid.go
  charmstore/client.go
  charmstore/client_test.go
  charmstore/info.go
  charmstore/info_test.go
  charmstore/jar.go
  charmstore/jar_test.go
  charmstore/latest.go
  charmstore/latest_test.go
  charmstore/package_test.go
  charmstore/stub_test.go
  cmd/containeragent/initialize/package_test.go
  core/macaroon/jar.go
Labels: feature, 3.1

#14988 [JUJU-2309] Add confirmation prompt to remove-unit cmd
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/application_unit_test.go
  cmd/juju/application/removeapplication.go
  cmd/juju/application/removeapplication_test.go
  cmd/juju/application/removeunit.go
  cmd/juju/application/removeunit_test.go
  cmd/juju/machine/remove.go
  cmd/juju/machine/remove_test.go
Labels: 3.0

#15035 [JUJU-2413] Remove typed lease error
  core/lease/errors.go
  worker/lease/manager.go
Labels: feature, 3.1

#14975 [JUJU-1852] - Feature/sidecar open port
  api/agent/uniter/uniter.go
  api/agent/uniter/uniter_test.go
  api/controller/caasfirewaller/client.go
  api/controller/caasfirewaller/client_test.go
  apiserver/facades/agent/uniter/uniter.go
  apiserver/facades/agent/uniter/uniter_test.go
  apiserver/facades/controller/caasfirewaller/firewaller.go
  apiserver/facades/controller/caasfirewaller/firewaller_test.go
  apiserver/facades/controller/caasfirewaller/mock_test.go
  apiserver/facades/controller/caasfirewaller/state.go
  apiserver/facades/schema.json
  caas/kubernetes/provider/application/application.go
  caas/kubernetes/provider/application/application_test.go
  caas/kubernetes/provider/resources/applier.go
  caas/kubernetes/provider/resources/service.go
  rpc/params/network.go
  state/application.go
  state/application_ports.go
  state/application_test.go
  state/machine_ports.go
  state/mocks/application_ports_mock.go
  state/package_test.go
  worker/caasfirewallersidecar/applicationworker.go
  worker/caasfirewallersidecar/applicationworker_test.go
  worker/caasfirewallersidecar/broker.go
  worker/caasfirewallersidecar/client.go
  worker/caasfirewallersidecar/mocks/client_mock.go
  worker/caasfirewallersidecar/package_test.go
  worker/uniter/runner/context/context.go
  worker/uniter/runner/context/context_test.go
  worker/uniter/runner/context/contextfactory.go
  worker/uniter/runner/context/contextfactory_test.go
  worker/uniter/runner/context/export_test.go
  worker/uniter/runner/context/ports.go
  worker/uniter/runner/context/ports_test.go
  worker/uniter/runner/jujuc/ports.go
  worker/uniter/runner/jujuc/ports_test.go
Labels: feature, 3.0

#15036 [JUJU-2416] Remove batch fsm controller config
  agent/agent.go
  agent/agent_test.go
  agent/format-2.0.go
  cmd/containeragent/initialize/config.go
  cmd/jujud/agent/bootstrap.go
  controller/config.go
  controller/config_test.go
  state/controller_test.go
  worker/agentconfigupdater/manifold.go
  worker/agentconfigupdater/manifold_test.go
  worker/agentconfigupdater/worker.go
  worker/agentconfigupdater/worker_test.go
  worker/containerbroker/mocks/agent_mock.go
  worker/instancemutater/mocks/agent_mock.go
  worker/stateconverter/mocks/agent_mock.go
  worker/upgradedatabase/mocks/agent.go
Labels: feature

#15033 [JUJU-2324] Use confirmation abstraction for remove-unit
  cmd/juju/application/removeunit.go
  cmd/juju/application/removeunit_test.go
Labels: failed to land, 3.1

#15037 [JUJU-2417] Standardise jujud building
  Makefile
  scripts/verify.bash
Labels: feature, 3.1

#15026 [JUJU-2343] Thread base through info and download
  cmd/juju/charmhub/charmhub.go
  cmd/juju/charmhub/convert.go
  cmd/juju/charmhub/convert_test.go
  cmd/juju/charmhub/download.go
  cmd/juju/charmhub/download_test.go
  cmd/juju/charmhub/findwriter.go
  cmd/juju/charmhub/findwriter_test.go
  cmd/juju/charmhub/info.go
  cmd/juju/charmhub/infowriter.go
  cmd/juju/charmhub/infowriter_test.go
  tests/suites/charmhub/download.sh
Labels: feature, 3.1

#15040 [JUJU-2396] Reduce dependence on charmrepo
  api/client/charms/client_test.go
  apiserver/facades/client/charms/client_test.go
  charmhub/download_test.go
  state/export_test.go
  testcharms/charm.go
  testcharms/repo/repo.go
Labels: 3.1

#15013 [JUJU-2230] Remove charmstore charm support from client
  cmd/juju/application/bundle_test.go
  cmd/juju/application/deploy.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/bundlehandler_test.go
  cmd/juju/application/deployer/deployer.go
  cmd/juju/application/deployer/deployer_test.go
  cmd/juju/application/deployer/interface.go
  cmd/juju/application/deployer/lxdprofilestep.go
  cmd/juju/application/deployer/mocks/deploy_mock.go
  cmd/juju/application/deployer/mocks/store_mock.go
  cmd/juju/application/deployer/package_test.go
  cmd/juju/application/deployer/register.go
  cmd/juju/application/deployer/register_test.go
  cmd/juju/application/deployer/steps.go
  cmd/juju/application/diffbundle.go
  cmd/juju/application/export_test.go
  cmd/juju/application/refresh.go
  cmd/juju/application/refresh_resources_test.go
  cmd/juju/application/refresh_test.go
  cmd/juju/application/refresher/package_test.go
  cmd/juju/application/refresher/refresher.go
  cmd/juju/application/refresher/refresher_test.go
  cmd/juju/application/refresher/store_mock_test.go
  cmd/juju/application/store/charmadapter.go
  cmd/juju/application/store/charmadapter_test.go
  cmd/juju/application/store/interface.go
  cmd/juju/application/store/mocks/store_mock.go
  cmd/juju/application/store/package_test.go
  cmd/juju/application/store/store_test.go
  cmd/juju/application/utils/origin.go
  testcharms/charm-repo/bundle/apache2-with-offers-legacy/bundle.yaml
  testcharms/charm-repo/bundle/aws-integrator-trust-conf-param/bundle.yaml
  testcharms/charm-repo/bundle/aws-integrator-trust-multi/bundle.yaml
  testcharms/charm-repo/bundle/aws-integrator-trust-single/bundle.yaml
  testcharms/charm-repo/bundle/basic/bundle.yaml
  testcharms/charm-repo/bundle/wordpress-with-saas/bundle.yaml
Labels: feature, failed to land, 3.1

#15042 [JUJU-2419] Expect kvm-provisioner worker to run in machine manifolds
  cmd/jujud/agent/agenttest/engine.go
  cmd/jujud/agent/engine_test.go
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/agent/machine_test.go
Labels: failed to land, 3.0

#15004 [JUJU-2351] Bootstrap to LXD VM
  apiserver/common/machine.go
  apiserver/facades/schema.json
  container/lxd/container.go
  container/lxd/container_test.go
  container/lxd/image.go
  container/lxd/image_test.go
  container/lxd/manager.go
  container/lxd/manager_test.go
  core/instance/hardwarecharacteristics.go
  core/instance/hardwarecharacteristics_test.go
  core/instance/virttype.go
  core/instance/virttype_test.go
  go.mod
  go.sum
  provider/common/bootstrap.go
  provider/common/bootstrap_test.go
  provider/lxd/environ_broker.go
  provider/lxd/environ_broker_test.go
  provider/lxd/environ_policy.go
  provider/lxd/environ_policy_test.go
  provider/lxd/package_mock_test.go
  provider/lxd/server.go
  provider/lxd/testing_test.go
  rpc/params/model.go
  state/addmachine.go
  state/machine.go
  state/migration_export.go
  state/migration_import.go
  state/migration_internal_test.go
  state/unit.go
  upgrades/upgradevalidation/mocks/lxd_mock.go
Labels: feature, 3.1

#15032 [JUJU-2117] Thread base through image-metadata
  api/client/imagemetadatamanager/client.go
  api/client/imagemetadatamanager/client_test.go
  cmd/juju/commands/bootstrap_test.go
  cmd/plugins/juju-metadata/addimage.go
  cmd/plugins/juju-metadata/addimage_test.go
  cmd/plugins/juju-metadata/deleteimage.go
  cmd/plugins/juju-metadata/imagemetadata.go
  cmd/plugins/juju-metadata/imagemetadata_test.go
  cmd/plugins/juju-metadata/listimages.go
  cmd/plugins/juju-metadata/listimages_test.go
  cmd/plugins/juju-metadata/validateagentsmetadata.go
  cmd/plugins/juju-metadata/validateimagemetadata.go
  cmd/plugins/juju-metadata/validateimagemetadata_test.go
  environs/bootstrap/bootstrap_test.go
  environs/imagemetadata/generate.go
  environs/imagemetadata/generate_test.go
  environs/imagemetadata/validation_test.go
  environs/simplestreams/simplestreams.go
  environs/simplestreams/simplestreams_test.go
Labels: feature, 3.1

#15039 [JUJU-2313] Remove charmstore-url model config
  controller/config.go
  controller/config_test.go
  state/controller_test.go
Labels: feature, 3.1

#15038 [JUJU-2410] Remove duplicated output error in list model when not connected to a controller
  cmd/juju/controller/listmodels.go
  cmd/juju/controller/listmodels_test.go
Labels: bug, 2.9

#15048 [JUJU-2431] Install dependencies for github runner
  .github/golangci-lint.config.yaml
  .github/workflows/static-analysis.yml
  Makefile
  apiserver/facades/client/charms/client_test.go
  cmd/jujud/agent/machine_test.go
  database/option_test.go
  go.mod
  go.sum
  tests/suites/static_analysis/lint_go.sh
  worker/lease/store.go
  worker/leaseexpiry/worker_test.go
Labels: feature, 3.1

#15043 [JUJU-2422] Allow overriding arch machine
  scripts/dqlite/Makefile
Labels: feature, 3.1

#15025 [JUJU-2394] Preliminary panic fix for no primary NIC VLAN
  network/containerizer/bridgepolicy.go
  network/containerizer/bridgepolicy_integration_test.go
  network/containerizer/linklayerdevicesforspaces_test.go
  provider/maas/devices.go
  provider/maas/maas2_environ_whitebox_test.go
Labels: bug, 2.9

#14848 [JUJU-2222] Support multi-homing on OpenStack
  provider/openstack/config.go
  provider/openstack/config_test.go
  provider/openstack/export_test.go
  provider/openstack/local_test.go
  provider/openstack/network_mock_test.go
  provider/openstack/networking.go
  provider/openstack/networking_interfaces.go
  provider/openstack/networking_test.go
  provider/openstack/provider.go
  provider/openstack/provider_test.go
Labels: 3.1

#15045 [JUJU-2229] No charmstore support in bundle code on the client
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/bundle.go
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/bundlehandler_test.go
  cmd/juju/application/deployer/charm.go
  cmd/juju/application/deployer/deployer_test.go
  cmd/juju/application/diffbundle.go
  cmd/juju/application/diffbundle_test.go
  cmd/juju/application/store/charmadapter_test.go
  cmd/juju/application/store/interface.go
  cmd/juju/application/store/store.go
Labels: feature, 3.1

#14977 [JUJU-2314] Adds info about apps in destroy warning messages
  api/base/types.go
  api/common/modelstatus.go
  apiserver/common/modelmanagerinterface.go
  apiserver/common/modelstatus.go
  apiserver/common/modelstatus_test.go
  apiserver/facades/schema.json
  cmd/juju/controller/destroy.go
  cmd/juju/controller/destroy_test.go
  cmd/juju/controller/export_test.go
  cmd/juju/controller/kill.go
  cmd/juju/controller/kill_test.go
  cmd/juju/controller/killstatus.go
  cmd/juju/model/destroy.go
  cmd/juju/model/destroy_test.go
  rpc/params/controller.go
  rpc/params/model.go
Labels: 3.0

#15054 Fix LXD init in Equinix provider
  provider/equinix/environ.go
Labels: 3.0

#15064 Fix controller config type coercion for time.Duration
  apiserver/admin_test.go
  cmd/juju/controller/config.go
  cmd/juju/controller/config_test.go
  controller/config.go
  controller/config_test.go
  state/controller.go
  state/controller_test.go
  state/upgrades.go
  state/upgrades_test.go
  upgrades/backend.go
  upgrades/operations.go
  upgrades/steps_2939.go
  upgrades/steps_2939_test.go
  upgrades/upgrade_test.go
Labels: bug, 2.9

#15067 [JUJU-2502] Fixed test-storage-test-persistent-storage-aws
  tests/suites/storage/persistent_storage.sh
Labels: bug, 3.0

#15063 [JUJU-2249] Fix LP 2002114, panic running full status.
  state/application.go
Labels: 2.9

#15069 Fix error message when trying to integrate 2 times in a row
  cmd/juju/application/integrate.go
  featuretests/cmd_juju_relation_test.go
Labels: 3.0

#15029 Merge 2.9 to 3.0
  cmd/juju/controller/config.go
  cmd/juju/controller/config_test.go
  cmd/juju/controller/listmodels.go
  cmd/juju/controller/listmodels_test.go
  controller/config.go
  controller/config_test.go
  network/containerizer/bridgepolicy.go
  network/containerizer/bridgepolicy_integration_test.go
  network/containerizer/linklayerdevicesforspaces_test.go
  provider/maas/devices.go
  provider/maas/maas_environ_whitebox_test.go
  state/application.go
  state/controller.go
  state/controller_test.go
Labels: 3.0

#15074 Merge 3.0 to develop
  cmd/juju/application/integrate.go
  cmd/juju/controller/config.go
  cmd/juju/controller/config_test.go
  cmd/juju/controller/listmodels.go
  cmd/juju/controller/listmodels_test.go
  controller/config.go
  controller/config_test.go
  featuretests/cmd_juju_relation_test.go
  network/containerizer/bridgepolicy.go
  network/containerizer/bridgepolicy_integration_test.go
  network/containerizer/linklayerdevicesforspaces_test.go
  provider/equinix/environ.go
  provider/maas/devices.go
  provider/maas/maas_environ_whitebox_test.go
  state/application.go
  state/controller.go
  state/controller_test.go
  tests/suites/storage/persistent_storage.sh
Labels: 3.1

#15062 [JUJU-2488] Final no charmstore
  cmd/juju/application/bundle_test.go
  cmd/juju/application/refresh.go
  cmd/juju/application/refresh_test.go
  cmd/juju/waitfor/application_test.go
  core/bundle/changes/changes_test.go
  core/bundle/changes/changessort_test.go
  core/bundle/changes/model_test.go
  migration/precheck_test.go
Labels: 3.1

#15068 [JUJU-2506] autocompletion of channel in empty model
  etc/bash_completion.d/juju
Labels: bug, 3.0

#15057 [JUJU-2449] Allow building locally without a LXC container
  .gitignore
  scripts/dqlite/Makefile
  scripts/dqlite/build-script.sh
Labels: feature

#15085 [JUJU-2450] Add sudo to apt-get, otherwise we can't get apt lock
  scripts/dqlite/build-script.sh
Labels: feature, 3.1

#15086 [JUJU-2450] Ensure musl is installed with the right privileges.
  scripts/dqlite/build-script.sh
Labels: feature, 3.1

#15087 [JUJU-2450] Look in the correct place for the build
  scripts/dqlite/Makefile
Labels: feature, 3.1

#15070 [JUJU-2482] Allow consuming of related changes
  worker/storageprovisioner/export_test.go
  worker/storageprovisioner/mock_test.go
  worker/storageprovisioner/storageprovisioner.go
  worker/storageprovisioner/storageprovisioner_test.go
Labels: bug, 2.9

#15092 [JUJU-2548] Added test-model-test-model-status to 2.9
  tests/suites/model/status.sh
  tests/suites/model/task.sh
Labels: 2.9

#15089 [JUJU-2465] Update juju/utils to v3.0.1
  core/arch/arches_test.go
  go.mod
  go.sum
Labels: 3.0

#15090 [JUJU-2547] Update fix to LP1984061. - adding latest to charm origin channel
  state/migration_import.go
  state/migration_import_test.go
Labels: bug, 2.9

#15102 [JUJU-2571] Pass series in charm upgrade series hook environment
  worker/uniter/hook/hook.go
  worker/uniter/hook/hook_test.go
  worker/uniter/operation/runhook_test.go
  worker/uniter/reboot/resolver.go
  worker/uniter/remotestate/mock_test.go
  worker/uniter/remotestate/snapshot.go
  worker/uniter/remotestate/watcher.go
  worker/uniter/remotestate/watcher_test.go
  worker/uniter/resolver/interface.go
  worker/uniter/resolver/opfactory.go
  worker/uniter/resolver/opfactory_test.go
  worker/uniter/resolver_test.go
  worker/uniter/runner/context/context.go
  worker/uniter/runner/context/contextfactory.go
  worker/uniter/uniter.go
  worker/uniter/upgradeseries/resolver.go
  worker/uniter/upgradeseries/resolver_test.go
Labels: bug, 3.0

#15096 [JUJU-1868] Fix concurrent provisioning issues in MAAS
  api/agent/provisioner/machine.go
  api/agent/provisioner/mocks/machine_mock.go
  api/agent/provisioner/provisioner.go
  api/agent/provisioner/provisioner_test.go
  go.mod
  go.sum
  provider/common/bootstrap.go
  provider/maas/config.go
  provider/maas/environ.go
  provider/maas/environprovider.go
  worker/containerbroker/mocks/machine_mock.go
  worker/provisioner/export_test.go
  worker/provisioner/mocks/provisioner.go
  worker/provisioner/package_test.go
  worker/provisioner/provisioner.go
  worker/provisioner/provisioner_task.go
  worker/provisioner/provisioner_task_test.go
  worker/provisioner/provisioner_test.go
Labels: 2.9

#15099 [JUJU-2463] fix LP1999060 single charm multi app bundle failures
  apiserver/facades/controller/charmdownloader/charmdownloader.go
  apiserver/facades/controller/charmdownloader/charmdownloader_test.go
  apiserver/facades/controller/charmdownloader/package_test.go
  state/application.go
  state/application_test.go
  state/export_test.go
  state/migration_import.go
  state/migration_import_test.go
  state/state.go
  state/upgrades.go
  state/upgrades_test.go
  upgrades/backend.go
  upgrades/operations.go
  upgrades/steps_303.go
  upgrades/upgrade_test.go
Labels: bug, 3.0

#15101 [JUJU-2522] Fixed test-ck-aws
  tests/suites/ck/ck.sh
  tests/suites/ck/task.sh
Labels: 2.9

#15078 [JUJU-2519] Remove groups on start instance failure
  provider/openstack/local_test.go
  provider/openstack/provider.go
Labels: bug, do not merge, 2.9

#15107 [JUJU-2585] Allow cross compiling jujud per GOARCH
  Makefile
  scripts/dqlite/Makefile
  scripts/dqlite/build-script.sh
Labels: feature, 3.2

#15105 [JUJU-2577] Allow building dqlite static libs for ppc64le
  scripts/dqlite/build-script.sh
Labels: feature, 3.2

#15113 [JUJU-2627] Remove raft lease API client
  api/controller/raftlease/doc.go
  api/controller/raftlease/package_test.go
  api/controller/raftlease/raftlease.go
  api/controller/raftlease/raftlease_test.go
  api/facadeversions.go
Labels: feature, 3.2

#15110 Merge 3.0 to 3.1
  apiserver/facades/controller/charmdownloader/charmdownloader.go
  apiserver/facades/controller/charmdownloader/charmdownloader_test.go
  apiserver/facades/controller/charmdownloader/package_test.go
  state/application.go
  state/application_test.go
  state/export_test.go
  state/migration_import.go
  state/migration_import_test.go
  state/state.go
  tests/suites/ck/ck.sh
  tests/suites/ck/overlay/aws.yaml
  tests/suites/ck/storage/aws.yaml
  tests/suites/ck/storage/azure.yaml
  tests/suites/ck/storage/gce.yaml
  tests/suites/ck/task.sh
  worker/uniter/hook/hook.go
  worker/uniter/hook/hook_test.go
  worker/uniter/operation/runhook_test.go
  worker/uniter/reboot/resolver.go
  worker/uniter/remotestate/mock_test.go
  worker/uniter/remotestate/snapshot.go
  worker/uniter/remotestate/watcher.go
  worker/uniter/remotestate/watcher_test.go
  worker/uniter/resolver/interface.go
  worker/uniter/resolver/opfactory.go
  worker/uniter/resolver/opfactory_test.go
  worker/uniter/resolver_test.go
  worker/uniter/runner/context/context.go
  worker/uniter/runner/context/contextfactory.go
  worker/uniter/uniter.go
  worker/uniter/upgradeseries/resolver.go
  worker/uniter/upgradeseries/resolver_test.go
Labels: bug, 3.1

#15115 [JUJU-2677] Remove Main test go file
  .github/workflows/client-tests.yml
  Makefile
  cmd/jujuc/main_test.go
  cmd/jujud/agent/machine_test.go
  cmd/jujud/main_test.go
Labels: feature, 3.2

#15116 [JUJU-2474] Fix unit status message when application is removed
  apiserver/common/unitstatus.go
  apiserver/common/unitstatus_test.go
Labels: bug, 2.9

#15123 [JUJU-2627] Fix lease expiry manifold tests
  cmd/jujud/agent/machine/manifolds_test.go
Labels: feature, 3.2
