Repository juju/juju, pull requests merged in 2023-12, with the labels that each got.

#16655 Merge 3.1
  caas/kubernetes/provider/scale/scale.go
  state/allcollections.go
  tests/suites/deploy/deploy_charms.sh
  tests/suites/secrets_iaas/vault.sh
  tests/suites/spaces_ec2/util.sh
  worker/caasapplicationprovisioner/ops.go
Labels: 3.3

#16648 Schema for storage instances
  domain/schema/model.go
  domain/schema/schema_test.go
Labels: 4.0

#16665 2.9 into 3.1
  container/kvm/libvirt/domainxml.go
  container/kvm/libvirt/domainxml_test.go
  state/allcollections.go
Labels: 3.1

#16661 Bootstrap agent tools
  agent/tools/toolsdir.go
  cmd/jujud/agent/bootstrap.go
  cmd/jujud/agent/bootstrap_test.go
  cmd/jujud/agent/machine/manifolds.go
  domain/autocert/state/state.go
  domain/flag/service/service.go
  domain/flag/service/service_test.go
  domain/flag/state/state.go
  domain/flag/state/state_test.go
  internal/bootstrap/agentbinary.go
  internal/bootstrap/agentbinary_test.go
  internal/bootstrap/bootstrap_mock_test.go
  internal/bootstrap/package_test.go
  internal/cloudconfig/userdatacfg_test.go
  internal/cloudconfig/userdatacfg_unix.go
  internal/servicefactory/interface.go
  worker/bootstrap/bootstrap_mock_test.go
  worker/bootstrap/manifold.go
  worker/bootstrap/manifold_test.go
  worker/bootstrap/package_test.go
  worker/bootstrap/worker.go
  worker/bootstrap/worker_test.go
  worker/objectstore/manifold.go
  worker/servicefactory/servicefactory_mock_test.go
  worker/upgradedatabase/servicefactory_mock_test.go
Labels: 4.0

#16659 Cloud model defaults for bootstrap.
  agent/agentbootstrap/bootstrap.go
  domain/cloud/bootstrap/bootstrap.go
  domain/cloud/bootstrap/bootstrap_test.go
  domain/cloud/errors/errors.go
  domain/cloud/state/state.go
  domain/cloud/state/state_test.go
  internal/database/statement.go
  internal/database/statement_test.go
Labels: 4.0

#16658 Merge 3.1 to 3.3
  apiserver/facades/client/client/status_test.go
  cmd/juju/status/status_internal_test.go
  state/application.go
  state/application_test.go
  state/charm_test.go
  state/unit_test.go
  worker/uniter/util_test.go
Labels: 3.3

#16678 Removing model config defaults table.
  domain/schema/controller.go
  domain/schema/schema_test.go
Labels: 4.0

#16680 Fix juju-exec machine lock log path. Fix caasapplication log path.
  apiserver/facades/agent/caasapplication/application.go
  apiserver/facades/agent/caasapplication/application_test.go
  cmd/containeragent/main_nix.go
  cmd/jujud/main.go
Labels: 3.3

#16681 Refactor state out of apiserver
  apiserver/charms.go
  cmd/jujud/agent/controllercharm.go
Labels: 4.0

#16683 Provide a charm-ref to add application
  state/state.go
Labels: 4.0

#16601 State layer for User domain
  core/user/user.go
  domain/schema/controller.go
  domain/user/errors/errors.go
  domain/user/service/service.go
  domain/user/service/service_test.go
  domain/user/service/state_mock_test.go
  domain/user/state/state.go
  domain/user/state/state_test.go
  domain/user/state/types.go
Labels: 4.0

#16691 Move upgrades package to internal package
  apiserver/facades/client/modelupgrader/upgrader.go
  apiserver/facades/client/modelupgrader/upgrader_test.go
  cmd/containeragent/unit/agent.go
  cmd/containeragent/unit/manifolds.go
  cmd/jujud/agent/machine.go
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/agent/machine/manifolds_test.go
  cmd/jujud/agent/util_test.go
  cmd/jujud/main.go
  internal/migration/package_test.go
  internal/migration/precheck.go
  internal/migration/precheck_test.go
  internal/upgrades/backend.go
  internal/upgrades/contexts.go
  internal/upgrades/doc.go
  internal/upgrades/environconfig.go
  internal/upgrades/environconfig_test.go
  internal/upgrades/export_test.go
  internal/upgrades/mocks/context_mock.go
  internal/upgrades/operations.go
  internal/upgrades/package_test.go
  internal/upgrades/preupgradesteps.go
  internal/upgrades/preupgradesteps_test.go
  internal/upgrades/testdata/uniter-state-app.yaml
  internal/upgrades/testdata/uniter-state-no-app.yaml
  internal/upgrades/testdata/uniter-state-no-hook.yaml
  internal/upgrades/testdata/uniter-state-something-else.notyaml
  internal/upgrades/upgrade.go
  internal/upgrades/upgrade_test.go
  internal/upgrades/upgradevalidation/interfaces.go
  internal/upgrades/upgradevalidation/migrate.go
  internal/upgrades/upgradevalidation/migrate_test.go
  internal/upgrades/upgradevalidation/mocks/lxd_mock.go
  internal/upgrades/upgradevalidation/mocks/state_mock.go
  internal/upgrades/upgradevalidation/package_test.go
  internal/upgrades/upgradevalidation/upgrade.go
  internal/upgrades/upgradevalidation/upgrade_test.go
  internal/upgrades/upgradevalidation/validation.go
  internal/upgrades/upgradevalidation/validation_test.go
  internal/upgrades/upgradevalidation/version.go
  internal/upgrades/upgradevalidation/version_test.go
  internal/upgradesteps/package_test.go
  internal/upgradesteps/worker.go
  internal/upgradesteps/worker_test.go
  worker/upgrader/manifold.go
  worker/upgrader/upgrader.go
  worker/upgrader/upgrader_test.go
  worker/upgradesteps/controllerworker.go
  worker/upgradesteps/manifold.go
  worker/upgradesteps/manifold_test.go
  worker/upgradesteps/package_test.go
  worker/upgradestepsmachine/machineworker.go
  worker/upgradestepsmachine/machineworker_test.go
  worker/upgradestepsmachine/manifold.go
  worker/upgradestepsmachine/manifold_test.go
  worker/upgradestepsmachine/package_test.go
Labels: 4.0

#16663 Add network domain state
  domain/network/state/package_test.go
  domain/network/state/space.go
  domain/network/state/space_test.go
  domain/network/state/subnet.go
  domain/network/state/subnet_test.go
  domain/network/state/types.go
  domain/schema/model.go
Labels: 4.0

#16682 Add storage volumes, filesystems and attachment skeletons
  domain/schema/model.go
  domain/schema/schema_test.go
Labels: 4.0

#16696 Objects HTTP get request
  apiserver/apiserver.go
  apiserver/objects.go
  apiserver/objects_test.go
Labels: 4.0

#16692 Enable a juju 3.x client to work against juju 2.9.latest server
  api/apiclient.go
  api/apiclient_test.go
  apiserver/admin.go
  apiserver/errors/errors.go
  apiserver/errors/errors_test.go
  apiserver/export_test.go
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/application_test.go
  apiserver/facades/client/application/application_unit_test.go
  apiserver/facades/client/charms/client.go
  apiserver/facades/client/charms/client_test.go
  apiserver/facades/client/charms/conversions.go
  apiserver/facades/client/machinemanager/machinemanager.go
  apiserver/restrict_newer_client.go
  apiserver/restrict_newer_client_test.go
  apiserver/restrict_restore_test.go
  apiserver/root.go
  rpc/params/apierror.go
Labels: 2.9

#16700 Add upsert method in state for subnets domain
  domain/network/state/space.go
  domain/network/state/space_test.go
  domain/network/state/subnet.go
  domain/network/state/subnet_test.go
Labels: 4.0

#16693 Add retry logic to lxd image download
  cmd/juju/commands/bootstrap.go
  container/broker/broker_test.go
  container/broker/kvm-broker.go
  container/broker/lxd-broker.go
  container/broker/lxd-broker_test.go
  container/interface.go
  container/kvm/kvm.go
  container/kvm/live_test.go
  container/lxd/connection.go
  container/lxd/connection_test.go
  container/lxd/export_test.go
  container/lxd/image.go
  container/lxd/image_test.go
  container/lxd/manager.go
  container/lxd/manager_test.go
  container/testing/common.go
  container/testing/interface_mock.go
  container/testing/package_mock.go
  provider/lxd/environ_broker.go
  provider/lxd/environ_broker_test.go
  provider/lxd/package_mock_test.go
  provider/lxd/server.go
  provider/lxd/testing_test.go
  upgrades/upgradevalidation/mocks/lxd_mock.go
Labels: 3.1

#16568 Add doc for instancemutetor worker
  worker/instancemutater/doc.go
Labels: 3.3

#16684 Add domain persistence and watcher for block devices.
  domain/blockdevice/package_test.go
  domain/blockdevice/service/package_test.go
  domain/blockdevice/service/service.go
  domain/blockdevice/state/package_test.go
  domain/blockdevice/state/state.go
  domain/blockdevice/state/state_test.go
  domain/blockdevice/state/types.go
  domain/blockdevice/types.go
  domain/blockdevice/watcher_test.go
  domain/life/life.go
  domain/life/life_test.go
  domain/life/package_test.go
  domain/machine/errors/errors.go
  domain/schema/model.go
Labels: 4.0

#16563 Add doc for remote relations worker
  worker/remoterelations/doc.go
Labels: 3.3

#16428 JU048: Add support for Pebble Notices
  go.mod
  go.sum
  testcharms/charms/pebble-notices/.gitignore
  testcharms/charms/pebble-notices/charmcraft.yaml
  testcharms/charms/pebble-notices/metadata.yaml
  testcharms/charms/pebble-notices/pyproject.toml
  testcharms/charms/pebble-notices/requirements.txt
  testcharms/charms/pebble-notices/src/charm.py
  testcharms/charms/pebble-notices/tests/unit/test_charm.py
  testcharms/charms/pebble-notices/tox.ini
  tests/suites/sidecar/sidecar.sh
  tests/suites/sidecar/task.sh
  worker/uniter/container/workload.go
  worker/uniter/container/workload_test.go
  worker/uniter/hook/hook.go
  worker/uniter/hook/hook_test.go
  worker/uniter/pebblenotices.go
  worker/uniter/pebblenotices_test.go
  worker/uniter/pebblepoller.go
  worker/uniter/pebblepoller_test.go
  worker/uniter/runner/context/context.go
  worker/uniter/runner/context/contextfactory.go
  worker/uniter/runner/context/env_test.go
  worker/uniter/runner/context/export_test.go
  worker/uniter/uniter.go
  worker/uniter/util_test.go
Labels: 3.4

#16704 Clear tech debt by migrating remaining uses of application offer tags to use offer uuids.
  api/watcher/watcher_test.go
  apiserver/common/crossmodel/crossmodel.go
  apiserver/common/crossmodel/interface.go
  apiserver/common/crossmodel/state.go
  apiserver/common/permissions_test.go
  apiserver/facades/client/application/application_unit_test.go
  apiserver/facades/client/applicationoffers/access_test.go
  apiserver/facades/client/applicationoffers/applicationoffers.go
  apiserver/facades/client/applicationoffers/applicationoffers_test.go
  apiserver/facades/client/applicationoffers/mock_test.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations_test.go
  apiserver/facades/controller/crossmodelrelations/mock_test.go
  apiserver/facades/controller/remoterelations/mocks/remoterelations_mocks.go
  apiserver/facades/controller/remoterelations/remoterelations_test.go
  state/applicationoffers.go
  state/applicationoffers_test.go
  state/applicationofferuser.go
  state/applicationofferuser_test.go
  state/migration_export_test.go
  state/migration_import.go
  state/migration_import_input_mock_test.go
  state/migration_import_tasks.go
  state/migration_import_tasks_test.go
  state/migration_import_test.go
  state/upgrades.go
  state/upgrades_test.go
  state/useraccess.go
  upgrades/backend.go
  upgrades/operations.go
  upgrades/steps_331.go
  upgrades/steps_331_test.go
  upgrades/upgrade_test.go
Labels: 3.3

#16688 Add bootstrap package in the user domain
  agent/agentbootstrap/bootstrap.go
  domain/user/bootstrap/bootstrap.go
  domain/user/bootstrap/bootstrap_test.go
  domain/user/bootstrap/package_test.go
  domain/user/service/service.go
  domain/user/state/state.go
  domain/user/state/state_test.go
Labels: 4.0

#16705 Add network domain service, SaveProviderSubnets method
  domain/network/service/package_test.go
  domain/network/service/space.go
  domain/network/service/space_test.go
  domain/network/service/state_mock_test.go
Labels: 4.0

#16690 Add EnableUser, DisableUser to user domain
  domain/user/service/service.go
  domain/user/service/service_test.go
  domain/user/service/state_mock_test.go
  domain/user/state/state.go
  domain/user/state/state_test.go
Labels: 4.0

#16701 Restructure charms client
  api/client/charms/client.go
  api/client/charms/client_test.go
  api/client/charms/export_test.go
  api/client/charms/localcharmclient.go
  api/client/charms/localcharmclient_test.go
  cmd/juju/application/deploy.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/refresh.go
  featuretests/client_macaroon_test.go
Labels: 3.4

#16714 Clean tools.tar.gz on success
  internal/bootstrap/agentbinary.go
  internal/bootstrap/agentbinary_test.go
  internal/worker/bootstrap/manifold.go
  internal/worker/bootstrap/manifold_test.go
  internal/worker/bootstrap/worker.go
  internal/worker/bootstrap/worker_test.go
Labels: 4.0

#16716 Fix flaky block device tests
  domain/blockdevice/state/state_test.go
  domain/blockdevice/watcher_test.go
  domain/cloud/state/state_test.go
  domain/schema/testing/modelsuite.go
  internal/changestream/testing/modelsuite.go
Labels: 4.0
