Repository juju/juju, pull requests merged in 2023-03, with the labels that each got.

#15247 New merge from 2.9 from 15196 timeline
  apiserver/facades/client/application/application.go
  cloud/fallback-public-cloud.yaml
  cloud/fallback_public_cloud.go
  cloudconfig/cloudinit/network_ubuntu.go
  cloudconfig/cloudinit/network_ubuntu_test.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/bundlehandler_test.go
  cmd/juju/application/deployer/interface.go
  cmd/juju/application/deployer/mocks/deploy_mock.go
  cmd/juju/application/deployer/resource.go
  cmd/juju/application/refresh.go
  cmd/juju/application/refresh_resources_test.go
  cmd/juju/application/refresh_test.go
  cmd/juju/application/refresher/refresher.go
  cmd/juju/application/utils/interface.go
  cmd/juju/application/utils/mocks/charmresource_mock.go
  cmd/juju/application/utils/utils.go
  cmd/juju/application/utils/utils_test.go
  cmd/juju/commands/bootstrap_test.go
  state/application.go
  state/resources.go
  tests/suites/resources/attach.sh
  tests/suites/resources/refresh.sh
  tests/suites/resources/task.sh
Labels: 3.0

#15246 [JUJU-2951] Fix opened-ports return, merge with pending open/close port ranges
  core/network/portrange.go
  state/application_ports.go
  worker/uniter/runner/context/context_test.go
  worker/uniter/runner/context/ports.go
Labels: 3.1

#15226 [JUJU-2668] Add s3 caller worker, use s3caller to download charms
  api/client/charms/downloader.go
  api/client/charms/downloader_s3.go
  api/client/charms/downloader_s3_test.go
  api/client/charms/mocks/s3caller_mock.go
  api/client/charms/package_test.go
  apiserver/facades/client/charms/client.go
  cmd/containeragent/unit/manifolds.go
  cmd/containeragent/unit/manifolds_test.go
  cmd/jujud/agent/machine/manifolds.go
  downloader/download.go
  downloader/downloader.go
  downloader/utils.go
  go.mod
  go.sum
  worker/caasoperator/caasoperator_test.go
  worker/deployer/unit_manifolds.go
  worker/deployer/unit_manifolds_test.go
  worker/s3caller/client.go
  worker/s3caller/manifold.go
  worker/s3caller/worker.go
  worker/uniter/charm/bundles.go
  worker/uniter/manifold.go
Labels: 3.2

#15241 [JUJU-2952] update help messages referencing charm store
  cmd/juju/application/deploy.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/charm.go
  cmd/juju/application/diffbundle.go
  cmd/juju/application/refresh.go
  cmd/juju/application/refresher/refresher.go
Labels: 3.1

#15204 [JUJU-2620] Eventqueue
  cmd/jujud/agent/machine/manifolds.go
  core/changestream/subscription.go
  worker/changestream/eventqueue/change_mock_test.go
  worker/changestream/eventqueue/eventqueue.go
  worker/changestream/eventqueue/eventqueue_test.go
  worker/changestream/eventqueue/logger_mock_test.go
  worker/changestream/eventqueue/package_test.go
  worker/changestream/eventqueue/stream_mock_test.go
  worker/changestream/manifold.go
  worker/changestream/manifold_test.go
  worker/changestream/package_test.go
  worker/changestream/stream/clock_mock_test.go
  worker/changestream/stream/logger_mock_test.go
  worker/changestream/stream/package_test.go
  worker/changestream/stream/stream.go
  worker/changestream/stream/stream_mock_test.go
  worker/changestream/stream/stream_test.go
  worker/changestream/stream_mock_test.go
  worker/changestream/worker.go
  worker/changestream/worker_test.go
Labels: feature, 3.2

#15264 Fix/sidecar migration
  apiserver/mocks/resources_mock.go
  apiserver/package_test.go
  apiserver/resources_mig.go
  apiserver/resources_mig_test.go
  caas/kubernetes/provider/application/application_test.go
  caas/kubernetes/provider/resources/statefulset.go
Labels: bug, 2.9

#15265 [JUJU-2566] Add facade and backend calls for watching secret changes across models
  api/controller/crossmodelrelations/crossmodelrelations.go
  api/controller/crossmodelrelations/crossmodelrelations_test.go
  api/facadeversions.go
  api/watcher/watcher.go
  api/watcher/watcher_test.go
  apiserver/admin_test.go
  apiserver/allfacades.go
  apiserver/facades/agent/secretsmanager/register.go
  apiserver/facades/controller/crosscontroller/register.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations_test.go
  apiserver/facades/controller/crossmodelrelations/mock_test.go
  apiserver/facades/controller/crossmodelrelations/register.go
  apiserver/facades/controller/crossmodelrelations/state.go
  apiserver/facades/controller/crossmodelsecrets/crossmodelsecrets.go
  apiserver/facades/controller/crossmodelsecrets/crossmodelsecrets_test.go
  apiserver/facades/schema.json
  apiserver/restrict_anonymous.go
  apiserver/restrict_caasmodel.go
  apiserver/watcher.go
  core/watcher/secrets.go
  rpc/params/secrets.go
  state/secrets.go
  state/secrets_test.go
Labels: 3.2

#15266 [JUJU-2928] fully remove users
  api/client/usermanager/client_test.go
  state/user.go
  state/user_test.go
Labels: 2.9

#15282 [JUJU-3254] Expose a way to build juju without jujud
  Makefile
Labels: feature, 3.2

#15281 [JUJU-2874] Ensure build tags are passed when building
  snap/snapcraft.yaml
Labels: feature, 3.2

#15284 [JUJU-3242] Add image-id constraint
  apiserver/facades/schema.json
  caas/kubernetes/provider/constraints.go
  core/constraints/constraints.go
  core/constraints/constraints_test.go
  provider/azure/environ.go
  provider/dummy/environs.go
  provider/ec2/environ.go
  provider/equinix/environ.go
  provider/gce/environ_policy.go
  provider/lxd/environ_policy.go
  provider/manual/environ.go
  provider/oci/environ.go
  provider/openstack/provider.go
  provider/vsphere/environ_policy.go
  state/constraints.go
  state/migration_internal_test.go
  state/unit.go
Labels: 3.2

#15260 Submitting a tool for examining model transaction queues
  scripts/juju-txn-helper/README.txt
  scripts/juju-txn-helper/requirements.txt
  scripts/juju-txn-helper/setup.py
  scripts/juju-txn-helper/snap/snapcraft.yaml
  scripts/juju-txn-helper/txn_helper.py
Labels: 3.2

#15292 [JUJU-3278] Remove bespoke dqlite REPL
  scripts/dqlite/Makefile
  scripts/dqlite/scripts/repl/install.sh
  scripts/dqlite/scripts/repl/repl.sh
  worker/dbaccessor/repl.go
  worker/dbaccessor/repl_test.go
  worker/dbaccessor/worker.go
Labels: feature, 3.2

#15267 [JUJU-2941] Tracked db
  cmd/jujud/agent/machine/manifolds.go
  core/database/trackeddb.go
  database/errors.go
  database/testing/fullsuite.go
  database/testing/simplesuite.go
  database/testing/trackeddb.go
  database/txn.go
  database/txn/errors.go
  database/txn/errors_test.go
  database/txn/package_test.go
  database/txn/transaction.go
  database/txn/transaction_test.go
  worker/changestream/eventqueue/eventqueue.go
  worker/changestream/manifold.go
  worker/changestream/manifold_test.go
  worker/changestream/stream/package_test.go
  worker/changestream/stream/stream.go
  worker/changestream/stream/stream_test.go
  worker/changestream/stream_mock_test.go
  worker/changestream/worker.go
  worker/changestream/worker_test.go
  worker/dbaccessor/clock_mock_test.go
  worker/dbaccessor/logger_mock_test.go
  worker/dbaccessor/manifold.go
  worker/dbaccessor/manifold_test.go
  worker/dbaccessor/package_mock_test.go
  worker/dbaccessor/package_test.go
  worker/dbaccessor/worker.go
  worker/dbaccessor/worker_test.go
  worker/lease/manager.go
  worker/lease/manifold/database_mock_test.go
  worker/lease/manifold/manifold.go
  worker/lease/manifold/manifold_test.go
  worker/lease/manifold/package_test.go
  worker/lease/store.go
  worker/lease/store_test.go
  worker/leaseexpiry/database_mock_test.go
  worker/leaseexpiry/manifold.go
  worker/leaseexpiry/manifold_test.go
  worker/leaseexpiry/package_test.go
  worker/leaseexpiry/worker.go
  worker/leaseexpiry/worker_test.go
Labels: feature, 3.2

#15293 [JUJU-3213] DeployFromRepository validate endpoint bindings, placement and number of units
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/deployrepository.go
  apiserver/facades/client/application/deployrepository_mocks_test.go
  apiserver/facades/client/application/deployrepository_test.go
  apiserver/facades/client/application/package_test.go
  cmd/juju/application/deployer/charm.go
Labels: feature, 3.2

#15300 [JUJU-3294] Allow suggested retry for juju download
  cmd/juju/charmhub/download.go
  cmd/juju/charmhub/download_test.go
Labels: bug, 2.9

#15312 [JUJU-3293] Update gomaasapi dep
  go.mod
  go.sum
Labels: bug, 2.9

#15249 [JUJU-2160] Tidy up Getdeployer on client
  cmd/juju/application/deploy.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/deployer.go
  cmd/juju/application/deployer/deployer_test.go
  tests/suites/deploy/deploy_charms.sh
Labels: 3.2

#15316 [JUJU-3308] Thread DB Getter through to the APIServer
  apiserver/apiserver.go
  apiserver/apiserver_test.go
  apiserver/facade/facadetest/context.go
  apiserver/facade/interface.go
  apiserver/facade/package_test.go
  apiserver/facades/client/charms/client_test.go
  apiserver/facades/controller/caasmodelconfigmanager/facade.go
  apiserver/facades/controller/caasmodelconfigmanager/mocks/context_mock.go
  apiserver/facades/controller/caasmodelconfigmanager/package_test.go
  apiserver/package_test.go
  apiserver/root.go
  apiserver/shared.go
  apiserver/shared_test.go
  apiserver/testserver/server.go
  cmd/jujud/agent/machine/manifolds.go
  core/database/interface.go
  provider/dummy/environs.go
  worker/apiserver/manifold.go
  worker/apiserver/manifold_test.go
  worker/apiserver/worker.go
  worker/apiserver/worker_state_test.go
  worker/apiserver/worker_test.go
  worker/changestream/worker.go
  worker/dbaccessor/manifold.go
  worker/dbaccessor/package_mock_test.go
  worker/dbaccessor/worker.go
  worker/dbaccessor/worker_test.go
  worker/lease/manifold/manifold.go
  worker/leaseexpiry/manifold.go
Labels: feature, 3.2

#15296 [JUJU-3273] Handle TODO regarding changing values in DeployInfo.
  api/client/application/client.go
  api/client/application/client_test.go
  apiserver/facades/client/application/deployrepository.go
  apiserver/facades/client/application/deployrepository_test.go
  apiserver/facades/schema.json
  rpc/params/applications.go
Labels: feature, 3.2

#15286 [JUJU-2990] Refactor add-cloud command docs
  cmd/juju/cloud/add.go
Labels: 3.2

#15288 [JUJU-2992] Refactor add-k8s command docs
  cmd/juju/caas/add.go
Labels: 3.2

#15289 [JUJU-2993] Refactor add-machine command docs
  cmd/juju/machine/add.go
Labels: 3.2

#15323 [JUJU-3326] implement charm config for DeployFromRepository
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/deployrepository.go
  apiserver/facades/client/application/deployrepository_test.go
  cmd/juju/application/deployer/charm.go
  cmd/juju/application/utils/utils.go
Labels: feature, 3.2

#15326 Include builtin secret backends for AdminBackendConfigInfo
  apiserver/common/secrets/secrets.go
  apiserver/common/secrets/secrets_test.go
Labels: 3.2

#15332 Bump golangci-lint to be compatible with go 1.20
  .github/golangci-lint.config.yaml
  .github/workflows/static-analysis.yml
  apiserver/facades/agent/caasapplication/application.go
  apiserver/facades/client/modelmanager/modelmanager.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations.go
  caas/kubernetes/provider/k8s.go
  cmd/juju/action/cancel.go
  cmd/juju/commands/migrate_test.go
  cmd/juju/gui/gui.go
  cmd/juju/storage/add.go
  cmd/modelcmd/base.go
  environs/manual/sshprovisioner/sshprovisioner.go
  provider/azure/storage.go
  provider/openstack/client.go
  state/migration_export.go
  tests/README.md
  tests/suites/static_analysis/lint_go.sh
  worker/uniter/charm/bundles.go
  worker/uniter/runner/jujuc/storage-add.go
Labels: 2.9

#15337 Go 1.20 in snapcraft.yaml
  snap/snapcraft.yaml
Labels: 2.9

#15322 [JUJU-3332] Support JWT login tokens for controller and model access
  apiserver/admin.go
  apiserver/admin_test.go
  apiserver/apiserver.go
  apiserver/apiserver_test.go
  apiserver/authentication/agent.go
  apiserver/authentication/agent_test.go
  apiserver/authentication/interfaces.go
  apiserver/authentication/user.go
  apiserver/authentication/user_test.go
  apiserver/debuglog.go
  apiserver/debuglog_db.go
  apiserver/export_test.go
  apiserver/facade/interface.go
  apiserver/facade/mocks/facade_mock.go
  apiserver/facades/client/client/mocks/facade_mock.go
  apiserver/facades/client/sshclient/mocks/authorizer_mock.go
  apiserver/facades/controller/caasmodelconfigmanager/mocks/context_mock.go
  apiserver/facades/schema.json
  apiserver/httpcontext.go
  apiserver/httpcontext/auth.go
  apiserver/httpcontext/auth_test.go
  apiserver/logintoken.go
  apiserver/logintoken_test.go
  apiserver/root.go
  apiserver/server_test.go
  apiserver/shared.go
  apiserver/shared_test.go
  apiserver/stateauthenticator/auth.go
  apiserver/stateauthenticator/authenticator_test.go
  apiserver/stateauthenticator/context.go
  apiserver/stateauthenticator/locallogin.go
  apiserver/testing/fakeauthorizer.go
  apiserver/testing/fakejwt.go
  controller/config.go
  controller/config_test.go
  core/permission/access.go
  go.mod
  go.sum
  rpc/params/params.go
  state/controller_test.go
Labels: 3.2

#15324 [JUJU-3333] Users removal triggers the removal of model access
  state/user.go
  state/user_test.go
Labels: 2.9

#15331 [JUJU-2741] Transition new Dqlite nodes into HA based on broadcast server details
  agent/agent.go
  agent/agent_test.go
  cmd/jujud/agent/agenttest/agent.go
  cmd/jujud/agent/machine.go
  database/app/dqlite_other.go
  database/client/dqlite_linux.go
  database/client/dqlite_other.go
  database/node.go
  database/node_test.go
  worker/dbaccessor/manifold.go
  worker/dbaccessor/package_mock_test.go
  worker/dbaccessor/package_test.go
  worker/dbaccessor/shim.go
  worker/dbaccessor/tracker.go
  worker/dbaccessor/tracker_test.go
  worker/dbaccessor/worker.go
  worker/dbaccessor/worker_test.go
Labels: 3.2

#15295 [JUJU-2940] DBAccessor metrics
  cmd/jujud/agent/machine/manifolds.go
  core/charm/downloader/mocks/charm_mocks.go
  core/charm/downloader/mocks/logger_mocks.go
  core/charm/downloader/mocks/storage_mocks.go
  core/charm/downloader/package_test.go
  worker/dbaccessor/manifold.go
  worker/dbaccessor/manifold_test.go
  worker/dbaccessor/metrics.go
  worker/dbaccessor/metrics_mock_test.go
  worker/dbaccessor/metrics_test.go
  worker/dbaccessor/package_test.go
  worker/dbaccessor/tracker.go
  worker/dbaccessor/tracker_test.go
  worker/dbaccessor/worker.go
  worker/dbaccessor/worker_test.go
Labels: feature, failed to land, 3.2

#15350 [JUJU-3382] Fix endpoint parse at lxd bootstrap
  provider/lxd/environ.go
  provider/lxd/environ_broker_test.go
  provider/lxd/environ_network_test.go
  provider/lxd/environ_policy_test.go
  provider/lxd/environ_test.go
  provider/lxd/testing_test.go
Labels: bug, 3.1

#15333 [JUJU-3340] Charm deploy must fail if image-id constraint is used and no explicit base is provided
  apiserver/facades/client/application/deployrepository.go
  apiserver/facades/client/application/deployrepository_test.go
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/charm.go
  cmd/juju/application/deployer/charm_test.go
  cmd/juju/application/deployer/deployer.go
  core/charm/series_selector.go
  core/charm/series_selector_test.go
Labels: 3.2

#15277 [JUJU-3233] Back firewall rules with model config
  api/client/firewallrules/client.go
  api/client/firewallrules/client_test.go
  api/client/firewallrules/package_test.go
  api/controller/firewaller/firewaller.go
  api/controller/firewaller/firewaller_test.go
  api/facadeversions.go
  apiserver/allfacades.go
  apiserver/common/crossmodel/crossmodel.go
  apiserver/common/crossmodel/interface.go
  apiserver/common/crossmodel/state.go
  apiserver/facades/client/firewallrules/backend.go
  apiserver/facades/client/firewallrules/firewallrules.go
  apiserver/facades/client/firewallrules/firewallrules_test.go
  apiserver/facades/client/firewallrules/mock_test.go
  apiserver/facades/client/firewallrules/package_test.go
  apiserver/facades/client/firewallrules/register.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations_test.go
  apiserver/facades/controller/crossmodelrelations/mock_test.go
  apiserver/facades/controller/firewaller/firewaller.go
  apiserver/facades/controller/firewaller/firewaller_unit_test.go
  apiserver/facades/controller/firewaller/interface.go
  apiserver/facades/controller/firewaller/mocks/firewaller_mocks.go
  apiserver/facades/controller/remoterelations/mocks/remoterelations_mocks.go
  apiserver/facades/schema.json
  cmd/juju/firewall/listformatter.go
  cmd/juju/firewall/listrules.go
  cmd/juju/firewall/listrules_test.go
  cmd/juju/firewall/setrule.go
  cmd/juju/firewall/setrule_test.go
  environs/config/config.go
  environs/config/config_test.go
  featuretests/cmd_juju_firewallrules_test.go
  rpc/params/firewall.go
  state/allcollections.go
  state/firewallrules.go
  state/firewallrules_test.go
  state/migration_export.go
  state/migration_export_test.go
  state/migration_import.go
  state/migration_import_input_mock_test.go
  state/migration_import_tasks.go
  state/migration_import_tasks_test.go
  state/migration_import_test.go
  state/migration_internal_test.go
  state/package_test.go
  worker/firewaller/firewaller.go
  worker/firewaller/firewaller_test.go
Labels: 3.2

#15348 [JUJU-3358] Use tags for login token access map and introduce AccessRequiredError
  apiserver/admin.go
  apiserver/apiserver.go
  apiserver/apiserver_test.go
  apiserver/common/crossmodel/auth.go
  apiserver/common/crossmodel/auth_test.go
  apiserver/common/crossmodel/mock_test.go
  apiserver/common/crossmodel/state.go
  apiserver/errors/errors.go
  apiserver/errors/types.go
  apiserver/export_test.go
  apiserver/facade/interface.go
  apiserver/facade/mocks/facade_mock.go
  apiserver/facades/client/applicationoffers/access_test.go
  apiserver/facades/client/applicationoffers/applicationoffers_test.go
  apiserver/facades/client/applicationoffers/base.go
  apiserver/facades/client/applicationoffers/mock_test.go
  apiserver/facades/client/applicationoffers/register.go
  apiserver/facades/client/client/mocks/facade_mock.go
  apiserver/facades/client/sshclient/mocks/authorizer_mock.go
  apiserver/facades/controller/caasmodelconfigmanager/mocks/context_mock.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations_test.go
  apiserver/facades/controller/crossmodelrelations/mock_test.go
  apiserver/httpcontext.go
  apiserver/localofferauth.go
  apiserver/logintoken.go
  apiserver/logintoken_test.go
  apiserver/root.go
  apiserver/server_test.go
  apiserver/shared.go
  apiserver/shared_test.go
  apiserver/testing/fakeauthorizer.go
  cmd/containeragent/initialize/package_test.go
  rpc/params/apierror.go
Labels: 3.2

#15349 [JUJU-3377] Ensure we call timer reset
  worker/dbaccessor/package_test.go
  worker/dbaccessor/tracker.go
  worker/dbaccessor/tracker_test.go
Labels: feature, 3.2

#15382 [JUJU-3355] Fix LP 2021700 - refresh charmhub charm after charm revision updater has run.
  state/charm.go
  state/charm_test.go
Labels: bug, 3.0

#15381 [JUJU-2039] Refactor enable-command command docs
  cmd/juju/block/enable.go
Labels: 3.2

#15384 [JUJU-3044] Refactor export-bundle command docs
  cmd/juju/model/exportbundle.go
Labels: 3.2

#15385 [JUJU-3046] Refactor find command docs
  cmd/juju/charmhub/find.go
Labels: 3.2

#15380 [JUJU-3037] Refactor download command docs
  cmd/juju/block/list.go
  cmd/juju/charmhub/download.go
  cmd/juju/controller/enabledestroy.go
Labels: 3.2

#15363 [JUJU-3015] Refactor consume command docs
  cmd/juju/application/consume.go
Labels: 3.2

#15362 [JUJU-3014] Refactor constraints command docs
  cmd/juju/application/constraints.go
Labels: 3.2

#15395 [JUJU-3391] Backport fixes for removal of user model ops
  api/client/usermanager/client_test.go
  state/database.go
  state/mocks/database_mock.go
  state/modeluser.go
  state/user.go
  state/user_test.go
Labels: 2.9

#15398 [JUJU-3394] Record the jwt auth token along side te macaroon on the cmr app entity
  api/client/application/client.go
  api/client/application/client_test.go
  api/client/applicationoffers/client.go
  api/client/applicationoffers/client_test.go
  apiserver/admin.go
  apiserver/apiserver.go
  apiserver/common/crossmodel/auth.go
  apiserver/common/crossmodel/auth_test.go
  apiserver/export_test.go
  apiserver/facade/interface.go
  apiserver/facade/mocks/facade_mock.go
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/application_unit_test.go
  apiserver/facades/client/applicationoffers/access_test.go
  apiserver/facades/client/applicationoffers/applicationoffers.go
  apiserver/facades/client/applicationoffers/applicationoffers_test.go
  apiserver/facades/client/client/mocks/facade_mock.go
  apiserver/facades/client/sshclient/mocks/authorizer_mock.go
  apiserver/facades/controller/caasmodelconfigmanager/mocks/context_mock.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations_test.go
  apiserver/facades/controller/crossmodelsecrets/crossmodelsecrets_test.go
  apiserver/facades/schema.json
  apiserver/localofferauth.go
  apiserver/logintoken.go
  apiserver/logintoken_test.go
  apiserver/root.go
  apiserver/testing/fakeauthorizer.go
  cmd/juju/application/consume.go
  cmd/juju/application/consume_test.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/integrate.go
  cmd/juju/application/integrateremote_test.go
  core/crossmodel/interface.go
  rpc/params/crossmodel.go
  state/applicationoffers.go
  state/applicationofferuser.go
  state/migration_export_test.go
  state/model.go
  state/model_test.go
  state/remoteapplication.go
  state/remoteapplication_test.go
Labels: 3.2

#15401 [JUJU-3400] Fix base bundle checks on constraints
  cmd/juju/application/bundle/bundle.go
  cmd/juju/application/bundle/bundle_test.go
  tests/suites/deploy/bundles/overlay_bundle_image_id.yaml
  tests/suites/deploy/bundles/overlay_bundle_image_id_on_base_bundle.yaml
  tests/suites/deploy/deploy_bundles.sh
Labels: bug, 3.2

#15359 [JUJU-3390] Improve test coverage for changestream
  worker/changestream/stream/stream.go
  worker/changestream/stream/stream_test.go
Labels: feature, 3.2

#15329 [JUJU-2899] Implement ssh-allowlist for aws
  api/controller/firewaller/firewaller.go
  api/controller/firewaller/firewaller_test.go
  apiserver/facades/controller/firewaller/firewaller.go
  apiserver/facades/controller/firewaller/firewaller_unit_test.go
  apiserver/facades/controller/firewaller/interface.go
  apiserver/facades/controller/firewaller/mocks/firewaller_mocks.go
  apiserver/facades/controller/firewaller/mocks/watcher_mocks.go
  apiserver/facades/controller/firewaller/modelfirewallruleswatcher.go
  apiserver/facades/controller/firewaller/modelfirewallruleswatcher_test.go
  apiserver/facades/controller/firewaller/package_test.go
  apiserver/facades/schema.json
  core/network/portrange.go
  core/network/portrange_test.go
  environs/models/model.go
  provider/common/bootstrap.go
  provider/common/mock_test.go
  provider/dummy/environs.go
  provider/ec2/environ.go
  provider/ec2/local_test.go
  provider/ec2/provider.go
  rpc/params/network.go
  worker/firewaller/firewaller.go
  worker/firewaller/firewaller_test.go
  worker/firewaller/manifold.go
Labels: 3.2

#15410 [JUJU-3407] Update cmd to v3.0.7
  go.mod
  go.sum
Labels: 3.2
