Repository juju/juju, pull requests merged in 2023-05, with the labels that each got.

#15563 [JUJU-3542] Revisit test suites to use charms with no storage, and wait until ready
  tests/suites/deploy/deploy_charms.sh
  tests/suites/machine/machine.sh
Labels: 3.2

#15567 [JUJU-3648] Allow schema gen building
  Makefile
Labels: feature, 4.0

#15568 [JUJU-3648] Controller model table schema
  database/bootstrap.go
  database/testing/simplesuite.go
  domain/schema/controller.go
  domain/schema/controller_test.go
  domain/schema/package_test.go
Labels: feature, 4.0

#15569 [JUJU-3648] Model table domain
  apiserver/facade/interface.go
  apiserver/facades/client/modelmanager/listmodelsummaries_test.go
  apiserver/facades/client/modelmanager/modelinfo_test.go
  apiserver/facades/client/modelmanager/modelmanager.go
  apiserver/facades/client/modelmanager/modelmanager_test.go
  apiserver/facades/client/modelmanager/register.go
  database/errors.go
  database/testing/trackeddb.go
  domain/errors.go
  domain/modelmanager/service/package_test.go
  domain/modelmanager/service/service.go
  domain/modelmanager/service/service_test.go
  domain/modelmanager/service/state_mock_test.go
  domain/modelmanager/service/types.go
  domain/modelmanager/service/types_test.go
  domain/modelmanager/state/package_test.go
  domain/modelmanager/state/state.go
  domain/modelmanager/state/state_test.go
  domain/package_test.go
  domain/schema/controller.go
  domain/state.go
  domain/state_test.go
  provider/dummy/environs.go
Labels: feature, 4.0

#15576 [JUJU-3675] Replace ubuntu with ubuntu-lite on CI tests when possible
  tests/suites/bootstrap/streams.sh
  tests/suites/cli/block.sh
  tests/suites/model/migration.sh
  tests/suites/refresh/refresh.sh
  tests/suites/upgrade/streams.sh
Labels: 3.2

#15548 [JUJU-3672] Fix relation interface name not found in juju status --relations --format json
  cmd/juju/status/formatted.go
  cmd/juju/status/formatter.go
  cmd/juju/status/status.go
  cmd/juju/status/status_internal_test.go
  featuretests/cmd_juju_status_test.go
Labels: bug, 3.1

#15572 [JUJU-3686] Dqlite-based UUID watcher
  core/changestream/change.go
  core/changestream/subscription.go
  core/watcher/eventqueue/base.go
  core/watcher/eventqueue/changestream_mock_test.go
  core/watcher/eventqueue/error.go
  core/watcher/eventqueue/interface.go
  core/watcher/eventqueue/package_mock_test.go
  core/watcher/eventqueue/package_test.go
  core/watcher/eventqueue/uuid.go
  core/watcher/eventqueue/uuid_test.go
  worker/changestream/eventqueue/eventqueue.go
  worker/changestream/eventqueue/eventqueue_test.go
Labels: 4.0

#15589 [JUJU-3689] Add Domain for External Controllers
  database/statement.go
  database/statement_test.go
  domain/externalcontroller/service/package_mock_test.go
  domain/externalcontroller/service/package_test.go
  domain/externalcontroller/service/service.go
  domain/externalcontroller/service/service_test.go
  domain/externalcontroller/state/package_test.go
  domain/externalcontroller/state/state.go
  domain/externalcontroller/state/state_test.go
  domain/externalcontroller/state/types.go
  domain/schema/controller.go
Labels: 4.0

#15602 [JUJU-3742] Add il-central-1 AWS region
  cloud/fallback-public-cloud.yaml
  cloud/fallback_public_cloud.go
  cmd/juju/commands/bootstrap_test.go
Labels: 2.9

#15531 [JUJU-3598] Ensure cancellation during bootstrap
  .github/workflows/migrate.yml
  caas/kubernetes/provider/bootstrap.go
  caas/kubernetes/provider/bootstrap_test.go
  cmd/juju/commands/bootstrap.go
  cmd/juju/common/controller.go
  cmd/juju/common/controller_test.go
  environs/bootstrap/bootstrap.go
  environs/bootstrap/bootstrap_test.go
Labels: bug, 3.2

#15606 [JUJU-3678] - Fix secret hook commands for non existing URIs
  apiserver/facades/agent/secretsmanager/secrets.go
  apiserver/facades/agent/secretsmanager/secrets_test.go
Labels: 3.1

#15608 [JUJU-3751] Added github migrate action from 2.9 to 3.1
  .github/workflows/migrate.yml
Labels: 3.1

#15347 Remove the GO ioutil pkg
  worker/filenotifywatcher/watcher_test.go
Labels: decaying, 3.3

#15616 [JUJU-3764] Fix some CI test failures for 2.9
  tests/suites/charmhub/download.sh
  tests/suites/deploy/deploy_charms.sh
  tests/suites/relations/relation_data_exchange.sh
  tests/suites/relations/relation_list_app.sh
Labels: 2.9

#15609 [JUJU-3697] Add image-id constraint on AWS integration tests
  tests/suites/constraints/aws_ami_creation.sh
  tests/suites/constraints/constraints.sh
  tests/suites/constraints/constraints_aws.sh
Labels: 3.3

#15582 [JUJU-3702] ComputeSeries: assume manifest, fall back to series.
  apiserver/facades/client/machinemanager/machinemanager_test.go
  cmd/juju/application/deployer/bundlehandler_test.go
  cmd/juju/application/deployer/deployer_test.go
  core/charm/computedseries.go
  core/charm/computedseries_test.go
Labels: bug, 2.9

#15610 [JUJU-3591] Reduce number of charmhub api calls required deploy from repository.
  apiserver/facades/client/application/deployrepository.go
  apiserver/facades/client/application/deployrepository_test.go
  apiserver/facades/client/application/repository_mocks_test.go
  apiserver/facades/client/charms/mocks/repository.go
  core/charm/basefromcharm.go
  core/charm/basefromcharm_test.go
  core/charm/baseselector.go
  core/charm/baseselector_test.go
  core/charm/charmpath.go
  core/charm/repository.go
  core/charm/repository/charmhub.go
  core/charm/repository/charmhub_test.go
  core/charm/seriesselector.go
  core/charm/seriesselector_test.go
  core/series/base.go
  core/series/base_test.go
Labels: 3.3

#15613 Update juju/cmd to 3.0.10
  go.mod
  go.sum
Labels: 3.3

#15579 [JUJU-3711] Model table dbworker
  cmd/juju/model/defaults.go
  cmd/package_test.go
  database/bootstrap.go
  database/testing/fullsuite.go
  worker/dbaccessor/doc.go
  worker/dbaccessor/manifold.go
  worker/dbaccessor/manifold_test.go
  worker/dbaccessor/package_test.go
  worker/dbaccessor/shim.go
  worker/dbaccessor/tracker.go
  worker/dbaccessor/tracker_test.go
  worker/dbaccessor/worker.go
  worker/dbaccessor/worker_integration_test.go
  worker/dbaccessor/worker_test.go
Labels: feature, failed to land, 4.0

#15624 [JUJU-3778] Fix remote app proxy offer uuid reference
  apiserver/facades/client/client/client_test.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations.go
  apiserver/rest.go
  apiserver/watcher.go
  core/multiwatcher/types.go
  core/series/supportedseries_linux_test.go
  core/series/supportedseries_test.go
  rpc/params/multiwatcher.go
  state/allwatcher.go
  state/allwatcher_internal_test.go
  state/applicationoffers.go
  state/applicationoffers_test.go
  state/cleanup_test.go
  state/migration_import.go
  state/remoteapplication.go
  state/remoteapplication_test.go
  state/upgrades.go
  state/upgrades_test.go
Labels: 2.9

#15628 [JUJU-3775] Fix raising `state.AddApplication` errors in DeployFromRepository
  apiserver/facades/client/application/deployrepository.go
Labels: feature, 3.3

#15592 [JUJU-3715] Clean up worker on delete model
  apiserver/apiserver.go
  apiserver/apiserver_test.go
  apiserver/facade/interface.go
  apiserver/facades/client/modelmanager/modelmanager.go
  apiserver/facades/client/modelmanager/register.go
  apiserver/package_test.go
  apiserver/root.go
  apiserver/shared.go
  apiserver/shared_test.go
  apiserver/testserver/server.go
  core/database/dbmanager.go
  domain/modelmanager/service/package_test.go
  domain/modelmanager/service/service.go
  domain/modelmanager/service/service_test.go
  domain/modelmanager/service/state_mock_test.go
  domain/modelmanager/state/state_test.go
  provider/dummy/environs.go
  worker/apiserver/manifold.go
  worker/apiserver/manifold_test.go
  worker/apiserver/worker.go
  worker/apiserver/worker_state_test.go
  worker/apiserver/worker_test.go
  worker/dbaccessor/manifold.go
  worker/dbaccessor/package_test.go
  worker/dbaccessor/worker.go
  worker/dbaccessor/worker_integration_test.go
  worker/dbaccessor/worker_test.go
Labels: feature, 4.0

#15596 [JUJU-3713] Changestream terms
  cmd/jujud/agent/machine/manifolds.go
  core/changestream/change.go
  worker/changestream/doc.go
  worker/changestream/eventmultiplexer/benchmarks_test.go
  worker/changestream/eventmultiplexer/change_mock_test.go
  worker/changestream/eventmultiplexer/clock_mock_test.go
  worker/changestream/eventmultiplexer/eventmultiplexer.go
  worker/changestream/eventmultiplexer/eventmultiplexer_test.go
  worker/changestream/eventmultiplexer/logger_mock_test.go
  worker/changestream/eventmultiplexer/package_test.go
  worker/changestream/eventmultiplexer/stream_mock_test.go
  worker/changestream/eventmultiplexer/subscription.go
  worker/changestream/eventmultiplexer/subscription_test.go
  worker/changestream/eventqueue/change_mock_test.go
  worker/changestream/eventqueue/eventqueue.go
  worker/changestream/eventqueue/eventqueue_test.go
  worker/changestream/eventqueue/package_test.go
  worker/changestream/manifold.go
  worker/changestream/manifold_test.go
  worker/changestream/package_test.go
  worker/changestream/stream/package_test.go
  worker/changestream/stream/stream.go
  worker/changestream/stream/stream_test.go
  worker/changestream/stream_mock_test.go
  worker/changestream/worker.go
  worker/changestream/worker_test.go
Labels: 4.0

#15650 [JUJU-3830] Use juju-qa-test rather than postgres
  tests/suites/machine/machine.sh
Labels: 2.9

#15644 Merge 3.3 into main
  api/client/application/client.go
  api/client/application/client_test.go
  api/client/charms/client.go
  api/client/charms/client_test.go
  apiserver/facades/client/application/application.go
  apiserver/facades/client/charms/client.go
  apiserver/facades/schema.json
  cmd/juju/application/deploy.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/bundle.go
  cmd/juju/application/deployer/charm.go
  cmd/juju/application/deployer/charm_test.go
  cmd/juju/application/deployer/deployer.go
  cmd/juju/application/deployer/deployer_test.go
  cmd/juju/application/deployer/interface.go
  cmd/juju/application/deployer/lxdprofile.go
  cmd/juju/application/deployer/lxdprofilestep.go
  cmd/juju/application/deployer/lxdprofilestep_test.go
  cmd/juju/application/deployer/mocks/deploy_mock.go
  cmd/juju/application/deployer/package_test.go
  cmd/juju/application/deployer/steps.go
  scripts/discourse-sync/requirements.txt
Labels: 4.0

#15645 Merge 3.1 into 3.2
  .github/workflows/migrate.yml
  apiserver/facades/agent/secretsmanager/secrets.go
  apiserver/facades/agent/secretsmanager/secrets_test.go
Labels: 3.2

#15648 [JUJU-3793] Add single entity base NotifyWatcher
  core/watcher/eventqueue/key.go
  core/watcher/eventqueue/key_test.go
  core/watcher/eventqueue/keys_test.go
  core/watcher/eventqueue/package_test.go
Labels: 4.0

#15633 [JUJU-3821] Fixed test-deploy-aks-charms
  tests/suites/deploy_aks/deploy_aks.sh
Labels: 2.9

#15330 [JUJU-3790] Remove unused agent API methods
  api/agent/agent/machine_test.go
  api/agent/agent/state.go
Labels: 4.0

#15647 [JUJU-3834] Added controller config schema
  domain/schema/controller.go
  domain/schema/controller_test.go
Labels: 4.0

#15656 Increment juju to 3.2.0
  scripts/win-installer/setup.iss
  snap/snapcraft.yaml
  version/version.go
Labels: 3.2

#15661 Fix data race in GetOSFromSeries
  core/series/supportedseries.go
Labels: 2.9

#15662 Fix relation departing test waiting.
  testcharms/charms/departer/metadata.yaml
  tests/suites/relations/relation_departing_unit.sh
Labels: 2.9

#15658 [JUJU-3847] Add sqlair package
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/agent/machine/manifolds_test.go
  core/database/trackeddb.go
  core/watcher/eventqueue/interface.go
  core/watcher/eventqueue/keys.go
  core/watcher/eventqueue/keys_test.go
  database/testing/fullsuite.go
  database/testing/simplesuite.go
  database/testing/trackeddb.go
  database/txn.go
  database/txn/transaction.go
  database/txn/transaction_test.go
  domain/externalcontroller/state/state.go
  domain/modelmanager/state/state.go
  go.mod
  go.sum
  provider/dummy/environs.go
  worker/changestream/stream/stream.go
  worker/dbaccessor/package_mock_test.go
  worker/dbaccessor/package_test.go
  worker/dbaccessor/tracker.go
  worker/dbaccessor/tracker_test.go
  worker/dbaccessor/worker.go
  worker/dbaccessor/worker_integration_test.go
  worker/dbaccessor/worker_test.go
  worker/lease/manifold/database_mock_test.go
  worker/lease/store.go
  worker/leaseexpiry/worker.go
Labels: feature, 4.0

#15666 [JUJU-3850] Limit Txn concurrency
  database/txn/errors.go
  database/txn/transaction.go
  database/txn/transaction_test.go
Labels: feature, 4.0

#15670 [JUJU-3867] Remove JujuConnSuite from api tests
  api/agent/deployer/deployer.go
  api/agent/deployer/deployer_test.go
  api/agent/deployer/machine.go
  api/agent/deployer/unit.go
  api/agent/logger/logger.go
  api/agent/logger/logger_test.go
  api/agent/logger/package_test.go
  api/agent/metricsadder/client_test.go
  api/agent/metricsadder/export_test.go
  api/agent/metricsadder/package_test.go
  api/client/metricsdebug/client_test.go
  api/client/metricsdebug/package_test.go
  api/controller/metricsmanager/client_test.go
  api/controller/metricsmanager/export_test.go
  api/controller/metricsmanager/package_test.go
  featuretests/api_logger_test.go
  worker/deployer/deployer_test.go
  worker/deployer/export_test.go
  worker/deployer/manifold.go
  worker/logger/manifold.go
Labels: 4.0

#15542 Apply LXD Project before validating profiles
  apiserver/facades/client/modelupgrader/upgrader_test.go
  migration/precheck_test.go
  provider/lxd/credentials.go
  provider/lxd/credentials_test.go
  provider/lxd/environ.go
  provider/lxd/environ_test.go
  provider/lxd/package_mock_test.go
  provider/lxd/server.go
  provider/lxd/server_integration_test.go
  upgrades/upgradevalidation/migrate_test.go
  upgrades/upgradevalidation/mocks/lxd_mock.go
  upgrades/upgradevalidation/upgrade_test.go
  upgrades/upgradevalidation/validation.go
  upgrades/upgradevalidation/validation_test.go
Labels: bug, 3.1

#15672 Bump juju/description/v3 to v3.0.15
  go.mod
  go.sum
  state/migration_import_test.go
  state/mocks/description_mock.go
Labels: 2.9

#15655 [JUJU-3783] Modify KeysWatcher to accept change type
  core/changestream/subscription.go
  core/watcher/eventsource/keys.go
  core/watcher/eventsource/keys_test.go
Labels: 4.0

#15682 [JUJU-3782] Replace external controller save method with new domain
  apiserver/facades/controller/externalcontrollerupdater/domain_mock_test.go
  apiserver/facades/controller/externalcontrollerupdater/externalcontrollerupdater.go
  apiserver/facades/controller/externalcontrollerupdater/externalcontrollerupdater_test.go
  apiserver/facades/controller/externalcontrollerupdater/package_test.go
  apiserver/facades/controller/externalcontrollerupdater/register.go
Labels: 4.0
