Repository juju/juju, pull requests merged in 2023-07, with the labels that each got.

#15840 Unwind jujud
  agent/addons/addons.go
  agent/addons/addons_test.go
  agent/agentbootstrap/bootstrap.go
  agent/config/agentconfig.go
  agent/config/agentconfig_test.go
  agent/config/config.go
  agent/config/package_test.go
  agent/errors/errors.go
  agent/errors/errors_test.go
  agent/errors/package_test.go
  agent/introspect/introspect.go
  agent/introspect/introspect_test.go
  agent/introspect/package_test.go
  api/agent/agent/state.go
  cmd/containeragent/main_nix.go
  cmd/containeragent/unit/agent.go
  cmd/containeragent/unit/agent_test.go
  cmd/containeragent/unit/export_test.go
  cmd/internal/agent/agentconf/agentconf.go
  cmd/internal/run/package_test.go
  cmd/internal/run/run.go
  cmd/internal/run/run_test.go
  cmd/jujud/agent/agent_test.go
  cmd/jujud/agent/agentconf/agentconf.go
  cmd/jujud/agent/agentconf/export_test.go
  cmd/jujud/agent/bootstrap.go
  cmd/jujud/agent/caasoperator.go
  cmd/jujud/agent/caasoperator_test.go
  cmd/jujud/agent/caasunitinit.go
  cmd/jujud/agent/checkconnection.go
  cmd/jujud/agent/checkconnection_test.go
  cmd/jujud/agent/engine/config.go
  cmd/jujud/agent/machine.go
  cmd/jujud/agent/machine_test.go
  cmd/jujud/agent/model.go
  cmd/jujud/agent/util_test.go
  cmd/jujud/dumplogs/dumplogs.go
  cmd/jujud/main.go
  cmd/jujud/util/util.go
  cmd/package_test.go
  core/agent/tag.go
  environs/testing/tools.go
  worker/agentconfigupdater/manifold.go
  worker/caasoperator/initializer.go
  worker/caasupgrader/upgrader.go
  worker/deployer/nested.go
  worker/deployer/nested_test.go
  worker/identityfilewriter/manifold.go
  worker/lease/secretaries.go
  worker/stateconfigwatcher/manifold.go
  worker/stateconverter/converter.go
  worker/uniter/runlistener.go
  worker/upgrader/upgrader.go
  worker/upgrader/upgrader_test.go
  worker/upgradesteps/worker.go
  worker/upgradesteps/worker_test.go
Labels: 4.0

#15833 [JUJU-4097] Lease migration import
  apiserver/facades/controller/migrationtarget/migrationtarget.go
  apiserver/facades/controller/migrationtarget/migrationtarget_test.go
  core/modelmigration/coordinator.go
  core/modelmigration/coordinator_test.go
  domain/lease/modelmigration/database_mock_test.go
  domain/lease/modelmigration/import.go
  domain/lease/modelmigration/import_test.go
  domain/lease/modelmigration/migrations_mock_test.go
  domain/lease/modelmigration/package_test.go
  domain/modelmigration/import.go
  domain/state.go
  migration/migration.go
  migration/migration_test.go
Labels: 4.0

#15849 [JUJU-3878] - Fix/update secret backend
  apiserver/facades/client/secretbackends/secrets.go
  secrets/provider/vault/config.go
  secrets/provider/vault/config_test.go
  state/migration_import_test.go
  state/secretbackends.go
  state/secretbackends_test.go
Labels: 3.1

#15819 [JUJU-4012] Watcher registry logger
  apiserver/root.go
  core/logger/labels.go
  core/watcher/registry/logger_mock_test.go
  core/watcher/registry/package_test.go
  core/watcher/registry/registry.go
  core/watcher/registry/registry_test.go
Labels: 4.0

#15788 [JUJU-4055] Add upgrade info methods
  domain/upgrade/service/package_mock_test.go
  domain/upgrade/service/package_test.go
  domain/upgrade/service/service.go
  domain/upgrade/service/service_test.go
  domain/upgrade/state/package_test.go
  domain/upgrade/state/state.go
  domain/upgrade/state/state_test.go
  domain/upgrade/state/types.go
Labels: 4.0

#15862 Add more logging to help diagnose upgrade issue
  tests/suites/upgrade/streams.sh
Labels: 3.2

#15860 No action in ensureRoleBinding if no change needs to be made;
  caas/kubernetes/provider/k8s_test.go
  caas/kubernetes/provider/operator_test.go
  caas/kubernetes/provider/package_test.go
  caas/kubernetes/provider/rbac.go
  caas/kubernetes/provider/rbac_test.go
Labels: 2.9

#15825 [JUJU-4103] Disallow ubuntu prior to focal from being deployed in bundles
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/bundlehandler_test.go
Labels: 3.1

#15826 [JUJU-4114] Cloud and Region model defaults to dqlite.
  database/statement_test.go
  domain/cloud/service/service.go
  domain/cloud/service/service_test.go
  domain/cloud/state/state.go
  domain/cloud/state/state_test.go
  domain/errors.go
  domain/modelconfig/service/interface.go
  domain/modelconfig/service/package_mock_test.go
  domain/modelconfig/service/package_test.go
  domain/modelconfig/service/service.go
  domain/modelconfig/service/service_test.go
  domain/schema/controller.go
  domain/schema/schema_test.go
Labels: 4.0

#15727 [JUJU-3969] Allow upgrades without specifying version
  api/controller/migrationmaster/client.go
  api/controller/migrationmaster/client_test.go
  apiserver/facades/client/controller/controller.go
  apiserver/facades/controller/migrationmaster/facade.go
  migration/interface.go
  migration/precheck.go
  migration/precheck_test.go
  upgrades/upgradevalidation/migrate.go
  upgrades/upgradevalidation/migrate_test.go
  upgrades/upgradevalidation/upgrade.go
  upgrades/upgradevalidation/validation_test.go
  upgrades/upgradevalidation/version.go
  upgrades/upgradevalidation/version_test.go
  worker/migrationmaster/worker.go
  worker/migrationmaster/worker_test.go
Labels: 3.1

#15899 [JUJU-4141] Bump dqlite v1.15.1
  api/client/client/client.go
  container/lxd/certificate.go
  container/lxd/connection.go
  container/lxd/container.go
  container/lxd/container_test.go
  container/lxd/export_test.go
  container/lxd/image.go
  container/lxd/image_test.go
  container/lxd/initialisation_test.go
  container/lxd/instance.go
  container/lxd/logger.go
  container/lxd/manager.go
  container/lxd/manager_test.go
  container/lxd/network.go
  container/lxd/network_test.go
  container/lxd/server.go
  container/lxd/server_test.go
  container/lxd/storage.go
  container/lxd/storage_test.go
  container/lxd/testing/lxd_mock.go
  container/lxd/testing/package_test.go
  container/lxd/testing/suite.go
  core/instance/virttype.go
  core/instance/virttype_test.go
  go.mod
  go.sum
  provider/lxd/credentials.go
  provider/lxd/credentials_test.go
  provider/lxd/environ.go
  provider/lxd/environ_broker_test.go
  provider/lxd/environ_network.go
  provider/lxd/environ_network_test.go
  provider/lxd/environ_policy_test.go
  provider/lxd/environ_test.go
  provider/lxd/instance.go
  provider/lxd/package_mock_test.go
  provider/lxd/server.go
  provider/lxd/server_integration_test.go
  provider/lxd/storage.go
  provider/lxd/storage_test.go
  provider/lxd/testing_test.go
  scripts/dqlite/scripts/env.sh
  upgrades/upgradevalidation/mocks/lxd_mock.go
Labels: 4.0

#15902 [JUJU-4141] Bump musl 1.2.3 to 1.2.4
  scripts/dqlite/scripts/musl/musl-install.sh
  snap/snapcraft.yaml
Labels: 4.0

#15900 [JUJU-4141] Bump sqlair to the latest version
  go.mod
  go.sum
Labels: 4.0

#15903 [JUJU-4141] Fix dqlite deps to pre-compiled versions
  scripts/dqlite/scripts/dqlite/dqlite-install.sh
Labels: 4.0

#15794 [JUJU-4093] Schema manager for applying DDL upgrades.
  core/database/schema/doc.go
  core/database/schema/package_test.go
  core/database/schema/query.go
  core/database/schema/query_test.go
  core/database/schema/schema.go
  core/database/schema/schema_test.go
  core/database/schema/tx_mock_test.go
Labels: 4.0

#15838 [JUJU-3785] Implement external controller migrations in new domain
  apiserver/facades/controller/externalcontrollerupdater/domain_mock_test.go
  apiserver/facades/controller/externalcontrollerupdater/externalcontrollerupdater.go
  core/crossmodel/externalcontroller.go
  domain/externalcontroller/modelmigration/export.go
  domain/externalcontroller/modelmigration/export_test.go
  domain/externalcontroller/modelmigration/import.go
  domain/externalcontroller/modelmigration/import_test.go
  domain/externalcontroller/modelmigration/migrations_mock_test.go
  domain/externalcontroller/modelmigration/package_test.go
  domain/externalcontroller/service/service.go
  domain/externalcontroller/service/service_test.go
  domain/externalcontroller/service/state_mock_test.go
  domain/externalcontroller/state/state.go
  domain/externalcontroller/state/state_test.go
  domain/externalcontroller/state/types.go
  domain/modelmigration/export.go
  domain/modelmigration/import.go
  state/migration_import.go
  state/migration_import_input_mock_test.go
  state/migration_import_tasks.go
  state/migration_import_tasks_test.go
  state/migration_import_test.go
  state/package_test.go
Labels: 4.0

#15915 [JUJU-4136] - User secret add
  .github/discourse-topic-ids.yaml
  api/client/secrets/client.go
  api/client/secrets/client_test.go
  api/facadeversions.go
  apiserver/facades/client/secrets/mocks/secretsstate.go
  apiserver/facades/client/secrets/register.go
  apiserver/facades/client/secrets/secrets.go
  apiserver/facades/client/secrets/secrets_test.go
  apiserver/facades/client/secrets/state.go
  apiserver/facades/schema.json
  cmd/juju/commands/main.go
  cmd/juju/commands/main_test.go
  cmd/juju/secrets/add.go
  cmd/juju/secrets/add_test.go
  cmd/juju/secrets/common.go
  cmd/juju/secrets/mocks/secretsapi.go
  cmd/juju/secrets/package_test.go
  state/secrets.go
  state/secrets_test.go
  worker/uniter/runner/jujuc/secret-add.go
Labels: 3.3

#15925 More forgiving retry for AWS calls.
  provider/ec2/environ.go
Labels: 3.1

#15916 [JUJU-4048] Remove GetChanges & series from GetChangesMapArgs
  api/client/bundle/client.go
  api/client/bundle/client_test.go
  api/facadeversions.go
  apiserver/facades/client/bundle/bundle.go
  apiserver/facades/client/bundle/bundle_test.go
  apiserver/facades/client/bundle/register.go
  apiserver/facades/schema.json
  apiserver/restrict_controller_test.go
  core/bundle/changes/changes.go
  core/bundle/changes/changes_test.go
  rpc/params/params.go
Labels: 4.0

#15929 Wire up the database/schema
  agent/agentbootstrap/bootstrap_test.go
  core/database/delta.go
  core/database/schema/package_test.go
  core/database/schema/query_test.go
  core/database/schema/schema.go
  core/database/schema/schema_test.go
  core/watcher/eventsource/namespace_test.go
  core/watcher/eventsource/package_test.go
  core/watcher/eventsource/value_test.go
  database/bootstrap.go
  database/migration.go
  database/migration_test.go
  database/pragma/pragma.go
  database/statement.go
  database/statement_test.go
  database/testing/dqlitesuite.go
  database/testing/fullsuite.go
  database/testing/simplesuite.go
  database/txn/transaction_test.go
  domain/cloud/state/state.go
  domain/cloud/state/state_test.go
  domain/controllerconfig/bootstrap/bootstrap.go
  domain/controllerconfig/bootstrap/bootstrap_test.go
  domain/controllerconfig/controllerconfig_test.go
  domain/controllerconfig/state/state_test.go
  domain/controllernode/state/state_test.go
  domain/externalcontroller/state/state_test.go
  domain/lease/state/state_test.go
  domain/modelmanager/state/state_test.go
  domain/schema/changelog.go
  domain/schema/controller.go
  domain/schema/model.go
  domain/schema/schema_test.go
  domain/schema/testing/controllersuite.go
  domain/schema/testing/modelsuite.go
  domain/schema/testing/schema.go
  domain/state_test.go
  domain/upgrade/state/state.go
  domain/upgrade/state/state_test.go
  domain/watcher_test.go
  juju/testing/apiserver.go
  migration/migration_test.go
  provider/dummy/environs.go
  worker/changestream/eventmultiplexer/package_test.go
  worker/changestream/package_test.go
  worker/changestream/stream/package_test.go
  worker/changestreampruner/package_test.go
  worker/changestreampruner/worker_test.go
  worker/dbaccessor/package_test.go
  worker/dbaccessor/tracker.go
  worker/dbaccessor/tracker_test.go
  worker/dbaccessor/worker_integration_test.go
  worker/leaseexpiry/manifold_test.go
  worker/leaseexpiry/worker_test.go
Labels: 4.0

#15924 Update lxd documentation links.
  cmd/juju/cloud/list.go
  container/lxd/server.go
  provider/lxd/environ.go
  provider/lxd/environ_test.go
  provider/lxd/server.go
Labels: 2.9

#15841 Fix version flag change
  cmd/juju/commands/main.go
  cmd/juju/commands/main_test.go
Labels: 3.1

#15945 [JUJU-4125] Move convinient factory methods for TxRunner and WatchableDB to core
  apiserver/facades/client/highavailability/register.go
  apiserver/facades/client/modelmanager/register.go
  apiserver/facades/controller/externalcontrollerupdater/register.go
  apiserver/facades/controller/migrationtarget/migrationtarget.go
  core/changestream/eventsource.go
  core/changestream/eventsource_test.go
  core/changestream/package_test.go
  core/database/runner.go
  core/modelmigration/coordinator.go
  core/modelmigration/coordinator_test.go
  domain/cloud/state/state.go
  domain/controllerconfig/state/state.go
  domain/controllernode/state/state.go
  domain/externalcontroller/modelmigration/export.go
  domain/externalcontroller/modelmigration/import.go
  domain/externalcontroller/state/state.go
  domain/lease/modelmigration/import.go
  domain/lease/state/state.go
  domain/modelmanager/state/state.go
  domain/state.go
  domain/state_test.go
  domain/upgrade/state/state.go
  migration/migration_test.go
  worker/dbaccessor/worker.go
  worker/lease/manifold.go
  worker/leaseexpiry/manifold.go
Labels: 4.0

#15868 [JUJU-4164] Revisit wait-for command errors
  cmd/juju/waitfor/application.go
  cmd/juju/waitfor/application_test.go
  cmd/juju/waitfor/errors.go
  cmd/juju/waitfor/machine.go
  cmd/juju/waitfor/machine_test.go
  cmd/juju/waitfor/model.go
  cmd/juju/waitfor/model_test.go
  cmd/juju/waitfor/query/box.go
  cmd/juju/waitfor/query/errors.go
  cmd/juju/waitfor/query/lexer.go
  cmd/juju/waitfor/query/lexer_test.go
  cmd/juju/waitfor/query/parser.go
  cmd/juju/waitfor/query/parser_test.go
  cmd/juju/waitfor/query/query.go
  cmd/juju/waitfor/query/query_test.go
  cmd/juju/waitfor/query/scope.go
  cmd/juju/waitfor/query/token.go
  cmd/juju/waitfor/strategy.go
  cmd/juju/waitfor/strategy_test.go
  cmd/juju/waitfor/unit.go
  cmd/juju/waitfor/unit_test.go
  cmd/juju/waitfor/waitfor.go
  cmd/juju/waitfor/waitforbase.go
Labels: 3.1

#15953 [JUJU-4275] Backport the setting of foreign keys via pragma
  database/bootstrap.go
  database/pragma/pragma.go
  worker/dbaccessor/manifold.go
  worker/dbaccessor/manifold_test.go
  worker/dbaccessor/tracker.go
  worker/dbaccessor/tracker_test.go
  worker/dbaccessor/worker.go
  worker/dbaccessor/worker_test.go
Labels: 3.1

#15965 [JUJU-4277] Throw an error in potential Dqlite backstop scenarios when conditions not met
  worker/dbaccessor/worker.go
  worker/dbaccessor/worker_test.go
Labels: 3.2

#15967 [JUJU-4306] Fix migration check
  .github/workflows/migrate.yml
  cmd/juju/waitfor/application.go
  cmd/juju/waitfor/application_test.go
  cmd/juju/waitfor/model.go
Labels: 3.1

#15966 [JUJU-4305] Inject ctrlConfigService in client/controller facade
  apiserver/facades/client/controller/controller.go
  apiserver/facades/client/controller/controller_test.go
  apiserver/facades/client/controller/export_test.go
  apiserver/facades/client/controller/mocks/domain_mock.go
  apiserver/facades/client/controller/package_test.go
  apiserver/facades/client/controller/register.go
Labels: 4.0

#15927 [JUJU-4125] Add export methods to model migration using coordinator
  apiserver/facades/client/modelmanager/listmodelsummaries_test.go
  apiserver/facades/client/modelmanager/mocks/migrator_mock.go
  apiserver/facades/client/modelmanager/modelinfo_test.go
  apiserver/facades/client/modelmanager/modelmanager.go
  apiserver/facades/client/modelmanager/modelmanager_test.go
  apiserver/facades/client/modelmanager/package_test.go
  apiserver/facades/client/modelmanager/register.go
  apiserver/facades/controller/migrationmaster/backend.go
  apiserver/facades/controller/migrationmaster/facade.go
  apiserver/facades/controller/migrationmaster/facade_test.go
  apiserver/facades/controller/migrationmaster/mocks/backend.go
  apiserver/facades/controller/migrationmaster/package_test.go
  apiserver/facades/controller/migrationmaster/register.go
  apiserver/facades/controller/migrationtarget/migrationtarget.go
  domain/modelmigration/export.go
  migration/migration.go
  migration/migration_test.go
Labels: 4.0

#15848 [JUJU-4135] Rootless Juju controller on Kubernetes
  caas/Dockerfile
  caas/application.go
  caas/kubernetes/provider/application/application.go
  caas/kubernetes/provider/application/application_test.go
  caas/kubernetes/provider/bootstrap.go
  caas/kubernetes/provider/bootstrap_test.go
  caas/kubernetes/provider/constants/constants.go
  caas/scripts.go
  cmd/containeragent/initialize/command.go
  cmd/containeragent/initialize/command_test.go
  cmd/containeragent/initialize/package_test.go
  cmd/containeragent/main_nix.go
  cmd/jujud/agent/caasoperator.go
  cmd/jujud/agent/machine.go
  worker/introspection/script.go
Labels: 3.3

#15961 [JUJU-4300] Ensure LXD proxy values are updated after lxd init has finished
  container/lxd/initialisation_linux.go
  container/lxd/initialisation_test.go
Labels: 3.2

#15988 Revert early unlock of mutex when starting DB tracker workers
  worker/dbaccessor/worker.go
Labels: 3.2

#15993 [JUJU-4322] Remove JujuConnSuite from remaining uniter worker tests
  api/agent/uniter/export_test.go
  api/agent/uniter/relationunit.go
  api/agent/uniter/settings.go
  api/client/charms/downloader.go
  core/network/portrange.go
  worker/uniter/charm/bundles.go
  worker/uniter/charm/bundles_test.go
  worker/uniter/charm/package_test.go
  worker/uniter/runner/context/context_test.go
  worker/uniter/runner/context/contextfactory_test.go
  worker/uniter/runner/context/export_test.go
  worker/uniter/runner/context/flush_test.go
  worker/uniter/runner/context/package_test.go
  worker/uniter/runner/context/relation_test.go
  worker/uniter/runner/context/storage_test.go
  worker/uniter/runner/context/unitStorage_test.go
  worker/uniter/runner/context/util_test.go
  worker/uniter/runner/export_test.go
  worker/uniter/runner/factory_test.go
  worker/uniter/runner/package_test.go
  worker/uniter/runner/runner_test.go
  worker/uniter/runner/util_test.go
  worker/uniter/upgradeseries/package_test.go
  worker/uniter/verifycharmprofile/package_test.go
Labels: 4.0

#15940 [JUJU-4126] Add UpdateExternalControllerModel and replace the usages of SaveAndMoveModels on facades
  apiserver/facades/controller/remoterelations/interface.go
  apiserver/facades/controller/remoterelations/mocks/remoterelations_mocks.go
  apiserver/facades/controller/remoterelations/package_test.go
  apiserver/facades/controller/remoterelations/register.go
  apiserver/facades/controller/remoterelations/remoterelations.go
  apiserver/facades/controller/remoterelations/remoterelations_test.go
Labels: 4.0

#16003 Output controller and model logs to archive
  tests/includes/juju.sh
  tests/includes/pids.sh
  tests/main.sh
  tests/suites/ck/ck.sh
  tests/suites/secrets_iaas/cmr.sh
  tests/suites/secrets_iaas/juju.sh
  tests/suites/secrets_iaas/vault.sh
Labels: 4.0

#15972 [JUJU-4099] Enforce single active upgrade
  domain/schema/controller.go
  domain/upgrade/service/package_mock_test.go
  domain/upgrade/service/service.go
  domain/upgrade/service/service_test.go
  domain/upgrade/state/state.go
  domain/upgrade/state/state_test.go
Labels: 4.0

#15817 [JUJU-4012] Wire up watcher registry secrets
  apiserver/allfacades.go
  apiserver/facades/agent/secretsdrain/package_test.go
  apiserver/facades/agent/secretsdrain/register.go
  apiserver/facades/agent/secretsdrain/secrets.go
  apiserver/facades/agent/secretsdrain/secrets_test.go
  apiserver/facades/agent/secretsmanager/package_test.go
  apiserver/facades/agent/secretsmanager/register.go
  apiserver/facades/agent/secretsmanager/secrets.go
  apiserver/facades/agent/secretsmanager/secrets_test.go
  apiserver/facades/client/controller/controller_test.go
  apiserver/facades/client/secretbackends/register.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations.go
  apiserver/facades/controller/secretbackendmanager/backends.go
  apiserver/facades/controller/secretbackendmanager/backends_test.go
  apiserver/facades/controller/secretbackendmanager/package_test.go
  apiserver/facades/controller/secretbackendmanager/register.go
  apiserver/facades/schema.json
  apiserver/internal/watcher.go
  apiserver/internal/watcher_mock_test.go
  apiserver/internal/watcher_test.go
  apiserver/watcher.go
  apiserver/watcher_test.go
  core/watcher/registry/registry.go
  generate/schemagen/schemagen.go
  go.mod
  go.sum
Labels: 4.0

#16009 Remove controller port api worker
  cmd/jujud/agent/bootstrap.go
  cmd/jujud/agent/bootstrap_test.go
  cmd/jujud/agent/machine.go
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/agent/machine/manifolds_test.go
  controller/config.go
  worker/controllerport/manifold.go
  worker/controllerport/manifold_test.go
  worker/controllerport/package_test.go
  worker/controllerport/worker.go
  worker/controllerport/worker_test.go
  worker/httpserverargs/manifold.go
  worker/httpserverargs/manifold_test.go
  worker/peergrouper/manifold.go
  worker/peergrouper/manifold_test.go
Labels: 4.0

#16011 Skip schema facade generation when builing image
  Makefile
Labels: 4.0

#16012 Fix intermittent mongo test failure around dates
  mongo/mongo_test.go
Labels: 3.2

#16010 [JUJU-4352] Use gc.TestingT(t) instead of testing.MgoTestPackage(t) where relevant
  agent/package_test.go
  api/agent/meterstatus/package_test.go
  api/agent/proxyupdater/package_test.go
  api/agent/uniter/package_test.go
  api/client/spaces/package_test.go
  api/controller/charmrevisionupdater/package_test.go
  api/controller/controller/controller_test.go
  api/controller/controller/legacy_test.go
  api/controller/controller/package_test.go
  cmd/containeragent/unit/manifolds.go
  cmd/juju/dashboard/package_test.go
  cmd/jujud/agent/controllercharm.go
  cmd/jujud/agent/machine.go
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/agent/util_test.go
  cmd/modelcmd/modelcommand_test.go
  cmd/modelcmd/package_test.go
  container/broker/package_test.go
  core/workerpool/package_test.go
  environs/cloudspec/package_test.go
  environs/manual/sshprovisioner/package_test.go
  environs/package_test.go
  generate/schemagen/gen/package_test.go
  juju/sockets/package_test.go
  migration/migration.go
  migration/migration_test.go
  migration/package_test.go
  network/package_test.go
  storage/poolmanager/interface.go
  storage/poolmanager/package_test.go
  storage/poolmanager/poolmanager.go
  storage/poolmanager/poolmanager_test.go
  upgrades/preupgradesteps.go
  upgrades/preupgradesteps_test.go
  worker/charmdownloader/package_test.go
  worker/logger/package_test.go
  worker/multiwatcher/package_test.go
  worker/multiwatcher/worker_test.go
  worker/proxyupdater/package_test.go
  worker/upgradesteps/manifold.go
  worker/upgradesteps/package_test.go
  worker/upgradesteps/worker.go
  worker/upgradesteps/worker_test.go
Labels: 4.0

#16015 Output controller and model logs to archive
  tests/includes/juju.sh
  tests/includes/pids.sh
  tests/main.sh
  tests/suites/ck/ck.sh
  tests/suites/secrets_iaas/cmr.sh
  tests/suites/secrets_iaas/juju.sh
  tests/suites/secrets_iaas/vault.sh
Labels: 3.2

#16004 Sort controller names on error
  cmd/modelcmd/controller.go
Labels: 3.1

#16024 [JUJU-4368] Prevent raising error prematurely in ModifyModelAccess
  apiserver/facades/client/modelmanager/modelmanager.go
Labels: bug, 3.2
