Repository juju/juju, pull requests merged in 2023-04, with the labels that each got.

#15412 Bump to juju 3.3-beta1
  scripts/win-installer/setup.iss
  snap/snapcraft.yaml
  version/version.go
Labels: 3.3

#15403 [JUJU-3398] Scoped catacomb context
  go.mod
  go.sum
  worker/changestream/stream/stream.go
  worker/dbaccessor/worker.go
  worker/firewaller/firewaller.go
Labels: feature, failed to land, 3.3

#15413 Bump to 3.2-beta2
  scripts/win-installer/setup.iss
  snap/snapcraft.yaml
  version/version.go
Labels: 3.2

#15422 Merge 3.0 to 3.1
  cmd/juju/controller/destroy.go
  cmd/juju/machine/remove.go
  state/user.go
  tests/suites/branches/branches.sh
  tests/suites/resources/basic.sh
  tests/suites/resources/refresh.sh
  tests/suites/resources/task.sh
Labels: 3.1

#15416 [JUJU-3472] Lxd cert validation bug
  apiserver/facades/client/modelupgrader/upgrader_test.go
  migration/precheck_test.go
  provider/lxd/export_test.go
  provider/lxd/provider.go
  provider/lxd/server.go
  upgrades/upgradevalidation/migrate_test.go
  upgrades/upgradevalidation/upgrade_test.go
  upgrades/upgradevalidation/validation.go
  upgrades/upgradevalidation/validation_test.go
Labels: 2.9

#15423 [JUJU-3367] Fix refresh ci tests: use focal to deploy local charm.
  tests/suites/refresh/refresh.sh
Labels: 2.9

#15433 3.0 into 3.1
  apiserver/facades/client/modelupgrader/upgrader_test.go
  migration/precheck_test.go
  provider/lxd/export_test.go
  provider/lxd/provider.go
  provider/lxd/server.go
  upgrades/upgradevalidation/migrate_test.go
  upgrades/upgradevalidation/upgrade_test.go
  upgrades/upgradevalidation/validation.go
  upgrades/upgradevalidation/validation_test.go
Labels: 3.1

#15431 [JUJU-3364] Fix manual aws
  tests/suites/manual/deploy_manual_aws.sh
Labels: 2.9

#15436 Don't try and checkout musl cross make if it exists.
  scripts/dqlite/scripts/musl/musl-install.sh
Labels: 3.2

#15432 [JUJU-3426] Fix error message for deploying cs: charms on 3.1 controller with 3.0 client
  cmd/juju/application/deployer/charm.go
Labels: 3.0

#15452 Don't conflate ec2 with aws and gce with google in BOOTSTRAP_PROVIDER.
  tests/includes/juju.sh
  tests/suites/ck/overlay/ec2.yaml
  tests/suites/manual/task.sh
Labels: 2.9

#15450 Fix data race in openDatabase.
  worker/dbaccessor/worker.go
Labels: 3.2

#15429 [JUJU-3413] Refactor documentation of leftover commands
  cmd/juju/action/list.go
  cmd/juju/agree/agree/agree.go
  cmd/juju/application/addunit.go
  cmd/juju/application/bind.go
  cmd/juju/application/config.go
  cmd/juju/application/deploy.go
  cmd/juju/application/diffbundle.go
  cmd/juju/application/expose.go
  cmd/juju/application/integrate.go
  cmd/juju/backups/create.go
  cmd/juju/block/disable.go
  cmd/juju/caas/add.go
  cmd/juju/charmhub/info.go
  cmd/juju/cloud/add.go
  cmd/juju/cloud/addcredential.go
  cmd/juju/cloud/defaultregion.go
  cmd/juju/cloud/detectcredentials.go
  cmd/juju/cloud/list.go
  cmd/juju/cloud/listcredentials.go
  cmd/juju/commands/add_sshkeys.go
  cmd/juju/commands/bootstrap.go
  cmd/juju/commands/debuglog.go
  cmd/juju/commands/helptool.go
  cmd/juju/commands/helptool_test.go
  cmd/juju/commands/import_sshkeys.go
  cmd/juju/controller/addmodel.go
  cmd/juju/controller/config.go
  cmd/juju/controller/destroy.go
  cmd/juju/controller/listcontrollers.go
  cmd/juju/crossmodel/find.go
  cmd/juju/firewall/listrules.go
  cmd/juju/machine/add.go
  cmd/juju/model/destroy.go
  cmd/juju/model/grantrevoke.go
  cmd/juju/model/grantrevokecloud.go
  cmd/juju/resource/charmresources.go
  cmd/juju/resource/charmresources_test.go
  cmd/juju/secretbackends/add.go
  cmd/juju/space/add.go
  cmd/juju/space/reload.go
  cmd/juju/storage/add.go
  cmd/juju/storage/attach.go
  cmd/juju/storage/detach.go
  cmd/juju/storage/import.go
  cmd/juju/storage/poolcreate.go
  cmd/juju/storage/remove.go
  cmd/juju/user/add.go
  cmd/juju/user/change_password.go
  cmd/juju/user/disenable.go
  go.mod
  go.sum
Labels: 3.3

#15451 Update ppc64le prebuilt sha + Use juju/musl-cross-make.
  .github/workflows/build.yml
  .github/workflows/client-tests.yml
  .github/workflows/gen.yml
  .github/workflows/migrate.yml
  .github/workflows/snap.yml
  .github/workflows/upgrade.yml
  scripts/dqlite/scripts/dqlite/dqlite-build.sh
  scripts/dqlite/scripts/dqlite/dqlite-install.sh
  scripts/dqlite/scripts/musl/musl-install.sh
  snap/snapcraft.yaml
Labels: 3.2

#15460 [JUJU-3942] Replace ubuntu charm with tiny-bash in integration tests
  tests/suites/deploy/bundles/overlay_bundle.yaml
  tests/suites/deploy/bundles/telegraf_bundle.yaml
  tests/suites/deploy/bundles/telegraf_bundle_with_fake_revisions.yaml
  tests/suites/deploy/bundles/telegraf_bundle_without_revisions.yaml
  tests/suites/deploy/deploy_bundles.sh
Labels: 2.9

#15461 [JUJU-3352] Find oracle shapes values, rather than hardcode
  go.mod
  go.sum
  provider/oci/common/client.go
  provider/oci/common/errors.go
  provider/oci/common/errors_test.go
  provider/oci/common/interfaces.go
  provider/oci/common/ociclients.go
  provider/oci/common/ociclients_test.go
  provider/oci/common_test.go
  provider/oci/environ.go
  provider/oci/environ_test.go
  provider/oci/export_test.go
  provider/oci/images.go
  provider/oci/images_test.go
  provider/oci/instance.go
  provider/oci/instance_test.go
  provider/oci/interfaces.go
  provider/oci/networking.go
  provider/oci/networking_test.go
  provider/oci/provider.go
  provider/oci/shapespecs.go
  provider/oci/storage_volumes.go
  provider/oci/storage_volumes_test.go
  provider/oci/testing/mocks_clientcompute.go
  provider/oci/testing/mocks_clientnetworking.go
  provider/oci/testing/mocks_clientstorage.go
  provider/oci/testing/mocks_compute.go
  provider/oci/testing/mocks_firewall.go
  provider/oci/testing/mocks_identity.go
  provider/oci/testing/mocks_networking.go
  provider/oci/testing/mocks_storage.go
Labels: bug, 3.2

#15472 Add support for no-prompt to login/change-user-password.
  cmd/juju/user/change_password.go
  cmd/juju/user/change_password_test.go
  cmd/juju/user/login.go
  cmd/juju/user/login_test.go
  tests/suites/user/login_password.sh
Labels: 2.9

#15303 [JUJU-3298] Cloud schema
  database/schema/controller.go
Labels: feature, 3.3

#15471 Use recommended storage from ck overlay.
  tests/suites/ck/ck.sh
  tests/suites/ck/overlay.yaml
Labels: 2.9

#15485 [JUJU-3528] Fix db-accessor worker tests
  worker/dbaccessor/package_test.go
  worker/dbaccessor/worker.go
  worker/dbaccessor/worker_test.go
Labels: 3.2

#15486 [JUJU-3488] Dynamically configure expected interfaces for spaces_ec2
  tests/suites/spaces_ec2/juju_bind.sh
  tests/suites/spaces_ec2/upgrade_charm_with_bind.sh
  tests/suites/spaces_ec2/util.sh
Labels: 3.2

#15487 [JUJU-3488] Dynamically configure expected interfaces for spaces_ec2
  tests/suites/spaces_ec2/juju_bind.sh
  tests/suites/spaces_ec2/upgrade_charm_with_bind.sh
  tests/suites/spaces_ec2/util.sh
Labels: 2.9

#15482 [JUJU-3512] validate secret backend config when we change the secret backend in model config
  apiserver/facades/client/modelconfig/backend.go
  apiserver/facades/client/modelconfig/mocks/secretsprovider.go
  apiserver/facades/client/modelconfig/modelconfig.go
  apiserver/facades/client/modelconfig/modelconfig_test.go
  apiserver/facades/client/modelconfig/package_test.go
  environs/config/config.go
Labels: 3.1

#15483 [JUJU-3494] Upgrade cmd to v3.0.9
  cmd/juju/application/integrate.go
  cmd/juju/cloud/listcredentials.go
  cmd/juju/commands/version.go
  cmd/juju/controller/listmodels.go
  cmd/juju/crossmodel/offer.go
  cmd/juju/secretbackends/add.go
  cmd/juju/secretbackends/remove.go
  cmd/juju/secretbackends/show.go
  cmd/juju/secretbackends/update.go
  cmd/juju/status/status.go
  cmd/juju/user/add.go
  cmd/juju/user/remove.go
  go.mod
  go.sum
Labels: 3.3

#15425 [JUJU-3349] Resolve resources for DeployFromAPI
  apiserver/facades/client/application/deployrepository.go
  apiserver/facades/client/application/deployrepository_test.go
Labels: 3.3

#15474 [JUJU-3502] Slow query logging
  agent/agent.go
  agent/agent_test.go
  agent/agentbootstrap/bootstrap_test.go
  agent/format-2.0.go
  agent/format-2.0_whitebox_test.go
  cloudconfig/instancecfg/instancecfg.go
  cloudconfig/podcfg/podcfg.go
  cmd/containeragent/initialize/config.go
  cmd/jujud/agent/agenttest/agent.go
  cmd/jujud/agent/bootstrap.go
  controller/config.go
  controller/config_test.go
  controller/configschema.go
  database/app/dqlite_linux.go
  database/app/dqlite_other.go
  database/bootstrap.go
  database/bootstrap_test.go
  database/client/dqlite_other.go
  database/interface.go
  database/node.go
  database/node_test.go
  database/package_test.go
  environs/tools/build.go
  featuretests/dblog_test.go
  state/controller_test.go
  testing/environ.go
  tests/includes/juju.sh
  tests/main.sh
  tests/suites/controller/query_tracing.sh
  tests/suites/controller/task.sh
  worker/agentconfigupdater/manifold.go
  worker/agentconfigupdater/manifold_test.go
  worker/agentconfigupdater/worker.go
  worker/agentconfigupdater/worker_test.go
  worker/containerbroker/mocks/agent_mock.go
  worker/dbaccessor/package_mock_test.go
  worker/dbaccessor/worker.go
  worker/dbaccessor/worker_test.go
  worker/instancemutater/mocks/agent_mock.go
  worker/stateconverter/mocks/agent_mock.go
  worker/upgradedatabase/mocks/agent.go
Labels: feature, 3.2

#15496 [JUJU-3488] Rename expose_ec2 to firewall and add ssh_allow test
  tests/main.sh
  tests/suites/expose_ec2/task.sh
  tests/suites/firewall/bundle_with_exposed_endpoints.sh
  tests/suites/firewall/bundles/invalid.yaml
  tests/suites/firewall/expose_app.sh
  tests/suites/firewall/ssh_allow.sh
  tests/suites/firewall/task.sh
Labels: 3.2

#15497 [JUJU-3456] Fix returned error when yaml is invalid on diff-bundle
  cmd/juju/application/diffbundle.go
  cmd/juju/application/diffbundle_test.go
Labels: 2.9

#15501 [JUJU-3567] Add ci test for cmr secrets
  tests/suites/secrets_iaas/cmr.sh
  tests/suites/secrets_iaas/task.sh
Labels: failed to land, 3.2

#15505 [JUJU-3566] Fix panic when deploying bundle with placement directive to undefined machine
  cmd/juju/application/deployer/bundle.go
  cmd/juju/application/deployer/bundle_test.go
Labels: bug, 3.2

#15508 Update application offer migration import to fix LP 2016333.
  state/application.go
  state/migration_import_input_mock_test.go
  state/migration_import_tasks.go
  state/migration_import_tasks_test.go
Labels: bug, 2.9

#15504 [JUJU-3569] Fix secrets vault ci test
  tests/suites/secrets_iaas/juju.sh
  tests/suites/secrets_iaas/task.sh
  tests/suites/secrets_iaas/vault.sh
  tests/suites/secrets_k8s/k8s.sh
Labels: 3.1

#15503 Merge 3.1 20230419
  apiserver/facades/client/modelconfig/backend.go
  apiserver/facades/client/modelconfig/mocks/secretsprovider.go
  apiserver/facades/client/modelconfig/modelconfig.go
  apiserver/facades/client/modelconfig/modelconfig_test.go
  apiserver/facades/client/modelconfig/package_test.go
  environs/config/config.go
Labels: 3.2

#15500 [JUJU-3518] fix lp 1999640 local charm fails refresh
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/application_unit_test.go
Labels: bug, failed to land, 2.9

#15506 Merge 2.9 into 3.0
  cmd/juju/application/diffbundle.go
  cmd/juju/application/diffbundle_test.go
  provider/lxd/provider.go
  provider/lxd/provider_test.go
  provider/maas/environprovider.go
  provider/maas/environprovider_test.go
  provider/openstack/provider.go
  provider/openstack/provider_test.go
  tests/main.sh
  tests/suites/deploy_aks/task.sh
  tests/suites/expose_ec2/task.sh
  tests/suites/firewall/bundle_with_exposed_endpoints.sh
  tests/suites/firewall/bundles/invalid.yaml
  tests/suites/firewall/expose_app.sh
  tests/suites/firewall/task.sh
  tests/suites/spaces_ec2/juju_bind.sh
  tests/suites/spaces_ec2/upgrade_charm_with_bind.sh
  tests/suites/spaces_ec2/util.sh
Labels: 3.0

#15502 [JUJU-3568] Add podspec deprecation warning to CLI
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/charm.go
  cmd/juju/application/deployer/deployer.go
  cmd/juju/application/deployer/deployer_test.go
Labels: 3.2

#15512 Better default make target
  Makefile
Labels: 3.2

#15509 [JUJU-3474] describe validation of arguments to deploy a charm.
  apiserver/common/charms.go
  apiserver/common/charms_test.go
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/deploy.go
  apiserver/facades/client/application/deployrepository.go
Labels: 3.3

#15518 Merge 2.9 20230421
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/application_unit_test.go
  state/application.go
  state/migration_import_input_mock_test.go
  state/migration_import_tasks.go
  state/migration_import_tasks_test.go
Labels: 3.0

#15406 [JUJU-3209] Sync CLI docs to Discourse
  .github/discourse-topic-ids.yaml
  .github/workflows/docs.yml
  scripts/discourse-sync/README.md
  scripts/discourse-sync/main.py
  scripts/discourse-sync/requirements.txt
Labels: 3.3

#15520 Merge 3.0 20230421
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/application_unit_test.go
  cmd/juju/application/diffbundle.go
  cmd/juju/application/diffbundle_test.go
  provider/lxd/provider.go
  provider/lxd/provider_test.go
  provider/maas/environprovider.go
  provider/maas/environprovider_test.go
  provider/openstack/provider.go
  provider/openstack/provider_test.go
  state/application.go
  state/migration_import_input_mock_test.go
  state/migration_import_tasks.go
  state/migration_import_tasks_test.go
  tests/main.sh
  tests/suites/deploy_aks/task.sh
  tests/suites/expose_ec2/task.sh
  tests/suites/firewall/bundle_with_exposed_endpoints.sh
  tests/suites/firewall/bundles/invalid.yaml
  tests/suites/firewall/expose_app.sh
  tests/suites/firewall/task.sh
  tests/suites/spaces_ec2/juju_bind.sh
  tests/suites/spaces_ec2/upgrade_charm_with_bind.sh
  tests/suites/spaces_ec2/util.sh
Labels: 3.1

#15514 [JUJU-2874] Build jujud on macos
  Makefile
  scripts/dqlite/scripts/dqlite/dqlite-install.sh
  scripts/dqlite/scripts/env.sh
  scripts/dqlite/scripts/musl/install-if-missing.sh
  scripts/dqlite/scripts/musl/musl-install.sh
Labels: 3.2

#15522 [JUJU-3555] DB Accessor worker report
  database/client/dqlite_other.go
  database/dqlite/dqlite_other.go
  worker/dbaccessor/package_mock_test.go
  worker/dbaccessor/shim.go
  worker/dbaccessor/tracker.go
  worker/dbaccessor/tracker_test.go
  worker/dbaccessor/worker.go
  worker/dbaccessor/worker_test.go
Labels: 3.2

#15516 [JUJU-3475] Additional bits and pieces of deployfromrepository arg validation.
  apiserver/facades/client/application/deployrepository.go
  apiserver/facades/client/application/deployrepository_test.go
Labels: feature, 3.3

#15529 [JUJU-3505] AllWatcher additional attrs
  apiserver/watcher.go
  apiserver/watcher_internal_test.go
  environs/config/config.go
  rpc/params/multiwatcher.go
Labels: bug, 3.2

#15535 [JUJU-3614] Prevent panic on empty bundle contents
  cmd/juju/application/bundle/bundle.go
  cmd/juju/application/bundle/bundle_test.go
  cmd/juju/application/deployer/bundle.go
  cmd/juju/application/deployer/bundle_test.go
Labels: bug, 3.2

#15532 [JUJU-3612] External controller schema
  database/schema/controller.go
  database/schema/controller_test.go
  database/schema/package_test.go
Labels: feature, 3.3
