Repository juju/juju, pull requests merged in 2023-09, with the labels that each got.

#16122 ci(generate): print the full diff for debugging
  .github/workflows/gen.yml
Labels: 2.9, github_actions

#15969 Move almost all actions to self-hosted runners.
  .github/reg.yml
  .github/workflows/build.yml
  .github/workflows/client-tests.yml
  .github/workflows/gen.yml
  .github/workflows/license.yml
  .github/workflows/microk8s-tests.yml
  .github/workflows/smoke.yml
  .github/workflows/snap.yml
  .github/workflows/static-analysis.yml
  .github/workflows/upgrade.yml
  tests/README.md
  tests/includes/run.sh
  tests/suites/smoke/deploy.sh
  tests/suites/smoke/task.sh
  tests/suites/static_analysis/lint_go.sh
Labels: 2.9

#16190 Prevent filenotify watcher from bouncing the world
  worker/changestream/worker.go
  worker/filenotifywatcher/watcher.go
Labels: 4.0

#16189 Add a transaction runner factory on dqlite suite
  database/testing/dqlitesuite.go
  database/testing/runner.go
  domain/cloud/state/state_test.go
  domain/controllerconfig/service/controllerconfig_test.go
  domain/controllerconfig/state/state_test.go
  domain/controllernode/state/state_test.go
  domain/credential/state/state_test.go
  domain/externalcontroller/state/state_test.go
  domain/lease/state/state_test.go
  domain/modelmanager/state/state_test.go
  domain/state_test.go
  domain/upgrade/state/state_test.go
  go.mod
Labels: 4.0

#16191 Update to the latest worker package updates
  go.mod
  go.sum
Labels: 4.0

#16188 Rework domain/controllerconfig package
  apiserver/facades/agent/agent/agent.go
  apiserver/facades/client/controller/controller.go
  apiserver/facades/client/controller/controller_test.go
  apiserver/facades/client/controller/export_test.go
  apiserver/facades/client/controller/mocks/domain_mock.go
  apiserver/facades/client/controller/package_test.go
  controller/config_test.go
  controller/package_test.go
  controller/serialize.go
  controller/serialize_test.go
  domain/controllerconfig/bootstrap/bootstrap.go
  domain/controllerconfig/controllerconfig_test.go
  domain/controllerconfig/package_test.go
  domain/controllerconfig/service/controllerconfig_test.go
  domain/controllerconfig/service/package_mock_test.go
  domain/controllerconfig/service/service.go
  domain/controllerconfig/service/service_test.go
  domain/controllerconfig/state/state.go
  domain/controllerconfig/state/state_test.go
  domain/testing/controllerconfigsuite.go
Labels: 4.0

#16199 Watcher test harness
  core/watcher/eventsource/value.go
  core/watcher/eventsource/value_test.go
  core/watcher/watchertest/notify.go
  database/testing/dqlitesuite.go
  database/testing/runner.go
  database/testing/trackeddb.go
  domain/credential/state/state.go
  domain/credential/state/state_test.go
  internal/changestream/eventmultiplexer/benchmarks_test.go
  internal/changestream/eventmultiplexer/change_mock_test.go
  internal/changestream/eventmultiplexer/clock_mock_test.go
  internal/changestream/eventmultiplexer/eventmultiplexer.go
  internal/changestream/eventmultiplexer/eventmultiplexer_test.go
  internal/changestream/eventmultiplexer/logger_mock_test.go
  internal/changestream/eventmultiplexer/metrics_mock_test.go
  internal/changestream/eventmultiplexer/package_test.go
  internal/changestream/eventmultiplexer/stream_mock_test.go
  internal/changestream/eventmultiplexer/subscription.go
  internal/changestream/eventmultiplexer/subscription_test.go
  internal/changestream/stream/clock_mock_test.go
  internal/changestream/stream/logger_mock_test.go
  internal/changestream/stream/metrics_mock_test.go
  internal/changestream/stream/package_test.go
  internal/changestream/stream/stream.go
  internal/changestream/stream/stream_mock_test.go
  internal/changestream/stream/stream_test.go
  internal/changestream/testing/changestream.go
  internal/changestream/testing/controllersuite.go
  internal/changestream/testing/modelsuite.go
  worker/changestream/watchabledb.go
Labels: 4.0

#16201 Remove redundant expensive build jobs
  .github/workflows/build.yml
Labels: 4.0

#15878 Improve modelcmd error message
  cmd/juju/application/scaleapplication_test.go
  cmd/modelcmd/modelcommand.go
  cmd/modelcmd/modelcommand_test.go
Labels: 3.1

#16211 Fix undertaker restarting when parameters changed.
  go.mod
  go.sum
  worker/undertaker/credentialapi_mock_test.go
  worker/undertaker/facade_mock_test.go
  worker/undertaker/undertaker.go
  worker/undertaker/undertaker_test.go
Labels: 2.9

#16206 Ensure we subscribe inside the loop
  internal/changestream/eventmultiplexer/eventmultiplexer.go
  internal/changestream/eventmultiplexer/eventmultiplexer_test.go
  internal/changestream/eventmultiplexer/subscription.go
Labels: 4.0

#16197 [JUJU-4473] Add autocert cache schema for dqlite domain
  domain/schema/controller.go
  domain/schema/schema_test.go
Labels: 4.0

#15882 Add k8s target to scale-application entry in juju help commands
  cmd/juju/application/scaleapplication.go
Labels: 3.1

#16208 Ensure that calls to DeleteDB never return catacomb.ErrDying
  state/state_test.go
  worker/dbaccessor/worker.go
  worker/dbaccessor/worker_integration_test.go
Labels: 4.0

#16213 [JUJU-4474] Implement the state layer for the new autocert domain
  domain/autocert/state/package_test.go
  domain/autocert/state/state.go
  domain/autocert/state/state_test.go
  domain/schema/controller.go
Labels: 4.0

#16215 Add action notification model-uuid index
  state/allcollections.go
Labels: 2.9

#16207 Add additional stream tests
  internal/changestream/stream/stream.go
  internal/changestream/stream/stream_test.go
Labels: 4.0

#16196 Merge 3.1 to 3.2 with actions changes
  .github/reg.yml
  .github/verify-prometheus-k8s.sh
  .github/workflows/build.yml
  .github/workflows/client-tests.yml
  .github/workflows/gen.yml
  .github/workflows/license.yml
  .github/workflows/microk8s-tests.yml
  .github/workflows/migrate.yml
  .github/workflows/smoke.yml
  .github/workflows/snap.yml
  .github/workflows/static-analysis.yml
  .github/workflows/upgrade.yml
  agent/agent.go
  agent/format-2.0.go
  allowed_signers
  apiserver/common/modelstatus_test.go
  apiserver/facades/agent/agent/agent_test.go
  apiserver/facades/agent/agent/model_test.go
  apiserver/facades/agent/agent/register.go
  apiserver/facades/agent/caasadmission/register.go
  apiserver/facades/agent/caasagent/register.go
  apiserver/facades/agent/provisioner/provisioner.go
  apiserver/facades/agent/secretsmanager/register.go
  apiserver/facades/client/controller/controller.go
  apiserver/facades/client/controller/controller_test.go
  apiserver/facades/controller/caasmodelconfigmanager/register.go
  apiserver/facades/controller/firewaller/firewaller_base_test.go
  apiserver/facades/controller/firewaller/register.go
  cmd/containeragent/initialize/config.go
  cmd/juju/application/scaleapplication.go
  cmd/juju/application/scaleapplication_test.go
  cmd/jujud/agent/agenttest/agent.go
  cmd/modelcmd/modelcommand.go
  cmd/modelcmd/modelcommand_test.go
  database/node.go
  database/node_test.go
  go.mod
  go.sum
  provider/ec2/environ.go
  scripts/dqlite/scripts/musl/musl-install.sh
  scripts/try-merge/main.go
  state/state_test.go
  state/testing/watcher.go
  tests/README.md
  tests/suites/smoke/deploy.sh
  tests/suites/smoke/task.sh
  worker/containerbroker/mocks/agent_mock.go
  worker/instancemutater/mocks/agent_mock.go
  worker/stateconverter/mocks/agent_mock.go
  worker/uniter/runner/context/context.go
  worker/uniter/runner/context/context_test.go
  worker/upgradedatabase/mocks/agent.go
Labels: 3.2

#16113 Update PR template to include Jira card number
  PULL_REQUEST_TEMPLATE.md
Labels: 2.9

#16217 [JUJU-4475] Add autocert cache domain service
  domain/autocert/service/package_test.go
  domain/autocert/service/service.go
  domain/autocert/service/service_mock_test.go
  domain/autocert/service/service_test.go
  domain/autocert/state/state_test.go
  domain/externalcontroller/service/service.go
  domain/servicefactory/controller.go
  domain/servicefactory/testing/service.go
  state/autocertcache.go
  state/autocertcache_test.go
  worker/httpserver/cert_test.go
  worker/httpserver/manifold.go
  worker/httpserver/manifold_test.go
  worker/httpserver/tls.go
  worker/servicefactory/interface.go
  worker/servicefactory/manifold.go
  worker/servicefactory/servicefactory_mock_test.go
Labels: 4.0

#16205 Adds support for model metadata to the controller.
  database/txn/transaction.go
  domain/credential/credential.go
  domain/model/errors/errors.go
  domain/model/service/package_test.go
  domain/model/service/service.go
  domain/model/service/service_test.go
  domain/model/state/package_test.go
  domain/model/state/state.go
  domain/model/state/state_test.go
  domain/schema/controller.go
  domain/schema/schema_test.go
Labels: 4.0

#16140 Increase SSH timeouts
  cmd/juju/commands/ssh.go
Labels: 2.9

#16226 API Client only use windowed facades
  api/apiclient.go
  api/facadeversions.go
  api/facadeversions_test.go
  apiserver/facades/controller/raftlease/facade.go
  apiserver/facades/controller/raftlease/facade_test.go
  apiserver/facades/controller/raftlease/register.go
  apiserver/facades/schema.json
Labels: 3.1

#16233 Move wrench package to internal/wrench
  cmd/jujud/agent/machine.go
  internal/wrench/export_test.go
  internal/wrench/wrench.go
  internal/wrench/wrench_nix.go
  internal/wrench/wrench_nix_test.go
  internal/wrench/wrench_test.go
  internal/wrench/wrench_windows.go
  internal/wrench/wrench_windows_test.go
  state/watcher/txnwatcher.go
  testing/base.go
  worker/environupgrader/worker.go
  worker/hostkeyreporter/worker.go
  worker/instancemutater/mutater.go
  worker/metrics/collect/manifold.go
  worker/metrics/sender/manifold.go
  worker/migrationmaster/worker.go
  worker/provisioner/provisioner_task.go
  worker/state/worker.go
  worker/storageprovisioner/filesystem_ops.go
  worker/storageprovisioner/volume_events.go
  worker/storageprovisioner/volume_ops.go
  worker/uniter/resolver.go
  worker/upgradesteps/worker.go
Labels: 4.0

#16238 Remove FAQ
  FAQ.txt
Labels: 4.0

#16227 Prevent bouncing worker for action retrieval
  worker/machineactions/worker.go
  worker/machineactions/worker_test.go
Labels: 3.1

#16229 Tracing worker
  cmd/jujud/agent/engine_test.go
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/agent/machine/manifolds_test.go
  core/trace/attribute.go
  core/trace/tracer.go
  go.mod
  go.sum
  testing/logger.go
  worker/dbaccessor/worker_integration_test.go
  worker/trace/agent_mock_test.go
  worker/trace/clock_mock_test.go
  worker/trace/manifold.go
  worker/trace/manifold_test.go
  worker/trace/package_test.go
  worker/trace/tracer.go
  worker/trace/tracer_mock_test.go
  worker/trace/tracer_test.go
  worker/trace/worker.go
  worker/trace/worker_test.go
Labels: 4.0

#16244 Merge 3.1 into 3.2
  PULL_REQUEST_TEMPLATE.md
  api/apiclient.go
  api/facadeversions.go
  api/facadeversions_test.go
  apiserver/facades/client/client/status.go
  caas/kubernetes/provider/bootstrap.go
  caas/kubernetes/provider/bootstrap_test.go
  caas/scripts.go
  cmd/juju/ssh/ssh.go
  go.mod
  go.sum
  state/allcollections.go
  state/application.go
  state/caasmodel_test.go
  state/cleanup.go
  state/cleanup_test.go
  state/prune.go
  state/storage.go
  tests/suites/secrets_k8s/task.sh
  worker/machineactions/worker.go
  worker/machineactions/worker_test.go
  worker/undertaker/credentialapi_mock_test.go
  worker/undertaker/facade_mock_test.go
  worker/undertaker/undertaker.go
  worker/undertaker/undertaker_test.go
  worker/uniter/uniter.go
Labels: 3.2

#16243 Bind Dqlite to a local-cloud address if possible at bootstrap
  agent/agentbootstrap/bootstrap.go
  agent/agentbootstrap/bootstrap_test.go
  api/common/network.go
  cmd/jujud/agent/agenttest/agent.go
  cmd/jujud/agent/bootstrap_test.go
  database/app/dqlite_linux.go
  database/app/dqlite_other.go
  database/bootstrap.go
  database/bootstrap_test.go
  database/network_mock_test.go
  database/node.go
  database/node_test.go
  database/package_test.go
  featuretests/dblog_test.go
  worker/dbaccessor/package_mock_test.go
  worker/dbaccessor/worker.go
  worker/dbaccessor/worker_test.go
Labels: 3.2

#16253 Merge 3.3 into main
  .github/workflows/docs.yml
  .github/workflows/microk8s-tests.yml
  .github/workflows/smoke.yml
  .github/workflows/upgrade.yml
  PULL_REQUEST_TEMPLATE.md
  api/apiclient.go
  api/facadeversions.go
  api/facadeversions_test.go
  apiserver/common/networkingcommon/networkconfigapi.go
  apiserver/facades/client/client/filtering.go
  apiserver/facades/client/client/status.go
  apiserver/facades/client/modelupgrader/upgrader_test.go
  apiserver/facadeversions_test.go
  caas/kubernetes/provider/bootstrap.go
  caas/kubernetes/provider/bootstrap_test.go
  caas/scripts.go
  cmd/juju/cloud/add.go
  cmd/juju/cloud/detectcredentials.go
  cmd/juju/interact/pollster.go
  cmd/juju/interact/query.go
  cmd/juju/machine/upgrademachine.go
  cmd/juju/ssh/ssh.go
  core/base/supported.go
  core/output/yamlformatter.go
  core/payloads/filter.go
  go.mod
  go.sum
  provider/azure/environ.go
  provider/lxd/environ.go
  state/allcollections.go
  state/application.go
  state/caasmodel_test.go
  state/cleanup.go
  state/cleanup_test.go
  state/prune.go
  state/storage.go
  tests/suites/secrets_k8s/task.sh
  upgrades/upgradevalidation/migrate_test.go
  worker/machineactions/worker.go
  worker/machineactions/worker_test.go
  worker/undertaker/credentialapi_mock_test.go
  worker/undertaker/facade_mock_test.go
  worker/undertaker/package_test.go
  worker/undertaker/undertaker.go
  worker/undertaker/undertaker_test.go
  worker/uniter/uniter.go
Labels: 4.0

#16237 Inject controller config into the uniter
  agent/agentbootstrap/bootstrap_test.go
  apiserver/common/controllerconfig.go
  apiserver/facades/agent/storageprovisioner/package_test.go
  apiserver/facades/agent/storageprovisioner/storageprovisioner_caas_test.go
  apiserver/facades/agent/storageprovisioner/storageprovisioner_iaas_test.go
  apiserver/facades/agent/storageprovisioner/storageprovisioner_test.go
  apiserver/facades/agent/uniter/export_test.go
  apiserver/facades/agent/uniter/lxdprofile_test.go
  apiserver/facades/agent/uniter/networkinfo_internal_test.go
  apiserver/facades/agent/uniter/networkinfo_test.go
  apiserver/facades/agent/uniter/package_test.go
  apiserver/facades/agent/uniter/register.go
  apiserver/facades/agent/uniter/uniter.go
  apiserver/facades/agent/uniter/uniter_apierror_test.go
  apiserver/facades/agent/uniter/uniter_cloudspec_test.go
  apiserver/facades/agent/uniter/uniter_metrics_test.go
  apiserver/facades/agent/uniter/uniter_network_test.go
  apiserver/facades/agent/uniter/uniter_test.go
  apiserver/facades/agent/upgrader/upgrader_test.go
  apiserver/facades/client/application/application_test.go
  apiserver/facades/client/application/deploy_test.go
  apiserver/facades/client/application/get_test.go
  apiserver/facades/client/client/status_caas_test.go
  apiserver/facades/client/client/status_test.go
  apiserver/facades/client/controller/controller_test.go
  apiserver/facades/client/modelmanager/modelmanager_test.go
  apiserver/facades/controller/firewaller/firewaller_test.go
  apiserver/server_test.go
  cmd/jujud/agent/agenttest/agent.go
  cmd/jujud/agent/bootstrap_test.go
  cmd/jujud/agent/machine_legacy_test.go
  database/testing/schema.go
  domain/cloud/state/state.go
  domain/testing/controllerconfigsuite.go
  juju/testing/apiserver.go
  state/watcher/helpers.go
Labels: 4.0

#16257 [JUJU-4504] Retry transactions when entering scope of a relation unit
  state/errors/common.go
  state/relationunit.go
  state/relationunit_test.go
Labels: bug, 2.9

#16260 Merge 2.9 into 3.1 - 2023/09/14
  state/errors/common.go
  state/relationunit.go
  state/relationunit_test.go
Labels: 3.1

#16270 Find relation via id not endpoint names in cleanup job.
  state/cleanup.go
  state/relation.go
Labels: bug, 2.9

#16249 Bump gomaasapi to v2.1.0
  go.mod
  go.sum
Labels: 2.9

#16276 Ensure API Client can call 3.x API Facades
  api/facadeversions.go
  apiserver/facades/client/modelmanager/register.go
  apiserver/facadeversions_test.go
Labels: 4.0

#16288 Remove the dockerignore file
  .dockerignore
Labels: 4.0

#16290 Remove feature tests and relocate tests
  apiserver/facades/agent/logger/logger_integration_test.go
  apiserver/facades/agent/meterstatus/meterstatus_integration_test.go
  apiserver/facades/client/charms/client_integration_test.go
  apiserver/facades/client/controller/controller_integration_test.go
  apiserver/facades/client/credentialmanager/client_integration_test.go
  apiserver/tools_integration_test.go
  featuretests/doc.go
  featuretests/package_test.go
Labels: 4.0

#16289 Remove utils package in root
  api/apiclient.go
  api/apiclient_test.go
  api/package_test.go
  cmd/containeragent/initialize/package_test.go
  cmd/containeragent/main_nix.go
  cmd/containeragent/unit/manifolds.go
  cmd/containeragent/unit/package_test.go
  cmd/juju/commands/main.go
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/main.go
  internal/network/debinterfaces/activate.go
  internal/network/netplan/activate.go
  internal/proxy/config/package_test.go
  internal/proxy/config/proxyconfig.go
  internal/proxy/config/proxyconfig_test.go
  internal/scriptrunner/scriptrunner.go
  internal/scriptrunner/scriptrunner_test.go
  provider/lxd/server.go
  utils/proxy/package_test.go
  utils/stringforwarder/stringforwarder.go
  utils/stringforwarder/stringforwarder_test.go
  worker/fanconfigurer/fanconfigurer.go
Labels: 4.0

#16292 Fix jwt permission
  apiserver/authentication/jwt/jwt.go
  apiserver/authentication/jwt/jwt_test.go
Labels: bug, 3.2

#16266 [JUJU-4615] Ask user to create local share after installing snap
  cmd/juju/commands/main.go
  juju/home.go
Labels: 3.1

#16313 Agent bootstrap controller config
  agent/agentbootstrap/bootstrap.go
  agent/agentbootstrap/bootstrap_test.go
  cmd/jujud/agent/bootstrap.go
  cmd/jujud/agent/bootstrap_test.go
  database/bootstrap.go
  domain/credential/bootstrap/bootstrap.go
  domain/credential/bootstrap/bootstrap_test.go
  juju/testing/apiserver.go
Labels: 4.0

#16304 Create dummy updatedatabase worker
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/agent/machine/manifolds_test.go
  worker/upgradedatabase/lock_mock_test.go
  worker/upgradedatabase/manifold.go
  worker/upgradedatabase/manifold_test.go
  worker/upgradedatabase/package_mock_test.go
  worker/upgradedatabase/package_test.go
  worker/upgradedatabase/upgradedatabase.go
  worker/upgradedatabase/upgradedatabase_test.go
Labels: 4.0

#16258 Remove client version checking
  api/apiclient.go
  api/apiclient_test.go
  apiserver/admin.go
  apiserver/errors/errors.go
  apiserver/errors/errors_test.go
  apiserver/export_test.go
  apiserver/restrict_newer_client.go
  apiserver/restrict_newer_client_test.go
  apiserver/root.go
  internal/migration/precheck.go
  internal/migration/precheck_test.go
  rpc/params/apierror.go
  upgrades/upgradevalidation/version.go
  upgrades/upgradevalidation/version_test.go
Labels: 4.0

#16280 Improve error message for missing facades/methods
  api/apiclient.go
  apiserver/admin_test.go
  apiserver/restricted_root_test.go
  apiserver/root_test.go
  domain/upgrade/service/watcher.go
  internal/rpcreflect/errors.go
  internal/rpcreflect/type_test.go
  rpc/reflect_test.go
  rpc/rpc_test.go
Labels: 4.0

#16295 Inject controllerconfig service into ControllerConfigAPI
  apiserver/common/controllerconfig.go
  apiserver/common/controllerconfig_test.go
  apiserver/common/interfaces.go
  apiserver/common/mocks/controllerconfig_mock.go
  apiserver/common/package_test.go
  apiserver/facades/agent/agent/agent.go
  apiserver/facades/agent/caasadmission/register.go
  apiserver/facades/agent/caasagent/register.go
  apiserver/facades/agent/provisioner/provisioner.go
  apiserver/facades/agent/secretsmanager/register.go
  apiserver/facades/client/applicationoffers/applicationoffers.go
  apiserver/facades/client/applicationoffers/base.go
  apiserver/facades/client/applicationoffers/mock_test.go
  apiserver/facades/client/applicationoffers/register.go
  apiserver/facades/client/controller/controller.go
  apiserver/facades/controller/caasmodelconfigmanager/register.go
  apiserver/facades/controller/crosscontroller/crosscontroller.go
  apiserver/facades/controller/crosscontroller/crosscontroller_test.go
  apiserver/facades/controller/crosscontroller/register.go
  apiserver/facades/controller/firewaller/register.go
  apiserver/facades/controller/remoterelations/register.go
  cmd/jujud/agent/machine_legacy_test.go
  cmd/jujud/agent/machine_test.go
  juju/testing/apiserver.go
  worker/syslogger/worker.go
  worker/syslogger/worker_test.go
Labels: 4.0

#16323 Refactor service factory model getter
  core/changestream/eventsource.go
  core/watcher/eventsource/package_test.go
  domain/servicefactory/model.go
  domain/servicefactory/service.go
  domain/servicefactory/testing/service.go
  domain/servicefactory/testing/suite.go
  internal/database/testing/runner.go
  internal/servicefactory/interface.go
  worker/servicefactory/manifold.go
  worker/servicefactory/servicefactory_mock_test.go
  worker/servicefactory/worker.go
Labels: 4.0

#16314 Agent bootstrap type
  agent/agentbootstrap/bootstrap.go
  agent/agentbootstrap/bootstrap_test.go
  cmd/jujud/agent/bootstrap.go
  cmd/jujud/agent/bootstrap_test.go
Labels: 4.0

#16320 Inject controller config provisioner
  apiserver/facades/agent/provisioner/provisioner.go
  apiserver/facades/agent/provisioner/provisioner_test.go
  apiserver/facades/agent/provisioner/provisioninginfo.go
  apiserver/facades/agent/provisioner/provisioninginfo_test.go
Labels: 4.0

#16327 Rephrase warning message for strictly confined snap
  cmd/juju/commands/main.go
Labels: 3.1

#16326 Supply Watcher Next() with context.Context
  apiserver/facades/client/client/client.go
  apiserver/facades/client/controller/controller_test.go
  apiserver/watcher.go
  apiserver/watcher_test.go
  core/multiwatcher/types.go
  worker/multiwatcher/watcher.go
  worker/multiwatcher/watcher_test.go
Labels: 4.0

#16319 Inject controller config machiner
  apiserver/facades/agent/machine/machiner.go
  apiserver/facades/agent/machine/machiner_test.go
  apiserver/facades/agent/machine/register.go
Labels: 4.0

#16331 Drop json codec v0 support
  rpc/dispatch_test.go
  rpc/jsoncodec/codec.go
  rpc/jsoncodec/codec_test.go
Labels: 4.0

#16343 Inject controller-config into storage provisioner
  apiserver/facades/agent/storageprovisioner/register.go
  apiserver/facades/agent/storageprovisioner/shim.go
  apiserver/facades/agent/storageprovisioner/storageprovisioner.go
  apiserver/facades/agent/storageprovisioner/storageprovisioner_caas_test.go
  apiserver/facades/agent/storageprovisioner/storageprovisioner_iaas_test.go
  apiserver/facades/agent/storageprovisioner/storageprovisioner_test.go
Labels: 4.0

#16339 Fix debug-hooks/debug-code commands on k8s and fix tmux sessions.
  .github/verify-agent-version.sh
  .github/workflows/microk8s-tests.yml
  .github/workflows/smoke.yml
  .github/workflows/upgrade.yml
  cmd/juju/commands/debughooks.go
  cmd/juju/commands/debughooks_test.go
  cmd/juju/commands/ssh_container.go
  cmd/juju/commands/ssh_container_test.go
  worker/uniter/runner/debug/client.go
  worker/uniter/runner/debug/server.go
Labels: do not merge, 2.9

#16354 Enable upgrade action. Fix --build-agent juju root finding.
  .github/workflows/upgrade.yml
  environs/tools/build.go
Labels: 3.2

#16344 Inject controller config into caas application
  apiserver/facades/agent/caasapplication/application.go
  apiserver/facades/agent/caasapplication/application_test.go
  apiserver/facades/agent/caasapplication/register.go
  apiserver/facades/schema.json
  rpc/dispatch_test.go
Labels: 4.0

#16347 Use existing controller config from args
  cmd/jujud/agent/bootstrap.go
  cmd/jujud/agent/controllercharm.go
Labels: 4.0

#16346 Inject controller config into cloud
  apiserver/common/credentialcommon/backend.go
  apiserver/common/credentialcommon/mocks/credentialcommon_mock.go
  apiserver/common/credentialcommon/modelcredential.go
  apiserver/common/credentialcommon/modelcredential_test.go
  apiserver/common/credentialcommon/package_test.go
  apiserver/facades/client/cloud/cloud.go
  apiserver/facades/client/cloud/cloud_test.go
  apiserver/facades/client/cloud/instance_information_test.go
  apiserver/facades/client/cloud/mocks/cloud_mock.go
  apiserver/facades/client/cloud/package_test.go
  apiserver/facades/client/cloud/register.go
  apiserver/facades/controller/migrationtarget/migrationtarget.go
  environs/context/callcontext.go
Labels: 4.0
