Repository juju/juju, pull requests merged in 2023-10, with the labels that each got.

#16341 RPC requests with trace id and span id
  api/apiclient.go
  api/apiclient_test.go
  rpc/client.go
  rpc/context.go
  rpc/context_test.go
  rpc/dispatch_test.go
  rpc/jsoncodec/codec.go
  rpc/rpc_test.go
  rpc/server.go
Labels: 4.0

#16356 Removes ControllerConfig calls from state tests
  apiserver/facades/controller/crosscontroller/crosscontroller.go
  apiserver/facades/controller/crosscontroller/crosscontroller_test.go
  apiserver/facades/controller/crosscontroller/register.go
  apiserver/server_test.go
  cmd/jujud/agent/agenttest/agent.go
  cmd/jujud/agent/machine_test.go
  cmd/jujud/agent/util_test.go
  state/address_test.go
  state/allwatcher_internal_test.go
  state/controller_test.go
  state/machine_test.go
  state/migration_import_test.go
  state/relationunit_test.go
  state/state_test.go
  state/unit_test.go
Labels: 4.0

#16322 Add to the info table db_completed_at
  domain/schema/controller.go
  domain/upgrade/service/package_mock_test.go
  domain/upgrade/service/service.go
  domain/upgrade/service/service_test.go
  domain/upgrade/state/state.go
  domain/upgrade/state/state_test.go
  domain/upgrade/state/types.go
  worker/upgradedatabase/worker.go
  worker/upgradedatabase/worker_test.go
Labels: 4.0

#16135 Report storage within FullStatus facade call.
  api/client/client/client.go
  api/facadeversions.go
  api/state_test.go
  apiserver/admin_test.go
  apiserver/common/storagecommon/filesystemdetails.go
  apiserver/common/storagecommon/storagedetails.go
  apiserver/common/storagecommon/volumedetails.go
  apiserver/facades/client/client/backend.go
  apiserver/facades/client/client/client.go
  apiserver/facades/client/client/client_test.go
  apiserver/facades/client/client/register.go
  apiserver/facades/client/client/status.go
  apiserver/facades/client/client/status_test.go
  apiserver/facades/client/client/statushistory_test.go
  apiserver/facades/client/storage/shim.go
  apiserver/facades/client/storage/storage.go
  apiserver/facades/schema.json
  cmd/juju/application/deploy.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/interface.go
  cmd/juju/application/deployer/mocks/deploy_mock.go
  cmd/juju/machine/base.go
  cmd/juju/machine/list_test.go
  cmd/juju/machine/mocks/status_api_mock.go
  cmd/juju/machine/upgrademachine.go
  cmd/juju/ssh/ssh.go
  cmd/juju/ssh/ssh_container.go
  cmd/juju/ssh/ssh_machine.go
  cmd/juju/ssh/ssh_machine_test.go
  cmd/juju/status/export_test.go
  cmd/juju/status/status.go
  cmd/juju/status/status_internal_test.go
  cmd/juju/status/status_test.go
  cmd/juju/storage/list.go
  rpc/params/status.go
Labels: 3.3

#16376 Remove stateservinginfo from peergrouper
  worker/peergrouper/manifold.go
  worker/peergrouper/manifold_test.go
Labels: 4.0

#16387 Better fetch instance support.
  provider/ec2/client.go
  provider/ec2/image.go
  provider/ec2/instance.go
  provider/ec2/instance_test.go
  provider/ec2/instancetypes.go
Labels: 3.1

#16380 Allow building with podman using `make OCI_BUILDER=podman ...`
  Makefile
  caas/Dockerfile
  make_functions.sh
Labels: 2.9

#16389 Removes ec2:DescribeInstanceTypeOfferings from iam doc.
  provider/ec2/iam_docs.go
Labels: 3.1

#16390 Use podman if it is installed. Fix DOCKER_USERNAME for podman.
  Makefile
  make_functions.sh
Labels: 2.9

#16391 Try and ensure secret access role bindings are created before serving the config to the agent
  caas/kubernetes/provider/rbac.go
  caas/kubernetes/provider/rbac_test.go
Labels: 3.1

#16384 Fix notify sighup tests
  worker/controlleragentconfig/manifold.go
  worker/controlleragentconfig/worker.go
  worker/controlleragentconfig/worker_test.go
Labels: 4.0

#16277 Add support for ARM shapes on Oracle OCI
  Makefile
  go.mod
  go.sum
  provider/oci/environ.go
  provider/oci/images.go
  provider/oci/images_integration_test.go
Labels: 3.3

#16296 [JUJU-4710] Remove the last occurences of ComputedSeries
  cmd/juju/application/deployer/deployer.go
  core/bundle/changes/handlers.go
  core/charm/baseselector.go
  core/charm/charmpath_test.go
  core/charm/computedbase.go
  core/charm/computedbase_test.go
  core/charm/computedseries.go
  core/charm/computedseries_test.go
  state/application.go
  state/application_test.go
  state/relation_test.go
  state/state.go
  state/state_test.go
  testcharms/charm-hub/quantal/charmhubby/manifest.yaml
  testcharms/charm-hub/quantal/dummy/manifest.yaml
  testcharms/charm-repo/bionic/mysql/manifest.yaml
  testcharms/charm-repo/focal/mysql-k8s/manifest.yaml
  testcharms/charm-repo/kubernetes/mysql/manifest.yaml
  testcharms/charm-repo/quantal/actionless/manifest.yaml
  testcharms/charm-repo/quantal/all-hooks/manifest.yaml
  testcharms/charm-repo/quantal/dummy/manifest.yaml
  testcharms/charm-repo/quantal/juju-controller/manifest.yaml
  testcharms/charm-repo/quantal/logging-frontend/manifest.yaml
  testcharms/charm-repo/quantal/logging-principal/manifest.yaml
  testcharms/charm-repo/quantal/logging-raring/hooks/.gitkeep
  testcharms/charm-repo/quantal/logging-raring/manifest.yaml
  testcharms/charm-repo/quantal/logging-raring/metadata.yaml
  testcharms/charm-repo/quantal/logging-raring/revision
  testcharms/charm-repo/quantal/logging/manifest.yaml
  testcharms/charm-repo/quantal/lxd-profile-fail/manifest.yaml
  testcharms/charm-repo/quantal/lxd-profile/manifest.yaml
  testcharms/charm-repo/quantal/mariadb/manifest.yaml
  testcharms/charm-repo/quantal/metered/manifest.yaml
  testcharms/charm-repo/quantal/monitoring/manifest.yaml
  testcharms/charm-repo/quantal/mysql-alternative/manifest.yaml
  testcharms/charm-repo/quantal/riak/manifest.yaml
  testcharms/charm-repo/quantal/sample-fail-no-os/.dir/ignored
  testcharms/charm-repo/quantal/sample-fail-no-os/.ignored
  testcharms/charm-repo/quantal/sample-fail-no-os/actions.yaml
  testcharms/charm-repo/quantal/sample-fail-no-os/build/ignored
  testcharms/charm-repo/quantal/sample-fail-no-os/config.yaml
  testcharms/charm-repo/quantal/sample-fail-no-os/empty/.gitkeep
  testcharms/charm-repo/quantal/sample-fail-no-os/hooks/install
  testcharms/charm-repo/quantal/sample-fail-no-os/hooks/remove
  testcharms/charm-repo/quantal/sample-fail-no-os/hooks/stop
  testcharms/charm-repo/quantal/sample-fail-no-os/metadata.yaml
  testcharms/charm-repo/quantal/sample-fail-no-os/revision
  testcharms/charm-repo/quantal/sample-fail-no-os/src/hello.c
  testcharms/charm-repo/quantal/sample-fail-no-os/version
  testcharms/charm-repo/quantal/starsay/manifest.yaml
  testcharms/charm-repo/quantal/storage-block/manifest.yaml
  testcharms/charm-repo/quantal/storage-block2/manifest.yaml
  testcharms/charm-repo/quantal/storage-filesystem-subordinate/manifest.yaml
  testcharms/charm-repo/quantal/storage-filesystem/manifest.yaml
  testcharms/charm-repo/quantal/storage-filesystem2/manifest.yaml
  testcharms/charm-repo/quantal/varnish/manifest.yaml
  testcharms/charm-repo/quantal/wordpress-extra-bindings/manifest.yaml
  testcharms/charm-repo/quantal/wordpress-nolimit/manifest.yaml
  testcharms/charm-repo/quantal/wordpress/manifest.yaml
Labels: 3.3

#16398 Backport request #16391 from wallyworld/k8s-secret-ensure-rbac
  caas/kubernetes/provider/rbac.go
  caas/kubernetes/provider/rbac_test.go
Labels: 3.1

#16293 Wire up trace
  api/package_test.go
  apiserver/admin.go
  apiserver/apiserver.go
  apiserver/export_test.go
  apiserver/restricted_root.go
  apiserver/root.go
  apiserver/shared.go
  apiserver/shared_test.go
  apiserver/testing/fakeapi.go
  cmd/containeragent/initialize/package_test.go
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/agent/machine/manifolds_test.go
  cmd/jujud/agent/machine_legacy_test.go
  core/trace/attribute.go
  core/trace/context.go
  core/trace/context_test.go
  core/trace/package_test.go
  core/trace/tracer.go
  core/trace/tracer_test.go
  internal/database/txn/transaction.go
  juju/testing/apiserver.go
  rpc/context.go
  rpc/rpc_test.go
  rpc/server.go
  worker/apiserver/manifold.go
  worker/apiserver/manifold_test.go
  worker/apiserver/worker.go
  worker/apiserver/worker_state_test.go
  worker/apiserver/worker_test.go
  worker/trace/manifold.go
  worker/trace/manifold_test.go
  worker/trace/package_test.go
  worker/trace/trace_mock_test.go
  worker/trace/tracer.go
  worker/trace/tracer_mock_test.go
  worker/trace/tracer_test.go
  worker/trace/worker.go
  worker/trace/worker_test.go
Labels: 4.0

#16383 Filter out icmpv6 when reading back ec2 security groups.
  provider/ec2/environ.go
Labels: 3.1

#16366 [JUJU-4688] Ensure charm origins have a revision
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/application_unit_test.go
  cmd/juju/application/utils/origin.go
  state/migration_export.go
  state/migration_import.go
  state/migration_import_test.go
  state/upgrades.go
  state/upgrades_test.go
  upgrades/backend.go
  upgrades/operations.go
  upgrades/steps_317.go
  upgrades/steps_317_test.go
  upgrades/upgrade_test.go
Labels: 3.1

#16400 Add s3caller worker config validation and tests
  cmd/containeragent/unit/manifolds.go
  worker/deployer/unit_manifolds.go
  worker/s3caller/api_mocks.go
  worker/s3caller/client.go
  worker/s3caller/client_test.go
  worker/s3caller/manifold.go
  worker/s3caller/manifold_test.go
  worker/s3caller/package_mock_test.go
  worker/s3caller/package_test.go
Labels: 4.0

#16358 3.1 to 4.x migrate job
  .github/workflows/migrate.yml
Labels: 4.0

#16365 Prevent CAAS Image Path docker request every controller config validation
  apiserver/facades/client/client/client.go
  apiserver/facades/client/modelupgrader/findagents.go
  apiserver/facades/controller/caasapplicationprovisioner/provisioner.go
  apiserver/facades/controller/caasmodeloperator/operator.go
  apiserver/facades/controller/caasmodeloperator/operator_test.go
  apiserver/facades/controller/caasoperatorprovisioner/provisioner.go
  apiserver/facades/controller/caasunitprovisioner/provisioner.go
  caas/kubernetes/provider/bootstrap.go
  caas/kubernetes/provider/bootstrap_test.go
  cloudconfig/podcfg/image.go
  cloudconfig/podcfg/image_test.go
  cmd/containeragent/initialize/package_test.go
  cmd/juju/commands/bootstrap.go
  cmd/jujud/agent/model/manifolds.go
  controller/config.go
  controller/config_test.go
  docker/auth.go
  docker/imagerepo/imagerepo.go
  docker/imagerepo/imagerepo_test.go
  docker/imagerepo/package_test.go
  docker/imagerepo/registry_test.go
  docker/registry/package_test.go
  docker/registry/registry.go
  worker/caasmodelconfigmanager/facade_mock_test.go
  worker/caasmodelconfigmanager/manifold.go
  worker/caasmodelconfigmanager/manifold_test.go
  worker/caasmodelconfigmanager/mocks/broker_mock.go
  worker/caasmodelconfigmanager/mocks/facade_mock.go
  worker/caasmodelconfigmanager/package_test.go
  worker/caasmodelconfigmanager/worker.go
  worker/caasmodelconfigmanager/worker_test.go
Labels: 3.1

#16367 Disallow default OCI repo translation to docker.io.
  .github/workflows/microk8s-tests.yml
  .github/workflows/upgrade.yml
  Makefile
  apiserver/facades/controller/caasapplicationprovisioner/provisioner_test.go
  apiserver/facades/controller/caasoperatorprovisioner/provisioner_test.go
  apiserver/facades/controller/caasunitprovisioner/provisioner_test.go
  caas/kubernetes/provider/application/application_test.go
  caas/kubernetes/provider/bootstrap_test.go
  caas/kubernetes/provider/k8s_test.go
  caas/kubernetes/provider/operator_test.go
  caas/kubernetes/provider/utils/dockerconfig.go
  caas/kubernetes/provider/utils/dockerconfig_test.go
  cloudconfig/podcfg/image.go
  cloudconfig/podcfg/image_test.go
  cloudconfig/podcfg/podcfg_test.go
  controller/config_test.go
  docker/registry/internal/acr.go
  docker/registry/internal/acr_test.go
  docker/registry/internal/base_client.go
  docker/registry/internal/dockerhub.go
  docker/registry/internal/dockerhub_test.go
  docker/registry/internal/ecr.go
  docker/registry/internal/ecr_test.go
  docker/registry/internal/gcr.go
  docker/registry/internal/github.go
  docker/registry/internal/gitlab.go
  docker/registry/internal/provider.go
  docker/registry/internal/quay.go
  docker/registry/registry.go
  docker/registry/registry_test.go
  make_functions.sh
Labels: 3.3

#16374 Improve private OCI registry for caas-image-repo
  .github/workflows/static-analysis.yml
  Makefile
  api/controller/caasmodelconfigmanager/client.go
  apiserver/facades/client/controller/controller.go
  apiserver/facades/client/controller/controller_test.go
  apiserver/facades/controller/caasmodelconfigmanager/facade.go
  apiserver/facades/controller/caasmodelconfigmanager/register.go
  apiserver/facades/schema.json
  caas/kubernetes/provider/bootstrap.go
  caas/kubernetes/provider/export_test.go
  cmd/juju/commands/bootstrap.go
  cmd/juju/commands/ssh_machine.go
  controller/config.go
  controller/config_test.go
  docker/auth.go
  docker/auth_test.go
  docker/registry/internal/acr.go
  docker/registry/internal/base_client.go
  docker/registry/internal/dockerhub.go
  docker/registry/internal/ecr.go
  docker/registry/internal/ecr_test.go
  docker/registry/internal/gcr.go
  docker/registry/internal/github.go
  docker/registry/internal/gitlab.go
  docker/registry/internal/interface.go
  docker/registry/internal/provider.go
  docker/registry/internal/quay.go
  docker/registry/internal/transports.go
  docker/registry/mocks/registry_mock.go
  docker/registry/registry_test.go
  make_functions.sh
  provider/equinix/environ.go
  tests/README.md
  tests/suites/static_analysis/lint_go.sh
  worker/caasmodelconfigmanager/mocks/facade_mock.go
  worker/caasmodelconfigmanager/worker.go
  worker/caasmodelconfigmanager/worker_test.go
Labels: 2.9

#16404 First step in cleaning up logic in cloud facade and improve tests
  apiserver/common/credentialcommon/backend.go
  apiserver/common/credentialcommon/mocks/credentialcommon_mock.go
  apiserver/common/credentialcommon/modelcredential.go
  apiserver/common/credentialcommon/modelcredential_test.go
  apiserver/common/credentialcommon/package_test.go
  apiserver/facades/client/cloud/backend.go
  apiserver/facades/client/cloud/cloud.go
  apiserver/facades/client/cloud/cloud_test.go
  apiserver/facades/client/cloud/export_test.go
  apiserver/facades/client/cloud/instance_information.go
  apiserver/facades/client/cloud/instance_information_test.go
  apiserver/facades/client/cloud/mocks/cloud_mock.go
  apiserver/facades/client/cloud/package_test.go
  apiserver/facades/client/cloud/register.go
  apiserver/facades/controller/migrationtarget/migrationtarget.go
  apiserver/facades/schema.json
  cloud/clouds.go
  state/clouduser.go
  state/clouduser_test.go
  state/credentialmodels_test.go
  state/modelcredential.go
Labels: 4.0

#16408 Remove docker dependency from controller config.
  apiserver/facades/client/client/client.go
  apiserver/facades/client/controller/controller.go
  apiserver/facades/client/controller/controller_test.go
  apiserver/facades/client/modelupgrader/findagents.go
  apiserver/facades/controller/caasapplicationprovisioner/provisioner.go
  apiserver/facades/controller/caasmodeloperator/operator.go
  apiserver/facades/controller/caasoperatorprovisioner/provisioner.go
  apiserver/facades/controller/caasunitprovisioner/provisioner.go
  caas/kubernetes/provider/bootstrap.go
  caas/kubernetes/provider/bootstrap_test.go
  cloudconfig/podcfg/image.go
  cmd/containeragent/initialize/package_test.go
  controller/config.go
  controller/config_test.go
  docker/auth.go
  docker/auth_test.go
  make_functions.sh
  worker/caasmodelconfigmanager/worker.go
  worker/caasmodelconfigmanager/worker_test.go
Labels: 3.1

#16403 [JUJU-4726] Fix aws_ami_creation instance_type
  tests/includes/aws_ami_creation.sh
Labels: 3.3

#16411 Fix controller config key finding in md-gen tool.
  controller/config.go
  scripts/md-gen/controller-config/main.go
Labels: 3.3

#16360 Agent controller config subscription
  cmd/jujud/agent/machine/manifolds.go
  go.mod
  go.sum
  worker/controlleragentconfig/doc.go
  worker/controlleragentconfig/manifold.go
  worker/controlleragentconfig/manifold_test.go
  worker/controlleragentconfig/worker.go
  worker/controlleragentconfig/worker_test.go
Labels: 4.0

#16414 Close temp files before potential errors
  agent/tools/toolsdir.go
  api/client/charms/client.go
  apiserver/charms.go
  apiserver/common/charms.go
  core/charm/downloader/downloader.go
  environs/filestorage/filestorage.go
  environs/sync/sync.go
  juju/testing/conn.go
  migration/migration.go
  provider/common/bootstrap.go
  storage/provider/managedfs.go
Labels: 3.1

#16412 Add wait_for after removing offers, relations and saas
  tests/suites/cmr/offer_consume.sh
Labels: 3.3

#16372 Model bootstrap wireup
  agent/agentbootstrap/bootstrap.go
  agent/agentbootstrap/bootstrap_test.go
  apiserver/facades/client/modelmanager/listmodelsummaries_test.go
  apiserver/facades/client/modelmanager/modelinfo_test.go
  apiserver/facades/client/modelmanager/modelmanager.go
  apiserver/facades/client/modelmanager/modelmanager_test.go
  apiserver/facades/client/modelmanager/register.go
  domain/cloud/bootstrap/bootstrap.go
  domain/cloud/bootstrap/bootstrap_test.go
  domain/cloud/state/state.go
  domain/cloud/state/state_test.go
  domain/credential/bootstrap/bootstrap.go
  domain/credential/bootstrap/bootstrap_test.go
  domain/credential/credential.go
  domain/credential/package_test.go
  domain/credential/state/state.go
  domain/credential/state/types.go
  domain/credential/types.go
  domain/credential/types_test.go
  domain/model/bootstrap/bootstrap.go
  domain/model/defaults.go
  domain/model/errors/errors.go
  domain/model/service/service.go
  domain/model/service/service_test.go
  domain/model/state/state.go
  domain/model/state/state_test.go
  domain/model/types.go
  domain/model/types_test.go
  domain/modelmanager/bootstrap/bootstrap.go
  domain/modelmanager/state/state.go
  domain/modelmanager/state/state_test.go
  domain/schema/controller.go
  domain/schema/schema_test.go
  domain/servicefactory/testing/suite.go
  go.mod
  internal/database/txn/errors_test.go
  juju/testing/apiserver.go
Labels: 4.0

#16415 Merge 3.3 to main
  Makefile
  api/controller/caasmodelconfigmanager/client.go
  apiserver/facades/client/client/client.go
  apiserver/facades/client/controller/controller.go
  apiserver/facades/client/controller/controller_test.go
  apiserver/facades/client/modelupgrader/findagents.go
  apiserver/facades/controller/caasapplicationprovisioner/provisioner.go
  apiserver/facades/controller/caasmodelconfigmanager/facade.go
  apiserver/facades/controller/caasmodelconfigmanager/register.go
  apiserver/facades/controller/caasmodeloperator/operator.go
  apiserver/facades/schema.json
  caas/Dockerfile
  caas/kubernetes/provider/bootstrap.go
  caas/kubernetes/provider/bootstrap_test.go
  caas/kubernetes/provider/export_test.go
  cloudconfig/podcfg/image.go
  cmd/containeragent/initialize/package_test.go
  cmd/juju/commands/bootstrap.go
  cmd/juju/ssh/ssh_machine.go
  controller/config.go
  controller/config_test.go
  internal/docker/auth.go
  internal/docker/auth_test.go
  internal/docker/registry/internal/acr.go
  internal/docker/registry/internal/base_client.go
  internal/docker/registry/internal/dockerhub.go
  internal/docker/registry/internal/ecr.go
  internal/docker/registry/internal/ecr_test.go
  internal/docker/registry/internal/gcr.go
  internal/docker/registry/internal/github.go
  internal/docker/registry/internal/gitlab.go
  internal/docker/registry/internal/interface.go
  internal/docker/registry/internal/provider.go
  internal/docker/registry/internal/quay.go
  internal/docker/registry/internal/transports.go
  internal/docker/registry/mocks/registry_mock.go
  internal/docker/registry/registry.go
  internal/docker/registry/registry_test.go
  make_functions.sh
  provider/equinix/environ.go
  scripts/md-gen/controller-config/main.go
  tests/includes/aws_ami_creation.sh
  tests/suites/cmr/offer_consume.sh
  worker/caasmodelconfigmanager/mocks/facade_mock.go
  worker/caasmodelconfigmanager/worker.go
  worker/caasmodelconfigmanager/worker_test.go
Labels: 4.0

#16420 Update upgrade database worker with the correct dependencies
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/agent/machine/manifolds_test.go
  domain/credential/service/service_test.go
  domain/schema/changelog.go
  domain/schema/controller.go
  domain/servicefactory/controller.go
  domain/servicefactory/testing/service.go
  domain/upgrade/service/package_mock_test.go
  domain/upgrade/service/service.go
  domain/upgrade/service/service_test.go
  domain/upgrade/service/watcher.go
  domain/upgrade/service/watcher_test.go
  domain/watcher.go
  domain/watcher_test.go
  internal/servicefactory/interface.go
  worker/servicefactory/servicefactory_mock_test.go
  worker/upgradedatabase/database_mock_test.go
  worker/upgradedatabase/manifold.go
  worker/upgradedatabase/manifold_test.go
  worker/upgradedatabase/package_mock_test.go
  worker/upgradedatabase/package_test.go
  worker/upgradedatabase/service_mock_test.go
  worker/upgradedatabase/servicefactory_mock_test.go
  worker/upgradedatabase/worker.go
  worker/upgradedatabase/worker_mock_test.go
  worker/upgradedatabase/worker_test.go
Labels: 4.0

#16424 Watch upgrades if it's already started
  domain/upgrade/service/service.go
  domain/upgrade/service/service_test.go
  worker/upgradedatabase/manifold.go
  worker/upgradedatabase/manifold_test.go
  worker/upgradedatabase/package_test.go
  worker/upgradedatabase/service_mock_test.go
  worker/upgradedatabase/worker.go
  worker/upgradedatabase/worker_test.go
Labels: 4.0

#16426 Bump critical packages + add mantic
  apiserver/facades/client/modelupgrader/upgrader_test.go
  core/series/supported.go
  core/series/supportedseries_linux_test.go
  core/series/supportedseries_test.go
  go.mod
  go.sum
  upgrades/upgradevalidation/migrate_test.go
  upgrades/upgradevalidation/upgrade_test.go
  upgrades/upgradevalidation/validation_test.go
Labels: 2.9

#16301 Add `controlsocket` worker
  caas/kubernetes/provider/bootstrap.go
  caas/kubernetes/provider/bootstrap_test.go
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/agent/machine/manifolds_test.go
  core/paths/paths.go
  go.mod
  worker/controlsocket/doc.go
  worker/controlsocket/handlers.go
  worker/controlsocket/handlers_test.go
  worker/controlsocket/manifold.go
  worker/controlsocket/package_test.go
  worker/controlsocket/shim.go
  worker/controlsocket/worker.go
  worker/controlsocket/worker_test.go
Labels: 3.3

#16388 Add integration tests for controller charm & Prometheus
  tests/ENV.md
  tests/includes/juju.sh
  tests/includes/retry.sh
  tests/includes/wait-for.sh
  tests/suites/controllercharm/prometheus.sh
  tests/suites/controllercharm/task.sh
Labels: 3.3

#16442 Wire up cloud facade to use new service apis
  apiserver/common/credentialcommon/backend.go
  apiserver/common/credentialcommon/cloudcredential_test.go
  apiserver/common/credentialcommon/credentialcommon_mock.go
  apiserver/common/credentialcommon/export_test.go
  apiserver/common/credentialcommon/modelcredential.go
  apiserver/common/credentialcommon/modelcredential_test.go
  apiserver/common/credentialcommon/package_test.go
  apiserver/facades/client/cloud/backend.go
  apiserver/facades/client/cloud/cloud.go
  apiserver/facades/client/cloud/cloud_test.go
  apiserver/facades/client/cloud/mocks/cloud_mock.go
  apiserver/facades/client/cloud/mocks/credential_mock.go
  apiserver/facades/client/cloud/package_test.go
  apiserver/facades/client/cloud/register.go
  apiserver/facades/client/controller/controller.go
  apiserver/facades/controller/migrationtarget/credential_mock_test.go
  apiserver/facades/controller/migrationtarget/migrationtarget.go
  apiserver/facades/controller/migrationtarget/migrationtarget_test.go
  apiserver/facades/controller/migrationtarget/package_test.go
  apiserver/facades/controller/migrationtarget/register.go
  apiserver/facades/schema.json
  domain/credential/modelmigration/export.go
  domain/credential/modelmigration/export_test.go
  domain/credential/service/service.go
  domain/credential/state/state.go
  domain/credential/state/state_test.go
  environs/context/callcontext.go
  state/credentialmodels_test.go
  state/migration_export.go
  state/modelcredential.go
Labels: 4.0

#16440 Fix integration test for enable-ha
  tests/suites/controller/enable_ha.sh
  worker/modelcache/worker_test.go
Labels: 3.2

#16435 rename import redirect in worker/uniter
  worker/uniter/charm/bundles_test.go
  worker/uniter/charm/charm_test.go
  worker/uniter/op_callbacks.go
  worker/uniter/resolver.go
  worker/uniter/resolver/loop.go
  worker/uniter/uniter.go
  worker/uniter/uniter_test.go
  worker/uniter/util_test.go
  worker/uniter/verifycharmprofile/verifycharmprofile.go
Labels: 3.1

#16445 Fix parsing of watch flag on status command
  cmd/juju/status/status.go
  cmd/juju/status/status_internal_test.go
Labels: bug, 3.1

#16448 Snap dependencies update
  snap/snapcraft.yaml
Labels: 4.0

#16452 Mechanical rearrangement for firewaller test
  api/testing/macaroonsuite.go
  worker/firewaller/firewaller_test.go
Labels: 3.1

#16453 Backport changes to fix model cache tests for adding a machine
  worker/modelcache/worker_test.go
Labels: 3.1

#16449 Remove credential tags from service api calls
  agent/agentbootstrap/bootstrap.go
  api/package_test.go
  apiserver/common/cloudspec/statehelpers.go
  apiserver/common/credentialcommon/cloudcredential.go
  apiserver/common/credentialcommon/cloudcredential_test.go
  apiserver/common/credentialcommon/credentialcommon_mock.go
  apiserver/common/mocks/credential_mock.go
  apiserver/common/modelmanagerinterface.go
  apiserver/common/secrets/secrets.go
  apiserver/common/secrets/secrets_test.go
  apiserver/facades/agent/agent/agent.go
  apiserver/facades/agent/agent/agent_test.go
  apiserver/facades/agent/agent/register.go
  apiserver/facades/agent/credentialvalidator/backend_test.go
  apiserver/facades/agent/credentialvalidator/credentialvalidator.go
  apiserver/facades/agent/credentialvalidator/credentialvalidator_test.go
  apiserver/facades/agent/uniter/uniter.go
  apiserver/facades/agent/uniter/uniter_apierror_test.go
  apiserver/facades/agent/uniter/uniter_network_test.go
  apiserver/facades/client/cloud/backend.go
  apiserver/facades/client/cloud/cloud.go
  apiserver/facades/client/cloud/cloud_test.go
  apiserver/facades/client/cloud/mocks/cloud_mock.go
  apiserver/facades/client/credentialmanager/client_integration_test.go
  apiserver/facades/client/credentialmanager/client_test.go
  apiserver/facades/client/modelmanager/modelmanager.go
  apiserver/facades/controller/migrationtarget/migrationtarget.go
  apiserver/facades/controller/migrationtarget/migrationtarget_test.go
  apiserver/testing/credential.go
  cmd/containeragent/initialize/package_test.go
  cmd/jujud/agent/bootstrap.go
  cmd/jujud/agent/machine_legacy_test.go
  domain/credential/bootstrap/bootstrap.go
  domain/credential/bootstrap/bootstrap_test.go
  domain/credential/modelmigration/export.go
  domain/credential/modelmigration/export_test.go
  domain/credential/modelmigration/import.go
  domain/credential/modelmigration/import_test.go
  domain/credential/modelmigration/migrations_mock_test.go
  domain/credential/service/service.go
  domain/credential/service/service_test.go
  domain/credential/service/state_mock_test.go
  domain/credential/state/state.go
  domain/credential/state/state_test.go
  domain/credential/state/types.go
  domain/credential/types.go
  domain/model/state/state_test.go
  environs/context/callcontext.go
  internal/migration/interface.go
  internal/migration/precheck.go
  internal/migration/precheck_test.go
  juju/testing/apiserver.go
  state/stateenvirons/config.go
  state/stateenvirons/config_test.go
  state/testing/policy.go
Labels: 4.0

#16457 Merge 2.9 to 3.1
  CONTRIBUTING.md
  apiserver/facades/agent/provisioner/imagemetadata_test.go
  apiserver/facades/agent/provisioner/provisioninginfo.go
  cmd/juju/commands/main_test.go
  core/base/supportedseries_test.go
  environs/bootstrap/bootstrap.go
  environs/bootstrap/bootstrap_test.go
  environs/simplestreams/datasource.go
  environs/simplestreams/datasource_test.go
  environs/simplestreams/testing/stub.go
  environs/storage/storage.go
  environs/storage/storage_test.go
  go.mod
  go.sum
  provider/openstack/local_test.go
  snap/snapcraft.yaml
Labels: 3.1

#16460 Merge 3.1 to 3.2
  CONTRIBUTING.md
  Makefile
  apiserver/facades/agent/provisioner/imagemetadata_test.go
  apiserver/facades/agent/provisioner/provisioninginfo.go
  cmd/juju/commands/main_test.go
  core/base/supportedseries_test.go
  environs/bootstrap/bootstrap.go
  environs/bootstrap/bootstrap_test.go
  environs/simplestreams/datasource.go
  environs/simplestreams/datasource_test.go
  environs/simplestreams/testing/stub.go
  environs/storage/storage.go
  environs/storage/storage_test.go
  go.mod
  go.sum
  provider/openstack/local_test.go
  snap/snapcraft.yaml
  worker/dbaccessor/package_test.go
Labels: 3.2

#16461 Merge 3.2 to 3.3
  CONTRIBUTING.md
  Makefile
  api/testing/macaroonsuite.go
  apiserver/facades/agent/provisioner/imagemetadata_test.go
  apiserver/facades/agent/provisioner/provisioninginfo.go
  cmd/juju/commands/main_test.go
  cmd/juju/status/status.go
  cmd/juju/status/status_internal_test.go
  core/base/supportedseries_test.go
  environs/bootstrap/bootstrap.go
  environs/bootstrap/bootstrap_test.go
  environs/simplestreams/datasource.go
  environs/simplestreams/datasource_test.go
  environs/simplestreams/testing/stub.go
  environs/storage/storage.go
  environs/storage/storage_test.go
  go.mod
  go.sum
  provider/openstack/local_test.go
  snap/snapcraft.yaml
  worker/dbaccessor/package_test.go
  worker/firewaller/firewaller_test.go
  worker/modelcache/worker_test.go
  worker/uniter/charm/bundles_test.go
  worker/uniter/charm/charm_test.go
  worker/uniter/resolver.go
  worker/uniter/resolver/loop.go
  worker/uniter/uniter.go
  worker/uniter/uniter_test.go
  worker/uniter/util_test.go
  worker/uniter/verifycharmprofile/verifycharmprofile.go
Labels: 3.3

#16446 Wireup apicaller tracer
  api/agent/agent/client.go
  api/base/caller.go
  api/base/caller_test.go
  api/base/clientfacade.go
  api/base/package_test.go
  apiserver/testing/fakeapi.go
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/agent/machine/manifolds_test.go
  core/trace/context.go
  core/trace/context_test.go
  core/trace/tracer.go
  rpc/server.go
  worker/agentconfigupdater/manifold.go
  worker/agentconfigupdater/manifold_test.go
  worker/trace/tracer.go
  worker/trace/tracer_test.go
  worker/trace/worker.go
Labels: 4.0

#16419 Remove Backups
  apiserver/backup.go
  apiserver/backup_test.go
  apiserver/export_test.go
  apiserver/facades/client/backups/backups.go
  apiserver/facades/client/backups/backups_test.go
  apiserver/facades/client/backups/create.go
  apiserver/facades/client/backups/create_test.go
  apiserver/facades/client/backups/domain_mock_test.go
  apiserver/facades/client/backups/export_test.go
  apiserver/facades/client/backups/mock_test.go
  apiserver/facades/client/backups/mongoinfo.go
  apiserver/facades/client/backups/package_test.go
  apiserver/facades/client/backups/register.go
  apiserver/facades/client/backups/shim.go
  cmd/juju/backups/create.go
  core/backups/metadata.go
  state/backups/backups.go
  state/backups/backups_test.go
  state/backups/create.go
  state/backups/create_test.go
  state/backups/db.go
  state/backups/db_dump_test.go
  state/backups/db_info_test.go
  state/backups/doc.go
  state/backups/exec.go
  state/backups/export_test.go
  state/backups/files.go
  state/backups/files_test.go
  state/backups/internal_test.go
  state/backups/legacy_test.go
  state/backups/metadata.go
  state/backups/package_test.go
  state/backups/testing/fakes.go
  state/backups/testing/suite.go
  state/backups/testing/testing.go
  tests/suites/backup/task.sh
Labels: 4.0

#16394 Add system identity public key to authorized_keys on new model configs
  controller/modelmanager/createmodel.go
  controller/modelmanager/createmodel_test.go
Labels: bug, 2.9

#16459 Prevent setting the authorized-keys model config
  apiserver/facades/client/modelconfig/modelconfig.go
  apiserver/facades/client/modelconfig/modelconfig_test.go
  cmd/juju/model/config.go
  cmd/juju/model/fakeenv_test.go
Labels: bug, 3.1

#16467 Export Oracle cloud models with region set from credentials
  state/migration_export.go
  state/migration_export_test.go
Labels: 2.9

#16462 Merge 3.3 to main
  CONTRIBUTING.md
  Makefile
  apiserver/facades/agent/provisioner/imagemetadata_test.go
  apiserver/facades/agent/provisioner/provisioninginfo.go
  cmd/juju/commands/main_test.go
  cmd/juju/status/status.go
  cmd/juju/status/status_internal_test.go
  core/base/supportedseries_test.go
  environs/bootstrap/bootstrap.go
  environs/bootstrap/bootstrap_test.go
  environs/simplestreams/datasource.go
  environs/simplestreams/datasource_test.go
  environs/simplestreams/testing/stub.go
  environs/storage/storage.go
  environs/storage/storage_test.go
  go.mod
  go.sum
  juju/testing/macaroonsuite.go
  provider/openstack/local_test.go
  snap/snapcraft.yaml
  worker/dbaccessor/package_test.go
  worker/metrics/collect/context_test.go
  worker/metrics/collect/handler_test.go
  worker/metrics/collect/manifold.go
  worker/metrics/collect/manifold_test.go
  worker/metrics/sender/sender_test.go
  worker/metrics/spool/manifold.go
  worker/metrics/spool/metrics.go
  worker/metrics/spool/metrics_test.go
  worker/uniter/charm/bundles_test.go
  worker/uniter/charm/charm_test.go
  worker/uniter/entity_mocks_test.go
  worker/uniter/resolver.go
  worker/uniter/resolver/loop.go
  worker/uniter/uniter.go
  worker/uniter/util_test.go
  worker/uniter/verifycharmprofile/verifycharmprofile.go
Labels: 4.0

#16393 Fixes problem with default region at oracle
  provider/oci/common/client.go
  provider/oci/provider.go
  provider/oci/provider_integration_test.go
Labels: bug, 3.3

#16472 Model config in bootstrap
  agent/agentbootstrap/bootstrap.go
  agent/agentbootstrap/bootstrap_test.go
  cmd/jujud/agent/bootstrap_test.go
  domain/modelconfig/bootstrap/bootstrap.go
  domain/modelconfig/bootstrap/bootstrap_test.go
  domain/modelconfig/bootstrap/package_test.go
  domain/modelconfig/service/coerce.go
  domain/modelconfig/service/service.go
  domain/modelconfig/state/state.go
  domain/modeldefaults/bootstrap/bootstrap.go
  internal/database/bootstrap.go
  internal/database/bootstrap_test.go
Labels: 4.0

#16480 Add correct watcher to catacomb
  worker/environ/environ.go
Labels: 2.9

#16479 Add cloud watcher and wire up to cloud spec notify watcher
  apiserver/common/cloudspec/cloudspec.go
  apiserver/common/cloudspec/cloudspec_test.go
  apiserver/common/cloudspec/statehelpers.go
  apiserver/common/mocks/credential_mock.go
  apiserver/common/modelmanagerinterface.go
  apiserver/facades/agent/agent/agent.go
  apiserver/facades/agent/caasagent/register.go
  apiserver/facades/agent/uniter/register.go
  apiserver/facades/agent/uniter/uniter.go
  apiserver/facades/client/controller/controller.go
  apiserver/facades/client/modelmanager/modelinfo_test.go
  apiserver/facades/controller/firewaller/firewaller_test.go
  apiserver/facades/controller/firewaller/register.go
  apiserver/facades/controller/undertaker/register.go
  domain/cloud/service/package_mock_test.go
  domain/cloud/service/package_test.go
  domain/cloud/service/service.go
  domain/cloud/service/service_test.go
  domain/cloud/state/state.go
  domain/cloud/state/state_test.go
  domain/servicefactory/controller.go
  state/allcollections.go
  state/watcher.go
  worker/environ/environ.go
Labels: 4.0

#16287 [JUJU-4619] Missing oracle cloud regions and list not being updated
  cloud/clouds_test.go
  cloud/fallback-public-cloud.yaml
  cloud/fallback_public_cloud.go
Labels: 3.1

#16434 [JUJU-4779] Clear hash, id and channel when switching to local charms
  cmd/juju/application/refresh_test.go
  cmd/juju/application/refresher/refresher.go
Labels: 2.9

#16437 Objectstore scaffolding
  apiserver/apiserver.go
  apiserver/charms.go
  apiserver/common/charms.go
  apiserver/export_test.go
  apiserver/facade/facadetest/context.go
  apiserver/facade/interface.go
  apiserver/facades/agent/secretsdrain/mocks/facade_mock.go
  apiserver/facades/client/charms/client.go
  apiserver/facades/client/charms/client_test.go
  apiserver/facades/client/charms/interfaces/downloader.go
  apiserver/facades/client/charms/mocks/state_mock.go
  apiserver/facades/client/charms/register.go
  apiserver/facades/client/charms/services/downloader.go
  apiserver/facades/client/charms/services/interfaces.go
  apiserver/facades/client/charms/services/mocks/interface_mocks.go
  apiserver/facades/client/charms/services/storage.go
  apiserver/facades/client/charms/services/storage_test.go
  apiserver/facades/controller/caasmodelconfigmanager/mocks/context_mock.go
  apiserver/facades/controller/charmdownloader/charmdownloader.go
  apiserver/facades/controller/charmdownloader/charmdownloader_test.go
  apiserver/facades/controller/charmdownloader/interfaces.go
  apiserver/facades/controller/charmdownloader/mocks/mocks.go
  apiserver/facades/controller/charmdownloader/register.go
  apiserver/rest.go
  apiserver/root.go
  apiserver/server_test.go
  apiserver/shared.go
  apiserver/shared_test.go
  cmd/jujud/agent/bootstrap.go
  cmd/jujud/agent/bootstrap_test.go
  cmd/jujud/agent/controllercharm.go
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/agent/machine/manifolds_test.go
  core/charm/downloader/downloader.go
  core/charm/downloader/downloader_test.go
  core/charm/downloader/mocks/storage_mocks.go
  core/objectstore/objectstore.go
  core/trace/attribute.go
  juju/testing/apiserver.go
  worker/apiserver/manifold.go
  worker/apiserver/manifold_test.go
  worker/apiserver/worker.go
  worker/apiserver/worker_state_test.go
  worker/apiserver/worker_test.go
  worker/objectstore/agent_mock_test.go
  worker/objectstore/clock_mock_test.go
  worker/objectstore/manifold.go
  worker/objectstore/manifold_test.go
  worker/objectstore/objectstore.go
  worker/objectstore/objectstore_mock_test.go
  worker/objectstore/package_test.go
  worker/objectstore/state_mock_test.go
  worker/objectstore/worker.go
  worker/objectstore/worker_test.go
Labels: 4.0

#16499 Remove generic base worker
  apiserver/facades/agent/storageprovisioner/storageprovisioner_caas_test.go
  internal/database/testing/dqlitesuite.go
  worker/objectstore/objectstore.go
Labels: 4.0

#16501 Stop panic in vsphere internal client
  provider/vsphere/internal/vsphereclient/client.go
Labels: 3.1

#16466 [JUJU-4822] Fix help text in model-defaults
  cmd/juju/model/defaults.go
Labels: 3.3

#16496 Wire upgrade service in migration checks.
  apiserver/facades/client/controller/controller.go
  apiserver/facades/client/controller/export_test.go
  apiserver/facades/client/controller/register.go
  apiserver/facades/controller/migrationmaster/facade.go
  apiserver/facades/controller/migrationmaster/facade_test.go
  apiserver/facades/controller/migrationmaster/mocks/backend.go
  apiserver/facades/controller/migrationmaster/mocks/precheckbackend.go
  apiserver/facades/controller/migrationmaster/package_test.go
  apiserver/facades/controller/migrationmaster/register.go
  apiserver/facades/controller/migrationtarget/domain_mock_test.go
  apiserver/facades/controller/migrationtarget/migrationtarget.go
  apiserver/facades/controller/migrationtarget/migrationtarget_test.go
  apiserver/facades/controller/migrationtarget/package_test.go
  apiserver/facades/controller/migrationtarget/register.go
  cmd/containeragent/unit/agent.go
  cmd/jujud/agent/machine.go
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/agent/machine/manifolds_test.go
  cmd/jujud/agent/model.go
  domain/upgrade/service/service.go
  domain/upgrade/service/service_test.go
  internal/migration/interface.go
  internal/migration/migration.go
  internal/migration/migration_mock_test.go
  internal/migration/migration_test.go
  internal/migration/package_test.go
  internal/migration/precheck.go
  internal/migration/precheck_test.go
  internal/upgrade/agent_mock_test.go
  internal/upgrade/lock.go
  internal/upgrade/lock_mock_test.go
  internal/upgrade/lock_test.go
  internal/upgrade/package_test.go
  internal/upgradesteps/worker.go
  worker/upgradedatabase/worker.go
  worker/upgradedatabase/worker_test.go
Labels: 4.0

#16464 Wireup charmhub tracer
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/deployrepository.go
  apiserver/facades/client/application/deployrepository_mocks_test.go
  apiserver/facades/client/application/deployrepository_test.go
  apiserver/facades/client/application/repository_mocks_test.go
  apiserver/facades/client/application/updatebase.go
  apiserver/facades/client/application/updatebase_mocks_test.go
  apiserver/facades/client/application/updatebase_test.go
  apiserver/facades/client/charms/client.go
  apiserver/facades/client/charms/client_test.go
  apiserver/facades/client/charms/interfaces/downloader.go
  apiserver/facades/client/charms/mocks/repository.go
  apiserver/facades/client/charms/services/downloader.go
  apiserver/facades/client/charms/services/repofactory.go
  apiserver/facades/client/charms/services/repofactory_test.go
  apiserver/facades/client/machinemanager/machinemanager.go
  apiserver/facades/client/machinemanager/mocks/upgradebase_mock.go
  apiserver/facades/client/machinemanager/upgradebase.go
  apiserver/facades/client/machinemanager/upgradebase_test.go
  apiserver/facades/client/resources/facade.go
  apiserver/facades/client/resources/mocks/backend.go
  apiserver/facades/client/resources/repository.go
  apiserver/facades/client/resources/server_addpending_test.go
  apiserver/facades/controller/charmdownloader/interfaces.go
  cmd/jujud/agent/bootstrap_test.go
  cmd/jujud/agent/controllercharm.go
  core/charm/downloader/downloader.go
  core/charm/downloader/downloader_test.go
  core/charm/downloader/export_test.go
  core/charm/downloader/mocks/charm_archive_mocks.go
  core/charm/downloader/mocks/repo_mocks.go
  core/charm/repository.go
  core/charm/repository/charmhub.go
  core/charm/repository/charmhub_test.go
  internal/charmhub/download.go
  internal/charmhub/find.go
  internal/charmhub/info.go
  internal/charmhub/refresh.go
  internal/charmhub/resources.go
Labels: 4.0

#16521 Cleanup with objectstore
  apiserver/facades/controller/cleaner/cleaner.go
  apiserver/facades/controller/cleaner/cleaner_test.go
  apiserver/facades/controller/cleaner/register.go
  apiserver/facades/controller/cleaner/state.go
  cmd/jujud/agent/machine/manifolds.go
  internal/objectstore/factory.go
  internal/objectstore/stateobjectstore.go
  juju/testing/apiserver.go
  state/application_test.go
  state/charm.go
  state/charm_test.go
  state/cleanup.go
  state/cleanup_test.go
  state/enableha_test.go
  state/export_test.go
  state/machine_test.go
  state/machine_upgradeseries_test.go
  state/minimumunits_test.go
  state/model_test.go
  state/payloads_test.go
  state/relation_test.go
  state/relationunit_test.go
  state/state_test.go
  state/unit_test.go
  worker/objectstore/manifold.go
  worker/objectstore/manifold_test.go
  worker/objectstore/worker.go
  worker/objectstore/worker_test.go
Labels: 4.0
