Repository juju/juju, pull requests merged in 2024-01, with the labels that each got.

#16711 Add spaces services methods to network domain
  domain/network/service/space.go
  domain/network/service/space_test.go
  domain/network/service/state_mock_test.go
  domain/network/state/space.go
  domain/network/state/space_test.go
  domain/network/state/subnet_test.go
Labels: 4.0

#16725 Add subnet methods to the network domain service layer
  domain/network/service/interface.go
  domain/network/service/space.go
  domain/network/service/state_mock_test.go
  domain/network/service/subnet.go
  domain/network/service/subnet_test.go
  domain/network/state/subnet.go
  go.mod
Labels: 4.0

#16728 Merge 2.9
  api/apiclient.go
  api/apiclient_test.go
  apiserver/admin.go
  apiserver/errors/errors.go
  apiserver/errors/errors_test.go
  apiserver/export_test.go
  apiserver/facades/client/application/application_unit_test.go
  apiserver/restrict_newer_client.go
  apiserver/restrict_newer_client_test.go
  apiserver/root.go
  rpc/params/apierror.go
Labels: 3.1

#16729 Update juju/charms dep and fix erroneous names/v4 import
  domain/network/service/space.go
  go.mod
  go.sum
Labels: 4.0

#16730 Merge 3.1
  api/apiclient.go
  api/apiclient_test.go
  apiserver/admin.go
  apiserver/errors/errors.go
  apiserver/errors/errors_test.go
  apiserver/export_test.go
  apiserver/facades/client/application/application_unit_test.go
  apiserver/restrict_newer_client.go
  apiserver/restrict_newer_client_test.go
  apiserver/root.go
  rpc/params/apierror.go
Labels: 3.3

#16731 Merge 3.3
  api/apiclient.go
  api/apiclient_test.go
  apiserver/admin.go
  apiserver/errors/errors.go
  apiserver/errors/errors_test.go
  apiserver/export_test.go
  apiserver/facades/client/application/application_unit_test.go
  apiserver/restrict_newer_client.go
  apiserver/restrict_newer_client_test.go
  apiserver/root.go
  rpc/params/apierror.go
Labels: 3.4

#16718 Homogenize vm naming in azure and aws
  provider/azure/environ.go
  provider/azure/environ_test.go
  provider/azure/environprovider.go
  provider/ec2/environ.go
  provider/ec2/local_test.go
  provider/ec2/provider.go
Labels: bug, 3.4

#16736 File potential race in object store
  internal/objectstore/fileobjectstore.go
  internal/objectstore/fileobjectstore_test.go
Labels: 4.0

#16689 Split logger for charms
  apiserver/common/charmhub.go
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/deployrepository.go
  apiserver/facades/client/charms/client.go
  apiserver/facades/client/charms/services/downloader.go
  apiserver/facades/client/charms/services/repofactory.go
  apiserver/facades/client/charms/services/repofactory_test.go
  apiserver/facades/client/charms/services/storage.go
  apiserver/facades/client/machinemanager/machinemanager.go
  apiserver/facades/client/resources/facade.go
  apiserver/facades/controller/charmdownloader/charmdownloader.go
  cmd/juju/application/deploy.go
  cmd/juju/application/diffbundle.go
  cmd/juju/application/refresh.go
  cmd/juju/charmhub/download.go
  cmd/juju/charmhub/find.go
  cmd/juju/charmhub/info.go
  cmd/jujud/agent/controllercharm.go
  cmd/jujud/agent/machine.go
  core/flags/flags.go
  internal/charmhub/client.go
  internal/charmhub/client_mock_test.go
  internal/charmhub/download_test.go
  internal/charmhub/errors_test.go
  internal/charmhub/fake_test.go
  internal/charmhub/find_test.go
  internal/charmhub/http.go
  internal/charmhub/http_test.go
  internal/charmhub/info_test.go
  internal/charmhub/logger.go
  internal/charmhub/package_test.go
  internal/charmhub/refresh_test.go
  internal/charmhub/resources_test.go
  internal/resource/charmhub.go
  internal/worker/bootstrap/worker_test.go
  scripts/charmhub/locate-series-less-charms.go
  testing/logger.go
Labels: 4.0

#16739 Merge 3.4
  apiserver/facades/client/application/application_unit_test.go
  cmd/containeragent/unit/manifolds.go
  cmd/jujud/agent/machine/manifolds.go
  core/logger/labels.go
  internal/migration/migration.go
  internal/worker/deployer/unit_manifolds.go
  internal/worker/migrationmaster/worker.go
  provider/azure/environ.go
  provider/azure/environ_test.go
  provider/azure/environprovider.go
  provider/ec2/environ.go
  provider/ec2/local_test.go
  provider/ec2/provider.go
  tests/includes/juju.sh
  tests/suites/model/migration.sh
Labels: 4.0

#16738 Add description column to flag table
  core/flags/flags.go
  domain/flag/service/service.go
  domain/flag/service/service_test.go
  domain/flag/service/state_mock_test.go
  domain/flag/state/state.go
  domain/flag/state/state_test.go
  domain/schema/controller.go
  internal/worker/bootstrap/bootstrap_mock_test.go
  internal/worker/bootstrap/manifold.go
  internal/worker/bootstrap/worker.go
  internal/worker/bootstrap/worker_test.go
Labels: 4.0

#16742 Remove objects endpoint
  apiserver/apiserver.go
  apiserver/objects.go
  apiserver/objects_test.go
Labels: 4.0

#16698 Ensure we release state once done
  apiserver/apiserver.go
  apiserver/httpcontext.go
  apiserver/rest.go
Labels: 3.1

#16694 Bootstrap worker controller charm infrastructure
  apiserver/facades/client/charms/services/repofactory.go
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/agent/machine/manifolds_test.go
  internal/bootstrap/agentbinary.go
  internal/bootstrap/bootstrap_mock_test.go
  internal/bootstrap/charm_mock_test.go
  internal/bootstrap/controller.go
  internal/bootstrap/controller_test.go
  internal/bootstrap/deployer.go
  internal/bootstrap/deployer_caas.go
  internal/bootstrap/deployer_caas_test.go
  internal/bootstrap/deployer_iaas.go
  internal/bootstrap/deployer_iaas_test.go
  internal/bootstrap/deployer_test.go
  internal/bootstrap/downloader_mock_test.go
  internal/bootstrap/objectstore_mock_test.go
  internal/bootstrap/package_test.go
  internal/worker/bootstrap/bootstrap_mock_test.go
  internal/worker/bootstrap/manifold.go
  internal/worker/bootstrap/manifold_test.go
  internal/worker/bootstrap/package_test.go
  internal/worker/bootstrap/worker.go
  internal/worker/bootstrap/worker_test.go
Labels: 4.0

#16726 Prevent file backed objectstore in ha mode
  apiserver/facades/client/highavailability/highavailability.go
  apiserver/facades/client/highavailability/highavailability_test.go
Labels: 4.0

#16755 Relocate charm services package
  apiserver/charms.go
  apiserver/facades/client/application/backend.go
  apiserver/facades/client/application/deployrepository.go
  apiserver/facades/client/application/deployrepository_mocks_test.go
  apiserver/facades/client/application/mocks/application_mock.go
  apiserver/facades/client/charms/client.go
  apiserver/facades/client/charms/interface.go
  apiserver/facades/client/charms/interfaces/state.go
  apiserver/facades/client/charms/mocks/state_mock.go
  apiserver/facades/client/charms/register.go
  apiserver/facades/client/charms/services/export_test.go
  apiserver/facades/controller/charmdownloader/charmdownloader.go
  apiserver/facades/controller/charmdownloader/charmdownloader_test.go
  apiserver/facades/controller/charmdownloader/interfaces.go
  apiserver/facades/controller/charmdownloader/mocks/mocks.go
  apiserver/facades/controller/charmdownloader/register.go
  apiserver/facades/controller/charmdownloader/shims.go
  cmd/jujud/agent/bootstrap_test.go
  cmd/jujud/agent/controllercharm.go
  internal/bootstrap/bootstrap_mock_test.go
  internal/bootstrap/deployer.go
  internal/bootstrap/deployer_test.go
  internal/bootstrap/package_test.go
  internal/charm/services/downloader.go
  internal/charm/services/interface_mocks_test.go
  internal/charm/services/interfaces.go
  internal/charm/services/package_test.go
  internal/charm/services/repofactory.go
  internal/charm/services/repofactory_test.go
  internal/charm/services/storage.go
  internal/charm/services/storage_test.go
Labels: 4.0

#16749 Inject explicitly user service in usermanager facade
  apiserver/facades/client/usermanager/domain_mock_test.go
  apiserver/facades/client/usermanager/package_test.go
  apiserver/facades/client/usermanager/register.go
  apiserver/facades/client/usermanager/usermanager.go
  apiserver/facades/client/usermanager/usermanager_test.go
  domain/servicefactory/controller.go
  domain/servicefactory/testing/service.go
  internal/servicefactory/interface.go
  internal/worker/servicefactory/servicefactory_mock_test.go
  internal/worker/upgradedatabase/servicefactory_mock_test.go
Labels: 4.0

#16754 Add GetAllUsers func to user service
  domain/user/service/service.go
  domain/user/service/state_mock_test.go
  domain/user/state/state.go
  domain/user/state/state_test.go
Labels: 4.0

#16748 Objectstore preemptive get
  internal/objectstore/fileobjectstore.go
  internal/objectstore/fileobjectstore_test.go
Labels: 4.0

#16760 Fix races in machine upgrade steps worker hook functions.
  internal/worker/upgradestepsmachine/machineworker_test.go
Labels: 4.0

#16761 Fix k8s permissions to allow cross model secrets to work with rbac
  apiserver/facades/controller/crossmodelsecrets/crossmodelsecrets.go
  apiserver/facades/controller/crossmodelsecrets/crossmodelsecrets_test.go
  apiserver/facades/controller/crossmodelsecrets/register.go
  caas/kubernetes/provider/application/application_test.go
  caas/kubernetes/provider/application/trust.go
  caas/kubernetes/provider/application/trust_test.go
Labels: 3.1

#16762 Merge 3.1
  apiserver/apiserver.go
  apiserver/facades/controller/crossmodelsecrets/crossmodelsecrets.go
  apiserver/facades/controller/crossmodelsecrets/crossmodelsecrets_test.go
  apiserver/facades/controller/crossmodelsecrets/register.go
  apiserver/httpcontext.go
  apiserver/rest.go
  caas/kubernetes/provider/application/application_test.go
  caas/kubernetes/provider/application/trust.go
  caas/kubernetes/provider/application/trust_test.go
Labels: 3.3

#16686 [JUJU-5194] - Discharge CMR macaroon to Jaas endpoint for external users;
  apiserver/authentication/jwt/jwt.go
  apiserver/authentication/jwt/jwt_test.go
  apiserver/common/crossmodel/auth.go
  apiserver/common/crossmodel/auth_test.go
  apiserver/common/crossmodel/bakery.go
  apiserver/common/crossmodel/bakery_test.go
  apiserver/common/crossmodel/mocks/authentication_mock.go
  apiserver/common/crossmodel/mocks/bakery_mock.go
  apiserver/common/crossmodel/mocks/bakerystorage_mock.go
  apiserver/common/crossmodel/mocks/crossmodel_mock.go
  apiserver/common/crossmodel/mocks/http_mock.go
  apiserver/common/crossmodel/package_test.go
  apiserver/facades/client/applicationoffers/access_test.go
  apiserver/facades/client/applicationoffers/applicationoffers_test.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations_test.go
  apiserver/facades/controller/crossmodelsecrets/crossmodelsecrets_test.go
  apiserver/offerauth.go
  apiserver/root.go
  docker/registry/internal/base_client_test.go
Labels: bug, 3.3

#16774 Merge 2.9 to 3.1
  allowed_signers
Labels: 3.1

#16766 S3Client PUT and DELETE methods
  cmd/containeragent/unit/manifolds.go
  core/objectstore/objectstore.go
  internal/objectstore/fileobjectstore.go
  internal/s3client/charmclient.go
  internal/s3client/charmclient_test.go
  internal/s3client/client.go
  internal/s3client/client_mock_test.go
  internal/s3client/client_test.go
  internal/s3client/package_test.go
  internal/s3client/session_mock_test.go
  internal/worker/deployer/unit_manifolds.go
  internal/worker/s3caller/manifold.go
  internal/worker/s3caller/manifold_test.go
  internal/worker/s3caller/package_mock_test.go
Labels: 4.0

#16778 Use a noop rate limiter in the aws sdk s3 client
  worker/s3caller/client.go
Labels: bug, 3.3

#16779 Remove a log line left in for debug in cmr auth
  apiserver/common/crossmodel/bakery.go
Labels: 3.3

#16780 Merge 3.3
  apiserver/common/crossmodel/bakery.go
  internal/s3client/client.go
Labels: 3.4

#16708 Propagates errors from start instance for each zone.
  provider/common/bootstrap.go
  provider/common/bootstrap_test.go
  provider/maas/maas_environ_whitebox_test.go
Labels: 3.3

#16781 Store cmr macaroon discharge endpoint on the context
  apiserver/common/crossmodel/auth.go
  apiserver/common/crossmodel/bakery.go
  apiserver/common/crossmodel/bakery_test.go
  apiserver/common/crossmodel/mocks/crossmodel_mock.go
  apiserver/common/crossmodel/package_test.go
  tests/includes/juju.sh
  tests/suites/cli/display_clouds.sh
  tests/suites/metrics/metrics.sh
Labels: 3.3

#16757 Ensure goroutines do not leak
  internal/changestream/eventmultiplexer/package_test.go
  internal/changestream/stream/package_test.go
  internal/changestream/stream/stream_test.go
  internal/database/app/dqlite_linux.go
  internal/database/app/dqlite_linux_test.go
  internal/database/app/package_test.go
  internal/worker/bootstrap/package_test.go
  internal/worker/changestream/package_test.go
  internal/worker/changestreampruner/package_test.go
  internal/worker/dbaccessor/package_test.go
  internal/worker/dbaccessor/worker_integration_test.go
Labels: 4.0

#16771 Very minimal machine state and service implementation for dqlite
  domain/blockdevice/state/state.go
  domain/machine/bootstrap/bootstrap.go
  domain/machine/bootstrap/bootstrap_test.go
  domain/machine/bootstrap/package_test.go
  domain/machine/service/package_mock_test.go
  domain/machine/service/package_test.go
  domain/machine/service/service.go
  domain/machine/service/service_test.go
  domain/machine/state/package_test.go
  domain/machine/state/state.go
  domain/machine/state/state_test.go
Labels: 4.0

#16783 ObjectStore: S3 Static Credentials
  controller/config.go
  controller/config_test.go
  controller/configschema.go
  state/controller_test.go
Labels: 4.0

#16751 Bootstrap worker: Deploy charm and add application
  cmd/jujud/agent/bootstrap.go
  cmd/jujud/agent/bootstrap_test.go
  cmd/jujud/agent/controllercharm.go
  cmd/jujud/agent/machine/manifolds.go
  internal/bootstrap/bootstrap_mock_test.go
  internal/bootstrap/controller.go
  internal/bootstrap/controller_test.go
  internal/bootstrap/deployer.go
  internal/bootstrap/deployer_caas.go
  internal/bootstrap/deployer_caas_test.go
  internal/bootstrap/deployer_test.go
  internal/bootstrap/package_test.go
  internal/charmhub/client.go
  internal/worker/bootstrap/bootstrap_mock_test.go
  internal/worker/bootstrap/deployer.go
  internal/worker/bootstrap/manifold.go
  internal/worker/bootstrap/manifold_test.go
  internal/worker/bootstrap/package_test.go
  internal/worker/bootstrap/worker.go
  internal/worker/bootstrap/worker_test.go
Labels: 4.0

#16763 Inject GetUserWithAuthInfo func in the User domain
  core/user/user.go
  domain/user/service/service.go
  domain/user/service/service_test.go
  domain/user/service/state_mock_test.go
  domain/user/state/state.go
  domain/user/state/state_test.go
  domain/user/state/types.go
Labels: 4.0

#16794 Improve Merge/Upgrade Github Actions
  .github/workflows/build.yml
  .github/workflows/client-tests.yml
  .github/workflows/gen.yml
  .github/workflows/license.yml
  .github/workflows/migrate.yml
  .github/workflows/smoke.yml
  .github/workflows/snap.yml
  .github/workflows/static-analysis.yml
  .github/workflows/upgrade.yml
  worker/state/statetracker_test.go
Labels: 3.3

#16798 [JUJU-5301] Add region polandcentral to azure public cloud
  cloud/fallback-public-cloud.yaml
  cloud/fallback_public_cloud.go
Labels: 3.1

#16803 Namespace the file objectstore
  internal/objectstore/fileobjectstore.go
  internal/objectstore/fileobjectstore_test.go
Labels: 4.0

#16792 Add terraform provider for juju smoke test workflow.
  .github/workflows/terraform-smoke.yml
Labels: 2.9, github_actions

#16800 Merge 3.3 to 3.4
  .github/workflows/build.yml
  .github/workflows/client-tests.yml
  .github/workflows/gen.yml
  .github/workflows/license.yml
  .github/workflows/migrate.yml
  .github/workflows/smoke.yml
  .github/workflows/snap.yml
  .github/workflows/static-analysis.yml
  .github/workflows/upgrade.yml
  worker/state/statetracker_test.go
Labels: 3.4

#16808 Merge from three three
  .github/workflows/terraform-smoke.yml
  allowed_signers
  cloud/fallback-public-cloud.yaml
  cloud/fallback_public_cloud.go
Labels: 3.4

#16785 Add auth to charm upload S3 endpoint
  apiserver/apiserver.go
Labels: 3.4

#16787 Save and delete machine rows in dqlite as machines are saved to mongo
  agent/agentbootstrap/bootstrap.go
  apiserver/facades/agent/unitassigner/register.go
  apiserver/facades/agent/unitassigner/state.go
  apiserver/facades/agent/unitassigner/unitassigner.go
  apiserver/facades/agent/unitassigner/unitassigner_test.go
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/application_test.go
  apiserver/facades/client/application/application_unit_test.go
  apiserver/facades/client/application/deploy.go
  apiserver/facades/client/application/get_test.go
  apiserver/facades/client/application/mocks/domain_mock.go
  apiserver/facades/client/application/package_test.go
  apiserver/facades/client/machinemanager/instance_information_test.go
  apiserver/facades/client/machinemanager/machinemanager.go
  apiserver/facades/client/machinemanager/machinemanager_test.go
  apiserver/facades/client/machinemanager/mocks/domain_mock.go
  apiserver/facades/client/machinemanager/mocks/types_mock.go
  apiserver/facades/client/machinemanager/package_test.go
  apiserver/facades/client/machinemanager/state.go
  apiserver/facades/controller/cleaner/cleaner.go
  apiserver/facades/controller/cleaner/cleaner_test.go
  apiserver/facades/controller/cleaner/register.go
  apiserver/facades/controller/cleaner/state.go
  apiserver/facades/controller/machineundertaker/register.go
  apiserver/facades/controller/machineundertaker/undertaker.go
  apiserver/facades/controller/machineundertaker/undertaker_test.go
  domain/servicefactory/model.go
  domain/servicefactory/testing/service.go
  generate/schemagen/schemagen.go
  internal/servicefactory/interface.go
  internal/worker/servicefactory/servicefactory_mock_test.go
  state/application_test.go
  state/cleanup.go
  state/cleanup_test.go
  state/enableha_test.go
  state/machine_test.go
  state/machine_upgradeseries_test.go
  state/minimumunits_test.go
  state/model_test.go
  state/payloads_test.go
  state/relation_test.go
  state/relationunit_test.go
  state/state_test.go
  state/unit_test.go
Labels: 4.0

#16804 Remove redundant base -> series -> base in local charm deploy
  cmd/juju/application/deployer/charm.go
  cmd/juju/application/deployer/deployer.go
Labels: 3.4

#16809 Add GetUserWithAuth function in user domain
  domain/user/errors/errors.go
  domain/user/service/service.go
  domain/user/service/service_test.go
  domain/user/service/state_mock_test.go
  domain/user/state/state.go
  domain/user/state/state_test.go
  domain/user/state/types.go
Labels: 4.0

#16797 Allow model migrations to use the model DB
  apiserver/facade/facadetest/context.go
  apiserver/facade/interface.go
  apiserver/facades/agent/secretsdrain/mocks/facade_mock.go
  apiserver/facades/agent/secretsdrain/package_test.go
  apiserver/facades/agent/secretsdrain/register_test.go
  apiserver/facades/client/modelmanager/modelmanager.go
  apiserver/facades/client/modelmanager/register.go
  apiserver/facades/controller/caasmodelconfigmanager/facade_test.go
  apiserver/facades/controller/caasmodelconfigmanager/mocks/context_mock.go
  apiserver/facades/controller/caasmodelconfigmanager/package_test.go
  apiserver/facades/controller/migrationmaster/facade.go
  apiserver/facades/controller/migrationmaster/register.go
  apiserver/facades/controller/migrationtarget/domain_mock_test.go
  apiserver/facades/controller/migrationtarget/migrationtarget.go
  apiserver/facades/controller/migrationtarget/migrationtarget_test.go
  apiserver/facades/controller/migrationtarget/package_test.go
  apiserver/root.go
  domain/user/service/service_test.go
  internal/migration/migration.go
Labels: 4.0

#16814 Remove legacy fallback case
  apiserver/facades/client/charms/client.go
  apiserver/facades/client/charms/client_test.go
Labels: 3.4

#16789 Add environ to bootstrap worker
  cmd/jujud/agent/machine.go
  cmd/jujud/agent/machine/manifolds.go
  internal/bootstrap/bootstrap_mock_test.go
  internal/bootstrap/deployer.go
  internal/worker/bootstrap/bootstrap_mock_test.go
  internal/worker/bootstrap/deployer_mock_test.go
  internal/worker/bootstrap/manifold.go
  internal/worker/bootstrap/manifold_test.go
  internal/worker/bootstrap/package_test.go
  internal/worker/bootstrap/worker.go
  internal/worker/bootstrap/worker_test.go
Labels: 4.0

#16811 Add migration support for block devices
  core/modelmigration/description_mock_test.go
  domain/blockdevice/modelmigration/export.go
  domain/blockdevice/modelmigration/export_test.go
  domain/blockdevice/modelmigration/import.go
  domain/blockdevice/modelmigration/import_test.go
  domain/blockdevice/modelmigration/migrations_mock_test.go
  domain/blockdevice/modelmigration/package_test.go
  domain/blockdevice/service/package_test.go
  domain/blockdevice/service/service.go
  domain/blockdevice/service/service_test.go
  domain/blockdevice/service/state_mock_test.go
  domain/blockdevice/state/state.go
  domain/blockdevice/state/state_test.go
  domain/blockdevice/state/types.go
  domain/blockdevice/types.go
  domain/filesystem/filesystemtype.go
  domain/filesystem/filesystemtype_test.go
  domain/filesystem/package_test.go
  domain/machine/state/state_test.go
  domain/modelmigration/export.go
  domain/modelmigration/import.go
  domain/schema/model.go
  domain/schema/schema_test.go
  go.mod
  go.sum
Labels: 4.0

#16768 DDL schema for permissions
  domain/schema/controller.go
  domain/schema/schema_test.go
Labels: 4.0

#16820 Use list of parameters instead user struct in AddUser* functions
  domain/user/bootstrap/bootstrap.go
  domain/user/service/service.go
  domain/user/service/service_test.go
  domain/user/service/state_mock_test.go
  domain/user/state/state.go
  domain/user/state/state_test.go
Labels: 4.0

#16764 Complete storage schema with volume, filesystem and attachment info, plus attachment plans
  domain/schema/model.go
  domain/schema/schema_test.go
Labels: 4.0

#16813 Wires up user correlation for models in DQlite.
  agent/agentbootstrap/bootstrap.go
  api/package_test.go
  cmd/containeragent/initialize/package_test.go
  cmd/containeragent/unit/package_test.go
  cmd/jujud/agent/bootstrap.go
  core/model/defaults.go
  core/multiwatcher/package_test.go
  core/user/defaults.go
  domain/cloud/state/state.go
  domain/cloud/state/state_test.go
  domain/credential/state/state_test.go
  domain/model/service/service.go
  domain/model/service/service_test.go
  domain/model/state/state.go
  domain/model/state/state_test.go
  domain/model/types.go
  domain/model/types_test.go
  domain/schema/controller.go
Labels: 4.0

#16819 Change signature for GetUserByAuth to use name and password
  domain/user/service/service.go
  domain/user/service/service_test.go
  domain/user/service/state_mock_test.go
  domain/user/state/state.go
  domain/user/state/state_test.go
Labels: 4.0

#16796 Create corresponding S3-compatible migrate endpoint for charms
  api/controller/migrationtarget/client.go
  api/controller/migrationtarget/client_test.go
  apiserver/apiserver.go
  apiserver/objects.go
  migration/migration.go
  migration/migration_test.go
  worker/migrationmaster/worker.go
Labels: 3.4

#16793 Service layer for annotations domain
  core/annotations/annotations.go
  core/annotations/annotations_test.go
  domain/annotation/service/package_test.go
  domain/annotation/service/service.go
  domain/annotation/service/service_test.go
  domain/annotation/service/state_mock_test.go
Labels: 4.0

#16822 Always verify result exists when looking for map entries.
  controller/modelmanager/createmodel.go
  controller/modelmanager/createmodel_test.go
Labels: bug, 3.3

#16833 Support minikube env folder on juju snap
  snap/snapcraft.yaml
Labels: 3.4

#16844 Support minikube env folder on juju snap
  snap/snapcraft.yaml
Labels: bug, 3.1

#16851 Rollback changes on snapcraft.yaml including minikube env files
  snap/snapcraft.yaml
Labels: bug, 3.4

#16850 Remove DefaultEndpointBindingSpace from legacy state
  apiserver/common/modelmanagerinterface.go
  apiserver/facades/client/application/deployrepository.go
  apiserver/facades/client/application/deployrepository_mocks_test.go
  apiserver/facades/client/application/mocks/application_mock.go
  apiserver/facades/client/spaces/package_mock_test.go
  environs/space/spaces.go
  environs/space/spaces_mock_test.go
  environs/space/spaces_test.go
  state/endpoint_bindings.go
  state/endpoint_bindings_test.go
  state/mocks/endpointbinding_mock.go
Labels: 4.0

#16856 Rename to correct error type in user domain
  domain/user/service/service.go
  domain/user/state/state.go
Labels: 4.0

#16859 Fixes minimal image selection for amd64 on OCI.
  provider/oci/images.go
  provider/oci/images_integration_test.go
Labels: 3.3

#16826 [SQLair] Replace slice queries in domain/modelconfig/state
  domain/modelconfig/state/state.go
Labels: 4.0

#16846 undertaker RemoveModel() handles secrets config not found
  apiserver/facades/controller/machineundertaker/backend.go
  apiserver/facades/controller/undertaker/undertaker.go
  apiserver/facades/controller/undertaker/undertaker_test.go
Labels: 3.3

#16854 Move address finding out of the worker
  cmd/jujud/agent/machine/manifolds.go
  internal/worker/bootstrap/addressfinder.go
  internal/worker/bootstrap/manifold.go
  internal/worker/bootstrap/manifold_test.go
  internal/worker/bootstrap/worker.go
  internal/worker/bootstrap/worker_test.go
Labels: 4.0

#16812 Introduces a new model table to describe agent information.
  domain/schema/controller.go
  domain/schema/schema_test.go
Labels: 4.0

#16863 Bind dbaccessor to loopback for k8s
  agent/agentbootstrap/bootstrap.go
  cmd/jujud/agent/agenttest/agent.go
  cmd/jujud/agent/machine/manifolds.go
  database/bootstrap.go
  database/bootstrap_test.go
  database/node.go
  database/node_test.go
  featuretests/dblog_test.go
  worker/dbaccessor/manifold.go
  worker/dbaccessor/manifold_test.go
  worker/dbaccessor/package_mock_test.go
  worker/dbaccessor/package_test.go
  worker/dbaccessor/worker.go
  worker/dbaccessor/worker_test.go
Labels: 3.3

#16872 Write dqlite machine rows after enable-ha adds new controller machines
  apiserver/facades/client/highavailability/highavailability.go
  apiserver/facades/client/highavailability/register.go
Labels: 4.0

#16869 Fix RegisterCredentials for kubernetes provider.
  caas/kubernetes/provider/cloud.go
  caas/kubernetes/provider/credentials.go
  caas/kubernetes/provider/credentials_test.go
Labels: 4.0

#16866 Remove the need for ha-space on the peergrouper
  internal/worker/peergrouper/controllertracker.go
  internal/worker/peergrouper/controllertracker_test.go
  internal/worker/peergrouper/desired.go
  internal/worker/peergrouper/desired_test.go
  internal/worker/peergrouper/mock_test.go
  internal/worker/peergrouper/shim.go
  internal/worker/peergrouper/worker.go
  internal/worker/peergrouper/worker_test.go
Labels: 4.0
