Repository juju/juju, pull requests merged in 2024-05, with the labels that each got.

#17315 Move secrets logic which uses an external backend to the service
  apiserver/facades/agent/secretsdrain/state.go
  apiserver/facades/agent/secretsmanager/mocks/secrets.go
  apiserver/facades/agent/secretsmanager/secrets.go
  apiserver/facades/agent/secretsmanager/secrets_test.go
  apiserver/facades/agent/secretsmanager/service.go
  apiserver/facades/agent/uniter/export_test.go
  apiserver/facades/agent/uniter/leadership_mocks_test.go
  apiserver/facades/agent/uniter/package_test.go
  apiserver/facades/agent/uniter/register.go
  apiserver/facades/agent/uniter/secret_mocks_test.go
  apiserver/facades/agent/uniter/secrets.go
  apiserver/facades/agent/uniter/secrets_test.go
  apiserver/facades/agent/uniter/uniter.go
  apiserver/facades/agent/uniter/uniter_apierror_test.go
  apiserver/facades/agent/uniter/uniter_cloudspec_test.go
  apiserver/facades/client/secrets/mocks/secretsbackend.go
  apiserver/facades/client/secrets/mocks/secretservice.go
  apiserver/facades/client/secrets/package_test.go
  apiserver/facades/client/secrets/register.go
  apiserver/facades/client/secrets/secrets.go
  apiserver/facades/client/secrets/secrets_test.go
  apiserver/facades/client/secrets/service.go
  apiserver/facades/schema.json
  domain/secret/service/delete.go
  domain/secret/service/package_test.go
  domain/secret/service/params.go
  domain/secret/service/provider_mock_test.go
  domain/secret/service/service.go
  domain/secret/service/service_test.go
  domain/secret/state/state.go
  domain/secret/state/state_test.go
Labels: 4.0

#17312 Restructure core/base slightly
  core/base/base.go
  core/base/base_test.go
  core/base/series.go
  core/base/series_test.go
  core/base/supportedbases.go
  core/base/supportedseries.go
  core/base/supportedseries_test.go
Labels: 4.0

#17321 Merge up 3.3 to 3.4
  .github/workflows/cla.yml
  .github/workflows/terraform-smoke.yml
  go.mod
  go.sum
Labels: 3.4

#17320 Rename vsphere template dir
  provider/vsphere/environ_broker.go
  provider/vsphere/environ_broker_test.go
  provider/vsphere/internal/vsphereclient/createvm.go
  provider/vsphere/internal/vsphereclient/createvm_test.go
  provider/vsphere/vm_template.go
  provider/vsphere/vm_template_test.go
Labels: 3.6

#17316 Simplify model config service creation.
  apiserver/facades/client/modelmanager/modelmanager.go
  apiserver/facades/client/modelmanager/services.go
  apiserver/facades/controller/migrationtarget/servicefactory_mock_test.go
  domain/servicefactory/model.go
  domain/servicefactory/testing/service.go
  internal/migration/servicefactory_mock_test.go
  internal/servicefactory/interface.go
  internal/worker/servicefactory/servicefactory_mock_test.go
Labels: 4.0

#17318 Use new bespoke structs for fetching secrets to drain info
  api/common/secretsdrain/client.go
  api/common/secretsdrain/client_test.go
  apiserver/common/secrets/drain.go
  apiserver/common/secrets/drain_test.go
  apiserver/common/secrets/mocks/commonsecrets_mock.go
  apiserver/common/secrets/service.go
  apiserver/facades/schema.json
  core/secrets/secret.go
  domain/secret/service/service.go
  domain/secret/service/service_test.go
  domain/secret/service/state_mock_test.go
  domain/secret/state/state.go
  domain/secret/state/state_test.go
  domain/secret/state/types.go
  domain/secretbackend/service/service.go
  domain/secretbackend/service/service_test.go
  internal/worker/secretsdrainworker/worker.go
  internal/worker/secretsdrainworker/worker_test.go
  rpc/params/secrets.go
Labels: 4.0

#17296 Model config client facades
  agent/agentbootstrap/bootstrap.go
  apiserver/facades/client/modelconfig/backend.go
  apiserver/facades/client/modelconfig/mocks/service_mock.go
  apiserver/facades/client/modelconfig/modelconfig.go
  apiserver/facades/client/modelconfig/modelconfig_test.go
  apiserver/facades/client/modelconfig/package_test.go
  apiserver/facades/client/modelconfig/register.go
  apiserver/facades/client/modelconfig/service.go
  apiserver/facades/schema.json
  domain/model/state/state.go
  domain/model/state/state_test.go
  domain/modelconfig/bootstrap/bootstrap.go
  domain/modelconfig/bootstrap/bootstrap_test.go
  domain/modelconfig/service/service.go
  domain/modelconfig/service/service_test.go
  domain/modelconfig/service/testing/state.go
  domain/modelconfig/state/state.go
  domain/modelconfig/state/state_test.go
  domain/modelconfig/validators/validators.go
  domain/modelconfig/validators/validators_test.go
  domain/servicefactory/testing/suite.go
  juju/testing/apiserver.go
  state/modelconfig.go
  state/modelconfig_test.go
Labels: do not merge, 4.0

#17326 3.6 into main
  internal/provider/vsphere/environ_broker.go
  internal/provider/vsphere/environ_broker_test.go
  internal/provider/vsphere/internal/vsphereclient/createvm.go
  internal/provider/vsphere/internal/vsphereclient/createvm_test.go
  internal/provider/vsphere/vm_template.go
  internal/provider/vsphere/vm_template_test.go
Labels: 4.0

#17325 Implement core/watcher.Normalise that reduces any watcher to a NotifyWatcher
  apiserver/common/modelwatcher.go
  core/watcher/normalise.go
  core/watcher/normalise_test.go
Labels: 4.0

#17313 Remove unused region field in gce provider Connection
  provider/gce/google/conn.go
  provider/gce/google/testing_test.go
Labels: 3.4

#17322 Move sshclient facades to use model config service.
  apiserver/facades/client/sshclient/authorizer_mock_test.go
  apiserver/facades/client/sshclient/facade.go
  apiserver/facades/client/sshclient/facade_test.go
  apiserver/facades/client/sshclient/leadership_mock_test.go
  apiserver/facades/client/sshclient/package_test.go
  apiserver/facades/client/sshclient/register.go
  apiserver/facades/client/sshclient/service.go
  apiserver/facades/client/sshclient/service_mock_test.go
  apiserver/facades/client/sshclient/shim.go
  apiserver/facades/client/sshclient/state_mock_test.go
Labels: 4.0

#17331 Replace BootstrapSeries with BootstrapBase
  caas/kubernetes/provider/k8s.go
  caas/kubernetes/provider/k8s_test.go
  environs/bootstrap.go
  environs/bootstrap/bootstrap.go
  environs/bootstrap/bootstrap_test.go
  provider/azure/environ_test.go
  provider/common/bootstrap.go
  provider/common/bootstrap_test.go
  provider/gce/environ_test.go
  provider/lxd/environ_test.go
  provider/oci/environ_integration_test.go
  provider/vsphere/environ_test.go
  testing/environ.go
Labels: 3.6

#17323 Use model access
  agent/agentbootstrap/bootstrap.go
  apiserver/facades/client/modelmanager/mocks/service_mock.go
  apiserver/facades/client/modelmanager/modelmanager.go
  apiserver/facades/client/modelmanager/modelmanager_test.go
  apiserver/facades/client/modelmanager/services.go
  domain/access/state/permission_test.go
  domain/cloud/state/state_test.go
  domain/model/bootstrap/bootstrap.go
  domain/model/bootstrap/bootstrap_test.go
  domain/model/modelmigration/import.go
  domain/model/modelmigration/import_test.go
  domain/model/modelmigration/migrations_mock_test.go
  domain/model/service/service.go
  domain/model/service/service_test.go
  domain/model/service/state_test.go
  domain/model/state/state.go
  domain/model/state/state_test.go
  domain/model/state/testing/model.go
  domain/model/types.go
  domain/model/types_test.go
  domain/modelconfig/bootstrap/bootstrap_test.go
  domain/secretbackend/state/state_test.go
  domain/servicefactory/testing/suite.go
Labels: 4.0

#17337 Secret drain api uses bespoke watcher, not modelconfig
  apiserver/common/secrets/drain.go
  apiserver/common/secrets/drain_test.go
  apiserver/common/secrets/mocks/commonsecrets_mock.go
  apiserver/common/secrets/mocks/statewatcher.go
  apiserver/common/secrets/package_test.go
  apiserver/common/secrets/service.go
  apiserver/common/secrets/state.go
  apiserver/common/secrets/watcher.go
  apiserver/common/secrets/watcher_test.go
  apiserver/facades/agent/secretsdrain/register.go
  apiserver/facades/controller/usersecretsdrain/register.go
  domain/secret/service/service.go
  domain/secret/service/watcher.go
Labels: 4.0

#17317 Moves firewaller facades (incl. common) and crossmodelrelation facades to model config service.
  apiserver/common/firewall/egressaddresswatcher.go
  apiserver/common/firewall/egressaddresswatcher_test.go
  apiserver/common/firewall/firewall.go
  apiserver/common/firewall/firewall_test.go
  apiserver/common/firewall/package_test.go
  apiserver/common/firewall/service_mock_test.go
  apiserver/common/firewall/state.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations_test.go
  apiserver/facades/controller/crossmodelrelations/package_test.go
  apiserver/facades/controller/crossmodelrelations/register.go
  apiserver/facades/controller/crossmodelrelations/service.go
  apiserver/facades/controller/crossmodelrelations/service_mock_test.go
  apiserver/facades/controller/firewaller/firewaller.go
  apiserver/facades/controller/firewaller/firewaller_base_test.go
  apiserver/facades/controller/firewaller/firewaller_test.go
  apiserver/facades/controller/firewaller/firewaller_unit_test.go
  apiserver/facades/controller/firewaller/modelfirewallruleswatcher.go
  apiserver/facades/controller/firewaller/modelfirewallruleswatcher_test.go
  apiserver/facades/controller/firewaller/package_mock_test.go
  apiserver/facades/controller/firewaller/package_test.go
  apiserver/facades/controller/firewaller/register.go
  apiserver/facades/controller/firewaller/service_mock_test.go
Labels: 4.0

#17264 Secret consumed changes watcher
  domain/schema/model.go
  domain/schema/schema_test.go
  domain/schema/secret.go
  domain/secret/service/consume.go
  domain/secret/service/service.go
  domain/secret/service/service_test.go
  domain/secret/service/state_mock_test.go
  domain/secret/service/watcher.go
  domain/secret/state/state.go
  domain/secret/state/state_test.go
  domain/secret/state/types.go
  domain/secret/watcher_test.go
  internal/worker/uniter/remotestate/watcher.go
  tests/suites/secrets_iaas/cmr.sh
Labels: 4.0

#17341 Ensure we clear multiwatcher payload on send
  core/watcher/eventsource/multiwatcher.go
  core/watcher/eventsource/mutliwatcher_test.go
  core/watcher/watchertest/strings.go
Labels: 4.0

#17324 Add default-space config validation for model config update
  domain/modelconfig/service/service.go
  domain/modelconfig/service/testing/state.go
  domain/modelconfig/state/state.go
  domain/modelconfig/state/state_test.go
  domain/modelconfig/validators/validators.go
  domain/modelconfig/validators/validators_test.go
Labels: 4.0

#17329 Replace credential models and owner access
  apiserver/facades/client/cloud/backend.go
  apiserver/facades/client/cloud/cloud.go
  apiserver/facades/client/cloud/cloud_test.go
  apiserver/facades/client/cloud/mocks/cloud_mock.go
  apiserver/facades/client/cloud/package_test.go
  apiserver/facades/client/cloud/register.go
  cloud/clouds.go
  domain/access/service/permission.go
  domain/access/service/permission_test.go
  domain/access/service/service.go
  domain/access/service/state_mock_test.go
  domain/access/state/permission.go
  domain/access/state/permission_test.go
  domain/access/types.go
  domain/model/state/testing/model.go
  state/credentialmodels_test.go
  state/modelcredential.go
Labels: 4.0

#17335 Move agent/logger facade to model config service.
  apiserver/facades/agent/logger/export_test.go
  apiserver/facades/agent/logger/logger.go
  apiserver/facades/agent/logger/logger_integration_test.go
  apiserver/facades/agent/logger/logger_test.go
  apiserver/facades/agent/logger/package_test.go
  apiserver/facades/agent/logger/register.go
  apiserver/facades/agent/logger/service.go
  apiserver/facades/agent/logger/service_mock_test.go
Labels: 4.0

#17344 Pruner workers
  cmd/jujud-controller/agent/machine.go
  cmd/jujud-controller/agent/machine/manifolds.go
  cmd/jujud-controller/agent/model/manifolds.go
  cmd/jujud-controller/agent/model/manifolds_test.go
  internal/worker/actionpruner/worker_test.go
  internal/worker/modelworkermanager/manifold.go
  internal/worker/modelworkermanager/manifold_test.go
  internal/worker/modelworkermanager/modelworkermanager.go
  internal/worker/modelworkermanager/modelworkermanager_test.go
  internal/worker/pruner/config.go
  internal/worker/pruner/manifold.go
  internal/worker/pruner/manifold_test.go
  internal/worker/pruner/mocks/mocks_facade.go
  internal/worker/pruner/package_test.go
  internal/worker/pruner/worker.go
  internal/worker/pruner/worker_test.go
  internal/worker/statushistorypruner/worker.go
  internal/worker/statushistorypruner/worker_test.go
Labels: 4.0

#17343 Service factory at model worker level
  cmd/jujud-controller/agent/machine.go
  cmd/jujud-controller/agent/machine/manifolds.go
  cmd/jujud-controller/agent/model/manifolds.go
  cmd/jujud-controller/agent/model/manifolds_test.go
  internal/worker/modelworkermanager/manifold.go
  internal/worker/modelworkermanager/manifold_test.go
  internal/worker/modelworkermanager/modelworkermanager.go
  internal/worker/modelworkermanager/modelworkermanager_test.go
Labels: 4.0

#17352 Remove last controller config watcher
  apiserver/facades/controller/caasapplicationprovisioner/mock_test.go
  apiserver/facades/controller/caasapplicationprovisioner/provisioner.go
  apiserver/facades/controller/caasapplicationprovisioner/provisioner_test.go
  apiserver/facades/controller/caasapplicationprovisioner/state.go
  internal/worker/peergrouper/mock_test.go
  state/settings.go
  state/watcher.go
Labels: 4.0

#17355 Fix logical race in tests
  internal/worker/upgradesteps/controllerworker_test.go
Labels: 4.0

#17206 Remove JUJU_TARGET_SERIES envvar from hook context
  internal/worker/uniter/runner/context/context.go
  internal/worker/uniter/runner/context/env_test.go
  internal/worker/uniter/runner/context/export_test.go
Labels: 4.0

#17353 Fix controllercharm prometheus test failure on gating tests
  tests/suites/controllercharm/prometheus.sh
Labels: 3.3

#17351 Make simple worker context compatible
  cmd/jujud-controller/agent/machine_test.go
  cmd/jujud-controller/agent/util_test.go
  cmd/jujud/agent/agent_test.go
  cmd/jujud/agent/machine_test.go
  cmd/jujud/agent/util_test.go
  internal/worker/caasenvironupgrader/worker.go
  internal/worker/environupgrader/worker.go
  internal/worker/identityfilewriter/manifold.go
  internal/worker/logsender/worker.go
  internal/worker/noopworker.go
  internal/worker/periodicworker_test.go
  internal/worker/simpleworker.go
  internal/worker/simpleworker_test.go
  internal/worker/undertaker/undertaker.go
Labels: 4.0

#17342 Improve changestream pruner log output
  internal/worker/changestreampruner/package_test.go
  internal/worker/changestreampruner/worker.go
  internal/worker/changestreampruner/worker_test.go
Labels: 4.0

#17362 Fix secret ci
  apiserver/facades/controller/crossmodelsecrets/crossmodelsecrets.go
  domain/secret/service/service.go
  tests/suites/secrets_iaas/cmr.sh
Labels: bug, 4.0

#17363 Store controller UUID for controller config in another table
  domain/controllerconfig/bootstrap/bootstrap.go
  domain/controllerconfig/bootstrap/bootstrap_test.go
  domain/controllerconfig/service/service.go
  domain/controllerconfig/state/state.go
  domain/controllerconfig/state/state_test.go
  domain/controllerconfig/state/types.go
  domain/schema/controller.go
  domain/schema/schema_test.go
  domain/schema/secret.go
  domain/secretbackend/state/state_test.go
  domain/secretbackend/state/types.go
Labels: 4.0

#17309 Fix `SimpleConnector` to set `UserTag` when no client credentials provided
  api/connector/package_test.go
  api/connector/simpleconnector.go
  api/connector/simpleconnector_test.go
Labels: 3.5

#17339 Removes client facade off of calls to mongo.
  apiserver/facades/client/client/backend.go
  apiserver/facades/client/client/client.go
  apiserver/facades/client/client/client_test.go
  apiserver/facades/client/client/package_mock_test.go
  apiserver/facades/client/client/package_test.go
  apiserver/facades/client/client/service.go
  apiserver/facades/client/client/service_mock_test.go
  apiserver/facades/client/client/statushistory_test.go
  apiserver/facades/client/modelmanager/modelmanager.go
  apiserver/facades/client/modelmanager/services.go
  core/model/readonlymodel.go
  domain/model/modelmigration/import.go
  domain/model/modelmigration/import_test.go
  domain/model/modelmigration/migrations_mock_test.go
  domain/model/service/modelservice.go
  domain/model/service/modelservice_test.go
  domain/model/state/modelstate.go
  domain/model/state/modelstate_test.go
  domain/servicefactory/model.go
Labels: has merge conflicts, 4.0

#17367 Disable auto prune and drain tests for now because they are not imple…
  tests/suites/secrets_iaas/juju.sh
  tests/suites/secrets_iaas/vault.sh
  tests/suites/secrets_k8s/k8s.sh
Labels: 4.0

#17354 Implement SecretRotated service call
  domain/schema/secret.go
  domain/secret/service/service.go
  domain/secret/service/service_test.go
  domain/secret/service/state_mock_test.go
  domain/secret/service/watcher.go
  domain/secret/state/state.go
  domain/secret/state/state_test.go
  domain/secret/state/types.go
  domain/secret/types.go
Labels: 4.0

#17255 Domain errors
  apiserver/common/charms.go
  apiserver/facades/agent/provisioner/provisioninginfo.go
  domain/errors.go
  domain/errors_test.go
  domain/network/errors/errors.go
  domain/network/state/space.go
  domain/network/state/space_test.go
  domain/objectstore/errors/errors.go
  domain/objectstore/state/state.go
  domain/objectstore/state/state_test.go
  domain/objectstore/watcher_test.go
  domain/secretbackend/service/service.go
  domain/secretbackend/state/state.go
  internal/database/errors.go
Labels: 4.0

#17374 Add OTEL trace id to goroutine labels
  api/base/caller.go
  core/trace/context.go
  core/trace/tracer.go
  internal/charmhub/download.go
  internal/charmhub/find.go
  internal/charmhub/info.go
  internal/worker/lease/manager.go
  internal/worker/uniter/operation/executor.go
  rpc/server.go
Labels: 4.0

#17386 Assert change stream becomes idle
  domain/controllerconfig/watcher_test.go
  internal/changestream/stream/stream.go
  internal/changestream/testing/changestream.go
  internal/changestream/testing/controllersuite.go
  internal/changestream/testing/modelsuite.go
Labels: 4.0

#17360 Logtailer test fix
  internal/logtailer/tailer_test.go
Labels: 4.0

#17350 Drop support for series in bundles
  cmd/juju/application/bundle/bundle.go
  cmd/juju/application/bundle/bundle_test.go
  cmd/juju/application/bundle/interface.go
  cmd/juju/application/bundle/mocks/bundledatasource_mock.go
  cmd/juju/application/bundle_test.go
  cmd/juju/application/deployer/bundle.go
  cmd/juju/application/deployer/bundle_test.go
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/bundlehandler_test.go
  cmd/juju/application/deployer/deployer_test.go
  cmd/juju/application/deployer/interface.go
  cmd/juju/application/deployer/mocks/charm_mock.go
  cmd/juju/application/deployer/mocks/resolver_mock.go
  cmd/juju/application/deployer/package_test.go
  cmd/juju/application/diffbundle_test.go
  cmd/juju/application/store/mocks/charm_mock.go
  cmd/juju/application/store/resolve.go
  go.mod
  go.sum
  internal/bundle/changes/changes_test.go
  internal/bundle/changes/handlers.go
  tests/suites/deploy/bundles/basic-openstack.yaml
  tests/suites/deploy/bundles/bundle-with-overlays/easyrsa-etcd.yaml
  tests/suites/deploy/bundles/bundle-with-overlays/easyrsa.yaml
  tests/suites/deploy/bundles/cmr_bundles_test_deploy.yaml
  tests/suites/deploy/bundles/lxd-profile-bundle.yaml
  tests/suites/firewall/bundles/invalid.yaml
Labels: 4.0

#17393 Intern juju/http package
  api/apiclient.go
  api/package_test.go
  apiserver/facades/controller/charmdownloader/charmdownloader.go
  apiserver/pubsub_test.go
  apiserver/registration_test.go
  apiserver/server_test.go
  apiserver/testing/fakeapi.go
  apiserver/testing/http.go
  apiserver/tools.go
  apiserver/tools_integration_test.go
  cmd/containeragent/initialize/package_test.go
  cmd/juju/cloud/updatepublicclouds.go
  cmd/juju/controller/register.go
  environs/simplestreams/datasource.go
  environs/simplestreams/export_test.go
  environs/simplestreams/testing/testing.go
  environs/sync/sync.go
  environs/sync/sync_test.go
  environs/testing/tools.go
  go.mod
  go.sum
  internal/charmhub/http.go
  internal/charmhub/http_test.go
  internal/downloader/utils.go
  internal/http/client.go
  internal/http/client_mock_test.go
  internal/http/client_test.go
  internal/http/clock_mock_test.go
  internal/http/http.go
  internal/http/http_mock_test.go
  internal/http/http_test.go
  internal/http/middleware.go
  internal/http/middleware_test.go
  internal/http/package_test.go
  internal/http/tls.go
  internal/http/tls_test.go
  internal/mongo/open.go
  internal/provider/ec2/environ.go
  internal/provider/gce/environ.go
  internal/provider/gce/google/auth.go
  internal/provider/gce/google/auth_test.go
  internal/provider/gce/google/config.go
  internal/provider/gce/google/config_connection_test.go
  internal/provider/gce/google/conn.go
  internal/provider/gce/google/conn_test.go
  internal/provider/gce/google/testing_test.go
  internal/provider/lxd/provider.go
  internal/provider/openstack/client.go
  internal/provider/openstack/provider.go
  internal/s3client/http.go
  internal/upgrades/upgradevalidation/validation.go
  internal/worker/httpserver/tls.go
  internal/worker/upgrader/upgrader.go
Labels: 4.0

#17396 Regenerate mocks
  apiserver/common/charms/mocks/mocks.go
  apiserver/facades/agent/provisioner/mocks/package_mock.go
  apiserver/facades/client/charms/mocks/repository.go
  apiserver/facades/client/charms/mocks/state_mock.go
  apiserver/facades/client/client/package_mock_test.go
  apiserver/facades/client/controller/mocks/state_mock.go
  apiserver/facades/client/machinemanager/package_mock_test.go
  apiserver/facades/client/modelgeneration/mocks/package_mock.go
  apiserver/facades/client/resources/mocks/backend.go
  apiserver/facades/controller/charmdownloader/mocks/mocks.go
  apiserver/facades/controller/charmrevisionupdater/mocks/mocks.go
  apiserver/mocks/resources_mock.go
  cmd/juju/application/utils/mocks/charmresource_mock.go
  cmd/juju/ssh/mocks/package_mock.go
  domain/application/service/package_mock_test.go
  internal/bootstrap/bootstrap_mock_test.go
  internal/bootstrap/charm_mock_test.go
  internal/bootstrap/downloader_mock_test.go
  internal/charm/downloader/mocks/charm_archive_mocks.go
  internal/resource/mocks/cache_mock.go
  internal/worker/bootstrap/bootstrap_mock_test.go
  internal/worker/uniter/api/domain_mocks.go
  internal/worker/uniter/runner/jujuc/mocks/context_mock.go
  internal/worker/uniter/runner/mocks/context_mock.go
  state/mocks/resources_mock.go
Labels: 4.0

#17208 Delete model
  apiserver/apiserver.go
  apiserver/facades/client/modelmanager/mocks/service_mock.go
  apiserver/facades/client/modelmanager/modelmanager.go
  apiserver/facades/client/modelmanager/services.go
  apiserver/facades/controller/migrationtarget/migrationtarget_test.go
  apiserver/package_test.go
  apiserver/root.go
  apiserver/shared.go
  apiserver/shared_test.go
  cmd/jujud-controller/agent/machine/manifolds.go
  core/context/package_test.go
  core/context/sourceable.go
  core/context/sourceable_test.go
  core/database/dbmanager.go
  core/modelmigration/coordinator.go
  core/modelmigration/coordinator_test.go
  domain/lease/modelmigration/import_test.go
  domain/model/modelmigration/import.go
  domain/model/modelmigration/import_test.go
  domain/model/modelmigration/migrations_mock_test.go
  domain/model/service/service.go
  domain/model/service/service_test.go
  domain/model/service/state_test.go
  domain/model/types.go
  domain/schema/testing/controllermodelsuite.go
  domain/servicefactory/controller.go
  internal/changestream/stream/stream.go
  internal/database/testing/dqlitesuite.go
  internal/migration/migration_test.go
  internal/worker/apiserver/manifold.go
  internal/worker/apiserver/manifold_test.go
  internal/worker/apiserver/worker.go
  internal/worker/apiserver/worker_state_test.go
  internal/worker/apiserver/worker_test.go
  internal/worker/changestream/worker.go
  internal/worker/changestreampruner/worker.go
  internal/worker/dbaccessor/deletedb.go
  internal/worker/dbaccessor/deletedb_test.go
  internal/worker/dbaccessor/tracker.go
  internal/worker/dbaccessor/tracker_test.go
  internal/worker/dbaccessor/worker.go
  internal/worker/dbaccessor/worker_integration_test.go
  internal/worker/dbaccessor/worker_namespace_test.go
  internal/worker/modelworkermanager/modelworkermanager.go
  internal/worker/objectstore/worker.go
  internal/worker/providertracker/providerworker.go
  juju/testing/apiserver.go
  tests/suites/smoke/deploy.sh
Labels: 4.0

#17348 Deprecate series in bundles
  cmd/juju/application/bundle/bundle.go
  cmd/juju/application/bundle/bundle_test.go
  cmd/juju/application/deployer/bundle.go
  cmd/juju/application/diffbundle.go
Labels: 3.1

#17406 Remove SuperSubnets from environs networking
  domain/network/service/package_mock_test.go
  environs/mocks/package_mock.go
  environs/networking.go
  environs/testing/package_mock.go
  internal/provider/azure/environ_network.go
  internal/provider/dummy/environs.go
  internal/provider/ec2/environ.go
  internal/provider/ec2/environ_vpc.go
  internal/provider/equinix/environ_network.go
  internal/provider/gce/environ_network.go
  internal/provider/gce/environ_network_test.go
  internal/provider/lxd/environ_network.go
  internal/provider/maas/environ.go
  internal/provider/manual/environ_network.go
  internal/provider/oci/networking.go
  internal/provider/openstack/local_test.go
  internal/provider/openstack/provider.go
  state/containernetworking.go
  state/containernetworking_test.go
Labels: 4.0

#17327 Match by MAC in Netplan for LXD VMs
  cloudconfig/cloudinit/cloudinit.go
  cloudconfig/cloudinit/interface.go
  cloudconfig/cloudinit/interface_test.go
  cloudconfig/cloudinit/network_ubuntu.go
  cloudconfig/cloudinit/network_ubuntu_test.go
  container/kvm/kvm.go
  container/lxd/manager.go
Labels: 3.4

#17409 Add Dqlite unit state DDL
  domain/schema/model.go
  domain/schema/schema_test.go
  internal/worker/firewaller/firewaller_test.go
Labels: 4.0

#17420 Remove the expired cert
  cmd/juju/commands/main.go
  cmd/juju/model/data.go
Labels: 4.0

#17412 Remove the fanconfigurer worker
  api/agent/fanconfigurer/facade.go
  apiserver/facades/agent/fanconfigurer/register.go
  cmd/jujud-controller/agent/engine_test.go
  cmd/jujud-controller/agent/machine/manifolds.go
  cmd/jujud-controller/agent/machine/manifolds_test.go
  cmd/jujud/agent/engine_test.go
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/agent/machine/manifolds_test.go
  internal/worker/fanconfigurer/fanconfigurer.go
  internal/worker/fanconfigurer/manifold.go
  internal/worker/fanconfigurer/package_test.go
  internal/worker/machiner/manifold.go
Labels: 4.0

#17401 Secret rotation watcher
  core/watcher/secrets.go
  core/watcher/watchertest/secrets.go
  domain/secret/service/service.go
  domain/secret/service/service_test.go
  domain/secret/service/state_mock_test.go
  domain/secret/service/watcher.go
  domain/secret/state/state.go
  domain/secret/state/state_test.go
  domain/secret/state/types.go
  domain/secret/types.go
  domain/secret/watcher_test.go
Labels: 4.0

#17436 Merge 3.3 to 3.4
  cmd/juju/application/bundle/bundle.go
  cmd/juju/application/bundle/bundle_test.go
  cmd/juju/application/deployer/bundle.go
  cmd/juju/application/diffbundle.go
Labels: 3.4

#17399 Intern featureflag package
  api/package_test.go
  api/userpass_login_provider.go
  apiserver/embeddedcli.go
  apiserver/facades/agent/uniter/package_test.go
  apiserver/facades/agent/uniter/uniter_network_test.go
  apiserver/facades/client/client/client.go
  apiserver/facades/client/client/status_test.go
  apiserver/facades/client/modelconfig/modelconfig_test.go
  apiserver/facades/client/modelupgrader/findagents.go
  apiserver/logsink/logsink.go
  apiserver/pubsub.go
  caas/kubernetes/provider/application/application.go
  caas/kubernetes/provider/bootstrap.go
  caas/kubernetes/provider/bootstrap_test.go
  cmd/containeragent/initialize/package_test.go
  cmd/containeragent/main_nix.go
  cmd/containeragent/unit/agent.go
  cmd/internal/agent/agentconf/agentconf.go
  cmd/juju/application/config.go
  cmd/juju/application/config_test.go
  cmd/juju/commands/bootstrap.go
  cmd/juju/commands/main.go
  cmd/juju/commands/main_test.go
  cmd/juju/controller/addmodel.go
  cmd/juju/controller/addmodel_test.go
  cmd/juju/model/package_test.go
  cmd/jujuc/main.go
  cmd/jujud-controller/main.go
  cmd/jujud/main.go
  cmd/plugins/juju-metadata/metadata.go
  core/assumes/featureset.go
  core/network/portrange.go
  environs/bootstrap/prepare.go
  environs/config/config.go
  environs/config/config_test.go
  go.mod
  go.sum
  internal/charm/assumes/expression.go
  internal/cloudconfig/instancecfg/instancecfg.go
  internal/cloudconfig/userdatacfg_unix.go
  internal/featureflag/consts.go
  internal/featureflag/doc.go
  internal/featureflag/flags.go
  internal/featureflag/flags_test.go
  internal/featureflag/package_test.go
  internal/provider/manual/environ.go
  internal/worker/provisioner/logging.go
  internal/worker/provisioner/logging_test.go
  juju/osenv/package_test.go
  juju/osenv/vars.go
  jujuclient/models.go
  jujuclient/modelsfile_test.go
  state/database.go
  state/migration_export.go
  state/migration_export_test.go
  state/payloads_test.go
  state/pool.go
  state/watcher/hubwatcher.go
  state/watcher/hubwatcher_test.go
  testing/base.go
Labels: 4.0

#17422 External controller log message
  worker/externalcontrollerupdater/externalcontrollerupdater.go
Labels: 3.4

#17429 Remove support for fan subnets on the network domain
  domain/network/service/interface.go
  domain/network/service/package_mock_test.go
  domain/network/service/watcher.go
  domain/network/state/space.go
  domain/network/state/space_test.go
  domain/network/state/subnet.go
  domain/network/state/subnet_test.go
  domain/network/state/types.go
  domain/network/watcher_test.go
  domain/schema/model.go
  domain/schema/schema_test.go
Labels: 4.0

#17381 Fix bad domain naming for model
  domain/model/bootstrap/bootstrap.go
  domain/model/service/modelservice.go
  domain/model/service/modelservice_test.go
  domain/model/service/service.go
  domain/model/service/state_test.go
  domain/model/state/state.go
  domain/model/state/state_test.go
  domain/modelconfig/bootstrap/bootstrap.go
Labels: 4.0

#17156 Generate triggers
  Makefile
  core/watcher/eventsource/namespace.go
  domain/blockdevice/state/state.go
  domain/blockdevice/state/types.go
  domain/cloud/state/state_test.go
  domain/modelconfig/bootstrap/bootstrap.go
  domain/modelconfig/modelconfig_test.go
  domain/modelconfig/package_test.go
  domain/modelconfig/service/providerservice.go
  domain/modelconfig/service/service.go
  domain/modelconfig/service/service_test.go
  domain/modelconfig/state/state.go
  domain/modelconfig/state/types.go
  domain/schema/changelog.go
  domain/schema/controller.go
  domain/schema/controller/cloud-triggers.gen.go
  domain/schema/controller/controller-triggers.gen.go
  domain/schema/controller/migration-triggers.gen.go
  domain/schema/controller/model-triggers.gen.go
  domain/schema/controller/objectstore-triggers.gen.go
  domain/schema/controller/secret-triggers.gen.go
  domain/schema/controller/upgrade-triggers.gen.go
  domain/schema/model.go
  domain/schema/model/model-triggers.gen.go
  domain/schema/model/network-triggers.gen.go
  domain/schema/model/objectstore-triggers.gen.go
  domain/schema/model/secret-triggers.gen.go
  domain/schema/model/storage-triggers.gen.go
  domain/schema/schema_test.go
  domain/schema/testing/controllersuite.go
  domain/schema/testing/modelsuite.go
  domain/schema/testing/schema.go
  domain/secret/watcher_test.go
  generate/triggergen/main.go
  internal/changestream/stream/stream.go
  internal/changestream/testing/changestream.go
  internal/changestream/testing/controllersuite.go
  internal/changestream/testing/modelsuite.go
  scripts/dqlite/cmd/main.go
Labels: 4.0

#17426 Add instance data sql schema
  domain/schema/model.go
  domain/schema/schema_test.go
Labels: 4.0

#17439 Remove the fan info field from subnet structs
  api/controller/firewaller/firewaller_test.go
  apiserver/common/networkingcommon/networkconfigapi.go
  apiserver/common/networkingcommon/networkconfigapi_test.go
  apiserver/facades/client/spaces/integrity.go
  apiserver/facades/client/spaces/move.go
  apiserver/facades/client/spaces/move_test.go
  apiserver/facades/controller/firewaller/firewaller_unit_test.go
  apiserver/facades/schema.json
  cmd/juju/space/space.go
  core/network/space.go
  core/network/space_test.go
  core/network/subnet.go
  core/network/subnet_test.go
  domain/network/modelmigration/export.go
  domain/network/modelmigration/export_test.go
  domain/network/modelmigration/import.go
  domain/network/modelmigration/import_test.go
  domain/network/service/interface.go
  domain/network/service/package_mock_test.go
  domain/network/service/space.go
  domain/network/service/space_test.go
  domain/network/state/space.go
  domain/network/state/space_test.go
  rpc/params/network.go
Labels: 4.0

#17428 DDL SQL files
  domain/schema/controller.go
  domain/schema/controller/sql/0000-namespace.sql
  domain/schema/controller/sql/0001-life.sql
  domain/schema/controller/sql/0002-lease.sql
  domain/schema/controller/sql/0003-changelog.sql
  domain/schema/controller/sql/0004-changelog-namespaces.sql
  domain/schema/controller/sql/0005-cloud.sql
  domain/schema/controller/sql/0006-external-controller.sql
  domain/schema/controller/sql/0007-model.sql
  domain/schema/controller/sql/0008-model-agent.sql
  domain/schema/controller/sql/0009-controller-config.sql
  domain/schema/controller/sql/0010-controller-node.sql
  domain/schema/controller/sql/0011-model-migration.sql
  domain/schema/controller/sql/0012-uprade-info.sql
  domain/schema/controller/sql/0013-autocert-cache.sql
  domain/schema/controller/sql/0014-objectstore-metadata.sql
  domain/schema/controller/sql/0015-user.sql
  domain/schema/controller/sql/0016-flag.sql
  domain/schema/controller/sql/0017-user-permission.sql
  domain/schema/controller/sql/0018-secret-backend.sql
  domain/schema/controller/triggers/cloud-triggers.gen.go
  domain/schema/controller/triggers/controller-triggers.gen.go
  domain/schema/controller/triggers/migration-triggers.gen.go
  domain/schema/controller/triggers/model-triggers.gen.go
  domain/schema/controller/triggers/objectstore-triggers.gen.go
  domain/schema/controller/triggers/secret-triggers.gen.go
  domain/schema/controller/triggers/upgrade-triggers.gen.go
  domain/schema/life.go
  domain/schema/model.go
  domain/schema/model/sql/0000-life.sql
  domain/schema/model/sql/0001-changelog.sql
  domain/schema/model/sql/0002-changelog-namespaces.sql
  domain/schema/model/sql/0003-read-only-model.sql
  domain/schema/model/sql/0004-model-config.sql
  domain/schema/model/sql/0005-objectstore-metadata.sql
  domain/schema/model/sql/0006-application.sql
  domain/schema/model/sql/0007-charm.sql
  domain/schema/model/sql/0008-network.sql
  domain/schema/model/sql/0009-unit.sql
  domain/schema/model/sql/0010-space.sql
  domain/schema/model/sql/0011-subnet.sql
  domain/schema/model/sql/0012-blockdevice.sql
  domain/schema/model/sql/0013-storage.sql
  domain/schema/model/sql/0014-secret.sql
  domain/schema/model/sql/0015-annotations.sql
  domain/schema/model/sql/0016-instance-data.sql
  domain/schema/model/triggers/model-triggers.gen.go
  domain/schema/model/triggers/network-triggers.gen.go
  domain/schema/model/triggers/objectstore-triggers.gen.go
  domain/schema/model/triggers/secret-triggers.gen.go
  domain/schema/model/triggers/storage-triggers.gen.go
  domain/schema/triggers.go
Labels: 4.0

#17444 Remove link to discorse post in docs
  cmd/juju/cloud/addcredential.go
  cmd/juju/cloud/addcredential_test.go
  provider/gce/credentials.go
Labels: 3.4

#17411 Move caasapplicationprovisioner facade to use model services
  apiserver/facades/controller/caasapplicationprovisioner/mock_test.go
  apiserver/facades/controller/caasapplicationprovisioner/package_test.go
  apiserver/facades/controller/caasapplicationprovisioner/provisioner.go
  apiserver/facades/controller/caasapplicationprovisioner/provisioner_test.go
  apiserver/facades/controller/caasapplicationprovisioner/service.go
  apiserver/facades/controller/caasapplicationprovisioner/service_mock_test.go
  apiserver/facades/controller/caasapplicationprovisioner/state.go
  tests/suites/smoke_k8s/deploy.sh
Labels: 4.0

#17442 Secret revision expiry watcher
  domain/secret/service/service.go
  domain/secret/service/service_test.go
  domain/secret/service/state_mock_test.go
  domain/secret/service/watcher.go
  domain/secret/state/state.go
  domain/secret/state/state_test.go
  domain/secret/state/types.go
  domain/secret/types.go
  domain/secret/watcher_test.go
Labels: 4.0

#17440 Azure image lookup
  apiserver/facades/client/machinemanager/upgradebase.go
  core/base/base.go
  core/base/base_test.go
  environs/bootstrap/bootstrap.go
  provider/azure/environ.go
  provider/azure/instancetype.go
  provider/azure/internal/imageutils/images.go
  provider/azure/internal/imageutils/images_test.go
  provider/common/bootstrap.go
  provider/dummy/environs.go
  provider/equinix/environ.go
  provider/oci/images.go
  state/charm.go
  upgrades/upgradevalidation/validation.go
  version/series.go
Labels: 3.4
