Repository juju/juju, pull requests merged in 2024-04, with the labels that each got.

#17134 Add a retry to the uniter facade CharmArchiveSha256 method.
  apiserver/facades/agent/uniter/uniter.go
  apiserver/facades/agent/uniter/uniter_test.go
Labels: 4.0

#17124 Include sql in verbose mode for tests
  core/database/schema/query.go
  core/database/schema/query_test.go
  core/database/schema/schema.go
  domain/schema/schema_test.go
  domain/schema/testing/controllermodelsuite.go
  domain/schema/testing/controllersuite.go
  domain/schema/testing/modelsuite.go
  domain/schema/testing/schema.go
  internal/changestream/stream/package_test.go
  internal/database/testing/dqlitesuite.go
  internal/worker/changestreampruner/package_test.go
Labels: 4.0

#17129 Rename space and subnet services into NetworkService
  apiserver/facades/agent/provisioner/provisioner.go
  apiserver/facades/controller/migrationtarget/servicefactory_mock_test.go
  domain/network/service/space.go
  domain/network/service/space_test.go
  domain/network/service/subnet.go
  domain/network/service/subnet_test.go
  domain/servicefactory/model.go
  domain/servicefactory/testing/service.go
  internal/migration/servicefactory_mock_test.go
  internal/network/containerizer/bridgepolicy.go
  internal/network/containerizer/shim.go
  internal/servicefactory/interface.go
  internal/worker/bootstrap/bootstrap_mock_test.go
  internal/worker/bootstrap/manifold.go
  internal/worker/bootstrap/package_test.go
  internal/worker/bootstrap/worker.go
  internal/worker/bootstrap/worker_test.go
  internal/worker/servicefactory/servicefactory_mock_test.go
Labels: 4.0

#17132 Fix subnet retrieval on space when empty subnets
  domain/network/state/space_test.go
  domain/network/state/types.go
Labels: 4.0

#17120 Model life
  core/model/model.go
  core/model/model_test.go
  domain/credential/state/state_test.go
  domain/model/state/state.go
  domain/model/state/state_test.go
  domain/schema/controller.go
  domain/schema/life.go
  domain/schema/model.go
  domain/schema/schema_test.go
Labels: 4.0

#17060 Generalize provider tracker
  cmd/jujud-controller/agent/model/manifolds.go
  cmd/jujud-controller/agent/model/manifolds_test.go
  domain/model/modelmigration/import.go
  internal/worker/bootstrap/worker_test.go
  internal/worker/caasadmission/manifold.go
  internal/worker/caasrbacmapper/manifold.go
  internal/worker/providertracker/caas_mock_test.go
  internal/worker/providertracker/manifold.go
  internal/worker/providertracker/manifold_test.go
  internal/worker/providertracker/package_test.go
  internal/worker/providertracker/worker.go
  internal/worker/providertracker/worker_test.go
Labels: 4.0

#17122 Eventsource multiwatcher
  api/controller/caasmodeloperator/client.go
  apiserver/common/cloudspec/cloudspec.go
  apiserver/common/watch.go
  apiserver/common/watch_test.go
  apiserver/facades/agent/proxyupdater/proxyupdater.go
  apiserver/facades/agent/uniter/storage.go
  apiserver/facades/agent/uniter/storage_test.go
  apiserver/facades/controller/caasapplicationprovisioner/provisioner.go
  apiserver/facades/controller/caasapplicationprovisioner/provisioner_test.go
  apiserver/facades/controller/caasmodeloperator/operator.go
  apiserver/facades/controller/caasmodeloperator/operator_test.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations_test.go
  caas/application.go
  caas/broker.go
  caas/kubernetes/provider/application/application.go
  caas/kubernetes/provider/application/application_test.go
  caas/mocks/application_mock.go
  caas/package_test.go
  core/watcher/eventsource/multiwatcher.go
  core/watcher/eventsource/mutliwatcher_test.go
  core/watcher/multinotify.go
  core/watcher/multinotify_test.go
  core/watcher/watchertest/notify.go
  internal/worker/caasapplicationprovisioner/application.go
  internal/worker/caasapplicationprovisioner/application_test.go
  internal/worker/caasmodeloperator/modeloperator.go
  internal/worker/caasmodeloperator/modeloperator_test.go
Labels: 4.0

#17064 Secretbackend service layer
  apiserver/facades/agent/credentialvalidator/credentialvalidator.go
  apiserver/facades/controller/migrationtarget/servicefactory_mock_test.go
  apiserver/facades/controller/secretbackendmanager/backends.go
  apiserver/facades/controller/secretbackendmanager/backends_test.go
  core/secrets/secretbackend.go
  core/watcher/watchertest/secretbackends.go
  domain/cloud/state/state.go
  domain/credential/errors/errors.go
  domain/credential/state/state.go
  domain/credential/state/state_test.go
  domain/interfaces.go
  domain/secretbackend/errors/errors.go
  domain/secretbackend/params.go
  domain/secretbackend/params_test.go
  domain/secretbackend/service/interface.go
  domain/secretbackend/service/package_test.go
  domain/secretbackend/service/provider_mock_test.go
  domain/secretbackend/service/service.go
  domain/secretbackend/service/service_test.go
  domain/secretbackend/service/state_mock_test.go
  domain/secretbackend/service/types.go
  domain/secretbackend/service/watcher.go
  domain/secretbackend/service/watcher_mock_test.go
  domain/secretbackend/service/watcherfactory_mock_test.go
  domain/secretbackend/state/state.go
  domain/secretbackend/state/state_test.go
  domain/secretbackend/state/types.go
  domain/secretbackend/watcher_test.go
  domain/servicefactory/controller.go
  domain/servicefactory/testing/service.go
  internal/changestream/testing/controllersuite.go
  internal/migration/servicefactory_mock_test.go
  internal/secrets/provider/kubernetes/provider.go
  internal/secrets/provider/provider.go
  internal/secrets/provider/vault/provider.go
  internal/servicefactory/interface.go
  internal/worker/servicefactory/servicefactory_mock_test.go
  internal/worker/upgradedatabase/servicefactory_mock_test.go
Labels: 4.0

#17116 Move business logic from secretmanager facade(s) to the secret service
  apiserver/common/secrets/access.go
  apiserver/common/secrets/access_test.go
  apiserver/common/secrets/drain.go
  apiserver/common/secrets/drain_test.go
  apiserver/common/secrets/mocks/commonsecrets_mock.go
  apiserver/common/secrets/mocks/state_mock.go
  apiserver/common/secrets/package_test.go
  apiserver/common/secrets/secrets.go
  apiserver/common/secrets/secrets_test.go
  apiserver/common/secrets/service.go
  apiserver/common/secrets/state.go
  apiserver/facades/agent/secretsdrain/register.go
  apiserver/facades/agent/secretsdrain/register_test.go
  apiserver/facades/agent/secretsmanager/leadership.go
  apiserver/facades/agent/secretsmanager/mocks/secrets.go
  apiserver/facades/agent/secretsmanager/mocks/secretsconsumer.go
  apiserver/facades/agent/secretsmanager/mocks/secretsriggerwatcher.go
  apiserver/facades/agent/secretsmanager/mocks/secretsstate.go
  apiserver/facades/agent/secretsmanager/mocks/secretswatcher.go
  apiserver/facades/agent/secretsmanager/mocks/secrettriggers.go
  apiserver/facades/agent/secretsmanager/package_test.go
  apiserver/facades/agent/secretsmanager/register.go
  apiserver/facades/agent/secretsmanager/secrets.go
  apiserver/facades/agent/secretsmanager/secrets_test.go
  apiserver/facades/agent/secretsmanager/service.go
  apiserver/facades/agent/secretsmanager/state.go
  apiserver/facades/agent/uniter/uniter.go
  apiserver/facades/agent/uniter/uniter_test.go
  apiserver/facades/client/secrets/register.go
  apiserver/facades/controller/crossmodelsecrets/register.go
  apiserver/facades/controller/usersecretsdrain/register.go
  apiserver/facades/schema.json
  apiserver/watcher.go
  core/permission/access.go
  domain/secret/service/service.go
  domain/secret/service/service_test.go
  internal/worker/uniter/remotestate/watcher.go
  state/charm.go
Labels: 4.0

#17142 cancelable API calls
  api/watcher/watcher.go
  api/watcher/watcher_test.go
  internal/rpcreflect/value.go
  rpc/client.go
  rpc/rpc_test.go
  rpc/server.go
Labels: 4.0

#17125 Local DB with schema
  go.mod
  go.sum
  scripts/dqlite/cmd/infer_schema.go
  scripts/dqlite/cmd/main.go
Labels: 4.0

#17141 Support minikube env folder on juju snap
  snap/snapcraft.yaml
Labels: 3.3

#17133 Implement access/state ReadAllAccessForUserAndObjectType and introduce v_permission
  domain/access/service/permission.go
  domain/access/service/permission_test.go
  domain/access/service/service.go
  domain/access/service/state_mock_test.go
  domain/access/state/permission.go
  domain/access/state/permission_test.go
  domain/schema/controller.go
  domain/schema/schema_test.go
Labels: 4.0

#17135 Unblock model migration
  apiserver/facades/agent/upgradesteps/register.go
  apiserver/facades/agent/upgradesteps/upgradesteps.go
  apiserver/facades/agent/upgradesteps/upgradesteps_test.go
  apiserver/facades/schema.json
Labels: 4.0

#17148 Decouple charm upload handlers
  apiserver/apiserver.go
  apiserver/objects.go
  apiserver/objects_test.go
Labels: do not merge

#17104 Drop default lts series
  caas/kubernetes/provider/bootstrap.go
  caas/kubernetes/provider/k8s.go
  caas/kubernetes/provider/k8s_test.go
  environs/bootstrap.go
  environs/bootstrap/bootstrap.go
  environs/bootstrap/bootstrap_test.go
  environs/manual/sshprovisioner/provisioner_test.go
  environs/testing/tools.go
  internal/charmhub/refresh.go
  internal/provider/azure/environ_test.go
  internal/provider/common/bootstrap.go
  internal/provider/common/bootstrap_test.go
  internal/provider/ec2/local_test.go
  internal/provider/gce/environ_test.go
  internal/provider/lxd/environ_test.go
  internal/provider/maas/package_test.go
  internal/provider/oci/environ_integration_test.go
  internal/provider/vsphere/environ_test.go
  testing/base.go
  testing/environ.go
  version/base.go
  version/base_test.go
Labels: 4.0

#17102 Fixes the oauth2 login.
  cmd/modelcmd/base.go
  cmd/modelcmd/base_test.go
  cmd/modelcmd/export_test.go
  juju/api.go
  juju/api_test.go
  juju/export_test.go
Labels: 3.5

#17143 Introduce worker.Runner to provider tracker
  cmd/jujud-controller/agent/engine_test.go
  cmd/jujud-controller/agent/machine.go
  cmd/jujud-controller/agent/machine_legacy_test.go
  cmd/jujud-controller/agent/model/manifolds.go
  cmd/jujud-controller/agent/model/manifolds_test.go
  internal/worker/modelworkermanager/modelworkermanager.go
  internal/worker/objectstore/package_test.go
  internal/worker/objectstore/worker.go
  internal/worker/providertracker/manifold.go
  internal/worker/providertracker/manifold_test.go
  internal/worker/providertracker/package_test.go
  internal/worker/providertracker/providerservice.go
  internal/worker/providertracker/providertracker_mock_test.go
  internal/worker/providertracker/providerworker.go
  internal/worker/providertracker/providerworker_test.go
  internal/worker/providertracker/trackertype.go
  internal/worker/providertracker/trackertype_test.go
  internal/worker/providertracker/trackerworker.go
  internal/worker/providertracker/trackerworker_test.go
Labels: 4.0

#17151 Implement UpsertPermission
  core/permission/access.go
  core/permission/user.go
  domain/access/service/permission.go
  domain/access/service/permission_test.go
  domain/access/service/service.go
  domain/access/service/state_mock_test.go
  domain/access/state/permission.go
  domain/access/state/permission_test.go
  domain/access/types.go
  domain/access/types_test.go
Labels: 4.0

#17147 Remove database critical logging
  internal/database/bootstrap.go
  internal/database/errors.go
  internal/database/errors_test.go
  internal/database/txn/errors.go
Labels: 4.0

#17118 Add support for Pebble change-update notice
  testcharms/charms/pebble-notices/src/charm.py
  testcharms/charms/pebble-notices/tests/unit/test_charm.py
  tests/suites/sidecar/sidecar.sh
  tests/suites/sidecar/task.sh
  worker/uniter/container/workload.go
  worker/uniter/container/workload_test.go
  worker/uniter/hook/hook.go
  worker/uniter/hook/hook_test.go
  worker/uniter/pebblenotices.go
  worker/uniter/pebblenotices_test.go
  worker/uniter/runner/context/contextfactory.go
Labels: 3.5

#17162 Wireup the cross model secret facade to the service service, replacing state calls.
  api/agent/secretsmanager/client.go
  apiserver/common/secrets/access.go
  apiserver/common/secrets/access_test.go
  apiserver/common/secrets/drain_test.go
  apiserver/common/secrets/mocks/commonsecrets_mock.go
  apiserver/common/secrets/secrets.go
  apiserver/common/secrets/secrets_test.go
  apiserver/common/secrets/service.go
  apiserver/errors/errors.go
  apiserver/errors/errors_test.go
  apiserver/facades/agent/secretsmanager/mocks/secrets.go
  apiserver/facades/agent/secretsmanager/secrets.go
  apiserver/facades/agent/secretsmanager/secrets_test.go
  apiserver/facades/agent/secretsmanager/service.go
  apiserver/facades/controller/crossmodelsecrets/crossmodelsecrets.go
  apiserver/facades/controller/crossmodelsecrets/crossmodelsecrets_test.go
  apiserver/facades/controller/crossmodelsecrets/mocks/secretsconsumer.go
  apiserver/facades/controller/crossmodelsecrets/mocks/secretservice.go
  apiserver/facades/controller/crossmodelsecrets/mocks/secretsstate.go
  apiserver/facades/controller/crossmodelsecrets/package_test.go
  apiserver/facades/controller/crossmodelsecrets/register.go
  apiserver/facades/controller/crossmodelsecrets/service.go
  apiserver/facades/controller/crossmodelsecrets/state.go
  domain/secret/errors/errors.go
  domain/secret/service/access.go
  domain/secret/service/consume.go
  domain/secret/service/params.go
  domain/secret/service/service.go
  domain/secret/service/watcher.go
  rpc/params/apierror.go
Labels: 4.0

#17171 Fix an error processing storage on k8s; handle storagepool notfound errors
  apiserver/facades/controller/caasapplicationprovisioner/mock_test.go
  apiserver/facades/controller/caasapplicationprovisioner/provisioner.go
  apiserver/facades/controller/caasapplicationprovisioner/provisioner_test.go
Labels: 4.0

#17166 Remove series charm url reference in legacy handler
  apiserver/charms.go
  apiserver/objects.go
  internal/bootstrap/deployer.go
Labels: 4.0

#17168 3.5 into main
  api/controller/crossmodelrelations/crossmodelrelations.go
  api/controller/crossmodelrelations/crossmodelrelations_test.go
  apiserver/facades/client/application/deployrepository.go
  apiserver/facades/client/application/deployrepository_test.go
  apiserver/facades/client/keymanager/keymanager.go
  apiserver/facades/client/keymanager/keymanager_test.go
  apiserver/facades/client/modelupgrader/upgrader.go
  apiserver/facades/client/modelupgrader/upgrader_test.go
  caas/kubernetes/provider/application/application.go
  caas/kubernetes/provider/application/application_test.go
  cmd/juju/sshkeys/remove_sshkeys.go
  cmd/modelcmd/base.go
  cmd/modelcmd/base_test.go
  cmd/modelcmd/export_test.go
  go.mod
  go.sum
  internal/worker/remoterelations/remoteapplicationworker.go
  internal/worker/remoterelations/remoterelations_test.go
  internal/worker/uniter/actions/resolver.go
  internal/worker/uniter/remotestate/watcher.go
  internal/worker/uniter/resolver.go
  juju/api.go
  juju/api_test.go
  juju/export_test.go
  tests/includes/wait-for.sh
  tests/suites/deploy/bundles/telegraf_bundle.yaml
  tests/suites/deploy/bundles/telegraf_bundle_with_fake_revisions.yaml
  tests/suites/deploy/bundles/telegraf_bundle_without_revisions.yaml
  tests/suites/firewall/expose_app.sh
  tests/suites/refresh/refresh.sh
  tests/suites/refresh/switch.sh
  tests/suites/secrets_k8s/k8s.sh
Labels: 4.0

#17175 3.4 into 3.5
  environs/imagemetadata/simplestreams.go
  juju/testing/instance.go
  provider/ec2/environ.go
  provider/openstack/provider.go
  provider/vsphere/image_metadata.go
  provider/vsphere/vm_template.go
  scripts/dqlite/scripts/dqlite/dqlite-build.sh
  snap/snapcraft.yaml
  tests/includes/wait-for.sh
Labels: 3.5

#17169 Remove series flag from a bunch of CLI commands
  cmd/juju/application/bundle_test.go
  cmd/juju/application/deploy.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/deployer.go
  cmd/juju/application/setapplicationbase.go
  cmd/juju/charmhub/charmhub.go
  cmd/juju/charmhub/data.go
  cmd/juju/charmhub/download.go
  cmd/juju/charmhub/download_test.go
  cmd/juju/charmhub/info.go
  cmd/juju/charmhub/info_test.go
  cmd/juju/commands/bootstrap.go
  cmd/juju/commands/bootstrap_test.go
  cmd/juju/machine/add.go
  cmd/juju/machine/add_test.go
  cmd/juju/machine/upgrademachine.go
  cmd/juju/machine/upgrademachine_test.go
  tests/suites/agents/key_workers_run.sh
  tests/suites/branches/branches.sh
  tests/suites/cmr/offer_consume.sh
  tests/suites/deploy/deploy_charms.sh
  tests/suites/deploy_aks/deploy_aks.sh
  tests/suites/machine/machine.sh
  tests/suites/model/migration.sh
  tests/suites/model/multi.sh
  tests/suites/refresh/refresh.sh
Labels: 4.0

#17174 Drop v5 & 6 of the charm facade
  api/client/charms/client.go
  api/client/charms/client_test.go
  api/facadeversions.go
  rpc/params/params.go
Labels: 4.0

#17165 Expose provider tracker to service factory
  apiserver/facades/controller/migrationtarget/servicefactory_mock_test.go
  cmd/jujud-controller/agent/machine.go
  cmd/jujud-controller/agent/machine/manifolds.go
  cmd/jujud-controller/agent/machine/manifolds_test.go
  cmd/jujud-controller/agent/model/manifolds.go
  core/providertracker/package_test.go
  core/providertracker/provider_mock_test.go
  core/providertracker/providertracker.go
  core/providertracker/providertracker_test.go
  domain/network/service/space.go
  domain/servicefactory/doc.go
  domain/servicefactory/model.go
  domain/servicefactory/service.go
  domain/servicefactory/testing/service.go
  domain/servicefactory/testing/suite.go
  internal/migration/servicefactory_mock_test.go
  internal/servicefactory/interface.go
  internal/worker/providertracker/manifold.go
  internal/worker/providertracker/providerworker.go
  internal/worker/servicefactory/manifold.go
  internal/worker/servicefactory/manifold_test.go
  internal/worker/servicefactory/package_test.go
  internal/worker/servicefactory/providertracker_mock_test.go
  internal/worker/servicefactory/servicefactory_mock_test.go
  internal/worker/servicefactory/worker.go
  internal/worker/servicefactory/worker_test.go
  rpc/client.go
  rpc/rpc_test.go
Labels: 4.0

#17181 Add state and service logic for getting and saving secret consumer info.
  api/agent/secretsmanager/client.go
  apiserver/facades/agent/secretsmanager/mocks/secrets.go
  apiserver/facades/agent/secretsmanager/secrets.go
  apiserver/facades/agent/secretsmanager/secrets_test.go
  apiserver/facades/agent/secretsmanager/service.go
  apiserver/facades/client/secrets/mocks/secretsstate.go
  apiserver/facades/client/secrets/secrets.go
  apiserver/facades/client/secrets/secrets_test.go
  apiserver/facades/client/secrets/service.go
  apiserver/facades/controller/crossmodelsecrets/crossmodelsecrets.go
  apiserver/facades/controller/crossmodelsecrets/crossmodelsecrets_test.go
  apiserver/facades/controller/crossmodelsecrets/mocks/secretservice.go
  apiserver/facades/controller/crossmodelsecrets/service.go
  core/secrets/secret.go
  domain/schema/model.go
  domain/schema/schema_test.go
  domain/schema/secret.go
  domain/secret/service/consume.go
  domain/secret/service/service.go
  domain/secret/service/service_test.go
  domain/secret/service/state_mock_test.go
  domain/secret/state/state.go
  domain/secret/state/state_test.go
  domain/secret/state/types.go
  internal/worker/uniter/remotestate/mock_test.go
  internal/worker/uniter/remotestate/watcher_test.go
  internal/worker/uniter/secrets/resolver.go
  internal/worker/uniter/secrets/resolver_test.go
  internal/worker/uniter/secrets/secrets.go
  internal/worker/uniter/secrets/secrets_test.go
  internal/worker/uniter/util_test.go
Labels: 4.0

#17182 3.5 into main
  environs/imagemetadata/simplestreams.go
  internal/provider/ec2/environ.go
  internal/provider/openstack/provider.go
  internal/provider/vsphere/image_metadata.go
  internal/provider/vsphere/vm_template.go
  internal/worker/uniter/container/workload.go
  internal/worker/uniter/container/workload_test.go
  internal/worker/uniter/hook/hook.go
  internal/worker/uniter/hook/hook_test.go
  internal/worker/uniter/pebblenotices.go
  internal/worker/uniter/pebblenotices_test.go
  internal/worker/uniter/runner/context/contextfactory.go
  juju/testing/instance.go
  scripts/dqlite/scripts/dqlite/dqlite-build.sh
  snap/snapcraft.yaml
  testcharms/charms/pebble-notices/src/charm.py
  testcharms/charms/pebble-notices/tests/unit/test_charm.py
  tests/includes/wait-for.sh
  tests/suites/sidecar/sidecar.sh
  tests/suites/sidecar/task.sh
Labels: 4.0

#17177 [JUJU-4948] Drop HostSeries calls + patches
  cmd/juju/commands/bootstrap_test.go
  cmd/jujud/reboot/rebootshim.go
  environs/bootstrap/bootstrap_test.go
  internal/provider/common/bootstrap_test.go
  internal/provider/ec2/local_test.go
  internal/provider/maas/package_test.go
Labels: 4.0

#17189 Fix aws_ami_creation tests to cleanup snapshots.
  tests/includes/aws_ami_creation.sh
Labels: 3.3

#17185 Implement secret state create charm secret and list secret methods.
  apiserver/facades/client/secrets/mocks/secretsstate.go
  apiserver/facades/client/secrets/secrets.go
  apiserver/facades/client/secrets/secrets_test.go
  apiserver/facades/client/secrets/service.go
  domain/secret/service/service.go
  domain/secret/service/service_test.go
  domain/secret/service/state_mock_test.go
  domain/secret/state/state.go
  domain/secret/state/state_test.go
  domain/secret/state/types.go
  domain/secret/types.go
Labels: 4.0

#17193 Use uuid v7 when adding a space, change method signature
  domain/network/service/space.go
  domain/network/service/space_test.go
  go.mod
  go.sum
Labels: 4.0

#17188 Avoid panics from using a nil pointer
  apiserver/facades/client/application/deployrepository.go
  apiserver/facades/client/application/deployrepository_test.go
Labels: 3.3

#17184 Update AddUserPermission and ReadAllUserAccessForUser.
  domain/access/errors/errors.go
  domain/access/state/permission.go
  domain/access/state/permission_test.go
  domain/access/state/types.go
  domain/access/state/user.go
  domain/access/state/user_test.go
Labels: 4.0

#17196 Merge 3.3 into 3.4
  apiserver/facades/client/application/deployrepository.go
  apiserver/facades/client/application/deployrepository_test.go
  tests/includes/aws_ami_creation.sh
Labels: 3.4

#17183 Remove series flag from juju metadata plugin
  cmd/plugins/juju-metadata/addimage.go
  cmd/plugins/juju-metadata/imagemetadata.go
  cmd/plugins/juju-metadata/listimages.go
  cmd/plugins/juju-metadata/validateimagemetadata.go
Labels: 4.0

#17176 Model config model migration
  core/modelmigration/package_test.go
  domain/model/modelmigration/import.go
  domain/model/modelmigration/import_test.go
  domain/model/modelmigration/migrations_mock_test.go
  domain/model/service/modelservice.go
  domain/model/service/modelservice_test.go
  domain/model/state/modelstate.go
  domain/model/state/modelstate_test.go
  domain/modelconfig/modelmigration/export.go
  domain/modelconfig/modelmigration/export_test.go
  domain/modelconfig/modelmigration/import.go
  domain/modelconfig/modelmigration/import_test.go
  domain/modelconfig/modelmigration/migrations_mock_test.go
  domain/modelconfig/modelmigration/package_test.go
  domain/modelconfig/modelmigration/service_mock_test.go
  domain/modelmigration/export.go
  domain/modelmigration/import.go
  internal/database/errors.go
  internal/migration/migration.go
Labels: 4.0

#17201 Expose the namespace for changestream pruner
  internal/worker/changestreampruner/worker.go
  internal/worker/changestreampruner/worker_test.go
Labels: 4.0

#17180 Restore runcmd shell flag after setting juju's runcmd
  cloudconfig/userdatacfg_unix.go
Labels: 3.5

#17195 Add spaces reload functionality to network domain
  domain/network/service/interface.go
  domain/network/service/package_mock_test.go
  domain/network/service/package_test.go
  domain/network/service/space.go
  domain/network/service/space_test.go
  domain/servicefactory/controller.go
  internal/worker/providerservicefactory/logger_mock_test.go
  internal/worker/providerservicefactory/manifold.go
  internal/worker/servicefactory/manifold.go
  internal/worker/servicefactory/servicefactory_logger_mock_test.go
Labels: 4.0

#17215 Backport charm upload changes
  apiserver/apiserver.go
  apiserver/charms.go
  apiserver/objects.go
  apiserver/objects_test.go
  cmd/jujud-controller/agent/controllercharm.go
Labels: 3.5

#17218 3.5 into main
  apiserver/facades/client/application/deployrepository.go
  apiserver/facades/client/application/deployrepository_test.go
  internal/cloudconfig/userdatacfg_unix.go
  internal/worker/uniter/container/workload.go
  internal/worker/uniter/container/workload_test.go
  internal/worker/uniter/hook/hook.go
  internal/worker/uniter/hook/hook_test.go
  internal/worker/uniter/pebblenotices.go
  internal/worker/uniter/pebblenotices_test.go
  internal/worker/uniter/runner/context/contextfactory.go
  scripts/discourse-sync/requirements.txt
  testcharms/charms/pebble-notices/src/charm.py
  testcharms/charms/pebble-notices/tests/unit/test_charm.py
  tests/includes/aws_ami_creation.sh
  tests/suites/sidecar/sidecar.sh
  tests/suites/sidecar/task.sh
Labels: 4.0

#17210 Add state implementation for remote secret consumers
  domain/secret/errors/errors.go
  domain/secret/service/consume.go
  domain/secret/service/service.go
  domain/secret/service/service_test.go
  domain/secret/service/state_mock_test.go
  domain/secret/state/state.go
  domain/secret/state/state_test.go
  domain/secret/state/types.go
Labels: 4.0

#17203 Introduces end to end model config setting.
  apiserver/facades/client/modelmanager/modelmanager.go
  domain/modelconfig/modelmigration/import.go
  domain/modeldefaults/service/service.go
  domain/modeldefaults/service/service_test.go
  domain/modeldefaults/service/testing/state.go
  domain/modeldefaults/state/state.go
  domain/modeldefaults/state/state_test.go
  environs/config/config.go
  environs/config/config_test.go
Labels: 4.0

#17164 Dqlite repl dump to sqlite3
  Makefile
  scripts/dqlite/cmd/main.go
Labels: 4.0

#17194 Replace series with base in packaging
  cloudconfig/cloudinit/cloudinit.go
  cloudconfig/cloudinit/cloudinit_centos.go
  cloudconfig/cloudinit/cloudinit_test.go
  cloudconfig/cloudinit/cloudinit_ubuntu.go
  cloudconfig/cloudinit/interface.go
  cloudconfig/cloudinit/renderscript_test.go
  cloudconfig/cloudinit/utils.go
  container/kvm/initialisation.go
  container/kvm/initialisation_internal_test.go
  container/lxd/initialisation_linux.go
  container/lxd/initialisation_test.go
  go.mod
  go.sum
  mongo/admin_test.go
  mongo/mongo.go
  mongo/mongo_test.go
  packaging/dependency/kvm.go
  packaging/dependency/lxd.go
  packaging/dependency/mongo.go
  packaging/manager.go
  packaging/manager_test.go
  upgrades/preupgradesteps.go
  upgrades/preupgradesteps_test.go
  worker/proxyupdater/proxyupdater.go
  worker/proxyupdater/proxyupdater_test.go
Labels: 3.5

#17202 Use access cloud service
  agent/agentbootstrap/bootstrap.go
  apiserver/common/modelmanagerinterface.go
  apiserver/facades/agent/uniter/uniter_network_test.go
  apiserver/facades/client/cloud/backend.go
  apiserver/facades/client/cloud/cloud.go
  apiserver/facades/client/cloud/cloud_test.go
  apiserver/facades/client/cloud/mocks/cloud_mock.go
  apiserver/facades/client/cloud/package_test.go
  apiserver/facades/client/cloud/register.go
  apiserver/facades/client/controller/backend.go
  apiserver/facades/client/controller/mocks/state_mock.go
  apiserver/facades/client/modelmanager/listmodelsummaries_test.go
  apiserver/facades/client/modelmanager/mocks/service_mock.go
  apiserver/facades/client/modelmanager/modelinfo_test.go
  apiserver/facades/client/modelmanager/modelmanager.go
  apiserver/facades/client/modelmanager/modelmanager_test.go
  apiserver/facades/client/modelmanager/package_test.go
  apiserver/facades/client/modelmanager/register.go
  apiserver/facades/client/modelmanager/services.go
  domain/access/errors/errors.go
  domain/access/service/service.go
  domain/access/state/permission.go
  domain/access/state/types.go
  domain/cloud/bootstrap/bootstrap.go
  domain/cloud/bootstrap/bootstrap_test.go
  domain/cloud/service/package_mock_test.go
  domain/cloud/service/service.go
  domain/cloud/service/service_test.go
  domain/cloud/state/state.go
  domain/cloud/state/state_test.go
  domain/cloud/state/types.go
  domain/credential/bootstrap/bootstrap_test.go
  domain/credential/state/state_test.go
  domain/model/bootstrap/bootstrap_test.go
  domain/model/state/state_test.go
  domain/model/state/testing/model.go
  domain/secretbackend/state/state_test.go
  domain/servicefactory/testing/suite.go
  juju/testing/apiserver.go
  state/clouduser.go
  state/clouduser_test.go
  state/initialize.go
  state/initialize_test.go
  state/state_test.go
  state/useraccess.go
Labels: 4.0

#17221 Move to CLA verification 'v1'
  .github/workflows/cla.yml
Labels: 2.9

#17224 Fix the case where a nil app config map could be returned with a nil error
  api/controller/caasunitprovisioner/client.go
  apiserver/facades/client/application/deploy_test.go
  caas/kubernetes/provider/k8s.go
  state/application.go
  state/application_test.go
  worker/uniter/actions/resolver.go
Labels: 3.4

#17212 Add DDL to support secret permission access and roles
  apiserver/facades/agent/secretsmanager/secrets.go
  apiserver/facades/agent/secretsmanager/secrets_test.go
  apiserver/facades/client/secrets/secrets.go
  apiserver/facades/client/secrets/secrets_test.go
  apiserver/facades/schema.json
  core/permission/access.go
  domain/schema/model.go
  domain/schema/schema_test.go
  domain/schema/secret.go
  domain/schema/triggers.go
  domain/secret/service/params.go
  domain/secret/state/state.go
Labels: 4.0

#17229 Backport pull request #17224
  api/controller/caasunitprovisioner/client.go
  apiserver/facades/client/application/deploy_test.go
  caas/kubernetes/provider/k8s.go
  state/application.go
  state/application_test.go
  worker/uniter/actions/resolver.go
Labels: 3.3

#17110 DDL changes for Juju controller models.
  agent/agentbootstrap/bootstrap.go
  apiserver/facades/agent/credentialvalidator/credentialvalidator.go
  apiserver/facades/client/modelmanager/modelmanager.go
  apiserver/facades/client/modelmanager/services.go
  core/cloud/cloud.go
  core/cloud/testing/testing.go
  core/credential/credential.go
  core/credential/credential_test.go
  domain/access/state/permission.go
  domain/access/state/permission_test.go
  domain/cloud/state/state.go
  domain/cloud/state/state_test.go
  domain/cloud/state/testing/cloud.go
  domain/cloud/state/types.go
  domain/controllernode/service/package_mock_test.go
  domain/controllernode/service/service.go
  domain/controllernode/service/service_test.go
  domain/controllernode/state/state.go
  domain/controllernode/state/state_test.go
  domain/credential/errors/errors.go
  domain/credential/state/state.go
  domain/credential/state/state_test.go
  domain/credential/state/types.go
  domain/model/bootstrap/bootstrap.go
  domain/model/errors/errors.go
  domain/model/modelmigration/import.go
  domain/model/modelmigration/import_test.go
  domain/model/modelmigration/migrations_mock_test.go
  domain/model/service/service.go
  domain/model/service/service_test.go
  domain/model/state/state.go
  domain/model/state/state_test.go
  domain/model/state/testing/model.go
  domain/modeldefaults/state/state.go
  domain/schema/controller.go
  domain/schema/model.go
  domain/schema/schema_test.go
  domain/schema/secret.go
  domain/secretbackend/service/interface.go
  domain/secretbackend/service/service.go
  domain/secretbackend/service/service_test.go
  domain/secretbackend/service/state_mock_test.go
  domain/secretbackend/state/state.go
  domain/secretbackend/state/state_test.go
  domain/secretbackend/state/types.go
  internal/worker/changestreampruner/worker.go
  internal/worker/changestreampruner/worker_test.go
  internal/worker/dbaccessor/worker.go
  internal/worker/dbaccessor/worker_integration_test.go
  internal/worker/dbaccessor/worker_namespace_test.go
Labels: has merge conflicts, 4.0

#17213 [JUJU-5878] Replace DetectSeries.. with DetectBase..
  environs/bootstrap/bootstrap.go
  environs/bootstrap/bootstrap_test.go
  environs/interface.go
  environs/manual/sshprovisioner/fakessh_test.go
  environs/manual/sshprovisioner/init_test.go
  environs/manual/sshprovisioner/provisioner_test.go
  environs/manual/sshprovisioner/sshprovisioner.go
  provider/lxd/environ.go
  provider/manual/environ.go
  provider/manual/environ_test.go
Labels: 3.6

#17228 Remove unused upgrade series code
  api/agent/upgradeseries/upgradeseries.go
  api/agent/upgradeseries/upgradeseries_test.go
  api/facadeversions.go
  apiserver/facades/agent/upgradeseries/register.go
  apiserver/facades/agent/upgradeseries/upgradeseries.go
  apiserver/facades/agent/upgradeseries/upgradeseries_test.go
  apiserver/facades/schema.json
  worker/upgradeseries/manifold.go
  worker/upgradeseries/mocks/package_mock.go
  worker/upgradeseries/shim.go
  worker/upgradeseries/upgrader.go
  worker/upgradeseries/upgrader_test.go
  worker/upgradeseries/worker.go
  worker/upgradeseries/worker_test.go
Labels: 3.6

#17223 Permission schema changes
  core/permission/access.go
  domain/access/state/permission.go
  domain/access/state/permission_test.go
  domain/access/state/types.go
  domain/cloud/state/state.go
  domain/cloud/state/types.go
  domain/schema/controller.go
  domain/schema/schema_test.go
Labels: 4.0

#17238 Fix insertion of new debug log records into the buffered logger
  api/apiclient_test.go
  api/common/logs.go
  apiserver/debuglog.go
  apiserver/debuglog_tailer.go
  cmd/juju/commands/debuglog.go
  cmd/juju/commands/debuglog_test.go
  core/logger/buf.go
  core/logger/buf_test.go
  core/logger/record.go
  core/logger/record_test.go
  internal/logtailer/tailer.go
  internal/logtailer/tailer_test.go
  rpc/params/internal.go
Labels: 4.0

#17239 Do not render empty pod affinity info
  caas/kubernetes/provider/application/constraints.go
  caas/kubernetes/provider/application/constraints_test.go
Labels: 3.3

#17240 Merge 3.3
  caas/kubernetes/provider/application/constraints.go
  caas/kubernetes/provider/application/constraints_test.go
Labels: 3.4

#17233 Merge provider trackers (IAAS & CAAS)
  apiserver/facades/client/modelmanager/modelmanager.go
  cmd/jujud-controller/agent/machine/manifolds.go
  cmd/jujud-controller/agent/machine/manifolds_test.go
  cmd/jujud-controller/agent/model/manifolds.go
  cmd/jujud-controller/agent/model/manifolds_test.go
  core/providertracker/providertracker.go
  domain/servicefactory/model.go
  domain/servicefactory/service.go
  domain/servicefactory/testing/suite.go
  internal/worker/providertracker/manifold.go
  internal/worker/providertracker/manifold_test.go
  internal/worker/providertracker/providerworker.go
  internal/worker/providertracker/providerworker_test.go
  internal/worker/providertracker/trackerworker.go
  internal/worker/providertracker/trackerworker_test.go
  internal/worker/servicefactory/manifold.go
  internal/worker/servicefactory/manifold_test.go
  internal/worker/servicefactory/worker.go
  internal/worker/servicefactory/worker_test.go
Labels: 4.0

#17245 Custom initial namespace query
  core/watcher/eventsource/base.go
  core/watcher/eventsource/namespace.go
  core/watcher/eventsource/namespace_test.go
  domain/watcher.go
Labels: 4.0

#17227 Update the version of sqlair in go.mod
  domain/secretbackend/state/state.go
  go.mod
  go.sum
Labels: 4.0

#17231 Implement state functionality for saving and reading secret permissions
  apiserver/facades/agent/secretsmanager/secrets.go
  apiserver/facades/agent/secretsmanager/secrets_test.go
  apiserver/facades/controller/crossmodelsecrets/crossmodelsecrets.go
  domain/secret/errors/errors.go
  domain/secret/grant.go
  domain/secret/grant_test.go
  domain/secret/params.go
  domain/secret/service/access.go
  domain/secret/service/params.go
  domain/secret/service/service.go
  domain/secret/service/service_test.go
  domain/secret/service/state_mock_test.go
  domain/secret/state/state.go
  domain/secret/state/state_test.go
  domain/secret/state/types.go
  domain/secret/types.go
Labels: 4.0

#17214 Secret obsolete watcher
  apiserver/facades/client/modelconfig/modelconfig_test.go
  apiserver/facades/controller/migrationtarget/servicefactory_mock_test.go
  domain/schema/controller.go
  domain/schema/model.go
  domain/schema/schema_test.go
  domain/secret/service/package_test.go
  domain/secret/service/service.go
  domain/secret/service/service_test.go
  domain/secret/service/state_mock_test.go
  domain/secret/service/watcher.go
  domain/secret/service/watcher_mock_test.go
  domain/secret/service/watcherfactory_mock_test.go
  domain/secret/state/state.go
  domain/secret/state/state_test.go
  domain/secret/state/types.go
  domain/secret/watcher_test.go
  domain/secretbackend/service/service.go
  domain/secretbackend/service/service_test.go
  domain/secretbackend/service/watcher.go
  domain/servicefactory/model.go
  domain/servicefactory/testing/service.go
  internal/migration/servicefactory_mock_test.go
  internal/servicefactory/interface.go
  internal/worker/servicefactory/servicefactory_mock_test.go
  internal/worker/uniter/remotestate/watcher.go
Labels: 4.0

#17217 Replace environs.ReloadSpaces by network service
  agent/agentbootstrap/bootstrap.go
  apiserver/facades/client/modelmanager/modelmanager.go
  apiserver/facades/client/modelmanager/modelmanager_test.go
  apiserver/facades/client/modelmanager/register.go
  apiserver/facades/client/modelmanager/services.go
  apiserver/facades/client/modelmanager/shims.go
  apiserver/facades/client/spaces/interface.go
  apiserver/facades/client/spaces/package_mock_test.go
  apiserver/facades/client/spaces/package_test.go
  apiserver/facades/client/spaces/register.go
  apiserver/facades/client/spaces/reload.go
  apiserver/facades/client/spaces/reload_test.go
  apiserver/facades/client/spaces/spaces.go
  domain/network/service/interface.go
  domain/network/service/package_mock_test.go
  domain/network/service/space.go
  domain/network/service/space_test.go
  domain/network/state/space.go
  domain/network/state/space_test.go
  domain/network/state/subnet.go
  domain/network/state/subnet_test.go
  domain/network/state/types.go
  domain/schema/model.go
  domain/servicefactory/controller.go
  domain/servicefactory/model.go
  environs/space/environs_mock_test.go
  environs/space/package_test.go
  environs/space/spaces.go
  environs/space/spaces_mock_test.go
  environs/space/spaces_test.go
  environs/space/state.go
  internal/worker/bootstrap/bootstrap_mock_test.go
  internal/worker/bootstrap/manifold.go
  internal/worker/bootstrap/worker.go
  internal/worker/bootstrap/worker_test.go
  internal/worker/providerservicefactory/logger_mock_test.go
  internal/worker/providerservicefactory/manifold.go
  internal/worker/servicefactory/manifold.go
  internal/worker/servicefactory/servicefactory_logger_mock_test.go
Labels: 4.0

#17243 Implement scp binary file copy with sshinit.
  cloudconfig/cloudinit/cloudinit.go
  cloudconfig/cloudinit/cloudinit_test.go
  cloudconfig/cloudinit/filetransporter_mock_test.go
  cloudconfig/cloudinit/interface.go
  cloudconfig/cloudinit/package_test.go
  cloudconfig/cloudinit/utils.go
  cloudconfig/sshinit/configure.go
  cloudconfig/sshinit/filetransport.go
  cloudconfig/sshinit/filetransport_test.go
  cloudconfig/sshinit/package_test.go
  cloudconfig/sshinit/sshclient_mock_test.go
  provider/common/bootstrap.go
Labels: 3.6

#17256 Mapper watchers
  core/watcher/eventsource/base.go
  core/watcher/eventsource/namespace.go
  core/watcher/eventsource/namespace_test.go
  core/watcher/eventsource/value.go
  core/watcher/eventsource/value_test.go
  domain/blockdevice/service/package_test.go
  domain/blockdevice/service/service.go
  domain/blockdevice/service/state_mock_test.go
  domain/blockdevice/state/state.go
  domain/upgrade/service/package_mock_test.go
  domain/upgrade/service/service.go
  domain/upgrade/service/service_test.go
  domain/watcher.go
  domain/watcher_test.go
Labels: 4.0

#17258 Unblock model migration
  .github/workflows/migrate.yml
  domain/model/modelmigration/import.go
  domain/model/modelmigration/import_test.go
  domain/modelconfig/modelmigration/export.go
  domain/modelconfig/modelmigration/import.go
  domain/modelconfig/service/service.go
  domain/modelconfig/service/service_test.go
  domain/servicefactory/model.go
Labels: 4.0

#17248 Drop GetSeriesFromBase call from equinix provider
  provider/equinix/environ.go
Labels: 3.6

#17263 Add support for deleting secrets
  apiserver/common/secrets/access.go
  apiserver/common/secrets/access_test.go
  apiserver/common/secrets/drain.go
  apiserver/common/secrets/drain_test.go
  apiserver/common/secrets/mocks/commonsecrets_mock.go
  apiserver/common/secrets/package_test.go
  apiserver/common/secrets/secrets.go
  apiserver/common/secrets/service.go
  apiserver/errors/errors.go
  apiserver/facades/agent/secretsmanager/leadership.go
  apiserver/facades/agent/secretsmanager/mocks/secrets.go
  apiserver/facades/agent/secretsmanager/secrets.go
  apiserver/facades/agent/secretsmanager/secrets_test.go
  apiserver/facades/agent/secretsmanager/service.go
  apiserver/facades/client/secrets/mocks/secretsstate.go
  apiserver/facades/client/secrets/secrets.go
  apiserver/facades/client/secrets/secrets_test.go
  apiserver/facades/client/secrets/service.go
  apiserver/facades/controller/crossmodelsecrets/crossmodelsecrets.go
  apiserver/facades/controller/crossmodelsecrets/crossmodelsecrets_test.go
  apiserver/facades/controller/crossmodelsecrets/mocks/secretservice.go
  apiserver/facades/controller/crossmodelsecrets/service.go
  domain/schema/secret.go
  domain/secret/errors/errors.go
  domain/secret/service/access.go
  domain/secret/service/access_test.go
  domain/secret/service/delete.go
  domain/secret/service/delete_test.go
  domain/secret/service/package_test.go
  domain/secret/service/params.go
  domain/secret/service/service.go
  domain/secret/service/service_test.go
  domain/secret/service/state_mock_test.go
  domain/secret/service/token_mock_test.go
  domain/secret/service/watcher.go
  domain/secret/state/state.go
  domain/secret/state/state_test.go
  domain/secret/state/types.go
Labels: 4.0

#17265 Remove debug logging for loggo labels.
  cmd/jujud-controller/agent/machine.go
  cmd/jujud/agent/machine.go
Labels: 4.0

#17267 Fix client tests gh action for mac
  .github/workflows/client-tests.yml
Labels: 3.1

#17261 Use access service in controller facade
  api/package_test.go
  apiserver/admin_test.go
  apiserver/facades/client/controller/backend.go
  apiserver/facades/client/controller/controller.go
  apiserver/facades/client/controller/controller_test.go
  apiserver/facades/client/controller/destroy.go
  apiserver/facades/client/controller/mocks/domain_mock.go
  apiserver/facades/client/controller/mocks/state_mock.go
  apiserver/facades/client/controller/package_test.go
  apiserver/facades/client/controller/register.go
  core/permission/user_test.go
  domain/access/errors/errors.go
  domain/access/state/permission.go
  domain/access/state/permission_test.go
  rpc/params/controller.go
Labels: 4.0

#17269 3.1 into 3.3
  .github/workflows/client-tests.yml
Labels: 3.3

#17259 Remove BaseSeriesVersion & UbuntuBaseVersion
  apiserver/facades/client/machinemanager/upgradebase.go
  core/base/base.go
  core/base/supportedbases.go
  environs/bootstrap/bootstrap.go
  packaging/dependency/kvm.go
  packaging/dependency/lxd.go
  packaging/dependency/mongo.go
  provider/common/bootstrap.go
  provider/dummy/environs.go
  provider/equinix/environ.go
  provider/oci/images.go
  state/charm.go
  upgrades/upgradevalidation/validation.go
  version/series.go
Labels: 3.6

#17272 Fix incorrect usage of FilesystemMountPoint
  state/application.go
  state/storage.go
Labels: 3.6

#17277 Rename model logger
  apiserver/logsink.go
  apiserver/logtransfer.go
  cmd/juju/commands/debuglog.go
  cmd/jujud-controller/agent/machine_legacy_test.go
  core/logger/buf.go
  core/logger/buf_test.go
  core/logger/interface.go
  core/logger/mocks/logger_mock.go
  core/logger/package_test.go
  internal/worker/logsink/loggers.go
  internal/worker/logsink/loggers_test.go
  internal/worker/logsink/manifold.go
  internal/worker/logsink/manifold_test.go
  internal/worker/logsink/worker.go
  internal/worker/logsink/worker_test.go
  internal/worker/modelworkermanager/manifold_test.go
  internal/worker/modelworkermanager/modelworkermanager.go
  internal/worker/modelworkermanager/modelworkermanager_test.go
  juju/testing/apiserver.go
Labels: 4.0

#17170 Adds model list support for dqlite.
  apiserver/facades/client/modelmanager/mocks/service_mock.go
  apiserver/facades/client/modelmanager/modelmanager.go
  apiserver/facades/client/modelmanager/modelmanager_test.go
  apiserver/facades/client/modelmanager/package_test.go
  apiserver/facades/client/modelmanager/services.go
  core/model/model.go
  core/user/user.go
  domain/model/service/service.go
  domain/model/service/service_test.go
  domain/model/service/state_test.go
  domain/model/state/state.go
  domain/model/state/state_test.go
  internal/worker/upgradedatabase/service_mock_test.go
  internal/worker/upgradedatabase/worker.go
  internal/worker/upgradedatabase/worker_test.go
Labels: 4.0

#17284 Ensure we write cloud region when doing add-model
  apiserver/facades/client/modelmanager/modelmanager.go
  domain/model/state/state.go
  domain/model/state/state_test.go
Labels: 4.0

#17295 Wireup external secrets
  api/common/secretbackends/client.go
  apiserver/common/secrets/mocks/commonsecrets_mock.go
  apiserver/common/secrets/mocks/provider_mock.go
  apiserver/common/secrets/secrets.go
  apiserver/common/secrets/secrets_test.go
  apiserver/common/secrets/service.go
  apiserver/errors/errors.go
  apiserver/errors/errors_test.go
  apiserver/facades/agent/secretsmanager/mocks/secretsprovider.go
  apiserver/facades/client/secrets/mocks/secretsbackend.go
  caas/broker.go
  caas/kubernetes/provider/rbac.go
  caas/kubernetes/provider/rbac_test.go
  caas/mocks/broker_mock.go
  core/secrets/secret.go
  domain/secret/service/consume.go
  domain/secret/service/delete.go
  domain/secret/service/delete_test.go
  domain/secret/service/service.go
  domain/secret/service/state_mock_test.go
  domain/secret/state/state.go
  domain/secret/state/state_test.go
  domain/secret/state/types.go
  domain/secretbackend/service/provider_mock_test.go
  internal/secrets/backend.go
  internal/secrets/backend_test.go
  internal/secrets/provider/juju/backend.go
  internal/secrets/provider/juju/provider.go
  internal/secrets/provider/kubernetes/backend.go
  internal/secrets/provider/kubernetes/mocks/kubernetes_mocks.go
  internal/secrets/provider/kubernetes/provider.go
  internal/secrets/provider/kubernetes/provider_test.go
  internal/secrets/provider/provider.go
  internal/secrets/provider/vault/backend.go
  internal/secrets/provider/vault/provider.go
  internal/secrets/provider/vault/provider_test.go
  internal/worker/providertracker/caas_mock_test.go
  internal/worker/uniter/runner/context/context.go
  rpc/params/apierror.go
  tests/includes/juju.sh
  tests/suites/secrets_iaas/cmr.sh
  tests/suites/secrets_iaas/juju.sh
  tests/suites/secrets_k8s/k8s.sh
Labels: 4.0

#17294 Remove check for machine addresses when updating endpoint bindings
  state/endpoint_bindings.go
Labels: 4.0

#17291 Fix returned errors on network domain state layer
  domain/network/service/space.go
  domain/network/service/subnet.go
  domain/network/state/space.go
  domain/network/state/subnet.go
  domain/network/state/subnet_test.go
Labels: 4.0

#17300 3.6 into main
  apiserver/facades/client/machinemanager/machinemanager_test.go
  apiserver/facades/controller/charmrevisionupdater/charmhub.go
  apiserver/facades/controller/charmrevisionupdater/updater.go
  core/base/supported.go
  core/base/supported_test.go
  core/base/supportedbases.go
  core/base/supportedbases_test.go
  core/base/supportedseries.go
  core/base/supportedseries_linux_test.go
  core/base/supportedseries_test.go
  environs/imagedownloads/simplestreams.go
  environs/imagemetadata/simplestreams.go
  environs/tools/tools.go
  go.mod
  go.sum
  internal/provider/azure/internal/imageutils/images.go
  internal/provider/common/bootstrap_test.go
  internal/provider/openstack/local_test.go
Labels: 4.0

#17283 Fixup 2.9 CI
  .github/workflows/client-tests.yml
  .github/workflows/terraform-smoke.yml
  apiserver/facades/client/modelupgrader/upgrader_test.go
  core/series/supported.go
  core/series/supportedseries_linux_test.go
  core/series/supportedseries_test.go
  go.mod
  go.sum
  upgrades/upgradevalidation/migrate_test.go
  upgrades/upgradevalidation/upgrade_test.go
  upgrades/upgradevalidation/validation_test.go
Labels: 2.9

#17297 Remove usages of SubnetsByCIDR and AllSubnets on machines and linklayerdevices.
  apiserver/facades/agent/provisioner/interface.go
  apiserver/facades/agent/provisioner/mocks/containerizer_mock.go
  apiserver/facades/agent/provisioner/mocks/package_mock.go
  apiserver/facades/agent/provisioner/provisioner.go
  apiserver/facades/agent/provisioner/provisioner_test.go
  apiserver/facades/client/spaces/interface.go
  apiserver/facades/client/spaces/package_mock_test.go
  apiserver/facades/client/spaces/spaces.go
  apiserver/facades/client/spaces/spaces_test.go
  internal/network/containerizer/bridgepolicy.go
  internal/network/containerizer/bridgepolicy_mock_test.go
  internal/network/containerizer/bridgepolicy_test.go
  internal/network/containerizer/linklayerdevicesforspaces_test.go
  internal/network/containerizer/shim.go
  state/ipaddresses_test.go
  state/linklayerdevices.go
  state/linklayerdevices_ipaddresses.go
  state/linklayerdevices_test.go
  state/machine_linklayerdevices.go
Labels: 4.0

#17307 Fix run_controller_clouds() subtest
  tests/suites/cli/display_clouds.sh
Labels: bug, 4.0

#17303 Merge 2.9 into 3.1
  .github/workflows/cla.yml
  .github/workflows/terraform-smoke.yml
  apiserver/facades/client/application/application_unit_test.go
  go.mod
  go.sum
Labels: 3.1
