Repository juju/juju, pull requests merged in 2024-02, with the labels that each got.

#16795 Adds controller system ssh key to controller config.
  apiserver/facades/agent/keyupdater/authorisedkeys.go
  apiserver/facades/agent/keyupdater/authorisedkeys_test.go
  apiserver/facades/agent/keyupdater/register.go
  apiserver/facades/agent/provisioner/provisioner.go
  apiserver/facades/agent/provisioner/provisioner_test.go
  apiserver/facades/client/keymanager/keymanager.go
  apiserver/facades/client/keymanager/keymanager_test.go
  apiserver/facades/schema.json
  cmd/juju/commands/bootstrap.go
  cmd/jujud/agent/bootstrap.go
  cmd/jujud/agent/bootstrap_test.go
  controller/config.go
  controller/configschema.go
  controller/modelmanager/createmodel.go
  controller/modelmanager/createmodel_test.go
  environs/config/authkeys.go
  environs/config/authkeys_test.go
  internal/cloudconfig/instancecfg/instancecfg.go
  state/controller_test.go
Labels: 4.0

#16868 Add service and state for saving very minimal app and unit records in dqlite
  domain/application/errors/errors.go
  domain/application/params.go
  domain/application/service/package_mock_test.go
  domain/application/service/package_test.go
  domain/application/service/params.go
  domain/application/service/service.go
  domain/application/service/service_test.go
  domain/application/state/package_test.go
  domain/application/state/state.go
  domain/application/state/state_test.go
  domain/machine/service/service.go
  domain/servicefactory/model.go
  domain/servicefactory/testing/service.go
  domain/unit/errors/errors.go
  domain/unit/service/package_mock_test.go
  domain/unit/service/package_test.go
  domain/unit/service/service.go
  domain/unit/service/service_test.go
  domain/unit/state/package_test.go
  domain/unit/state/state.go
  domain/unit/state/state_test.go
  internal/servicefactory/interface.go
  internal/worker/servicefactory/servicefactory_mock_test.go
Labels: 4.0

#16882 Update go version on snapcraft yaml
  scripts/juju-mongotop/go.mod
  snap/snapcraft.yaml
Labels: 4.0

#16876 Pass all the availability zones when discovering subnets in clustered lxd
  provider/lxd/environ_network.go
  provider/lxd/environ_network_test.go
Labels: bug, 3.3

#16828 S3bucketname
  cmd/jujud/agent/machine/manifolds.go
  core/objectstore/types.go
  core/objectstore/types_test.go
  internal/objectstore/factory.go
  internal/objectstore/fileobjectstore.go
  internal/objectstore/s3objectstore.go
  internal/objectstore/s3objectstore_test.go
  internal/s3client/client.go
  internal/worker/objectstore/manifold.go
  internal/worker/objectstore/manifold_test.go
  internal/worker/objectstore/objectstore_mock_test.go
  internal/worker/objectstore/package_test.go
  internal/worker/objectstore/worker.go
  internal/worker/objectstore/worker_test.go
  internal/worker/objectstores3caller/manifold.go
  internal/worker/objectstores3caller/manifold_test.go
  internal/worker/objectstores3caller/package_test.go
  internal/worker/objectstores3caller/services_mocks_test.go
  internal/worker/objectstores3caller/worker.go
  internal/worker/objectstores3caller/worker_test.go
Labels: 4.0

#16877 Provide controller config rules
  .github/golangci-lint.config.yaml
  .github/workflows/static-analysis.yml
  controller/config.go
  domain/cloud/state/state.go
  domain/controllerconfig/service/package_mock_test.go
  domain/controllerconfig/service/service.go
  domain/controllerconfig/service/service_test.go
  domain/controllerconfig/state/state.go
  domain/controllerconfig/state/state_test.go
  domain/controllernode/state/state_test.go
  domain/externalcontroller/state/state.go
  domain/externalcontroller/state/state_test.go
  domain/lease/state/state.go
  domain/lease/state/state_test.go
  domain/model/state/state.go
  domain/network/state/space_test.go
  domain/network/state/subnet_test.go
  scripts/dqlite-bench/ops.go
  tests/suites/static_analysis/lint_go.sh
Labels: 4.0

#16874 Move the tmp file location for the objectstore
  internal/objectstore/base.go
  internal/objectstore/factory.go
  internal/objectstore/fileobjectstore.go
  internal/objectstore/s3objectstore.go
  internal/objectstore/s3objectstore_test.go
Labels: 4.0

#16890 Revert dot-minikube on snapcraft until auto-connect is approved
  snap/snapcraft.yaml
Labels: 3.1

#16862 Lock object blobs with a retention lock
  internal/s3client/client.go
  internal/s3client/client_test.go
Labels: 4.0

#16852 Fix racy test in dbaccessor
  internal/worker/dbaccessor/package_test.go
  internal/worker/dbaccessor/tracker.go
  internal/worker/dbaccessor/tracker_test.go
Labels: 4.0

#16886 Watchable services
  domain/blockdevice/modelmigration/export.go
  domain/blockdevice/modelmigration/import.go
  domain/blockdevice/service/service.go
  domain/blockdevice/service/service_test.go
  domain/blockdevice/watcher_test.go
  domain/cloud/service/service.go
  domain/cloud/service/service_test.go
  domain/controllerconfig/controllerconfig_test.go
  domain/controllerconfig/service/service.go
  domain/controllerconfig/service/service_test.go
  domain/credential/modelmigration/export.go
  domain/credential/modelmigration/import.go
  domain/credential/service/service.go
  domain/credential/service/service_test.go
  domain/externalcontroller/modelmigration/export.go
  domain/externalcontroller/modelmigration/import.go
  domain/externalcontroller/service/service.go
  domain/externalcontroller/service/service_test.go
  domain/modelconfig/service/service.go
  domain/modelconfig/service/service_test.go
  domain/modeldefaults/service/service.go
  domain/modelmanager/service/service.go
  domain/objectstore/service/service.go
  domain/objectstore/service/service_test.go
  domain/objectstore/watcher_test.go
  domain/servicefactory/controller.go
  domain/servicefactory/model.go
  domain/servicefactory/testing/service.go
  domain/upgrade/service/service.go
  domain/upgrade/service/service_test.go
  internal/servicefactory/interface.go
  internal/worker/certupdater/manifold_test.go
  internal/worker/httpserver/manifold_test.go
  internal/worker/httpserverargs/manifold_test.go
  internal/worker/modelworkermanager/manifold_test.go
  internal/worker/objectstore/manifold_test.go
  internal/worker/servicefactory/servicefactory_mock_test.go
  internal/worker/upgradedatabase/manifold_test.go
  internal/worker/upgradedatabase/servicefactory_mock_test.go
Labels: 4.0

#16832 Move addresses and controller cloud service initialization to bootstrap worker
  agent/agentbootstrap/bootstrap.go
  agent/agentbootstrap/bootstrap_test.go
  apiserver/admin_test.go
  apiserver/facades/agent/deployer/deployer_test.go
  apiserver/facades/agent/provisioner/provisioner_test.go
  apiserver/facades/agent/uniter/uniter_test.go
  apiserver/server_test.go
  cmd/jujud/agent/agent_test.go
  cmd/jujud/agent/agenttest/agent.go
  cmd/jujud/agent/machine_test.go
  domain/network/service/space.go
  domain/network/service/space_test.go
  domain/servicefactory/model.go
  domain/servicefactory/testing/service.go
  internal/servicefactory/interface.go
  internal/worker/bootstrap/bootstrap_mock_test.go
  internal/worker/bootstrap/deployer.go
  internal/worker/bootstrap/manifold.go
  internal/worker/bootstrap/manifold_test.go
  internal/worker/bootstrap/package_test.go
  internal/worker/bootstrap/worker.go
  internal/worker/bootstrap/worker_test.go
  internal/worker/peergrouper/publish.go
  internal/worker/peergrouper/publish_test.go
  internal/worker/peergrouper/worker.go
  internal/worker/peergrouper/worker_test.go
  internal/worker/servicefactory/servicefactory_mock_test.go
  juju/testing/apiserver.go
  juju/testing/utils.go
  state/address.go
  state/address_test.go
  state/endpoint_bindings.go
  state/state_test.go
Labels: 4.0

#16567 Add lease manager worker documentation
  worker/lease/doc.go
Labels: 3.3

#16885 3.5 into main
  .github/workflows/merge.yml
  agent/agentbootstrap/bootstrap.go
  agent/agentbootstrap/bootstrap_test.go
  api/base/types.go
  apiserver/facades/client/modelmanager/modelinfo_test.go
  apiserver/facades/client/modelmanager/modelmanager.go
  apiserver/facades/controller/machineundertaker/backend.go
  apiserver/facades/controller/undertaker/undertaker.go
  apiserver/facades/controller/undertaker/undertaker_test.go
  cmd/jujud/agent/agenttest/agent.go
  cmd/jujud/agent/bootstrap_test.go
  cmd/jujud/agent/machine/manifolds.go
  internal/database/bootstrap.go
  internal/database/bootstrap_test.go
  internal/database/node.go
  internal/database/node_test.go
  internal/worker/dbaccessor/manifold.go
  internal/worker/dbaccessor/manifold_test.go
  internal/worker/dbaccessor/package_mock_test.go
  internal/worker/dbaccessor/worker.go
  internal/worker/dbaccessor/worker_integration_test.go
  internal/worker/dbaccessor/worker_namespace_test.go
  internal/worker/dbaccessor/worker_test.go
  testcharms/charms/pebble-notices/requirements.txt
  testcharms/charms/pebble-notices/src/charm.py
  testcharms/charms/pebble-notices/tests/unit/test_charm.py
Labels: 4.0

#16853 Turn charm URL in CharmIDs into strings
  api/client/application/client.go
  api/client/application/client_test.go
  api/client/charms/client.go
  api/client/charms/client_test.go
  api/client/resources/client.go
  api/client/resources/client_upload_test.go
  apiserver/facades/client/client/perm_test.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/bundlehandler_test.go
  cmd/juju/application/deployer/charm.go
  cmd/juju/application/deployer/charm_test.go
  cmd/juju/application/deployer/interface.go
  cmd/juju/application/deployer/mocks/deploy_mock.go
  cmd/juju/application/refresh.go
  cmd/juju/application/refresh_test.go
  cmd/juju/application/utils/interface.go
  cmd/juju/application/utils/mocks/charmresource_mock.go
  cmd/juju/application/utils/utils.go
  cmd/juju/application/utils/utils_test.go
  cmd/juju/resource/charmresources.go
  cmd/juju/resource/deploy_test.go
Labels: 3.5

#16881 Adds setting and configuring agent version.
  agent/agentbootstrap/bootstrap.go
  domain/model/bootstrap/bootstrap.go
  domain/model/errors/errors.go
  domain/model/service/service.go
  domain/model/service/service_test.go
  domain/model/state/state.go
  domain/model/state/state_test.go
  domain/model/types.go
  domain/model/types_test.go
  domain/servicefactory/controller.go
  environs/bootstrap/bootstrap.go
  internal/cloudconfig/instancecfg/instancecfg.go
Labels: 4.0

#16894 Permissions service layer
  core/permission/access.go
  core/permission/access_test.go
  core/permission/useraccess.go
  domain/permission/service/package_test.go
  domain/permission/service/service.go
  domain/permission/service/service_test.go
  domain/permission/service/state_mock_test.go
  domain/schema/controller.go
Labels: 4.0

#16898 Suppress klog log messages
  caas/kubernetes/provider/klog.go
  go.mod
Labels: 3.1

#16825 Remove series from charm url when adding charms in bundles
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/bundlehandler_test.go
Labels: 3.5

#16906 Ask cloud state if auth type is supported.
  cloud/clouds.go
  domain/cloud/state/state.go
  domain/cloud/state/state_test.go
Labels: 4.0

#16909 Moves model types from domain to core.
  agent/agentbootstrap/bootstrap.go
  apiserver/facades/client/cloud/register.go
  apiserver/facades/controller/migrationtarget/register.go
  core/model/model.go
  core/model/model_test.go
  domain/cloud/state/state_test.go
  domain/credential/service/modelcredential.go
  domain/model/service/service_test.go
  domain/model/state/state.go
  domain/model/state/state_test.go
  domain/model/types.go
  domain/model/types_test.go
Labels: 4.0

#16910 Add jujud-controller binary name.
  cmd/jujud-controller/main.go
  juju/names/names.go
Labels: 3.5

#16847 Wire up trace uniter hooks
  internal/worker/meterstatus/connected.go
  internal/worker/meterstatus/context.go
  internal/worker/meterstatus/context_test.go
  internal/worker/meterstatus/isolated.go
  internal/worker/meterstatus/manifold_test.go
  internal/worker/meterstatus/runner.go
  internal/worker/metrics/collect/context.go
  internal/worker/metrics/collect/context_test.go
  internal/worker/metrics/collect/manifold.go
  internal/worker/uniter/operation/executor.go
  internal/worker/uniter/operation/util_test.go
  internal/worker/uniter/runcommands/mock_test.go
  internal/worker/uniter/runner/context/context.go
  internal/worker/uniter/runner/context/env_test.go
  internal/worker/uniter/runner/factory_test.go
  internal/worker/uniter/runner/mocks/context_mock.go
  internal/worker/uniter/runner/runner.go
  internal/worker/uniter/runner/runner_test.go
Labels: 4.0

#16911 Add jujud-controller-snap-source controller config.
  .github/microk8s-launch-config-aws.yaml
  .github/workflows/microk8s-tests.yml
  .github/workflows/smoke.yml
  .github/workflows/upgrade.yml
  controller/config.go
  controller/config_test.go
  controller/configschema.go
  state/controller_test.go
Labels: 3.5

#16917 Fix docker cache for github actions.
  .github/microk8s-launch-config-aws.yaml
  .github/workflows/microk8s-tests.yml
  .github/workflows/smoke.yml
  .github/workflows/upgrade.yml
Labels: 2.9

#16916 Move api host ports filtering on management space to the bootstrap worker
  domain/network/service/space.go
  domain/network/service/space_test.go
  internal/worker/bootstrap/bootstrap_mock_test.go
  internal/worker/bootstrap/manifold.go
  internal/worker/bootstrap/worker.go
  internal/worker/bootstrap/worker_test.go
Labels: 4.0

#16928 Increments juju to 3.4.0
  scripts/win-installer/setup.iss
  snap/snapcraft.yaml
  version/version.go
Labels: 3.4

#16927 Clean up unnecessary log in the bootstrap worker
  internal/worker/bootstrap/worker.go
Labels: 4.0

#16900 Copy remaining charms handler tests to s3 charm handler
  apiserver/apiserver.go
  apiserver/charms.go
  apiserver/objects.go
  apiserver/objects_test.go
  apiserver/rest.go
Labels: 4.0

#16849 [SQLair] Replace slice queries in domain/cloud/state
  domain/cloud/bootstrap/bootstrap.go
  domain/cloud/state/state.go
  domain/cloud/state/types.go
  go.mod
  go.sum
  juju/testing/apiserver.go
Labels: 4.0

#16920 Migrate utils.Password to password.Password
  agent/agentbootstrap/bootstrap.go
  apiserver/admin_test.go
  apiserver/authentication/agent_test.go
  apiserver/authentication/user_test.go
  apiserver/facades/agent/caasapplication/application.go
  apiserver/facades/agent/meterstatus/meterstatus_integration_test.go
  apiserver/facades/agent/uniter/package_test.go
  apiserver/facades/agent/uniter/uniter_test.go
  apiserver/facades/client/machinemanager/instanceconfig.go
  apiserver/tools_test.go
  cmd/containeragent/initialize/package_test.go
  doc/bootstrapping.txt
  internal/auth/password_test.go
  internal/cloudconfig/podcfg/podcfg.go
  internal/password/package_test.go
  internal/password/password.go
  internal/password/password_test.go
  internal/worker/apicaller/connect.go
  internal/worker/caasapplicationprovisioner/application.go
  internal/worker/caasmodeloperator/modeloperator.go
  internal/worker/deployer/deployer.go
  internal/worker/provisioner/provisioner_task.go
  internal/worker/uniter/runner/runner.go
  juju/testing/apiserver.go
  scripts/generate-password/main.go
  state/application.go
  state/application_test.go
  state/enableha.go
  state/initialize.go
  state/machine.go
  state/migration_export_test.go
  state/migration_import_test.go
  state/model.go
  state/unit.go
  state/user.go
  state/user_test.go
  testing/factory/factory.go
  testing/factory/factory_test.go
Labels: 4.0

#16896 State layer for Annotation domain
  core/annotations/annotations.go
  domain/annotation/errors/errors.go
  domain/annotation/service/service.go
  domain/annotation/state/package_test.go
  domain/annotation/state/query.go
  domain/annotation/state/state.go
  domain/annotation/state/state_test.go
  domain/annotation/state/types.go
  domain/schema/model.go
  domain/schema/schema_test.go
Labels: 4.0

#16914 Refactor cli deployer code and tests
  cmd/juju/application/deployer/deployer.go
  cmd/juju/application/deployer/deployer_test.go
Labels: 4.0

#16945 Update to Pebble v1.4.1
  go.mod
  go.sum
Labels: 3.3

#16944 Add a log file tailer and wire up to the debug-log backend
  apiserver/apiserver.go
  apiserver/debuglog.go
  apiserver/debuglog_db.go
  apiserver/logsink.go
  apiserver/logtransfer.go
  cmd/internal/dumplogs/dumplogs.go
  core/logger/interface.go
  core/logger/tailer.go
  go.mod
  go.sum
  internal/logtailer/logging.go
  internal/logtailer/package_test.go
  internal/logtailer/tailer.go
  internal/logtailer/tailer_test.go
  internal/worker/logsink/loggers.go
  internal/worker/logsink/loggers_test.go
  internal/worker/logsink/manifold.go
  internal/worker/logsink/worker_test.go
  internal/worker/modelworkermanager/modelworkermanager.go
  internal/worker/modelworkermanager/modelworkermanager_test.go
  juju/testing/apiserver.go
  state/logs.go
  state/logs_test.go
Labels: 4.0

#16925 Wires up credential owner to user table.
  agent/agentbootstrap/bootstrap.go
  apiserver/facades/client/controller/controller_test.go
  domain/cloud/state/state.go
  domain/cloud/state/state_test.go
  domain/credential/bootstrap/bootstrap_test.go
  domain/credential/state/state.go
  domain/credential/state/state_test.go
  domain/model/state/state.go
  domain/model/state/state_test.go
  domain/schema/controller.go
  domain/user/state/state.go
  domain/user/state/state_test.go
  juju/testing/apiserver.go
Labels: 4.0

#16912 Bifurcate upgrade-controller and upgrade-model commands.
  cmd/juju/commands/main.go
  cmd/juju/commands/upgradecontroller.go
  cmd/juju/commands/upgradecontroller_test.go
  cmd/juju/commands/upgrademodel.go
  cmd/juju/commands/upgrademodel_test.go
  cmd/package_test.go
  environs/tools/build.go
Labels: 3.5

#16924 Insist users provide a base for pre-deployed charms
  cmd/juju/application/deployer/charm.go
  cmd/juju/application/deployer/charm_test.go
  cmd/juju/application/deployer/deployer.go
  cmd/juju/application/deployer/deployer_test.go
  core/base/supportedbases.go
  core/base/supportedbases_test.go
Labels: 4.0

#16963 Rename method on permission service
  core/permission/access.go
  domain/permission/package_test.go
  domain/permission/service/service.go
  domain/permission/service/service_test.go
  domain/permission/service/state_mock_test.go
  domain/permission/types.go
  domain/permission/types_test.go
Labels: 4.0

#16801 [JUJU-5100] - Dqlite secrets
  domain/schema/changelog.go
  domain/schema/controller.go
  domain/schema/model.go
  domain/schema/schema_test.go
  domain/schema/secret.go
  go.mod
Labels: 4.0

#16892 Object store namespace pruner
  apiserver/facades/controller/migrationmaster/package_test.go
  core/objectstore/metadata.go
  core/objectstore/objectstore.go
  domain/objectstore/service/service.go
  domain/objectstore/service/service_test.go
  domain/objectstore/service/state_mock_test.go
  domain/objectstore/state/state.go
  domain/objectstore/state/state_test.go
  internal/objectstore/base.go
  internal/objectstore/base_test.go
  internal/objectstore/fileobjectstore.go
  internal/objectstore/fileobjectstore_test.go
  internal/objectstore/objectstore_mock_test.go
  internal/objectstore/s3objectstore.go
  internal/objectstore/s3objectstore_test.go
  internal/objectstore/testing/memory.go
  internal/s3client/client.go
  internal/s3client/session_mock_test.go
  internal/worker/objectstore/client_mock_test.go
  internal/worker/objectstores3caller/package_mock_test.go
  internal/worker/units3caller/package_mock_test.go
Labels: 4.0

#16871 [SQLair] Replace slice queries in domain/externalcontroller/state
  domain/externalcontroller/state/state.go
  domain/externalcontroller/state/types.go
Labels: 4.0

#16977 Remove assign clean
  apiserver/common/modelstatus_test.go
  apiserver/facades/agent/uniter/uniter_test.go
  apiserver/facades/agent/upgrader/unitupgrader_test.go
  apiserver/facades/client/application/application_test.go
  apiserver/facades/client/application/application_unit_test.go
  apiserver/facades/client/application/deploy.go
  cmd/jujud-controller/agent/machine_legacy_test.go
  doc/provisioning.md
  environs/envcontext/distribution.go
  internal/provider/common/availabilityzones.go
  internal/provider/common/availabilityzones_test.go
  internal/provider/common/export_test.go
  internal/provider/ec2/environ.go
  internal/provider/ec2/environ_test.go
  internal/provider/maas/environ.go
  internal/provider/openstack/provider.go
  state/assign_test.go
  state/bench_test.go
  state/cleanup_test.go
  state/distribution.go
  state/distribution_test.go
  state/filesystem_test.go
  state/internal_test.go
  state/policy.go
  state/state.go
  state/stateenvirons/policy.go
  state/storage_dynamicadd_test.go
  state/storage_test.go
  state/testing/policy.go
  state/unit.go
  state/unit_assignment_test.go
  state/unit_test.go
  state/volume_test.go
Labels: 4.0

#16983 Disallow offering non-global scoped endpoints.
  state/applicationoffers.go
  state/applicationoffers_test.go
Labels: 3.3

#16952 Wire up new annotations service on dqlite in annotations facade
  apiserver/facades/client/annotations/client.go
  apiserver/facades/client/annotations/client_test.go
  apiserver/facades/client/annotations/register.go
  apiserver/facades/client/annotations/state.go
  apiserver/facades/client/client/perm_test.go
  apiserver/facades/controller/migrationtarget/servicefactory_mock_test.go
  domain/annotation/state/state.go
  domain/servicefactory/model.go
  domain/servicefactory/testing/service.go
  internal/migration/servicefactory_mock_test.go
  internal/servicefactory/interface.go
  internal/worker/servicefactory/servicefactory_mock_test.go
Labels: 4.0

#16836 Replace unique slice func with call to collections
  domain/network/state/space.go
Labels: 4.0

#16992 2 bug fixes together for landing in 2.9
  cmd/jujuc/main_test.go
  cmd/jujud/main_test.go
  core/series/supportedseries_linux_test.go
  core/series/supportedseries_test.go
Labels: 2.9

#16993 backport to 2.9: Have podman build append to manifest when building images.
  make_functions.sh
Labels: 2.9

#16978 Bug 2053216 num provision workers
  environs/config/config.go
  environs/config/config_test.go
  state/modelconfig_test.go
  worker/provisioner/provisioner_test.go
Labels: 2.9
