Repository juju/juju, pull requests merged in 2024-03, with the labels that each got.

#16955 Login changes
  api/apiclient.go
  api/client_credentials_login_provider.go
  api/client_credentials_login_provider_test.go
  api/connector/simpleconnector.go
  api/export_test.go
  api/interface.go
  api/session_token_login_provider.go
  api/session_token_login_provider_test.go
  api/state.go
  api/try_in_order_login_provider.go
  api/try_in_order_login_provider_test.go
  api/userpass_login_provider.go
  cmd/juju/controller/register.go
  cmd/juju/user/login.go
  cmd/modelcmd/base.go
  juju/api.go
  jujuclient/file.go
  jujuclient/interface.go
  jujuclient/mem.go
Labels: 3.5

#16961 Use a socket to notify controlleragentconfig worker of config reload instead of SIGHUP
  cmd/jujud-controller/agent/machine/manifolds.go
  core/paths/paths.go
  internal/socketlistener/package_test.go
  internal/socketlistener/socketlistener.go
  internal/socketlistener/socketlistener_test.go
  internal/worker/controlleragentconfig/manifold.go
  internal/worker/controlleragentconfig/manifold_test.go
  internal/worker/controlleragentconfig/worker.go
  internal/worker/controlleragentconfig/worker_test.go
  internal/worker/controlsocket/handlers.go
  internal/worker/controlsocket/handlers_test.go
  internal/worker/controlsocket/manifold.go
  internal/worker/controlsocket/worker.go
  internal/worker/controlsocket/worker_test.go
Labels: 4.0

#16962 Cleanup annotations from current state juju 5510
  apiserver/facades/client/client/backend.go
  apiserver/facades/client/client/mocks/client_mock.go
  apiserver/watcher.go
  rpc/params/multiwatcher.go
  rpc/params/multiwatcher_internal_test.go
  rpc/params/params_test.go
  state/allcollections.go
  state/allwatcher.go
  state/allwatcher_internal_test.go
  state/annotations.go
  state/annotations_test.go
  state/application.go
  state/machine.go
  state/migration_export.go
  state/migration_export_test.go
  state/migration_import.go
  state/migration_import_test.go
  state/migration_internal_test.go
  state/state.go
Labels: 4.0

#17013 Expose logging for errors
  domain/objectstore/state/state_test.go
  domain/schema/objectstore.go
  internal/database/errors.go
Labels: 4.0

#16996 Make sure subnets are updated when a NIC gets an address on manual cloud
  apiserver/common/networkingcommon/networkconfigapi.go
  apiserver/common/networkingcommon/networkconfigapi_test.go
Labels: bug, 3.3

#17027 Idempotent bootstrap worker
  internal/bootstrap/agentbinary.go
  internal/bootstrap/agentbinary_test.go
  internal/charm/services/storage.go
  internal/charm/services/storage_test.go
Labels: 4.0

#17010 Check instance/machine mapping exclusively for model migration in credential validation
  apiserver/common/credentialcommon/modelcredential.go
  apiserver/common/credentialcommon/modelcredential_test.go
  apiserver/facades/client/cloud/cloud.go
  apiserver/facades/client/cloud/cloud_test.go
  apiserver/facades/controller/migrationtarget/migrationtarget.go
Labels: 3.3

#17034 Provider service factory
  cmd/jujud-controller/agent/machine/manifolds.go
  cmd/jujud-controller/agent/machine/manifolds_test.go
  domain/cloud/service/package_mock_test.go
  domain/cloud/service/package_test.go
  domain/cloud/service/providerservice.go
  domain/cloud/service/providerservice_test.go
  domain/cloud/service/service.go
  domain/cloud/service/service_test.go
  domain/cloud/state/state.go
  domain/cloud/state/state_test.go
  domain/credential/service/package_test.go
  domain/credential/service/providerservice.go
  domain/credential/service/providerservice_test.go
  domain/credential/service/service.go
  domain/credential/service/service_test.go
  domain/credential/service/types.go
  domain/modelconfig/service/providerservice.go
  domain/modelconfig/service/providerservice_test.go
  domain/modelconfig/service/service.go
  domain/modelconfig/service/service_test.go
  domain/servicefactory/provider.go
  internal/servicefactory/interface.go
  internal/worker/providerservicefactory/changestream_mock_test.go
  internal/worker/providerservicefactory/logger_mock_test.go
  internal/worker/providerservicefactory/manifold.go
  internal/worker/providerservicefactory/manifold_test.go
  internal/worker/providerservicefactory/package_test.go
  internal/worker/providerservicefactory/servicefactory_mock_test.go
  internal/worker/providerservicefactory/worker.go
  internal/worker/providerservicefactory/worker_test.go
Labels: 4.0

#17043 Model table schema
  agent/agentbootstrap/bootstrap.go
  core/modelmigration/coordinator.go
  core/modelmigration/coordinator_test.go
  core/modelmigration/op_mock_test.go
  core/modelmigration/testing/operation.go
  domain/model/bootstrap/bootstrap.go
  domain/model/bootstrap/bootstrap_test.go
  domain/model/modelmigration/import.go
  domain/model/modelmigration/import_test.go
  domain/model/modelmigration/migrations_mock_test.go
  domain/model/modelmigration/package_test.go
  domain/model/service/modelservice.go
  domain/model/service/modelservice_test.go
  domain/model/service/service.go
  domain/model/service/service_test.go
  domain/model/state/modelstate.go
  domain/model/state/modelstate_test.go
  domain/model/state/state_test.go
  domain/model/types.go
  domain/schema/model.go
  domain/schema/schema_test.go
  domain/schema/testing/modelsuite.go
Labels: 4.0

#17047 Use docker v2 manifest format with podman push.
  make_functions.sh
Labels: 2.9

#17050 Fix LP, avoid panic on nil pointer.
  apiserver/facades/client/application/deployrepository.go
  apiserver/facades/client/application/deployrepository_test.go
Labels: 3.3

#17051 Add extra uniter debugging for resolving next actions
  worker/uniter/actions/resolver.go
  worker/uniter/remotestate/watcher.go
  worker/uniter/resolver.go
Labels: 3.3

#17039 Remodel storage constraint ddl to reflect reality
  domain/annotation/state/state_test.go
  domain/application/service/service_test.go
  domain/schema/model.go
  domain/schema/schema_test.go
Labels: 4.0

#17052 Ensure we wait for startup correctly
  internal/objectstore/base_test.go
  internal/objectstore/s3objectstore.go
Labels: 4.0

#17046 Log status updates via logging interface along with the DB write
  go.mod
  go.sum
  state/addmachine.go
  state/application.go
  state/filesystem.go
  state/initialize.go
  state/machine.go
  state/model.go
  state/modelcredential.go
  state/modelmigration.go
  state/relation.go
  state/remoteapplication.go
  state/state.go
  state/status.go
  state/unit.go
  state/unitagent.go
  state/volume.go
Labels: 4.0

#17048 Add secretbackend state layer;
  domain/schema/controller.go
  domain/schema/schema_test.go
  domain/schema/secret.go
  domain/secretbackend/errors/errors.go
  domain/secretbackend/package_test.go
  domain/secretbackend/params.go
  domain/secretbackend/state/operation.go
  domain/secretbackend/state/operation_test.go
  domain/secretbackend/state/package_test.go
  domain/secretbackend/state/state.go
  domain/secretbackend/state/state_test.go
  domain/secretbackend/state/types.go
  domain/secretbackend/state/types_test.go
  domain/types.go
  domain/types_test.go
Labels: 4.0

#16979 Replace legacy state with network domain on bridge policy
  apiserver/facades/agent/provisioner/provisioner.go
  internal/network/containerizer/bridgepolicy.go
  internal/network/containerizer/package_test.go
  internal/network/containerizer/shim.go
Labels: 4.0

#17053 Merge 2.9 to 3.1
  make_functions.sh
  tests/suites/relations/relation_list_app.sh
Labels: 3.5

#17035 Update utils for SSH newline bugfix
  apiserver/facades/client/keymanager/keymanager.go
  apiserver/facades/client/keymanager/keymanager_test.go
  cmd/juju/commands/remove_sshkeys.go
  go.mod
  go.sum
Labels: 3.3

#17058 Update controlsocket to user userservice
  apiserver/authentication/user.go
  apiserver/registration_test.go
  apiserver/stateauthenticator/authenticator_test.go
  apiserver/stateauthenticator/context.go
  apiserver/stateauthenticator/services_mock_test.go
  cmd/jujud-controller/agent/machine/manifolds.go
  core/user/user.go
  domain/user/service/service.go
  domain/user/service/service_test.go
  internal/worker/bootstrap/bootstrap_mock_test.go
  internal/worker/bootstrap/manifold.go
  internal/worker/bootstrap/package_test.go
  internal/worker/bootstrap/worker.go
  internal/worker/bootstrap/worker_test.go
  internal/worker/controlsocket/manifold.go
  internal/worker/controlsocket/package_test.go
  internal/worker/controlsocket/services_mock_test.go
  internal/worker/controlsocket/shim.go
  internal/worker/controlsocket/worker.go
  internal/worker/controlsocket/worker_test.go
  internal/worker/httpserverargs/authenticator.go
  internal/worker/httpserverargs/services_mock_test.go
  internal/worker/httpserverargs/worker.go
Labels: 4.0

#17066 Merge 2.9 into 3.1
  make_functions.sh
  tests/suites/relations/relation_list_app.sh
Labels: 3.1

#17071 On model upgrades, only search for agents if different to controller
  apiserver/facades/client/modelupgrader/upgrader.go
  apiserver/facades/client/modelupgrader/upgrader_test.go
Labels: 3.3

#16956 Introduce jaas-plugin plug
  snap/snapcraft.yaml
Labels: 3.5

#17057 model manager facade service
  agent/agentbootstrap/bootstrap.go
  apiserver/facade/facadetest/modelcontext.go
  apiserver/facade/interface.go
  apiserver/facades/client/modelmanager/listmodelsummaries_test.go
  apiserver/facades/client/modelmanager/modelinfo_test.go
  apiserver/facades/client/modelmanager/modelmanager.go
  apiserver/facades/client/modelmanager/modelmanager_test.go
  apiserver/facades/client/modelmanager/register.go
  apiserver/facades/controller/migrationtarget/servicefactory_mock_test.go
  apiserver/root.go
  domain/cloud/state/state_test.go
  domain/model/bootstrap/bootstrap.go
  domain/model/bootstrap/bootstrap_test.go
  domain/model/modelmigration/import.go
  domain/model/modelmigration/import_test.go
  domain/model/service/service.go
  domain/model/service/service_test.go
  domain/model/state/state.go
  domain/model/state/state_test.go
  domain/model/state/testing/model.go
  domain/model/types.go
  domain/model/types_test.go
  domain/modelconfig/service/service.go
  domain/modelconfig/service/service_test.go
  domain/modeldefaults/types.go
  domain/modeldefaults/types_test.go
  domain/modelmanager/service/deleter_mock_test.go
  domain/modelmanager/service/package_test.go
  domain/modelmanager/service/service.go
  domain/modelmanager/service/service_test.go
  domain/modelmanager/service/state_mock_test.go
  domain/modelmanager/state/package_test.go
  domain/modelmanager/state/state.go
  domain/modelmanager/state/state_test.go
  domain/schema/controller.go
  domain/schema/schema_test.go
  domain/secretbackend/state/state.go
  domain/secretbackend/state/state_test.go
  domain/servicefactory/controller.go
  domain/servicefactory/testing/service.go
  domain/servicefactory/testing/suite.go
  internal/migration/servicefactory_mock_test.go
  internal/servicefactory/interface.go
  internal/worker/servicefactory/servicefactory_mock_test.go
  internal/worker/upgradedatabase/servicefactory_mock_test.go
Labels: 4.0

#17070 Wire through rootless charm/workloads for k8s.
  api/common/charms/common.go
  api/common/charms/common_test.go
  apiserver/common/charms/appcharminfo_test.go
  apiserver/common/charms/common.go
  apiserver/common/charms/package_test.go
  apiserver/facades/schema.json
  caas/Dockerfile
  caas/application.go
  caas/kubernetes/provider/application/application.go
  caas/kubernetes/provider/application/application_test.go
  caas/kubernetes/provider/bootstrap.go
  caas/kubernetes/provider/constants/constants.go
  rpc/params/charms.go
  worker/caasapplicationprovisioner/ops.go
  worker/caasapplicationprovisioner/ops_test.go
Labels: 3.5

#17067 Add user permissions creating user
  agent/agentbootstrap/bootstrap.go
  apiserver/admin_test.go
  apiserver/auditconfig_test.go
  apiserver/authentication/agent_test.go
  apiserver/authentication/user_test.go
  apiserver/charms_test.go
  apiserver/facades/client/client/api_test.go
  apiserver/facades/client/client/client_test.go
  apiserver/facades/client/usermanager/usermanager.go
  apiserver/facades/client/usermanager/usermanager_test.go
  apiserver/introspection_test.go
  apiserver/objects_test.go
  apiserver/pubsub_test.go
  apiserver/ratelimit_test.go
  apiserver/registration_test.go
  apiserver/tools_integration_test.go
  apiserver/tools_test.go
  core/permission/access.go
  core/permission/user.go
  core/permission/user_test.go
  domain/cloud/state/state_test.go
  domain/credential/bootstrap/bootstrap_test.go
  domain/credential/state/state_test.go
  domain/model/bootstrap/bootstrap_test.go
  domain/model/state/state_test.go
  domain/model/state/testing/model.go
  domain/permission/errors/errors.go
  domain/permission/service/service.go
  domain/permission/service/service_test.go
  domain/permission/service/state_mock_test.go
  domain/permission/state/state.go
  domain/permission/state/state_test.go
  domain/permission/state/types.go
  domain/permission/types.go
  domain/secretbackend/state/state_test.go
  domain/servicefactory/testing/suite.go
  domain/user/bootstrap/bootstrap.go
  domain/user/bootstrap/bootstrap_test.go
  domain/user/errors/errors.go
  domain/user/service/service.go
  domain/user/service/service_test.go
  domain/user/service/state_mock_test.go
  domain/user/service/types.go
  domain/user/state/state.go
  domain/user/state/state_test.go
  internal/worker/bootstrap/worker.go
Labels: 4.0

#17061 [JUJU-5694] Fix regression with deploy
  apiserver/facades/client/application/application.go
  apiserver/facades/client/charms/client.go
  apiserver/facades/client/charms/client_test.go
Labels: 2.9

#17068 Pass controller and model txn runners in bootstrap
  agent/agentbootstrap/bootstrap.go
  agent/agentbootstrap/bootstrap_test.go
  apiserver/facades/agent/caasapplication/application_test.go
  cmd/jujud-controller/agent/agenttest/agent.go
  cmd/jujud-controller/agent/bootstrap_test.go
  cmd/jujud/agent/agenttest/agent.go
  domain/cloud/bootstrap/bootstrap.go
  domain/cloud/bootstrap/bootstrap_test.go
  domain/controllerconfig/bootstrap/bootstrap.go
  domain/controllerconfig/bootstrap/bootstrap_test.go
  domain/controllerconfig/controllerconfig_test.go
  domain/credential/bootstrap/bootstrap.go
  domain/credential/bootstrap/bootstrap_test.go
  domain/machine/bootstrap/bootstrap.go
  domain/machine/bootstrap/bootstrap_test.go
  domain/model/bootstrap/bootstrap.go
  domain/model/bootstrap/bootstrap_test.go
  domain/modelconfig/bootstrap/bootstrap.go
  domain/modelconfig/bootstrap/bootstrap_test.go
  domain/servicefactory/testing/suite.go
  domain/testing/controllerconfigsuite.go
  domain/user/bootstrap/bootstrap.go
  domain/user/bootstrap/bootstrap_test.go
  internal/database/bootstrap.go
  internal/database/bootstrap_test.go
  internal/database/testing/dqlitesuite.go
  juju/testing/apiserver.go
Labels: 4.0

#17062 Add new facades version for remote space removal
  api/client/application/client.go
  api/client/application/client_test.go
  api/client/applicationoffers/client.go
  api/client/applicationoffers/client_test.go
  api/facadeversions.go
  apiserver/admin_test.go
  apiserver/common/crossmodel/auth.go
  apiserver/common/crossmodel/auth_test.go
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/application_test.go
  apiserver/facades/client/application/application_unit_test.go
  apiserver/facades/client/application/register.go
  apiserver/facades/client/applicationoffers/access_test.go
  apiserver/facades/client/applicationoffers/applicationoffers.go
  apiserver/facades/client/applicationoffers/applicationoffers_test.go
  apiserver/facades/client/applicationoffers/base.go
  apiserver/facades/client/applicationoffers/conversions.go
  apiserver/facades/client/applicationoffers/register.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations_test.go
  apiserver/facades/controller/crossmodelrelations/register.go
  apiserver/facades/schema.json
  cmd/juju/application/consume_test.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/integrateremote_test.go
  core/crossmodel/interface.go
  rpc/params/crossmodel.go
Labels: 3.5

#17065 Swap db-accessor cluster configuration source
  cmd/jujud-controller/agent/machine/manifolds.go
  cmd/jujud-controller/agent/safemode/manifolds.go
  internal/worker/dbaccessor/manifold.go
  internal/worker/dbaccessor/manifold_test.go
  internal/worker/dbaccessor/package_mock_test.go
  internal/worker/dbaccessor/package_test.go
  internal/worker/dbaccessor/worker.go
  internal/worker/dbaccessor/worker_integration_test.go
  internal/worker/dbaccessor/worker_namespace_test.go
  internal/worker/dbaccessor/worker_test.go
Labels: 4.0

#17087 Fix refresh bash tests to look for correct charm channel
  tests/suites/refresh/refresh.sh
  tests/suites/refresh/switch.sh
Labels: 3.3

#17086 Merge 3.5 to main
  api/common/package_test.go
  apiserver/facades/agent/provisioner/provisioner.go
  apiserver/facades/agent/provisioner/provisioner_test.go
  apiserver/facades/agent/secretsmanager/secrets.go
  apiserver/facades/agent/secretsmanager/secrets_test.go
  caas/kubernetes/provider/bootstrap.go
  cmd/juju/application/config.go
  cmd/juju/application/config_test.go
  cmd/jujud-controller/agent/util_test.go
  cmd/jujud/agent/util_test.go
  core/network/discovery.go
  core/network/discovery_mock_test.go
  core/network/discovery_test.go
  core/network/package_test.go
  core/secrets/createsecret.go
  core/secrets/createsecret_test.go
  environs/bootstrap/config.go
  environs/config/config.go
  environs/config/config_test.go
  environs/imagemetadata.go
  environs/imagemetadata_test.go
  internal/charm/repository/charmhub.go
  internal/charm/repository/charmhub_test.go
  internal/charm/repository/sanitiser.go
  internal/charm/repository/sanitiser_test.go
  internal/cloudconfig/userdatacfg_unix.go
  internal/container/broker/instance_broker.go
  internal/container/lxd/manager.go
  internal/container/lxd/manager_test.go
  internal/upgrades/upgrade.go
  internal/worker/containerbroker/broker.go
  internal/worker/containerbroker/broker_test.go
  internal/worker/machiner/machiner.go
  internal/worker/machiner/machiner_test.go
  internal/worker/provisioner/container_initialisation.go
  internal/worker/provisioner/container_initialisation_test.go
  internal/worker/provisioner/containermanifold.go
  internal/worker/provisioner/containerworker_test.go
  internal/worker/provisioner/provisioner_test.go
  scripts/generate-password/main.go
  scripts/removejujuservices.bash
  scripts/sanitise-db.py
  state/applicationoffers.go
  state/applicationoffers_test.go
  state/migration_import.go
  state/upgrades.go
Labels: 4.0

#17056 Remove remote spaces
  api/facadeversions.go
  apiserver/admin_test.go
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/backend.go
  apiserver/facades/client/application/mocks/application_mock.go
  apiserver/facades/client/applicationoffers/applicationoffers.go
  apiserver/facades/client/applicationoffers/base.go
  apiserver/facades/client/applicationoffers/register.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations.go
  apiserver/facades/controller/crossmodelrelations/register.go
  apiserver/restrict_anonymous_test.go
  apiserver/restrict_controller_test.go
  rpc/params/crossmodel.go
  state/migration_export.go
  state/migration_export_test.go
  state/migration_import.go
  state/migration_import_tasks_test.go
  state/migration_import_test.go
  state/migrations/remoteapplications.go
  state/migrations/remoteapplications_mock_test.go
  state/migrations/remoteapplications_test.go
  state/remoteapplication.go
  state/remoteapplication_test.go
Labels: 4.0

#17009 Add Prepare method to StateBase to allow for SQLair statement reuse.
  domain/annotation/state/state.go
  domain/application/state/state.go
  domain/autocert/state/state.go
  domain/blockdevice/state/state.go
  domain/cloud/state/state.go
  domain/credential/state/state.go
  domain/externalcontroller/state/state.go
  domain/machine/state/state.go
  domain/modelconfig/state/state.go
  domain/network/state/space.go
  domain/network/state/subnet.go
  domain/permission/state/state.go
  domain/secretbackend/state/state.go
  domain/state.go
  domain/state_test.go
  domain/storage/state/storagepool.go
  domain/unit/state/state.go
  domain/upgrade/state/state.go
  domain/upgrade/state/state_test.go
  domain/user/state/state.go
  go.mod
  go.sum
  internal/worker/changestreampruner/worker.go
Labels: has merge conflicts, 4.0

#17090 Wire up PEBBLE_COPY_ONCE for workload containers.
  caas/kubernetes/provider/application/application.go
  caas/kubernetes/provider/application/application_test.go
  go.mod
  go.sum
Labels: 3.5

#17092 Adds wait-for login to check EC2 SG changes in CI test
  tests/includes/wait-for.sh
  tests/suites/firewall/expose_app.sh
Labels: 3.3

#16985 Remove (almost) all charm url series reads and writes
  api/client/charms/export_test.go
  api/client/charms/localcharmclient.go
  api/client/charms/localcharmclient_test.go
  api/client/charms/localcharmputters.go
  api/client/charms/localcharmputters_test.go
  apiserver/facades/client/charms/client_integration_test.go
  cmd/juju/application/bundle_test.go
  cmd/juju/application/deploy.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/bundle.go
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/bundlehandler_test.go
  cmd/juju/application/deployer/deployer.go
  cmd/juju/application/deployer/deployer_test.go
  cmd/juju/application/deployer/interface.go
  cmd/juju/application/deployer/mocks/deploy_mock.go
  cmd/juju/application/refresh_test.go
  cmd/juju/application/refresher/interface.go
  cmd/juju/application/refresher/refresher.go
  cmd/juju/application/refresher/refresher_mock_test.go
  cmd/juju/application/refresher/refresher_test.go
  core/charm/charmpath.go
  core/charm/charmpath_test.go
  core/charm/computedbase.go
  internal/charm/repository/charmhub.go
  internal/charm/repository/charmhub_test.go
  testcharms/charm-repo/focal/mysql/actions.yaml
  testcharms/charm-repo/focal/mysql/config.yaml
  testcharms/charm-repo/focal/mysql/hooks/config-changed
  testcharms/charm-repo/focal/mysql/hooks/hooks
  testcharms/charm-repo/focal/mysql/hooks/install
  testcharms/charm-repo/focal/mysql/hooks/update-status
  testcharms/charm-repo/focal/mysql/icon.svg
  testcharms/charm-repo/focal/mysql/manifest.yaml
  testcharms/charm-repo/focal/mysql/metadata.yaml
  testcharms/charm-repo/focal/mysql/revision
Labels: 4.0

#17099 Preliminary work to wire to user secret facade to the secret service
  api/package_test.go
  apiserver/errors/errors.go
  apiserver/errors/errors_test.go
  apiserver/facades/client/secrets/mocks/secretsstate.go
  apiserver/facades/client/secrets/package_test.go
  apiserver/facades/client/secrets/register.go
  apiserver/facades/client/secrets/secrets.go
  apiserver/facades/client/secrets/secrets_test.go
  apiserver/facades/client/secrets/service.go
  apiserver/facades/client/secrets/state.go
  apiserver/facades/controller/migrationtarget/servicefactory_mock_test.go
  cmd/containeragent/initialize/package_test.go
  core/permission/access.go
  domain/secret/errors/errors.go
  domain/secret/service/access.go
  domain/secret/service/consume.go
  domain/secret/service/delete.go
  domain/secret/service/params.go
  domain/secret/service/service.go
  domain/secret/service/watcher.go
  domain/secret/types.go
  domain/servicefactory/model.go
  domain/servicefactory/testing/service.go
  internal/migration/servicefactory_mock_test.go
  internal/servicefactory/interface.go
  internal/worker/servicefactory/servicefactory_mock_test.go
  rpc/params/apierror.go
Labels: 4.0

#17076 Secretbackend state fix
  domain/model/state/modelstate_test.go
  domain/schema/controller.go
  domain/schema/model.go
  domain/schema/schema_test.go
  domain/schema/secret.go
  domain/schema/triggers.go
  domain/secretbackend/errors/errors.go
  domain/secretbackend/params.go
  domain/secretbackend/params_test.go
  domain/secretbackend/state/operation.go
  domain/secretbackend/state/operation_test.go
  domain/secretbackend/state/state.go
  domain/secretbackend/state/state_test.go
  domain/secretbackend/state/types.go
  domain/secretbackend/state/types_test.go
  domain/secretbackend/state/upserts.go
  domain/secretbackend/types.go
  internal/database/types.go
  internal/database/types_test.go
Labels: 4.0

#17109 Merge 3.4 3.5 20240326
  api/controller/crossmodelrelations/crossmodelrelations.go
  api/controller/crossmodelrelations/crossmodelrelations_test.go
  apiserver/facades/client/application/deployrepository.go
  apiserver/facades/client/application/deployrepository_test.go
  apiserver/facades/client/bundle/bundle.go
  apiserver/facades/client/bundle/bundle_test.go
  apiserver/facades/client/keymanager/keymanager.go
  apiserver/facades/client/keymanager/keymanager_test.go
  apiserver/facades/client/modelupgrader/upgrader.go
  apiserver/facades/client/modelupgrader/upgrader_test.go
  cmd/juju/commands/remove_sshkeys.go
  go.mod
  go.sum
  state/migration_export.go
  state/migration_export_test.go
  state/migration_import.go
  state/migration_import_test.go
  state/mocks/description_mock.go
  tests/includes/wait-for.sh
  tests/suites/deploy/bundles/telegraf_bundle.yaml
  tests/suites/deploy/bundles/telegraf_bundle_with_fake_revisions.yaml
  tests/suites/deploy/bundles/telegraf_bundle_without_revisions.yaml
  tests/suites/firewall/expose_app.sh
  tests/suites/refresh/refresh.sh
  tests/suites/refresh/switch.sh
  tests/suites/secrets_k8s/k8s.sh
  worker/remoterelations/remoteapplicationworker.go
  worker/remoterelations/remoterelations_test.go
  worker/uniter/actions/resolver.go
  worker/uniter/remotestate/watcher.go
  worker/uniter/resolver.go
Labels: 3.5

#17069 4 of 5 read methods for permission state.
  domain/permission/errors/errors.go
  domain/permission/state/state.go
  domain/permission/state/state_test.go
  domain/permission/state/types.go
Labels: feature, 4.0

#17108 Remove check for validating controller config spaces
  state/controller.go
Labels: 4.0

#17107 Remove space retrieval on the allwatcher
  state/address.go
  state/allwatcher.go
  state/allwatcher_internal_test.go
Labels: 4.0

#17115 Remove mux dead code from the model worker manager
  cmd/jujud-controller/agent/machine.go
  cmd/jujud-controller/agent/machine/manifolds.go
  cmd/jujud-controller/agent/machine/manifolds_test.go
  cmd/jujud-controller/agent/model/manifolds.go
  internal/worker/modelworkermanager/manifold.go
  internal/worker/modelworkermanager/manifold_test.go
  internal/worker/modelworkermanager/modelworkermanager.go
Labels: 4.0

#17079 [JUJU-5718] Fix a regression when deploying with certain clients
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/application_test.go
  apiserver/facades/client/application/application_unit_test.go
  apiserver/facades/client/application/export_test.go
  apiserver/facades/client/charms/client.go
  apiserver/facades/client/charms/client_test.go
  apiserver/facades/client/charms/export_test.go
Labels: 2.9

#17119 Remove checks on spaces bound to endpoints when deleting spaces
  apiserver/common/modelmanagerinterface.go
  apiserver/facades/client/modelmanager/modelinfo_test.go
  apiserver/facades/client/spaces/package_mock_test.go
  apiserver/testing/stub_network.go
  environs/space/spaces.go
  environs/space/spaces_mock_test.go
  environs/space/spaces_test.go
  state/model.go
  state/model_test.go
Labels: 4.0

#17103 Back enable ha with microceph
  tests/includes/microceph.sh
  tests/suites/controller/enable_ha.sh
Labels: 4.0

#17106 Remove curl series read from test factory
  state/application_test.go
  testing/factory/factory.go
Labels: 4.0

#17130 Add missing methods UpdateSpace and GetAllSubnets to network domain service
  domain/network/service/space.go
  domain/network/service/space_test.go
  domain/network/service/subnet.go
  domain/network/service/subnet_test.go
Labels: 4.0
