Repository juju/juju, pull requests merged in 2024-08, with the labels that each got.

#17835 feat(schema): construct port range schema
  domain/schema/model/sql/0022-port-ranges.sql
  domain/schema/schema_test.go
Labels: 4.0

#17419 refactor(facade): use model config service in provisioner facade
  apiserver/common/modelmanagerinterface.go
  apiserver/common/modelwatcher.go
  apiserver/common/package_test.go
  apiserver/common/service_mock_test.go
  apiserver/common/tools.go
  apiserver/common/tools_test.go
  apiserver/facades/agent/provisioner/imagemetadata_test.go
  apiserver/facades/agent/provisioner/provisioner.go
  apiserver/facades/agent/provisioner/provisioner_test.go
  apiserver/facades/agent/provisioner/provisioninginfo.go
  apiserver/facades/agent/provisioner/service.go
  apiserver/facades/agent/unitassigner/unitassigner.go
  apiserver/facades/agent/upgrader/register.go
  apiserver/facades/agent/upgrader/service.go
  apiserver/facades/agent/upgrader/upgrader.go
  apiserver/facades/agent/upgrader/upgrader_test.go
  apiserver/facades/client/client/client.go
  apiserver/facades/client/machinemanager/instanceconfig.go
  apiserver/facades/client/machinemanager/machinemanager.go
  apiserver/facades/client/modelmanager/modelmanager_test.go
  apiserver/facades/client/modelmanager/register.go
  apiserver/facades/client/modelupgrader/register.go
  cmd/jujud-controller/agent/machine_test.go
  domain/modelagent/state/state.go
  environs/config/config.go
Labels: do not merge, 4.0

#17852 fix: unset the bootstrap additional args after bootstrap
  tests/includes/juju.sh
  tests/suites/controllercharm/prometheus.sh
Labels: 3.6

#17847 feat(application): Resource DDL schema
  domain/schema/model/sql/0022-resource.sql
  domain/schema/schema_test.go
Labels: 4.0

#17854 Fix machine migrations
  apiserver/facades/agent/machine/machiner.go
  apiserver/facades/client/controller/controller.go
  domain/blockdevice/modelmigration/export.go
  domain/machine/modelmigration/export.go
  domain/machine/modelmigration/export_test.go
  domain/machine/modelmigration/import_test.go
  domain/machine/modelmigration/migrations_mock_test.go
  domain/machine/modelmigration/package_test.go
  domain/modelmigration/export.go
Labels: 4.0

#17863 fix: ignore not implemented error
  worker/upgradeseries/worker.go
Labels: 4.0

#17844 fix: set param LastConnection to nil if IsZero
  apiserver/facades/client/usermanager/usermanager.go
  apiserver/facades/client/usermanager/usermanager_test.go
Labels: 4.0

#17864 feat: update description package
  go.mod
  go.sum
  state/mocks/description_mock.go
Labels: 4.0

#17849 chore(secrets): add unit tests and fix state method
  domain/secret/service/access_test.go
  domain/secret/service/consume.go
  domain/secret/service/delete.go
  domain/secret/service/delete_test.go
  domain/secret/service/service.go
  domain/secret/service/service_test.go
  domain/secret/service/state_mock_test.go
  domain/secret/state/state.go
  domain/secret/state/state_test.go
Labels: 4.0

#17855 feat: pass model uuid through the context
  apiserver/apiserver.go
  core/model/context.go
  core/model/context_test.go
Labels: 4.0

#17769 feat: add `facadecheck` script
  doc/architectural-overview.md
  scripts/facadecheck/main.go
Labels: 3.5

#17861 feat(model): move model summaries to model domain
  apiserver/common/modeluser.go
  apiserver/facades/client/modelmanager/listmodelsummaries_test.go
  apiserver/facades/client/modelmanager/mocks/service_mock.go
  apiserver/facades/client/modelmanager/modelmanager.go
  apiserver/facades/client/modelmanager/services.go
  core/credential/credential.go
  core/model/modelsummary.go
  domain/model/service/service.go
  domain/model/service/service_test.go
  domain/model/service/state_test.go
  domain/model/state/state.go
  domain/model/state/state_test.go
  domain/model/state/types.go
Labels: 4.0

#17836 feat: update dqlite build script
  Makefile
  scripts/dqlite/scripts/dqlite/dqlite-build.sh
  scripts/dqlite/scripts/env.sh
  snap/snapcraft.yaml
Labels: 3.6

#17889 fix: remove debug flag
  snap/snapcraft.yaml
Labels: 3.6

#17866 docs: add better migration steps
  PULL_REQUEST_TEMPLATE.md
Labels: 4.0

#17885 feat(units): make progress on dual wrting units
  apiserver/facades/agent/caasapplication/application.go
  apiserver/facades/agent/caasapplication/application_test.go
  apiserver/facades/client/application/application_unit_test.go
  apiserver/facades/client/application/deploy.go
  apiserver/facades/client/application/deployrepository.go
  apiserver/facades/client/application/deployrepository_test.go
  apiserver/facades/client/application/get_test.go
  apiserver/facades/client/application/service.go
  apiserver/facades/client/application/service_mock_test.go
  apiserver/facades/client/charms/client.go
  core/charm/origin.go
  domain/application/errors/errors.go
  domain/application/modelmigration/import.go
  domain/application/modelmigration/import_test.go
  domain/application/modelmigration/migrations_mock_test.go
  domain/application/platform.go
  domain/application/platform_test.go
  domain/application/service/application.go
  domain/application/service/application_test.go
  domain/application/service/package_mock_test.go
  domain/application/service/params.go
  domain/application/state/application.go
  domain/application/state/application_test.go
  domain/application/state/types.go
  domain/application/types.go
  domain/schema/model/sql/0017-machine.sql
  domain/schema/model/sql/0018-application.sql
  domain/schema/model/sql/0019-unit.sql
  domain/schema/schema_test.go
  domain/secret/watcher_test.go
  internal/bootstrap/bootstrap_mock_test.go
  internal/bootstrap/deployer.go
  internal/bootstrap/deployer_test.go
  internal/bootstrap/service.go
  internal/testing/factory/factory.go
  internal/worker/bootstrap/bootstrap_mock_test.go
  internal/worker/bootstrap/service.go
  state/migration_import.go
Labels: 4.0

#17845 feat: export charm actions, config and lxd profile
  go.mod
  go.sum
  state/migration_export.go
  state/migration_export_test.go
  state/mocks/description_mock.go
Labels: 3.6

#17883 chore: merge 3.6 into main
  api/api_mock_test.go
  api/apiclient.go
  api/apiclient_test.go
  api/clientcredentialsloginprovider.go
  api/clientcredentialsloginprovider_test.go
  api/connection.go
  api/httpclient.go
  api/interface.go
  api/legacyloginprovider.go
  api/legacyloginprovider_test.go
  api/sessiontokenloginprovider.go
  api/sessiontokenloginprovider_test.go
  cmd/internal/loginprovider/tryinorderloginprovider.go
  cmd/internal/loginprovider/tryinorderloginprovider_test.go
  cmd/juju/commands/bootstrap.go
  cmd/juju/controller/config.go
  cmd/juju/controller/register.go
  cmd/juju/model/config.go
  cmd/juju/user/login.go
  go.mod
  go.sum
  internal/provider/azure/clients.go
  internal/provider/azure/environ.go
  internal/provider/azure/environ_test.go
  tests/includes/juju.sh
  tests/suites/controllercharm/prometheus.sh
Labels: 4.0

#17512 feat: add --resources arg to juju download
  cmd/juju/charmhub/download.go
  cmd/juju/charmhub/download_test.go
  testcharms/charm-hub/charms/juju-qa-test-resources/charmcraft.yaml
  testcharms/charm-hub/charms/juju-qa-test-resources/requirements.txt
  testcharms/charm-hub/charms/juju-qa-test-resources/resource/Makefile
  testcharms/charm-hub/charms/juju-qa-test-resources/resource/main.go
  testcharms/charm-hub/charms/juju-qa-test-resources/src/charm.py
  tests/suites/charmhub/download.sh
  tests/suites/charmhub/find.sh
  tests/suites/charmhub/info.sh
  tests/suites/charmhub/task.sh
Labels: 3.6

#17900 fix: use ed25519 ssh keys when juju sshing
  go.mod
  go.sum
Labels: 3.5

#17895 fix(test): intermittent failure in serviceSuite.TestListAllModelSummaries
  domain/model/service/service_test.go
Labels: 4.0

#17890 Remove fan config from model config
  api/agent/fanconfigurer/facade.go
  api/facadeversions.go
  apiserver/allfacades.go
  apiserver/facades/agent/fanconfigurer/fanconfigurer.go
  apiserver/facades/agent/fanconfigurer/fanconfigurer_test.go
  apiserver/facades/agent/fanconfigurer/package_test.go
  apiserver/facades/agent/fanconfigurer/register.go
  apiserver/facades/schema.json
  core/network/fan.go
  core/network/fan_test.go
  environs/config/config.go
  environs/config/schema.go
  environs/config/validator_test.go
  internal/migration/precheck.go
  rpc/params/network.go
Labels: 4.0

#17875 fix: setuping mocks inside deployer suite SetUpTest
  apiserver/facades/agent/deployer/deployer_test.go
Labels: 4.0

#17887 feat(application): resource service layer
  core/migration/package_test.go
  core/resources/id.go
  core/resources/id_test.go
  core/resources/resource.go
  core/resources/testing/resource.go
  core/unit/id.go
  core/unit/id_test.go
  core/unit/package_test.go
  core/unit/testing/testing.go
  core/watcher/eventsource/package_test.go
  core/watcher/package_test.go
  domain/application/doc.go
  domain/application/errors/errors.go
  domain/application/resource/doc.go
  domain/application/resource/types.go
  domain/application/service/package_mock_test.go
  domain/application/service/package_test.go
  domain/application/service/resource.go
  domain/application/service/resource_test.go
  domain/application/state/application.go
Labels: 4.0

#17891 feat: prevent agent bouncing
  api/agent/fanconfigurer/facade.go
  worker/fanconfigurer/fanconfigurer.go
  worker/fanconfigurer/fanconfigurer_test.go
  worker/fanconfigurer/package_mock_test.go
  worker/fanconfigurer/package_test.go
Labels: 3.6

#17901 chore: merge 2.9 into 3.1
  .github/workflows/static-analysis.yml
  .github/workflows/upgrade.yml
  acceptancetests/jujupy/client.py
  acceptancetests/jujupy/tests/test_status.py
  acceptancetests/repository/trusty/haproxy/cm.py
  acceptancetests/tests/test_jujucharm.py
  apiserver/common/tools_test.go
  go.mod
  go.sum
  provider/azure/internal/errorutils/errors_test.go
  scripts/find-bad-doc-comments.py
  scripts/leadershipclaimer/count-leadership.py
  tests/README.md
  tests/suites/static_analysis/lint_go.sh
  worker/uniter/runner/runner.go
  worker/uniter/runner/runner_test.go
  worker/uniter/util_test.go
Labels: 3.1

#17684 fix(destroy): improve prompting on model destroy with storage
  cmd/juju/model/destroy.go
  cmd/juju/model/destroy_test.go
Labels: 3.6

#17903 chore: merge 3.1 into 3.4
  .github/workflows/static-analysis.yml
  .github/workflows/upgrade.yml
  apiserver/common/tools_test.go
  go.mod
  go.sum
  provider/azure/internal/errorutils/errors_test.go
  tests/README.md
  tests/suites/static_analysis/lint_go.sh
  worker/uniter/runner/runner.go
  worker/uniter/runner/runner_test.go
  worker/uniter/util_test.go
Labels: 3.4
