Repository juju/juju, pull requests merged in 2024-07, with the labels that each got.

#17601 fix(docs): handle schema.NonEmptyString in controller config keys doc generation
  scripts/md-gen/controller-config/main.go
Labels: 3.5

#17600 chore: merge 3.5 into 3.6
  .github/workflows/docs.yml
  .github/workflows/static-analysis.yml
  CONTRIBUTING.md
  api/clientcredentialsloginprovider.go
  api/clientcredentialsloginprovider_test.go
  api/export_test.go
  api/interface.go
  api/userpass_login_provider.go
  apiserver/facades/client/controller/controller.go
  cmd/internal/loginprovider/export_test.go
  cmd/internal/loginprovider/package_test.go
  cmd/internal/loginprovider/sessiontokenloginprovider.go
  cmd/internal/loginprovider/sessiontokenloginprovider_test.go
  cmd/internal/loginprovider/tryinorderloginprovider.go
  cmd/internal/loginprovider/tryinorderloginprovider_test.go
  cmd/juju/commands/bootstrap.go
  cmd/juju/commands/bootstrap_test.go
  cmd/juju/commands/migrate.go
  cmd/juju/controller/register.go
  cmd/juju/storage/add.go
  cmd/juju/user/login.go
  cmd/modelcmd/base.go
  controller/config.go
  controller/config_test.go
  controller/configschema.go
  core/status/caas.go
  core/status/caas_test.go
  scripts/md-gen/controller-config/main.go
  scripts/md-gen/version-notice/main.go
  snap/snapcraft.yaml
  state/allcollections.go
  storage/constraints.go
  storage/constraints_test.go
  tests/suites/deploy/bundles/basic-openstack.yaml
  tests/suites/deploy/deploy_bundles.sh
  worker/auditconfigupdater/manifold.go
  worker/certupdater/manifold.go
  worker/controlsocket/manifold.go
  worker/httpserver/manifold.go
  worker/migrationmaster/worker.go
  worker/migrationmaster/worker_test.go
  worker/peergrouper/manifold.go
Labels: 3.6

#17613 chore: merge 3.6 into main
  .github/workflows/docs.yml
  .github/workflows/static-analysis.yml
  CONTRIBUTING.md
  api/agent/uniter/unit.go
  api/agent/uniter/unit_test.go
  api/agent/uniter/uniter.go
  api/agent/uniter/uniter_test.go
  api/apiclient.go
  api/apiclient_test.go
  api/clientcredentialsloginprovider.go
  api/clientcredentialsloginprovider_test.go
  api/common/unitstate.go
  api/common/upgradeseries.go
  api/common/watch.go
  api/export_test.go
  api/interface.go
  api/userpass_login_provider.go
  apiserver/facades/client/controller/controller.go
  cmd/internal/loginprovider/export_test.go
  cmd/internal/loginprovider/package_test.go
  cmd/internal/loginprovider/sessiontokenloginprovider.go
  cmd/internal/loginprovider/sessiontokenloginprovider_test.go
  cmd/internal/loginprovider/tryinorderloginprovider.go
  cmd/internal/loginprovider/tryinorderloginprovider_test.go
  cmd/juju/commands/bootstrap.go
  cmd/juju/commands/bootstrap_test.go
  cmd/juju/commands/migrate.go
  cmd/juju/controller/register.go
  cmd/juju/storage/add.go
  cmd/juju/user/login.go
  cmd/modelcmd/base.go
  controller/config.go
  controller/config_test.go
  controller/configschema.go
  core/status/caas.go
  core/status/caas_test.go
  go.mod
  internal/storage/directive.go
  internal/storage/directive_test.go
  internal/worker/auditconfigupdater/manifold.go
  internal/worker/certupdater/manifold.go
  internal/worker/migrationmaster/worker.go
  internal/worker/migrationmaster/worker_test.go
  internal/worker/peergrouper/manifold.go
  scripts/md-gen/controller-config/main.go
  scripts/md-gen/version-notice/main.go
  snap/snapcraft.yaml
  state/allcollections.go
  tests/suites/deploy/deploy_bundles.sh
Labels: 4.0

#17585 refactor(network): refactor large SELECTs into table views and use SQLair
  domain/network/state/space.go
  domain/network/state/subnet.go
  domain/network/state/types.go
  domain/schema/model/sql/0008-space.sql
  domain/schema/schema_test.go
Labels: 4.0

#17292 feat: use domain when checking login credentials
  apiserver/admin.go
  apiserver/admin_test.go
  apiserver/apiserver.go
  apiserver/auditconfig_test.go
  apiserver/authentication/http.go
  apiserver/authentication/interfaces.go
  apiserver/common/permissions.go
  apiserver/common/permissions_test.go
  apiserver/errors/http.go
  apiserver/errors/types.go
  apiserver/export_test.go
  apiserver/facades/client/client/api_test.go
  apiserver/facades/client/usermanager/domain_mock_test.go
  apiserver/facades/client/usermanager/package_test.go
  apiserver/facades/client/usermanager/register.go
  apiserver/facades/client/usermanager/usermanager.go
  apiserver/facades/client/usermanager/usermanager_test.go
  apiserver/httpcontext.go
  apiserver/httpcontext/auth.go
  apiserver/introspection.go
  apiserver/introspection_test.go
  apiserver/macaroon_test.go
  apiserver/ratelimit_test.go
  apiserver/root.go
  apiserver/server_test.go
  apiserver/stateauthenticator/auth.go
  apiserver/stateauthenticator/context.go
  apiserver/stateauthenticator/delegator.go
  apiserver/stateauthenticator/services_mock_test.go
  apiserver/tools_integration_test.go
  core/permission/access.go
  domain/access/bootstrap/bootstrap.go
  domain/access/service/user.go
  domain/access/validation.go
  domain/access/validation_test.go
  internal/worker/httpserverargs/authenticator.go
  internal/worker/httpserverargs/services_mock_test.go
  internal/worker/httpserverargs/worker.go
  juju/testing/macaroonsuite.go
  rpc/params/params.go
Labels: 4.0

#17598 feat(domain): add modelagent service
  apiserver/facades/controller/migrationtarget/servicefactory_mock_test.go
  domain/credential/state/state_test.go
  domain/modelagent/doc.go
  domain/modelagent/service/package_test.go
  domain/modelagent/service/service.go
  domain/modelagent/service/service_mock_test.go
  domain/modelagent/service/service_test.go
  domain/modelagent/state/package_test.go
  domain/modelagent/state/state.go
  domain/modelagent/state/state_test.go
  domain/modelagent/state/types.go
  domain/schema/controller/sql/0007-model.sql
  domain/servicefactory/model.go
  domain/servicefactory/testing/service.go
  internal/migration/servicefactory_mock_test.go
  internal/servicefactory/interface.go
  internal/worker/servicefactory/servicefactory_mock_test.go
Labels: 4.0

#17607 feat: charm domain service - set charm
  domain/charm/errors/errors.go
  domain/charm/service/actions.go
  domain/charm/service/actions_test.go
  domain/charm/service/charm.go
  domain/charm/service/config.go
  domain/charm/service/config_test.go
  domain/charm/service/lxdprofile.go
  domain/charm/service/lxdprofile_test.go
  domain/charm/service/manifest.go
  domain/charm/service/manifest_test.go
  domain/charm/service/metadata.go
  domain/charm/service/metadata_test.go
  domain/charm/service/package_mock_test.go
  domain/charm/service/service.go
  domain/charm/types.go
Labels: 4.0

#17631 fix: data race in rpc layer
  rpc/client.go
Labels: 4.0

#17630 feat(machine): add machine cloud instance service layer
  domain/machine/service/machine_cloud_instance.go
  domain/machine/service/machine_cloud_instance_test.go
  domain/machine/service/package_mock_test.go
  domain/machine/service/service.go
Labels: 4.0

#17583 feat(dqlite): add AllMachines, InstanceId and InstanceStatus in machine domain
  apiserver/facades/agent/unitassigner/unitassigner.go
  apiserver/facades/agent/unitassigner/unitassigner_test.go
  apiserver/facades/client/annotations/client_test.go
  apiserver/facades/client/application/application_unit_test.go
  apiserver/facades/client/application/deploy.go
  apiserver/facades/client/application/domain_mock.go
  apiserver/facades/client/highavailability/highavailability.go
  apiserver/facades/client/machinemanager/machinemanager.go
  apiserver/facades/client/machinemanager/machinemanager_test.go
  apiserver/facades/client/machinemanager/package_mock_test.go
  apiserver/facades/controller/machineundertaker/undertaker.go
  apiserver/facades/controller/machineundertaker/undertaker_test.go
  domain/annotation/state/query.go
  domain/annotation/state/state_test.go
  domain/blockdevice/state/state.go
  domain/blockdevice/state/state_test.go
  domain/blockdevice/state/types.go
  domain/blockdevice/watcher_test.go
  domain/machine/bootstrap/bootstrap.go
  domain/machine/bootstrap/bootstrap_test.go
  domain/machine/errors/errors.go
  domain/machine/modelmigration/import.go
  domain/machine/service/package_mock_test.go
  domain/machine/service/service.go
  domain/machine/service/service_test.go
  domain/machine/state/machine_cloud_instance.go
  domain/machine/state/machine_cloud_instance_test.go
  domain/machine/state/state.go
  domain/machine/state/state_test.go
  domain/machine/state/types.go
  domain/schema/model.go
  domain/schema/model/sql/0017-machine.sql
  domain/schema/model/triggers/machine-triggers.gen.go
  state/cleanup.go
  state/cleanup_test.go
Labels: 4.0

#17640 fix: go version should not include patch level
  CONTRIBUTING.md
  go.mod
  scripts/juju-mongotop/go.mod
Labels: 3.6

#17612 feat: Implementation of keyupdater domain state
  domain/keyupdater/state/controllerkeystate.go
  domain/keyupdater/state/controllerkeystate_test.go
  domain/keyupdater/state/package_test.go
  domain/keyupdater/state/state.go
  domain/keyupdater/state/state_test.go
  domain/keyupdater/state/types.go
Labels: 4.0

#17623 feat: send model description on migration
  api/controller/migrationmaster/client.go
  api/controller/migrationmaster/client_test.go
  api/controller/migrationtarget/client.go
  api/controller/migrationtarget/client_test.go
  apiserver/facades/client/controller/controller.go
  apiserver/facades/client/controller/controller_test.go
  apiserver/facades/client/controller/export_test.go
  apiserver/facades/client/controller/register.go
  apiserver/facades/controller/migrationmaster/facade.go
  apiserver/facades/controller/migrationmaster/facade_test.go
  apiserver/facades/schema.json
  core/migration/migration.go
  rpc/params/migration.go
  worker/migrationmaster/worker_test.go
Labels: 3.6

#17560 refactor: agenttools facade uses model config service
  Makefile
  apiserver/facades/controller/agenttools/agenttools.go
  apiserver/facades/controller/agenttools/agenttools_test.go
  apiserver/facades/controller/agenttools/package_test.go
  apiserver/facades/controller/agenttools/register.go
  apiserver/facades/controller/agenttools/service.go
  apiserver/facades/controller/agenttools/service_mock_test.go
Labels: 4.0

#17647 fix: add-k8s should reject if the cloud name uses the builtin "microk8s" name
  cmd/juju/caas/add.go
  cmd/juju/caas/add_test.go
Labels: 3.4

#17644 docs: change non-existant "refreshed" hook to "upgrade-charm"
  cmd/juju/application/refresh.go
Labels: 3.4

#17634 feat: add ControllerUUID facadeContext/sharedServerContext
  apiserver/apiserver.go
  apiserver/common/modelmanagerinterface.go
  apiserver/facade/facadetest/context.go
  apiserver/facade/interface.go
  apiserver/facades/agent/provisioner/provisioner.go
  apiserver/facades/agent/provisioner/provisioner_test.go
  apiserver/facades/agent/provisioner/provisioninginfo_test.go
  apiserver/facades/agent/secretsmanager/register.go
  apiserver/facades/agent/storageprovisioner/register.go
  apiserver/facades/agent/storageprovisioner/storageprovisioner.go
  apiserver/facades/agent/storageprovisioner/storageprovisioner_caas_test.go
  apiserver/facades/agent/storageprovisioner/storageprovisioner_iaas_test.go
  apiserver/facades/agent/storageprovisioner/storageprovisioner_test.go
  apiserver/facades/client/cloud/register.go
  apiserver/facades/client/modelmanager/modelinfo_test.go
  apiserver/facades/client/modelmanager/modelmanager.go
  apiserver/facades/client/modelmanager/register.go
  apiserver/facades/client/secretbackends/register.go
  apiserver/facades/client/secrets/register.go
  apiserver/facades/client/sshclient/facade.go
  apiserver/facades/client/sshclient/facade_test.go
  apiserver/facades/client/sshclient/register.go
  apiserver/facades/controller/crossmodelsecrets/register.go
  apiserver/facades/controller/migrationtarget/migrationtarget.go
  apiserver/facades/controller/migrationtarget/register.go
  apiserver/registration.go
  apiserver/root.go
  apiserver/shared.go
  apiserver/shared_test.go
  generate/schemagen/schemagen.go
  internal/worker/apiserver/worker.go
  internal/worker/apiserver/worker_state_test.go
  internal/worker/apiserver/worker_test.go
  juju/testing/apiserver.go
Labels: 4.0

#17635 feat: charm domain state
  core/charm/id.go
  domain/charm/service/metadata.go
  domain/charm/service/metadata_test.go
  domain/charm/service/package_mock_test.go
  domain/charm/service/service.go
  domain/charm/service/service_test.go
  domain/charm/state/metadata.go
  domain/charm/state/metadata_test.go
  domain/charm/state/package_test.go
  domain/charm/state/state.go
  domain/charm/state/state_test.go
  domain/charm/state/types.go
  domain/charm/types.go
  domain/schema/model/sql/0011-storage.sql
  domain/schema/model/sql/0015-charm.sql
  domain/schema/schema_test.go
  internal/database/testing/database.go
  internal/database/testing/notest.go
Labels: 4.0

#17641 test: fixes secretexpire worker tests by using Alarm not Timer.
  cmd/output/progress/mocks/clock_mock.go
  container/lxd/mocks/clock_mock.go
  go.mod
  go.sum
  service/snap/clock_mock_test.go
  state/mocks/clock_mock.go
  worker/changestream/clock_mock_test.go
  worker/changestream/stream/clock_mock_test.go
  worker/dbaccessor/clock_mock_test.go
  worker/filenotifywatcher/clock_mock_test.go
  worker/leaseexpiry/clock_mock_test.go
  worker/querylogger/clock_mock_test.go
  worker/secretexpire/secretexpire.go
  worker/storageprovisioner/mock_test.go
Labels: 3.4

#17615 revert: move session token login provider
  api/export_test.go
  api/sessiontokenloginprovider.go
  api/sessiontokenloginprovider_test.go
  api/userpassloginprovider.go
  cmd/internal/loginprovider/export_test.go
  cmd/internal/loginprovider/package_test.go
  cmd/internal/loginprovider/tryinorderloginprovider.go
  cmd/juju/controller/register.go
  cmd/juju/user/login.go
  cmd/modelcmd/base.go
Labels: 3.5

#17650 feat(domain): add machine_requires_reboot table in dqlite
  domain/schema/model/sql/0017-machine.sql
  domain/schema/schema_test.go
Labels: 4.0

#17662 fix: use correct LXD profile on state.Charm struct
  .github/workflows/terraform-smoke.yml
  apiserver/common/charms/appcharminfo_test.go
  apiserver/common/charms/charminfo_test.go
  apiserver/common/charms/common.go
  apiserver/common/charms/mocks/mocks.go
  apiserver/facades/client/application/application_test.go
  state/charm.go
Labels: 3.4

#17675 chore: merge 3.5
  .github/workflows/terraform-smoke.yml
  api/export_test.go
  api/sessiontokenloginprovider.go
  api/sessiontokenloginprovider_test.go
  api/userpassloginprovider.go
  apiserver/common/charms/appcharminfo_test.go
  apiserver/common/charms/charminfo_test.go
  apiserver/common/charms/common.go
  apiserver/common/charms/mocks/mocks.go
  apiserver/facades/client/application/application_test.go
  cmd/internal/loginprovider/export_test.go
  cmd/internal/loginprovider/package_test.go
  cmd/internal/loginprovider/tryinorderloginprovider.go
  cmd/juju/application/integrate.go
  cmd/juju/application/refresh.go
  cmd/juju/caas/add.go
  cmd/juju/caas/add_test.go
  cmd/juju/commands/upgradecontroller.go
  cmd/juju/commands/upgrademodel.go
  cmd/juju/controller/register.go
  cmd/juju/user/login.go
  cmd/modelcmd/base.go
  cmd/output/progress/mocks/clock_mock.go
  container/lxd/mocks/clock_mock.go
  go.mod
  go.sum
  service/snap/clock_mock_test.go
  state/application.go
  state/charm.go
  state/mocks/clock_mock.go
  state/state.go
  worker/changestream/clock_mock_test.go
  worker/changestream/stream/clock_mock_test.go
  worker/dbaccessor/clock_mock_test.go
  worker/filenotifywatcher/clock_mock_test.go
  worker/leaseexpiry/clock_mock_test.go
  worker/querylogger/clock_mock_test.go
  worker/secretexpire/secretexpire.go
  worker/storageprovisioner/mock_test.go
Labels: 3.6

#17676 chore(ci): update balchua/microk8s-actions to v0.4.3
  .github/workflows/microk8s-tests.yml
  .github/workflows/smoke.yml
  .github/workflows/upgrade.yml
Labels: 3.4

#17660 feat: add controller model ID to ServerConfig, sharedServerContext
  apiserver/admin.go
  apiserver/apiserver.go
  apiserver/embeddedcli.go
  apiserver/export_test.go
  apiserver/facades/agent/provisioner/provisioner_test.go
  apiserver/facades/agent/provisioner/provisioninginfo_test.go
  apiserver/facades/agent/storageprovisioner/storageprovisioner_caas_test.go
  apiserver/facades/agent/storageprovisioner/storageprovisioner_iaas_test.go
  apiserver/facades/client/application/application_test.go
  apiserver/facades/client/controller/controller_test.go
  apiserver/facades/controller/migrationtarget/servicefactory_mock_test.go
  apiserver/introspection.go
  apiserver/registration.go
  apiserver/root.go
  apiserver/shared.go
  apiserver/shared_test.go
  apiserver/tools.go
  cmd/jujud-controller/agent/bootstrap.go
  cmd/jujud-controller/agent/machine.go
  cmd/jujud-controller/agent/machine/manifolds.go
  domain/servicefactory/testing/service.go
  domain/servicefactory/testing/suite.go
  internal/migration/migration.go
  internal/migration/servicefactory_mock_test.go
  internal/servicefactory/interface.go
  internal/worker/apiserver/controllerconfig_mock_test.go
  internal/worker/apiserver/manifold.go
  internal/worker/apiserver/manifold_test.go
  internal/worker/apiserver/package_test.go
  internal/worker/apiserver/service.go
  internal/worker/apiserver/service_mock_test.go
  internal/worker/apiserver/worker.go
  internal/worker/apiserver/worker_state_test.go
  internal/worker/apiserver/worker_test.go
  internal/worker/bootstrap/manifold.go
  internal/worker/modelworkermanager/modelworkermanager.go
  internal/worker/objectstore/manifold.go
  internal/worker/objectstore/manifold_test.go
  internal/worker/objectstore/objectstore_mock_test.go
  internal/worker/objectstore/worker.go
  internal/worker/servicefactory/servicefactory_mock_test.go
  internal/worker/servicefactory/worker.go
  juju/testing/apiserver.go
  state/stateenvirons/policy.go
Labels: 4.0

#17656 feat(domain): crud for machine reboot management in DQLite
  domain/machine/service/package_mock_test.go
  domain/machine/service/service.go
  domain/machine/service/service_test.go
  domain/machine/state/state.go
  domain/machine/state/state_test.go
Labels: 4.0

#17679 chore(network): remove fan option from container networking config
  environs/config/config.go
  internal/network/containerizer/bridgepolicy.go
  internal/network/containerizer/bridgepolicy_test.go
Labels: 4.0

#17667 fix: assert user auth tag
  cmd/juju/application/bind_test.go
  cmd/juju/application/refresh_test.go
  cmd/modelcmd/modelcommand_test.go
  juju/api.go
  juju/api_test.go
  juju/mock_test.go
Labels: 3.4

#17652 fix: error useage and use sqlair in upgrade domain
  domain/upgrade/errors/errors.go
  domain/upgrade/service/service.go
  domain/upgrade/service/service_test.go
  domain/upgrade/state/state.go
  domain/upgrade/state/state_test.go
  domain/upgrade/state/types.go
  internal/worker/upgradedatabase/worker.go
  internal/worker/upgradedatabase/worker_test.go
  internal/worker/upgradesteps/controllerworker.go
Labels: 4.0

#17673 chore(watcher): add PrimeChangeStream for tests with empty changelog table
  domain/machine/watcher_test.go
  domain/network/watcher_test.go
  internal/changestream/testing/modelsuite.go
Labels: 4.0

#17638 feat(dqlite): add IsController service on machine domain
  domain/machine/service/package_mock_test.go
  domain/machine/service/service.go
  domain/machine/service/service_test.go
  domain/machine/state/machine_cloud_instance.go
  domain/machine/state/state.go
  domain/machine/state/state_test.go
  domain/machine/state/types.go
Labels: 4.0

#17663 feat(machine): add machine cloud instance watcher
  domain/machine/service/package_mock_test.go
  domain/machine/service/service.go
  domain/machine/service/watcher.go
  domain/machine/state/machine_cloud_instance.go
  domain/machine/state/types.go
  domain/machine/watcher_test.go
  domain/schema/model.go
  domain/schema/model/sql/0002-changelog-namespaces.sql
  domain/schema/model/triggers/machine-cloud-instance-triggers.go
  domain/schema/schema_test.go
Labels: 4.0

#17688 chore: use larger runners for long checks
  .github/verify-prometheus-k8s.sh
  .github/verify-snappass-test.sh
  .github/workflows/migrate.yml
  .github/workflows/smoke.yml
  .github/workflows/snap.yml
  .github/workflows/terraform-smoke.yml
  .github/workflows/upgrade.yml
Labels: 3.6

#17666 feat: larger back-off strategy
  internal/changestream/stream/stream.go
Labels: 4.0

#17690 docs(network): add network domain package documentation
  domain/network/doc.go
Labels: 4.0

#17680 chore: merge 3.6 into main
  CONTRIBUTING.md
  go.mod
  scripts/juju-mongotop/go.mod
Labels: 4.0

#17696 chore: merge #17623 to main
  api/controller/migrationmaster/client.go
  api/controller/migrationmaster/client_test.go
  api/controller/migrationtarget/client.go
  api/controller/migrationtarget/client_test.go
  apiserver/facades/client/controller/controller.go
  apiserver/facades/client/controller/controller_test.go
  apiserver/facades/client/controller/export_test.go
  apiserver/facades/client/controller/register.go
  apiserver/facades/controller/migrationmaster/facade.go
  apiserver/facades/controller/migrationmaster/facade_test.go
  apiserver/facades/schema.json
  core/migration/migration.go
  core/modelmigration/description_mock_test.go
  domain/schema/model/triggers/machine-cloud-instance-triggers.gen.go
  go.mod
  go.sum
  internal/worker/migrationmaster/worker_test.go
  rpc/params/migration.go
Labels: 4.0

#17704 ci: unify static analysis jobs under one so none are missed
  .github/workflows/static-analysis.yml
  api/sessiontokenloginprovider.go
  cmd/internal/loginprovider/doc.go
  cmd/internal/loginprovider/tryinorderloginprovider.go
  tests/suites/static_analysis/doc_go.py
  tests/suites/static_analysis/lint_go.sh
  tests/suites/static_analysis/task.sh
  tests/suites/static_analysis/versions.sh
Labels: 3.6

#17576 fix: charm version
  internal/charm/charmdir.go
  internal/charm/charmdir_test.go
  internal/charm/export_test.go
Labels: 4.0

#17653 fix(machine): only destroy controller machines with force
  state/cleanup.go
  state/cleanup_test.go
  state/machine.go
  state/machine_test.go
Labels: bug, 3.4

#17701 docs(cmd): fix formatting in juju config help
  cmd/juju/application/config.go
Labels: 3.4

#17706 chore: merge 3.4 into 3.5
  .github/workflows/microk8s-tests.yml
  .github/workflows/smoke.yml
  .github/workflows/upgrade.yml
  cmd/juju/application/bind_test.go
  cmd/juju/application/refresh_test.go
  cmd/modelcmd/modelcommand_test.go
  juju/api.go
  juju/api_test.go
  juju/mock_test.go
  state/cleanup.go
  state/cleanup_test.go
  state/machine.go
  state/machine_test.go
Labels: 3.5

#17707 chore: merge 3.5 into 3.6
  .github/workflows/microk8s-tests.yml
  .github/workflows/smoke.yml
  .github/workflows/upgrade.yml
  cmd/juju/application/bind_test.go
  cmd/juju/application/refresh_test.go
  cmd/modelcmd/modelcommand_test.go
  juju/api.go
  juju/api_test.go
  juju/mock_test.go
  state/cleanup.go
  state/cleanup_test.go
  state/machine.go
  state/machine_test.go
Labels: 3.6

#17692 fix(domain): cleanup broken model when recreating it
  domain/model/state/state.go
  domain/model/state/state_test.go
Labels: 4.0

#17695 ci: improve generate action
  .github/workflows/gen.yml
Labels: 4.0

#17694 chore: merge idempotent secrets from 3.6
  api/agent/secretsmanager/client.go
  api/agent/secretsmanager/client_test.go
  api/agent/uniter/unit.go
  api/client/secrets/client.go
  api/client/secrets/client_test.go
  apiserver/facades/agent/secretsmanager/secrets.go
  apiserver/facades/agent/secretsmanager/secrets_test.go
  apiserver/facades/agent/uniter/uniter_test.go
  apiserver/facades/client/secrets/secrets.go
  apiserver/facades/client/secrets/secrets_test.go
  apiserver/facades/schema.json
  cmd/juju/secrets/list.go
  cmd/juju/secrets/show_test.go
  core/secrets/secret.go
  core/secrets/secretvalue.go
  core/secrets/secretvalue_test.go
  domain/secret/service/params.go
  internal/worker/uniter/operation/util_test.go
  internal/worker/uniter/runner/context/context.go
  internal/worker/uniter/runner/context/context_test.go
  internal/worker/uniter/runner/context/contextfactory.go
  internal/worker/uniter/runner/context/flush_test.go
  internal/worker/uniter/runner/context/secrets.go
  internal/worker/uniter/runner/context/util_test.go
  internal/worker/uniter/runner/jujuc/context.go
  internal/worker/uniter/runner/jujuc/jujuctesting/secrets.go
  internal/worker/uniter/runner/testing/utils.go
  rpc/params/secrets.go
  state/migration_export.go
  state/migration_export_test.go
  state/migration_import_tasks.go
  state/migration_import_test.go
  state/migration_internal_test.go
  state/secrets.go
  state/secrets_test.go
  tests/suites/secrets_iaas/juju.sh
Labels: 4.0

#17712 chore: merge 2.9 into 3.1
  Makefile
  go.mod
  go.sum
Labels: 3.1

#17714 chore: merge 3.1 into 3.4
  Makefile
  go.mod
  go.sum
  tests/suites/manual/spaces.sh
Labels: 3.4

#17626 refactor(apiserver): move `common/crossmodel` package to model config services
  apiserver/apiserver.go
  apiserver/common/crossmodel/auth.go
  apiserver/common/crossmodel/auth_test.go
  apiserver/common/crossmodel/crossmodel.go
  apiserver/common/crossmodel/interface.go
  apiserver/common/crossmodel/mocks/crossmodel_mock.go
  apiserver/common/crossmodel/service.go
  apiserver/export_test.go
  apiserver/facades/client/application/application.go
  apiserver/facades/client/applicationoffers/access_test.go
  apiserver/facades/client/applicationoffers/applicationoffers.go
  apiserver/facades/client/applicationoffers/applicationoffers_test.go
  apiserver/facades/client/applicationoffers/base.go
  apiserver/facades/client/applicationoffers/base_test.go
  apiserver/facades/client/applicationoffers/package_test.go
  apiserver/facades/client/applicationoffers/register.go
  apiserver/facades/client/applicationoffers/service.go
  apiserver/facades/client/applicationoffers/service_mock_test.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations_test.go
  apiserver/facades/controller/crossmodelrelations/register.go
  apiserver/facades/controller/crossmodelsecrets/crossmodelsecrets.go
  apiserver/facades/controller/crossmodelsecrets/crossmodelsecrets_test.go
  apiserver/facades/controller/crossmodelsecrets/register.go
  apiserver/facades/controller/remoterelations/mocks/remoterelations_mocks.go
  apiserver/facades/controller/remoterelations/register.go
  apiserver/facades/controller/remoterelations/remoterelations.go
  apiserver/facades/controller/remoterelations/remoterelations_test.go
  apiserver/offerauth.go
  apiserver/service.go
Labels: 4.0

#17713 feat(azure): support creds with managed identity
  cloud/clouds.go
  cloud/clouds_test.go
  cloud/fallback-public-cloud.yaml
  cloud/fallback_public_cloud.go
  cmd/juju/controller/kill.go
  environs/bootstrap/bootstrap.go
  environs/bootstrap/bootstrap_test.go
  provider/azure/cloud.go
  provider/azure/cloud_test.go
  provider/azure/credentials.go
  provider/azure/credentials_test.go
  provider/azure/environ.go
  provider/azure/environprovider.go
  provider/azure/identity.go
  provider/azure/identity_test.go
  tests/suites/cloud_azure/managed_identity.sh
Labels: 3.6

#17710 ci: fix migrate action on main
  .github/waitfor.sh
  .github/workflows/gen.yml
  .github/workflows/migrate.yml
  apiserver/facades/agent/provisioner/provisioninginfo.go
Labels: 4.0

#17715 merge: 3.4 to 3.5
  Makefile
  cmd/juju/application/config.go
  go.mod
  go.sum
  tests/suites/manual/spaces.sh
Labels: 3.5

#17691 docs(controller-config): fix wording on agent controller config keys
  controller/config.go
Labels: 3.4

#17668 feat: state get implementations
  domain/charm/state/actions.go
  domain/charm/state/actions_test.go
  domain/charm/state/config.go
  domain/charm/state/config_test.go
  domain/charm/state/manifest.go
  domain/charm/state/state.go
  domain/charm/state/state_test.go
  domain/charm/state/types.go
  domain/schema/model/sql/0015-charm.sql
  domain/schema/schema_test.go
Labels: 4.0

#17683 feat: prevent unit agent bouncing with no upgrade series
  api/client/machinemanager/machinemanager.go
  api/client/machinemanager/machinemanager_test.go
  worker/uniter/agent.go
  worker/uniter/remotestate/watcher.go
  worker/uniter/remotestate/watcher_test.go
Labels: 3.6

#17705 feat(domain): add macaroon_root_key table
  domain/schema/controller/sql/0020-bakery-storage.sql
  domain/schema/controller/sql/0020-macaroon.sql
  domain/schema/schema_test.go
Labels: 4.0

#17718 feat(migration): prevent pre-4.0 models with fan config to be migrated
  api/controller/migrationmaster/client.go
  api/controller/migrationtarget/client_test.go
  apiserver/facades/client/controller/controller.go
  apiserver/facades/client/controller/register.go
  apiserver/facades/controller/migrationtarget/migrationtarget.go
  internal/migration/precheck.go
  internal/migration/precheck_test.go
Labels: 4.0

#17708 feat: set charm
  domain/charm/state/actions.go
  domain/charm/state/actions_test.go
  domain/charm/state/config.go
  domain/charm/state/config_test.go
  domain/charm/state/manifest.go
  domain/charm/state/manifest_test.go
  domain/charm/state/metadata.go
  domain/charm/state/metadata_test.go
  domain/charm/state/state.go
  domain/charm/state/state_test.go
  domain/charm/state/types.go
  domain/schema/model/sql/0015-charm.sql
Labels: 4.0

#17725 fix: change stream test composition
  internal/changestream/stream/package_test.go
  internal/changestream/stream/stream.go
  internal/changestream/stream/stream_test.go
  internal/logger/testing/check.go
Labels: 4.0

#17727 docs(block): remove doc/block.txt
  apiserver/common/block.go
  cmd/juju/block/doc.go
  cmd/juju/block/protection.go
  core/model/block.go
  core/model/doc.go
  doc/block_commands_operations.txt
  state/block.go
Labels: 3.6

#17664 feat: use controller UUID in access perms
  agent/agentbootstrap/bootstrap.go
  apiserver/admin.go
  apiserver/admin_test.go
  apiserver/auditconfig_test.go
  apiserver/authentication/agent_test.go
  apiserver/authentication/user_test.go
  apiserver/charms_test.go
  apiserver/facades/agent/caasapplication/application_test.go
  apiserver/facades/client/client/api_test.go
  apiserver/facades/client/cloud/cloud.go
  apiserver/facades/client/controller/controller.go
  apiserver/facades/client/controller/controller_test.go
  apiserver/facades/client/usermanager/register.go
  apiserver/facades/client/usermanager/usermanager.go
  apiserver/facades/client/usermanager/usermanager_test.go
  apiserver/introspection.go
  apiserver/introspection_test.go
  apiserver/objects_test.go
  apiserver/pubsub_test.go
  apiserver/ratelimit_test.go
  apiserver/registration_test.go
  apiserver/server_test.go
  apiserver/stateauthenticator/delegator.go
  apiserver/tools_integration_test.go
  apiserver/tools_test.go
  core/permission/user.go
  core/permission/user_test.go
  domain/access/bootstrap/bootstrap_test.go
  domain/access/service/user_test.go
  domain/access/state/permission.go
  domain/access/state/permission_test.go
  domain/access/state/user_test.go
  domain/controllerconfig/bootstrap/bootstrap.go
  domain/controllerconfig/bootstrap/bootstrap_test.go
  domain/credential/bootstrap/bootstrap_test.go
  domain/credential/state/state_test.go
  domain/model/bootstrap/bootstrap_test.go
  domain/model/state/state_test.go
  domain/modelconfig/bootstrap/bootstrap_test.go
  domain/modelconfig/modelconfig_test.go
  domain/schema/controller/sql/0017-user-permission.sql
  domain/schema/testing/controllersuite.go
  domain/secretbackend/state/state_test.go
  domain/servicefactory/testing/suite.go
  internal/worker/bootstrap/worker.go
  internal/worker/bootstrap/worker_test.go
  juju/testing/apiserver.go
  juju/testing/macaroonsuite.go
Labels: 4.0

#17735 fix(tests): fix controller removal on enable-ha integration tests
  tests/suites/controller/enable_ha.sh
Labels: 3.4

#17726 fix: use unique error for session token login
  api/sessiontokenloginprovider.go
  api/sessiontokenloginprovider_test.go
  rpc/params/apierror.go
Labels: 3.5

#17719 feat: delete charm
  domain/charm/service/charm_mock_test.go
  domain/charm/service/package_mock_test.go
  domain/charm/service/package_test.go
  domain/charm/service/service.go
  domain/charm/service/service_test.go
  domain/charm/state/state.go
  domain/charm/state/state_test.go
  domain/charm/state/types.go
Labels: 4.0

#17737 chore: merge 3.4 into 3.5
  controller/config.go
  tests/suites/controller/enable_ha.sh
Labels: 3.5

#17733 test: move licence check to static_analysis test suite
  .github/workflows/changed-files.yml
  .github/workflows/license.yml
  .github/workflows/static-analysis.yml
  tests/suites/static_analysis/licence.sh
  tests/suites/static_analysis/task.sh
Labels: 3.6

#17729 feat(macaroons): implement root key service + state
  domain/macaroon/errors/errors.go
  domain/macaroon/service/config_test.go
  domain/macaroon/service/package_mock_test.go
  domain/macaroon/service/rootkeys.go
  domain/macaroon/service/rootkeys_test.go
  domain/macaroon/service/service.go
  domain/macaroon/state/config.go
  domain/macaroon/state/config_test.go
  domain/macaroon/state/rootkeys.go
  domain/macaroon/state/rootkeys_test.go
  domain/macaroon/state/state.go
  domain/macaroon/state/types.go
  domain/macaroon/types.go
Labels: 4.0

#17709 feat(dqlite): double write Dead machine life with EnsureDeadMachine backed by dqlite
  apiserver/common/ensuredead.go
  apiserver/common/ensuredead_test.go
  apiserver/common/mocks/machine_service_mock.go
  apiserver/common/package_test.go
  apiserver/facades/agent/machine/machiner.go
  apiserver/facades/agent/machine/machiner_test.go
  apiserver/facades/agent/machine/package_mock_test.go
  apiserver/facades/agent/machine/package_test.go
  apiserver/facades/agent/machine/register.go
  apiserver/facades/agent/provisioner/provisioner.go
  apiserver/facades/agent/provisioner/provisioner_test.go
  apiserver/facades/agent/storageprovisioner/register.go
  apiserver/facades/agent/storageprovisioner/service.go
  apiserver/facades/agent/storageprovisioner/storageprovisioner.go
  apiserver/facades/agent/storageprovisioner/storageprovisioner_caas_test.go
  apiserver/facades/agent/storageprovisioner/storageprovisioner_iaas_test.go
  apiserver/facades/agent/storageprovisioner/storageprovisioner_test.go
  apiserver/facades/agent/uniter/register.go
  apiserver/facades/agent/uniter/service.go
  apiserver/facades/agent/uniter/uniter_apierror_test.go
  apiserver/facades/agent/uniter/uniter_cloudspec_test.go
  domain/machine/service/package_mock_test.go
  domain/machine/service/service.go
  domain/machine/service/service_test.go
  domain/machine/state/state.go
  domain/machine/state/state_test.go
  domain/machine/state/types.go
Labels: 4.0

#17738 chore: merge 3.5 into 3.6
  api/sessiontokenloginprovider.go
  api/sessiontokenloginprovider_test.go
  controller/config.go
  rpc/params/apierror.go
  tests/suites/controller/enable_ha.sh
Labels: 3.6

#17741 chore: merge 3.6 into main
  .github/workflows/build.yml
  .github/workflows/client-tests.yml
  .github/workflows/context-tests.yml
  .github/workflows/gen.yml
  .github/workflows/license.yml
  .github/workflows/migrate.yml
  .github/workflows/snap.yml
  .github/workflows/static-analysis.yml
  .github/workflows/terraform-smoke.yml
  .github/workflows/upgrade.yml
  api/client/machinemanager/machinemanager_test.go
  api/sessiontokenloginprovider.go
  api/sessiontokenloginprovider_test.go
  apiserver/common/block.go
  cmd/juju/block/doc.go
  cmd/juju/block/protection.go
  controller/config.go
  core/model/block.go
  core/model/doc.go
  doc/block_commands_operations.txt
  internal/worker/uniter/remotestate/watcher_test.go
  rpc/params/apierror.go
  state/block.go
  tests/suites/cloud_azure/managed_identity.sh
  tests/suites/controller/enable_ha.sh
  tests/suites/static_analysis/licence.sh
  tests/suites/static_analysis/task.sh
Labels: 4.0

#17486 docs: add SeeAlso and Example docstrings for juju commands;
  cmd/juju/action/cancel.go
  cmd/juju/action/exec.go
  cmd/juju/action/showtask.go
  cmd/juju/agree/agree/agree.go
  cmd/juju/agree/listagreements/listagreements.go
  cmd/juju/application/bind.go
  cmd/juju/application/config.go
  cmd/juju/application/expose.go
  cmd/juju/application/refresh.go
  cmd/juju/application/removeapplication.go
  cmd/juju/application/resolved.go
  cmd/juju/application/scaleapplication.go
  cmd/juju/application/showunit.go
  cmd/juju/application/unexpose.go
  cmd/juju/backups/download.go
  cmd/juju/commands/bootstrap.go
  cmd/juju/commands/helptool.go
  cmd/juju/commands/helptool_test.go
  cmd/juju/commands/list_sshkeys.go
  cmd/juju/commands/version.go
  cmd/juju/controller/addmodel.go
  cmd/juju/machine/show.go
  cmd/juju/metricsdebug/collectmetrics.go
  cmd/juju/metricsdebug/metrics.go
  cmd/juju/model/grantrevoke.go
  cmd/juju/model/grantrevokecloud.go
  cmd/juju/model/retryprovisioning.go
  cmd/juju/model/show.go
  cmd/juju/resource/list.go
  cmd/juju/resource/upload.go
  cmd/juju/secrets/list.go
  cmd/juju/secrets/show.go
  cmd/juju/space/reload.go
  cmd/juju/ssh/debugcode.go
  cmd/juju/ssh/debughooks.go
  cmd/juju/status/history.go
  cmd/juju/storage/detach.go
  cmd/juju/storage/import.go
  cmd/juju/storage/list.go
  cmd/juju/storage/poollist.go
  cmd/juju/storage/remove.go
  cmd/juju/storage/show.go
  cmd/juju/subnet/list.go
  cmd/juju/waitfor/waitfor.go
Labels: 3.4

#17655 feat: add Pebble check-failed and check-recovered events
  go.mod
  go.sum
  testcharms/charms/pebble-checks/.gitignore
  testcharms/charms/pebble-checks/charmcraft.yaml
  testcharms/charms/pebble-checks/metadata.yaml
  testcharms/charms/pebble-checks/pyproject.toml
  testcharms/charms/pebble-checks/requirements.txt
  testcharms/charms/pebble-checks/src/charm.py
  testcharms/charms/pebble-checks/tests/unit/test_charm.py
  testcharms/charms/pebble-checks/tox.ini
  tests/suites/sidecar/sidecar.sh
  tests/suites/sidecar/task.sh
  worker/uniter/container/workload.go
  worker/uniter/container/workload_test.go
  worker/uniter/hook/hook.go
  worker/uniter/hook/hook_test.go
  worker/uniter/pebblenotices.go
  worker/uniter/pebblenotices_test.go
  worker/uniter/pebblepoller.go
  worker/uniter/pebblepoller_test.go
  worker/uniter/runner/context/context.go
  worker/uniter/runner/context/contextfactory.go
  worker/uniter/runner/context/contextfactory_test.go
  worker/uniter/runner/context/env_test.go
  worker/uniter/runner/context/export_test.go
Labels: 3.6

#17732 refactor: call ModelConfigAPI instead of ControllerAPI.ModelConfig
  api/controller/controller/controller.go
  api/controller/controller/legacy_test.go
  apiserver/facades/client/controller/controller.go
  apiserver/facades/schema.json
  cmd/juju/commands/mocks/controller_mock.go
  cmd/juju/commands/package_test.go
  cmd/juju/commands/upgradecontroller.go
  cmd/juju/commands/upgradecontroller_test.go
  cmd/juju/commands/upgrademodel.go
  cmd/juju/commands/upgrademodel_test.go
  cmd/juju/controller/destroy.go
  cmd/juju/controller/destroy_test.go
  cmd/juju/controller/export_test.go
  cmd/juju/controller/kill.go
  cmd/juju/controller/kill_test.go
  cmd/juju/controller/showcontroller.go
  cmd/juju/controller/showcontroller_test.go
Labels: 3.6

#17746 feat: add machine_parent table to schema
  domain/schema/model/sql/0017-machine.sql
  domain/schema/schema_test.go
Labels: 4.0

#17516 feat: juju switch to previous controller or model
  cmd/juju/commands/bootstrap_test.go
  cmd/juju/commands/mocks/jujuclient_mock.go
  cmd/juju/commands/switch.go
  cmd/juju/commands/switch_test.go
  cmd/juju/controller/addmodel.go
  cmd/juju/controller/addmodel_test.go
  cmd/juju/user/utils_clientstore_mock_test.go
  jujuclient/controllers.go
  jujuclient/controllersfile_test.go
  jujuclient/file.go
  jujuclient/interface.go
  jujuclient/jujuclienttesting/stub.go
  jujuclient/mem.go
  jujuclient/models.go
Labels: 4.0

#17753 refactor: rename userservice to accesservice
  apiserver/stateauthenticator/auth.go
  apiserver/stateauthenticator/authenticator_test.go
  apiserver/stateauthenticator/context.go
  apiserver/stateauthenticator/context_test.go
  apiserver/stateauthenticator/delegator.go
  apiserver/stateauthenticator/package_test.go
  apiserver/stateauthenticator/services_mock_test.go
  internal/worker/httpserverargs/authenticator.go
  internal/worker/httpserverargs/manifold.go
  internal/worker/httpserverargs/manifold_test.go
  internal/worker/httpserverargs/package_test.go
  internal/worker/httpserverargs/services_mock_test.go
  internal/worker/httpserverargs/worker.go
  internal/worker/httpserverargs/worker_test.go
Labels: 4.0

#17751 refactor(apiserver): drop some state calls
  apiserver/export_test.go
  apiserver/stateauthenticator/auth.go
  apiserver/stateauthenticator/authenticator_test.go
  apiserver/stateauthenticator/context.go
  apiserver/stateauthenticator/context_test.go
  domain/model/state/state.go
  domain/model/state/state_test.go
  internal/worker/httpserverargs/authenticator.go
  internal/worker/httpserverargs/manifold_test.go
  internal/worker/httpserverargs/package_test.go
  internal/worker/httpserverargs/worker.go
  internal/worker/httpserverargs/worker_test.go
  juju/testing/apiserver.go
Labels: 4.0

#17720 feat: watch charm changes
  core/watcher/watchertest/harness.go
  core/watcher/watchertest/watcher.go
  domain/charm/package_test.go
  domain/charm/service/config.go
  domain/charm/watcher_test.go
  domain/controllerconfig/watcher_test.go
  domain/schema/model.go
  domain/schema/model/sql/0002-changelog-namespaces.sql
  domain/schema/model/triggers/charm.gen.go
  domain/schema/schema_test.go
Labels: 4.0

#17693 feat(dqlite): introduce status in machine domain
  core/status/status.go
  core/status/status_test.go
  domain/machine/errors/errors.go
  domain/machine/service/machine_cloud_instance.go
  domain/machine/service/package_mock_test.go
  domain/machine/service/service.go
  domain/machine/service/service_test.go
  domain/machine/state/machine_cloud_instance.go
  domain/machine/state/machine_cloud_instance_test.go
  domain/machine/state/state.go
  domain/machine/state/state_test.go
  domain/machine/state/types.go
  domain/schema/model/sql/0016-machine-cloud-instance.sql
  domain/schema/model/sql/0017-machine.sql
  domain/schema/model/sql/0021-status.sql
  domain/schema/schema_test.go
Labels: 4.0

#17750 fix: dqlite watcher tidy-up
  core/watcher/eventsource/base.go
  core/watcher/eventsource/namespace.go
  core/watcher/eventsource/value.go
  domain/secret/state/state.go
Labels: 4.0

#17758 chore: merge 3.6 into main
  .github/workflows/context-tests.yml
  api/controller/controller/controller.go
  api/controller/controller/controller_test.go
  apiserver/facades/client/controller/controller.go
  apiserver/facades/schema.json
  cmd/juju/commands/mocks/controller_mock.go
  cmd/juju/commands/package_test.go
  cmd/juju/commands/upgradecontroller.go
  cmd/juju/commands/upgradecontroller_test.go
  cmd/juju/commands/upgrademodel.go
  cmd/juju/commands/upgrademodel_test.go
  cmd/juju/controller/destroy.go
  cmd/juju/controller/destroy_test.go
  cmd/juju/controller/export_test.go
  cmd/juju/controller/kill.go
  cmd/juju/controller/kill_test.go
  cmd/juju/controller/showcontroller.go
  cmd/juju/controller/showcontroller_test.go
  go.mod
  go.sum
  internal/charm/hooks/hooks.go
  internal/worker/authenticationworker/worker.go
  internal/worker/uniter/container/workload.go
  internal/worker/uniter/container/workload_test.go
  internal/worker/uniter/hook/hook.go
  internal/worker/uniter/hook/hook_test.go
  internal/worker/uniter/pebblenotices.go
  internal/worker/uniter/pebblenotices_test.go
  internal/worker/uniter/pebblepoller.go
  internal/worker/uniter/pebblepoller_test.go
  internal/worker/uniter/runner/context/context.go
  internal/worker/uniter/runner/context/contextfactory.go
  internal/worker/uniter/runner/context/contextfactory_test.go
  internal/worker/uniter/runner/context/env_test.go
  internal/worker/uniter/runner/context/export_test.go
  testcharms/charms/pebble-checks/.gitignore
  testcharms/charms/pebble-checks/charmcraft.yaml
  testcharms/charms/pebble-checks/metadata.yaml
  testcharms/charms/pebble-checks/pyproject.toml
  testcharms/charms/pebble-checks/requirements.txt
  testcharms/charms/pebble-checks/src/charm.py
  testcharms/charms/pebble-checks/tests/unit/test_charm.py
  testcharms/charms/pebble-checks/tox.ini
  tests/main.sh
  tests/suites/authorized_keys/machine.sh
  tests/suites/authorized_keys/task.sh
  tests/suites/authorized_keys/user.sh
  tests/suites/sidecar/sidecar.sh
  tests/suites/sidecar/task.sh
Labels: 4.0

#17763 chore: merge 3.4
  apiserver/facades/client/client/client.go
  apiserver/facades/client/client/client_test.go
  apiserver/facades/client/modelupgrader/findagents.go
  apiserver/facades/client/modelupgrader/upgrader_test.go
  cmd/juju/action/cancel.go
  cmd/juju/action/exec.go
  cmd/juju/action/showtask.go
  cmd/juju/agree/agree/agree.go
  cmd/juju/agree/listagreements/listagreements.go
  cmd/juju/application/bind.go
  cmd/juju/application/config.go
  cmd/juju/application/expose.go
  cmd/juju/application/refresh.go
  cmd/juju/application/removeapplication.go
  cmd/juju/application/resolved.go
  cmd/juju/application/scaleapplication.go
  cmd/juju/application/showunit.go
  cmd/juju/application/unexpose.go
  cmd/juju/backups/download.go
  cmd/juju/commands/bootstrap.go
  cmd/juju/commands/helptool.go
  cmd/juju/commands/helptool_test.go
  cmd/juju/commands/list_sshkeys.go
  cmd/juju/commands/version.go
  cmd/juju/controller/addmodel.go
  cmd/juju/machine/show.go
  cmd/juju/metricsdebug/collectmetrics.go
  cmd/juju/metricsdebug/metrics.go
  cmd/juju/model/grantrevoke.go
  cmd/juju/model/grantrevokecloud.go
  cmd/juju/model/retryprovisioning.go
  cmd/juju/model/show.go
  cmd/juju/resource/list.go
  cmd/juju/resource/upload.go
  cmd/juju/secrets/list.go
  cmd/juju/secrets/show.go
  cmd/juju/space/reload.go
  cmd/juju/ssh/debugcode.go
  cmd/juju/ssh/debughooks.go
  cmd/juju/status/history.go
  cmd/juju/storage/detach.go
  cmd/juju/storage/import.go
  cmd/juju/storage/list.go
  cmd/juju/storage/poollist.go
  cmd/juju/storage/remove.go
  cmd/juju/storage/show.go
  cmd/juju/subnet/list.go
  cmd/juju/waitfor/waitfor.go
  docker/registry/internal/acr.go
  docker/registry/internal/acr_test.go
  docker/registry/internal/base_client.go
  docker/registry/internal/base_manifests.go
  docker/registry/internal/base_manifests_test.go
  docker/registry/internal/base_tags.go
  docker/registry/internal/ecr.go
  docker/registry/internal/ecr_test.go
  docker/registry/internal/interface.go
  docker/registry/internal/package_test.go
  docker/registry/mocks/registry_mock.go
Labels: 3.5

#17754 feat: update juju/cmd/v4 package to v4.0.1
  cmd/internal/run/run.go
  cmd/internal/run/run_test.go
  cmd/juju/commands/plugin.go
  cmd/juju/commands/plugin_test.go
  go.mod
  go.sum
Labels: 4.0

#17574 feat: Container manager service
  apiserver/common/modelmanagerinterface.go
  apiserver/facades/agent/provisioner/container_test.go
  apiserver/facades/agent/provisioner/imagemetadata_test.go
  apiserver/facades/agent/provisioner/package_test.go
  apiserver/facades/agent/provisioner/provisioner.go
  apiserver/facades/agent/provisioner/provisioner_internal_test.go
  apiserver/facades/agent/provisioner/provisioner_test.go
  apiserver/facades/agent/provisioner/provisioninginfo_test.go
  apiserver/facades/agent/provisioner/register.go
  apiserver/facades/agent/provisioner/service.go
  apiserver/facades/agent/provisioner/service_mock_test.go
  apiserver/facades/client/modelmanager/modelinfo_test.go
  apiserver/facades/client/modelmanager/modelmanager.go
  apiserver/facades/controller/migrationtarget/servicefactory_mock_test.go
  cmd/containeragent/initialize/package_test.go
  cmd/jujud-controller/agent/bootstrap.go
  core/container/types.go
  core/containermanager/types.go
  core/modelconfig/doc.go
  core/modelconfig/types.go
  domain/agentprovisioner/doc.go
  domain/agentprovisioner/service/mock_test.go
  domain/agentprovisioner/service/package_test.go
  domain/agentprovisioner/service/service.go
  domain/agentprovisioner/service/service_test.go
  domain/agentprovisioner/state/package_test.go
  domain/agentprovisioner/state/state.go
  domain/agentprovisioner/state/state_test.go
  domain/agentprovisioner/state/types.go
  domain/keyupdater/service/service.go
  domain/keyupdater/service/service_mock_test.go
  domain/keyupdater/service/service_test.go
  domain/keyupdater/state/state.go
  domain/keyupdater/state/state_test.go
  domain/modelconfig/service/service.go
  domain/modelconfig/validators/validators.go
  domain/modelconfig/validators/validators_test.go
  domain/servicefactory/model.go
  domain/servicefactory/testing/service.go
  environs/config/config.go
  environs/config/schema.go
  internal/container/lxd/initialisation_linux.go
  internal/container/lxd/initialisation_test.go
  internal/migration/export_test.go
  internal/migration/precheck.go
  internal/migration/servicefactory_mock_test.go
  internal/network/containerizer/bridgepolicy.go
  internal/network/containerizer/bridgepolicy_test.go
  internal/provider/manual/provider.go
  internal/servicefactory/interface.go
  internal/worker/provisioner/container_initialisation.go
  internal/worker/provisioner/container_initialisation_test.go
  internal/worker/provisioner/containerworker_test.go
  internal/worker/servicefactory/servicefactory_mock_test.go
  state/containernetworking.go
  state/containernetworking_test.go
Labels: 4.0

#17755 feat: allows to check what a machine should do in case of reboot
  domain/machine/errors/errors.go
  domain/machine/service/package_mock_test.go
  domain/machine/service/service.go
  domain/machine/service/service_test.go
  domain/machine/state/machine_cloud_instance.go
  domain/machine/state/reboot.go
  domain/machine/state/reboot_test.go
  domain/machine/state/state.go
  domain/machine/state/state_test.go
  domain/machine/types.go
Labels: 4.0

#17757 feat: coerce error for every transaction
  apiserver/facades/agent/provisioner/provisioninginfo.go
  domain/access/state/permission.go
  domain/access/state/user.go
  domain/agentprovisioner/state/state.go
  domain/annotation/state/state.go
  domain/autocert/errors/errors.go
  domain/autocert/state/state.go
  domain/autocert/state/state_test.go
  domain/blockdevice/state/state.go
  domain/charm/state/state.go
  domain/cloud/state/state.go
  domain/controllernode/errors/errors.go
  domain/controllernode/service/service.go
  domain/controllernode/service/service_test.go
  domain/controllernode/state/state.go
  domain/controllernode/state/state_test.go
  domain/credential/state/state.go
  domain/externalcontroller/state/state.go
  domain/flag/state/state.go
  domain/keymanager/state/state.go
  domain/keyupdater/state/controllerkeystate.go
  domain/keyupdater/state/state.go
  domain/lease/state/state.go
  domain/macaroon/errors/errors.go
  domain/macaroon/state/config.go
  domain/macaroon/state/config_test.go
  domain/macaroon/state/errors.go
  domain/macaroon/state/rootkeys.go
  domain/macaroon/state/rootkeys_test.go
  domain/machine/state/machine_cloud_instance.go
  domain/machine/state/machine_cloud_instance_test.go
  domain/machine/state/state.go
  domain/machine/state/state_test.go
  domain/model/state/modelstate.go
  domain/model/state/state.go
  domain/model/state/state_test.go
  domain/modelagent/state/state.go
  domain/modelconfig/state/state.go
  domain/modeldefaults/state/state.go
  domain/network/errors/errors.go
  domain/network/state/space.go
  domain/network/state/space_test.go
  domain/network/state/subnet.go
  domain/network/state/subnet_test.go
  domain/objectstore/service/service.go
  domain/objectstore/state/state.go
  domain/secret/state/state.go
  domain/secretbackend/state/state.go
  domain/state.go
  domain/storage/state/storagepool.go
  domain/upgrade/service/service.go
  domain/upgrade/state/state.go
Labels: 4.0

#17700 docs: add conventional commits guidelines to contributing.md
  CONTRIBUTING.md
  doc/conventional-commits.md
Labels: 3.4

#17578 feat: pebble identities with rootless charms
  caas/kubernetes/provider/application/application.go
  caas/kubernetes/provider/application/application_test.go
  caas/kubernetes/provider/application/spec31_test.go
  caas/kubernetes/provider/application/spec35_test.go
  caas/kubernetes/provider/application/spec36_test.go
  cmd/containeragent/initialize/command.go
  cmd/containeragent/initialize/package_test.go
  go.mod
  go.sum
  service/pebble/identity/doc.go
  service/pebble/identity/identities.go
  testcharms/charms/sidecar-non-root/hooks/install
  testcharms/charms/sidecar-non-root/hooks/rootful-pebble-ready
  testcharms/charms/sidecar-non-root/hooks/rootless-pebble-ready
  testcharms/charms/sidecar-non-root/hooks/upgrade-charm
  testcharms/charms/sidecar-non-root/manifest.yaml
  testcharms/charms/sidecar-non-root/metadata.yaml
  testcharms/charms/sidecar-sudoer/hooks/install
  testcharms/charms/sidecar-sudoer/hooks/rootful-pebble-ready
  testcharms/charms/sidecar-sudoer/hooks/rootless-pebble-ready
  testcharms/charms/sidecar-sudoer/hooks/upgrade-charm
  testcharms/charms/sidecar-sudoer/manifest.yaml
  testcharms/charms/sidecar-sudoer/metadata.yaml
  tests/suites/sidecar/rootless.sh
  tests/suites/sidecar/task.sh
  worker/caasapplicationprovisioner/ops.go
Labels: dependencies, 3.6

#17766 feat: db error metrics
  internal/database/txn/context.go
  internal/database/txn/transaction.go
  internal/worker/dbaccessor/metrics.go
  internal/worker/dbaccessor/metrics_test.go
  internal/worker/dbaccessor/tracker.go
Labels: 4.0

#17740 feat: set charm additional data
  domain/charm/errors/errors.go
  domain/charm/service/charm.go
  domain/charm/service/package_mock_test.go
  domain/charm/service/service.go
  domain/charm/service/service_test.go
  domain/charm/state/metadata.go
  domain/charm/state/metadata_test.go
  domain/charm/state/state.go
  domain/charm/state/state_test.go
  domain/charm/state/types.go
  domain/charm/types.go
  domain/charm/watcher_test.go
  domain/schema/model/sql/0015-charm.sql
  domain/schema/model/triggers/charm.gen.go
Labels: 4.0

#17747 fix: retry applying lxd profiles
  core/lxdprofile/name.go
  core/lxdprofile/name_test.go
  state/machine.go
  state/machine_test.go
  worker/instancemutater/export_test.go
  worker/instancemutater/mutater.go
  worker/instancemutater/mutater_test.go
  worker/instancemutater/worker_test.go
  worker/provisioner/provisioner_task.go
Labels: 3.4

#17731 feat: remove deploy from directory
  cmd/juju/application/bundle_test.go
  cmd/juju/application/deploy.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/charm.go
  cmd/juju/application/deployer/deployer_test.go
  cmd/juju/application/refresh.go
  cmd/juju/application/refresh_test.go
  core/charm/charmpath.go
  core/charm/charmpath_test.go
  go.mod
  go.sum
  internal/charm/bundledir.go
  internal/charm/charmarchive_test.go
  internal/charm/charmdir.go
  internal/charm/charmdir_test.go
  internal/charm/jujuignore.go
  internal/charm/jujuignore_test.go
  testcharms/repo/repo.go
  tests/suites/deploy/bundles/trusted_bundle.yaml
  tests/suites/deploy/charms/trust-checker/manifest.yaml
  tests/suites/deploy/charms/trust-checker/metadata.yaml
  tests/suites/deploy/deploy_bundles.sh
Labels: 4.0

#17782 build: prevent internal/pki/test from linking into juju bins
  internal/pki/test/notest.go
  snap/snapcraft.yaml
Labels: 4.0

#17777 chore: merge application and charm domain
  apiserver/facades/controller/cleaner/cleaner_test.go
  domain/application/charm/doc.go
  domain/application/charm/types.go
  domain/application/doc.go
  domain/application/errors/errors.go
  domain/application/modelmigration/import.go
  domain/application/package_test.go
  domain/application/service/actions.go
  domain/application/service/actions_test.go
  domain/application/service/application.go
  domain/application/service/application_test.go
  domain/application/service/charm.go
  domain/application/service/charm_mock_test.go
  domain/application/service/charm_test.go
  domain/application/service/config.go
  domain/application/service/config_test.go
  domain/application/service/lxdprofile.go
  domain/application/service/lxdprofile_test.go
  domain/application/service/manifest.go
  domain/application/service/manifest_test.go
  domain/application/service/metadata.go
  domain/application/service/metadata_test.go
  domain/application/service/package_mock_test.go
  domain/application/service/package_test.go
  domain/application/service/params.go
  domain/application/service/service.go
  domain/application/state/actions.go
  domain/application/state/actions_test.go
  domain/application/state/application.go
  domain/application/state/application_test.go
  domain/application/state/charm.go
  domain/application/state/charm_test.go
  domain/application/state/config.go
  domain/application/state/config_test.go
  domain/application/state/manifest.go
  domain/application/state/manifest_test.go
  domain/application/state/metadata.go
  domain/application/state/metadata_test.go
  domain/application/state/package_test.go
  domain/application/state/state.go
  domain/application/state/types.go
  domain/application/types.go
  domain/application/watcher_test.go
  domain/charm/errors/errors.go
  domain/charm/package_test.go
  domain/charm/service/charm.go
  domain/charm/service/package_mock_test.go
  domain/charm/service/package_test.go
  domain/charm/state/types.go
  domain/secret/watcher_test.go
  domain/servicefactory/model.go
  internal/bootstrap/bootstrap_mock_test.go
  internal/bootstrap/deployer.go
Labels: 4.0

#17789 fix(migration): empty map compared to nil map for credential equality
  state/cloudcredentials.go
  state/cloudcredentials_test.go
  state/migration_import.go
  state/migration_import_test.go
Labels: 3.4

#17784 chore: update pebble-checks test charm to use ops 2.15
  testcharms/charms/pebble-checks/requirements.txt
  testcharms/charms/pebble-checks/src/charm.py
  testcharms/charms/pebble-checks/tests/unit/test_charm.py
  testcharms/charms/pebble-notices/pyproject.toml
  testcharms/charms/pebble-notices/requirements.txt
  testcharms/charms/pebble-notices/tox.ini
Labels: 3.6

#17788 fix: do not emit hook context ID
  worker/uniter/runner/runner.go
  worker/uniter/runner/runner_test.go
  worker/uniter/util_test.go
Labels: 2.9

#17793 ci: remove installed lxd for 2.9
  .github/workflows/upgrade.yml
Labels: 2.9

#17794 chore(deps): security updates
  .github/workflows/static-analysis.yml
  acceptancetests/jujupy/client.py
  acceptancetests/jujupy/tests/test_status.py
  acceptancetests/repository/trusty/haproxy/cm.py
  acceptancetests/tests/test_jujucharm.py
  go.mod
  go.sum
  provider/azure/internal/errorutils/errors_test.go
  scripts/find-bad-doc-comments.py
  scripts/leadershipclaimer/count-leadership.py
  tests/README.md
  tests/suites/static_analysis/lint_go.sh
Labels: 2.9

#17778 fix: watcher for WatchModelMachines
  core/watcher/eventsource/namespace.go
  domain/machine/service/package_mock_test.go
  domain/machine/service/service.go
  domain/machine/service/service_test.go
  domain/machine/service/watcher.go
  domain/machine/service/watcher_test.go
  domain/machine/state/state.go
  domain/machine/watcher_test.go
  domain/schema/model.go
Labels: 4.0

#17798 feat(secrets): remove mongo secrets code
  apiserver/common/modelmanagerinterface.go
  apiserver/facades/agent/uniter/package_test.go
  apiserver/facades/agent/uniter/secrets.go
  apiserver/facades/agent/uniter/secrets_test.go
  apiserver/facades/agent/uniter/uniter_test.go
  apiserver/facades/client/secrets/secrets.go
  core/secrets/secret.go
  state/allcollections.go
  state/application.go
  state/application_test.go
  state/cleanup_test.go
  state/export_test.go
  state/migration_export.go
  state/migration_export_test.go
  state/migration_import.go
  state/migration_import_tasks.go
  state/migration_import_test.go
  state/migration_internal_test.go
  state/package_test.go
  state/relation.go
  state/relation_test.go
  state/remoteapplication.go
  state/remoteapplication_test.go
  state/secretbackends.go
  state/secretbackends_test.go
  state/secrets.go
  state/secrets_test.go
  state/state.go
  state/testing/watcher.go
  state/unit.go
  state/unit_test.go
Labels: 4.0

#17797 feat(secrets): secret migration plumbing
  domain/modelmigration/export.go
  domain/modelmigration/import.go
  domain/secret/errors/errors.go
  domain/secret/modelmigration/export.go
  domain/secret/modelmigration/export_test.go
  domain/secret/modelmigration/import.go
  domain/secret/modelmigration/import_test.go
  domain/secret/modelmigration/migrations_mock_test.go
  domain/secret/modelmigration/package_test.go
  domain/secret/service/exportimport.go
  domain/secret/service/params.go
  domain/secret/state/state.go
  domain/secretbackend/service/interface.go
  domain/secretbackend/service/service.go
  domain/secretbackend/service/service_test.go
  domain/secretbackend/service/state_mock_test.go
  domain/secretbackend/state/state.go
  domain/secretbackend/state/state_test.go
Labels: 4.0

#17796 feat: ensure core/arch package for charms
  core/arch/arches.go
  core/arch/arches_test.go
  core/base/package_test.go
  core/os/ostype/ostype.go
  core/os/ostype/ostype_test.go
  core/settings/package_test.go
  domain/application/errors/errors.go
  domain/application/service/charm.go
  domain/application/service/charm_test.go
  domain/application/service/manifest.go
  domain/application/service/manifest_test.go
  domain/application/watcher_test.go
  internal/charm/base.go
  internal/charm/base_test.go
  internal/charm/doc.go
  internal/charm/manifest.go
  internal/charm/url.go
Labels: 4.0

#17687 feat(apiserver): thin out Machiner api by replacing Jobs with IsController
  api/agent/machiner/machine.go
  api/facadeversions.go
  apiserver/facades/agent/machine/machiner.go
  apiserver/facades/agent/machine/machiner_test.go
  apiserver/facades/agent/machine/package_mock_test.go
  apiserver/facades/agent/machine/register.go
  apiserver/facades/schema.json
  domain/machine/service/package_mock_test.go
  domain/machine/service/service.go
  domain/machine/service/service_test.go
  domain/machine/state/state.go
  domain/machine/state/state_test.go
  internal/worker/stateconverter/converter.go
  internal/worker/stateconverter/converter_test.go
  internal/worker/stateconverter/interfaces.go
  internal/worker/stateconverter/mocks/machiner_mock.go
  rpc/params/params.go
Labels: 4.0

#17752 feat(access): check for everyone external in service
  apiserver/admin.go
  apiserver/admin_test.go
  apiserver/authentication/jwt/jwt.go
  apiserver/authentication/jwt/jwt_test.go
  apiserver/authentication/user.go
  apiserver/common/permissions.go
  apiserver/common/permissions_test.go
  apiserver/facades/client/applicationoffers/applicationoffers.go
  apiserver/facades/client/bundle/bundle.go
  apiserver/facades/client/cloud/cloud.go
  apiserver/facades/client/controller/controller.go
  apiserver/facades/client/controller/controller_test.go
  apiserver/facades/client/modelmanager/modelmanager.go
  apiserver/facades/client/usermanager/usermanager.go
  apiserver/facades/client/usermanager/usermanager_test.go
  apiserver/macaroon_test.go
  apiserver/registration.go
  apiserver/stateauthenticator/auth.go
  apiserver/stateauthenticator/context.go
  apiserver/stateauthenticator/delegator.go
  apiserver/stateauthenticator/services_mock_test.go
  core/credential/credential.go
  core/permission/access.go
  core/permission/access_test.go
  core/permission/user.go
  domain/access/bootstrap/bootstrap.go
  domain/access/bootstrap/bootstrap_test.go
  domain/access/service/permission.go
  domain/access/service/service.go
  domain/access/service/state_mock_test.go
  domain/access/service/user.go
  domain/access/service/user_test.go
  domain/access/state/permission.go
  domain/access/state/permission_test.go
  domain/access/state/types.go
  domain/access/state/user.go
  domain/access/state/user_test.go
  domain/access/types.go
  domain/cloud/state/state_test.go
  domain/credential/bootstrap/bootstrap_test.go
  domain/credential/state/state_test.go
  domain/model/bootstrap/bootstrap_test.go
  domain/model/state/state_test.go
  domain/model/state/testing/model.go
  domain/modelconfig/bootstrap/bootstrap_test.go
  domain/modelconfig/modelconfig_test.go
  domain/schema/controller/sql/0015-user.sql
  domain/schema/controller/sql/0017-user-permission.sql
  domain/schema/schema_test.go
  domain/secretbackend/state/state_test.go
  internal/worker/httpserverargs/authenticator.go
  internal/worker/httpserverargs/services_mock_test.go
  internal/worker/httpserverargs/worker.go
  juju/testing/macaroonsuite.go
  state/useraccess.go
Labels: 4.0

#17759 feat(machine): add parental services for machines
  domain/blockdevice/state/state.go
  domain/keyupdater/service/service_test.go
  domain/keyupdater/state/state.go
  domain/keyupdater/state/state_test.go
  domain/machine/errors/errors.go
  domain/machine/service/package_mock_test.go
  domain/machine/service/service.go
  domain/machine/service/service_test.go
  domain/machine/state/reboot.go
  domain/machine/state/state.go
  domain/machine/state/state_test.go
  domain/machine/state/types.go
Labels: 4.0

#17808 fix: idempotent binary storage
  state/binarystorage/binarystorage.go
  state/binarystorage/binarystorage_test.go
Labels: 4.0

#17767 feat(machine): add AllMachineRemovals on machine service
  domain/machine/service/package_mock_test.go
  domain/machine/service/service.go
  domain/machine/service/service_test.go
  domain/machine/state/state.go
  domain/machine/state/state_test.go
  domain/machine/state/types.go
  domain/schema/model/sql/0017-machine.sql
  domain/schema/schema_test.go
Labels: 4.0

#17743 refactor(apiserver): move application and charm packages to model services
  apiserver/facades/client/application/application.go
  apiserver/facades/client/application/application_test.go
  apiserver/facades/client/application/application_unit_test.go
  apiserver/facades/client/application/backend.go
  apiserver/facades/client/application/deploy.go
  apiserver/facades/client/application/deploy_test.go
  apiserver/facades/client/application/deployrepository.go
  apiserver/facades/client/application/deployrepository_mocks_test.go
  apiserver/facades/client/application/deployrepository_test.go
  apiserver/facades/client/application/get_test.go
  apiserver/facades/client/application/mocks/application_mock.go
  apiserver/facades/client/application/package_test.go
  apiserver/facades/client/application/service.go
  apiserver/facades/client/application/service_mock_test.go
  apiserver/facades/client/application/storage.go
  apiserver/facades/client/charms/client.go
  apiserver/facades/client/charms/client_test.go
  apiserver/facades/client/charms/export_test.go
  apiserver/facades/client/charms/interfaces/state.go
  apiserver/facades/client/charms/mocks/state_mock.go
  apiserver/facades/client/charms/package_test.go
  apiserver/facades/client/charms/register.go
  apiserver/facades/client/charms/service.go
  apiserver/facades/client/charms/service_mock_test.go
  apiserver/facades/controller/charmdownloader/charmdownloader.go
  apiserver/facades/controller/charmdownloader/charmdownloader_test.go
  apiserver/facades/controller/charmdownloader/interfaces.go
  apiserver/facades/controller/charmdownloader/mocks/mocks.go
  apiserver/facades/controller/charmdownloader/package_test.go
  apiserver/facades/controller/charmdownloader/register.go
  apiserver/facades/controller/charmdownloader/service.go
  apiserver/facades/controller/charmdownloader/service_mock_test.go
  internal/bootstrap/bootstrap_mock_test.go
  internal/bootstrap/deployer.go
  internal/bootstrap/deployer_test.go
  internal/bootstrap/package_test.go
  internal/bootstrap/service.go
  internal/charm/services/downloader.go
  internal/charm/services/interface_mocks_test.go
  internal/charm/services/interfaces.go
  internal/charm/services/package_test.go
  internal/charm/services/repofactory.go
  internal/charm/services/repofactory_test.go
  internal/charm/services/service.go
  internal/charm/services/service_mock_test.go
  internal/worker/apiserver/worker_state_test.go
  internal/worker/bootstrap/bootstrap_mock_test.go
  internal/worker/bootstrap/deployer.go
  internal/worker/bootstrap/manifold.go
  internal/worker/bootstrap/package_test.go
  internal/worker/bootstrap/service.go
  internal/worker/bootstrap/worker.go
  internal/worker/bootstrap/worker_test.go
  tests/suites/charmhub/download.sh
Labels: 4.0

#17824 refactor: image metadata facade to dqlite
  apiserver/facades/client/imagemetadatamanager/export_test.go
  apiserver/facades/client/imagemetadatamanager/metadata.go
  apiserver/facades/client/imagemetadatamanager/metadata_test.go
  apiserver/facades/client/imagemetadatamanager/package_test.go
  apiserver/facades/client/imagemetadatamanager/register.go
  apiserver/facades/client/imagemetadatamanager/service.go
  apiserver/facades/client/imagemetadatamanager/service_mock_test.go
  apiserver/facades/client/imagemetadatamanager/state.go
Labels: 4.0

#17825 chore: bump to version 3.1.10
  scripts/win-installer/setup.iss
  snap/snapcraft.yaml
  version/version.go
Labels: 3.1

#17826 chore: bump to version 3.4.6
  scripts/win-installer/setup.iss
  snap/snapcraft.yaml
  version/version.go
Labels: 3.4

#17827 chore: bump to version 3.5.4
  scripts/win-installer/setup.iss
  snap/snapcraft.yaml
  version/version.go
Labels: 3.5

#17832 chore: remove autocert collection from allcollections
  state/allcollections.go
  state/migration_internal_test.go
Labels: 4.0

#17829 chore: fix mocks setup on spaces facade tests
  apiserver/facades/client/spaces/spaces_test.go
Labels: 4.0

#17831 chore: fix mocks setup on machine facade tests
  apiserver/facades/agent/machine/machiner_test.go
Labels: 4.0

#17820 feat: export charm metadata and manifest
  api/controller/migrationmaster/client.go
  api/controller/migrationmaster/client_test.go
  api/controller/migrationtarget/client.go
  api/controller/migrationtarget/client_test.go
  apiserver/common/modelmanagerinterface.go
  apiserver/facades/client/bundle/bundle.go
  apiserver/facades/client/bundle/bundle_test.go
  apiserver/facades/client/bundle/mock_test.go
  apiserver/facades/client/bundle/state.go
  apiserver/facades/client/modelmanager/modelinfo_test.go
  apiserver/facades/client/modelmanager/modelmanager.go
  apiserver/facades/controller/migrationmaster/facade.go
  apiserver/facades/controller/migrationmaster/facade_test.go
  apiserver/facades/controller/migrationmaster/mocks/backend.go
  apiserver/facades/controller/migrationtarget/migrationtarget_test.go
  core/migration/migration.go
  go.mod
  go.sum
  migration/migration.go
  migration/migration_test.go
  state/export_test.go
  state/migration_description_mock_test.go
  state/migration_export.go
  state/migration_export_test.go
  state/migration_import.go
  state/migration_import_input_mock_test.go
  state/migration_import_mock_test.go
  state/migration_import_tasks.go
  state/migration_import_tasks_test.go
  state/migration_import_test.go
  state/migrations/description_mock_test.go
  state/migrations/externalcontroller_mock_test.go
  state/migrations/externalcontrollers.go
  state/migrations/externalcontrollers_test.go
  state/migrations/firewallrules.go
  state/migrations/firewallrules_mock_test.go
  state/migrations/firewallrules_test.go
  state/migrations/offerconnections.go
  state/migrations/offerconnections_test.go
  state/migrations/offerconntections_mock_test.go
  state/migrations/package_test.go
  state/migrations/relationetworks_mock_test.go
  state/migrations/relationnetworks.go
  state/migrations/relationnetworks_test.go
  state/migrations/remoteapplications.go
  state/migrations/remoteapplications_mock_test.go
  state/migrations/remoteapplications_test.go
  state/migrations/remoteentities.go
  state/migrations/remoteentities_mock_test.go
  state/migrations/remoteentities_test.go
  state/mocks/description_mock.go
  state/package_test.go
  worker/migrationmaster/worker_test.go
Labels: 3.6

#17819 feat: remove GetPermission and update UserAccessFunc
  apiserver/admin.go
  apiserver/apiserver.go
  apiserver/authentication/interfaces.go
  apiserver/authentication/jwt/jwt.go
  apiserver/authentication/jwt/jwt_test.go
  apiserver/common/crossmodel/auth.go
  apiserver/common/crossmodel/auth_test.go
  apiserver/common/crossmodel/interface.go
  apiserver/common/crossmodel/mock_test.go
  apiserver/common/crossmodel/mocks/crossmodel_mock.go
  apiserver/common/crossmodel/package_test.go
  apiserver/common/permissions.go
  apiserver/common/permissions_test.go
  apiserver/export_test.go
  apiserver/facades/client/applicationoffers/access_test.go
  apiserver/facades/client/applicationoffers/applicationoffers_test.go
  apiserver/facades/client/applicationoffers/mock_test.go
  apiserver/facades/client/usermanager/domain_mock_test.go
  apiserver/facades/client/usermanager/usermanager.go
  apiserver/facades/client/usermanager/usermanager_test.go
  apiserver/facades/controller/crossmodelrelations/crossmodelrelations_test.go
  apiserver/facades/controller/crossmodelsecrets/crossmodelsecrets_test.go
  apiserver/facades/controller/remoterelations/mocks/remoterelations_mocks.go
  apiserver/httpcontext.go
  apiserver/introspection.go
  apiserver/offerauth.go
  apiserver/root.go
  apiserver/service.go
  apiserver/stateauthenticator/delegator.go
  domain/access/service/service.go
  domain/access/state/permission.go
Labels: 4.0

#17790 docs: categorised --config keys for bootstrap
  cmd/juju/commands/bootstrap.go
  cmd/juju/controller/config.go
  cmd/juju/model/config.go
Labels: 3.5

#17606 fix: federated auth with stream connectors
  api/apiclient.go
  api/clientcredentialsloginprovider.go
  api/clientcredentialsloginprovider_test.go
  api/httpclient.go
  api/interface.go
  api/legacyloginprovider.go
  api/legacyloginprovider_test.go
  api/sessiontokenloginprovider.go
  api/sessiontokenloginprovider_test.go
  api/state.go
  cmd/internal/loginprovider/tryinorderloginprovider.go
  cmd/internal/loginprovider/tryinorderloginprovider_test.go
  cmd/juju/controller/register.go
  cmd/juju/user/login.go
Labels: 3.5

#17838 3.6 into main
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/charm.go
  internal/storage/provider/common.go
  internal/storage/provider/common_test.go
  state/assign_test.go
  state/migration_export.go
  state/migration_export_test.go
  state/migration_import_test.go
  state/unit.go
  testcharms/charms/pebble-checks/requirements.txt
  testcharms/charms/pebble-checks/src/charm.py
  testcharms/charms/pebble-checks/tests/unit/test_charm.py
  testcharms/charms/pebble-notices/pyproject.toml
  testcharms/charms/pebble-notices/requirements.txt
  testcharms/charms/pebble-notices/tox.ini
Labels: 4.0

#17795 chore(doc): move command docs from legacy /doc to cmd/doc.go
  cmd/doc.go
  doc/commands.txt
Labels: 4.0

#17837 chore(ports): removed unused methods
  apiserver/facades/agent/uniter/uniter_network_test.go
  apiserver/facades/agent/uniter/uniter_test.go
  apiserver/facades/client/application/mocks/state_mock.go
  state/application_ports.go
  state/application_test.go
  state/machine_ports.go
  state/machine_ports_test.go
  state/machine_test.go
  state/migration_import_test.go
  state/mocks/application_ports_mock.go
  state/package_test.go
  state/unit_machine_ports.go
  state/unit_ports.go
  state/unit_test.go
Labels: 4.0

#17840 feat(azure): cleanup auto managed identities
  go.mod
  go.sum
  provider/azure/clients.go
  provider/azure/environ.go
  provider/azure/environ_test.go
Labels: 3.6
