Repository juju/juju, pull requests merged in 2024-06, with the labels that each got.

#17332 Add model last login to domain
  apiserver/admin_test.go
  apiserver/facades/client/controller/controller.go
  apiserver/facades/client/controller/controller_test.go
  apiserver/facades/client/controller/mocks/domain_mock.go
  apiserver/facades/client/modelmanager/listmodelsummaries_test.go
  apiserver/facades/client/modelmanager/mocks/service_mock.go
  apiserver/facades/client/modelmanager/modelmanager.go
  apiserver/facades/client/modelmanager/modelmanager_test.go
  apiserver/facades/client/modelmanager/services.go
  apiserver/stateauthenticator/auth.go
  apiserver/stateauthenticator/context.go
  apiserver/stateauthenticator/services_mock_test.go
  domain/access/errors/errors.go
  domain/access/service/service.go
  domain/access/service/state_mock_test.go
  domain/access/service/user.go
  domain/access/service/user_test.go
  domain/access/state/permission.go
  domain/access/state/types.go
  domain/access/state/user.go
  domain/access/state/user_test.go
  domain/model/state/testing/model.go
  domain/schema/controller/sql/0015-user.sql
  domain/schema/controller/sql/0019-model-last-login.sql
  domain/schema/schema_test.go
  internal/worker/httpserverargs/authenticator.go
  internal/worker/httpserverargs/services_mock_test.go
  internal/worker/httpserverargs/worker.go
Labels: 4.0

#17421 Change proxyupdater to use model config service
  apiserver/facades/agent/proxyupdater/package_test.go
  apiserver/facades/agent/proxyupdater/proxyupdater.go
  apiserver/facades/agent/proxyupdater/proxyupdater_test.go
  apiserver/facades/agent/proxyupdater/service.go
  apiserver/facades/agent/proxyupdater/service_mock_test.go
Labels: 4.0

#17460 [JUJU-6025] - Remove CTEs with JOINs;
  domain/secret/state/state.go
Labels: go, 4.0

#17391 Model id creation in service layer
  .github/CODEOWNERS
  agent/agentbootstrap/bootstrap.go
  apiserver/facades/client/modelmanager/mocks/service_mock.go
  apiserver/facades/client/modelmanager/modelmanager.go
  apiserver/facades/client/modelmanager/modelmanager_test.go
  apiserver/facades/client/modelmanager/services.go
  domain/cloud/state/state_test.go
  domain/model/bootstrap/bootstrap.go
  domain/model/bootstrap/bootstrap_test.go
  domain/model/errors/errors.go
  domain/model/modelmigration/import.go
  domain/model/modelmigration/import_test.go
  domain/model/modelmigration/migrations_mock_test.go
  domain/model/service/service.go
  domain/model/service/service_test.go
  domain/model/service/state_test.go
  domain/model/state/state.go
  domain/model/state/state_test.go
  domain/model/state/testing/model.go
  domain/model/types.go
  domain/model/types_test.go
  domain/modelconfig/bootstrap/bootstrap_test.go
  domain/modelconfig/modelconfig_test.go
  domain/modelconfig/service/service.go
  domain/secretbackend/state/state_test.go
  domain/servicefactory/testing/suite.go
Labels: 4.0

#17466 Asserts controller config defaults to model.
  agent/agentbootstrap/bootstrap.go
  domain/modeldefaults/bootstrap/bootstrap.go
  domain/modeldefaults/bootstrap/bootstrap_test.go
  domain/modeldefaults/state/state.go
  domain/servicefactory/testing/suite.go
Labels: 4.0

#17144 Allow multiple constraints flag
  cmd/juju/application/deploy.go
  cmd/juju/application/deploy_test.go
  cmd/juju/commands/bootstrap.go
  cmd/juju/commands/bootstrap_test.go
  cmd/juju/commands/enableha.go
  cmd/juju/commands/enableha_test.go
  cmd/juju/common/flags.go
  cmd/juju/machine/add.go
  cmd/juju/machine/add_test.go
Labels: 3.6

#17459 Add cloud type to model information
  core/model/model.go
  core/model/readonlymodel.go
  domain/model/service/modelservice.go
  domain/model/service/modelservice_test.go
  domain/model/state/modelstate.go
  domain/model/state/modelstate_test.go
  domain/model/state/state.go
  domain/model/state/state_test.go
  domain/model/types.go
  domain/modelconfig/state/state_test.go
  domain/modeldefaults/state/state.go
  domain/modeldefaults/state/state_test.go
  domain/schema/model/sql/0003-read-only-model.sql
  domain/schema/schema_test.go
  domain/secret/state/state_test.go
  domain/secret/watcher_test.go
Labels: 4.0

#17445 Remove UbuntuVersions function
  apiserver/facades/client/modelupgrader/mocks/state_mock.go
  apiserver/facades/client/modelupgrader/shims.go
  apiserver/facades/client/modelupgrader/upgrader_test.go
  apiserver/facades/controller/migrationmaster/mocks/precheckbackend.go
  core/base/supportedbases.go
  core/base/supportedseries_test.go
  internal/migration/interface.go
  internal/migration/precheck_test.go
  internal/provider/oci/images.go
  internal/upgrades/upgradevalidation/interfaces.go
  internal/upgrades/upgradevalidation/migrate_test.go
  internal/upgrades/upgradevalidation/mocks/state_mock.go
  internal/upgrades/upgradevalidation/upgrade_test.go
  internal/upgrades/upgradevalidation/validation.go
  internal/upgrades/upgradevalidation/validation_test.go
  state/assign_test.go
  state/state.go
  state/state_test.go
Labels: 4.0

#17437 Complete machine schema DDL
  domain/schema/model/sql/0008-network.sql
  domain/schema/model/sql/0017-constraint.sql
  domain/schema/model/sql/0018-machine.sql
  domain/schema/schema_test.go
  internal/worker/dbaccessor/deletedb.go
Labels: 4.0

#17179 Remove supported containers check at agent for machine startup
  cmd/jujud/agent/machine.go
  container/utils.go
  container/utils_test.go
  core/bundle/changes/changes.go
  worker/containerbroker/broker.go
  worker/containerbroker/broker_test.go
Labels: bug, 3.4

#17464 Ensure relation-ids excludes ids for broken relations
  cmd/juju/commands/helptool_test.go
  worker/uniter/runner/context/context.go
  worker/uniter/runner/context/context_test.go
  worker/uniter/runner/context/contextfactory.go
  worker/uniter/runner/context/contextfactory_test.go
  worker/uniter/runner/context/export_test.go
  worker/uniter/runner/context/relation.go
  worker/uniter/runner/context/relation_test.go
  worker/uniter/runner/context/util_test.go
  worker/uniter/runner/jujuc/relation-ids.go
  worker/uniter/runner/jujuc/relation-ids_test.go
Labels: 3.4

#17472 Feat(migration): Add `Name` method to model migration operations
  core/modelmigration/coordinator.go
  core/modelmigration/coordinator_test.go
  core/modelmigration/op_mock_test.go
  core/modelmigration/package_test.go
  domain/application/modelmigration/import.go
  domain/blockdevice/modelmigration/export.go
  domain/blockdevice/modelmigration/import.go
  domain/credential/modelmigration/export.go
  domain/credential/modelmigration/import.go
  domain/externalcontroller/modelmigration/export.go
  domain/externalcontroller/modelmigration/import.go
  domain/lease/modelmigration/import.go
  domain/machine/modelmigration/import.go
  domain/model/modelmigration/import.go
  domain/model/modelmigration/import_test.go
  domain/modelconfig/modelmigration/export.go
  domain/modelconfig/modelmigration/import.go
  domain/network/modelmigration/export.go
  domain/network/modelmigration/import.go
  domain/storage/modelmigration/export.go
  domain/storage/modelmigration/import.go
  internal/migration/migration.go
Labels: 4.0

#17452 Improve error message for juju register when controller is inaccesible
  cmd/juju/controller/register.go
  cmd/juju/controller/register_test.go
Labels: 3.4

#17473 Return a non-empty network topology when only alpha space has been explicitly set as constraint.
  apiserver/facades/agent/provisioner/provisioninginfo.go
  apiserver/facades/agent/provisioner/provisioninginfo_test.go
Labels: bug, 3.4

#17479 3.6 into main
  .github/workflows/cla.yml
  caas/kubernetes/provider/application/application.go
  caas/kubernetes/provider/application/application_test.go
  cmd/juju/application/deploy.go
  cmd/juju/application/deploy_test.go
  cmd/juju/cloud/addcredential.go
  cmd/juju/cloud/addcredential_test.go
  cmd/juju/commands/bootstrap.go
  cmd/juju/commands/bootstrap_test.go
  cmd/juju/commands/enableha.go
  cmd/juju/commands/enableha_test.go
  cmd/juju/commands/helptool_test.go
  cmd/juju/common/flags.go
  cmd/juju/machine/add.go
  cmd/juju/machine/add_test.go
  cmd/jujud-controller/agent/machine.go
  cmd/jujud/agent/machine.go
  core/base/base.go
  core/base/base_test.go
  go.mod
  go.sum
  internal/bundle/changes/changes.go
  internal/container/utils.go
  internal/container/utils_test.go
  internal/provider/azure/instancetype.go
  internal/provider/azure/internal/errorutils/errors_test.go
  internal/provider/azure/internal/imageutils/images.go
  internal/provider/azure/internal/imageutils/images_test.go
  internal/provider/gce/credentials.go
  internal/worker/containerbroker/broker.go
  internal/worker/containerbroker/broker_test.go
  internal/worker/externalcontrollerupdater/externalcontrollerupdater.go
  internal/worker/uniter/runner/context/context.go
  internal/worker/uniter/runner/context/context_test.go
  internal/worker/uniter/runner/context/contextfactory.go
  internal/worker/uniter/runner/context/contextfactory_test.go
  internal/worker/uniter/runner/context/export_test.go
  internal/worker/uniter/runner/context/relation.go
  internal/worker/uniter/runner/context/relation_test.go
  internal/worker/uniter/runner/context/util_test.go
  internal/worker/uniter/runner/jujuc/relation-ids.go
  internal/worker/uniter/runner/jujuc/relation-ids_test.go
  internal/worker/uniter/runner/util_test.go
  scripts/find-bad-doc-comments.py
  scripts/leadershipclaimer/count-leadership.py
  state/secrets.go
  state/secrets_test.go
  tests/includes/juju.sh
  tests/main.sh
  tests/suites/backup/backup.sh
  tests/suites/cli/model_defaults.sh
  tests/suites/constraints/constraints.sh
  tests/suites/deploy/deploy_bundles.sh
  tests/suites/deploy/deploy_charms.sh
  tests/suites/manual/deploy_manual.sh
  tests/suites/manual/spaces.sh
Labels: 4.0

#17468 Introduces helper for getting controller model.
  domain/model/service/service.go
  domain/model/service/service_test.go
  domain/model/service/state_test.go
  domain/model/state/state.go
  domain/model/state/state_test.go
Labels: 4.0

#17456 Hardcode GetSeriesFromBase, ControllerBases & WorkloadBases
  apiserver/facades/client/application/deployrepository.go
  apiserver/facades/client/machinemanager/machinemanager_test.go
  apiserver/facades/client/modelupgrader/upgrader_test.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/bundlehandler_test.go
  cmd/juju/application/deployer/deployer.go
  cmd/juju/commands/bootstrap.go
  cmd/juju/commands/bootstrap_test.go
  cmd/jujud-controller/agent/bootstrap_test.go
  core/base/distrosource_mock_test.go
  core/base/package_test.go
  core/base/series.go
  core/base/series_test.go
  core/base/supported.go
  core/base/supported_test.go
  core/base/supportedbases.go
  core/base/supportedbases_test.go
  core/base/supportedseries.go
  core/base/supportedseries_linux_test.go
  core/base/supportedseries_test.go
  environs/bootstrap/bootstrap_test.go
  environs/bootstrap/tools_test.go
  environs/config/config.go
  environs/imagedownloads/simplestreams.go
  environs/imagedownloads/simplestreams_test.go
  environs/imagemetadata/generate_test.go
  environs/imagemetadata/simplestreams.go
  environs/sync/sync_test.go
  environs/tools/simplestreams_test.go
  environs/tools/tools.go
  environs/tools/tools_test.go
  internal/migration/precheck_test.go
  internal/provider/maas/environ.go
  internal/provider/openstack/local_test.go
  internal/upgrades/preupgradesteps.go
  internal/upgrades/preupgradesteps_test.go
  internal/upgrades/upgradevalidation/migrate_test.go
  internal/upgrades/upgradevalidation/upgrade_test.go
  internal/upgrades/upgradevalidation/validation.go
  internal/upgrades/upgradevalidation/validation_test.go
Labels: 4.0

#17483 fix: distro-info upgrade getting stuck
  container/lxd/initialisation_test.go
  go.mod
  go.sum
Labels: 3.5

#17482 fix: distro-info upgrade getting stuck
  container/lxd/initialisation_test.go
  go.mod
  go.sum
Labels: 3.4

#17475 Move retrystrategy facade to model config service
  apiserver/facades/agent/retrystrategy/export_test.go
  apiserver/facades/agent/retrystrategy/package_test.go
  apiserver/facades/agent/retrystrategy/register.go
  apiserver/facades/agent/retrystrategy/retrystrategy.go
  apiserver/facades/agent/retrystrategy/retrystrategy_test.go
  apiserver/facades/agent/retrystrategy/service.go
  apiserver/facades/agent/retrystrategy/service_mock_test.go
  go.mod
  go.sum
  internal/worker/uniter/uniter.go
Labels: 4.0

#17491 fix: panic: InsecureKeyProfile cannot be used outside tests
  Makefile
  core/watcher/todo.go
  core/watcher/todo_test.go
  core/watcher/watchertest/strings.go
  domain/secret/service/watcher.go
  testing/notest.go
Labels: 4.0

#17493 chore: merge 3.5 into 3.6
  agent/agentbootstrap/bootstrap.go
  agent/agentbootstrap/bootstrap_test.go
  apiserver/facades/agent/provisioner/provisioninginfo.go
  apiserver/facades/agent/provisioner/provisioninginfo_test.go
  cmd/juju/controller/register.go
  cmd/juju/controller/register_test.go
  container/lxd/initialisation_test.go
  go.mod
  go.sum
  tests/suites/manual/deploy_manual.sh
  tests/suites/manual/util.sh
Labels: 3.6

#17496 fix: model migration due to zero agent version
  domain/model/modelmigration/import.go
  domain/model/modelmigration/import_test.go
Labels: 4.0

#17449 Lint SQL files
  .github/.sqlfluff
  .github/workflows/static-analysis.yml
  domain/schema/controller/sql/0001-life.sql
  domain/schema/controller/sql/0002-lease.sql
  domain/schema/controller/sql/0003-changelog.sql
  domain/schema/controller/sql/0004-changelog-namespaces.sql
  domain/schema/controller/sql/0005-cloud.sql
  domain/schema/controller/sql/0006-external-controller.sql
  domain/schema/controller/sql/0007-model.sql
  domain/schema/controller/sql/0008-model-agent.sql
  domain/schema/controller/sql/0009-controller-config.sql
  domain/schema/controller/sql/0010-controller-node.sql
  domain/schema/controller/sql/0011-model-migration.sql
  domain/schema/controller/sql/0012-uprade-info.sql
  domain/schema/controller/sql/0013-autocert-cache.sql
  domain/schema/controller/sql/0014-objectstore-metadata.sql
  domain/schema/controller/sql/0015-user.sql
  domain/schema/controller/sql/0017-user-permission.sql
  domain/schema/controller/sql/0018-secret-backend.sql
  domain/schema/controller/sql/0019-model-last-login.sql
  domain/schema/model/sql/0000-life.sql
  domain/schema/model/sql/0001-changelog.sql
  domain/schema/model/sql/0002-changelog-namespaces.sql
  domain/schema/model/sql/0003-read-only-model.sql
  domain/schema/model/sql/0004-model-config.sql
  domain/schema/model/sql/0005-objectstore-metadata.sql
  domain/schema/model/sql/0006-application.sql
  domain/schema/model/sql/0007-charm.sql
  domain/schema/model/sql/0008-network.sql
  domain/schema/model/sql/0009-unit.sql
  domain/schema/model/sql/0010-space.sql
  domain/schema/model/sql/0011-subnet.sql
  domain/schema/model/sql/0012-blockdevice.sql
  domain/schema/model/sql/0013-storage.sql
  domain/schema/model/sql/0014-secret.sql
  domain/schema/model/sql/0015-annotations.sql
  domain/schema/model/sql/0016-instance-data.sql
  domain/schema/model/sql/0017-constraint.sql
  domain/schema/model/sql/0018-machine.sql
  internal/worker/dbaccessor/doc.go
  scripts/find-bad-doc-comments.py
  scripts/leadershipclaimer/count-leadership.py
Labels: 4.0

#17484 fix: leadership tracker worker killed by uniter
  worker/uniter/uniter.go
Labels: 3.4

#17494 Merge 3.6 into main
  agent/agentbootstrap/bootstrap_test.go
  apiserver/facades/agent/provisioner/provisioninginfo.go
  apiserver/facades/agent/provisioner/provisioninginfo_test.go
  cmd/juju/controller/register.go
  cmd/juju/controller/register_test.go
  tests/suites/manual/util.sh
Labels: 4.0

#17495 fix(migration): Return ErrDBNotFound for not found namespace
  core/database/dbmanager.go
  domain/model/modelmigration/import.go
  domain/model/modelmigration/import_test.go
  domain/model/service/service.go
  domain/model/service/service_test.go
  domain/model/state/modelstate.go
  internal/worker/changestream/worker.go
  internal/worker/changestream/worker_test.go
  internal/worker/dbaccessor/worker.go
  internal/worker/dbaccessor/worker_integration_test.go
  internal/worker/dbaccessor/worker_namespace_test.go
Labels: 4.0

#17430 Charm schema
  apiserver/facades/client/annotations/client_test.go
  domain/annotation/state/query.go
  domain/annotation/state/state.go
  domain/annotation/state/state_test.go
  domain/schema/model/sql/0007-charm.sql
  domain/schema/schema_test.go
Labels: 4.0

#17508 feat(charm): Charm SQL DDL Schema
  domain/schema/model/sql/0007-charm.sql
  domain/schema/schema_test.go
Labels: 4.0

#17509 fix(migrate): Migrate from 3.6/edge -> 4.0
  .github/workflows/migrate.yml
Labels: 4.0

#17497 fix(offer): improve error message when updating offers with removed endpoints
  apiserver/facades/client/client/api_test.go
  cmd/juju/ssh/debughooks_test.go
  cmd/juju/status/status_internal_test.go
  state/application_test.go
  state/applicationoffers.go
  state/applicationoffers_test.go
  testcharms/charm-repo/quantal/mysql/metadata.yaml
Labels: bug, 3.4

#17510 fix(db): Dqlite HA: too many colons in address
  database/node.go
  database/node_test.go
Labels: 3.4

#17514 feat(application): Application DDL schema
  domain/schema/controller/sql/0000-namespace.sql
  domain/schema/controller/sql/0002-lease.sql
  domain/schema/controller/sql/0003-changelog.sql
  domain/schema/controller/sql/0005-cloud.sql
  domain/schema/controller/sql/0006-external-controller.sql
  domain/schema/controller/sql/0007-model.sql
  domain/schema/controller/sql/0008-model-agent.sql
  domain/schema/controller/sql/0009-controller-config.sql
  domain/schema/controller/sql/0010-controller-node.sql
  domain/schema/controller/sql/0011-model-migration.sql
  domain/schema/controller/sql/0012-uprade-info.sql
  domain/schema/controller/sql/0013-autocert-cache.sql
  domain/schema/controller/sql/0014-objectstore-metadata.sql
  domain/schema/controller/sql/0015-user.sql
  domain/schema/controller/sql/0016-flag.sql
  domain/schema/controller/sql/0017-user-permission.sql
  domain/schema/controller/sql/0018-secret-backend.sql
  domain/schema/model/sql/0001-changelog.sql
  domain/schema/model/sql/0003-password.sql
  domain/schema/model/sql/0004-read-only-model.sql
  domain/schema/model/sql/0005-model-config.sql
  domain/schema/model/sql/0006-application.sql
  domain/schema/model/sql/0006-objectstore-metadata.sql
  domain/schema/model/sql/0007-platform.sql
  domain/schema/model/sql/0008-space.sql
  domain/schema/model/sql/0009-subnet.sql
  domain/schema/model/sql/0010-blockdevice.sql
  domain/schema/model/sql/0011-storage.sql
  domain/schema/model/sql/0012-secret.sql
  domain/schema/model/sql/0013-annotations.sql
  domain/schema/model/sql/0014-constraint.sql
  domain/schema/model/sql/0015-charm.sql
  domain/schema/model/sql/0016-instance-data.sql
  domain/schema/model/sql/0017-machine.sql
  domain/schema/model/sql/0018-application.sql
  domain/schema/model/sql/0019-unit.sql
  domain/schema/model/sql/0020-network.sql
  domain/schema/schema_test.go
Labels: 4.0

#17490 Move storageprovisioner facade to use model config/info services
  apiserver/facades/agent/storageprovisioner/register.go
  apiserver/facades/agent/storageprovisioner/service.go
  apiserver/facades/agent/storageprovisioner/shim.go
  apiserver/facades/agent/storageprovisioner/storageprovisioner.go
  apiserver/facades/agent/storageprovisioner/storageprovisioner_caas_test.go
  apiserver/facades/agent/storageprovisioner/storageprovisioner_iaas_test.go
  apiserver/facades/agent/storageprovisioner/storageprovisioner_test.go
  tests/suites/storage/charm_storage.sh
  tests/suites/storage/persistent_storage.sh
Labels: 4.0

#17506 style(sqlair): use SQLair in autocert domain
  domain/autocert/doc.go
  domain/autocert/state/state.go
  domain/autocert/state/types.go
Labels: 4.0

#17520 build: fix dependabot.yml, target-branch is a string.
  .github/dependabot.yml
Labels: 3.6

#17485 fix: unit agent lost on migration success
  worker/migrationminion/manifold.go
  worker/migrationminion/worker.go
  worker/migrationminion/worker_test.go
Labels: 3.4

#17513 fix(upgrade): noble upgrade support
  apiserver/facades/client/modelupgrader/upgrader_test.go
  cmd/juju/application/deployer/bundlehandler_test.go
  cmd/juju/application/deployer/deployer.go
  core/base/supported.go
  core/base/supportedseries_linux_test.go
  core/charm/baseselector.go
  core/charm/baseselector_test.go
  provider/ec2/series_test.go
  testcharms/charm-hub/charms/juju-qa-test/charmcraft.yaml
  testing/environ.go
  upgrades/upgradevalidation/migrate_test.go
  upgrades/upgradevalidation/upgrade_test.go
  upgrades/upgradevalidation/validation_test.go
Labels: 3.4

#17523 refactor(deploy): Remove remaining series from 3.6 (except from compatibility code)
  cmd/juju/application/bundle_test.go
  cmd/juju/application/deploy.go
  cmd/juju/application/deploy_test.go
  cmd/juju/application/deployer/bundle.go
  cmd/juju/application/deployer/bundlehandler.go
  cmd/juju/application/deployer/bundlehandler_test.go
  cmd/juju/application/deployer/charm.go
  cmd/juju/application/deployer/deployer.go
  cmd/juju/application/deployer/deployer_test.go
  cmd/juju/application/deployer/interface.go
  cmd/juju/application/deployer/mocks/deploy_mock.go
  cmd/juju/application/deployer/mocks/deployer_mock.go
  cmd/juju/application/deployer/package_test.go
  cmd/juju/application/mocks/deployer_mock.go
  cmd/juju/application/refresh_test.go
  cmd/juju/application/refresher/interface.go
  cmd/juju/application/refresher/refresher.go
  cmd/juju/application/refresher/refresher_mock_test.go
  cmd/juju/application/refresher/refresher_test.go
  cmd/juju/application/unexpose_test.go
  core/charm/charmpath.go
  core/charm/charmpath_test.go
  core/charm/computedbase.go
  core/charm/repository/charmhub.go
  core/charm/repository/charmhub_test.go
  featuretests/client_macaroon_test.go
  testcharms/charm-repo/focal/mysql/actions.yaml
  testcharms/charm-repo/focal/mysql/config.yaml
  testcharms/charm-repo/focal/mysql/hooks/config-changed
  testcharms/charm-repo/focal/mysql/hooks/hooks
  testcharms/charm-repo/focal/mysql/hooks/install
  testcharms/charm-repo/focal/mysql/hooks/update-status
  testcharms/charm-repo/focal/mysql/icon.svg
  testcharms/charm-repo/focal/mysql/manifest.yaml
  testcharms/charm-repo/focal/mysql/metadata.yaml
  testcharms/charm-repo/focal/mysql/revision
  testcharms/charm-repo/focal/wordpress/actions.yaml
  testcharms/charm-repo/focal/wordpress/actions/.gitkeep
  testcharms/charm-repo/focal/wordpress/config.yaml
  testcharms/charm-repo/focal/wordpress/hooks/.gitkeep
  testcharms/charm-repo/focal/wordpress/metadata.yaml
  testcharms/charm-repo/focal/wordpress/revision
Labels: 3.6

#17515 feat(machine): add state layer for machine cloud instance
  domain/machine/state/machine_cloud_instance.go
  domain/machine/state/machine_cloud_instance_test.go
  domain/machine/state/types.go
  domain/schema/model/sql/0016-machine-cloud-instance.sql
  domain/schema/schema_test.go
Labels: 4.0

#17534 chore: merge 2.9 to 3.1
  go.mod
  go.sum
Labels: 3.1

#17517 chore: backport storage test changes to 3.6
  tests/suites/storage/charm_storage.sh
  tests/suites/storage/persistent_storage.sh
Labels: 3.6

#17522 style(sqlair): use SQLair in the flag domain
  domain/flag/doc.go
  domain/flag/state/state.go
  domain/flag/state/state_test.go
  domain/flag/state/types.go
Labels: 4.0

#17546 chore: remove last deployment type in charm
  internal/charm/meta.go
  rpc/params/charms.go
Labels: 4.0

#17519 refactor: use model config service in caasmodeloperator facade
  apiserver/facades/controller/caasmodeloperator/mock_test.go
  apiserver/facades/controller/caasmodeloperator/operator.go
  apiserver/facades/controller/caasmodeloperator/operator_test.go
  apiserver/facades/controller/caasmodeloperator/package_test.go
  apiserver/facades/controller/caasmodeloperator/register.go
  apiserver/facades/controller/caasmodeloperator/service.go
  apiserver/facades/controller/caasmodeloperator/service_mock_test.go
  apiserver/facades/controller/caasmodeloperator/state.go
Labels: 4.0

#17474 fix(waitfor): nil pointer exception in wait-for
  cmd/juju/waitfor/unit.go
  cmd/juju/waitfor/unit_test.go
Labels: 3.4

#17500 Service implementation of authorised keys.
  cmd/juju/sshkeys/remove_sshkeys.go
  core/user/user.go
  domain/keymanager/doc.go
  domain/keymanager/errors/errors.go
  domain/keymanager/service/package_test.go
  domain/keymanager/service/service.go
  domain/keymanager/service/service_mock_test.go
  domain/keymanager/service/service_test.go
  domain/keymanager/types.go
  internal/ssh/authorisedkey.go
  internal/ssh/importer/errors/errors.go
  internal/ssh/importer/github.go
  internal/ssh/importer/github_test.go
  internal/ssh/importer/importer.go
  internal/ssh/importer/importer_test.go
  internal/ssh/importer/launchpad.go
  internal/ssh/importer/launchpad_test.go
Labels: 4.0

#17547 chore: merge 3.6 to main
  .github/workflows/docs.yml
  apiserver/admin.go
  apiserver/facades/client/client/api_test.go
  core/charm/baseselector.go
  internal/database/node.go
  internal/database/node_test.go
  internal/provider/ec2/series_test.go
  internal/worker/migrationminion/manifold.go
  internal/worker/migrationminion/worker.go
  internal/worker/migrationminion/worker_test.go
  scripts/discourse-sync/client.py
  scripts/discourse-sync/main.py
  scripts/discourse-sync/requirements.txt
  state/application_test.go
  state/applicationoffers.go
  state/applicationoffers_test.go
  testcharms/charm-hub/charms/juju-qa-test/charmcraft.yaml
  testcharms/charm-repo/quantal/mysql/metadata.yaml
  testing/environ.go
Labels: 4.0

#17524 chore: remove unused methods from instancepoller facade
  api/controller/instancepoller/instancepoller.go
  api/controller/instancepoller/instancepoller_test.go
  apiserver/facades/controller/instancepoller/instancepoller.go
  apiserver/facades/controller/instancepoller/instancepoller_test.go
  apiserver/facades/controller/instancepoller/mock_test.go
  apiserver/facades/controller/instancepoller/package_mock_test.go
  apiserver/facades/controller/instancepoller/package_test.go
  apiserver/facades/controller/instancepoller/service.go
  apiserver/facades/controller/instancepoller/service_mock_test.go
  apiserver/facades/controller/instancepoller/state.go
  apiserver/facades/schema.json
Labels: 4.0

#17544 fix: surface custom controller charm error
  cmd/juju/commands/bootstrap.go
  cmd/juju/commands/bootstrap_test.go
Labels: 3.4

#17451 chore: move CLI specific login providers
  api/clientcredentialsloginprovider.go
  api/clientcredentialsloginprovider_test.go
  api/export_test.go
  api/interface.go
  api/userpass_login_provider.go
  cmd/internal/loginprovider/export_test.go
  cmd/internal/loginprovider/package_test.go
  cmd/internal/loginprovider/sessiontokenloginprovider.go
  cmd/internal/loginprovider/sessiontokenloginprovider_test.go
  cmd/internal/loginprovider/tryinorderloginprovider.go
  cmd/internal/loginprovider/tryinorderloginprovider_test.go
  cmd/juju/controller/register.go
  cmd/juju/user/login.go
  cmd/modelcmd/base.go
Labels: 3.5

#17521 style(sqlair): use SQLair in the externalcontroller domain.
  domain/externalcontroller/doc.go
  domain/externalcontroller/state/state.go
  domain/externalcontroller/state/types.go
Labels: 4.0

#17570 chore: commit message contributing guidelines
  CONTRIBUTING.md
Labels: 3.4

#17577 fix: handle case of ErrNoRows for GetAll
  domain/externalcontroller/state/state.go
  domain/externalcontroller/state/state_test.go
Labels: 4.0

#17433 chore: pass an io.Writer instead of a callback function for session token login
  cmd/internal/loginprovider/sessiontokenloginprovider.go
  cmd/internal/loginprovider/sessiontokenloginprovider_test.go
  cmd/juju/controller/register.go
  cmd/juju/user/login.go
  cmd/modelcmd/base.go
Labels: 3.5

#17572 fix(application): caas model application status to respect severity
  core/status/caas.go
  core/status/caas_test.go
Labels: 3.5

#17575 fix: race with add-model on same user with same model name
  state/allcollections.go
Labels: 3.4

#17536 style(sqlair): use SQLair in the objectstore domain
  domain/objectstore/doc.go
  domain/objectstore/service/service.go
  domain/objectstore/service/service_test.go
  domain/objectstore/service/state_mock_test.go
  domain/objectstore/state/state.go
  domain/objectstore/state/state_test.go
  domain/objectstore/state/types.go
Labels: 4.0

#17431 chore: add logging to tryInOrderLoginProviders Login method
  cmd/internal/loginprovider/tryinorderloginprovider.go
  cmd/internal/loginprovider/tryinorderloginprovider_test.go
  cmd/juju/controller/register.go
  cmd/juju/user/login.go
Labels: 3.5

#17487 Improve storage directive parsing
  cmd/juju/storage/add.go
  storage/constraints.go
  storage/constraints_test.go
Labels: 3.4

#17579 feat: remove initial model bootstrap arg
  agent/agentbootstrap/bootstrap.go
  agent/agentbootstrap/bootstrap_test.go
  caas/kubernetes/provider/bootstrap_test.go
  caas/kubernetes/provider/k8s.go
  cmd/juju/commands/bootstrap.go
  cmd/juju/commands/bootstrap_test.go
  cmd/jujud-controller/agent/bootstrap_test.go
  environs/bootstrap/bootstrap.go
  internal/cloudconfig/instancecfg/instancecfg.go
  internal/cloudconfig/podcfg/podcfg.go
  internal/cloudconfig/userdatacfg_test.go
  tests/includes/juju.sh
Labels: 4.0

#17554 feat(cli): Prevent controller-config command to set controller-name to empty string
  cmd/juju/commands/bootstrap.go
  controller/config.go
  controller/config_test.go
  controller/configschema.go
Labels: 3.4

#17580 feat(macaroons): Implement bakery config service
  apiserver/facades/controller/migrationtarget/servicefactory_mock_test.go
  domain/bakerystorage/service/config.go
  domain/bakerystorage/service/config_test.go
  domain/bakerystorage/service/package_mock_test.go
  domain/bakerystorage/service/package_test.go
  domain/bakerystorage/service/service.go
  domain/bakerystorage/state/config.go
  domain/bakerystorage/state/config_test.go
  domain/bakerystorage/state/errors.go
  domain/bakerystorage/state/package_test.go
  domain/bakerystorage/state/state.go
  domain/bakerystorage/state/types.go
  domain/schema/controller/sql/0020-bakery-storage.sql
  domain/schema/schema_test.go
  domain/servicefactory/controller.go
  domain/servicefactory/testing/service.go
  internal/migration/servicefactory_mock_test.go
  internal/servicefactory/interface.go
  internal/worker/bootstrap/bootstrap_mock_test.go
  internal/worker/bootstrap/manifold.go
  internal/worker/bootstrap/package_test.go
  internal/worker/bootstrap/worker.go
  internal/worker/bootstrap/worker_test.go
  internal/worker/peergrouper/controllerconfig_mock_test.go
  internal/worker/peergrouper/controllertracker_test.go
  internal/worker/peergrouper/desired_test.go
  internal/worker/peergrouper/manifold_test.go
  internal/worker/peergrouper/mock_test.go
  internal/worker/peergrouper/package_test.go
  internal/worker/peergrouper/publish_test.go
  internal/worker/peergrouper/service_mock_test.go
  internal/worker/peergrouper/worker_test.go
  internal/worker/servicefactory/servicefactory_mock_test.go
  internal/worker/upgradedatabase/servicefactory_mock_test.go
Labels: 4.0

#17558 feat(dqlite): Add WatchModelMachines on machine WatchableService
  apiserver/facades/agent/unitassigner/unitassigner.go
  apiserver/facades/agent/unitassigner/unitassigner_test.go
  apiserver/facades/client/application/deploy.go
  apiserver/facades/client/application/domain_mock.go
  apiserver/facades/client/highavailability/highavailability.go
  apiserver/facades/client/machinemanager/machinemanager.go
  apiserver/facades/client/machinemanager/package_mock_test.go
  apiserver/facades/controller/cleaner/cleaner_test.go
  apiserver/facades/controller/migrationtarget/servicefactory_mock_test.go
  domain/machine/modelmigration/import.go
  domain/machine/package_test.go
  domain/machine/service/package_mock_test.go
  domain/machine/service/service.go
  domain/machine/service/service_test.go
  domain/machine/service/watcher.go
  domain/machine/state/machine_cloud_instance_test.go
  domain/machine/state/state.go
  domain/machine/state/state_test.go
  domain/machine/watcher_test.go
  domain/schema/model.go
  domain/schema/model/sql/0002-changelog-namespaces.sql
  domain/schema/model/triggers/machine-triggers.gen.go
  domain/schema/schema_test.go
  domain/servicefactory/model.go
  domain/servicefactory/testing/service.go
  internal/migration/servicefactory_mock_test.go
  internal/servicefactory/interface.go
  internal/worker/servicefactory/servicefactory_mock_test.go
Labels: 4.0

#17582 feat(dqlite): add GetMachineLife in machine domain
  domain/machine/service/package_mock_test.go
  domain/machine/service/service.go
  domain/machine/service/service_test.go
  domain/machine/state/state.go
  domain/machine/state/state_test.go
  domain/machine/state/types.go
Labels: 4.0

#17505 refactor: move uniter facade to model config/info services
  apiserver/facades/agent/uniter/networkinfo.go
  apiserver/facades/agent/uniter/networkinfo_test.go
  apiserver/facades/agent/uniter/newlxdprofile.go
  apiserver/facades/agent/uniter/newlxdprofile_test.go
  apiserver/facades/agent/uniter/package_mocks_test.go
  apiserver/facades/agent/uniter/package_test.go
  apiserver/facades/agent/uniter/register.go
  apiserver/facades/agent/uniter/service.go
  apiserver/facades/agent/uniter/service_mock_test.go
  apiserver/facades/agent/uniter/uniter.go
  apiserver/facades/agent/uniter/uniter_apierror_test.go
  apiserver/facades/agent/uniter/uniter_cloudspec_test.go
  apiserver/facades/agent/uniter/uniter_network_test.go
  apiserver/facades/agent/uniter/uniter_test.go
Labels: 4.0

#17587 feat: add github action to ensure consistency
  .github/workflows/static-analysis.yml
  snap/snapcraft.yaml
Labels: 3.4

#17586 fix: ensure we release state
  apiserver/facades/client/controller/controller.go
  worker/auditconfigupdater/manifold.go
  worker/certupdater/manifold.go
  worker/controlsocket/manifold.go
  worker/httpserver/manifold.go
  worker/migrationmaster/worker.go
  worker/migrationmaster/worker_test.go
  worker/peergrouper/manifold.go
Labels: 3.4

#17584 docs(cmd): fix typos, phrasing, information flow in 'juju migrate' help details
  cmd/juju/commands/migrate.go
Labels: 3.4

#17596 fix: allow migration from 3.6
  domain/model/service/service.go
  domain/model/service/service_test.go
Labels: 4.0

#17590 docs(cmd): Updates remove ssh key docs.
  cmd/juju/sshkeys/remove_sshkeys.go
Labels: 4.0

#17589 test(bundle): delete subtest `run_deploy_lxd_profile_bundle_openstack`
  tests/suites/deploy/bundles/basic-openstack.yaml
  tests/suites/deploy/deploy_bundles.sh
Labels: 3.4

#17563 feat(azure): add support for managed identities
  cmd/juju/controller/kill.go
  environs/tags/tags.go
  environs/tags/tags_test.go
  go.mod
  go.sum
  provider/azure/cloud.go
  provider/azure/cloud_test.go
  provider/azure/credentials.go
  provider/azure/credentials_test.go
  provider/azure/deployments.go
  provider/azure/environ.go
  provider/azure/environ_identity_test.go
  provider/azure/environ_test.go
  provider/azure/environprovider.go
  provider/azure/identity.go
  provider/azure/identity_test.go
  provider/azure/internal/armtemplates/template.go
  tests/includes/ha.sh
  tests/main.sh
  tests/suites/cloud_azure/managed_identity.sh
  tests/suites/cloud_azure/task.sh
  tests/suites/controller/enable_ha.sh
Labels: 3.6

#17592 feat(dqlite): Implement NamespaceNotifyWatcher;
  core/watcher/eventsource/value.go
  core/watcher/eventsource/value_test.go
  domain/watcher.go
  domain/watcher_test.go
Labels: 4.0

#17588 feat(macaroons): wire up bakery config service
  apiserver/apiserver.go
  apiserver/common/crossmodel/auth.go
  apiserver/common/crossmodel/auth_test.go
  apiserver/common/crossmodel/bakery.go
  apiserver/common/crossmodel/bakery_test.go
  apiserver/common/crossmodel/interface.go
  apiserver/common/crossmodel/mocks/bakerystorage_mock.go
  apiserver/common/crossmodel/mocks/crossmodel_mock.go
  apiserver/common/crossmodel/package_test.go
  apiserver/export_test.go
  apiserver/facades/client/controller/controller_test.go
  apiserver/offerauth.go
  apiserver/root.go
  apiserver/stateauthenticator/auth.go
  apiserver/stateauthenticator/authenticator_test.go
  apiserver/stateauthenticator/context.go
  apiserver/stateauthenticator/context_test.go
  apiserver/stateauthenticator/export_test.go
  apiserver/stateauthenticator/package_test.go
  apiserver/stateauthenticator/services_mock_test.go
  internal/worker/httpserverargs/authenticator.go
  internal/worker/httpserverargs/manifold.go
  internal/worker/httpserverargs/manifold_test.go
  internal/worker/httpserverargs/worker.go
  internal/worker/httpserverargs/worker_test.go
  juju/testing/apiserver.go
  state/bakerystorage.go
  state/bakerystorage/config.go
  state/bakerystorage/config_test.go
  state/initialize.go
Labels: 4.0

#17569 feat: charm domain service - initial scaffold
  core/charm/id.go
  core/charm/id_test.go
  core/charm/testing/testing.go
  domain/charm/errors/errors.go
  domain/charm/service/actions.go
  domain/charm/service/actions_test.go
  domain/charm/service/config.go
  domain/charm/service/config_test.go
  domain/charm/service/lxdprofile.go
  domain/charm/service/lxdprofile_test.go
  domain/charm/service/manifest.go
  domain/charm/service/manifest_test.go
  domain/charm/service/metadata.go
  domain/charm/service/metadata_test.go
  domain/charm/service/package_mock_test.go
  domain/charm/service/package_test.go
  domain/charm/service/service.go
  domain/charm/service/service_test.go
  domain/charm/types.go
Labels: 4.0

#17595 style: use SQLair in the lease domain
  domain/lease/doc.go
  domain/lease/state/state.go
  domain/lease/state/types.go
Labels: 4.0

#17594 fix(cmr): expose all controller addresses cross-controller
  apiserver/facades/controller/crosscontroller/crosscontroller_test.go
  apiserver/facades/controller/crosscontroller/mock_test.go
  apiserver/facades/controller/crosscontroller/package_test.go
  apiserver/facades/controller/crosscontroller/register.go
Labels: 3.4

#17597 fix(charm): icmp open-port not supported on caas
  apiserver/facades/agent/uniter/uniter.go
  apiserver/facades/agent/uniter/uniter_test.go
Labels: 3.5

#17603 chore: move jujud-controller back into jujud for 3.6
  Makefile
  cmd/jujud-controller/agent/agent_test.go
  cmd/jujud-controller/agent/engine_test.go
  cmd/jujud-controller/agent/machine.go
  cmd/jujud-controller/agent/machine/manifolds.go
  cmd/jujud-controller/agent/machine/manifolds_test.go
  cmd/jujud-controller/agent/machine/package_test.go
  cmd/jujud-controller/agent/machine/startupmanifold.go
  cmd/jujud-controller/agent/machine/startupmanifold_test.go
  cmd/jujud-controller/agent/machine_test.go
  cmd/jujud-controller/agent/mocks/machine_mock.go
  cmd/jujud-controller/agent/package_test.go
  cmd/jujud-controller/agent/util_test.go
  cmd/jujud-controller/main.go
  cmd/jujud/agent/bootstrap.go
  cmd/jujud/agent/bootstrap_test.go
  cmd/jujud/agent/caasoperator.go
  cmd/jujud/agent/controllercharm.go
  cmd/jujud/agent/engine_test.go
  cmd/jujud/agent/machine.go
  cmd/jujud/agent/machine/manifolds.go
  cmd/jujud/agent/machine/manifolds_test.go
  cmd/jujud/agent/machine/stateflag.go
  cmd/jujud/agent/machine_test.go
  cmd/jujud/agent/model/agent.go
  cmd/jujud/agent/model/agent_test.go
  cmd/jujud/agent/model/errors.go
  cmd/jujud/agent/model/errors_test.go
  cmd/jujud/agent/model/manifolds.go
  cmd/jujud/agent/model/manifolds_test.go
  cmd/jujud/agent/model/package_test.go
  cmd/jujud/agent/mongo_test.go
  cmd/jujud/agent/util_test.go
  cmd/jujud/main.go
  cmd/package_test.go
  environs/tools/build.go
  juju/names/names.go
  snap/snapcraft.yaml
Labels: 3.6

#17610 refactor: machine id to machine name
  core/machine/machine.go
  core/machine/machine_test.go
Labels: 4.0

#17605 fix: migrate 3.6 to 4.0
  api/agent/meterstatus/client.go
  api/agent/meterstatus/client_test.go
  api/agent/uniter/unit.go
  api/agent/uniter/unit_test.go
  api/agent/uniter/uniter.go
  api/agent/uniter/uniter_test.go
  api/apiclient.go
  api/apiclient_test.go
  api/common/unitstate.go
  api/common/upgradeseries.go
  api/common/watch.go
  apiserver/admin_test.go
  worker/meterstatus/manifold.go
  worker/meterstatus/manifold_test.go
  worker/metrics/sender/manifold.go
  worker/metrics/sender/manifold_test.go
  worker/uniter/runner/context/contextfactory.go
Labels: 3.6

#17470 feat(secrets): implement watch revisions to prune
  api/controller/usersecrets/client.go
  api/controller/usersecrets/client_test.go
  apiserver/facades/controller/usersecrets/mocks/service.go
  apiserver/facades/controller/usersecrets/package_test.go
  apiserver/facades/controller/usersecrets/register.go
  apiserver/facades/controller/usersecrets/secrets.go
  apiserver/facades/controller/usersecrets/secrets_test.go
  apiserver/facades/controller/usersecrets/service.go
  apiserver/facades/schema.json
  core/watcher/watchertest/notify.go
  domain/secret/service/delete.go
  domain/secret/service/delete_test.go
  domain/secret/service/package_test.go
  domain/secret/service/service.go
  domain/secret/service/service_test.go
  domain/secret/service/state_mock_test.go
  domain/secret/service/watcher.go
  domain/secret/service/watcher_mock_test.go
  domain/secret/service/watcherfactory_mock_test.go
  domain/secret/state/state.go
  domain/secret/state/state_test.go
  domain/secret/watcher_test.go
  internal/worker/secretspruner/mocks/worker_mock.go
  internal/worker/secretspruner/worker.go
  internal/worker/secretspruner/worker_test.go
Labels: 4.0

#17568 fix(openstack): fix model sec group misconfiguration
  provider/openstack/firewaller.go
  provider/openstack/local_test.go
  provider/openstack/provider.go
Labels: 3.4

#17604 feat: key updater domain
  domain/keymanager/service/service.go
  domain/keyupdater/doc.go
  domain/keyupdater/service/controllerkey.go
  domain/keyupdater/service/controllerkey_mock_test.go
  domain/keyupdater/service/controllerkey_test.go
  domain/keyupdater/service/package_test.go
  domain/keyupdater/service/service.go
  domain/keyupdater/service/service_mock_test.go
  domain/keyupdater/service/service_test.go
  domain/schema/model.go
  domain/schema/model/sql/0002-changelog-namespaces.sql
  domain/schema/model/triggers/user-public-ssh-key.gen.go
  domain/schema/schema_test.go
  internal/ssh/authorisedkey.go
Labels: 4.0
