Repository juju/juju, pull requests merged in 2024-10, with the labels that each got.

#18239 chore: merge 3.1 to 3.4
  .github/api-client-allowed-list.txt
  .github/golangci-lint.config.yaml
  .github/workflows/gen.yml
  .github/workflows/static-analysis.yml
  CONTRIBUTING.md
  cmd/jujud/agent/machine.go
  go.mod
  go.sum
  scripts/juju-mongotop/go.mod
  snap/snapcraft.yaml
  tests/README.md
  tests/suites/static_analysis/lint_go.sh
Labels: 3.4

#18240 chore: merge 3.4 to 3.5
  .github/golangci-lint.config.yaml
  go.mod
  go.sum
  scripts/juju-mongotop/go.mod
Labels: 3.5

#18241 chore: merge 3.5 to 3.6
  apiserver/apiserver.go
  apiserver/apiserver_test.go
  apiserver/debuglog.go
  apiserver/debuglog_db.go
  apiserver/debuglog_db_internal_test.go
  go.mod
  go.sum
  state/address.go
  state/applicationoffers.go
  state/applicationoffers_test.go
  state/modeloperation.go
  state/package_test.go
  state/pool.go
  state/relation.go
  testcharms/charms/refresher/charmcraft.yaml
  tests/suites/refresh/switch.sh
Labels: 3.6

#18248 test: lengthen timeouts on controllercharm tests
  tests/suites/controllercharm/prometheus.sh
Labels: 3.6

#18231 Merge 3.6 to main
  .github/commitlint.config.mjs
  .github/workflows/microk8s-tests.yml
  .github/workflows/static-analysis.yml
  apiserver/apiserver.go
  apiserver/common/crossmodel/crossmodel.go
  apiserver/debuglog.go
  apiserver/debuglog_tailer.go
  caas/kubernetes/provider/application/application.go
  caas/kubernetes/provider/application/application_test.go
  caas/kubernetes/provider/application/spec36_test.go
  go.mod
  go.sum
  internal/worker/dbaccessor/tracker.go
  internal/worker/dbaccessor/tracker_test.go
  state/address.go
  state/applicationoffers.go
  state/modelmigration.go
  state/modeloperation.go
  state/pool.go
  state/relation.go
  testcharms/charms/refresher/charmcraft.yaml
  tests/includes/verbose.sh
  tests/main.sh
  tests/suites/cli/local_charms.sh
  tests/suites/controllercharm/prometheus.sh
  tests/suites/refresh/switch.sh
Labels: 4.0
