Repository juju/juju, pull requests merged in 2025-03, with the labels that each got.

#19179 docs: update releases and roadmap docs
  docs/user/reference/juju/juju-roadmap-and-releases.md
Labels: 3.6

#19139 docs: update juju management
  docs/user/howto/manage-juju.md
Labels: 3.6

#19155 fix(docs): update broken url for metrics collection from Juju controller
  docs/user/tutorial.md
Labels: 3.6

#19215 docs: fix PR template link for conventional-commits.md
  PULL_REQUEST_TEMPLATE.md
Labels: 3.6

#19279 chore: bump github.com/golang-jwt/jwt/v5 from 5.2.1 to 5.2.2
  go.mod
  go.sum
Labels: 2.9

#19337 chore: remove mongo profile
  agent/agent.go
  agent/format-2.0.go
  caas/kubernetes/provider/bootstrap.go
  cmd/containeragent/initialize/config.go
  cmd/jujud-controller/agent/agenttest/agent.go
  cmd/jujud-controller/agent/bootstrap.go
  cmd/jujud-controller/util/util.go
  cmd/jujud/agent/agenttest/agent.go
  controller/config.go
  controller/config_test.go
  controller/configschema.go
  docs/user/reference/configuration/list-of-controller-configuration-keys.md
  docs/user/reference/juju-cli/list-of-juju-cli-commands/bootstrap.md
  docs/user/reference/juju-cli/list-of-juju-cli-commands/controller-config.md
  internal/cloudconfig/podcfg/podcfg.go
  internal/mongo/mongo.go
  internal/mongo/service.go
  internal/mongo/service_test.go
  internal/upgrade/agent_mock_test.go
  internal/upgradesteps/agent_mock_test.go
  internal/worker/agentconfigupdater/manifold.go
  internal/worker/agentconfigupdater/manifold_test.go
  internal/worker/agentconfigupdater/worker.go
  internal/worker/agentconfigupdater/worker_test.go
  internal/worker/auditconfigupdater/agent_mock_test.go
  internal/worker/bootstrap/agent_mock_test.go
  internal/worker/containerbroker/mocks/agent_mock.go
  internal/worker/instancemutater/mocks/agent_mock.go
  internal/worker/objectstore/agent_mock_test.go
  internal/worker/stateconverter/mocks/agent_mock.go
  internal/worker/trace/agent_mock_test.go
  internal/worker/upgradedatabase/agent_mock_test.go
  internal/worker/upgradesteps/agent_mock_test.go
  internal/worker/upgradestepsmachine/agent_mock_test.go
  tests/suites/controller/mongo_memory_profile.sh
  tests/suites/controller/task.sh
Labels: 4.0

#19341 chore: remove mongo logging
  cmd/internal/agent/agentconf/agentconf.go
  internal/worker/logger/logger.go
  state/mgo/logger.go
Labels: 4.0

#19342 chore: remove leadership from state
  state/leadership.go
  state/settings_op.go
  state/status.go
Labels: 4.0
