Repository juju/juju, pull requests merged in 2025-02, with the labels that each got.

#18772 chore: merge 3.5.6 to 3.5
  provider/azure/environ.go
  provider/azure/environ_test.go
  provider/azure/instancetype.go
  provider/azure/internal/errorutils/errors.go
  provider/azure/internal/errorutils/errors_test.go
  provider/azure/internal/imageutils/images.go
  provider/azure/internal/imageutils/images_test.go
Labels: 3.5

#18982 chore: remove left over log critical message
  state/secrets.go
Labels: 3.6

#18970 fix(apiserver): avoid splitting untrusted data
  apiserver/stateauthenticator/auth.go
Labels: 2.9

#19021 chore: update dependencies + cleanup github actions
  .github/workflows/build.yml
  .github/workflows/cla.yml
  .github/workflows/client-tests.yml
  .github/workflows/gen.yml
  .github/workflows/license.yml
  .github/workflows/merge.yml
  .github/workflows/microk8s-tests.yml
  .github/workflows/smoke.yml
  .github/workflows/snap.yml
  .github/workflows/static-analysis.yml
  .github/workflows/terraform-smoke.yml
  .github/workflows/update-brew-formulae.yml
  .github/workflows/upgrade.yml
  go.mod
  go.sum
Labels: 2.9
