Repository juju/juju, pull requests merged in 2025-06, with the labels that each got.

#19879 chore: bump Pebble version to v1.19.2
  go.mod
  go.sum
Labels: 3.6

#19920 chore: bump go to 1.24.4
  .gitignore
  go.mod
  go.sum
Labels: 2.9

#19921 chore: bump go to 1.24.4
  .gitignore
  go.mod
  go.sum
Labels: 3.6

#19946 chore: remove various unused legacy state logic
  state/application.go
  state/settings.go
  state/state.go
  state/status.go
  state/storage.go
  state/unit.go
Labels: 4.0

#19960 chore: remove legacy state from actions client facade
  apiserver/facades/client/action/action.go
  apiserver/facades/client/action/interface.go
  apiserver/facades/client/action/operation.go
  apiserver/facades/client/action/package_mock_test.go
  apiserver/facades/client/action/package_test.go
  apiserver/facades/client/action/register.go
  apiserver/facades/client/action/run.go
  apiserver/facades/client/action/run_test.go
  apiserver/facades/client/action/state_mock_test.go
  state/action.go
  state/operation.go
  state/sequence.go
  state/state.go
Labels: 4.0

#19996 chore: delete legacy state upgrades module
  state/upgrades.go
Labels: 4.0

#19995 chore: remove state/migrations package
  state/migrations/doc.go
  state/migrations/firewallrules.go
  state/migrations/relationnetworks.go
Labels: 4.0

#20008 fix: deadlock in event multiplexer dispatch timeout/unsubscribe
  internal/changestream/eventmultiplexer/eventmultiplexer_test.go
  internal/changestream/eventmultiplexer/subscription.go
  internal/changestream/eventmultiplexer/subscription_test.go
Labels: 4.0

#20005 feat: stub uniter action watcher in domain
  apiserver/facades/agent/uniter/service.go
  apiserver/facades/agent/uniter/service_mock_test.go
  apiserver/facades/agent/uniter/uniter.go
  apiserver/facades/agent/uniter/uniter_legacy_test.go
  domain/application/service/actions.go
Labels: 4.0

#20004 feat: get app+unit life in life facades from application domain
  api/agent/lifeflag/client.go
  api/agent/lifeflag/facade.go
  api/agent/lifeflag/facade_test.go
  api/controller/lifeflag/client.go
  api/facadeversions.go
  apiserver/allfacades.go
  apiserver/common/life.go
  apiserver/common/life_test.go
  apiserver/common/mocks/common_mock.go
  apiserver/facades/agent/lifeflag/facade.go
  apiserver/facades/agent/machine/machiner.go
  apiserver/facades/agent/machine/package_mock_test.go
  apiserver/facades/agent/storageprovisioner/service.go
  apiserver/facades/agent/storageprovisioner/service_mock_test.go
  apiserver/facades/controller/firewaller/interface.go
  apiserver/facades/controller/firewaller/service_mock_test.go
  apiserver/facades/controller/instancepoller/service.go
  apiserver/facades/controller/lifeflag/facade.go
  apiserver/facades/controller/lifeflag/facade_test.go
  apiserver/facades/controller/lifeflag/package_test.go
  apiserver/facades/controller/lifeflag/register.go
  apiserver/facades/controller/lifeflag/service_mock_test.go
  apiserver/facades/controller/lifeflag/util_test.go
  apiserver/facades/controller/lifeflag/watcher_registry_mock_test.go
  domain/application/service/service.go
  domain/application/watcher_test.go
  internal/worker/lifeflag/worker.go
  internal/worker/lifeflag/worker_test.go
Labels: 4.0

#20026 chore: remove legacy state from API server authenticators
  apiserver/admin_test.go
  apiserver/authentication/agent.go
  apiserver/export_test.go
  apiserver/stateauthenticator/auth.go
  apiserver/stateauthenticator/authenticator_test.go
  apiserver/stateauthenticator/context.go
  apiserver/stateauthenticator/context_integration_test.go
  apiserver/stateauthenticator/context_test.go
  apiserver/stateauthenticator/services_mock_test.go
  internal/worker/httpserverargs/authenticator.go
  juju/testing/apiserver.go
Labels: 4.0

#20052 chore: remove Sequences method from state
  apiserver/facades/client/modelconfig/backend.go
  apiserver/facades/client/modelconfig/modelconfig.go
  apiserver/facades/client/modelconfig/modelconfig_test.go
  apiserver/facades/client/modelconfig/register.go
  state/sequence.go
Labels: 4.0

#20045 chore: remove various unused Mongo-based assets
  scripts/dialmongo.bash
  scripts/juju-mongotop/Makefile
  scripts/juju-mongotop/README.md
  scripts/juju-mongotop/go.mod
  scripts/juju-mongotop/go.sum
  scripts/juju-mongotop/main.go
  scripts/mgo-run-txn/main.go
  scripts/mgo-run-txn/test-increment.json
  scripts/mgo-run-txn/test-insert.json
  scripts/mgo-run-txn/test-update.json
  state/errors.go
  state/model.go
  state/stateenvirons/config.go
  state/stateenvirons/doc.go
  state/watcher/doc.go
Labels: 4.0

#19898 docs: fix loal typo
  cmd/juju/application/deploy.go
  cmd/juju/resource/upload.go
  docs/reference/juju-cli/list-of-juju-cli-commands/attach-resource.md
  docs/reference/juju-cli/list-of-juju-cli-commands/deploy.md
Labels: 4.0

#20071 feat: network domain state methods for DevicesToBridge
  domain/network/service/container.go
  domain/network/state/container.go
  domain/network/state/container_test.go
  domain/network/state/package_test.go
  domain/network/state/types.go
Labels: 4.0
